### ISSUE TITLE
DOMA: consider clearing VALPOS

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#1053]
If the domain contains a lot of fixed values, and then inserting a new value in the top, it will trigger a very long diff due to the VALPOS field.

The value position is implicitly part of the XML, so we should consider clearing the VALPOS field

**Comment by ibnbr** [comment]
This maybe impact on this code, because it's use VALPOS.

```abap
      lt_dd07v_tmp = it_dd07v.
      LOOP AT lt_dd07v_tmp ASSIGNING <ls_dd07v>.
        READ TABLE lt_dd07_texts ASSIGNING <ls_dd07_text>
          WITH KEY ddlanguage = <lv_lang> valpos = <ls_dd07v>-valpos.
        CHECK sy-subrc = 0. " ! no translation -> master translation remain (maybe not OK)
        MOVE-CORRESPONDING <ls_dd07_text> TO <ls_dd07v>.
        DELETE lt_dd07_texts INDEX sy-tabix. " Optimization
      ENDLOOP.
```

I tried to create some test to analyze, but nothing I did goes through this part of the code.

What's I18N_TEXT on DOMA? I translated the doma texts but don't generated this files.

**Comment by ibnbr** [comment]
I got it.

I think we can change the READ using DOMVALUE_L and DOMVALUE_H instead of VALPOS.

**Comment by sbcgua** [comment]
@ibnbr example of DOMA translation
![image](https://user-images.githubusercontent.com/15635498/66894324-c48ccb00-eff8-11e9-80f5-e4f50f94cf44.png)

**Comment by larshp** [comment]
Suggest this approach: 

add the code to fill the empty values now -> PR #3083

In 4(?) months: add the code that clears the fields

This way users will have a chance to update to latest abapGit, and we can avoid some problems

**Comment by mbtools** [comment]
It's been >7 months ;-)

**Comment by larshp** [comment]
todo: clearing VALPOS

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/pull/4283 serializes and deserializes everything properly. I don't think a "large diff" when inserting a value is a problem. It won't happen often, and it will be very obvious that only the VALPOS numbering has changed.

**Comment by larshp** [comment]
Developer A inserts a value at position 10, developer B inserts a value at position 20, in separate pull requests, this will lead to conflicts with VALPOS, without VALPOS in the XML it might be possible to merge it

tho, it might not be something that happens often, if there is a lot of changes in a DOMA a value table might be the right thing to use

**Comment by larshp** [comment]
closing, no progress
