### ISSUE TITLE
Reset local: Delete unnecessary objects deletes class accidentialy instead of include

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#1066]
Currently we have the feature within reset local to delete unnecessary objects. It seems that different class includes and probably more isn't handled correctly.

E.g. consider this test repo.
https://gitlab.com/christianguenter/bug_reset_local.git

Herein we have two branches, master and add_include.

In master we have just an empty class.
![image](https://user-images.githubusercontent.com/17437789/33146055-0eea1cfa-cfc3-11e7-8cdc-61a9499f9fbb.png)

In add_include we added the 'Class-relevant Local Types' include
![image](https://user-images.githubusercontent.com/17437789/33145765-f4c16dc0-cfc1-11e7-95c2-2d7b61871741.png)

When we now switch back from branch add_include to master we see it as follow in abapGit.
![image](https://user-images.githubusercontent.com/17437789/33145843-3c3d5682-cfc2-11e7-9c83-766d1e5bac10.png)
![image](https://user-images.githubusercontent.com/17437789/33145840-376ab640-cfc2-11e7-8b56-27c6cf36624e.png)˙

If we now 'reset local' erroneously the popup to delete unnecessary objects appears. Although the class exists in local and remote repo and therefore shouldn't be deleted.  
![image](https://user-images.githubusercontent.com/17437789/33145920-79e0ab9c-cfc2-11e7-861a-30ee317a71f5.png)

If we select the class and press ok the whole class is deleted, if we press no nothing happens and the superflous include isn't removed.

Imho the desired behaviour is that the include is removed?

There unnecessary objects are determined here.
https://github.com/larshp/abapGit/blob/c5158bb3330a75141e8ab7bf3be852dcc32ecaa2/src/zabapgit_repo_impl.prog.abap#L325-L367

**Comment by christianguenter2** [comment]
After the class is deleted the repo is deserialized and then class is created again. So it's usually not a problem but a bit ugly. 
It's only a real issue for abapGit repo as its self modifying and gives shortdumps during the deserialization. Workaround is then to use the self containing abapGit report to reset the abapGit repo.

**Comment by larshp** [comment]
@christianguenter2 try again, this should be solved with https://github.com/abapGit/abapGit/pull/4510

**Comment by christianguenter2** [comment]
Works 👍
