### ISSUE TITLE
TABL: foreign key inherited from .INCLUDE not set at pull

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#1079]
The TABL should inherit the foreign key from the .INCLUDE, as in the remote. Clicking pull does not set the foreign key inheritance.

![image](https://user-images.githubusercontent.com/5888506/34432678-e716562a-ec79-11e7-8fbd-9fbd75cf9304.png)

![image](https://user-images.githubusercontent.com/5888506/34432683-f09ec768-ec79-11e7-95aa-9d4159b3fad1.png)

![image](https://user-images.githubusercontent.com/5888506/34432685-f60ec068-ec79-11e7-92c1-5b0287d3847f.png)

**Comment by larshp** [comment]
How will it know, the data is removed in serialization, https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_tabl.prog.abap#L306

**Comment by mbtools** [comment]
Ran a test. When adding a foreign key relationship to the include and activating it, the DB table will automatically inherit the foreign key (existing data could be inconsistent but that's a different issue). 

The definition of the foreign key is only part of the include and *not* in the XML of the table. There's already a test repo:
https://github.com/abapGit-tests/TABL_foreign_key
