### ISSUE TITLE
Annoying Logon language different than the original popup

### ISSUE THREAD

**Issue by Zeatynis** [abapGit/abapGit#1175]
When importing zip I have to click this popup for every object 👎 

![image](https://user-images.githubusercontent.com/9119187/35408809-c2b5de52-0210-11e8-9bcf-6458f0abc230.png)

Is there anything you could do to achieve something like "set for all" ?
In my case original language is english and logon is polish.

**Comment by larshp** [comment]
and original language is German

what is the master language of the repository? see the .abapgit.xml file

**Comment by Dave94** [comment]
Polish:
<MASTER_LANGUAGE>L</MASTER_LANGUAGE>

**Comment by Dave94** [comment]
I log on with polish language and my repo is in polish.
I update existing objects which have been created before on target system when logged in english.

**Comment by esjewett** [comment]
I think this is the same issue, no? https://github.com/uweku/mockA/issues/18

Is there are reason ABAPGit can't just adjust the master language to match the login language during import?

**Comment by larshp** [comment]
It could, but if the text is in German, and then adjusting to English login, then the German text will end up indicated as English?

Some of the APIs uses the login language as master language

**Comment by esjewett** [comment]
Yeah, it's a problem, good point 😬 Is there any way to just suppress the warning? I mean, obviously I want to maintain everything in my logon language and if a text gets supplied from the original language that is fine, right? Anyway, just saw the issue over on mocka and thought it seemed like something that would be relevant to ABAPGit.

**Comment by Dave94** [comment]
Great would be if there were button "english for all" or something like that :D Those popups slow the pull process majorly.

**Comment by larshp** [comment]
logon in the original language?

**Comment by Dave94** [comment]
hmm?
You ask or propose a solution?

**Comment by mbtools** [comment]
trying to bring this to a conclusion: in the case mentioned here, the objects existed already in the system in a different original language (German) than the repo (Polish). Imho, the popups can be avoided by uninstalling the existing objects (logon in German or English) and then reinstalling the repo (login in Polish). I suggest closing this issue.
