### ISSUE TITLE
Error: The class "ZCX_ABAPGIT_EXCEPTION" was not derived from either "CX_STATIC_CHECK" or "CX_DYNAMIC_CHECK".	

### ISSUE THREAD

**Issue by kartefact** [abapGit/abapGit#1273]
Hi,

I was trying to setup ABAPGIT on one of our systems and when I try to pull the latest version on ZABAPGIT package, I get the error:
The class "ZCX_ABAPGIT_EXCEPTION" was not derived from either "CX_STATIC_CHECK" or "CX_DYNAMIC_CHECK".	

System Details:
![image](https://user-images.githubusercontent.com/3407499/37917910-4f803c50-313d-11e8-88e0-c3ceee803ba9.png)

What could be the problem?

There were other problems in 702 which I manually commented out. Do we have a fork/branch specifically for 702? 

P.S. I'm a novice to this, so pardon me if my questions are silly.

**Comment by larshp** [comment]
Are you using the long copy/paste report or the development version? Can you add a screenshot of the syntax error?

**Comment by kartefact** [comment]
I initially used the long copy/paste report. Then ran the program and it found differences from the remote repo. I did a pull and it asked me for overwriting the program and activation. I said yes and when trying to activate, the program terminated due to the method update_meta which I commented out. Then copy+pasted the code again and repeated all the steps. Now I get this error:
![image](https://user-images.githubusercontent.com/3407499/37920389-5a0977a2-3144-11e8-8b57-3a4ab23a6d85.png)

**Comment by larshp** [comment]
hmm, how does ZCX_ABAPGIT_EXCEPTION look in SE24?

**Comment by kartefact** [comment]
![image](https://user-images.githubusercontent.com/3407499/37922363-f73d922e-3149-11e8-8c4b-a15ab4e8a4eb.png)

All tabs except the following are empty:
![image](https://user-images.githubusercontent.com/3407499/37922546-71f16dec-314a-11e8-9374-7d9c2e72fd36.png)


Code view:

` CLASS zcx_abapgit_exception DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  CREATE PUBLIC.`

`  PUBLIC SECTION.
    INTERFACES:
      if_t100_message.
    CLASS-METHODS: `
     ` "! Raise exception with text `
     ` "! @parameter iv_text | Text `
     ` "! @parameter ix_previous | Previous exception `
     ` "! @raising zcx_abapgit_exception | Exception `
     ` raise IMPORTING iv_text     TYPE clike
                      ix_previous TYPE REF TO cx_root OPTIONAL
            RAISING   zcx_abapgit_exception,`
      ` "! Raise exception with T100 message`
      ` "! <p>`
      ` "! Will default to sy-msg* variables. These need to be set right before calling this method.`
      ` "! </p>`
      ` "! @parameter iv_msgid | Message ID`
      ` "! @parameter iv_msgno | Message number`
      ` "! @parameter iv_msgv1 | Message variable 1`
      ` "! @parameter iv_msgv2 | Message variable 2`
      ` "! @parameter iv_msgv3 | Message variable 3`
      ` "! @parameter iv_msgv4 | Message variable 4`
      ` "! @raising zcx_abapgit_exception | Exception`
      ` raise_t100 IMPORTING VALUE(iv_msgid) TYPE symsgid DEFAULT sy-msgid
                           VALUE(iv_msgno) TYPE symsgno DEFAULT sy-msgno
                           VALUE(iv_msgv1) TYPE symsgv DEFAULT sy-msgv1
                           VALUE(iv_msgv2) TYPE symsgv DEFAULT sy-msgv2
                           VALUE(iv_msgv3) TYPE symsgv DEFAULT sy-msgv3
                           VALUE(iv_msgv4) TYPE symsgv DEFAULT sy-msgv4
                 RAISING   zcx_abapgit_exception . '
`     METHODS: `
     ` constructor  IMPORTING textid ` ` LIKE if_t100_message=>t100key OPTIONAL `
`                             previous LIKE previous OPTIONAL
                             msgv1    TYPE symsgv OPTIONAL
                             msgv2    TYPE symsgv OPTIONAL
                             msgv3    TYPE symsgv OPTIONAL
                             msgv4    TYPE symsgv OPTIONAL. `
` DATA:`
    ` subrc TYPE sysubrc READ-ONLY,
      msgv1 TYPE symsgv READ-ONLY,
      msgv2 TYPE symsgv READ-ONLY,
      msgv3 TYPE symsgv READ-ONLY,
      msgv4 TYPE symsgv READ-ONLY.  `



` PRIVATE SECTION.
    CONSTANTS:
      gc_generic_error_msg TYPE string VALUE 'An error occured (ZCX_ABAPGIT_EXCEPTION)' ##NO_TEXT.`

**Comment by flaiker** [comment]
That seems very bizarre. I have many questions....
Does the syntax check say anything in SE24 for ZCX_ABAPGIT_EXCEPTION? Can you activate that class again? Is the source code your pasted here the active one or inactive? Where did you copy that source code from (SE24 doesn't support source code based view for exception classes afaik, so eclipse?)?

Just to reproduce the situation:
- You copy pasted the all in one report from github into a new report ZABAPGIT.
- You changed some lines so that you were able to activate it on 702.
- You then executed the report and cloned the abapGit repository into that same package, causing it to detect report ZABAPGIT to be changed on remote and many objects missing.
- You then pressed pull and activated all the objects overriding the report ZABAPGIT with the development version.
- There was an error because of one of the backporting changes.
- You now have like half the objects of the online version of abapGit because the installation process aborted at some point.
- You copy pasted the all in one report again into the now development version of report ZABAPGIT
?

You also seem to have both $ABAPGIT and ZABAPGIT as packages?

When I install abapGit I normally do it like this:
- Copy paste the all in one report into ZABAPGITDEPL in $TMP
- Do the whole SSL configuration thing
- Run ZABAPGITDEPL, clone larshp/abapGit into ZABAPGIT

I install the copy-paste version with a different name so abapGit doesn't change its own source code while it's pulling the development version.

**Comment by kartefact** [comment]
My answers below:

Does the syntax check say anything in SE24 for ZCX_ABAPGIT_EXCEPTION? 
Ans: Yes, it says that the constructor is inconsistent and offers to cleanup.

Can you activate that class again? Is the source code your pasted here the active one or inactive? 
Ans: Yes, it was in the active state. I activated it again and it got activated fine. No errors.

Where did you copy that source code from (SE24 doesn't support source code based view for exception classes afaik, so eclipse?)?
Ans: No, I got the code from SE24 by clicking the "Public section" button.

Just to reproduce the situation:
You copy pasted the all in one report from github into a new report ZABAPGIT.
You changed some lines so that you were able to activate it on 702.
You then executed the report and cloned the abapGit repository into that same package, causing it to detect report ZABAPGIT to be changed on remote and many objects missing.
You then pressed pull and activated all the objects overriding the report ZABAPGIT with the development version.
There was an error because of one of the backporting changes.
You now have like half the objects of the online version of abapGit because the installation process aborted at some point.
You copy pasted the all in one report again into the now development version of report ZABAPGIT
?
Ans: Yes to all above.

You also seem to have both $ABAPGIT and ZABAPGIT as packages?
Ans: No. I just have $ABAPGIT package. 

When I install abapGit I normally do it like this:
Copy paste the all in one report into ZABAPGITDEPL in $TMP
Do the whole SSL configuration thing
Run ZABAPGITDEPL, clone larshp/abapGit into ZABAPGIT
I install the copy-paste version with a different name so abapGit doesn't change its own source code while it's pulling the development version.
Ans: Perhaps that's what I need to do. I was overwriting my version with the dev version from the online repo. I'll try this in the morning and get back.

**Comment by kartefact** [comment]
I tried the way you did @flaiker, and this is what I get when trying to activate the objects:

![image](https://user-images.githubusercontent.com/3407499/37960103-57d7b636-31d2-11e8-8a7a-918d5eb91a23.png)

**Comment by larshp** [comment]
can you try deleting ZCX_ABAPGIT_EXCEPTION manually, and manually create it again?

**Comment by kartefact** [comment]
Now I get a lot more errors:

![image](https://user-images.githubusercontent.com/3407499/37972606-53c60ad8-31f6-11e8-99c2-e745690d3a19.png)

**Comment by larshp** [comment]
Looks like it is one step further, as it now complains about the other exception classes.

In your previous screenshot, the superclass was missing, guess this is also the case for the other exception classes.
![image](https://user-images.githubusercontent.com/5888506/37978875-63bbc07c-31e7-11e8-88ac-18768c0c9d76.png)

method update_meta is important, we should try to figure out why it dumped in that method in the first place

**Comment by kartefact** [comment]
I put in the super class in all the exception classes and introduced the default_text method with its parameter manually and activated. It activated without problems. There are still some other syntax errors. Shall check them today.

**Comment by larshp** [comment]
okay, how which parameters does the constructor for class CL_OO_CLASS_SECTION_SOURCE have in your system?

looks like this is related to https://github.com/larshp/abapGit/issues/933

**Comment by kartefact** [comment]
![image](https://user-images.githubusercontent.com/3407499/38313895-aa46d53e-3842-11e8-94dd-b493eaea76ed.png)

**Comment by larshp** [comment]
Can you add it as a screenshot or simple TXT format? I do not know if RTF files can securely be opened or not

**Comment by kartefact** [comment]
Please find it attached in text format below:

[Dump.txt](https://github.com/larshp/abapGit/files/2250094/Dump.txt)

**Comment by larshp** [comment]
what version are you running? the code in the dump does not match the latest version, https://github.com/larshp/abapGit/blob/23ded859eab88ddb30f2729f3b9a79263a549bb8/src/objects/zcl_abapgit_oo_class_new.clas.abap#L177-L191

**Comment by larshp** [comment]
suggest changing the code in method `update_cs_number_of_methods` to the latest code manually

but please also open issues for the syntax errors, most of the abapGit developers does not have access to 702 systems to test on, so we rely on the community to open issues in order to have abapGit work on 702

**Comment by kartefact** [comment]
Thanks Lars. I shall try doing that.
I shall also try with the latest version and open new issues for them.
Regards,
Karthikeyan Ravikumar

**Comment by larshp** [comment]
See https://github.com/larshp/abapGit/blob/master/changelog.txt, a lot has happened since 1.62.0

abapGit should support 702, but it might take some time to get it right, just open an issue for downport, then we will take it step by step, one fix at a time

**Comment by larshp** [comment]
Okay, try copy pasting the code from https://github.com/larshp/abapGit/blob/master/src/zcx_abapgit_exception.clas.abap into the source based class editor manually to see if it works.

Also try isolating the issue, if the issue is only caused by the exception classes, try making a public repo with just one exception class to see if it can reproduce the problem.

**Comment by kartefact** [comment]
Note: I commented the code in the update_meta method ( Issue #933 which I was getting from the latest build of the report program) and pulled from the repo and I end up in this issue.

**Comment by larshp** [comment]
method `update_meta` is definitely required for class deserialization to work, back when #933 was created the code was work in progress and not activated, now it is productive code.

**Comment by kartefact** [comment]
Getting the attached dump when pulling without commenting the `update_meta` method.
[Dump.txt](https://github.com/larshp/abapGit/files/2269111/Dump.txt)

**Comment by larshp** [comment]
@kartefact try changing the code to https://github.com/larshp/abapGit/commit/91b10be0b48b40fde05d9392a7c195be0e75af4a

**Comment by kartefact** [comment]
The problem seems to be with only the exception classes. I added the superclass CX_STATIC_CHECK to the following classes manually:

ZCX_ABAPGIT_2FA_AUTH_FAILED
ZCX_ABAPGIT_2FA_COMM_ERROR
ZCX_ABAPGIT_2FA_DEL_FAILED
ZCX_ABAPGIT_2FA_ERROR 
ZCX_ABAPGIT_2FA_GEN_FAILED
ZCX_ABAPGIT_2FA_ILLEGAL_STATE
ZCX_ABAPGIT_2FA_UNSUPPORTED
ZCX_ABAPGIT_CANCEL
ZCX_ABAPGIT_EXCEPTION
ZCX_ABAPGIT_NOT_FOUND

Added GET_DEFAULT_TEXT method and RV_TEXT attribute to all the 2FA classes

then it activated after the pull, but still shows differences.

**Comment by larshp** [comment]
@kartefact did the code in https://github.com/larshp/abapGit/commit/91b10be0b48b40fde05d9392a7c195be0e75af4a work?

**Comment by kartefact** [comment]
@larshp Getting the following error when I try to pull the latest build from repo:

![image](https://user-images.githubusercontent.com/3407499/43826980-5112900c-9b16-11e8-9fb6-5048cfbbb60b.png)

**Comment by larshp** [comment]
for this you have to debug the scanner to see what the error is

**Comment by kartefact** [comment]
Ignore the above error. It was due to my mistake during copy paste. After correction, it was still having a problem with lo_update not being instantiated. Was dumping. I put a condition `IF lo_update IS BOUND` and now it is compiling fine. However, I get the same error as the title of this issue again.
Another thing that I forgot to mention (may be useful) is that I get a popup to choose the package for the exception classes when I pull. I don't get this for other classes.

**Comment by kartefact** [comment]
I tried the same on another 702 system. Following is what I did:

1. I applied the latest build of the long form program.
2. Executed and tried installing the abapGit repo. Program terminated with the update_meta method being the problem.
3. Applied the code from [91b10be](https://github.com/larshp/abapGit/commit/91b10be0b48b40fde05d9392a7c195be0e75af4a) manually and re-tried. Landed with Exception class errors.
4. Manually added the super class and the missing method and attribute to all the exception classes and activated only the exception classes.
5. Now tried pulling again. Everything pulls fine and shows as activated with success message, but the differences don't go away.
6. On checking the $ABAPGit package in SE80, I see that nothing is activated.

**Comment by kartefact** [comment]
Problem seems to be with the editor not activating the objects. Has anyone faced this before?

**Comment by mbtools** [comment]
I have retested the current AG **developer** version 1.100 on 702 and some issues remain:
1. Exceptions with super class `zcx_abapgit_exception` are not deserialized properly
![image](https://user-images.githubusercontent.com/59966492/97820333-b51c0680-1c7b-11eb-8e48-ddceb49013ba.png)
2. Diff related to class/interface serialization 
3. Warnings related to missing pragmas 

Solutions:
1. Under investigation
2. This is a known issue as discussed here https://github.com/abapGit/abapGit/issues/3741. The workaround is to use an exit for custom serializer.
3. Can be ignored

**Comment by mbtools** [comment]
Apparently, in 702 the constructor of exceptions is not inherited from the super-class. However, during deserialize, it creates an implementation for the constructor *and* the system generates a new constructor. Since we can't stop the generation (in 702), I think a custom serializer is again the answer, unfortunately.

**Comment by larshp** [comment]
hmm
