### ISSUE TITLE
AVAS	Classification

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#1360]
Serialization and deserialization for AVAS Classification

package SPAK_TOOL_CLASSIFICATION?

**Comment by larshp** [comment]
can probably be done with class CL_CLS_ATTR_VALUE_ASSIGNMENT, similar to https://github.com/larshp/abapGit/pull/1513

**Comment by jfilak** [comment]
The SOBJ serialization (abapGit-plugins) for AVAS objects work well, only the deserialization does not write TADIR.

**Comment by jfilak** [comment]
Also the key should be the uuid because it is subject to change. I think the uuid can be ignored, because in our landscape we sometimes need to "re-create" an AVAS object for an report in an older releases - so it gets a new uuid, which is overwritten during the next upgrade.

**Comment by larshp** [comment]
I would like to deprecate abapGit-plugins, as it is not really clear if it works or not. In this case the TADIR entry is missing.

Moving it to a real object makes sure it is tested, and we can do fixes for it.

Also see https://github.com/larshp/abapGit/issues/1449

**Comment by larshp** [comment]
Future actions/questions:

* AVAS stores the name of the DEVC objects, but in abapGit it does not necessarily have the same name. Perhaps assume that DEVC classifications are always in the package, as LOCAL and HOME objects will never be serialized in abapGit
* I'm not sure how Linked Objects works in SCLAS, so this has not been implemented

**Comment by mbtools** [comment]
`AVAS` is supported. If someone needs additional features of it, they can open a new issue.
