### ISSUE TITLE
DCLS: deserialize fails if gtadir already exists

### ISSUE THREAD

**Issue by jfilak** [abapGit/abapGit#1469]
The function tadir_insert do not check if the object exists in gtadir and if it exists, the call dies with an error.
Unfortunately, the method cl_dd_utilities=>write_tadir do not accept DCLS but we can copy the approach.

If gtadir exists and we skip tadir_inser in DCLS~deserialize, the corresponding tadir entry is created during activation.

**Comment by larshp** [comment]
I think GTADIR is used only inside SAP, so its not easy to reproduce in normal systems

pull requests welcome

**Comment by mbtools** [comment]
If SAP wants this fixed, please create a PR since no one else is using GTADIR feature. Closing.
