### ISSUE TITLE
Objects are not moved to new package after switching branches

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#1483]
Same scenario as in #1482 

If I install the test [repo](https://gitlab.com/christianguenter/test_move_package) branch master and pull. Then switch to branch new_package where the class is moved to a subpackage, it's not possible to pull respectively pull does nothing. The class isn't moved to the subpackage and still a diff is shown.
![image](https://user-images.githubusercontent.com/17437789/41200509-01e774dc-6ca6-11e8-945b-0b6d53dfe96a.png)
 
![image](https://user-images.githubusercontent.com/17437789/41200524-5d865ace-6ca6-11e8-80b3-a16392ed1e07.png)

![image](https://user-images.githubusercontent.com/17437789/41200525-5ee3fa16-6ca6-11e8-8a4a-5711a608b422.png)

Expected behaviour: class is moved to subpackage.

**Comment by larshp** [comment]
some previous work by @EduardoCopat, see https://github.com/larshp/abapGit/pull/1007

**Comment by christianguenter2** [comment]
Seems that #1482 fixed this too. Although it's still not possible to pull after switching branches 'reset local' does the job. That's ok for me. I'll close.

**Comment by christianguenter2** [comment]
Thought this one is fixed, but it seems not.

Test case https://gitlab.com/christianguenter/test_package.git

- Clone master
- Switch to branch subpackage
- neither pull nor reset local moves the class in the subpackage

**Comment by mbtools** [comment]
I can reproduce it. However, the subpackage branch is not consistent and contains the class ZCL_Z_TEST_PACKAGE class twice. I suspect that's why abapGit can't properly assign the class to the sub-package. We should test again, after you remove the class from the main package (branch subpackage/src).

**Comment by christianguenter2** [comment]
After removing the files from main package everything works as expected. Closing.
![grafik](https://user-images.githubusercontent.com/17437789/148026196-48cb07ed-4e15-4b85-88fb-b1df7605850a.png)
