### ISSUE TITLE
CMOD	Customer enhancement projects

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#151]
function modules
MOD_KUN_ACTIVATE
MOD_KUN_DELETE

**Comment by larshp** [comment]
hmm, this seems difficult, however it might already work via https://github.com/larshp/abapGit-Plugins


Notes:
* looking at function module MOD_KUN_RENAME it seems that only database table MODACT + MODATTR + MODTEXT are relevant
* include LSMODF0K, FORM modify_modact
* include LSMODF0K, FORM modify_modattr
* function module AFTER_IMP_CMOD

**Comment by mbtools** [comment]
Close because newer releases don't support it anyway?

**Comment by flaiker** [comment]
Source?

You cannot create new enhancements using SMOD but you should still be able to implement existing ones in CMOD. Is that not the case?

**Comment by mbtools** [comment]
SAP is transitioning to enhancement spots. This was done for BW/4HANA https://launchpad.support.sap.com/#/notes/2462639 (no more CMODs available). You can of course still implement those that still exist. However, I think for most (all?) SMODs there are equivalent BAdIs or enhancement spots available.

**Comment by larshp** [comment]
lets try closing it 🤷‍♂️

**Comment by mbtools** [comment]
Someone might want it... https://github.com/abapGit/abapGit/pull/3947 🤷‍♂️

**Comment by larshp** [comment]
😁

**Comment by flaiker** [comment]
> SAP is transitioning to enhancement spots. This was done for BW/4HANA https://launchpad.support.sap.com/#/notes/2462639 (no more CMODs available). You can of course still implement those that still exist. However, I think for most (all?) SMODs there are equivalent BAdIs or enhancement spots available.

Interesting. I couldn't find any such note on S/4HANA (and I'll have some work to do if they actually did that for the logistics components....).
