### ISSUE TITLE
SUSH	Assignment: Service --> Authorization Objects

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#1582]
serialization of SUSH

**Comment by larshp** [comment]
relevant database tables:

```
USOBHASH
USOBT
USOBX
USOB_SM
USOTT
```

some info in https://answers.sap.com/questions/7071989/using-the-authorization-sservice.html

not sure how SUSH objects work

**Comment by ThomasPloski** [comment]
Hi Lars, object handler fur SUSH object type is currently under development. Will create a PR as soon as the development is completed and verified by object type expert.

**Comment by larshp** [comment]
done in https://github.com/abapGit/abapGit/pull/4324, closing
