### ISSUE TITLE
introduce interfaces for REPO classes

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#1757]
introduce interfaces for REPO classes

will try out some stuff, not sure how it should look

**Comment by larshp** [comment]
okay, this is not easy, will start some refactoring

**Comment by larshp** [comment]
next step: move methods GET_UNNECESSARY_LOCAL_OBJS + SET_NEW_REMOTE to some other class

**Comment by larshp** [comment]
after https://github.com/larshp/abapGit/issues/2127 ?

**Comment by sbcgua** [comment]
Opinion.
If there is a plan to rebase on interface, I'd propose also to get rid of inheritance (repo -> online, offline). It seems not ideal pattern. Just as example - repo srv must re-create (!) the object when swiching types. And let see what is the difference between online and offline repo - it is more or less the strategy used to get remote source.

I'd propose to make some kind of composite object. A single class for repo. But it would employ different strategies (separate classes) depending on it's type. E.g. some `zif_remote_strategy`. SRV will even not be aware. There will be 2 strategies: online (more or less the code from repo_online) and offline (which should merge most part of zcl_abapgit_zip code which is not used anyhow else now so will fir the offline strategy perfectly). Imho this kind of approach would be cleaner and also would give easy possibility to extend the strategies if it ever be needed.

One potential complexity: now repo_meta (`ms_data`) contains both information for online and offline. This should be either accepted or adjusted to have common meta and specific meta, depending on repo type (not sure which is better).

![image](https://user-images.githubusercontent.com/15635498/48977856-4efbd180-f0ab-11e8-84c3-bc83ba00c25b.png)

**Comment by sbcgua** [comment]
yeah ... maybe it is a stupid question after commenting ... :) But why do you want repo to be an interface ? Where will it be used ?

**Comment by larshp** [comment]
for unit testing
