### ISSUE TITLE
DDLS: newline problem? add tests

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#1879]
add tests under https://github.com/abapGit-tests

With https://github.com/MDJoerg/MQBA, it looks like there is a newline problem

![image](https://user-images.githubusercontent.com/5888506/44783966-4a974980-ab8c-11e8-92ce-36cdf91c8d6c.png)

**Comment by larshp** [comment]
In Eclipse, saved, before activation:

![image](https://user-images.githubusercontent.com/5888506/44787011-2a6c8800-ab96-11e8-94cf-5e4fff5012d4.png)

after activation:
![image](https://user-images.githubusercontent.com/5888506/44787023-36584a00-ab96-11e8-8c67-c1d11c3a3dfd.png)

**Comment by jrodriguez-rc** [comment]
The newline is generated at activation, isn't it? In that case, something changed from 750 to 752 that include the newline

**Comment by larshp** [comment]
try testing it in the systems

if the behavior is different in the two versions, I think we should implement a fix in abapGit to align to one of the behaviors

**Comment by larshp** [comment]
I'm unable to reproduce this with the systems I have access to

**Comment by jrodriguez-rc** [comment]
The test https://github.com/abapGit-tests/DDLS in which version was serialized?
The github file has `space` `lf` `space`, but in 752 only includes `lf` character (in this fork https://github.com/jrodriguez-rc/DDLS I have formated into 752 version)

I found the code in 752 which includes the `lf` character in method `CL_DD_DDL_HANDLER=>ADD_BASEOBJS_INFO_TO_DDLS`

For my fork, I made a PR #4143 and it works in a 750 system

**Comment by jrodriguez-rc** [comment]
Another format problem in 750 and lower:
![image](https://user-images.githubusercontent.com/56556686/98481126-57963580-21f8-11eb-9f32-c3ac8b0d72ec.png)

**Comment by mbtools** [comment]
In 750 `SOURCE_TYPE` does not exist in structure `DDDDLSRCV`. We do not have a solution for objects that are different in different releases.

**Comment by mbtools** [comment]
Update: release differences can be handled by exit now
https://docs.abapgit.org/ref-exits.html#pre_calculate_repo_status

close this?
