### ISSUE TITLE
DEVC: application component

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#1880]
Cloning https://github.com/abapGit-tests/DEVC_component into package eg. $DEVC will cause a diff

It looks like "application component" can only be set for transported packages

![image](https://user-images.githubusercontent.com/5888506/44784406-dfe70d80-ab8d-11e8-84cc-6cc5aa7c1400.png)

**Comment by flaiker** [comment]
That seems like a non-trivial fix. I guess you would have to save the application component of the remote .xml in some extra storage and retrieve it on serialization if the package is local?

**Comment by flaiker** [comment]
But of course it could have been changed on the remote in the meantime...

**Comment by larshp** [comment]
hmm, yeah, its difficult

**Comment by larshp** [comment]
I think we should do as @flaiker suggest above, if the class is local then persist fields COMP_POSID + COMPONENT using ZCL_ABAPGIT_PERSISTENCE_DB, logic to be implemented in class ZCL_ABAPGIT_OBJECT_DEVC

**Comment by mbtools** [comment]
Let's not waste more than a line for this https://github.com/larshp/abapGit/pull/3635
