### ISSUE TITLE
Question: how to separate translations from code?

### ISSUE THREAD

**Issue by jfilak** [abapGit/abapGit#1886]
Whenever translators translate a string in a class I am responsible for I get a difference in abapGit.

I would like to allow translations to live in their own files and possible in a dedicated directory. This is the layout I am used to from Open Source projects in C and Python. We were using gettext where translations are stored in `po` files  in the `po` directory.

That would get rid of the noise and distraction and allow translators to care about the files in the translations directory and developers to ignore changes in that directory.

**Comment by mbtools** [comment]
Still experimental, but what was requested. Closed by https://github.com/abapGit/abapGit/pull/6189
