### ISSUE TITLE
docs: Explain better the setup for Github

### ISSUE THREAD

**Issue by Safadurimo** [abapGit/abapGit#1901]
I had problems to understand how to set the ssl parameters for github.
There is a short explanation here: https://docs.abapgit.org/guide-ssl-setup.html, but I don't have access to the SAP Notes.
I learned at https://github.com/larshp/abapGit/issues/1225 that I have the option to either add these parameters to a file or use the RZ10 transaction.
I think Github access is so important, this should go into the offical documentation.

**Comment by larshp** [comment]
pull requests/suggestions welcome 😄 

File to change is https://github.com/larshp/abapGit/blob/master/docs/guide-ssl-setup.md

**Comment by larshp** [comment]
In the next trial version the parameters should already be there, https://twitter.com/se38/status/1029281064446058496

**Comment by larshp** [comment]
@Safadurimo will you add a PR with suggestions?
