### ISSUE TITLE
Use of sy-langu in object serializers

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#2080]
Lots of object serializers use SY-LANGU. Is that correct? Or shouldn't they use mv_language?
https://github.com/larshp/abapGit/search?q=sy-langu&unscoped_q=sy-langu

E.g. CUS0:
https://github.com/larshp/abapGit/blob/cf052951703467922b7ec015132a961e13a749f9/src/objects/zcl_abapgit_object_cus0.clas.abap#L76-L103

**Comment by larshp** [comment]
yeah, should use `mv_language` instead

there is a check which makes sure that `sy-langu = mv_language`, so I dont think this breaks anything right now

**Comment by larshp** [comment]
remaining:
![image](https://user-images.githubusercontent.com/5888506/77849097-64b26700-71c9-11ea-9849-fcb65af36363.png)

**Comment by franzreitmayer** [comment]
zcl_abapgit_objects_generic has no field mv_language. The first finding there is related to transport entry, hence not sure whether to fix or not. The 2nd finding (meth get_where_clause, same class) also not clear.

**Comment by larshp** [comment]
thanks, pull requests welcome

**Comment by larshp** [comment]
todo, 
![image](https://user-images.githubusercontent.com/5888506/105608852-bbff7480-5da5-11eb-884d-d09c948c8721.png)
