### ISSUE TITLE
SFSW: Diff and inactive after pull

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#2083]
SFSW objects is shown with diff and inactive after pull although it's not.
![image](https://user-images.githubusercontent.com/17437789/48300372-318c0c80-e4dc-11e8-90c1-c459bd7595a2.png)

After a refresh the correct state is shown.
![image](https://user-images.githubusercontent.com/17437789/48300375-4668a000-e4dc-11e8-9504-45b39c45487a.png)

Test repo
https://github.com/abapGit-tests/SFSW.git

**Comment by larshp** [comment]
hmm, this is difficult as its activated in ZCL_ABAPGIT_OBJECTS_ACTIVATION

**Comment by mbtools** [comment]
I think the solution is to remove VERSION from the XML (for SFBF, SFBS, SFSW). No?

**Comment by christianguenter2** [comment]
Meanwhile switch isn't activated at all
![grafik](https://user-images.githubusercontent.com/17437789/148029407-5c97163d-3837-4b01-a874-ac45a085e3f5.png)

```
    TRY.
        lo_switch->activate( ).
      CATCH cx_pak_invalid_state.  " Operation can't be executed in present object state
      CATCH cx_pak_invalid_data.   " Invalid data
      CATCH cx_pak_not_authorized. " User doesn't have sufficient authorizations
    ENDTRY.
```

doesn't help, as `CX_PAK_INVALID_STATE` is raised.
