### ISSUE TITLE
REFRESH_LOCAL_CHECKSUMS regression ?

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#2086]
#1485, #1509, #1666 
@larshp @christianguenter2 
Adressing this change: https://github.com/larshp/abapGit/commit/7ac8dc15b6d9e6770db62a744881d547b2590fd8#diff-d158fe7ee88c07dfcafb76f118041794R369

Hi both, do you occasionally remember the reason for this change above (removing check of branch equality in `REBUILD_LOCAL_CHECKSUMS`) ? The problem that the change broke the originally intended logic. Here is the idea:

- DB keeps last syncronized SHA1
- it is then used to detect proper change status. Just serialized local sha1 compared to DB: if differ -> local was modified. Just fetched remote compared to DB: if differ -> remote was modified. Comparing directly local to remote is not sufficient as the changes in L and R are **independent** so the "third side" should be referred (DB)
- some times DB SHA1 brokes ... for what ever reason, bugs, changes in code ...
- `rebuild` was a **manual** command intended to restore from errors and inconsistencies in DB. However it may only compare local and remote which is insufficient as stated above. Comparing the branch was a hack to infer more probable reason: if the branch is the same as in DB then remote was not changes and so the SHA1 difference is due to local modifiction, and if branch was changed then remote is newer ... and even if not, well, remote is the last state of code so maybe it is OK to import it ... BTW the logic is also described in `ZCL_ABAPGIT_SERVICES_REPO->REFRESH_LOCAL_CHECKSUMS`

So without the branch checking the result is less accurate.   
I'm considering returning the branch check. Do you have any comments ?

**Comment by larshp** [comment]
I dont understand what it is needed for, what is the bug/feature we are trying to solve?

**Comment by sbcgua** [comment]
OK, here is a bug:

1) I have a repo, and the remote has been changed
![image](https://user-images.githubusercontent.com/15635498/48303215-46829300-e510-11e8-8c59-d2ed10e4edac.png)

2) Now I update the local checksums
![image](https://user-images.githubusercontent.com/15635498/48303231-70d45080-e510-11e8-9f10-14dff3672715.png)

So now I mistakenly think that the local is newer and has something to commit which will overwrite a newer remote version. If the `rebuild` checked the branch sha1 it would not  happen and so the logic would be more safe.

**Comment by larshp** [comment]
in step 2, what is staged and pushed? if ZVISUAL_EXAMPLE is staged and pushed, the diff will disappear?

**Comment by sbcgua** [comment]
Staged and pushed would be the reverse change of remote content.  So it will "downgrade" the remote. Of course the diff will disappear but this will wrongly modify the repo. So it is an issue of git client (here abapGit)

**Comment by sbcgua** [comment]
**TODO** also: universally call `rebuild_local_checksums` on creation of a new repo. This call must use only local files. See #2150

**Comment by larshp** [comment]
moving discussion to https://github.com/abapGit/abapGit/issues/3997, closing
