### ISSUE TITLE
Docs: Recipes / Scenarios / Whitepapers

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2087]
Hi All,
Inspired by @esjewett, I'm considering adding a section with abapGit recipes / scenarios / whitepapers. Ideally one-pagers, with nice drawings, workflow description, problem description, benefits, external links and hints for setup.

Something like:

1: Collaborating on open source software
2: Using abapGit for backup and transparency
3: Setting up code review / peer review
4: Mirroring transports across systems
5: Decentralized development
6: Continious Integration (something something)
7: Delivering maintainable software products(@christianguenter2 's setup)
(titles to be aligned)

Any suggestions for software to draw diagrams? I'm thinking [draw.io](http://draw.io) or [InkScape](https://inkscape.org/), something that is free and open source, plus can export SVGs

**Comment by larshp** [comment]
plantUML looks nice

some links:
http://chumper.github.io/2016/01/04/blog-setup.html
https://stackoverflow.com/questions/32203610/how-to-integrate-uml-diagrams-into-gitlab-or-github

**Comment by larshp** [comment]
```
@startuml

frame "Organization 1" {
  agent "System 1" as sys1
  actor "Developer 1" as dev1
}

cloud "Git Host" as git

frame "Organization 2" {
  agent "System 2" as sys2
  actor "Developer 2" as dev2
}

sys1 --> git
git --> sys2

@enduml
```

![image](https://user-images.githubusercontent.com/5888506/48671134-d1bce380-eb23-11e8-8f5c-c231b78a73dc.png)

**Comment by EduardoCopat** [comment]
There is also [Mermaid](https://mermaidjs.github.io/). In my opinion, it looks better 😛.

**Comment by sbcgua** [comment]
Mermaid is an option too. From advantages: it is JS not Java (like planuml), it is open source, it is newer ... But there is one bad feeling: look at the recent [changes](https://github.com/knsv/mermaid/graphs/code-frequency) to the repo ... seems a bit abandoned. Where as planuml is developed [quite intensively](http://plantuml.com/news) even though it is an old and mature product.

**Comment by sbcgua** [comment]
BTW this can be nice for the DevOps charts: http://plantuml.com/stdlib

**Comment by jfilak** [comment]
Hmm, planuml images look like KDE Umbrello images: https://umbrello.kde.org/

**Comment by larshp** [comment]
**A: Start versioning ABAP code using abapGit**
+ Versioning of non-standard-versioned objects
+ Full transparency of what happend when
+ Backup
+ Code insights (WIP)

https://blogs.sap.com/2017/05/07/abap-using-git-for-safety-and-transparency/

**B: Make one branch per feature(Change Request/Transport)**
Manually or via Transport to Branch or https://github.com/abapGit/background_modes (WIP)
+ Enables peer code review, https://blogs.sap.com/2018/03/23/abap-code-reviews-with-abapgit/
+ Easy rollback (WIP)
+ Static code analysis per transport

How to avoid conflicts?
Let the developer create the pull request, or create automatically?

**C: Releasing transports**
Automatically when the PR is approved? Push/Pull setup?
When releasing manually call API to check PR is approved? (plus transport matches branch)

**D: Importing transports**
Avoid transport errors(syntax) via static analysis, run syntax check of import before releasing


**Add-ons:**
Unit test results?
Risk assessment, for each PR automatically add comment with impact analysis, key metrics, if dangerous statements added, dynamic code added
Static analysis, check for SQL injection

**Comment by esjewett** [comment]
I think on (B), optimal option is to have 1 Dev integration system and 1-n dev systems where developers actually do work. No one manually touches the Dev integration system. The dev integration system just tracks master. Developers use one of the 1-n other systems to generate branches that will merge cleanly to master. When the pull request is approved, the branch is merged, pulled into the Dev integration system and a transport created and immediately released. This guarantees that you have the same thing in the transport as you have in the master branch. 

If you’re stuck with a single dev system, then you have to do manually checks to make sure transport contents match pull requests in a continuous integration scenario.

**Comment by larshp** [comment]
Agree, there are multiple variations of above. Local developer systems are optimal, but guess somewhere out in the future. I have trouble adding extra infrastructure at clients, it easily gets into a lot of politics

**Comment by larshp** [comment]
closing, no progress
