### ISSUE TITLE
Unable to clone subpackages when parent package already cloned (vice versa)

### ISSUE THREAD

**Issue by joymike** [abapGit/abapGit#2149]
Hi All,

Just want to clarify whether this is "feature" or not.

We are trying to use abapGit for our code review process. We have decided to clone our top package to git repo, which works great (but slow). The performance is being addressed in a separate thread. 

However when we try to clone a subpackage to a completely different git repo, we get an error that the parent repo is already cloned. We couldn't quite understand why this check was in place? 
Can someone please kindly explain?

With this restriction, we now have to choose whether to use git as a code review tool or not as it will stop our developers using abapGit for development. 

Cheers

Michael

**Comment by joymike** [comment]
ZMAIN goes to repo1 (for code review across the board)
ZCHILD connects to repo2 (for developer to quickly version control his own code)

Conceptually I see it like this.
During development, developer responsible for pushing changes to repo2. 
In order to release their transports to trigger for a code review, they use transport to branch to push to repo1. (maybe automate this as you have suggested in a different thread).

**Comment by larshp** [comment]
Why not have the developer version control his code in a branch in repo1? Assuming each feature is developed in a branch. This gives less complexity for the developer, as there is only one repo, and less effort to set up?

**Comment by joymike** [comment]
The main benefit of ZCHILD -> repo2 is that their view would contain only their own changes, and not all changes in the entire repo. 

Thanks Lars. We will look into that suggestion of everyone using repo1. Now that performance is much improved, this option is much more palatable. I also like your suggestion of making the check optional, while showing a message on the screen alerting the user either the parent/subpackage is also sync'd by a different developer. This will allow greater flexibility on how different organisations implement different git designs.

**Comment by EduardoCopat** [comment]
> Perhaps we should just make a global setting to disable this check, been getting questions from more parties around this. However, I still have to understand a scenario where this makes sense.

That is something that can be done. But then we may reach a point where we have lots and lots of settings/preferences...

**Comment by mbtools** [comment]
In addition to using one repo with branches, there's the option to use CI: Create the main repo independent of abapGit and mirror all your child repos into it. See https://blogs.sap.com/2021/04/20/automagic-standalone-renaming-of-abap-objects/ for an example. You wouldn't even need any renaming. 

I don't see us changing the current design linking packages to repos.  Suggest closing
