### ISSUE TITLE
git commit --amend

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#2166]
https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things

It some cases it would be really useful for me to amend changes to the last commit. My current workaround is to create a new commit and then squast the commits via command line. Any opinions whether this is something we should add as a feature to abapGit?

**Comment by larshp** [comment]
yeah, its a git feature, then it should be part of the git client

**Comment by christianguenter2** [comment]
[WIP](https://github.com/christianguenter2/abapGit/tree/amend)

**Comment by marcellourbani** [comment]
I read this only now, and I don't think it's a good idea for abapGit.

I often use it on my local repo, but public repos are another beast: while allowed, overwriting a public commit is frown upon. And in ABAPGit we mostly work with public repos

Don't feel like double checking, but if I remember correctly when one amends a commit it doesn't change its ID, so if I amend a public commit I introduce an undetected change (well, mostly undetected)

Say I publish commit1 and Lars pulls it
Then I amend it and Christian pulls it

As far as the commit hashes are concerned the history will look the same for everybody, but the files are different. If I push something else and you both pull it, you just apply the new commit on top of the previous, without updating the newer version of the amended commit

https://stackoverflow.com/questions/253055/how-do-i-push-amended-commit-to-the-remote-git-repository

**Comment by marcellourbani** [comment]
Yep sorry for the confusion. Does mess up public repos but in a much saner way

**Comment by esjewett** [comment]
IMO, WebIDE does this right. It allows amending local commits but does *not* allow you to amend a commit that has already been pushed. I think this is the way ABAPGit should work if it allows amending commits at all. It is a seriously problematic idea to have the system allow you to change public commits (rebase, amend, squash) without passing through some really scary warnings.

**Comment by mbtools** [comment]
seems controversial. suggest closing (since your wip was dropped)
