### ISSUE TITLE
Error handling for DESERIALIZE

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2169]
Currently some of the errors during deserialization is shown in the GUI, however we want to decouple all GUI dependencies from the abapGit API.

Method ZCL_ABAPGIT_REPO->DESERIALIZE should return(or similar) a ZCL_ABAPGIT_LOG instance with the errors for the objects.

The list should include syntax errors, so perhaps run syntax check for all objects after deserialization to find erroneous objects and add errors to the log.

**Comment by larshp** [comment]
Note that the user usually finds errors by looking in the overview, if there is a diff, the deserialization failed

**Comment by larshp** [comment]
Steps to reproduce:
1: clone https://github.com/larshp/deserialize_error.git
2: after pull, no errors are shown, only the diff indicates that something is wrong,
![image](https://user-images.githubusercontent.com/5888506/49646146-8a3cbf80-fa1e-11e8-8e33-337215f10484.png)

**Comment by larshp** [comment]
With experimental features on, it gives the following error
![image](https://user-images.githubusercontent.com/5888506/49647026-67f87100-fa21-11e8-8ec5-f5441c6fb2bb.png)
This seems to solve most of the issue for DDIC

I suggest the following
1: More testing of the experimental deserialization(`DD_MASS_ACT_C3`)
2: Decouple [show_activation_errors](https://github.com/larshp/abapGit/blob/7cdbbc92b6b6cb9c31b1975615bb1b45a92c65f9/src/objects/zcl_abapgit_objects_activation.clas.abap#L313) from GUI by having `DESERIALIZE` return an instance of `ZCL_ABAPGIT_LOG`
3: related https://github.com/larshp/abapGit/issues/1584
4: related https://github.com/larshp/abapGit/issues/1055

**Comment by christianguenter2** [comment]
5: two errors
https://ci.abapgit.org
![image](https://user-images.githubusercontent.com/17437789/50575901-fe446a80-0e06-11e9-952b-72400d3bdfc1.png)

**Comment by larshp** [comment]
Note that above errors are the same as when running without experimental features enabled

**Comment by GoWale** [comment]
Also related to #891 I think

**Comment by larshp** [comment]
experimental features enabled, so the error messages are shown to the user

**Comment by mbtools** [comment]
closed with #2729
