### ISSUE TITLE
Limit languages (translations) to be serialized

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#2202]
The idea is to limit searilizable languages e.g. per repo.

Why:
- when transferring (updating!) developments in client systems it may happen that some local objects got additional translations (e.g. after migration to EHP8 in some packages EN translation replicated to all installed langs - don't know why). This kills transparency on what has changed as there are always new local changes which were not in the original code and makes the update quite manual
- for the delivery of a product to a client we would limit the language list to the installed ones

Does any one has similar or related issues?

Currently not sure about the implementation approach. Here is what come to my mind:

Option 1: the serialization must have some context variable, set once on the init phase, listing the languages to serialize. So each object type class can respect it. The problem is that there is no context now. The only place is `io_xml` which is ok ... but semantically strange. Advantages - minimal changes to the existing low level code (serializers).

Options 2: more revolutional. rewrite ~~everything~~ how the translation are serialized at all ! Now they are in the same XML file as the object. This is consistent. But has limitation. E.g. I remember there was an issue with discussion on how to better manage object translations in AG and someone mentioned PO-files (a popular open source approach for tranlation). So meaning that the translations should be moved to a separate file and optimized for easier editing. This would also make subject of this issue cleaner - after/before  serialization some external code (external to type serializers) can filter needed languages. So this approach will kill 2 targets. But it changes the serialization structure ...

maybe there are more ideas ?

**Comment by larshp** [comment]
related: https://github.com/larshp/abapGit/issues/1886

**Comment by larshp** [comment]
@sbcgua is this issue tackled in one of the new PRs? alternatively, move this issue to #2539

**Comment by sbcgua** [comment]
The ground for the solution is kind of laid in #4415 and  #4494
I think this may be closed.
