### ISSUE TITLE
Remove redundant / useless information from INTF xml

### ISSUE THREAD

**Issue by EduardoCopat** [abapGit/abapGit#2207]
Follow up on #1458.

Some fields from INTF xml are redudant. For example: `EXPOSURE`. 

See also #2195.

**Comment by AndreaBorgia-Abo** [comment]
Got a few repos where the only difference between remote and local is that remotes have (one or more of) VERSION / EXPOSURE / CLSFINAL set and my local copy does not.
Examples:
* [ABAP ALV Google Upload Sheet](https://github.com/SAP-samples/abap-alv-google-upload-sheet)
* [abapGit user exit logon by rfc](https://github.com/sandraros/abapGit-user-exit-logon-by-rfc)
* [ZCL_PDF](https://github.com/beraadim/zcl_pdf)

Conversely, this one is reported as having differences but the comparison window is empty:
* [ABAP Swagger](https://github.com/larshp/ABAP-Swagger)

Is it related to this issue? I've tried resetting local objects but it doesn't go away.

**Comment by larshp** [comment]
for 
- ABAP ALV Google Upload Sheet
- abapGit user exit logon by rfc
- ZCL_PDF
I guess they have not been updated to the latest abapGit format, suggest submitting a pull request to the repositories

Empty diff, its typically empty when the difference is only whitespace, try committing the changes, and opening a PR

**Comment by AndreaBorgia-Abo** [comment]
format: will do

empty diff: I'm puzzled that it survives a reset, I expected that it would be like a fresh install with whatever is that upstream has at this point in time. I wouldn't bother them with such trivia.

**Comment by larshp** [comment]
ABAP Swagger fixed in https://github.com/larshp/ABAP-Swagger/pull/66

**Comment by larshp** [comment]
closing this issue, moving to similar issue https://github.com/abapGit/abapGit/issues/4048
