### ISSUE TITLE
Suggestion: Remove feature "Make off-line" / "Make online"

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2244]
There is a feature under Advanced, which allows switching the repo type between online and offline.

The class ZCL_ABAPGIT_REPO_SRV keeps a list of the repository objects, of references to either ZCL_ABAPGIT_REPO_OFFLINE or ZCL_ABAPGIT_REPO_ONLINE, when the type of repo is changed, the object must be changed correspondingly.
This is implemented via listeners, ZCL_ABAPGIT_REPO->BIND_LISTENER and ZCL_ABAPGIT_REPO_SRV->ZIF_ABAPGIT_REPO_LISTENER~ON_META_CHANGE, ie. when the internal state of the object is changed it has to call the listener. Ideally, it should be possible to change the internal state independently.

The suggestion is to remove the feature, as the assumption is it is not used very much and adds some complexity in the code.

Currently, the user can do:
1: Advanced -> Make off-line
2: Click okay

Without the feature, the user will be able to do the same thing in more clicks,
1: Advanced -> Remove
2: Click okay
3: Click new offline
4: Enter details
5: Click okay

**Comment by sbcgua** [comment]
6) + re-enter all repo setting if they were not default.

I vote against. I use it from time to time. My typical flow for the new code is creating repo offline first and then attaching it to online after a while.

**Comment by pokrakam** [comment]
FWIW, I use it and find it a minor timesaver. Use cases: 

- Offline is my 'cold storage'. To work on something, I create offline repo, import, switch to online (gitHub/AGS), work on it (background mode update enabled), switch to offline, save zip

- on a few occasions I've gotten myself into a git-knot. Switching to offline and back somehow seemed to perform a 'harder reset' than the "Reset" function and fixed the issue on at least one occasion so I use it for troubleshooting

Counter-question: Is there a difference between "Package to Zip" and offline repo export? 
I remember seeing some differences, but my experiences may have spanned different AG versions. But to be on the safe side, my local backup process has thus far been: copy URL, switch to offline, export zip, switch to online, paste URL, save. A quick test now showed no difference.

If an offline repo is different to a 'Package to Zip' then I definitely would like to keep this feature. Or perhaps we could implement a 'local repo backup' instead?

In all scenarios I can work around easily, so I'm OK either way.

**Comment by larshp** [comment]
I think this is a sacrifice that must be made, in order to remove complexity, we need to remove complexity to have a chance to refactor REPO

**Comment by larshp** [comment]
I still think this is a sacrifice that must be made, but closing for now
