### ISSUE TITLE
Give error if installing into a main package

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2273]
When installing an offline or online project, give error if installing into a main package, as main packages cannot contain repository objects.

Or somehow verify if its allowed, and no objects will be deserialized to an existing main package

**Comment by larshp** [comment]
actually this is okay, as long as the folder only contains subfolders(packages)

**Comment by flaiker** [comment]
By the way: Surprisingly the check is not as strict as it seems and you can actually create some other objects types than DEVC in a main package. I think BMFR, CUS* etc are allowed for example.

**Comment by larshp** [comment]
heh, its a feature

**Comment by mbtools** [comment]
And sub-packages can also be main-packages. are you sure it's a "good first issue"? label "crazy" and close ;-)
