### ISSUE TITLE
Reduce memory consumption during repo import

### ISSUE THREAD

**Issue by mfsap** [abapGit/abapGit#2280]
To reduce memory consumption during repo import, I would recommend not to store the DOM (IF_IXML library) for the XML in each instance of ZCL_ABAPGIT_XML(_INPUT).
As an alternative, the ZCL_ABAPGIT_XML instance should store the XML string only. For each READ operation, a local DOM can be used used. To avoid several single READ operations each creating an own DOM, a READ_MULTIPLE method could be provided that may read several artifacts from the local DOM via table like parameter. If artifacts are requested multiple times, we can be think about storing the results in a generic table after they have been extracted once. This concludes the metadata structures as well.  I know that this may increase the runtime, but in my case I have had memory problems importing a huge repo….

**Comment by larshp** [comment]
Suggest something like:
* Rewrite GET_METADATA so it finds the metadata using string functions
* Instantiate the ZCL_ABAPGIT_XML_INPUT instance just before DESERIALIZE, this way the garbage collector can remove it from memory when the current object has been serialized

**Comment by mbtools** [comment]
Depending on the repo, https://github.com/abapGit/abapGit/pull/4357 can reduce memory consumption a lot. @mfsap, do you have a test case to check?

**Comment by larshp** [comment]
ref https://github.com/abapGit/abapGit/pull/4775 releases some serialization memory, which also impacts import

**Comment by larshp** [comment]
this was optimized in above PR, probably always possible to optimize, closing, open PR or issue with specific new suggestions
