### ISSUE TITLE
File format updates, collection

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2309]
Lets try to gather file format updates, and make changes in one go,

**Comment by larshp** [comment]
**VIEW**
looks like VIEWNAME,
https://github.com/abapGit-tests/VIEW/blob/master/src/zag_unit_testv.view.xml#L25
can be cleared

plus ROLLNAME/data elements are not really part of this object

**Comment by larshp** [comment]
**INTF + CLAS**
guess the class name under DESCRIPTIONS can be cleared, it is enough to have the header name in the xml

```xml
   <DESCRIPTIONS>
    <SEOCOMPOTX>
     <CLSNAME>ZCL_CLASS_NAME</CLSNAME>
```

**Comment by larshp** [comment]
**TABL**
TABNAME for each field can be cleared,
https://github.com/abapGit-tests/TABL/blob/master/src/zabapgit_unit_t2.tabl.xml#L23
probably also
https://github.com/abapGit-tests/TABL/blob/master/src/zabapgit_unit_t2.tabl.xml#L15
and more?

**Comment by larshp** [comment]
**MSAG**
Field ARBGB can be cleared for each message,
https://github.com/abapGit-tests/MSAG_simple/blob/master/src/zag_unit_test.msag.xml#L13

**Comment by larshp** [comment]
Plus there is the byte order mark, https://github.com/larshp/abapGit/issues/799

**Comment by larshp** [comment]
and https://github.com/larshp/abapGit/issues/2207

**Comment by larshp** [comment]
https://github.com/larshp/abapGit/issues/2235

PROG: consider clearing VARCL + UCCHECK

**Comment by larshp** [comment]
VSEOCLASS-UNICODE
VSEOCLASS-VERSION
VSEOCLASS-STATE

VSEOINTERF-UNICODE
VSEOINTERF-VERSION
VSEOINTERF-STATE

PROGDIR-STATE
PROGDIR-VARCL
PROGDIR-UCCHECK

**Comment by mfsap** [comment]
For object type DCLS:
IF_ACM_DCL_HANDLER=>TY_S_DCL_HEADER-ACTIVATION_STATUS

**Comment by mfsap** [comment]
For object type DDLX: MASTER_SYSTEM

**Comment by mfsap** [comment]
MSAG: Field DOKIL-DOKSTATE for message longtexts

**Comment by larshp** [comment]
@mfsap which are most important, where to start?

**Comment by mfsap** [comment]
it doesn't mater where to start :-) 
I'm just collecting attributes that can/should be avoided...

**Comment by mfsap** [comment]
ENQU: AS4LOCAL (and AS4VERS)

**Comment by filak-sap** [comment]
Do we need really DESCRIPTIONS in `clas.xml`? I haven't seen an option to change method description in ADT.

**Comment by larshp** [comment]
@filak-sap SAP standard class CL_OO_CLASS assumes classes have descriptions

also see https://github.com/larshp/abapGit/issues/2539, @sbcgua suggests to move all texts to a separate file

**Comment by flaiker** [comment]
> Do we need really DESCRIPTIONS in clas.xml? I haven't seen an option to change method description in ADT.

There's the so called "synchronized short texts" feature in ABAP Doc that allows you to edit these texts in ADT.

**Comment by mbtools** [comment]
Looks to be completed.
