### ISSUE TITLE
SOTR: Why do we skip SOTR?

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#2320]
Does anybody know why we skip SOTR?
https://github.com/larshp/abapGit/blob/9270a58b62ebdf8f23f80d9cae00890ffed236d2/src/zcl_abapgit_tadir.clas.abap#L69-L70

**Comment by larshp** [comment]
probably a bad decision back from 2016 😄 as they can be created independently via SOTR_EDIT

I guess we should work towards not excluding them, but do consider what should happen with the existing code as SOTR is currently part of serialized class/interface object xmls.

**Comment by larshp** [comment]
actually, I cannot figure out how to create a SOTR object which has an entry in TADIR

**Comment by mbtools** [comment]
All SOTR entries in TADIR have OBJ_NAME = DEVCLASS. They are automatically created when you create the first component that contains a text. Don't think they need separate handling.

![image](https://user-images.githubusercontent.com/59966492/87254451-bfa65c00-c450-11ea-9c4a-5e5d6b459e01.png)

**Comment by mbtools** [comment]
According to https://launchpad.support.sap.com/#/notes/1247020, R3TR / SOTR / <package> stands for all text/concepts. Since abapgit handles individual objects, R3TR/SOTR can be ignored.
