### ISSUE TITLE
Test conflicting transports

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2345]
Question:
What happens if I import two objects A, and B
B is already assigned to transport 2
When doing a pull I select transport 1

I guess it runs without errors or warnings but A is in transport 1 and B is in transport 2

**Comment by christianguenter2** [comment]
Yes, I think so too.

**Comment by mfsap** [comment]
If a main object (R3TR object) is locked in a different request, the pull should work well. But what happens, if sub-objects are recorded in different requests? E.g. messages of the same message class (LIMU MESS objects) are part of different requests and the pull requires R3TR MSAG recording? It this case, a deadlock exists that can only be resolved either by the user via “manual transport consolidation” or by splitting the R3TR into LIMU by abapGit (which sounds very complex). In this case, I would recommend that the user “consolidates” the different requests either by creating a single request or by releasing the requests in advance.

**Comment by larshp** [comment]
closing, no progress
