### ISSUE TITLE
Allow offline repos to use a folder that contains a cloned repo

### ISSUE THREAD

**Issue by gregorwolf** [abapGit/abapGit#2371]
Currently offline repos can only be used with ZIP files. In some cases the user on a local pc can access the internet but SAP can't. So the user could clone the repo to the desktop and point abapGit to that folder.

**Comment by larshp** [comment]
If we make a new type, "offline with folder", I think https://github.com/larshp/abapGit/issues/2244 should be done first, it gets difficult with 3 types and possibility to switch between all of them

**Comment by mbtools** [comment]
Just adding some thoughts...

I can imagine a bunch of different sources for a repo:

Source Type | Description | Exists
-------------| ----------------|--------------------
Git server (HTTP) | Online repo | Yes
Git server (RFC) | Online repo | Yes, with exit
ZIP file (local) | Offline repo | Yes
ZIP file (file server)  | Like an offline repo with import/export | No
Folder (local) | Like an online repo with read/write access (temporary) | No
Folder (file server) | Like an online repo with read/write access (with or w/ logon) | No

The current on/offline repo classes should be combined into one. Then point to one of the "repo source" classes. A bit of work but doable

**Comment by mbtools** [comment]
With the current architecture, using a folder with individual files is not feasible. AG must read all files when opening a repo which would take quite a long time. 

We might revisit once "connectors" are implemented as suggested in https://github.com/abapGit/abapGit/issues/3799
