### ISSUE TITLE
Refactoring ZCL_ABAPGIT_DEPENDENCIES

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2464]
Class ZCL_ABAPGIT_DEPENDENCIES is used to determine the object deletion sequence.

It contains object specific code, which I suggest moving to each object, as a new method in `ZIF_ABAPGIT_OBJECT`, the method will return a list of dependencies, eg DTEL A requires DOMA B. This information can then be used to make a dependency graph.

Currently I dont think we have issues regarding cyclic dependencies, but we might get it with above refactoring, in that case suggest adding a `PRE_DELETE` method to `ZIF_ABAPGIT_OBJECT` which eg. removes search help references from TABLs, and check tables from DOMA objects, in order to safely reduce the dependency graph pre deletion.

**Comment by GoWale** [comment]
I'll give it a try.
I think there should be 2 methods:
1. Get edges/dependencies for each object
2. Add delete_preparation as mentioned to cut cyclic dependencies

The two method will allow more checks before the fine deletion will start. (e.g. dependent object is not part of the repo and therefore the repo cannot be uninstalled.)

I tested some public repo cause auf my deserialize changes and uninstall seems to have some open issues?
I think it no so common to uninstall a repos that is a little more complex.

**Comment by larshp** [comment]
suggest getting https://github.com/larshp/abapGit/pull/2518 closed first

**Comment by mbtools** [comment]
Duplicate. Use #3536
