### ISSUE TITLE
unsupported object list

### ISSUE THREAD

**Issue by kuzeydev** [abapGit/abapGit#2468]
I think it would be a good idea to create a file for each repo which includes all unsupported objects. then owner of repo knows what objects he lacks.

**Comment by larshp** [comment]
it is shown in the git client, 
![image](https://user-images.githubusercontent.com/5888506/53547643-de43d580-3b2f-11e9-8c52-0de4cd212e65.png)

**Comment by kuzeydev** [comment]
> it is shown in the git client,
> ![image](https://user-images.githubusercontent.com/5888506/53547643-de43d580-3b2f-11e9-8c52-0de4cd212e65.png)

is it shown when exporting...
I cannot see when importing.
![image](https://user-images.githubusercontent.com/40596541/53561477-0cd9a480-3b60-11e9-811c-53e5c4d493d8.png)


That is the list that should be written in a file. 
When exporting you see the list, however when importing you cant see which objects is missing.
It would be better to know which objects is not included in repo you are about to import/pull.
Just an idea.

**Comment by larshp** [comment]
from my point of view, we should work towards supporting the object types, instead of building special processes to handle it.

**Comment by larshp** [comment]
recently https://github.com/abapGit/abapGit/pull/4601 and https://github.com/abapGit/abapGit/pull/4589 was implemented, I think this is okay for tackling this issue

closing
