### ISSUE TITLE
SFBS: Inactive after deserialization

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#2470]
Demo repo
https://github.com/abapGit-tests/SFBS.git

![image](https://user-images.githubusercontent.com/17437789/53573583-0baf7400-3b6e-11e9-8d9f-fd66b57df06b.png)

![image](https://user-images.githubusercontent.com/17437789/53573586-0ce0a100-3b6e-11e9-80d3-bd2e35b359f0.png)

Possible side effect of parallel DDIC activation
#1055

**Comment by GoWale** [comment]
yes side effects of the new DDIC actiavtion.
Fixed in the draft #2518 seems it needs the old activation function.
I think this is for SFBF, SFBS and maybe SFWF?
