### ISSUE TITLE
Ignore ABAP language version in object metadata

### ISSUE THREAD

**Issue by mfsap** [abapGit/abapGit#2476]
For the object metadata, the ABAP language version should not be considered (e.g. for classes, the UNICODE field is re-used for language version '5'). In case of object comparison (local<->remote), this field could not count.

**Comment by larshp** [comment]
what is the exact list of object types and fields?

some are mentioned in https://github.com/larshp/abapGit/issues/2309, also if we do this change include more fields if needed, so we disturb users as little as possible

**Comment by mbtools** [comment]
REPOSRC-UCCHECK... It's still being serialized. If we take it away, we won't know if a program is Unicode-enabled or not or whether it's cloud-compliant or not. I think we should keep the field.

We could discuss what should happen during deserialize if a UCCHECK value (ABAP version) is not supported by the importing system.

**Comment by mbtools** [comment]
ABAP language version is essential. Closing

https://blogs.sap.com/2022/09/09/abap-language-versions-faqs/
