### ISSUE TITLE
Deseralize steps, #2

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2493]
after https://github.com/larshp/abapGit/pull/2449

suggest after that to refactor to remove CATCH cx_sy_dyn_call_illegal_method. and the late deserialization flag

**Comment by larshp** [comment]
all the single methods implemented, still some refactoring needed but leaving as is for now

**Comment by GoWale** [comment]
I would create a PR for the last step (Swapping DDIC/ABAP + changing activation) this evening when I'm back home.
Or should I wait till the weekend to not conflict all the changes in this busy week?

**Comment by larshp** [comment]
just go ahead, I dont think there will be many changes in the serializers 😄 

and thanks for the fix btw

**Comment by larshp** [comment]
no idea, closing
