### ISSUE TITLE
isolate use of cl_gui_frontend_services to the /ui/ package

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2510]
isolate use of cl_gui_frontend_services to the /ui/ package

@ThomasPloski

**Comment by larshp** [comment]
@ThomasPloski regarding the call to gui frontend services from the objects super class
![image](https://user-images.githubusercontent.com/5888506/54288083-27237180-45a7-11e9-96dd-2e0312280614.png)
would it be okay to have the super class call a method in the class from https://github.com/larshp/abapGit/pull/2516, code would not be perfectly separated, but it could be possible to inject a zif_frontend_service class without calls to cl_gui_frontend_services

**Comment by larshp** [comment]
todo: 
![image](https://user-images.githubusercontent.com/5888506/77849298-f2428680-71ca-11ea-9009-ae2ae5dc1581.png)

**Comment by larshp** [comment]
it needs to be "hidden" behind a factory method, that way, a mock can be injected

**Comment by larshp** [comment]
@g-back did https://github.com/abapGit/abapGit/pull/5046 also solve this issue?

**Comment by g-back** [comment]
No, local types of class `zcl_abapgit_transport_mass` still contains direct references to it. Will decouple these some time this week.
