### ISSUE TITLE
User exit, change lt_results in deserialize

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2514]
User exit, add possibility to change lt_results in zcl_abapgit_objects->deserialize

can also take the log object from https://github.com/larshp/abapGit/issues/2495 as input

@ThomasPloski

**Comment by JanisB-AT** [comment]
I stumbled into this while poking around looking for an "easy" way to implement #413... Was this maybe meant as a way to influence the list of objects to be deserialized..?

**Comment by larshp** [comment]
hmm, no, the idea was to be able to change the contents

but anyhow, I'll go ahead and close, its from 2019
