### ISSUE TITLE
Deserialization changes ECTD data

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#2535]
ECTD is not fully supported by UDO and I tried to use abapgit as a workaround. There are some minor issues here as well:

After pulling the following ECTD object, you should see differences between remote and local.
[zfh_ifme_tdc_ff_parser_json.ectd.zip](https://github.com/larshp/abapGit/files/2972269/zfh_ifme_tdc_ff_parser_json.ectd.zip)

It will remove a trailing newline in the data:
```
<CONTENT>:3:NEWT
</CONTENT>
```
becomes
```
<CONTENT>:3:NEWT</CONTENT>
```
It also changed SORTLNR from 2 to 1, whatever that is.

There's also an issue with the diff display. There is a very long line in the serialized xml and the diff doesn't word wrap, so I can't see the other part or scroll.
![image](https://user-images.githubusercontent.com/5097067/54450902-cbe1b280-4751-11e9-8246-2b55b52bac25.png)

**Comment by christianguenter2** [comment]
Can you provide a public test repo to reproduce the issue? I cannot import your zip as the IF_IFME_TESTING=>TS_JSON doesn't exist in my NW 752 dev edition.

**Comment by FreHu** [comment]
Try pulling https://github.com/FreHu/abapgit-ectd-bug

Small correction, the diff is partly visible at 1440p:
![image](https://user-images.githubusercontent.com/5097067/54535706-624ee780-498f-11e9-98e7-d10362d8f113.png)

**Comment by christianguenter2** [comment]
![image](https://user-images.githubusercontent.com/17437789/54564566-651bfd80-49cc-11e9-8430-19cb593ed5ab.png)

**Comment by FreHu** [comment]
I renamed the test data container. Shouldn't SAP disallow copying to a local package without a customer prefix in the first place? I'm not familiar with the rules about this.

Strangely, now pulling causes the following error, which I wasn't getting before:
![saplogon_iuJTVGKjov](https://user-images.githubusercontent.com/5097067/54592671-28342300-4a2d-11e9-896e-c28d8398d9a1.png)

Despite the error, the pull works (refresh the repo after).

**Comment by mbtools** [comment]
Works with 754 SP 7 and latest abapGit
