### ISSUE TITLE
+Online: missing check of "Git clone URL" already used in another Online Project?

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#2590]
### Context why I came to ask for this new check
I wanted to define a special configuration: one Git repository but two Online projects, because I have two systems S1 and S2. In S1 there is the development of the package P1 and in S2 there is the development of the package P2. In S1, P1 is pushed and P2 is pulled. and in S2, P2 is pushed and P2 is pulled (all automatically).

So, my idea was to define these Online projects (package - root folder) :
Package P1  -  /src/p1/
Package P2  -  /src/p2/

"Unfortunately", impossible to make it work (essentially because there's only one .abapgit file at the root of the Git repository, which defines only one root folder and abapGit in both systems changes it alternatively after each pull/push, and that messes up everything.

Conclusion: I understand now that the only solution is to create a second Git repository. Okay, no problem.

### So my question is
Is it possible to add a check if one tries to create an Online project whose "Git clone URL" is already used in another existing Online projet, so that to avoid wasting time? (of course I can change the code if you think it's OK)

**Comment by flaiker** [comment]
There have been a number of issues posted, where people came up with some let's say "innovative" ideas to map their existing package hierarchies to git repositories.

There are already some checks in place to prevent shooting yourself in the foot, like checking for if a super package is already contained in another repository. So it should be fine to add another one.

Another option would be to just add a chapter in the documentation. One theoretical use case for having the same remote in multiple online repositories on the same system would be if there were entirely different objects in different branches.

**Comment by mariusraht2** [comment]
IMHO we can skip the first option because the missing check and the possibility to add repos redundantly by its urls is nothing game-breaking as far as I see it at the moment. It would only add some new logic without real added value for the stability of the report. If the user thinks he needs the redundant repos he can add it, if not he won't use it. Or is there any function within abapGit which would fail if it would have to deal with duplicate repos?

**Comment by larshp** [comment]
I think its okay to add this check for same url already used in other repo.

If users really want to do this anyhow, they can comment out the code, add query parameter to the url.

**Comment by mbtools** [comment]
we check if URL is used already (https://github.com/abapGit/abapGit/blob/8555d1a0da6400fc04dbb0e3851e69bf76e5b720/src/repo/zcl_abapgit_repo_srv.clas.abap#L651)
