### ISSUE TITLE
Java GUI replaces spaces in file names with <?>

### ISSUE THREAD

**Issue by filak-sap** [abapGit/abapGit#2592]
Spaces get replaced by `EFBFBD`

I found out taht the characters are replaced by Java GUI - CL_GUI_HTML_VIEWER=>GET_SAPEVENT_POSTDATA.

I have to investigate the problem deeper. Maybe, it's only on my Linux box.

**Comment by filak-sap** [comment]
@larshp What do you think about a commit like this one: https://github.com/filak-sap/abapGit/commit/93fc5b927ccd4035d76254777df961a3243f8bf8

**Comment by larshp** [comment]
if EFBFBD corresponds to <?>, it looks good to me, I think its safe to replace this

**Comment by mbtools** [comment]
Is this still an issue? Out of curiosity, what's the feature_tab for "saphtml" when you run CL_GUI_FRONTEND_SERVICES=>GET_FEATURES_TAB (in se24)?

**Comment by kjetil-kilhavn** [comment]
That's a nice method, hadn't heard about that before!
Here's the output from SAP GUI for Java 7.50 rev 12 with the ABAP 1909 for Hana (docker) backend

| COMPONENT                     | FEATURENAME                   | VALUE                         |
| ----------------------------- | ----------------------------- | ----------------------------- |
| saphtml                       | simplebrowse                  | X                             |
| saphtml                       | detachurlinbrowser            | X                             |
| saphtml                       | getcharsetstring              | X                             |
| saphtml                       | detachedbrowser               | X                             |
| saphtml                       | endsessionfeature             | X                             |
| saphtml                       | enablesso                     | X                             |
| saphtml                       | loadiconfont                  | X                             |
| saphtml                       | enablesecsess                 | X                             |

**Comment by mbtools** [comment]
Form data must not contain any spaces, ?, !, or /. These must be escaped properly (for example space to %20) when composing the HTML in AG (and then unescaped when AG handles the event). https://github.com/abapGit/abapGit/issues/4661

In a case as described above, please check first how the page/form was build.

**Comment by mbtools** [comment]
Is this fixed by #4677 or is it different?

**Comment by kjetil-kilhavn** [comment]
In SAP GUI for Java 7.570 rev 1 with the ABAP 1909 for Hana (docker) backend output from CL_GUI_FRONTEND_SERVICES=>GET_FEATURES_TAB has one change; the last line (enablesecsess) is not there.

**Comment by mbtools** [comment]
Anymore problems like this with JavaGui 7.70?

**Comment by mbtools** [comment]
No reply. CLosing
