### ISSUE TITLE
Updating to latest abapGit, Reset local does not delete all methods

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#2595]
after updating to latest abapGit, I get the following diffs, reset local does not help
guess this is due to the interface which is now deleted
workaround: update the 3 classes manually

![image](https://user-images.githubusercontent.com/5888506/55213617-266c1b80-51f4-11e9-8e70-a94a221ac296.png)
![image](https://user-images.githubusercontent.com/5888506/55213627-2d932980-51f4-11e9-9134-d990ba049186.png)
![image](https://user-images.githubusercontent.com/5888506/55213638-3126b080-51f4-11e9-88b3-b8b75b2508af.png)
![image](https://user-images.githubusercontent.com/5888506/55213645-3683fb00-51f4-11e9-9603-024c7eeb2bf0.png)

**Comment by sandraros** [comment]
I have a nightly automatic background pull and it does a short dump SYNTAX_ERROR when I start ZABAPGIT:

![image](https://user-images.githubusercontent.com/34005250/55286251-6b7d8280-5399-11e9-99b8-4e2d0904e974.png)

**Comment by sandraros** [comment]
A quick solution to correct the code is to "clean up the method includes" via SE24.

Repeat the procedure for the 3 classes:
- ZCL_ABAPGIT_GUI_PAGE
- ZCL_ABAPGIT_GUI_VIEW_REPO
- ZCL_ABAPGIT_GUI_VIEW_TUTORIAL

(the below screen captures are for ZCL_ABAPGIT_GUI_VIEW_REPO)

Start SE24, enter the class name and click button "Change".

# Menu Utilities -> Clean Up -> Method Includes (or okcode `.SCM` for lazy persons)

![image](https://user-images.githubusercontent.com/34005250/55286274-cd3dec80-5399-11e9-8ef3-babee751b09f.png)

# Say `YES` to the popup to delete the includes:

![image](https://user-images.githubusercontent.com/34005250/55286276-da5adb80-5399-11e9-965b-d1fc5a4fc2cc.png)

# And activate:

![image](https://user-images.githubusercontent.com/34005250/55286344-d11e3e80-539a-11e9-91da-de8b7a85a948.png)

**Comment by larshp** [comment]
yea, it will not work in all cases, as the program running is the one being updated

Recommend keeping the full report in ZABAPGIT_FULL and update using it, as noted in https://docs.abapgit.org/guide-install.html

**Comment by sandraros** [comment]
Same issue while upgrading from 1.86.1 to 1.86.2 (+ issue #2406)

**Comment by larshp** [comment]
I think this is still a problem

**Comment by larshp** [comment]
closing, issue is getting old
