### ISSUE TITLE
UX - transport to branch

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#2618]
discussion from #2572 
## Transport to branch:
I can transport a task, but I can only enter a request ID, not a task ID. Then I have to find the task manually.
![image](https://user-images.githubusercontent.com/5097067/54902423-a7b46d00-4ed9-11e9-8f7f-4113b05eac9d.png)

Could the initial branch commit message be taken from the request/task longtext?

------------------

@sbcgua 
Transport to branch
Cool. +1
But 2 comments:

What if there are more than one transports ?
What if certain repo/system does not use transport management e.g. for some developments I just put everything in one transport and never release

----------------

_What if there are more than one transports ?_
Not sure I understand, but these seem to be unique:
![image](https://user-images.githubusercontent.com/5097067/54919687-c0387d80-4f01-11e9-9691-a15d5716496d.png)
They have the system ID at the start and are generated in increasing order, request and tasks combined.

_What if certain repo/system does not use transport management e.g. for some developments I just put everything in one transport and never release_

I guess you have no use for transport to branch then, or?

-----------------

transports: well, I'm not using this feature to be honest. At least yet. So would vote that it is not the obligatory way, there should be an option to turn it on/off for a certain repo imho.

-----------------

My additional notes: Transport to branch does not seem to be used much, but I had a very good use case last week where I had to find a method deleted in an older release as well as look for usages. 

I don't know of a good way of doing this with SAP transports as you can only easily compare one object at a time.

I can however make branches from these transports and compare across branches. I even did this across two packages by making the same transport branches in both. Then use vscode to add multiple folders into your workspace and search.

**Comment by mbtools** [comment]
Closing in fav of related issues:

- https://github.com/abapGit/abapGit/pull/5916
- https://github.com/abapGit/abapGit/issues/5672
- https://github.com/abapGit/abapGit/issues/5673
