### ISSUE TITLE
User exit: Additional files during serialization

### ISSUE THREAD

**Issue by kgorin8** [abapGit/abapGit#2663]
Hey. I was thinking about using abapGit as a basis for exporting documentation for objects. Is it possible to make plugins "non-exclusive", so that for example I export html document for PROG from a plugin but the PROG object still goes to it's respective serialization class?

**Comment by mbtools** [comment]
You can use `seriallize_postprocess` and `deserialize_postprocess`
https://docs.abapgit.org/ref-exits.html#exits
