### ISSUE TITLE
ECTC/ECATT: abapGit CI failed - diff

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#2722]
![image](https://user-images.githubusercontent.com/17437789/58690738-8add5f80-838a-11e9-826c-af1dd881cb83.png)

Demo repo
https://github.com/abapGit-tests/ECATT.git

**Comment by christianguenter2** [comment]
Error occurs only if abapGit CI runs in background. Then local xml diffs.

![image](https://user-images.githubusercontent.com/17437789/59632220-fe80ba00-9149-11e9-983e-fede089de13c.png)

![image](https://user-images.githubusercontent.com/17437789/59632219-fcb6f680-9149-11e9-93e0-a77213e80b95.png)

**Comment by mbtools** [comment]
Works with 754 SP 7 and latest abapGit
