### ISSUE TITLE
Show performance metrics for time consuming operations

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#2727]
People care more about performance when they actually see measurable numbers. It also makes it easier to spot a degradation between different versions or as a consequence of repository growth.

We should display the time it took to execute
- serialization
- deserialization
- syntax check
- code inspector

either as a message after it is done or somewhere on the result page

Even google considers this the first thing it should show you:
![image](https://user-images.githubusercontent.com/5097067/61001892-c2afcd80-a360-11e9-8fa5-d1f71ce88060.png)

**Comment by sbcgua** [comment]
Imho, debug pane at the bottom would be a good place. Messages can be too distracting to show them to all unconditionally. (There is a div with debug id, used for js output, but should be no problem to add some message list to output from abap)

**Comment by FreHu** [comment]
You don't want to hide the information from the user, but I agree that a message is too annoying. For syntax check/inspection you can easily put it somewhere on top of the page. For serialization, maybe the log from #2729 could be utilized.

**Comment by g-back** [comment]
Prototype for syntax check/Inspection (syntax check is technically an inspection too), on success:
![image](https://user-images.githubusercontent.com/27279305/68390460-a46aaa80-0165-11ea-9b3d-da25e8113ea5.png)
Would this be all right like this?

In the case of an inspection with findings: where would be the best place to put the metric? On top? Bottom? Should it somehow be highlighted by background color, something else?

**Comment by FreHu** [comment]
I agree that syntax check is an inspection (you could even set up a variant to do just syntax check) and would like the two pages to be as similar as possible.

Code inspector has this nice bar below the buttons:
![image](https://user-images.githubusercontent.com/5097067/68391914-dfbaa880-0168-11ea-85f7-b80985419e4a.png)

We could easily fit the information there.

![image](https://user-images.githubusercontent.com/5097067/68392264-b64e4c80-0169-11ea-94a7-e0b6e5d1bbf0.png)

- This way the metrics can be in the same place for both success and failure. 
- I'd use a neutral color for the message and report the time in seconds with two decimals

**Comment by mbtools** [comment]
Backend runtime is available when hovering over footer logo (https://github.com/abapGit/abapGit/pull/5043)

It could be more visible by moving it to the left side of the footer (opposite of "js:ok")
