### ISSUE TITLE
Improve error information - follow up

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#2811]
Follow up to #2775 and #1998.

- [x] Bug: Errorenous regex for message class and id. Best to get rid of it.
https://github.com/larshp/abapGit/blob/5081ddf7d08ec7cc02ec031cae0349763b123c9a/src/ui/zcl_abapgit_gui_chunk_lib.clas.abap#L163-L189
- [x] Refactor: Remove dynamic instantiation of ZCL_ABAPGIT_MESSAGE_HELPER somehow
https://github.com/larshp/abapGit/blob/5081ddf7d08ec7cc02ec031cae0349763b123c9a/src/zcx_abapgit_exception.clas.abap#L95-L114
- [x] Improve tooltip of "Goto source" link
![image](https://user-images.githubusercontent.com/17437789/62007471-0cb0f580-b14e-11e9-9afc-ea5e3cd7f9b0.png)
https://github.com/larshp/abapGit/blob/5081ddf7d08ec7cc02ec031cae0349763b123c9a/src/ui/zcl_abapgit_gui_chunk_lib.clas.abap#L233-L238
https://github.com/larshp/abapGit/pull/2775#discussion_r306390278
- [x] Check whether ROLLBACK should be decoupled from UI again.
https://github.com/larshp/abapGit/pull/2775#discussion_r305536671
- [x] Cleanup JS: Remove unnecessary functions (toggleDiplay, etc.)
https://github.com/larshp/abapGit/pull/2775#discussion_r306387234
- [x] Add tooltip for message class and id (e.g. raw message?)
![image](https://user-images.githubusercontent.com/17437789/62007542-ee97c500-b14e-11e9-8413-b701df0a661b.png)
https://github.com/larshp/abapGit/blob/5081ddf7d08ec7cc02ec031cae0349763b123c9a/src/ui/zcl_abapgit_gui_chunk_lib.clas.abap#L221-L227
- [x] Refactor CSS
https://github.com/larshp/abapGit/pull/2775#discussion_r306391068
- [x] Beautify message panel
https://github.com/larshp/abapGit/pull/2775#discussion_r306398751
- [x] Improve error information in log popup as well
- [x] Add icon in front of error message
![image](https://user-images.githubusercontent.com/17437789/62365931-bcf37500-b525-11e9-8c8e-af2fa3e236a8.png)

**Comment by mbtools** [comment]
- CSS refactor is in https://github.com/abapGit/abapGit/issues/3530
- I looked extensively at `zcl_abapgit_message_helper` (https://github.com/abapGit/abapGit/pull/3943). I don't see a way to avoid the dynamic call until we get rid of the standalone program, which is unlikely.
- Rollback can be configured in `zcl_abapgit_gui->constructor` (https://github.com/abapGit/abapGit/pull/3403)

-> Suggest to close this one

**Comment by mbtools** [comment]
Reviewed CSS issues with close button. They were fixed in https://github.com/abapGit/abapGit/pull/2819. 

This is complete now.
