### ISSUE TITLE
Error serializing: No matching task exists under request xxxxxxx for user xxxxxxx.

### ISSUE THREAD

**Issue by ABAPChris** [abapGit/abapGit#2844]
Hello, 

we tried to deserialize objects from a gerrit repository into SAP NW 7.50 by using ZABAPGIT. 
Deserializing works fine for many of the objects. But one object can not pulled because of the error message:

**No matching task exists under request xxxxxxx for user xxxxxxxx 
Import of object /WRP/ZDS_LOGTEST failed** 

This object is of type **TABL**. 

The diff is: 
![image](https://user-images.githubusercontent.com/53512054/62450398-88252f00-b76c-11e9-87a9-d531adfa58a8.png)

Does anybody knows the reason? Is this a bug in zabapgit?

Best Regards, 
Christian

**Comment by larshp** [comment]
is the object /WRP/ZDS_LOGTEST already present in a different transport/task? namely the request xxxxxxx ? and the user xxxxxxxx does not have a task under this request?

**Comment by ABAPChris** [comment]
The object is already in an other request/task included (status: released).
I tried to add the object to a new task of this request in which the object is  already included. 
But i got the same error. 
Christian

**Comment by larshp** [comment]
suggest releasing the other request first, or alternatively merging it into the target transport

**Comment by ABAPChris** [comment]
I'll try it out. Unfortunately I can only do that next week. After that I will get back to you. Thanks for the quick support. 
Christian

**Comment by ABAPChris** [comment]
I released all transport an tried to assign the object to a new transport but getting the same error.

**Comment by larshp** [comment]
so the error "No matching task exists under request xxxxxxx for user xxxxxxx" is for a a request that has been released?

**Comment by ABAPChris** [comment]
The original tasks and requests have been released. Then I tried again to use a completely new transport / request, but with the same error.

**Comment by larshp** [comment]
and the task/request mentioned in the error is released?

**Comment by ABAPChris** [comment]
yes

**Comment by mbtools** [comment]
FYI, if you are using namespaces, you might need *two tasks*: one for "development" and one for "repairs" 

This is the case, for example, if only the repair key is maintained
