### ISSUE TITLE
Object type ignored, not supported: FUGS, FUGX

### ISSUE THREAD

**Issue by sarfran** [abapGit/abapGit#2851]
When creating a Repo from a Package, the object types FUGS and FUGX are not processed, error message:
Object type ignored, not supported: FUGS-<Name>
Object type ignored, not supported: FUGX-<Name>

We used the latest abapGit Client (1.89.0), and also installed the abapGit Plugin.
Any idea how we can also process these?
Thanks!

**Comment by larshp** [comment]
currently not supported

FUGS	Function Group with Customer Include: SAP Part
FUGX	Function Group with Customer Include: Customer Part

**Comment by larshp** [comment]
FUGS objects are only for SAP internal use?

**Comment by fsarraz** [comment]
Thanks for the quick response! Both function groups are needed for Customer Includes, FUGS is not only for SAP internal use.

**Comment by larshp** [comment]
pull requests welcome, I currently dont have any good systems to test this on

**Comment by CASAG-MariusRaht** [comment]
I tried to create them but got the following message: EXIT modules are no longer supported

> Message no. FL049
> 
> Diagnosis
> As of release 5.0, the concept of SMOD/CMOD is not longer supported. For this reason, no new EXIT modules and groups can be created.
> 
> Procedure
> Use BADIs instead of EXIT modules.

**Comment by mbtools** [comment]
Not supported anymore. Closing
