### ISSUE TITLE
Branching can cause changes to be flipped 

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#2869]
Steps to reproduce:

1) Create repo
2) New online
3) Commit a class
4) Make change in the class
![SapGuiServer_lddbLyp93u](https://user-images.githubusercontent.com/5097067/63013387-6fafc580-be8c-11e9-8322-9d90f7d061c4.png)
5) Create new branch
6) Commit change to new branch
![image](https://user-images.githubusercontent.com/5097067/63013511-adace980-be8c-11e9-805d-20d69d06dac6.png)

7) Switch back to master

The changes are now backwards - Abapgit now shows my uncommitted addition as a deletion on master.
![chrome_7imNfgLALQ](https://user-images.githubusercontent.com/5097067/63013591-d7fea700-be8c-11e9-86f6-6e8cc39c2bab.png)

- Deleting the branch does not help.
- I only have the option to pull the change from remote

![image](https://user-images.githubusercontent.com/5097067/63013801-607d4780-be8d-11e9-9315-77d6198cf169.png)

This correctly reset my class to the state on the remote, but I had no way of committing my addition.

**Comment by flaiker** [comment]
> I only have the option to pull the change from remote

Does Advanced -> Force Stage allow you to commit the change?

**Comment by FreHu** [comment]
Yes. I also managed to unscrew the repo where I found the bug originally with `update local checksums`.

**Comment by flaiker** [comment]
Maybe related to #2086

**Comment by flaiker** [comment]
I guess the checksums should be rebuild on branch switch by calling `rebuild_local_checksums` in `zcl_abapgit_repo_online->set_branch_name`? I am not really sure how the whole status thing works.
https://github.com/larshp/abapGit/blob/f73e18d587d6e052655f7e3ab2eba04cc93e5cbc/src/zcl_abapgit_repo_online.clas.abap#L224-L229

**Comment by mbtools** [comment]
I can reproduce this scenario. However, I think abapGit behaves correctly (as designed).

I had the same question https://github.com/larshp/abapGit/issues/3519. Maybe we should make "Advanced > Reset Local" (which is "Force Pull") and "Advanced > Force Stage" more prominent. 

I would not be opposed to always having "Pull" and "Stage" available when there is a diff on any side. Like this:

BUILD_MAIN_TOOLBAR:
```
      IF iv_rstate IS NOT INITIAL. " Something new at remote
        ro_toolbar->add( iv_txt = 'Pull'
                         iv_act = |{ zif_abapgit_definitions=>c_action-git_pull }?{ mv_key }|
                         iv_opt = iv_pull_opt ).
      ELSE. " nothing new but we want to sync anyway
        ro_toolbar->add( iv_txt = 'Force Pull' ... ).  "<<< add this
      ENDIF.
      IF iv_lstate IS NOT INITIAL. " Something new at local
        ro_toolbar->add( iv_txt = 'Stage'
                         iv_act = |{ zif_abapgit_definitions=>c_action-go_stage }?{ mv_key }|
                         iv_opt = zif_abapgit_html=>c_html_opt-strong ).
      ELSE. " nothing new but we want to sync anyway
        ro_toolbar->add( iv_txt = 'Force Stage' ... ). "<<< add this
      ENDIF.
```

**Comment by larshp** [comment]
moving discussion to #3997, closing
