### ISSUE TITLE
Message container for unsupported objects disappears when returning from diff

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#2880]
If you have some unsupported object types in your repo a container appears listing these objects. When you then use the "view diff" button to display a diff and return with F3 the container is gone. This is a bit unintuitive because if you want to look through multiple diffs the cursor position is not as expected (view diff -> F3 -> move cursor one line down).

**Comment by mbtools** [comment]
"refresh" will show the list of unsupported objects again. keeping it always visible would be a bit annoying esp. if the list is long. or did you have something else in mind?

**Comment by mbtools** [comment]
We have diff per
- object
- file
- package (in folder view)
- all

I don't see an easy way to have a free selection. Close?

**Comment by mbtools** [comment]
Unsupported objects are shown again in the pull dialog (https://github.com/abapGit/abapGit/pull/6320)
