### ISSUE TITLE
APACK: Export versioned dependencies

### ISSUE THREAD

**Issue by SebastianWolf-SAP** [abapGit/abapGit#2893]
APACK currently doesn't feature any possibility to declare version numbers for dependencies. Both strict, half-open and unbounded version ranges (see also https://dzone.com/articles/manifestmf-and-featurexml ) should be supported to enable import tools (such as the abapGit ADT plugin) to tell the user if there are inconsistencies or conflicts.

**Comment by mbtools** [comment]
Closed via #2894
