### ISSUE TITLE
SKTD: Knowledge Transfer Document - Documentation Infrastructure

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#2997]
![image](https://user-images.githubusercontent.com/17437789/67424228-0d82e780-f5d6-11e9-8237-650ecbbe2e87.png)

**Comment by larshp** [comment]
@christianguenter2 can you help adding a few hints? I'm not sure how to create this thing in SE80

just trying to move the issue forward

**Comment by mariusraht2** [comment]
@larshp It's not possible to create the KTD in SE80 as it seems - one has to use ADT. You even can't open these objects in SE80 as it will state that you should please open it in ADT^^.

**Comment by christianguenter2** [comment]
Seems like it was already implemented by SAP in ABAP in the cloud as `CL_ABAPGIT_OBJECT_SKTD`.

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.
