### ISSUE TITLE
Diff filter - add 'changed by me' option

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#3021]
Usually people want to filter to their changes, but if there are many authors, it is tedious to deselect them one by one. 

Add a `me` filter to diff/patch similar to the one recently added to the stage list:
![image](https://user-images.githubusercontent.com/5097067/68012261-d4a7da00-fc89-11e9-8224-885ffb1890a7.png)

**Comment by sbcgua** [comment]
Cool idea. Maybe it is even worth to show earlier - I mean near the filter button to avoid unnessesary clicks. Or even on the main page near "Show diff" (which I'd rename to simply "Diff")

**Comment by wozjac** [comment]
Hi,

what about such solution?
![onlym](https://user-images.githubusercontent.com/20969653/116941048-3c6c2600-ac6f-11eb-8212-2a3f2246fa8c.gif)

"Only my changes" shows only your changes on the diff hits + jump list + sets your username in the "Changed by" list.
Disabling the option brings back all.

**Comment by sbcgua** [comment]
looks as a good option

**Comment by wozjac** [comment]
Pushed this feature here: https://github.com/wozjac/abapGit/tree/wozjac/my_changes_diff_filter.

**Comment by FreHu** [comment]
great! now you just need to make a pull request using this button:

![image](https://user-images.githubusercontent.com/5097067/117079040-4a877880-ad3b-11eb-9e2f-b1a04f5c4ec0.png)

**Comment by larshp** [comment]
@wozjac yea, please open a pull request with the changes, this will trigger CI, make the changes visible, and also easier to test(via the switch to PR feature in abapGit)
