### ISSUE TITLE
Revert to any single Commit

### ISSUE THREAD

**Issue by mariusraht2** [abapGit/abapGit#3040]
I didn't find this feature and need it so I suggest it: I think it would be useful to be able to revert to any single commit. For this it should be possible to select any existent commit and revert the repository to it.

Related to Issue #753.

**Comment by mariusraht2** [comment]
I could need some help on the following issue: I plan co to ask Git if a commit is existent. We only have a method which fetches all branches from Git, but not anything like it for commits. Does anyone know which request is to be send to Git to ask if a specific commit is existent in a branch?

It would be nice if the short and the long form (SHA1) of commits would be supported.

**Comment by larshp** [comment]
I dont have much time today or tomorrow, so remind me when I forget to answer 😄

**Comment by mariusraht2** [comment]
Added the question above also to [Stackoverflow](https://stackoverflow.com/questions/58799348/git-confirm-given-commit-is-existent-via-https-protocol).

**Comment by mariusraht2** [comment]
There are some minor optimizations to be made but if you want to try it - feel free. I'm pretty sure it's not perfect yet, so please give me feedback and tips how the process of reversion could be improved or what you expect from it!

**Comment by larshp** [comment]
cool

if possible, when doing the PR, try splitting it into multiple steps, I'd like to avoid large PRs

**Comment by mariusraht2** [comment]
![grafik](https://user-images.githubusercontent.com/45243391/69435779-804fc180-0d40-11ea-9a1c-99f8bfe48723.png)

**Comment by christianguenter2** [comment]
Small remark. Wouldn't 'Checkout commit' or 'Reset commit', depending on your implementation, be the appropriate git term? [Revert](https://git-scm.com/docs/git-revert) a commit means to undo its changes.

**Comment by mariusraht2** [comment]
- Yes, indeed; I prefer 'Checkout commit' because at the moment its possible to jump between the commits in a different branch
- Nothing, you have to stage the changes after an actual reset
- On Stage the remote (latest commit) and the development objects of the checked-out commit will be compared with eachother and you can push the 'changes' of the checked-out commit to the remote repo or pull everything and it 'resets' the local repo to the latest commit.

**Comment by mariusraht2** [comment]
Tend to look into step 5 - a user wouldn't suspect in step 3 on Pull that the latest commit is the referenced commit in this case and to avoid complexity. Now I only need to solve the problem that the changes can be staged if the latest commit is checked-out.

**Comment by mariusraht2** [comment]
It seems after the local reset via 'Checkout Commit' the dev objects aren't marked as 'changed' and therefore Staging isn't possible. But Force Stage could be used in this case already.

**Comment by mariusraht2** [comment]
Just for documentation: [Result.docx](https://github.com/larshp/abapGit/files/3952761/Result.docx)

**Comment by larshp** [comment]
sorry, I've removed the linked word file, no need to share files that potentially can contain bad stuff

**Comment by mariusraht2** [comment]
Ok, no problem - will avoid upload microsoft documents in the future.

**Comment by mariusraht2** [comment]
Does anyone know a way to add a button to the popup RS_VALUES_BOX or REUSE_ALV_POPUP_TO_SELECT? Neither of them seems to support this :(. I thought about adding a button "Load more..." to be able to save some performance. 

Instead of loading all commits for a branch which would take approxiametly an hour or more (^.^) I select only commit til a specific level (e.g. "deepen 30"). I want to optimize this algorithm though: Thought about selecting by commit parent and go futher down the hierarchie if a specific amount of commits wasn't loaded.

**Comment by mariusraht2** [comment]
For now I chose to just add another entry "Load more..." because the other reasonable option (own page) would take too much time - want to test it some time and release this bit by bit.

**Comment by mariusraht2** [comment]
Implementation is nearly done. Only one small problem with loading more commits: It seems I have to do a http request with a rising deepen level to get all sub commits of a branch, which is really time conduming at a specific deepen level. My first approach was to get sub commits by the last gotten sub commit but it seems sometimes not every older commit is being fetched due to the commit hierarchie. 

So I suggest we limit the 'load more' function to a specific value (e. g. max. last 100 commits) and fetch them always by deepen level 100.

**Comment by larshp** [comment]
some of the new git features supports only getting the commits, and ignoring the blobs, guess it can be used in this case, like for the branch overview page

**Comment by mariusraht2** [comment]
Yes, I already reuse the related function like it is being used in branch overview page. But it's just very time-consuming to load over 3000 commits (> 8 Minutes). So we have to limit it. Yet I don't know how to do it.

**Comment by mariusraht2** [comment]
@larshp I plan to ship the changes now in the following chunks:

**MODEL:**
zcl_abapgit_git_commit
zcl_abapgit_git_object 
zcl_abapgit_git_porcelain
zcl_abapgit_git_transport
zif_abapgit_persistence
zcl_abapgit_branch_overview
zcl_abapgit_repo
zcl_abapgit_repo_online
zif_abapgit_definitions

**GUI:**
zcl_abapgit_gui_chunk_lib 
zcl_abapgit_gui_page_boverview
zcl_abapgit_gui_page_commit
zcl_abapgit_gui_page_main
zcl_abapgit_gui_page_merge 
zcl_abapgit_popups  
zcl_abapgit_services_repo 
zif_abapgit_popups 

**LOGIC:**
zcl_abapgit_gui_router 
zcl_abapgit_gui_view_repo 
zcl_abapgit_services_git 

Is this ok with you?

**Comment by larshp** [comment]
yea, some of the classes I would not expect any changes to, but lets see

**Comment by sandraros** [comment]
Some people [asked](https://answers.sap.com/questions/13698511/abapgit-revert-to-specific-commit.html) where the commit can be selected, maybe this can be useful to comment here with a screenshot. Select the repository, click Settings, and then:
![image](https://user-images.githubusercontent.com/34005250/183932503-7db18aeb-09fa-41cb-bd0c-20b1b81f6342.png)
