### ISSUE TITLE
Add severity as attribute to `zcx_abapgit_exception` for `zif_abapgit_log`

### ISSUE THREAD

**Issue by mariusraht2** [abapGit/abapGit#3071]
I think a reasonable change would be to add severity as an attribute of `zcx_abapgit_exception` for `zif_abapgit_log` to decide on.

_Originally posted by @FreHu in https://github.com/larshp/abapGit/pull/3034#issuecomment-553414903_

**Comment by FreHu** [comment]
I'm not gonna go with that PR after all, but I still think it is a good idea in general.

**Comment by larshp** [comment]
old issue, either its implemented or not needed, closing
