### ISSUE TITLE
idoc segment not set to released after pull

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#3072]
Steps to reproduce:
1: pull https://github.com/abapGit-tests/IDOC_segment_released
2: check diff

I'm installing to local package

![image](https://user-images.githubusercontent.com/5888506/69125268-b7567680-0aa5-11ea-8620-2162cdf2fc3a.png)

**Comment by ibnbr** [comment]
For this need to call de FM SEGMENTDEFINITION_CLOSE, but the difference still may happen depending what SAP System Version its is installing.

![image](https://user-images.githubusercontent.com/2778247/69146332-6303c480-0aae-11ea-9bfb-e8bce7485a49.png)

Close the IDOC SEGEMENT cause problem to uninstall the Package, maybe need to call FM SEGMENTDEFINITION_UNCLOSE before uninstall the package, but in my tests it doesn't work 100% of the time.

**Comment by larshp** [comment]
we need to do something else then, for idocs I think its important that the release matches, and it should not be cleared

**Comment by larshp** [comment]
and if the segment is released, then pulling it gives error "Last segment definition ZFOOBAR000 has been released and cannot be changed"

**Comment by larshp** [comment]
probably still a problem, pull requests welcome

however its not been an issue for me for some time, closing
