### ISSUE TITLE
Convert package $ABAPGIT_SYNTAX into an autonomous project

### ISSUE THREAD

**Issue by nununo** [abapGit/abapGit#3075]
I would like to use the code from $ABAPGIT_SYNTAX package to highlight code in another open source project I'm working on.

It would be great if this set of classes could be factored out into its own open source project and reviewed (if needed) to have a well defined reusable API.

Then APACK could be used to say that abapGit depends on it. Then I could do the same.

And who knows maybe we can identify more parts of abapGit which could become autonomous and reusable.

Is this feasible?

**Comment by larshp** [comment]
its not easy to bootstrap, and APACK only works in ABAP cloud

if your project is installed via abapGit, just assume the code is there and call the classes?

**Comment by nununo** [comment]
Ah, I had forgotten that APACK only works in ABAP cloud :(

This will be an open source project so it must be self-suficient. For now I'll have to copy the classes, giving you proper credit for them of course! ;)

**Comment by larshp** [comment]
I did not build that part

**Comment by mbtools** [comment]
One day we might have "ABAP Libraries" and then we can revisit this (and many other parts of AG). Until then copy away with MIT license.
