### ISSUE TITLE
Support for ABAPGIT after SSO enablement of enterprise github

### ISSUE THREAD

**Issue by dassharma** [abapGit/abapGit#3113]
By the end of January 2020, our organisation is enabling SSO for the enterprise version of github. I use ABAPGIT for pushing code to the repositories created in the enterprise version of github.

How can I adapt or what configurations are required in SAP GUI to enable SSO verification?

Thanks in advance.

**Comment by jfilak** [comment]
Need to mention that our SSO is based on private SSL certificates.

**Comment by larshp** [comment]
Need to do something like described in https://help.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on

I dont have access to any SSO/SAML setup, so its difficult to test for me

**Comment by jfilak** [comment]
Is there a way how to get my client SSL cert from Operating system (Windows) without the need to save it in STRUST?

**Comment by jfilak** [comment]
Our start screen opens an URL which does SSO autohrization too. By accident, I have 2 SSO certs and  SAPGUI asks me to single out one. So, I guess there must by some way how to get the cert also for abapGit.

**Comment by larshp** [comment]
pull requests welcome, its difficult to test and build without a SAML setup

**Comment by larshp** [comment]
I just tried https://docs.github.com/en/github/authenticating-to-github/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on and it seems to work in the setup I have access to

**Comment by larshp** [comment]
closing
