### ISSUE TITLE
ENHO: Store source code in separate .ABAP file?

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#3126]
Currently we store the source code of implicit source code enhancements in the xml of ENHO. I see some value in storing the source in separate .ABAP files. Especially as the code is escaped in the xml.

![image](https://user-images.githubusercontent.com/17437789/71015260-90ff1780-20f3-11ea-965d-341b583911b7.png)

https://github.com/abapGit-tests/ENHO/blob/efd3420bb1229e873f10fb4d7067242dd1b9166f/src/ztest_implicit_enho.enho.xml#L32-L38

Not entirely sure whether we should do that and about the implementation as there can be multiple ABAP "sections" in one ENHO object.

**Comment by larshp** [comment]
yea, we should look ingo possible solutions, just afraid it will become a lot of files

I typically recommend to quickly branch off the code into a global class, instead of having multiple lines of code in the ENHO

**Comment by mbtools** [comment]
I have an implementation that puts the code into a separate file. Number of files will be similar to function groups (a few). I don't see that's as a problem.

Existing format on remote side, new format on local side:

![image](https://user-images.githubusercontent.com/59966492/120790865-c7249700-c533-11eb-96c3-0c14f5ea9284.png)

![image](https://user-images.githubusercontent.com/59966492/120790943-dc012a80-c533-11eb-916a-e35ba1fb3c83.png)

The new implementation can still read the old format and deserialize it. However, the new files won't be compatible with previous AG versions. The impact is only on ENHO of type HOOK_IMPL, but if I see it right this requires increasing the XML version for ENHO in general. Or do you see a way to do it only for HOOK_IMPL?

**Comment by mbtools** [comment]
Closed by #4951
