### ISSUE TITLE
what control subpackage orginal language?

### ISSUE THREAD

**Issue by hsingll** [abapGit/abapGit#3138]
There is no language tag in subpackage XML file.I think it will keep same as abapGit package master language.

But when I pull this repository with logon language EN,it shows there is difference between logon language EN and original language ZH about subpackage.
It really confused me.
![Snipaste_0107-113851](https://user-images.githubusercontent.com/26346635/71866755-4c8af880-3142-11ea-9c75-14c2b5adee31.png)

PS：after pull and active all objects,I check TADIR and TDEVCT table,all objects and subpack is created in EN,Not ZH the orginal language even if I chose "maint. in orig. lang.".

**Comment by BlackmanCC** [comment]
I have the same issue here. My usual logon language is DE, but Im installed abapGit with logon language EN. All abapGit-objects in TADIR have master language E, but when updating abapGit I also get the popup.

**Comment by larshp** [comment]
not sure, the popup is from SAP standard, suggest debugging

**Comment by larshp** [comment]
hmm, guess the easiest workaround is to logon in the master language

**Comment by larshp** [comment]
no idea, closing
