### ISSUE TITLE
IOBJ - check dependencies between objects and set import queue

### ISSUE THREAD

**Issue by pawelwiejkut** [abapGit/abapGit#3155]
Hello!
As already mentioned in https://github.com/larshp/abapGit/pull/3146#issuecomment-572171435 and https://github.com/larshp/abapGit/pull/3147#issuecomment-573078610, we have an issue during import of few IOBJ with dependencies in the wrong order.

**Comment by larshp** [comment]
thanks, can you help opening a pull request to https://github.com/abapGit/IOBJ_dependencies with an example of the problem?

**Comment by mbtools** [comment]
Since https://github.com/abapGit/abapGit/pull/6229, [`get_deserialze_order`](https://docs.abapgit.org/development-guide/serializers/serializers.html) is available to be implemented. However, it's not trivial to find the correct order of InfoObjects. 

Not realistic. Closing
