### ISSUE TITLE
Uninstalling repository dependent objects

### ISSUE THREAD

**Issue by jrodriguez-rc** [abapGit/abapGit#3228]
I was trying to uninstall a repository but it wasn't uninstalled but a CDS was causing an error. I tried then to remove all objects manually and I checked that CDS cannot be removed because it was used in other CDS.

This could happen also with other objects like structures or tables.

**Comment by larshp** [comment]
yea, perpahs do a consistency check that everything is only referred inside the package

https://github.com/larshp/abapGit/issues/2467

**Comment by jrodriguez-rc** [comment]
The error is that referenced CDS were in the same package

**Comment by christianguenter2** [comment]
Is this just related with abapGit? I had several issues with CDS views outside of abapGit too. Particularily while deleting them.

**Comment by mbtools** [comment]
https://github.com/larshp/abapGit/pull/3726 has fixed a few dependency issues. @jrodriguez-rc do you have a test repo for this case?

**Comment by jrodriguez-rc** [comment]
I haven't, I'll check with [hardyp/AbapToTheFuture03](https://github.com/hardyp/AbapToTheFuture03) repository

**Comment by larshp** [comment]
suggest making a public repository with a minimal reproducible example

can be stored under https://github.com/abapGit-tests for future tests

**Comment by mbtools** [comment]
#3959 brought several improvements. Uninstalling CDS views with dependencies (like in abaptothefuture repo) should work now.

**Comment by larshp** [comment]
@jrodriguez-rc try again, latest version

**Comment by jrodriguez-rc** [comment]
I tried with [hardyp/AbapToTheFuture03](https://github.com/hardyp/AbapToTheFuture03), remains some empty packages:
![image](https://user-images.githubusercontent.com/56556686/99370828-73679e80-28be-11eb-92c7-cd0aacb57531.png)

But all the content is deleted, included the CDS, so I'll close this issue. Thank you @mbtools

**Comment by mbtools** [comment]
Check in tadir. What’s left in the packages? Just the main and sub packs or more?

**Comment by jrodriguez-rc** [comment]
Just packages, I could delete them with right-click -> delete

**Comment by mbtools** [comment]
I thought that was taken care off. I will check. Anyway thx for testing (since I don’t have a Hana box at the moment)
