### ISSUE TITLE
WIP: Development Guidelines -Prefixes- docs

### ISSUE THREAD

**Issue by jrodriguez-rc** [abapGit/abapGit#3239]
In the documentation is specified that the development of abapGit uses the standard settings from abapOpenChecks.

I was preparing an SCI variant to upload to the repository and use it but performing ATC check I have a lot of bad naming messages (129).

Something I checked is that constants are defined as `C_` instead `GC_`

Bad naming,   expected PV_, got IV_REPO_URL | $ABAPGIT | ZABAPGIT | 129 | PROG
-- | -- | -- | -- | --
Bad naming, expected LS_, got LT_FILES | $ABAPGIT | ZABAPGIT_PARALLEL | 21 | FUGR
Bad naming, expected C_, got CO_RUN_MODE | $ABAPGIT | ZCL_ABAPGIT_CODE_INSPECTOR | 44 | CLAS
Bad naming, expected LV_, got LS_NEW | $ABAPGIT_UTILS | ZCL_ABAPGIT_DIFF | 37 | CLAS
Bad naming, expected LV_, got LS_OLD | $ABAPGIT_UTILS | ZCL_ABAPGIT_DIFF | 44 | CLAS
Bad naming, expected C_, got   CO_STARTING_BEACON | $ABAPGIT_UTILS | ZCL_ABAPGIT_DIFF | 6 | CLAS
Bad naming, expected LV_, got LS_REGEX | $ABAPGIT_UTILS | ZCL_ABAPGIT_DIFF | 406 | CLAS
Bad naming, expected IV_, got   IM_OBJECT_TYPE | $ABAPGIT_OBJECTS_ECATT | ZCL_ABAPGIT_ECATT_HELPER | 7 | CLAS
Bad naming, expected IV_, got   IM_OBJECT_VERSION | $ABAPGIT_OBJECTS_ECATT | ZCL_ABAPGIT_ECATT_HELPER | 7 | CLAS
Bad naming, expected IV_, got   IM_OBJECT_NAME | $ABAPGIT_OBJECTS_ECATT | ZCL_ABAPGIT_ECATT_HELPER | 7 | CLAS
Bad naming, expected C_, got CO_XML | $ABAPGIT_OBJECTS_ECATT | ZCL_ABAPGIT_ECATT_HELPER | 35 | CLAS
Bad naming, expected <LG_, got   <LV_D_AKH> | $ABAPGIT_OBJECTS_ECATT | ZCL_ABAPGIT_ECATT_SP_UPLOAD | 97 | CLAS
Bad naming, expected <LG_, got   <LV_I_AKH> | $ABAPGIT_OBJECTS_ECATT | ZCL_ABAPGIT_ECATT_SP_UPLOAD | 98 | CLAS
Bad naming, expected <LG_, got   <LV_D_AKH> | $ABAPGIT_OBJECTS_ECATT | ZCL_ABAPGIT_ECATT_VAL_OBJ_UPL | 224 | CLAS
Bad naming, expected <LG_, got   <LV_I_AKH> | $ABAPGIT_OBJECTS_ECATT | ZCL_ABAPGIT_ECATT_VAL_OBJ_UPL | 225 | CLAS
Bad naming, expected LR_, got LO_MARKER | $ABAPGIT | ZCL_ABAPGIT_ENVIRONMENT | 28 | CLAS
Bad naming, expected RI_, got   RO_ENVIRONMENT | $ABAPGIT | ZCL_ABAPGIT_FACTORY | 34 | CLAS
Bad naming, expected GI_, got   GO_ENVIRONMENT | $ABAPGIT | ZCL_ABAPGIT_FACTORY | 76 | CLAS
Bad naming, expected LI_, got LO_PACKAGE | $ABAPGIT | ZCL_ABAPGIT_FILE_STATUS | 460 | CLAS
Bad naming, expected II_, got IO_PAGE | $ABAPGIT_UI_CORE | ZCL_ABAPGIT_GUI | 31 | CLAS
Bad naming, expected LV_, got   LC_CSS_BUILD | $ABAPGIT_UI_CORE | ZCL_ABAPGIT_GUI_HTML_PROCESSOR | 83 | CLAS
Bad naming, expected LC_, got C_CSS_CLASS | $ABAPGIT_UI | ZCL_ABAPGIT_GUI_PAGE_DIFF | 1008 | CLAS
Bad naming, expected LI_, got LO_FE_SERV | $ABAPGIT_UI | ZCL_ABAPGIT_GUI_ROUTER | 179 | CLAS
Bad naming, expected C_, got   MC_HOTKEY_INTERFACE | $ABAPGIT_UI | ZCL_ABAPGIT_HOTKEYS | 24 | CLAS
Bad naming, expected LS_, got   LT_TYPE_INFOS | $ABAPGIT_UI | ZCL_ABAPGIT_HOTKEYS | 149 | CLAS
Bad naming, expected II_, got   IO_ENVIRONMENT | $ABAPGIT | ZCL_ABAPGIT_INJECTOR | 25 | CLAS
Bad naming, expected C_, got   GC_SECTION_TEXT | $ABAPGIT | ZCL_ABAPGIT_MESSAGE_HELPER | 8 | CLAS
Bad naming, expected C_, got   GC_SECTION_TOKEN | $ABAPGIT | ZCL_ABAPGIT_MESSAGE_HELPER | 14 | CLAS
Bad naming, expected LV_, got LS_STRING | $ABAPGIT | ZCL_ABAPGIT_MESSAGE_HELPER | 171 | CLAS
Bad naming, expected <LG_, got   <LV_ARG> | $ABAPGIT | ZCL_ABAPGIT_MESSAGE_HELPER | 278 | CLAS
Bad naming, expected LI_, got LO_LOG | $ABAPGIT | ZCL_ABAPGIT_OBJECTS | 48 | CLAS
Bad naming, expected <LS_, got   <LV_FILE> | $ABAPGIT | ZCL_ABAPGIT_OBJECTS | 310 | CLAS
Bad naming, expected MI_, got   MO_PERSISTENCE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECTS_SAXX_SUPER | 27 | CLAS
Bad naming, expected MI_, got   MO_APPL_OBJ_DATA | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECTS_SAXX_SUPER | 28 | CLAS
Bad naming, expected IG_, got   IV_OBJECT_CLASS | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECTS_SUPER | 37 | CLAS
Bad naming, expected <LT_, got   <LG_DATA_BASEINFO> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_DDLS | 331 | CLAS
Bad naming, expected <LG_, got   <LS_DATA_BASEINFO> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_DDLS | 332 | CLAS
Bad naming, expected MI_, got   MO_PERSISTENCE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_DDLX | 7 | CLAS
Bad naming, expected CG_, got CS_DATA | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_DDLX | 13 | CLAS
Bad naming, expected CG_, got CS_METADATA | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_DDLX | 16 | CLAS
Bad naming, expected C_, got CO_NAME | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ECATT_SUPER | 46 | CLAS
Bad naming, expected C_, got   CO_DEFAULT_VERSION | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ECATT_SUPER | 50 | CLAS
Bad naming, expected LI_, got LO_ELEMENT | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ECATT_SUPER | 144 | CLAS
Bad naming, expected LI_, got LO_ELEMENT | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ECATT_SUPER | 159 | CLAS
Bad naming, expected LI_, got LO_NODE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ECATT_SUPER | 346 | CLAS
Bad naming, expected LI_, got   LO_VERSION_NODE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ECATT_SUPER | 491 | CLAS
Bad naming, expected <LV_, got   <LS_COMPOSITE_CHILD> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ENHC | 75 | CLAS
Bad naming, expected <LV_, got   <LS_ENH_CHILD> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ENHC | 76 | CLAS
Bad naming, expected LV_, got LS_ORDER | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_FORM | 223 | CLAS
Bad naming, expected CG_, got CS_HEADER | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_FTGL | 21 | CLAS
Bad naming, expected <LG_, got   <LS_TOGGLE> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_FTGL | 81 | CLAS
Bad naming, expected <LG_, got   <LS_TOGGLE> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_FTGL | 177 | CLAS
Bad naming, expected <LG_, got   <LV_FIELD> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_FTGL | 215 | CLAS
Bad naming, expected MI_, got MO_MIME_API | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IAMU | 15 | CLAS
Bad naming, expected RI_, got RO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 17 | CLAS
Bad naming, expected II_, got IO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 21 | CLAS
Bad naming, expected II_, got IO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 25 | CLAS
Bad naming, expected II_, got IO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 28 | CLAS
Bad naming, expected II_, got IO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 31 | CLAS
Bad naming, expected II_, got IO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 35 | CLAS
Bad naming, expected RI_, got RO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 39 | CLAS
Bad naming, expected II_, got IO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 43 | CLAS
Bad naming, expected II_, got IO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 47 | CLAS
Bad naming, expected LI_, got LO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 61 | CLAS
Bad naming, expected LI_, got LO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 88 | CLAS
Bad naming, expected LI_, got LO_TEMPLATE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IATU | 120 | CLAS
Bad naming, expected MV_, got   MC_SOURCE_STYLE_2006 | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IAXU | 8 | CLAS
Bad naming, expected MV_, got   MC_GENERATOR_CLASS | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IAXU | 9 | CLAS
Bad naming, expected <LG_, got   <LO_XML_API> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IAXU | 81 | CLAS
Bad naming, expected <LG_, got   <LO_XML_API> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IAXU | 133 | CLAS
Bad naming, expected CG_, got   CS_STRUCTURE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IDOC | 11 | CLAS
Bad naming, expected CG_, got   CS_STRUCTURE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IDOC | 23 | CLAS
Bad naming, expected <LG_, got   <LV_ANY_FIELD> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IDOC | 34 | CLAS
Bad naming, expected CG_, got CS_METADATA | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IOBJ | 10 | CLAS
Bad naming, expected <LG_, got   <LV_TSTPNM> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IOBJ | 29 | CLAS
Bad naming, expected <LG_, got   <LS_VIOBJ> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IOBJ | 30 | CLAS
Bad naming, expected <LG_, got   <LS_DETAILS> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IOBJ | 123 | CLAS
Bad naming, expected <LG_, got   <LS_INFOOBJECT> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IOBJ | 132 | CLAS
Bad naming, expected <LG_, got   <LV_OBJSTAT> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IOBJ | 274 | CLAS
Bad naming, expected <LG_, got   <LS_VIOBJ> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IOBJ | 275 | CLAS
Bad naming, expected <LG_, got   <LS_DETAILS> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_IOBJ | 338 | CLAS
Bad naming, expected LS_, got LV_T100A | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_MSAG | 263 | CLAS
Bad naming, expected CG_, got CS_METADATA | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ODSO | 17 | CLAS
Bad naming, expected <LG_, got   <LS_DETAILS> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ODSO | 34 | CLAS
Bad naming, expected <LG_, got   <LV_TSTPNM> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ODSO | 35 | CLAS
Bad naming, expected <LG_, got   <LS_DETAILS> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ODSO | 124 | CLAS
Bad naming, expected <LG_, got   <LS_DETAILS> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_ODSO | 282 | CLAS
Bad naming, expected IT_, got   IS_ELEMENTS_DATA | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_PINF | 46 | CLAS
Bad naming, expected CG_, got CS_HEADER | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SMTG | 21 | CLAS
Bad naming, expected <LG_, got   <LS_TEMPLATE> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SMTG | 89 | CLAS
Bad naming, expected <LG_, got   <LS_HEADER> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SMTG | 90 | CLAS
Bad naming, expected <LG_, got   <LV_NAME> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SMTG | 93 | CLAS
Bad naming, expected <LG_, got   <LV_DESCRIPTION> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SMTG | 94 | CLAS
Bad naming, expected <LG_, got   <LV_HEADER_TEXT> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SMTG | 95 | CLAS
Bad naming, expected <LG_, got   <LS_TEMPLATE> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SMTG | 255 | CLAS
Bad naming, expected <LG_, got   <LS_HEADER> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SMTG | 256 | CLAS
Bad naming, expected <LG_, got   <LV_FIELD> | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SMTG | 323 | CLAS
Bad naming, expected LT_, got LV_TEXT_TAB | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SOTS | 55 | CLAS
Bad naming, expected C_, got   ATTRIB_ABAPGIT_LEADIG_SPACES | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SSFO | 14 | CLAS
Bad naming, expected C_, got   TRANSOBJECTTYPE_CLASS | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SUSC | 8 | CLAS
Bad naming, expected LS_, got LV_CLSKEY | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_SUSO | 95 | CLAS
Bad naming, expected C_, got CO_VIEWCLASS | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_VIEW | 17 | CLAS
Bad naming, expected LS_, got LV_ENQUEUE | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_XINX | 72 | CLAS
Bad naming, expected LS_, got   LV_TRANSP_KEY | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_XINX | 76 | CLAS
Bad naming, expected LS_, got LV_DD12V | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OBJECT_XINX | 254 | CLAS
Bad naming, expected RI_, got   RO_OBJECT_ORIENTED_OBJECT | $ABAPGIT_OBJECTS | ZCL_ABAPGIT_OO_FACTORY | 5 | CLAS
Bad naming, expected <LG_, got   <LV_DST> | $ABAPGIT_PERSIST | ZCL_ABAPGIT_PERSISTENCE_REPO | 231 | CLAS
Bad naming, expected <LG_, got   <LV_SRC> | $ABAPGIT_PERSIST | ZCL_ABAPGIT_PERSISTENCE_REPO | 232 | CLAS
Bad naming, expected LI_, got LO_PACKAGE | $ABAPGIT | ZCL_ABAPGIT_REPO_SRV | 165 | CLAS
Bad naming, expected LI_, got   LO_USER_PERSISTENCE | $ABAPGIT_UI | ZCL_ABAPGIT_SERVICES_ABAPGIT | 70 | CLAS
Bad naming, expected <LG_, got   <LS_CONTEXT> | $ABAPGIT_UI | ZCL_ABAPGIT_SERVICES_ABAPGIT | 147 | CLAS
Bad naming, expected LI_, got LO_PACKAGE | $ABAPGIT_UI | ZCL_ABAPGIT_SERVICES_ABAPGIT | 313 | CLAS
Bad naming, expected LI_, got LO_POPUPS | $ABAPGIT_UI | ZCL_ABAPGIT_SERVICES_GIT | 148 | CLAS
Bad naming, expected <LV_, got   <LS_PACKAGE> | $ABAPGIT | ZCL_ABAPGIT_TRANSPORT | 294 | CLAS
Bad naming, expected C_, got GC_ZIP_EXT | $ABAPGIT | ZCL_ABAPGIT_TRANSPORT_MASS | 113 | CLAS
Bad naming, expected IG_, got IV_LOGIC | $ABAPGIT | ZCL_ABAPGIT_TRANSPORT_MASS | 118 | CLAS
Bad naming, expected MV_, got   GV_TIMESTAMP | $ABAPGIT | ZCL_ABAPGIT_TRANSPORT_MASS | 129 | CLAS
Bad naming, expected MV_, got   GV_SEPARATOR | $ABAPGIT | ZCL_ABAPGIT_TRANSPORT_MASS | 130 | CLAS
Bad naming, expected MV_, got   GV_FULL_FOLDER | $ABAPGIT | ZCL_ABAPGIT_TRANSPORT_MASS | 131 | CLAS
Bad naming, expected LX_, got LO_EXCEPT | $ABAPGIT | ZCL_ABAPGIT_TRANSPORT_MASS | 25 | CLAS
Bad naming, expected LI_, got LO_POPUPS | $ABAPGIT_UI | ZCL_ABAPGIT_UI_INJECTOR | 109 | CLAS
Bad naming, expected LI_, got LO_POPUPS | $ABAPGIT_UI | ZCL_ABAPGIT_UI_INJECTOR | 138 | CLAS
Bad naming, expected C_, got   GC_AUTHORIZATION | $ABAPGIT | ZIF_ABAPGIT_AUTH | 5 | INTF
Bad naming, expected IO_, got IX_ERROR | $ABAPGIT_UI_CORE | ZIF_ABAPGIT_GUI_ERROR_HANDLER | 4 | INTF
Bad naming, expected RI_, got RO_HTML | $ABAPGIT_UI_CORE | ZIF_ABAPGIT_GUI_RENDERABLE | 4 | INTF
Bad naming, expected C_, got GC_STEP_ID | $ABAPGIT_OBJECTS | ZIF_ABAPGIT_OBJECT | 13 | INTF
Bad naming, expected RS_, got   RV_TRANSPORT_TYPE | $ABAPGIT | ZIF_ABAPGIT_SAP_PACKAGE | 24 | INTF
Bad naming, expected C_, got   GC_XML_VERSION | $ABAPGIT | ZIF_ABAPGIT_VERSION | 4 | INTF
Bad naming, expected C_, got   GC_ABAP_VERSION | $ABAPGIT | ZIF_ABAPGIT_VERSION | 5 | INTF

**Comment by larshp** [comment]
yea

regarding constants I'd like to fix it via https://github.com/abaplint/abaplint/issues/716, also abaplint does not check the types just yet

the abaplint configuration is a lot easier to manage, also see https://blogs.sap.com/2020/02/01/running-abaplint-from-sci-atc-adt/

**Comment by jrodriguez-rc** [comment]
I mean, I am doing a revision of checks specified in the documentation to update the code in [this branch](https://github.com/jrodriguez-rc/abapGit/tree/abapOpenChecks) and I renamed constants to `C_`, is that better than `GC_`?

**Comment by larshp** [comment]
suggest starting out renaming the non-constants fields

**Comment by jrodriguez-rc** [comment]
I created a PR #3240 (actually as a draft) renaming all except constants

**Comment by jrodriguez-rc** [comment]
Released first PR #3240 renaming all except constants

**Comment by jrodriguez-rc** [comment]
Now only constants need to be renamed, when naming is decided I will change them and create a new PR

**Comment by jrodriguez-rc** [comment]
@larshp maybe an SCI variant should be generated for abapGit with naming prefixes and more checks

**Comment by larshp** [comment]
yea, but its difficult to manage

I'll add functionality in abaplint to check the prefixes, then its easy to run, and could potentially quick-fix the current issues

**Comment by larshp** [comment]
closing, ok for now
