### ISSUE TITLE
Diff/Patch - improvement to filter by type

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#3249]
Use case: I would like to be able to hide for example all diffs in message classes or test data containers, which will both fall under xml.

![image](https://user-images.githubusercontent.com/5097067/76397378-405a2c00-637b-11ea-96bb-1deeb15db6b8.png)

The filter should work based on object type and not the filename extension.

**Comment by larshp** [comment]
perhaps have both possiblities, per file extension and per object type
