### ISSUE TITLE
Branch created with no changes identified

### ISSUE THREAD

**Issue by 7qiang** [abapGit/abapGit#3258]
**user case:** 
1. task released, and branch created with no issues, checksums in table ZABAPGIT updated
2. branch deleted from GITHUB
3. create branch again, branch created with no changes identified

**findings from my side**
ZCL_ABAPGIT_TRANSPORT_OBJECTS-->TO_STAGE is checking if flag LSTATE is not checked. 
LSTATE is checked when something different found between dev code and checksums in table ZABAPGIT. LSTATE wont be checked when trying to create the second branch as checksums have been updated when the first branch is created.

Would you please advise if there is any solution for this user case?

**Comment by bigld** [comment]
Hi @7qiang 
I'm not sure where you expect any differences when you create a new branch?
Maybe I missed something, but this is how git works.

If your local master branch (active ABAP coding) is up-to-date with the remote (github) master and you create a new branch off master, there can't be any differences.
