### ISSUE TITLE
Expand/collapse additional features

### ISSUE THREAD

**Issue by eduardocopat** [abapGit/abapGit#3261]
Copied from @FreHu in PR #3248. Follow-up on #3165.

A few ideas:

I think the ideal location for the collapse button would be the left side, the screen is wide and there is nothing to click on the right. 

![image](https://user-images.githubusercontent.com/5097067/76311937-49db8980-62d2-11ea-8b1e-9a8f06b1b7c7.png)
vs
![image](https://user-images.githubusercontent.com/5097067/76312030-7beceb80-62d2-11ea-8538-9e99e4460bf8.png)

It could be placed left of the added/removed/modified counters, there is more space for it there, you could have a more noticeable icon.

When I collapse everything, I would like to have an overview of my staged changes. 
- add expand/collapse all options to the top menu
--------------------------------
Collapsing of partially staged files

![image](https://user-images.githubusercontent.com/5097067/76312112-a0e15e80-62d2-11ea-9b47-1cbb94809244.png)

In the first file, I have no lines selected, but in the second one I have one of two lines selected. They both make it look like nothing is selected. 
- There could be an extra line shown in collapsed mode which would summarize the user's selection ("1 of 2 lines staged")
- Different background colors for `nothing staged`/`something staged`/`everything staged`

_Originally posted by @FreHu in https://github.com/larshp/abapGit/pull/3248#issuecomment-597063373_

**Comment by mbtools** [comment]
As reference, expand/collapse is available:

![image](https://user-images.githubusercontent.com/59966492/151877485-a5d295f2-84dc-4445-b54e-895ba9b807a4.png)

Feature requests:
- add expand/collapse all options (diff and patch)
- visualize number of selected changes when collapsed (patch)

**Comment by mbtools** [comment]
Expand/collapse all available in #6511
