### ISSUE TITLE
Add last changed by to repo page

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#3267]
The same information should be available on both the repo and stage page.

Column placement: after path column.

**Comment by wozjac** [comment]
@FreHu something like this?
![2021-08-28_21-09-35](https://user-images.githubusercontent.com/20969653/131229206-16003c34-f8f9-4c93-a148-11adfcf80cf1.gif)
Its only for a remote repo.
I'm using zcl_abapgit_objects=>changed_by method, ty_repo_item is extended with a new field for holding the username. 
You can check in https://github.com/wozjac/abapGit/commit/fda2aaec4362f7cf395e25d3c657110e08083913

**Comment by FreHu** [comment]
i tried it, looks good. feel free to submit a PR
