### ISSUE TITLE
Maintenance screens missing

### ISSUE THREAD

**Issue by ypcyc** [abapGit/abapGit#3287]
I've "successfully" imported function group that was used for Table Maintenance, no errors.
But when I tried to modify table content in sm30, I'm getting a dump.
When I compared Function group structure I can see that only 3 screen of total 5 were  copied/created.
I have even tried to delete the Function group and copied one more time, same issue.

**Comment by mariusraht2** [comment]
It would be useful to see the dump the error you experienced generated. Is it possible to reproduce the error? If so, how?

**Comment by ypcyc** [comment]
Export was done with 1.93
Import with 1.94
Dump is pretty simple: SM30 tries to call screen 0004 that is missing in imported function group.

**Comment by ypcyc** [comment]
Maybe this might help. Screen does look like typical table maintenance view:
![image](https://user-images.githubusercontent.com/1402005/78369593-1ab4f100-75ce-11ea-93d4-f1183e9a1ab2.png)

**Comment by goreraks** [comment]
@ypcyc I was able to successfully pull the function group related to table maintenance without any issue. Also the maintaining the entries via SM30 was possible for me.
Please check your file <function group name>.fugr.xml where the XML tag "<DYNPROS>" exist.

**Comment by mbtools** [comment]
If this is still an issue, pls provide a test repo

**Comment by larshp** [comment]
@ypcyc

**Comment by ypcyc** [comment]
I don't have those files and access to that system anymore

**Comment by larshp** [comment]
okay, will close the issue then, open new issue when/if it can be reproduced
