### ISSUE TITLE
PFAC: Support for Workflow Rules for Agent Determination

### ISSUE THREAD

**Issue by mauriciolauffer** [abapGit/abapGit#3332]
Is there support for PFAC object type? It's the workflow rules for agent determination, created in tcode PFAC.

**Comment by mauriciolauffer** [comment]
How one could start working to add support for workflow rules for agent determination (PFAC / PDAC objects)? What would be the process?

**Comment by larshp** [comment]
some information here https://docs.abapgit.org/development/serializers.html

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.
