### ISSUE TITLE
SRVD - Error when import definition service

### ISSUE THREAD

**Issue by anagarcigm** [abapGit/abapGit#3349]
Good Morning,

We are working in eclipse and we are importing in our premise step by step.
Firt we create a table, pass to our git and pull on premise. 
In the third step we create the definition service. When we pull it in our on-premise system, the process fails.
I have attached an image with the errors and the files.
I have seen in object zcl_abap ZCL_ABAPGIT_OBJECT_SRVD in method deserialize this code.

    io_xml->read(
      EXPORTING
        iv_name = 'SRVD'
      CHANGING
        cg_data = <ls_service_definition> ).

    ASSIGN COMPONENT 'CONTENT-SOURCE' OF STRUCTURE <ls_service_definition>
           TO <lv_source>.
    ASSERT sy-subrc = 0.

    <lv_source> = mo_files->read_string( 'assrvd' ). <- i haven´t a file with this extension only srvdsrv.

Thanks in advance.
Best regards,

**Comment by christianguenter2** [comment]
Hm, a service definition should always have a .assrvd file. If I'm not mistaken.
Where did you create your service definition? What system version?
Can you show us your repository? The files in it?

**Comment by christianguenter2** [comment]
Can you also show the content of the 'srvd.xml' file?

**Comment by anagarcigm** [comment]
I have created in eclipse conected to a trial foundry account in scp.
The service definition is associated to view.

In the git repository, there isn`t this file.
A colleague have imported this repository in eclipse and it works fine.

![Captura5](https://user-images.githubusercontent.com/56394203/81281786-93d6b680-905a-11ea-800e-49fb578f7baa.PNG)


![Captura3](https://user-images.githubusercontent.com/56394203/81279836-ec588480-9057-11ea-952e-950ac283ada4.PNG)

Thanks in advance.

**Comment by christianguenter2** [comment]
Now that's quite interesting. Seems that SAP implemented already their own serializers in ABAP in the Cloud for object types BDEF, SRVB and SRVD which are not compatible with the ones we recently added to abapGit. 

Hm, at first sight we could make them compatible by changing the file extension from assrvd to srvdsrv.

@larshp  what do you think? Do you know what SAPs plans are? They could just have added their serializers to the official abapGit project. Hm...

**Comment by larshp** [comment]
@ThomasPloski

**Comment by anagarcigm** [comment]
Hello
It doesn´t work. 

![Captura7](https://user-images.githubusercontent.com/56394203/81303912-a235ca00-907c-11ea-8bfe-36206f3ccdfd.PNG)

Debugging we have see like the information of core metadata is empty. 
The error source type " does not exist, we have seen is in Method WRITE_SRVDSRC (CL_SRVD_OBJECT_PERSIST). L_metadata-srvd_source_type in empty.
![Captura6](https://user-images.githubusercontent.com/56394203/81303887-9813cb80-907c-11ea-8f13-bbbee1395f69.PNG)

Thanks in advance 
Best regards

**Comment by anagarcigm** [comment]
Good Morning,

Are there news about this?

Thanks in advance,
Best regards.

**Comment by larshp** [comment]
The open source abapGit works with itself, from an open source perspective we don't have control of the code on the SAP systems, and legally we cannot take the SAP copyrighted code and make it open source.

**Comment by ThomasPloski** [comment]
In process

**Comment by mbtools** [comment]
@anagarcigm the new SRVD implementation is now available. can this be closed?
