### ISSUE TITLE
Possibility to check objects before staging/pushing

### ISSUE THREAD

**Issue by ThomasPloski** [abapGit/abapGit#3350]
Hi abapGit Community,

Is there any possiblity to check given objects regarding consistency before/during staging/pushing and in case of an identified inconsistency to ignore it?

Cheers,
Thomas

**Comment by flaiker** [comment]
Hi,

you can run Advanced -> Syntax Check in the main view before pressing Stage or also activate the ATC integration to always run a check variant before committing (repo settings -> code inspector check variant).

**Comment by ThomasPloski** [comment]
Hi flaiker,

Thank you for drawing attention of this feature. 

Do you know whether abapGit supports a state information like ignored/skipped during staging which can be set in a object handler?

Thanks.

Best regards,
Thomas

**Comment by larshp** [comment]
during staging? the developer decides what to stage, then its up to the CI to verify that the files are consistent
