### ISSUE TITLE
Error while importing behaviour definition/implementation

### ISSUE THREAD

**Issue by druizmar** [abapGit/abapGit#3351]
Hi community!

I'm new to abapGit and i'm having the following issue when i try to import my behaviour definition and implementation class from gitHub to backend system where i already have table and data definition files correctly loaded:

> "Object description is missing"
> "Object description is missing"
> "Import of object ZGIT_DATA_DEF2 failed"

The content of behavior definition file is:
managed implementation in class zgit_data_def2_bhv unique;

```
define behavior for ZGIT_DATA_DEF2 persistent table ZGIT_TABLE2

lock master
{
  create;
  update;
  delete;
}
```

And the implementation class is as simple as:
```
CLASS zgit_data_def2_bhv DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zgit_data_def2.
ENDCLASS.

CLASS zgit_data_def2_bhv IMPLEMENTATION.
ENDCLASS.
```

Any ideas on what is going wrong? :(

**Comment by christianguenter2** [comment]
Can you check whether description is there in the bdef.xml? Like this:
https://github.com/abapGit-tests/BDEF/blob/2ef3ae1ed979d6a4c882a912142eb9ea78a37eeb/src/zroot_cds.bdef.xml#L10

If not does the behaviour definiton has a description in the source system?

**Comment by christianguenter2** [comment]
And what's the source system?

**Comment by larshp** [comment]
@ThomasPloski

**Comment by druizmar** [comment]
Hi, thanks for your attention.

I generate the file on Eclipse ADT then push it to git and from git to backend (SAP Hana release 754). 

My bdef.xml looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_BDEF" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <BDEF>
    <NAME>ZGIT_DATA_DEF2</NAME>
    <TYPE>BDEF/BDO</TYPE>
    <DESCRIPTION>Behavior for ZGIT_DATA_DEF2</DESCRIPTION>
    <DESCRIPTION_TEXT_LIMIT>60</DESCRIPTION_TEXT_LIMIT>
    <LANGUAGE>EN</LANGUAGE>
    <MASTER_LANGUAGE>EN</MASTER_LANGUAGE>
    <SOURCE_FIXED_POINT_ARITHMETIC>true</SOURCE_FIXED_POINT_ARITHMETIC>
    <SOURCE_UNICODE_CHECKS_ACTIVE>true</SOURCE_UNICODE_CHECKS_ACTIVE>
   </BDEF>
  </asx:values>
 </asx:abap>
</abapGit>
```

**Comment by christianguenter2** [comment]
ABAP in the cloud BDEF implementation and On Premise BDEF implementation are not compatible yet.
See here 
https://github.com/larshp/abapGit/issues/3349#issuecomment-625231200

**Comment by druizmar** [comment]
Ok. Thanks for helping anyway.

**Comment by ThomasPloski** [comment]
Hi community, I am currently working to fix this issue.

**Comment by larshp** [comment]
@ThomasPloski any updates?

**Comment by larshp** [comment]
@ThomasPloski any updates?

**Comment by ThomasPloski** [comment]
fix provided by pull request #4012

**Comment by larshp** [comment]
@druizmar try again, latest version

**Comment by anagarcigm** [comment]
Hi larshp,
I am a collage of druizmar. I am doing the pull of this repo of sap:
https://github.com/SAP-samples/abap-platform-refscen-flight.git
And I have this error.
Object description is missing 
Object description is missing 
Import of object /DMO/I_TRAVEL_U failed   (The same error)

The 12th of January I did this pull and althought I received the error message in eclipse the object was generated and you have to activate.

Some change has broken the generation of BDEF.
I have done the pull of one of my repos and object were created (service definition too).  I will continue testing other repos.

Best regards,

**Comment by larshp** [comment]
@ThomasPloski can you help?

I dont have access to a system where I can test this, plus not sure if abap-platform-refscen-flight is in the right/latest format or not

**Comment by anagarcigm** [comment]
Hi,
 I forget to tell us that , i use onpremise 2020.

I do this task once a month because the machine is refreshed. 
I use the information of this page https://github.com/SAP-samples/abap-platform-refscen-flight/tree/On-Premise-2020. 
Best regards.

**Comment by anagarcigm** [comment]
Hello,
Can you give some information about the issue? Today I did the pull and the problem continues.

**Comment by ahusemann84** [comment]
Hi @ThomasPloski,

I experienced the reported issue as well, when importing the Flight Reference Scenario from the on-premise-2020 branch:

![image](https://user-images.githubusercontent.com/80681442/119665231-74acf180-be34-11eb-858b-c1cb80ef62b0.png)

The behaviour definitions are then incomplete, I can see them in ADT in the Package Explorer but get an error when opening them.

I use following versions:
abapGit version: 1.108.0 
XML version:  v1.0.0 
GUI version:  7600.1.8 
APACK version:  1 

Is there meanwhile any solution known?

Thanks and BR
Arne

**Comment by anagarcigm** [comment]
Hi Arne,
I create manually the objects in eclipse. Although appear the object in eclipse you can use the same name.

Best regards.
Ana

**Comment by larshp** [comment]
try again, latest version
