### ISSUE TITLE
Refactoring: use less DDIC types

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#3386]
Instead of `lv_index   TYPE syst-index.` do `lv_index   LIKE sy-index.` etc

the use of DDIC structure SYST is not needed

https://github.com/larshp/abapGit/search?q=syst&unscoped_q=syst

**Comment by flaiker** [comment]
Why not just use the data element directly (syst_index / syindex) instead of referencing a global variable?

**Comment by larshp** [comment]
I'm guessing that it is more likely for the global variable SY to exist in the future, than DDIC syst_index / syindex

this is also for improving static analysis, so it does not need to know the DDIC object SYST

**Comment by mbtools** [comment]
I prefer to exclusively use TYPE. no LIKE which might lead to a chain of LIKEs to find the type. Therefore I code TYPE sy-subrc which clearly states the purpose of the variable as well. In the end, all variations above work the same way and are equally future proof imho. Just stay consistent within a project

**Comment by larshp** [comment]
yea, `lv_index TYPE sy-index` is also good

**Comment by larshp** [comment]
https://stats.abaplint.org/#/-/larshp/abapGit

What can be replaced with a "built-in" type is preferable, it will never be possible to replace all. And typing should be consistent, ie. DDIC reused where it adds value

![image](https://user-images.githubusercontent.com/5888506/84521625-97063780-acd5-11ea-9d40-25ed12fca268.png)

**Comment by larshp** [comment]
https://abaplint.app/stats/larshp/abapGit/void_types

**Comment by larshp** [comment]
good for now, closing
