### ISSUE TITLE
Enforce naming prefix for TYPES

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#3398]
In order to be able to statically determine if the TYPE is defined within the ABAP code or in DDIC, TYPE naming will be enabled via

https://rules.abaplint.org/types_naming/

Regex pattern "^TY_.+$"

Static analysis is also required for future automatic up/down-port

**Comment by larshp** [comment]
nah, seems to be okay for now, closing

**Comment by mbtools** [comment]
we have consistent naming everywhere else. it's 97 types to rename. doable

**Comment by larshp** [comment]
hmm, yea, well, 🤷‍♂️
