### ISSUE TITLE
Missing menu hover and visual connection to dropdown menus

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#3411]
In the default theme, there's no visual indicator when moving mouse over selectable items. Also when opening a dropdown menu, the menu name remains as is. This can be confusing... For example, which menu was actually selected here, Branch or Tag?

![image](https://user-images.githubusercontent.com/59966492/82753515-804f7d80-9dc6-11ea-96be-e930e5519253.png)

![image](https://user-images.githubusercontent.com/59966492/82752988-6744cd80-9dc2-11ea-87e8-c82093850dba.png)

Dark theme uses different color and underline on hover, but has the same issue with dropdown menus:

![image](https://user-images.githubusercontent.com/59966492/82753519-89d8e580-9dc6-11ea-922c-aed8133bb466.png)

![image](https://user-images.githubusercontent.com/59966492/82753015-a83ce200-9dc2-11ea-9faf-0582984e76b3.png)

Proposed solution:

![image](https://user-images.githubusercontent.com/59966492/82753870-898e1980-9dc9-11ea-8147-a1843649c0d1.png)

![image](https://user-images.githubusercontent.com/59966492/82753871-901c9100-9dc9-11ea-9229-f2b867b79a51.png)

![image](https://user-images.githubusercontent.com/59966492/82753873-9a3e8f80-9dc9-11ea-9226-ddb749b8ec0b.png)

![image](https://user-images.githubusercontent.com/59966492/82753879-a0347080-9dc9-11ea-80bb-90a2ba2583ec.png)

**Comment by sbcgua** [comment]
Conceptually - good feature, but a couple of concerns:
1) I'd better not do it with box shadow - this is kind of 3d button look from 200x :)) Background highlight would be better
2) There is an idea to remove favorites bar at all (don't remember the issue number). Though this does not cancel the idea for the menus

**Comment by mbtools** [comment]
1. The box shadow was already there for the dropdown. I just applied it to the menu to get the same look. Agree, both should be just background highlight. 
2. https://github.com/larshp/abapGit/issues/3269 I'm in favor of it.

**Comment by mbtools** [comment]
Closed by #4768
