### ISSUE TITLE
Issues with SAP GUI 7.70 Edge (based on Chromium) Browser Control

### ISSUE THREAD

**Issue by gregorwolf** [abapGit/abapGit#3446]
Today I've received the SAP GUI 7.70 Beta 2 shipment and I've installed this version:

![Screenshot 2020-06-03 at 12 57 41](https://user-images.githubusercontent.com/2639535/83629101-d1672a80-a599-11ea-8341-04fdf24f2b2c.png)

with this GUI Version it is possible to select  Edge (based on Chromium) as the Browser Control:

![Screenshot 2020-06-03 at 12 54 08](https://user-images.githubusercontent.com/2639535/83628984-a381e600-a599-11ea-8406-e8f928595a86.png)

Unfortunately when doing so the ZABAPGIT transaction looks like this:

![Screenshot 2020-06-03 at 12 45 08](https://user-images.githubusercontent.com/2639535/83629002-ada3e480-a599-11ea-857f-e5b5262191c6.png)

I'm using the latest version from the master branch:

![Screenshot 2020-06-03 at 12 53 47](https://user-images.githubusercontent.com/2639535/83629017-b4325c00-a599-11ea-8fd1-fd3fb3591706.png)

What is the best way to start correcting this issue?

**Comment by larshp** [comment]
can 7.70 be downloaded from the marketplace? any SAP note references?

**Comment by gregorwolf** [comment]
I've applied to the beta program to be able to test abapGit. I will ping my SAP Contacts how they can support here.

**Comment by larshp** [comment]
as a first step, try verifying that SAP demo report SAPHTML_EVENTS_DEMO works

**Comment by gregorwolf** [comment]
Looks OK and the Events seem to work:

![Screenshot 2020-06-03 at 13 27 58](https://user-images.githubusercontent.com/2639535/83631624-168d5b80-a59e-11ea-8089-d512f226ac41.png)

So it might be only a CSS issue.

**Comment by sbcgua** [comment]
setKeyBinding is a JS function. So I'd say download the html + css (common + default theme) + js file and try openning it offline.

Additional info:
- https://docs.abapgit.org/development/developing-ui-css.html ("Recommended ..." at the bottom)
- also comment bundle css at the start of the real html and uncomment refs to original css files ("CSS variables support" in the same guide)

P.S. wow, edge in sap gui, is it 2020 ? Maybe I'll move from GUI 7.40 after all ... (sarcasm detected ... just ignore :)) )

**Comment by gregorwolf** [comment]
In the Edge developer tools I see the CSS and JS files only as empty files in the sources:

![Screenshot 2020-06-03 at 16 08 07](https://user-images.githubusercontent.com/2639535/83646775-6b3bd100-a5b4-11ea-9360-e47c0153aac9.png)

In the console I get this warnings:

> HTML000001.htm:7 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "file:///SAPHTMLP://htmlviewer.sap.com/0lkeJ2dG7jgegQQRC5KBiG/css/common.css".
> HTML000001.htm:8 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "file:///SAPHTMLP://htmlviewer.sap.com/0lkeJ2dG7jgegQQRC5KBiG/css/ag-icons.css".
> HTML000001.htm:12 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "file:///SAPHTMLP://htmlviewer.sap.com/0lkeJ2dG7jgegQQRC5KBiG/css/bundle.css".

**Comment by gregorwolf** [comment]
Also here I've created an incident in the SAP Marketplace: 366939 / 2020

**Comment by FreHu** [comment]
Joining the 7.70 party so I can help out with testing.

**Comment by sbcgua** [comment]
`file:///SAPHTMLP://htmlviewer.sap.com/0lkeJ2dG7jgegQQRC5KBiG/css/common.css`

Hmm, by the way, does previous SAP GUI add the hash string into the path ? I'm not sure it is taken into account within html declaration. Maybe this is the issue ?

**Comment by gregorwolf** [comment]
Today I've got a response in the Incident 366939 / 2020:

> The issue here was the CSS which was in the relative path to the main HTML page.
> The issue has been fixed and it will be  available in one of the subsequent patch of the SAP GUI 770.

**Comment by gregorwolf** [comment]
I've just tested a patched version of SAPChromiumEdge.dll. You can now use DevTools:

![Screenshot 2020-06-18 at 10 15 56](https://user-images.githubusercontent.com/2639535/84995775-b45f5980-b14c-11ea-800b-fc0dd9aa675e.png)

**Comment by mbtools** [comment]
Did you find any bugs in AG related to GUI 7.70 or is it all working now?

**Comment by larshp** [comment]
I'll go ahead and close this, open a new issue if there are more issues

**Comment by mbtools** [comment]
Just for reference: 
SAP Note 2901278 - SAP GUI HTML Control based on Chromium Edge: Legacy HTML does not work (correctly) / present limitations
https://launchpad.support.sap.com/#/notes/0002901278

**Comment by B0yEditi0n** [comment]
> Today I've received the SAP GUI 7.70 Beta 2 shipment and I've installed this version:
> 
> ![Screenshot 2020-06-03 at 12 57 41](https://user-images.githubusercontent.com/2639535/83629101-d1672a80-a599-11ea-8341-04fdf24f2b2c.png)
> 
> with this GUI Version it is possible to select Edge (based on Chromium) as the Browser Control:
> 
> ![Screenshot 2020-06-03 at 12 54 08](https://user-images.githubusercontent.com/2639535/83628984-a381e600-a599-11ea-8406-e8f928595a86.png)
> 
> Unfortunately when doing so the ZABAPGIT transaction looks like this:
> 
> ![Screenshot 2020-06-03 at 12 45 08](https://user-images.githubusercontent.com/2639535/83629002-ada3e480-a599-11ea-857f-e5b5262191c6.png)
> 
> I'm using the latest version from the master branch:
> 
> ![Screenshot 2020-06-03 at 12 53 47](https://user-images.githubusercontent.com/2639535/83629017-b4325c00-a599-11ea-8fd1-fd3fb3591706.png)
> 
> What is the best way to start correcting this issue?

i'm sorry for the quest, but how you debug in SAP GUI using edge?

**Comment by mbtools** [comment]
@B0yEditi0n check [debugging](https://docs.abapgit.org/development-guide/testing/debugging.html) in our docs

PS: Please create a new issue next time
