### ISSUE TITLE
Add remote url to repo settings, remove change remote function

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#3451]
If the remote url was added to the repo settings, all the settings would be in the same place and the `change remote` popup could be removed.

![](https://user-images.githubusercontent.com/5097067/83780517-8cbcbb80-a68d-11ea-8b1c-26e844d109e7.png)

**Comment by mbtools** [comment]
currently, master language is read-only in the repo settings but changable in the popup. the problem with the popup is also that it mixes repo and local settings. 

On my wish list is also an option to switch URLs between original and my own fork (without having to reenter the URLs).

**Comment by FreHu** [comment]
You can't change the master language from the popup, it's actually this setting (I just added it to the popup recently).

![](https://user-images.githubusercontent.com/5097067/83851492-bd930400-a712-11ea-833d-50ab71d1d0bf.png)

If you wanted to switch between original/fork, it could be solved by having the option to configure clone url and additional remotes. Then branch switch popup could show branches on remotes as well.

**Comment by christianguenter2** [comment]
+1 for switching between original and fork.

**Comment by sbcgua** [comment]
switching between forks would be nice ...

additional question: when do you need such switching ? I realized that it is just for abapgit ... maybe ... it makes sense to request list of forks from github instead of writing them by hand. Vendor lock, but it is the most popular platform.

**Comment by larshp** [comment]
I switch between remotes when testing pull requests from forked repos

**Comment by sbcgua** [comment]
github only ? or anything else ?

**Comment by larshp** [comment]
should eventually work with more platforms, but can start with github.

I guess you are thinking about the ref names for the pull requests, which works differently on different platforms

**Comment by sbcgua** [comment]
I meant that it is not possible to get fork list with git proto, it should be github http api. Here is how I would see working with forks (imho and based on my scenarios):

- the URL entered at clone time is marked as origin
- one can change the origin at repo settings (as Frederik proposes)
- in addition there is some kind of command - switch to fork - which lists available forks (fetched via API). Probably it should be a command pallette with search - e.g. AG have lots of forks :)))
- in such case origin URL is remembered in the settings. The feature above should have some shortcut to "reset" URL back to the origin quickly

UX consideration: the url at repo page - does any one ever click it intentionally ? I was thinking to remove "Change remote" and to move it to this URL instead. Would be fine imho. But within this new concept it would be less intuitive ... anyway I think the URL UX can be improved

![image](https://user-images.githubusercontent.com/15635498/84028134-de6c8b00-a998-11ea-9943-08bbc28767bf.png)

**Comment by mbtools** [comment]
+1
Keep it simple. No auto-retrieve of fork URLs. The could be in on other sites, enterprise or local gits. Just let users enter alternative URLs in repo settings (simple UI like in "Bypass proxy" popup). 

Keep the URL link (anything else but launching a browser would be bad design). Add a new icon - between the URL and the changelog icon - for switching forks.  It should show a popup like the "switch branch". 

Remove "Change remote" from menu. Instead one would go to repo settings once and enter alternative URL there. This way system will also remember it for future switching (via the new icon).

**Comment by sbcgua** [comment]
Imho this need some prototype to try and feel :)

**Comment by FreHu** [comment]
Changing remote should now be added to repo overview as well. With #3551 , you could switch remote, branch and go stage directly from repo list. 

What's missing is branch creation, or "stage in new branch" for quick changes, just like github creates the patch-x branches for you.

**Comment by sbcgua** [comment]
"stage in new branch" would be a very nice feature. Imho it can be a field at commit page rather then a command at the repo view

**Comment by FreHu** [comment]
this was resolved by https://github.com/abapGit/abapGit/pull/4724, i'll open some minor points separately
