### ISSUE TITLE
Broken dynamic method call in ZCL_ABAPGIT_TADIR

### ISSUE THREAD

**Issue by Elberet** [abapGit/abapGit#3453]
The method name in the dynamic call below is, as far as I can tell, misspelled:

https://github.com/larshp/abapGit/blob/d36b43defe2949fc53c880206ebb8537f21d0463/src/zcl_abapgit_tadir.clas.abap#L256

Class `ZCL_ABAPGIT_OBJECT_SICF` contains a public static method `read_tadir_sicf`, but _not_ `read_tadir`.

**Comment by larshp** [comment]
yea, its a problem, either remove it since it does not work(has it ever worked?)

or change

**Comment by Elberet** [comment]
There is some additional ugliness here that makes me not want to just remove the broken call just yet...

`zcl_abapgit_objects=>warning_package_find` tries to warn the user, when deserializing an object would modify something outside of the package being imported. This sounds like an important feauture, but it relies on `zif_abapgit_tadir~read_single`.

This sounds to me like this needs fixing rather than removal, but a _proper_ fix should:
 - enhance `zif_abapgit_object` with a method for TADIR entry lookup,
 - rework the dynamic call to instead call the above method,
 - add implementations of `zif_abapgit_object~<new_method_name>` to the relevant object handler base class(es) and provide an override for the SICF handler,

Problem is, business has moved on and I'm basically out of time to dedicate to abapGit. ☹️

**Comment by larshp** [comment]
@Elberet the comment above seems unrelated to the initial issue raised, suggest opening it as a separate issue
