### ISSUE TITLE
Why we need separate action "Create Package" in new online project popup instead merge it with "OK"

### ISSUE THREAD

**Issue by goreraks** [abapGit/abapGit#3458]
I believe most of the times while cloning new repo, the package name provided in the popup will always be new i.e. doesn't exist in the local system.
So why one has to click on "Create package", instead clicking on "Ok" should have the functionality of "Create package" if the package doesn't exist.
![image](https://user-images.githubusercontent.com/58498218/83940155-2015fe00-a800-11ea-82bc-15752085d535.png)

**Comment by mbtools** [comment]
Might be easy for $local packages but how would you specify details for a new transportable package like transport path?  

On my wish list is an option to include a default package name in the repo - maybe in APACK.

**Comment by larshp** [comment]
show the popup after ok or click create package, not much of a difference, I don't see this as a big issue

**Comment by mariusraht2** [comment]
I agree. We should show the "Create package" popup automatically if the entered package doesn't exist after click on ok. Plus we wouldn't need the additional button "Create package" anymore.

**Comment by mbtools** [comment]
The main package is created automatically during pull  (since #4814). Closing
