### ISSUE TITLE
ACGR: Add support for Roles

### ISSUE THREAD

**Issue by ed-holland** [abapGit/abapGit#3474]
Support for transporting Roles as part of the development changes.

There are two types of roles: Single & Composite
Note: Roles are client specific

Single Roles consist off:
- Name
- Description
- Long Text
- List of Authorization Objects
FUBA Create: PRGN_RFC_CREATE_ACTIVITY_GROUP

Composite Roles consist off:
- Name
- Description
- Long Text
- List with Roles
FUBA Create: PRGN_RFC_CREATE_AGR_MULTIPLE

Information can be retrieved using FUBA PRGN_STRU_LOAD_DEFINITION

**Comment by larshp** [comment]
abapGit finds the objects via TADIR, as far as I remember roles are not recorded in TADIR?

to solve roles we need https://github.com/larshp/abapGit/issues/3441

**Comment by ed-holland** [comment]
No, it does not create entries in TADIR but can be transported using R3TR (complete object types).
One can not handle Roles as a set of tables. They will need to be created using the FUBA's provided or similar ones.
My proposal would be to extracting them as XML and store them in the repository as it is a structured object.

**Comment by larshp** [comment]
need some way to identify that the role is part of the project/repository/package

**Comment by ed-holland** [comment]
We use naming conventions to assign them. In general, i do not think it is possible to auto assign objects like this or TABU entries etc. It has to be done either manually or by rules (exit?).

**Comment by ed-holland** [comment]
A transport or change request can be used to simplify the input of course.

**Comment by ed-holland** [comment]
Or way simpler to achieve... to support client specific non-TADIR objects... 

allow for a special file on top-level that contains a piece list like structure that is automatically added to the transport created from the branch.

**Comment by larshp** [comment]
So,

A: Possibility to specify the piece list / list of semi objects, consisting of: object type(4 characters) + object name + folder = package.
Either as part of the existing `.abapgit.xml` or as new file. Add add functionality in the UI to maintain it

B: Hook it into existing TADIR functionality so abapGit can reuse the existing serializing logic for semi objects

C: add serializer for ACGR, ZCL_ABAPGIT_OBJECTS_GENERIC might do the trick

Suggest above to be 3 subsequent pull requests

**Comment by ed-holland** [comment]
A) I would put it into a seperate file as it can contain many entries, Not sure what you mean with "=package". It would contain rows of:
Type, Object Name, Object Key
Optionally, the UI could allow the import of a Transport, Sorting, Remove Duplicates.

**Comment by larshp** [comment]
many entries? Do you have any other object types in mind? That are not in TADIR?

the serialized object files will have to go into some folder, the folder structure corresponds to the package structure in ABAP

**Comment by ed-holland** [comment]
Many is relative ofcourse. We have 16 roles and 2 authorizations that we deliver as examples to customers. But this could be a generic way to add objects that you want to transport but do not want to edit as a file.

If one want's to store them in the repository, one could export them as a blob and commit the export files.

**Comment by larshp** [comment]
"authorizations" following objects are already supported and recorded in TADIR
SUCU | Authorization Groups 
SUSC | Authorization object class 
SUSH | Assignment: Service –> Authorization Objects 
SUSO | Authorization object
AUTH | Authorization Check Fields

right now, the only object type I can think of which should really be in TADIR is the roles, so I think its okay to start out by adding these in .abapgit.xml

_export as blob and store_: that's always possible, but it will be manual work, committing and creating blob after each change, for all TADIR types abapGit helps the user to keep track of what has changed

**Comment by ed-holland** [comment]
The transaction PFCG has a button to transport the roles.  It creates a customizing request from it. There are many tables involved during export.

the role is based on Authorizations (tran su03, which transport as TABU with tables USR12 and USR13).

Manual is something i try to avoid as it will cause problems at some time. If automation is possible one should try it (reasonable amount of time).

**Comment by mbtools** [comment]
Closing in fav of https://github.com/abapGit/abapGit/issues/3860
