### ISSUE TITLE
Docu Request: Enhance documentation on own serializers

### ISSUE THREAD

**Issue by CastedConst** [abapGit/abapGit#3527]
Hi All,

I have maybe exotic use case, which I don't see as part of abapGit, but would greatly appreciate more documentation whether abapGit could be used to implement it, or how to do it.

### Scenario
A set of packages/repositories should be backed up every night. Semantically these packages can be described as a basic "framework" package and several "plugins". The packages described as plugins register themselves in the framework by adding several entries into the tables of the framework package.

While it is obvious that a superior implementation would incorporate the plugins e.g. by searching implementing classes of a certain interface, the current design is already existing and used in plenty of plugins.

For a "stupid" backup the content of the "framework" package could include the table entries of the plugins. However, the idea is to use a GitHub-Based backup as transition point to change the development model in the future and ultimately having a Repo for each Plugin. As the table records in the framework tables also contain plugin-specific configuration this next step would require the table records to be stored in the plugin Repo instead of the framework Repo.

My gut feeling is that the "correct" assignment of the table entries to the plugin Repos and the ease of usage of abapGit will be the major factors of adoption, therefore I'd like to automate as many of the aspects as possible.

### Thoughts
Potential idea how the plugin specific table records in the framework tables could be added to abapGit from all I read in this Repo so far:
* Storing the plugin specific records from the framework tables in the other Repos would probably require some representation / proxy in the plugin repo (e.g. a class with a special interface)
* Having this class we may use a custom serialization of it to write additional files with the records
* During de-serialization the files are converted back and inserted into the framework tables. As each record key starts with the ID of the plugin we can perform a delete-insert on that key area (or a lock if required).
Completely switching to a class and removing the records is not easy as the configuration is quite powerful.

Potential idea how to ease the usage of abapGit as best as possible (not part of the docu request, just FYI)
* Starting with a backup from the consolidation system. Colleagues can perform Bug Tracking and quick Lookups in GitHub. Add a "testing" and "development" branch linked to test and dev systems based on the same technique.
* After a transition period change the approach from "backup" to "push". Instead of pulling the current state from the test system the transport path is cut and the update of the systems is done via Git. A merge into the test branch updates the test system, a merge in the master branch updates the consolidation system. Usage of Commits, 4-Eye principle, etc. The Dev branch is mainly a vehicle.
* Potential next level: Pull Request to the Dev Branch. However this may cause merge conflicts in the Dev-System, not sure if worth the effort given our setup.

### Question
Is it possible to serialize table records from a table in another dev package as part of the current dev package? If yes, how could this be done and if not what is the alternative?

Thank you very much & best regards,
Thorsten

**Comment by mbtools** [comment]
Hi Thorsten,

Currently, abapGit handles objects listed in table TADIR - if we have a serializer for it. There's no generic "table content (TABU)" serializer. Ideas are being discussed (see https://github.com/larshp/abapGit/issues/3441) but nothing is implemented yet. It goes beyond a serializer since we are talking things not mentioned in TADIR and there are client-specific issues to take into consideration.

As mentioned in 3441, in the meantime, try to use xDAT objects.

**Comment by larshp** [comment]
best approach would be to implement #3441, which could be used by a lot of people

you could also choose to use the raw git classes from abapGit to do anything git related, https://github.com/larshp/abapGit/tree/master/src/git might require a bit of refactoring

**Comment by CastedConst** [comment]
Thanks for the quick response. I need to check the raw git classes in more detail to fully understand the capabilities and trade-offs of the different approaches.

**Comment by larshp** [comment]
closing, I think this is covered in https://github.com/abapGit/abapGit/issues/3441

**Comment by CastedConst** [comment]
Quite busy at the moment, but will take it for a spin as soon as I have some time
