### ISSUE TITLE
Abapgit logo discussion

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#3541]
This is for discussions on abapgit logo changes. Maybe it is time to refresh it ... or maybe not... 
Initiated here #3498.

Below are some sketches from my side. 
Personally I think that current logo is OK. It is a bit large and asymmetric which puts some restrictions on usage in design. On the other hand it is well distinguished and clear in terms of its message.

Sources, including vector, are here https://github.com/sbcgua/abapgit-design as well PNG renders with transparent background and the original logo vector

![new-2020-06-drafts](https://user-images.githubusercontent.com/15635498/85418860-01429600-b57a-11ea-8f90-579025f62e30.png)

**Comment by mbtools** [comment]
these look good in the current size but in the height of the header area you won't be able to read the "abap".

![image](https://user-images.githubusercontent.com/59966492/85639402-f4609800-b688-11ea-976a-76f9c7e3d330.png)

i tried to align it with top and bottom of font but it looks strange

![image](https://user-images.githubusercontent.com/59966492/85639541-4d303080-b689-11ea-940a-d3333e1aba2c.png)

i haven't had enough of it yet, so i vote for keeping the design.  :-)

**Comment by sbcgua** [comment]
![image](https://user-images.githubusercontent.com/15635498/86406725-512d0580-bcbc-11ea-8874-311c817fba60.png)

[vector](https://github.com/sbcgua/abapgit-design/blob/master/logo/wip/git-w-abap.svg)

**Comment by larshp** [comment]
close this issue? 🤷‍♂️

**Comment by sbcgua** [comment]
Probably yes
