### ISSUE TITLE
How to import a subpackage and its report into an existing parent package?

### ISSUE THREAD

**Issue by GiantCrocodile** [abapGit/abapGit#3547]
Hello,

we exported an ABAP package to a ZIP archive. Afterwards we wanted to import the package to a different system.

Structure of export system:
- Parent Package `A`
  - subpackage `B` (to export; this contains an ABAP report)

We would like to import it like this:
- Parent Package `C`
  - <import here> (thus a subpackage `B` is created and the report objects are stored here)

The parent package exists in both systems. The import system doesn't have the subpackage to import into; thus it must be created on importing the DEVC object.

We did export not just the report inside the package but also the package itself. We are able to see the DEVC object of the package of the exported report in the ZIP file. When we try to import this - regardless of `PREFIX` or `FULL` mode used - the content of the subpackage is directly imported to the parent package. Thus the content lays in package 'C' and the original subpackage where the package was inside is lost. On import the metadata, e. g. package description of the parent ABAP package was overwritten and all objects were laying in the parent package. No subpackage was created and thus the objects were not stored one level deeper (in the subpackage). The exported metadata contains no information about the original parent package.

Is there a way to import a report in an ABAP package into a SAP system so that the parent system is not holding the imported objects but the imported objects are kept in a subpackage and thus the package hierarchy/structure is kept as on the export system?

I hope it's not too vague what we want to achieve. We read the documentation and searched for similar issues but found none. This happens on a NW 731 system (export) and it's imported to a NW 740 system.

Thank you for your help!

Best Regards,

**Comment by mbtools** [comment]
Your repos should be created for package A and C. Then export repo A. If A contains objects or subpackages you don't want in the target system, deleted them from the zip. Then import the zip into repo C. 

If your packages are named as above, then both repos should be FULL mode. If you subpackage is calls A_B, then use PREFIX mode. It will then create subpackage C_B in the target system.

**Comment by GiantCrocodile** [comment]
I will review this with a colleague and get back to you end of next week. Thank you for your help @mbtools.
