### ISSUE TITLE
git - implement distributed part?

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#357]
currently abapGit does not implement the distributed part of git, it has to have a connection to the git server, and pulls all information from the server each time.

However, normal git clients store all old objects/files(blobs) locally.

Perhaps it is time to look into if this is a good idea for abapGit? It will give better performance for large repositories, as all objects does not have to be fetched each time.

**Comment by sbcgua** [comment]
Not crazy but cool imho :)

Some practical highlights around this (not directly related but about performance)

1. One of the annoying thing now is actually local serialization. E.g. I want to see diff - it serialize complete repo, then I press "back" -  it serialize complete repo again. For the big project it takes time. I actually have some ideas how to improve it ... some day ... (may come sooner if I'll have to deal with that big project more in near future ;)
2. There is a practical issue with abap which does not meet much in other git-relevant environments. Many developenrs - one environment. 2 people cannot work on 2 feature at the same time. For me this is an issue. Some kind of stashing may help - e.g. saving changed content when swicthing branches.

**Comment by larshp** [comment]
1. the functionality is implemented where it caches the serialized objects. However the code calls `refresh` quite often to make sure everything is the latest version.

2. There is only 1 active version of each program/class in an ABAP system, we cannot change this. Stashing: why not just commit the code to a new branch before switching?

**Comment by sbcgua** [comment]
1. I'll make some coding to show what I mean :)

2. Yes, I meant that this is an inconvenience point worth to thinking on. Stashing: genearlly agree. But what if it was not commited and then person 2 wants to continue his work and don't know what to do with the existing changes. Automatic stashing could be a nice feature to protect from mistakes. Anyway just as an idea.

**Comment by larshp** [comment]
closing, not in scope for now
