### ISSUE TITLE
Advanced option 'Reset local' doesn't remove additional translations

### ISSUE THREAD

**Issue by ChristopheCaparros** [abapGit/abapGit#3576]
Hello Lars,

I have noticed an issue with translations in case of 'Reset Local' of a repo. I'm using the version 1.97.0 of Abapgit .

The option 'Advanced / Reset local' doesn't allow to reset all the translations of Sap objects.
The additional translations done in my local repo are not removed with 'Reset local'.
It results some diffirences in Abapgit even after doing Reset local.

Is there a way to avoid this ?

Thanks,
Christophe

Example with a data element :
![Screen shot of remaing diff for an example](https://user-images.githubusercontent.com/22550208/86253049-49823980-bbb4-11ea-9776-b52eca8db1aa.png)

**Comment by FreHu** [comment]
You need to enable the serialize master language only option in the repo settings. Then you shouldn't see the translations.

**Comment by ChristopheCaparros** [comment]
Thanks for your quick answer. 
In fact my problem is not really the differences displayed. My objective is to Reset the Local repository and have the same version than in the remote Git server including the translations (to removed translations which are not in the remote Git server).

Do you think it is possible ?

Thanks,
Christophe

**Comment by FreHu** [comment]
I see what you mean. Not sure if this is a bug or a missing feature.

**Comment by mbtools** [comment]
Deserialize for DTEL takes the languages that exist in the remote repo and updates the local DD04T table. Since there are no languages stored in your remote repo, there's nothing to apply to the local side. Any local translations will remain. (ZCL_ABAPGIT_OBJECT_DTEL->DESERIALIZE_TEXTS). Deleting the translation is not foreseen currently.

How about uninstalling and doing a new pull from remote?

**Comment by ChristopheCaparros** [comment]
Hello Marc,
Sorry for my late answer.
I agree with your proposal to uninstall in local repo and do a new pull from remote.
I'm closing the issue.

Regards,
Christophe
