### ISSUE TITLE
New clone online repo page: add hotkeys for buttons

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#3577]
I was used to use the F6-hotkey for 'Create package'. Would be nice if all button had hotkeys.
![image](https://user-images.githubusercontent.com/17437789/86402111-972d9d80-bcab-11ea-8103-d657f2628444.png)

**Comment by sbcgua** [comment]
Cool idea. I was planning to do some polishing in #3559 , so I can have a look on this as well. Or did you want to do it yourself ? (actually, imho hotkeys are more page related than html_form class stuff)

**Comment by sbcgua** [comment]
P.S. "Back" has implicit hotkey...

**Comment by sbcgua** [comment]
just thinking: in order to transfer all fields data to abap, the form should be submitter, not just the sapaction.

**Comment by christianguenter2** [comment]
I can give it a try. You're right about back (F3), that's nice.

**Comment by christianguenter2** [comment]
No longer needed. As actions are in the meantime available via command palette.
