### ISSUE TITLE
signing commits

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#358]
https://help.github.com/articles/signing-commits-using-gpg/

Would require implementing the PGP/GPG/OpenPGP algorithm from scratch in ABAP.

Also keys would have to be stored in the database, which raises some security concerns. Suggest [DES](https://github.com/larshp/abapNTLM/blob/master/zcl_des.clas.abap) encrypting the keys(or other [symmetric-key](https://en.wikipedia.org/wiki/Symmetric-key_algorithm) encryption algorithm, [AES](https://github.com/Sumu-Ning/AES)?).

https://tools.ietf.org/html/rfc4880

https://github.com/git/git/blob/master/Documentation/technical/signature-format.txt

https://github.com/openpgpjs/openpgpjs

**Comment by larshp** [comment]
see https://github.com/larshp/abapPGP

**Comment by larshp** [comment]
still relevant IMHO

**Comment by mbtools** [comment]
agree. We might be able to use it like signing emails with SMIME

![image](https://user-images.githubusercontent.com/59966492/113437451-e34a7180-93e6-11eb-974d-c378c5ce5ebb.png)

![image](https://user-images.githubusercontent.com/59966492/113437516-0b39d500-93e7-11eb-925d-f5d7e2b130c5.png)

I think you add signing certificates to the STRUST address book first and then you can use the email for signing. 

Just an idea but I don't have time to play with this at the moment

**Comment by larshp** [comment]
I dont think this will happen anytime soon, closing the issue for now, can always reopen if started
