### ISSUE TITLE
Refactoring: Handling of parameters for on_event 

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#3602]
There's a lack of consistency in processing parameters passed from CL_GUI_HTML_VIEWER->SAPEVENT. Event data is passed on as GETDATA/POSTDATA in the original format. It's up to the receiver to parse the query string. Often but not always parameter names are uppercased. And often but not always parameter value are unescaped. 

Suggestion:

The idea is to centralize pre-processing of event data. In ZCL_ABAPGIT_GUI->ON_EVENT, take QUERY_TABLE, convert all parameter names to upper case and unescape all parameter values (like ZCL_ABAPGIT_HTML_ACTION_UTILS=> PARSE_FIELDS_UPPER_CASE_NAME) , and pass the result on to the event handler(s). By keeping GETDATA/POSTDATA and making QUERY_TABLE an optional input, event handlers can be transitioned step-by-step.

Result:

This will simplify handling of event data by avoiding the need to parse and unescape url/form data in many places.

**Comment by sbcgua** [comment]
Good idea. I'd probably encapsulate the logic into a class (`zcl_abapgit_gui_sapevent` ?) and pass it along. What do you think ? `ZCL_ABAPGIT_HTML_ACTION_UTILS` may probably be merged with it (not sure, but intuitively it should)

Thoughts:
- I think it makes sense to keep both raw and parsed (maybe unsuccessfully) query
- the query can be stored as `zcl_abapgit_string_map` for convenience and code reuse
- some cases (e.g. open repo) do not have key/value format (`repo?00000001`) - I'd say it is a good chance to unify (`repo?id=00000001`). Currently it looks like an exceptional handling in multiple places in the code

**Comment by sbcgua** [comment]
In addition (or maybe separately) I'd refactor returning shape. From multiple `exporting` to a single structure `returning` - I've been looking at it for some time already ... :)

**Comment by mbtools** [comment]
I noticed the URLs with a parameter value. In other places, it's key=00000000 for the repo. add_field just isn't used consistently. By using a central function we can also ensure security better (one day we have to tackle XSS etc and fix all string templates with variables that are used to compose the html).

**Comment by sbcgua** [comment]
Continuing the discussion from #3689.

So the idea is that each part of the code should play it's focused role. Thus I wouldn't integrate it directly in GUI class, it is packed enough. Here is what I mean by "sketching" (below is the suggestion)

**A) Shape of the call (`on_event`)**. Would be nice to have the call in one line

```abap
processing_status = li_event_handler->on_event( lo_event ).
...
if processing_status-state = 'new_page'.
  render( processing_status-page ).
endif.

```
- The returning param should be just a structure of the current exporting params, no big change.
- `lo_event` - should provide all the convenience stuff about the event and parsing mechanics. This should be a dedicated class to be able to grow the convenience stuff if needed (parsing, selectors, xml, json, whatever).

**B) coming back to the event class**

It should be easily construct-able
```abap
create object lo_event
  exporting
    iv_action    = iv_action
    iv_getdata   = iv_getdata
    it_postdata  = it_postdata
```

It should allow access to the original data
```abap
lo_event->mv_action
lo_event->mv_getdata
```
- ... as attrs or getter (I prefer read-only attrs but really does not matter)
- This, in particular, would much simplify the migration. I think that the method shape change should be done at once for all pages ! But only this change. With no other changes first, to simplify test and review. And the attrs will simplify the change - just prefix params with `io_event->` - that's it. On the second stage pages may use "advanced feature of the new class"

**C) "Advanced features of the new class"**

```abap
lo_event->query( ) " -> returns parsed getdata as a string_map
lo_event->form_data( ) " -> parsed postdata
```
- the "parsing" should be "non-strict", meaning, no raise on error
- the returning string_maps should be immutable (I'll add the feature)

so the following usage should become typical
```
lo_event->query( )->get( 'repo_id' )
```

**Comment by mbtools** [comment]
Nice. You are taking it quite a bit further than I had initially intended but that's the point of refactoring :-)

A) agree

B) agree on attrs for get/postdata since access to these will phase out overtime and eventually they can become private. but a getter for the parameters makes sense etc.

C) Let's combine get/postdata into a single string_map. i have that code done already with testclass. we can then shorten the get to
`lo_event->get( 'repo_id' )` 
I think the most efficient way would be `to_abap` to get all parameters into a structure. 

**D) Generating URLs**
Ultimately, we want to replace zcl_abapgit_html_action_utils. There we also have to opposite direction for composing a URL from the parameters. So maybe the new class is not zcl_abapgit_event but zcl_abapgit_parameters (or ...url_params) with setters as well - or better a `from_abap`. 

Are you thinking subclass of string_map or new class with string_map as attribute?

**Comment by sbcgua** [comment]
> C) Let's combine get/postdata ...

I wouldn't recommend. What if there are fields in query and other kind of data (xml ?) in the body ? Seem like there are no such cases in AG so far but I bet we might face it in future and will have to refactor everything again. As a benchmark - all typical JS http related libs separate query and body. I think they know something :)

> D) Generating URLs

Yeap, some util for this could be helpful. But need a clear use case. E.g. now there are links which are coded like this
`ri_html->add( |<a href="abcd?param1={ lv_x }&param2 = { lv_y }">My link</a>| )`
And the generator would look like
```abap
lo_params = zcl_string_map=>create( ).
lo_params->set( 
  iv_key = 'param1'
  iv_val = lv_x )->set( 
  iv_key = 'param2'
  iv_val = lv_y ).
ri_html->add( zcl_generator=>create(
  iv_txt = 'My link'
  iv_base = 'abcd'
  iv_query = lo_params
) )
```
so ... yeah ... needs some convenient concept ...

> Are you thinking subclass of string_map or new class with string_map as attribute?

Attributes pls. :) subclassing is usually evil. :) I added `freeze` [feature](https://github.com/larshp/abapGit/pull/3696) by the way a couple of days ago to prevent external change of params.

**Comment by sbcgua** [comment]
Yet todo: string_map case insensitive, remove upper/lower difference and respectively `is_upper_cased`. See comments: https://github.com/abapGit/abapGit/pull/3975#issuecomment-702988686

**Comment by mbtools** [comment]
Also, if you put a break-point into ZCL_ABAPGIT_HTML_ACTION_UTILS->PARSE_FIELDS, you will see that every GET causes the field list to be parsed again (esp. if action is in a later method of gui_router).

**Comment by sbcgua** [comment]
why ? maps are parsed just once and the memoized
https://github.com/abapGit/abapGit/blob/c27a0c0b38ef5c679abd84d9b6f35aef2885f95e/src/ui/core/zcl_abapgit_gui_event.clas.abap#L81

**Comment by mbtools** [comment]
with #4007 it looks correct now.

**Comment by mbtools** [comment]
Works beautifully :-)
