### ISSUE TITLE
Input history for Online Repo URLs

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#3639]
The new form for adding an online repo does not have an option to select previously used URLs. 

Suggestion:

1) After user selects "Clone online repo" on a validated form, save the URL in the user persistency (similarly to favorites). 
2) Enhance the form with a value help for URL showing previously used URLs.

The URL history could also be used in "Change remote" https://github.com/larshp/abapGit/issues/3451#issuecomment-643150930 once this becomes a form.

**Comment by mariusraht2** [comment]
![image](https://user-images.githubusercontent.com/45243391/92499240-edfbaa00-f1fb-11ea-813e-181e71729a28.png)

**Comment by mbtools** [comment]
just like that :-)

**Comment by mariusraht2** [comment]
I think we should only save N recently used URLs not all the user ever entered - maybe 5-10 are good numbers for that? If a new URL is being added the oldest entry will be deleted if the maximum size would be exceeded. What do you think?

**Comment by larshp** [comment]
how often would this feature be used? from my point of view, cloning the same repo is not something that would happen very often

**Comment by mbtools** [comment]
I’ve missed this feature a few times.
- when testing with same repo (create-pull-uninstall, repeat)
- when cloning a new repo with a similar URL 
- when trying to remember a URL you used before
It needs to be quick and easy. A JS dropdown with type-ahead would be ideal. But The popup will do

**Comment by larshp** [comment]
we've been trying to move to JS, so if that is happening, the popup would have to be rewritten, the persistence removed and rewritten

**Comment by mariusraht2** [comment]
I'll leave it alone for now

**Comment by flaiker** [comment]
How come the default input history of the browser doesn't work? Is it because of the embedded control?

I enabled Internet Options -> Content -> Input history for forms and opening the repo page directly in IE shows the history (even when setting the render mode to IE8 or lower):

![image](https://user-images.githubusercontent.com/5270359/93013324-b730e580-f5a7-11ea-9908-41e5174b179f.png)

I also played around with `autocomplete="on"` and `vcard_name="cloneurl"` but that didn't work.

**Comment by flaiker** [comment]
Apparently you would have to set flag `DOCHOSTUIFLAG_ENABLE_FORMS_AUTOCOMPLETE` in `IDocHostUIHandler::GetHostInfo` which seems impossible as the proxy object on the ABAP side does not expose anything relevant and you cannot access the attribute directly using OLE either.

**Comment by mbtools** [comment]
@flaiker does the autocomplete work with SAPGUI 7.70? If yes, I will close this. If no, I will add it to #4705.

**Comment by flaiker** [comment]
No, could get it to work with the Edge control either.

**Comment by larshp** [comment]
suggest closing, nice to have

**Comment by mbtools** [comment]
we can reopen if/when we have HTML popups

**Comment by mbtools** [comment]
Works with SAPGUI 7.70 patch 4:

![image](https://user-images.githubusercontent.com/59966492/152134312-f74124cc-eaa2-4509-a0ab-c90dd0d0e9c1.png)

![image](https://user-images.githubusercontent.com/59966492/152134427-e2f2b4c2-88cb-4b7e-a5be-a6202a129270.png)
