### ISSUE TITLE
docs: Does Ignore Files support placeholders/regex?

### ISSUE THREAD

**Issue by GiantCrocodile** [abapGit/abapGit#3694]
Hello,

we should add clarification if `Ignore files` as described [here](https://docs.abapgit.org/ref-dot-abapgit.html) does support regular expressions or placeholders like `*` or `?`.

Use case: ignore every file with file type extension like `md`, `txt`, `json`, `yml` or `yaml` file.

Best Regards,

**Comment by mbtools** [comment]
You can find the current logic in https://github.com/larshp/abapGit/blob/master/src/zcl_abapgit_dot_abapgit.clas.abap#L216

It's based on ABAP CP operator (not regex). A file is ignored, if the path&file contains at least one of the patterns listed in .abapgit.xml. 

Ignoring *.txt or *.json might lead to problems, if for example you have mime objects (W3MI) which use these extensions. And serializers for other object types might generate files with these or other extensions as well in the future. 

(see https://github.com/larshp/abapGit/issues/3675 for suggested improvement to logic)

**Comment by GiantCrocodile** [comment]
Great explanation @mbtools! I will have a look at the implementation tomorrow.

Yes, it can be problematic in some cases. It was just an example and needs proper planning as with any other change you would do :).

**Comment by larshp** [comment]
@GiantCrocodile can you help to update the documentation?

**Comment by GiantCrocodile** [comment]
@larshp Hi! I have no good idea how to improve it at the moment and I'm working 24/7 on a deadline for next week so I'm quite busy at the moment. I will see what I can do in a week or two.
