### ISSUE TITLE
Deployment mode

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#3705]
Would be very nice to have a more controlled pull. Desired features:
- be able to pull specific files or categories (e.g. interfaces, then classes, or all but tables or ...)
- be able to strip certain details out of diff e.g. when deploying between different system versions there are some new attrs added. Thus the objects always have diff. Or. A system with different set of languages. Would be nice to strip certain languages. Technically I'd see it as some kind of XML postprocessor, which would enable to delete certain XML parts according to set of XPath rules, entered in some freely enterable "deployment config" 

This would probably need a lot of minor (or less minor refactoring). From UI side: separate a table component with switchable checkbox selection. From repo: possibility to supply some kind of "deserialization scheduler" with object list. From serialization/deserialization side: an xpath stripper. 

P.S. originally was planning to make it a [separate program](https://github.com/sbcgua/abap-deployer), but then why not to make it a part of AG - should be easier in all respects... (optimistically ;)

**Comment by larshp** [comment]
pull specific files: suggest moving it to https://github.com/abapGit/abapGit/issues/413

strip details: suggest an user exit as a starting point, the user can choose to do whatever with the files after they are pulled from git

**Comment by sbcgua** [comment]
Agree, closing this one. The "strip details" feature went to #4540
