### ISSUE TITLE
REPOSITORY LIST: selecting other repo no longer possible after cancelling logon

### ISSUE THREAD

**Issue by bigld** [abapGit/abapGit#3732]
If you cancel the logon to a private repo A from repo list selecting any other repo result in logon popup for repo A

ZCL_ABAPGIT_GUI_PAGE_MAIN is no longer in handler list mt_event_handlers in zcl_abapgit_gui->handle_action
but the cancelled repo => onkon action would be triggered and the last action Open repo A is executed

**Comment by bigld** [comment]
maybe related #3701

**Comment by mbtools** [comment]
I reworked repo view startup in https://github.com/larshp/abapGit/pull/3831. Pls test with your scenario.

**Comment by bigld** [comment]
it's working now
closing!
