### ISSUE TITLE
Collect Online Repo Commit Display URLs

### ISSUE THREAD

**Issue by bigld** [abapGit/abapGit#3733]
For #3560 the last commit short hash may be/was added to the online repo header
![image](https://user-images.githubusercontent.com/4643389/90043573-93d6fa00-dccc-11ea-8548-88e551931df7.png)

This URL is different for each provider and must therefore be generated differently

eg:

  | Repo URL | Show Commit URL
-- | -- | --
github | https:\/\/github.com/larshp/abapGit.git | https: //github.com/larshp/abapGit/commit/17b6411cdb59cfb4478a8e6b3de1da3241fedd41
bitbucket | https:\/\/bitbucket.org/bigld/abapgit.git | https:\/\/bitbucket.org/bigld/abapgit/commits/17b6411cdb59cfb4478a8e6b3de1da3241fedd41
gitlab | https:\/\/gitlab.com/<user\>/\<repo\>.git | https:\/\/gitlab.com/\<user\>/\<repo\>/-/commit/17b6411cdb59cfb4478a8e6b3de1da3241fedd41          

Please provide repo URLs and commit URLs for other provider so we can support them, too.
Assembla, abapGitServer, SCP, AWS, TFS, Azure DevOps,...

thank you!

**Comment by sbcgua** [comment]
`https://gitlab.com/<user>/<repo>/-/commit/<hash>`

**Comment by ed-holland** [comment]
Local hosted gitlab repository:
https://<url>:<port>/<group>/<repo>/-/commit/<hash>

**Comment by FreHu** [comment]
We have this silly policy against sharing internal urls, but it's like this:

`https://github.<top_secret>.corp/<org>/<repo>/commit/<hash>`

But different enterprises might use a different TLD, we should just capture `github.(whatever)/<org>/<repo>/commit/<hash>`and use the match to build the commit url.

**Comment by larshp** [comment]
and http, https://github.com/larshp/abapGit/pull/3731/files#r469872442

**Comment by bigld** [comment]
Assumption:
if repo url is http(s)://<something>/<some path>/<repo>**.git**
show url is   http(s)://<something>/<some path>/<repo>/**<commit path>/<hash>**

Simple and flexible Solution:
we add a repo setting to set the <commit path> per repo 
or (if no setting) 
we search for gitlab. or github. or bitbucket. or ... in <something> and use the provider defined <commit path>

**Comment by mbtools** [comment]
A setting works but No one wants to maintain setting for potentially hundreds of corporate repos. I suggest a central class to cover the most common cases but add an exit for custom logic.

**Comment by larshp** [comment]
@bigld will you be working on implementing the findings from above?

**Comment by bigld** [comment]
I will start soon!

**Comment by EduardoCopat** [comment]
Closing as it solved by #4073
