### ISSUE TITLE
Action menu - order search results by longest match length

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#3738]
This is not the desired result:

![](https://user-images.githubusercontent.com/5097067/90244677-8424f600-de31-11ea-9c51-a261712345ca.png)

The user should see css files first as they have the most matched characters in a row.

**Comment by mbtools** [comment]
Stale. closing

for reference, a fuzzy logic would have to be implemented here:
https://github.com/abapGit/abapGit/blob/main/src/ui/zabapgit_js_common.w3mi.data.js

`function fuzzyMatchAndMark` and `CommandPalette.prototype.applyFilter`
