### ISSUE TITLE
CLAS/INTF: Inconsistent serialization

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#3741]
Collection of issues for CLAS serialization (some apply to INTF as well):

1. Different serialization depending on release (esp. older releases like 702)
2. Inconsistent sort order of method implementations (alphabetically or by edit order)
3. Missing edit order in serialization for SE24 users
4. Inconsistent case of class name in CLASS &lt;name&gt; IMPLEMENTATION
5. Comments before CLASS ... DEFINITION. are being erased in 702 
6. Pub, Pro, Pri sections of classes are not pretty-printer
7. Empty Pub, Pro, Pri sections are created with default comments on older releases
8. Statements in definition parts end with "&lt;space&gt;." or just "."
9. Returning clause uses value(...) although pretty-print is set to uppercase keywords

Proposed solutions:

- [ ] Always serialize method implementations alphabetically 
- [ ] Include edit order in serialize/deserialize
- [ ] Convert class name to lower case in CLASS IMPLEMENTATION statement
- [ ] Create abaplint check to check for comments before CLASS DEFINITION statement
- [ ] Always pretty print Pub, Pro, Pri sections 
- [ ] PUBLIC/PROTECTED/PRIVATE SECTION statements in case the section is empty (avoid generation with default comments)
- [ ] Replace "&lt;space&gt;." with "." at end of lines in definition sections
- [ ] If pretty-print is set to uppercase keywords, replace "value()" with "VALUE()" in Pub,Pro,Pri sections

Anything to add? Comments?

**Comment by larshp** [comment]
I think what is shown to the developer(class based editor in SE24 or ADT) when editing the object is what should be serialized

**Comment by mbtools** [comment]
that's exactly the issue: developers are seeing different output depending on the tool they use to edit classes and the release they are running on. However, a serializer should produce a standardized output independent of editor and release.

**Comment by flaiker** [comment]
You can get consistent results regarding method order and some upper/lower case stuff by using the exit [CUSTOM_SERIALIZE_ABAP_CLIF](https://docs.abapgit.org/ref-exits.html#custom_serialize_abap_clif). See religious beliefs discussion in #2321 and related PRs on why that's not the default behavior :)

**Comment by mbtools** [comment]
i'm aware of the exit and have implemented some of the above. But it's doesn't help the abapgit repo PRs if only I use it. Maybe the AG contributors could agree to use such exit limited to $ABAPGIT* packages.

**Comment by flaiker** [comment]
> Maybe the AG contributors could agree to use such exit limited to $ABAPGIT* packages.

- It will create another leap in git history where everything is reordered like the move from local to global classes.
- It's an additional hurdle for new contributors who might be already frustrated after meticulously fixing every abaplint error in their PR :)

**Comment by mbtools** [comment]
From #3960: I have one kind request @mbtools : would be really great if you don't mix style changes and feature changes. This makes the review a lot more difficult. I know it's tempting ... I barely can withstand myself ... and sometimes I don't ... :( But would greatly simplify ... Also some of stylings are opinionated which also adds some confusion.

@sbcgua: I would love to comply but I can't. Styling changes are almost impossible to avoid. I'm using SAPGUI (for various reasons, which we can discuss somewhere else) and any change using the SE24 form editor will require to use pretty printer afterwards to comply with our [guidelines](https://docs.abapgit.org/development/guidelines.html). 

1. Do we allow choice of editor for abapGit (SAPGUI, ADT, Vscode)? 
2. Which styling do we want to use for abapGit class/interface codeing (see list above)? 
3. What do we do with abapGit code that does not follow the guidelines?

A good topic for our next call.

**Comment by flaiker** [comment]
Something relevant: In the ADT class version comparison you can switch between the "normal" method implementation sort order, which might get corrupted at some point, and an alphabetical sort order which should filter out unwanted diffs. This unfortunately is a tooling specific solution to the problem.

![image](https://user-images.githubusercontent.com/5270359/97564534-03fc3e80-19e5-11eb-8ee2-29bab6748292.png)

**Comment by flaiker** [comment]
Another note: After system copy and reimport of transports that were not in production yet all classes have the alphabetical sort order and upper case class name again. I guess this applies to any object import using transports. I'll probably bite the bullet and activate the [custom clif serializer](https://gist.github.com/flaiker/999c8165b89131608b05cd371529fef5) to avoid this in the future. (I don't want to pull at all for the relevant repos)

**Comment by larshp** [comment]
yea, maybe we should go as far as making this an option in `.abapgit.xml`

I do consider this a bug in CTS, but I also think it will never be fixed

**Comment by mbtools** [comment]
It's not CTS. There are several bugs in how the class coding is generated. I have fixed them in my system via enhancements. 
- class name/endclass case
- section indent
- space dot
Not sure when I will find the time to fight with SAP support to get these fixed in standard. Might need some public community pressure. I can share my $hacks repo if you like. 

I mentioned in one of the calls that at least a one-time cleanup in the AG repo would help. Something for the cold winter months for me to do.

**Comment by mbtools** [comment]
Can be solved using `serialize_postprocessing` exit:
https://docs.abapgit.org/ref-exits.html#serialize_postprocessing
