### ISSUE TITLE
Idea to improve security/authorizations setup

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#3758]
abapGit is missing a general mechanism to secure various functions. We do have an exit (via `ZCL_ABAPGIT_AUTH=>IS_ALLOWED`) but it is used only in a few places.

Suggestion:

We call `ZCL_ABAPGIT_AUTH=>IS_ALLOWED` in `ZCL_ABAPGIT_HTML_TOOLBAR->ADD` which is used to construct all menus. We could pass the URL of the link/action (IV_ACT) to the exit. This would give users the option to implement an authorization check for any combination of action and repo since these are part of or can be derived from the URL. 

```
    IF iv_opt IS SUPPLIED.
      ls_item-opt = iv_opt.
    ELSEIF zcl_abapgit_auth=>is_allowed( IV_AUTHORIZATION = IV_ACT IV_PARAM = IV_TYP ) = abap_false.
      ls_item-opt = zif_abapgit_html=>c_html_opt-crossout.
    ENDIF.
```

Taking it a step further, the same logic could be added to `ZCL_ABAPGIT_HTML->ADD_A` to secure any links. 

Seem to me like a simple way to add a generic authorization check to abapGit. What do you think?

**Comment by larshp** [comment]
👍 

yea, ZCL_ABAPGIT_AUTH needs more work, above is in-line with what has been started

**Comment by sbcgua** [comment]
Some thoughts:
1) I wouldn't add so deep as `add_a` - `auth` is a "business" level of logic, not the level of technical util, e.g. how would `is_allowed` understand where `add_d` was called from and how would it impact the functionality. Even the toolbar is probably too deep. I'd rather call it directly in pages (which does know what to check). There is also uncontrollable JS ... so really should be on the level which "understands" what it is doing
2) Conceptually: ag is used by developers, who would have all the auth to bypass this check ... so practically ... it is more a marketing feature imho ... though, it is better to have as an argument just in case

**Comment by mbtools** [comment]
The requirements for more security are certainly there and prevent companies from adopting abapGit (https://github.com/larshp/abapGit/issues/3432). Without proper auth-checks, one can't call it "enterprise ready" which some (many?) companies require. 

Sure developers can bypass anything but doesn't mean there are consequences doing so (like job loss). Companies might have many repos and several dev teams that need "separation". Maybe only some are allowed to manage branches . And then there are test or prod systems where only certain git tasks might be authorized. 

Agree with you that "link level" isn't the right place. Page is probably not detailed enough. I'm just looking for a central place so we don't have to make big changes. Maybe GUI->HANDLE_ACTION and passing ACTION and PARAMETER_STRING_MAP ;-) to the auth check?

**Comment by larshp** [comment]
HANDLE_ACTION; think that would make it more difficult to use, the logic should be on the page, instead of having to dig into page logic to find the right authorizations

**Comment by flaiker** [comment]
Shouldn't the actual authorization checks be done in the business logic instead of in the frontend? For example I would expect the checks to also work when using the API which doesn't know anything about pages/buttons/toolbars/links. You can of course additionally call the checks beforehand to hide / gray out buttons.
