### ISSUE TITLE
Positioning of action buttons

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#3769]
I don't like the placement of many abapgit buttons, some I would even consider objectively bad in terms of UX.

In most forms on the web, the submit button would be at the bottom of the page because that's where you are when you're done with it.

abapgit of course does its own thing(s):

![](https://user-images.githubusercontent.com/5097067/90535215-f3c11b00-e17a-11ea-8811-dca9d03ebbc8.png)

Patch button placement is especially annoying because you go to the bottom to select your changes need to go back to the top to continue (home button helps).

![](https://user-images.githubusercontent.com/5097067/90535265-03d8fa80-e17b-11ea-8078-666dc4290b10.png)

Stage

![](https://user-images.githubusercontent.com/5097067/90535530-469ad280-e17b-11ea-8fb2-cfbc5958b4ca.png)

Repo

![](https://user-images.githubusercontent.com/5097067/90535699-7d70e880-e17b-11ea-810f-7993c5c73b7e.png)

Buttons which make you switch pages should be on the bottom of the page. The Belize theme has this floating action bar at the bottom where such buttons should be. Unfortunately this is not part of the html, and relies on gui statuses, where you can promote a gui status button to this location if the user has the belize theme enabled.

So I propose doing exactly this in html, in all themes (I guess the belize theme will have a taller bar because I don't see a way of removing this).

This would also make the button placement consistent with every (recent) SAP application. Also see https://experience.sap.com/fiori-design-web/action-placement/

**Comment by mbtools** [comment]
Agree. Consistency is king. I don't think we must do exactly what SAP is doing, but the fiori design guide is excellent. 

Regarding toolbars/buttons, a key part is making the sticky to top or bottom and have only the core content part scroll. We need some CSS magic.

**Comment by sbcgua** [comment]
The mentioned "css magic" is called `position: sticky` and is not supported by IE (although after some recent discoveries with SVG I already have some doubts if IE runs Edge under the cover in Win10 ... :)
The idea is good. Any draft pre-renders ? :)
Also: part of the issues can be solved by narrowing the view area (except diff). So I'd suggest having some prototypes to save the effort

**Comment by FreHu** [comment]
I've definitely seen this done IE compatible and I've never heard of position: sticky. IIRC, it's position: fixed that can do this as well.

**Comment by sbcgua** [comment]
problem with "fixed" is that you have to "calculate" how it will look at any scroll position (e.g. Save button in settings). and "sticky" is a combination of "fixed" and "relative" depending on the scrolling. Really cool css feature - https://medium.com/@elad/css-position-sticky-how-it-really-works-54cd01dc2d46 :)

E.g. the "save" button in settings - it is on the edge of ugliness imho :) The sticky would be perfect and allow align the button properly. As I understand, before "sticky" this was achieved by JS.

**Comment by mbtools** [comment]
We refactored all dialogs and many popups so button placement is pretty consistent.
