### ISSUE TITLE
abapgit API test page

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#3770]
Add a page for testing abapgit functions for an arbitrary object. This could be useful for debugging/development purposes. Off the top of my head, we could have

*   Serialization
*   Last changed by
*   Transport request
*   ADT link/jump
*   Performance measurements

It would take place of this function (or maybe hide it under debug info).

![](https://user-images.githubusercontent.com/5097067/90536850-e3aa3b00-e17c-11ea-83ea-06ff34fa0619.png)

**Comment by larshp** [comment]
do we need this? close?

**Comment by mbtools** [comment]
Much is tested in https://github.com/abapGit/CI. If something should be added, let's open an issue on CI repo.
