### ISSUE TITLE
Integration testing with ABAP Unit

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#3776]
I think it could be useful to create a test suite to preform a turnaround test: Deserialize a new object from XML, then serialise it and compare the resulting XML to verify it matches. This could be fully automated at object type level, each object type pulling the test from repo `abapGit-tests/XXXX`

I thought the first part would be quick and easy, but it turned out to be a bit more complex. I am currently implementing PDTS and started off by just pasting the XML from Github into the test code. However on attempting the initial turnaround, I spent way more time than anticipated in trying to match up the input/output XML classes, I think something needs to be harmonised there as the stringified XML is different with all the simple approaches I tried. Or maybe I'm going about it the wrong way and should be using the FILES class. Nevertheless, I'd like to focus on the PDTS/WS objects for now so am parking this issue here and if anyone would like to throw some ideas in or run with it then they're welcome. 

If anyone is interested in my first approach, it's [zcl_abapgit_object_pdts](https://github.com/larshp/abapGit/blob/pokrakam/object-pdts/src/objects/zcl_abapgit_object_pdts.clas.testclasses.abap) (not in `master` yet).

**Comment by larshp** [comment]
unit tests should not be dangerous to the customer system IMHO, as far as I remember its possible to filter the selection in https://github.com/abapGit/ci, so it can run for just one repo at a time

**Comment by pokrakam** [comment]
I see value in both local unit tests and in abapGitCI. CI is a more comprehensive higher level test, but unit test has more TDD-friendly performance. PDTS create-compare-delete now runs pretty quick on my laptop because everything is local.
![image](https://user-images.githubusercontent.com/25539927/91036059-8ee44580-e5fe-11ea-8bf3-67651923e61a.png)

On a grander scale, it could be feasible to have a common framework of global test classes used by ABAP Unit and abapGitCI. For speed reasons, the unit tests could use hardcoded repos, which could be generated from the GitHub test repos. Feel free to add a low priority or crazy label :)

The reason for critical is because we are creating objects and can mess things up. I've ended with corrupt classes that SE80 says are there, but try to delete or edit and it says doesn't exist.

**Comment by mbtools** [comment]
For the developer of a new ser/deser class it's essential to do frequent end-2-end tests. I currently do it manually with repos from abapgit-test. 

For others, I think centralized abapgitCI is sufficient. maybe we can combine both and come up with a generic unit test for these classes. Could be activated by a checkbox on the debug page for selected object types.

**Comment by larshp** [comment]
or just run the report that already exists

**Comment by mbtools** [comment]
See https://github.com/abapGit/abapGit/pull/3961
