### ISSUE TITLE
ACGR: Support for PFCG roles (authorizations) 

### ISSUE THREAD

**Issue by gardian12** [abapGit/abapGit#3860]
Hello together, I need to resume the initial feature request #827 

**How to handle roles?**

Here are the facts about roles:

- Roles can't be handled with BC Sets
- Roles are customizing and not linked to a development package
- Roles are essential part of an application and should be delivered as well
- Roles can be easily handled as files, see transaction PFCG (upload / download function)
- Therefore it would be highly recommended also to cover PFCG roles by abapGit
- Without disturbing the core of abapGit it would be possible.

As an example: Customizing files, like roles, could be stored with a separated folder /**_cust_**/, parallel to /**_src_**/.
Manual selection of role to be added to the repo would be needed any way.

Hope you can reopen, the feature request with this insights.

**Comment by jrodriguez-rc** [comment]
We can build initial object support based on Download/Upload roles functionality
![image](https://user-images.githubusercontent.com/56556686/92698006-3629e200-f34c-11ea-98ef-4475da10c361.png)

As a workaround, while is thinking how to assign customizing to the repository, roles can be added via abapGit exit `zif_abapgit_exit->change_tadir`

**Comment by gardian12** [comment]
Well at first we can keep it simple, like a simple upload/download option at abapGit UI to keep or retrieve the files.
In background there should be a separated folder created and handled by abapGit to store the files.
This folder should be different to the _src_ folder not to harm the development objects underneath.

**Comment by jrodriguez-rc** [comment]
Some additional changes need to be done, everything outside of `/` and `/src/` folders is ignored
![image](https://user-images.githubusercontent.com/56556686/92709372-24017100-f357-11ea-935a-9e0cda778c04.png)

**Comment by jrodriguez-rc** [comment]
Role support is being discussed in this issue #3474

**Comment by gardian12** [comment]
When everything outside of `/` and `/src/` folders is ignored, we do not have a problem o create a folder beside `/src/` (e.g. `/cust/`) to store additional files. The function module `PRGN_DOWNLOAD_AGRS` and `PRGN_EXECUTE_UPLOAD` can do the job of writing and receiving a role as file. Details as discussed in #3474 are covered by these.

**Comment by mbtools** [comment]
Since there are no `TADIR` entries for roles i.e. no association with packages, I would treat them the same way as `TABU` data. An extension of the current data serializer seems feasible resulting in role data being persisted in `/data/`.

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.

**Comment by services-holland** [comment]
Following @IGNVDRON sollution...
One could store the Roles prefixes in the REPO repository settings (similar to texts objects) and allow selection from there.
That would not require a change to a domain.
