### ISSUE TITLE
Transport Task(repair; development/correction) issue on deserialisation 

### ISSUE THREAD

**Issue by habrahams** [abapGit/abapGit#3865]
Scenario, pulling a repository which contain objects that are deemed "repair" as well as "development/correction", the first task "repair" is created in the created request, but when the objects are processed that are deemed  "development/correction" an error is thrown that states that there is no applicable "development/correction" task in request.
If you create a new task in the request and change the type to "development/correction" and re-run the pull the issue is resolved.

**Comment by mbtools** [comment]
There shouldn't be any repairs. Repairs happen when you transport an object from another system and then change it (instead of changing in the original system). If this happens in your dev system, then you should change the original system for the imported objects in SE03 (to the dev system). Then there won't be any repairs.

**Comment by habrahams** [comment]
Yes, strictly speaking you are correct, and this can be used to get past the "repair" task issue, and if that is the answer then I am happy with that.
This said, would it be possible to handle this scenario more gracefully? For example providing a descriptive error message stating that object repairs are not supported and that the objects in question's original system needs to be changed before performing a pull?

**Comment by mbtools** [comment]
OK, transparency first. How about we display an icon after the object name, if the object is not original to the system (i.e. was transported from another system; tadir-srcsystem <> sy-sysid)? When hovering over the icon, we could show the system id, where the object came from. 
Then we can think about raising an exception, in case a pull tries to overwrite the foreign objects. Or we could even add a menu item to change the tadir-srcsystem to the local system (basically what SE03 does).

**Comment by habrahams** [comment]
I think your suggestion(s) would address the issue perfectly! I would be really happy with that.

**Comment by mbtools** [comment]
![image](https://user-images.githubusercontent.com/59966492/101564372-0a44e980-3999-11eb-8b27-92b7e861c5de.png)

needs a different icon, but shows what it would look like. maybe this?
![image](https://user-images.githubusercontent.com/59966492/101564766-bedf0b00-3999-11eb-879e-257bc2083b53.png)

**Comment by larshp** [comment]
icon suggested seems good, just something thats not currently used, we can always change it

**Comment by habrahams** [comment]
@mbtools , sorry for not getting back to you. I've relocated to the US and haven't had much time to respond.
