### ISSUE TITLE
Initial support for customizing content folder

### ISSUE THREAD

**Issue by jrodriguez-rc** [abapGit/abapGit#3866]
Now is only possible serialization of objects in the initial folder (by default `/src/`)
![image](https://user-images.githubusercontent.com/56556686/92709372-24017100-f357-11ea-935a-9e0cda778c04.png)

A suggestion could be to change "initial folder" for "repository folder" and add another for "customizing folder"
![image](https://user-images.githubusercontent.com/56556686/92893521-09440080-f41a-11ea-870b-876b774ea60c.png)

This should be previous to #3441 and I don't know if customizing serialization is supported in Cloud (Harmonization of object serializers in ABAP in the Cloud and abapGit. #3349)

**Comment by larshp** [comment]
note this topic is on the agenda for https://github.com/larshp/abapGit/issues/3834

**Comment by larshp** [comment]
closing, use https://github.com/abapGit/abapGit/issues/3441 instead
