### ISSUE TITLE
TABL(DDIC Structure with .include) serialisation/deserialisation issue with check tables and explicit search helps

### ISSUE THREAD

**Issue by habrahams** [abapGit/abapGit#3867]
I have run into an issue when I push a DDIC structure to a repo and pull the structure into another system.
Now there are two issues, and I think they are related.

This said, the system I push from, the structure is pushed successfully and Abapgit does not show any object differences after the push, thus I assume that the push has completely pushed the structure.

The structure has two .include statements, the one include exists in another package and is not part of a repo. The second is a place holder for customer enhancements(The second include structure does not exist it is a infotype customer enhancement structure).

The first structure has check tables and explicit search helps attached in the DDIC se11 view.

The first issue(After pull, Abapgit reports changes in local objects): When the deserialisation happens, the object cannot be activated because it says the second customer include does not exist(The activation issue does not happen with the other structures which also has a second include that does not exist).
![image](https://user-images.githubusercontent.com/16045067/92902344-7f983100-f421-11ea-8af0-e44cc80e637e.png)
If I activate it manually it activates successfully. 

After the activation the check tables that should be inherited from the first .include structure are missing. If I edit the structure in SE11 by removing the .include structure, add an arbitrary field, activate the structure, remove the arbitrary field and put back the .include structure and activate it, the check tables are once again present, this leads to the second issue where a fields has a check table and a explicit search help attached to the field.

The second issue(After manual structure fix): When I go to Abapgit and refresh the comparison, abapgit reports that now there have been changes on the remote and it is pointing to the explicit search helps attached to the fields which I just resolved the check table issue.

1. DDIC Structure on source system:
![image](https://user-images.githubusercontent.com/16045067/92898317-2d094580-f41e-11ea-8ea6-02f3a4d4bab0.png)

2. DDIC Structure After Pull
![image](https://user-images.githubusercontent.com/16045067/92902951-fd5c3c80-f421-11ea-902b-685d0fae5554.png)

3. Abapgit diff after pull and manual activation
![image](https://user-images.githubusercontent.com/16045067/92903643-85424680-f422-11ea-8a0d-608d9ce5b596.png)

4. Removing/Restoring the first include resolves the missing check tables.
![image](https://user-images.githubusercontent.com/16045067/92907444-a0fb1c00-f425-11ea-90ba-d1e8a87e007e.png)

5. Comparison after check tables restored
![image](https://user-images.githubusercontent.com/16045067/92905356-e0c10400-f423-11ea-8d2a-501a6a3d4a40.png)

**Comment by mbtools** [comment]
Known issue with foreign keys in includes https://github.com/larshp/abapGit/issues/1079

Activation of foreign keys should be fixed with same logic as https://github.com/larshp/abapGit/pull/3545:
- remove keys during DDIC phase
- add keys during LATE phase
https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_tabl.clas.abap

want to give it a try?

**Comment by habrahams** [comment]
@mbtools I'll have a look at it as soon as I get a chance. If I think I'll be able resolve the issue I'll confirm first. If anybody else wants to pickup the ticket please do so.

**Comment by habrahams** [comment]
@mbtools thanks a lot for this!

**Comment by habrahams** [comment]
@larshp , I have picked up another issue with regard to the serialisation/deserialisation of the foreign keys.
Should be reopen this issue or should I create a new one?

**Comment by larshp** [comment]
create new please
