### ISSUE TITLE
SFPF issue after deserialisation 

### ISSUE THREAD

**Issue by habrahams** [abapGit/abapGit#3868]
After a SFPF object has been deserialised to a different system, Abapgit shows local changes:
![image](https://user-images.githubusercontent.com/16045067/92908172-4615f480-f426-11ea-8c88-b15e77303012.png)

**Comment by mbtools** [comment]
CACHE_INFO needs to be cleared during serialize
https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_sfpf.clas.abap#L317

**Comment by larshp** [comment]
merged, closing
