### ISSUE TITLE
Dialogs: Global Settings (preview)

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#3878]
![image](https://user-images.githubusercontent.com/59966492/92975492-62318a00-f456-11ea-9a04-00706b9a06b7.png)
![image](https://user-images.githubusercontent.com/59966492/92975311-f6e7b800-f455-11ea-8ca4-1acb2048c4a4.png)

Using ZCL_ABAPGIT_HTML_FORM takes about half the coding compared to the old settings page... with better looks and features. thx @sbcgua!

**Comment by larshp** [comment]
again, do note https://github.com/larshp/abapGit/issues/3417, exactly the global settings have a lot of fields, which might not work with GET(if that ends up being a solution)

**Comment by FreHu** [comment]
Nice, but the title case is gone!

**Comment by mbtools** [comment]
It’s some CSS that hasn’t been used before. Group titles also need darker colour. I will adjust it. 

User settings will be different dialog. Tricky part is the table of hotkeys which doesn’t have a matching HTML form field type yet

**Comment by sbcgua** [comment]
There was also a discussion somewhere about removing the hotkey settings ... I'd probably create a separate component for table. With optional `input` column to integrate it is a "form".
