### ISSUE TITLE
Make a repo's master language configurable

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#3894]
A repo's master language is read-only in the repo settings, but should be changeable. One use case for changing it is to move objects to a target system with a different master language. It's not that unusual, and not the first time I'm working in a multi-language landscape

Two workarounds are to use the DB util or recreating the repo while logged on in the other language, so I'd suggest this could be a low priority good first issue type of change if nobody has any arguments against it.

It looks like a deliberate decision as it is the only read-only item at the top with all others changeable below it:
![image](https://user-images.githubusercontent.com/25539927/93389444-1458bf80-f864-11ea-94ea-b0291449e075.png)
Am I missing an important reason or can this be changed? Or perhaps we should be able to address this on the import (better solution IMO, but probably more work)?

**Comment by mbtools** [comment]
intentionally. "if someone changes the master language I think it can cause a lot of problems for the user"
https://github.com/larshp/abapGit/issues/3413#issuecomment-633232415

keep in mind that many objects only contain texts in your logon language, let's say English. if you logon to another system in French, how should they be imported? Without text? or with English text in the French text field? Overall, quite confusing.

**Comment by pokrakam** [comment]
Thanks for the pointer, I searched for a previous issue but somehow missed that one.
Personally I found the current setup confusing and it caused me problems. Importing a 'foreign' repo failed with a cryptic error  telling me I should install the repo (didn't have time to fully debug to understand it). 
In this scenario, I created a repo containing German objects while logged on in English. I figured using the 'All Language' setting would carry all texts across and import all objects with their original language, just like a ToC. But then I was surprised that abapGit would apply a blanket language setting that has to match the repo-creator's login language. I could not make it import until I XML-Edited the repo to change the language.

**Comment by flaiker** [comment]
There at least used to be a very clear message "Please logon in master language XY (Advanced -> Switch to master language)". Is that not the case anymore? And switching the logon language is very convenient using the button.

I think you can't import objects with a different master language than the logon language as not all used object APIs have a parameter for that and might default back to sy-langu which would cause mixed behavior (?).

**Comment by pokrakam** [comment]
Yes, but it doesn't work. The scenario here is that I wanted to import in a language (D) different to the source repo (E). So switching my language to E in the target system is not the solution.

I just checked again and the message is: 
`Current login language 'DE' does not match master language 'EN'. Run 'Advanced' > 'Open in master language' `
When trying to open in master language, I get a cryptic: 
`Please install the abapGit repository`

If this gets messy then I would suggest not spending too much time on it. I thought a quick fix to make it configurable in the importing system would be the easy answer, but it may not be such a widespread hurdle.

PS. the weirdest setup I've had was a customer with an IS and an ECC system in EN and DE. The weird part was that they even mandated that code comments should be in the corresponding language in each system.

**Comment by flaiker** [comment]
Hmm, I haven't worked with multi language landscapes. But I would have assumed that changing the master language (at package level) is something done very rarely. Wouldn't you have to completely translate all objects, even the ones where translation relevance is set to none, before doing the conversion? Including a full development stop in between? Otherwise the target texts will be either empty or in the previous master language which then messes up the translation process going forward?

**Comment by pokrakam** [comment]
Yes the target texts such as class descriptions will be empty if you're logged on in another language, this is also the result of a ToC. I don't like it but it's the status quo and we have to work with it. There are numerous scenarios that result in a multi-language landscape:
- Customer has German legacy system and want to change to English going forward so the new XYZ system shall be English
- A third party / integration partner or outsourcing requirement mandates at least a partial switch to English
- Specific country-centric systems in large multinational corporations
- Corporate mergers

And yes it's messy and can be a pain, but it also hilights the need for naming objects well so that descriptions are not that necessary. I have never needed to change translation relevance or stop development. e.g. If I see a few blank names I may take a few minutes to pull up the other language and update them in the missing language, it gets included in the current work, leaving the campsite a bit better and all that.

**Comment by flaiker** [comment]
I see. I would just fear that "in between" changing the master language from DE to EN and having all texts available in the new master language EN the translation office does its thing and maintains translations from EN to DE now. And since some EN texts are still missing they'll maybe just delete the existing DE ones too.

Even if we don't enable it to be switched in the UI we should at least document the process on how to do it manually. I looked at SE03 -> Change object catalog entries -> Fcode MASS and found you cannot mass change the original language there. I also was unable to do it using TOC or relocation nor did I find anything in I18n to mass change the original language. How did you do it? The only way I found is to login in the new language and edit each object individually forcing the "Do you want to change the original language" popup.

**Comment by pokrakam** [comment]
I've not used this to change the master language of the individual objects, but it does make it an annoyance to move between systems and users that work in different languages when abapGit blocks mismatched languages. 
An English user on an English system should be able to import a repo created by a German user on a German system. Or perhaps it's supposed to work and the `Please install the abapGit repository` message is misleading or incorrect?

But that said, I'd suggest that if we did want to mass-change objects' language then a mass replace through the XMLs is the easiest way to do it.

**Comment by larshp** [comment]
Last I tried it worked, login to the system in German and install the project with master language = German

**Comment by flaiker** [comment]
Afaik systems aren't english or german, they just have an amount of languages that are installed and which you can login with. The english user could install the german repo by pressing the logon in master language button and then pressing pull, assuming german is installed in general.
At least that's how I update abapGit at work where I usually log on in the german language.

**Comment by mbtools** [comment]
this only works properly for object types that support master language and i18n. most object types, however, do not have this feature and you will have to study the code to see which language is actually updated during a pull. (see https://github.com/larshp/abapGit/search?q=i18n&unscoped_q=i18n for classes that support it).

maybe as a first step, we extend the metadata with a "supports i18n" flag and update dev docs on how to implement i18n.

**Comment by mbtools** [comment]
I don't see us changing the current behaviour. Closing
