### ISSUE TITLE
ZCL_ABAPGIT_MESSAGE_HELPER->GET_T100_LONGTEXT seems broken

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#3906]
start after https://github.com/larshp/abapGit/pull/3905 is merged

this will never assign anything, https://github.com/larshp/abapGit/blob/9c41a2b7d851e62a88785a90448a63b3ce34a8d3/src/zcl_abapgit_message_helper.clas.abap#L281-L285

plus RV_TARGET is CHAR01, and `CONCATENATE '&' iv_arg '&' INTO rv_target.`

**Comment by mbtools** [comment]
Found the bugs... 3 in total related to the T100 longtexts.
- Incorrect `me` reference leading to dump
- Wrong length of rv_target (error came with https://github.com/abapGit/abapGit/pull/3204 by changing `exporting ev_target type c` to `returning rv_target type char01`)
- T100 message during object deletion lost the T100 info and showed up as 00(001)
PR otw

**Comment by larshp** [comment]
good first issue, yea, its difficult to know without spending some time
