### ISSUE TITLE
docs: anchor links in /development/

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#3926]
The links in https://docs.abapgit.org/guide-install.html are ancored, so it can be easily shared

However, this is not done for the /development/ folder, example https://docs.abapgit.org/development/api.html

**Comment by larshp** [comment]
anchors, 

![image](https://user-images.githubusercontent.com/5888506/94231241-e4fd1f00-ff03-11ea-9640-b184d3d5cf30.png)

**Comment by mbtools** [comment]
https://docs.abapgit.org/development/api.html is written according to specs:
https://github.github.com/gfm/#atx-headings

Look at https://docs.abapgit.org/ref-dot-abapgit.html. Some headings have anchors, others not. The HTML is generated by GH so the problem seems to be on their side.

**Comment by mbtools** [comment]
pages, where anchors work, have a bit of JS included at the end. no idea why the API page doesn't have the JS. 🤷‍♂️ 

the comments in the JS are helpful: h1 no anchor, h2-h4 will get anchors, h5-h6 no anchor. I will edit some of the pages based on that.

**Comment by larshp** [comment]
I forgot to add the JS to the /development/ pages, or the development pages were added later
