### ISSUE TITLE
Sync directly between two abapGits in different systems?

### ISSUE THREAD

**Issue by nununo** [abapGit/abapGit#3928]
Hi,

I'm currently not using a git server. So, when I need to sincronize a package between two systems I have to export a zip on the source and import it on the target.

I actually found this zip features quite smart and it works pretty well. Congratulations.

But I was wondering: wouldn't it be neat if I could tell the abapGit from the target system to directly connect to the abapGit of the source system and skip the zip files altogether?

This would necessarily need abapGit to be accessible via a published API. But maybe that would be feasible.

Anyway, just an idea. Curious to know what everyone else things about it.

Cheers,
Nuno

**Comment by larshp** [comment]
install https://github.com/larshp/abapGitServer ?

**Comment by nununo** [comment]
I guess you're probably right. abapGitServer will solve it :)
