### ISSUE TITLE
abapgit.org landing page

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#3937]
I've switched off the redirect for abapgit.org, and now it will show https://github.com/abapGit/abapgit.org instead

Suggest making https://abapgit.org a landing page with 3 simple links:
* documentation, https://docs.abapgit.org
* code, https://github.com/abapGit/abapGit
* eclipse plugin
* projects, https://dotabap.org

**Comment by mbtools** [comment]
I like the simplicity of the abap**lint**.org homepage/tiles. I would add two more tiles:
- quick start, https://github.com/abapGit/abapGit/blob/master/README.md
(can this be shown without the Github stuff around it?)
- demo (some youtube of the latest version)

**Comment by FreHu** [comment]
Direct link to latest full report would also be useful.

**Comment by larshp** [comment]
thinking something like this, the boxes are images/icons,

![image](https://user-images.githubusercontent.com/5888506/109603326-f76a2d00-7b21-11eb-9040-3cea7196a5c9.png)

Possible Scenarios:

- Backup and Transparency
- Code Review
- Static Analysis and Testing
- Moving to Steampunk
- Upgrading to S/4
- Safely moving changes to Production
- Code Transformation
- Serverless ABAP

**Comment by larshp** [comment]
+ search possibilities

**Comment by schealex** [comment]
i'm gonna put something together

**Comment by schealex** [comment]
![image](https://user-images.githubusercontent.com/3441348/109699687-24a1f400-7b91-11eb-90dd-ed19e5fb5be5.png)
here is a quick preview of what i got so far ;)

**Comment by larshp** [comment]
we already use Font Awesome in a few places, https://github.com/abapGit/abapGit#credits-and-references

So guess the placeholders can be replaced with some icons

**Comment by schealex** [comment]
progess can be tracked here https://github.com/schealex/abapgit.org

i've also created a `data` folder within `src` where you can find the data that will be used to generate the content of the page. We would only need to add there if we want to add further links / scenarios

let me know what you think guys :)

**Comment by larshp** [comment]
on the docs homepage, we have the content centered,

![image](https://user-images.githubusercontent.com/5888506/109752477-c270df80-7be0-11eb-9ead-cd1e2b453b63.png)

its 4.3MB to serve a HTML page that I guess is less than 100kb? the dist might not be shaken and minified, but still,

![image](https://user-images.githubusercontent.com/5888506/109752583-f3e9ab00-7be0-11eb-89a6-04202b37ea69.png)

**Comment by schealex** [comment]
I'm still working on the layout but good to know that it should be centered ;)

also regarding the size, yeah if you run the dev version with debugging and source maps and all of that sure thats quite big :D

Check the actual builded version:
![image](https://user-images.githubusercontent.com/3441348/109780064-e9420c80-7c06-11eb-900b-01bdb49efc9c.png)
i find 44kb quite small for a modern frontend ;)

**Comment by larshp** [comment]
hmm, yea, well, is there a way to take the HTML and css and just store that?

I think its a lot of setup, with 150mb+ modules, to generate a single static HTML page?

**Comment by schealex** [comment]
Yeah sure the final build package is just some html, css and a small js file. Just a couple hundred kb including the images. Which can be build and deployed whereever you want via CI.

I'm a bit sick at the moment but will return to working on it soon. 

About the Scenarios, should it just be a list with short descriptions and then links to the project / seperate page or would you also like to have subpages for each?

**Comment by larshp** [comment]
Scnearios: as a starting point just a short list with links

**Comment by larshp** [comment]
@schealex any news? I might have some time during this week...

**Comment by schealex** [comment]
Hey @larshp i've just pushed some updates. Could you please check if there is still something missing for the base page functionality? I've also added a search based upon algoliasearch which is the one we spoke of before. You will need to setup a account there and get a api key and access token. I can provide you my test-one's if you need them to try it out.

**Comment by larshp** [comment]
https://github.com/schealex/abapgit.org

**Comment by larshp** [comment]
algoliasearch: I dont think there will be any content to search, at least for now, its just one static landing page with links

**Comment by larshp** [comment]
see https://github.com/abapGit/abapgit.org/pull/1

**Comment by larshp** [comment]
merged, https://abapgit.org

follow https://github.com/abapGit/abapgit.org for progress and updates

**Comment by larshp** [comment]
Possible improvements, from above and slack,

* Maybe another tile could point to https://docs.abapgit.org/other-articles-and-presentations.html
* quick start, https://github.com/abapGit/abapGit/blob/master/README.md
(can this be shown without the Github stuff around it?)
* demo (some youtube of the latest version)
* use-cases/scenarios, see https://github.com/abapGit/abapGit/issues/3937#issuecomment-788627865

**Comment by mbtools** [comment]
https://github.com/markedjs/marked#usage to render the readme.md

**Comment by larshp** [comment]
done for now, closing
