### ISSUE TITLE
Dependencies on Uninstall

### ISSUE THREAD

**Issue by abap-weasel** [abapGit/abapGit#3949]
Hi abapGit guys,

I am wondering if anybody else has difficulties when it comes to dependencies, which would lead to a dialog prompt, while uninstalling. When such an situation occurs an error message like this is shown:
"Object TYPE NAME has dependencies and must be deleted manually"
Afterwards Uninstall is stopped. 

I think it would be viable to have abapGit continue deleting repo objects and have it retry objects that had a dependency again later afterwards. Maybe this could be enabled via a setting like "Retry Uninstall 3 Times".

Example: 
We have a structure A that is included in another structure B. 
abapGit stops when trying to delete structure A and shows dependency message.
If abapGit would continue to delete until structure B is gone, it would be able to delete A later.

I have tried to implement that already but I was not able to pull it off. :-( 
So I'd like to at least leave this suggestion here.

**Comment by larshp** [comment]
Above is what class [ZCL_ABAPGIT_DEPENDENCIES](https://github.com/abapGit/abapGit/blob/master/src/zcl_abapgit_dependencies.clas.abap) tries to do

do you have a specific example where the error occurs?

**Comment by mbtools** [comment]
please test with the latest version which performs several tries to delete objects. If this doesn't resolve your issue, please provide a public test repo.

**Comment by larshp** [comment]
@abap-weasel

**Comment by larshp** [comment]
closing, not possible to reproduce, no reply
