### ISSUE TITLE
Clarification of ZIF_ABAPGIT_OBJECT~EXISTS required

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#3964]
According to https://docs.abapgit.org/development/serializers.html, `EXISTS` should check if an object exists. However, several classes only check if an active version of the object exists and return false although an inactive version might exist. Is this intended or a bug?

Examples:
https://github.com/abapGit/abapGit/blob/master/src/objects/zcl_abapgit_object_dtel.clas.abap#L227 (call with status = 'A')
https://github.com/abapGit/abapGit/blob/master/src/objects/zcl_abapgit_object_doma.clas.abap#L303 (select with as4local = 'A')
https://github.com/abapGit/abapGit/blob/master/src/objects/zcl_abapgit_object_type.clas.abap#L80 (call with r3status = 'A')

This has a side effect in case classes check for existence for example before deletion and therefore inactive objects do not show in the repo view nor can they be uninstalled. I guess I answered my own question -> It's a bug ;-) 

Example:
https://github.com/abapGit/abapGit/blob/master/src/objects/zcl_abapgit_object_tabl.clas.abap#L575

**Comment by larshp** [comment]
yea, did not consider the above scenario, some changes are needed to handle it
