### ISSUE TITLE
install abapgit, tutorial page

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#3965]
looks like abapgit_install / install_abapgit was removed from the tutorial page?

so the corresponding code can be deleted

https://github.com/abapGit/abapGit/blob/fff8f1b237f43135435b7c98527ca19b5df86042/src/ui/zcl_abapgit_services_abapgit.clas.abap#L28

**Comment by flaiker** [comment]
Seems to have been moved to debug info?

https://github.com/abapGit/abapGit/blob/1e93c1d3d360efbf646ac190aa1d3341700ca12e/src/ui/zcl_abapgit_gui_page_debuginfo.clas.abap#L115-L123

**Comment by larshp** [comment]
hmm, seems a bit hidden
