### ISSUE TITLE
Diff/Patch: Description in beacon

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#3973]
Not sure how it works but shouldn't the `@@ CLASS ... IMPLEMENTATION => METHOD method_name` be rendered directly above the `METHOD method_name` line?

![image](https://user-images.githubusercontent.com/5270359/94921119-e99f7580-04b7-11eb-8983-a9b61ec6d99a.png)

**Comment by flaiker** [comment]
Actually looking at it closer the method name also doesn't fit `interface_00001040` <> `interface_00001011`.

**Comment by christianguenter2** [comment]
Yeah, looks a bit strange. Diff page should be the same?
Reason is that the shortlist code block starts 8 lines before the actual change and ends 8 lines after the change. And the beacon with context info is then taken from the beginning of the shortlist code block.
Logic is here:
https://github.com/abapGit/abapGit/blob/1e4560b32aab75dfd59f5fb899ee26fe1b5b0f2b/src/utils/zcl_abapgit_diff.clas.abap#L361-L382

**Comment by christianguenter2** [comment]
Beacon calculations happens here:
https://github.com/abapGit/abapGit/blob/1e4560b32aab75dfd59f5fb899ee26fe1b5b0f2b/src/utils/zcl_abapgit_diff.clas.abap#L195-L228

And rendering here:
https://github.com/abapGit/abapGit/blob/a49b68efa7fdf57f5e967cd6310d91f4c2671046/src/ui/zcl_abapgit_gui_page_diff.clas.abap#L567-L587

**Comment by flaiker** [comment]
I see, then it makes sense somewhat. Maybe the amount of lines loaded around the diff should take the current block into account?  

Git CLI seems to just render the text of the block one level higher up:

![image](https://user-images.githubusercontent.com/5270359/94987271-689eb780-0565-11eb-923c-fc208f6561e7.png)
