### ISSUE TITLE
"Branch master not found" when creating online repo

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#3974]
Github recently changed the default branch name to "main" (https://github.com/github/renaming). However, when you try to create a new online repo in abapGit, the default will be set to "master" leading to the following error:

![image](https://user-images.githubusercontent.com/59966492/94938331-af75aa00-049e-11eb-870a-74471053ff11.png)

Issue:

abapGit does not automatically detect the name of the default branch. The initial default branch is hardcoded to refs/heads/master (`zif_abapgit_definitions=>c_git_branch-master).

Workaround:

When creating a new online repo, enter "main" as the default branch:

![image](https://user-images.githubusercontent.com/59966492/94938373-bc929900-049e-11eb-9d9d-da27a4801cd8.png)

**Comment by sbcgua** [comment]
I think this can be fixed. The branch list contains special branch "HEAD" which is the master branch. It was even in the branch list before, then removed. So technically should be possible to go through the branches, comparing the SHA1, and identify anonother non-HEAD branch which will be the master or main

**Comment by sbcgua** [comment]
Scanning the code for `'HEAD'` may help, I can see just a couple of places, one of which is a global constant which is yet used in another couple of places.

**Comment by mbtools** [comment]
yes, just a bit tricky since at that time the abapGit repo doesn't exist yet. `ZCL_ABAPGIT_BRANCH_OVERVIEW->GET_BRANCHES` requires the repo

**Comment by larshp** [comment]
reproduces with public repository https://github.com/larshp/head_branch_main
