### ISSUE TITLE
Diff view: 'Last changed by:' is unknown

### ISSUE THREAD

**Issue by GiantCrocodile** [abapGit/abapGit#3988]
Hello,

I noticed that the 'Last changed by:' information has the value 'unknown' if you just clone an empty repository and want to do a diff view before pushing objects for the first time.

It's a minor issue but I suspect it should show the local last change user, not the one from the repository (being not available at this moment).

Happens on NW 740 with abapGit v1.100.0. The changed objects are a simple report and a basic ABAP class.

Best Regards,

**Comment by mbtools** [comment]
"last changed" is always a local user. however, some objects don't support it (like .abapgit.xml) and will always show "unknown".

I tried to reproduce it with a new repo and a program and diff correctly shows my user id as last changed. do you have a screenshot?

**Comment by GiantCrocodile** [comment]
Ah, I didn't notice that it's a per-file field; I thought this information is only shown once for the whole set of changes.

Nevermind, I will close this issue.
