### ISSUE TITLE
Group all UI pages in separate package

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#3990]
UI page classes are mixed in with many other GUI and utility classes in $abapgit_ui. The suggestion is to put all UI pages into a separate $abapgit_ui_pages package.

**Comment by sbcgua** [comment]
a good idea potentially. One concern. What should move to that package ? Just pages ? Or pages and components ? E.g. html_from, toolbar, chunks. These are not utilities. So the border is not very clear. I'd probably widen that new package to all html generating stuff and call it differently. `components` or `views` or ...
And also would merge it with `ui_db` - it feels lonely there :)

**Comment by mbtools** [comment]
I would combine classes that you might have to touch in case you want to create a new page and that are abapgit specific. so chunks and ui_db yes, html_form/toolbar no.

Or see it from someone's pov who wants to use the UI framework in their own project but doesn't want any of the abapGit specifics. Those parts should be in a separate package (core).

**Comment by sbcgua** [comment]
makes sense. I think it may take a couple of steps to identify the right classes, but why not :)

> who wants to use the UI framework in their own project but doesn't want any of the abapGit specifics

This is exactly the `ui_core`. It was the intention behind this separation. I was even planning a project based on that - abap_deployer, but then decided that such a functionality should be a part of abapgit (some day ... just give me a couple of work-free months :)))) The idea was also to teach abapmerge to be able to merge a project like this (I mean any project) into a single file and to be installable like abapgit. Well ... now I personally think webabapgit and alike is a better alternative then `ui_core`. 🤷‍♂️ 

html_form/toolbar is by the way not the core ! although they are not abapgit specific. But they represent specific visual components and are not abstract enough.

**Comment by mbtools** [comment]
Here's what's "core" in my system ;-)... I renamed a few classes (like chunk > lib) for clarity, too. new event logic is still missing. all I can say is that the apps I'm able to build with this look and feel awesome. 

![image](https://user-images.githubusercontent.com/59966492/95396639-56a77680-08cf-11eb-9a36-f54b293762cc.png)

**Comment by mbtools** [comment]
Closed by https://github.com/abapGit/abapGit/pull/5945
