### ISSUE TITLE
Serializing only a single folder

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#3998]
If you have the show folders view option enabled, could refresh/stage (including serialization) only work in the context of that folder? This would solve serialization speed for big package hierarchies assuming you only need to work in a single subpackage.

Also, multiple people working in different packages wouldn't see each other's diffs.

The default folder for each package could even be a user setting so you could do this from the repo overview as well.

**Comment by mbtools** [comment]
Sounds good. But difficult to realize. You don't want to get into a situation where only part of a repo is serialized and then a process assumes all files are up-to-date, for example (currently `zcl_abapgit_repo->status` is all or nothing).

**Comment by FreHu** [comment]
Yes, this would have to be filtered for the package/folder. On the local side it's easy enough, for remote some kind of sparse checkout would be required.

**Comment by flaiker** [comment]
:+1:
Similarly serializing only objects locked in any / a selected transport would be nice to have for the same reasons.

**Comment by mbtools** [comment]
Closing in favor of https://github.com/abapGit/abapGit/issues/5137 (optimize serializing objects)
