### ISSUE TITLE
HTTP error 421 occured: SSL handshake with gitlab.com:443 failed: SSSLERR_PEER_CERT_UNTRUSTED (-102)

### ISSUE THREAD

**Issue by click4ramesh** [abapGit/abapGit#4004]
This is the CAL version on Azure VM - SAP NetWeaver AS ABAP 7.51 SP02 on ASE.

When trying to access any repo from abapGit it says " HTTP error 421 occured: SSL handshake with gitlab.com:443 failed: SSSLERR_PEER_CERT_UNTRUSTED (-102) The peer's X.509 Certificate (chain) is"

I have downloaded and imported the certificates from github.com, api.github.com & other 2 root certificates and have imported them in STRUST and have maintained the below profile parameters in RZ10 and have restarted the SAP instance.

ssl/client_ciphersuites = 150:PFS:HIGH::EC_P256:EC_HIGH
ssl/ciphersuites = 135:PFS:HIGH::EC_P256:EC_HIGH
icm/HTTPS/client_sni_enabled = TRUE

ZABAPGIT_TEST_SSL returns 'Ok' from github and api.github.com.

I'm not much of a basis guy, not sure where to continue troubleshooting, please help.

**Comment by mbtools** [comment]
Your repos is on git*lab*.com. You have to import all certificates for gitlab.com to STRUST.

**Comment by click4ramesh** [comment]
Thank you, importing GitLab certificate resolved it.

**Comment by Enzo1975** [comment]
Hello mate. I have the some error on SAP Hana. I have follow the procedure. I attach screenshot.

RZ10
![image](https://user-images.githubusercontent.com/32358379/134161018-09791075-de73-4af2-b2f3-81b45049c132.png)

STRUST
![image](https://user-images.githubusercontent.com/32358379/134160913-9a83ba6f-085d-45f3-ad76-02d427d8cc72.png)

ZABAPGIT_TEST_SSL
![image](https://user-images.githubusercontent.com/32358379/134160787-e119d27c-8542-4f5a-88df-98f99fc81a7d.png)

SAP Hana Version
![image](https://user-images.githubusercontent.com/32358379/134161306-056b3b16-bf76-41c3-80af-eed3aca4c7d8.png)

**Comment by Enzo1975** [comment]
![image](https://user-images.githubusercontent.com/32358379/134165678-df467e2b-0c8d-46f4-917e-9e238cd7d91a.png)
