### ISSUE TITLE
shortdump in ZIF_ABAPGITP_XML_OUTPUT~ADD

### ISSUE THREAD

**Issue by filak-sap** [abapGit/abapGit#4021]
We had CX_SY_DYN_CALL_ILLEGAL_METHOD in ZIF_ABAPGITP_XML_OUTPUT~ADD which contains:
```
  It was tried to call the method "ADD" of the class "ZCL_ABAPGIT_XML_OUTPUT".
  However, in the class "ZCL_ABAPGIT_XML_OUTPUT", the method "ADD" could not be found.
```

I opened the class ZCL_ABAPGIT_XML_OUTPUT and I saw that the method add is there but only explicitly available via the interface zif_abapgit_xml_output.
I added "ALIASES: add for zif_abapgit_xml_output~add" to the public class section and the dump is gone.
However, I am not sure if it's really necessary. I am particularly confused because I can see that the wrapper calls more zif_abapgit_xml_output methods which are not causing short dumps.

Any thoughts?

**Comment by larshp** [comment]
which line number triggered the short dump? I guess it was from outside the ADD method?

The ALIASes for the XML classes was removed some weeks ago, I don't think there's any usages of the ALIASes left. But try deleting the class ZCL_ABAPGIT_XML_OUTPUT and importing it again?

![image](https://user-images.githubusercontent.com/5888506/95966667-b2ac5680-0e0b-11eb-9ae9-b55e04a3e624.png)

**Comment by mariusraht2** [comment]
I just had to copy it from GitHub into my NPL and that resolved the issue in my case.

**Comment by filak-sap** [comment]
Ooops, my bad, copy'n'pate error - I thought I already added the source code line which caused the problem.
It's in the class zcl_abapgitp_xml_factory from abapgit-plugins (I have learned about the origin just know, I thought it's from the abapgit directly).

Here: https://github.com/abapGit/abapGit-Plugins/blob/master/src/zcl_abapgitp_xml_factory.clas.locals_imp.abap#L20

**Comment by larshp** [comment]
yea, thats a problem

`CALL METHOD mo_wrapped_xml->('ADD')`

should be replaced with

`CALL METHOD mo_wrapped_xml->('ZIF_ABAPGITP_OUTPUT~ADD')`

or alternatively changed to user the interface instead of the class reference

**Comment by filak-sap** [comment]
How to convert lo_warpper to zif_abapgitp_xml_output without CAST which is not supported in older ABAP releases?

```abap
    DATA lo_wrapped_xml TYPE REF TO object.

    CREATE OBJECT lo_wrapped_xml TYPE zcl_abapgit_xml_output
      EXPORTING
        iv_xml = iv_xml.
```

**Comment by larshp** [comment]
hmm, I dont remember why the XML object is wrapped that way, might be easier just to remove the wrapper

or even easier, do `mo_wrapped_xml->('ZIF_ABAPGITP_OUTPUT~ADD')`

**Comment by flaiker** [comment]
@filak-sap The old way of doing `CAST #(` is an assignment using `?=` if that was your question.

**Comment by mbtools** [comment]
Just curious: What object type is still requiring the plug-in? Why not add it to the core?
