### ISSUE TITLE
abapGit asks for authentication to perform a check

### ISSUE THREAD

**Issue by GiantCrocodile** [abapGit/abapGit#4027]
Hello,

when you are on the repository overview page (main page) and click on action 'Check', abapGit asks you for your authentication data for your Git repository/server. You can type in any information and it will still do the ATC check. Afterwards you can press the 'Stage' button and it will ask you for your credentials again. Providing wrong or no information by cancelling the dialog does crash abapGit with an error regarding that dynpro `ZABAPGIT 1001` wasn't called via `CALL SELECTION-SCREEN`.

My suggestion:

1. Remove the authentication check before the ATC check as it's not needed for that task and
2. Make sure that abapGit won't crash in both cases.

Happens with abapGit v1.100.0.

Best Regards,

**Comment by mariusraht2** [comment]
Currently it needs the credentials to determine the commit hash from the remote repo:
![image](https://user-images.githubusercontent.com/45243391/96118957-8ddbe000-0eec-11eb-9511-cd76f6712ea5.png)

**Comment by mariusraht2** [comment]
It should already only be requested if it is an online repo and the credentials haven't been cached yet. Hmm..the issue happens with a private online repo, right?

But nonetheless we have an issue here with the handling of cancel in ZABAPGIT_PASSWORD_DIALOG. It not only happens if one cancels the login dialog explained in this issue but also after clicking on cancel if one clicks on a private online repo in AG.

**Comment by mariusraht2** [comment]
Ah, I see now what you mean: If you just don't enter the credentials and confirm the popup the Code Inspector page opens up nonetheless. But if you cancel AG crashes. The Latter should be resolved with my changes already - at the moment it would just don't show the Code Inspector page but instead the repo list. Will change the behaviour of the cancel button to open up the Code Inspector page on cancel too.

**Comment by mbtools** [comment]
I had looked at this before. May I suggest that we do **not** show the hash on every screen? Show it on the repo view but not on other pages. This would avoid the login and related problems,

**Comment by mariusraht2** [comment]
Plus we should really change the password dialog-related logic from report- to class-based..

**Comment by mbtools** [comment]
class-based and html, please, so it will work with web-version

**Comment by larshp** [comment]
issue https://github.com/abapGit/abapGit/issues/783 for the password dialog, its not an easy task

for the code inspector page, I think its okay to always omit the sha1
