### ISSUE TITLE
Deletion of local objects should enable the staging button

### ISSUE THREAD

**Issue by mariusraht2** [abapGit/abapGit#4030]
If one deletes an object (e.g. a report) within a package, AG shows the option to pull from remote after refreshing. In this case it should show "Stage" to be able to push the changes (deleted object) to the remote repo without the need to use "Force Stage".

**Reproduction:**
1. Create a test report > Refresh AG > Stage the new object
2. Delete test report in system > Refresh AG

**Comment by abal-illumiti** [comment]
I have the same issue with object deletions. 

1. commit objects to newly created repo from a package.
2. Delete a report. 
3. Object deletion is not recognized.
