### ISSUE TITLE
Activation error on 702 "Unexpected word "EXPORTING" in functional method call" 		

### ISSUE THREAD

**Issue by jeovax** [abapGit/abapGit#4032]
I found this activation error on abap 702.
"Unexpected word "EXPORTING" in functional method call".

The error occur in zcl_abapgit_object_pdts->get_container_xml method line 91.

The code was added in this pull request
https://github.com/abapGit/abapGit/pull/3711

![image](https://user-images.githubusercontent.com/52725130/96201825-f7cba800-0f33-11eb-9c59-ddb37f018c62.png)

**Comment by larshp** [comment]
@jeovax thanks for the bug report

I'll provide a PR for this

**Comment by larshp** [comment]
long term fix is https://github.com/abaplint/abaplint/issues/1399 to avoid this kind of errors

**Comment by larshp** [comment]
@jeovax try again, latest version

**Comment by larshp** [comment]
@jeovax assuming this part worked as you opened https://github.com/abapGit/abapGit/issues/4032

closing
