### ISSUE TITLE
Abap 702, Method "TO_LOWER" is unknown or PROTECTED or PRIVATE.

### ISSUE THREAD

**Issue by jeovax** [abapGit/abapGit#4036]
Activation error "Method "TO_LOWER" is unknown or PROTECTED or PRIVATE." at line 48.835 in the report.

The issue occur in ZCL_ABAPGIT_PERSISTENCE_USER->read_repo_config method.

Thanks and Regards

![image](https://user-images.githubusercontent.com/52725130/96262097-b836a780-0f97-11eb-8754-3348466e0a08.png)

_Originally posted by @larshp in https://github.com/abapGit/abapGit/issue_comments/709844073_

**Comment by larshp** [comment]
thanks, reading the ABAP help, it looks like `to_lower` works in 702, can you try it out in a simple report?

it might be that method calls are not allowed in this position, and that the error message is misleading

**Comment by mbtools** [comment]
Change to
```abap
  METHOD read_repo_config.
    DATA lv_url TYPE string.
    lv_url = to_lower( iv_url ).
    READ TABLE ms_user-repo_config INTO rs_repo_config WITH KEY url = lv_url.
  ENDMETHOD.
```

I will create a PR

**Comment by jeovax** [comment]
Thanks the new version is working
