### ISSUE TITLE
Terminology - Because it's the right thing to do...

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4043]
Replacing racially insensitive language in abapGit

Current | Suggested Change
-------- | ------------
User Master Record | User Record
Master Language | Main Language
Master Branch | Main Branch

Priority:
1. UI texts & documentation
2. Object and variable names in coding

References:
https://help.sap.com/doc/b0322267728e48a28b0c8ee7dd1ab4c7/1.0/en-US/Inclusive%20Language%20Guidelines.pdf
https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

To-do:
- [x] User Master Record > User Record
- [x] Master Language > Main Language (UI, comments, docs)
- [x] Master Language > Main Language (variables/parameters)
- [x] Master Branch > Main Branch (UI, comments, docs)
- [x] Master Branch > Main Branch (variables/parameters)
- [x] Docs (screenshots)

PS: I found no references to "slave", "black", or "white".

**Comment by larshp** [comment]
Note, according to link below, github will provide a feature for seamless rename of default branch,
https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-
so for abapGit itself, suggest awaiting this feature before renaming `master` to `main`

**Comment by mbtools** [comment]
#4158, #4159

**Comment by larshp** [comment]
renaming branches, https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/, I'll probably test it on a few other repos before abapGit

**Comment by mbtools** [comment]
Agree, let a few others covert their repo branches first

**Comment by larshp** [comment]
I've renamed the default branch for most abapGit organization repos,

todo, need to coordinate,
https://github.com/abapGit/eclipse.abapgit.org
https://github.com/abapGit/ADT_Frontend

**Comment by larshp** [comment]
default branches in organization https://github.com/abapGit-tests renamed for all repos
