### ISSUE TITLE
Dump, ITAB_DUPLICATE_KEY

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4044]
![image](https://user-images.githubusercontent.com/5888506/96415046-43a97600-11ee-11eb-9f74-c95cda64acf2.png)

**Comment by g-back** [comment]
Duplicates:

CHAR
CLNT
CUKY
CURR
DATS
DEC
INT1
INT2
INT4
INT8
LANG
NUMC
QUAN
SSTRING

**Comment by larshp** [comment]
@g-back thanks, will you be opening a PR adding the code back in(without duplicates)?

**Comment by g-back** [comment]
Guess I am!
