### ISSUE TITLE
CLAS and INTF XML file format

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4048]
`<CLSNAME>` is repeated, it can be removed from the XML descriptions, keep the first CLSNAME? And inserted again at deserialize.
Note that this can be done backwards compatible

![image](https://user-images.githubusercontent.com/5888506/96443948-b249fc00-120d-11eb-8e5f-aedefeb21809.png)

**Comment by FreHu** [comment]
I'd remove whatever redundancies can be removed

**Comment by FreHu** [comment]
Then this becomes obsolete: https://github.com/abaplint/abaplint/blob/master/packages/core/src/rules/xml_consistency.ts

**Comment by larshp** [comment]
yea

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/issues/2207#issue-390283413

**Comment by mbtools** [comment]
Closed by #5755
