### ISSUE TITLE
Not able to link ABAP package to Git. Dump error during serialization. 

### ISSUE THREAD

**Issue by suryakiran987** [abapGit/abapGit#4049]
This error occurs when Serializing large packages.

Error Details ASSERTION_FAILED
Program Name ZABAPGIT_FULL
Method Name CALCULATE_STATUS
Line Number in Program 21804-05
Assert statement line number 21816

**Comment by larshp** [comment]
thanks,

can you help pasting a screenshot of the dump?

how does the git repository look? any files?

are you using sap gui for windows?

**Comment by suryakiran987** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/9563028/96712973-8cfbf000-13bd-11eb-92fa-9d83ae2c3302.png)
![Screenshot (2)](https://user-images.githubusercontent.com/9563028/96712982-8ff6e080-13bd-11eb-810f-a85bb2271051.png)
![Screenshot (1)](https://user-images.githubusercontent.com/9563028/96712988-91c0a400-13bd-11eb-9458-e70e554c4dd5.png)
![Screenshot](https://user-images.githubusercontent.com/9563028/96712996-9422fe00-13bd-11eb-9fc0-9773c28c222b.png)

Git repo does not have any files. We are using Azure Repos.
Yes, we are using SAP GUI for Windows.

**Comment by larshp** [comment]
Try setting a breakpoint and checking the filenames, 

![image](https://user-images.githubusercontent.com/5888506/96714090-f241e800-13a1-11eb-8ac7-b190965e2c38.png)

Also is it possible to reproduce in a public repository? And does it happen only on Azure, ie. does it work on github?

**Comment by mbtools** [comment]
You are running an old version of abapGit. In the current version, the assert statement is on line 23200. Your old version has it on 21816.

Please update to the current version: https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap

**Comment by mbtools** [comment]
Sorry, didn't mean to close. Let us know how it works with current build.

**Comment by larshp** [comment]
@suryakiran987 did updating to latest version help?

**Comment by larshp** [comment]
closing, no reply
