### ISSUE TITLE
Set validity of default transport request

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4050]
AG uses a default transport request to record changes. However, it does not set any validity date when defining such transport. In case, the AG process fails, the default transport will not get reset and remain indefinitely. 

Suggestion: Set validity to 1 day 
(`ZCL_ABAPGIT_DEFAULT_TRANSPORT->SET_INTERNAL`)

**Comment by larshp** [comment]
oh, cool, good idea
