### ISSUE TITLE
Password Dialog doesn't accept password containing "ß"

### ISSUE THREAD

**Issue by MyongYin** [abapGit/abapGit#4055]
The password dialog that is used to connect ABAPgit to an external Git server has problems when the password contains an "ß" character. When you type in this character, two * characters are visible in the input field and and the cursor position is weird. This happens on a Unicode system (NW 7.5).

**Comment by larshp** [comment]
Thanks for the bug report

Suggest as a temporary workaround changing the password to contain only 7bit ascii symbols

Note that the password dialog is currently being refactored, https://github.com/abapGit/abapGit/pull/4052, so don't spend too much time looking into the popup

**Comment by flaiker** [comment]
@mbtools What wrong behavior should your report be able to reproduce? For me it works just fine (correct number of masked characters in input field and correct list output). I also tried different logon languages (EN and DE).

I recall there being some issues with password fields and their masking in a previous SAP GUI version. I tested on 760 Patch Level 8.

**Comment by larshp** [comment]
I'm on the below version, and I can reproduce the issue, so sounds like its a GUI bug, @MyongYin try updating to latest SAP GUI version?

![image](https://user-images.githubusercontent.com/5888506/97405251-a9d17f80-18f7-11eb-95c0-a7a91e3a3adb.png)

**Comment by flaiker** [comment]
See note 2837035 - Truncation of a password field's value while inputting international characters for example German umlauts

**Comment by mbtools** [comment]
GUI 760 Sp8. Unicode 750 sp18 backend. Issue still exists.

**Comment by flaiker** [comment]
Can you post a screenshot? I am not sure what exactly I am looking for trying to reproduce the error.

**Comment by mbtools** [comment]
I’m not at a system right now. It’s quite simple: when you type a German ß in the password field, it shows two stars with the cursor in the middle of both.

**Comment by larshp** [comment]
after inserting the "ß", cannot move the cursor past the second "*"

![image](https://user-images.githubusercontent.com/5888506/97428168-e318e800-1915-11eb-8fa8-26e20d9b9aa1.png)

**Comment by flaiker** [comment]
Ah nevermind me. I also have the issue. 2837035 seems to have only fixed this for the password field in the normal system logon and not for screen-invisible ? Note in the session logon screen there is a complete field mask while screen-invisible only masks entered characters. Not sure how that is implemented (SAPMSYST-0020).

**Comment by flaiker** [comment]
Ok, it only affects string fields. Changing p_pass from string to char20 resulted in the whole field being masked like on the logon screen and the ß issue also disappeared. String fields always behave weird in dynpros so I guess this was missed by the note.

**Comment by mariusraht2** [comment]
oauth tokens can't contain german umlauts such as ßäöü etc. Only some special characters (e.g. +-=) are allowed to be used additionally to numbers and a-z or A-Z. We removed the compability with 2FA tokens. Plus we currently refactor the password dialog. Thus I think we shouldn't implement a workaround for the existing password dialog.

**Comment by mariusraht2** [comment]
According to RFC 6750 a bearer token (which is the token to execute the server authentication in OAuth) can't contain german umlauts (see discussion on Stackoverflow https://stackoverflow.com/questions/50031993/what-characters-are-allowed-in-an-oauth2-access-token) such as 'ß'. Only number, a-z and A-Z characters are allowed and some special characters (-._~+/). Additionally we removed support for 2FA and are currently refactoring the password dialog.

**Comment by MyongYin** [comment]
> According to RFC 6750 a bearer token (which is the token to execute the server authentication in OAuth) can't contain german umlauts (see discussion on Stackoverflow https://stackoverflow.com/questions/50031993/what-characters-are-allowed-in-an-oauth2-access-token) such as 'ß'. Only number, a-z and A-Z characters are allowed and some special characters (-._~+/). Additionally we removed support for 2FA and are currently refactoring the password dialog.

I don't see the connection my issue. I have a password which is stored in an LDAP server. I use to login to Bitbucket.  I don't type in Bearer token to login to Bitbucket.

**Comment by mariusraht2** [comment]
Ok, thanks for the clarification 👍

**Comment by MyongYin** [comment]
> 2035293

I can't reproduce this Behaviour in 
![image](https://user-images.githubusercontent.com/73307916/97713512-3a5abc00-1ac0-11eb-9003-982660b5c67c.png)

**Comment by MyongYin** [comment]
> See note 2837035 - Truncation of a password field's value while inputting international characters for example German umlauts

The note is included in my SAPgui version:

MAIN MODULE INFORMATION:
   sapfront.dll
   SAP-Frontend für Windows
   760 Final Release
   7600.1.6.3392
   1998402

The problem still exists :(

**Comment by flaiker** [comment]
@MyongYin Can you check if the change in #4135 fixes your issue?
