### ISSUE TITLE
Stage button during ATC check visible although nothing to stage

### ISSUE THREAD

**Issue by GiantCrocodile** [abapGit/abapGit#4057]
Hello,

steps to reproduce:

1. Do 'Check' action on an already staged Git repository
2. Press 'Stage' button
3. Error: ` There are no changes that could be staged ` (Message 00/001)

Solution:
The button shouldn't be disabled or it should take you to the diff/object overview where you see that there's nothing to stage. So either fix the button or implement a proper process to take the user to a page with proper information without an error message as it's nothing the user can do about at this step.

abapGit v1.100.0

Best Regards,

**Comment by mbtools** [comment]
Selecting "Stage" first serializes everything before staging. You won't know if there will be changes until after the serializing is done. 

I think this behavior makes sense since you might change objects based on the code inspector findings.
