### ISSUE TITLE
Enhance user information

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4059]
In various places, the user id is displayed in abapGit. However, user ids can be quite cryptic. It would be nice to get further details like user first/last name and email.

Suggestion:

Add new `add_user` method to `zcl/zif_abapgit_html` which generates the following HTML. An option could be to add an icon as a prefix. 
```html
<a href="sapevent:show_user" title="{ first & last name}, { email }">{ user id }</a>
```

On hover, you would see some details. On click, it would jump to `su01d` to display all user details. In addition, I could imagine an exit to replace the link/action. This could be used to launch your favorite chat client or create an email to the user (i.e. generate a mailto link).

**Comment by sbcgua** [comment]
Good idea. 
P.S. `gui_chunk_lib` would be a better place.
