### ISSUE TITLE
TABL: Dump while uninstalling GTT

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#4074]
Demo repo
https://gitlab.com/christianguenter/test_gtt

GTT requires strict SQL syntax
https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenddic_database_tables_gtt.htm

![image](https://user-images.githubusercontent.com/17437789/97318550-46e6d680-186c-11eb-8087-87eedafb0307.png)
![image](https://user-images.githubusercontent.com/17437789/97318576-4e0de480-186c-11eb-8b8d-f081d9781d59.png)
![image](https://user-images.githubusercontent.com/17437789/97318615-57974c80-186c-11eb-9f9b-a608a781a8dd.png)

**Comment by larshp** [comment]
suggest that if `IS_GTT` is set, then skip the test/SELECT, as its probably okay to delete a temporary table without asking

**Comment by mbtools** [comment]
Also, function DB_COUNT_DATA might be nice replacement for SQL logic to check if data is present.

**Comment by christianguenter2** [comment]
yeah, `IS_GTT` is available since 750. Or we could catch the exception and set `lv_no_ask = abap_true` as quick fix.

**Comment by larshp** [comment]
I think catching the exception would be okay, just add a comment regarding GTT, so its possible to remember the scenario

Also suggest adding the scenario to https://github.com/abapGit-tests

**Comment by christianguenter2** [comment]
`DB_COUNT_DATA` is a bit weird on my NW 752 SP04 dev system. I cannot open it and it looks inactive in object list. And a strange message appears.
![image](https://user-images.githubusercontent.com/17437789/97322369-02f5d080-1870-11eb-8fd4-f94cb9822f6c.png)
