### ISSUE TITLE
TABL: Deserializing GTT - popup makes no sense

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#4081]
demo repo
https://github.com/abapGit-tests/TABL_GTT.git

This message while creating a GTT makes no sense, as the GTT doesn't exist. 
It only appears when then GTT already existed earlier in the system.
![image](https://user-images.githubusercontent.com/17437789/97324204-dcd13000-1871-11eb-8462-630094760fcc.png)

Seems that the nametab used for existence check still contains the GTT.
![image](https://user-images.githubusercontent.com/17437789/97325858-b3190880-1873-11eb-8b59-01da09e8a22c.png)

**Comment by christianguenter2** [comment]
Maybe we should call `DD_NAMETAB_DELETE` after deleting TABL objects?

**Comment by larshp** [comment]
that sounds dangerous 🚨 

after the existence check it should hit https://github.com/abapGit/abapGit/blob/c05af1163f9ff035cdc70caf33df94965c7a6a38/src/objects/zcl_abapgit_object_tabl.clas.abap#L784 ? and in there I think its possible to do the same as https://github.com/abapGit/abapGit/pull/4075#issuecomment-717385249

**Comment by christianguenter2** [comment]
Don't know if it's that dangerous.

Yeah, we could do probably the same, but I think it would be much more cleaner if existence check returns the right result. I guess this is source for other bugs too.

**Comment by larshp** [comment]
hmm, yea

**Comment by mbtools** [comment]
Since we rely on nametab, I think calling DD_NAMETAB_DELETE is the way to go (after successful DDIC deletion). Might need the same for DTEL actually.

**Comment by mbtools** [comment]
I tried to reproduce but the following works without issues (1.101.0):
- New repo https://github.com/abapGit-tests/TABL_GTT.git
- Pull 
- Uninstall
- Pull
- Uninstall

After uninstall, calling `DD_GET_NAMETAB_HEADER` returns `NOT_FOUND`.

Am I missing some step?
