### ISSUE TITLE
Split GET_*COMMIT_DISPLAY_URL logic to separate class

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4085]
its currently in class ZCL_ABAPGIT_REPO_ONLINE, but only uses public methods

related to https://github.com/abapGit/abapGit/issues/2127

**Comment by mbtools** [comment]
I think you meant `GET_COMMIT_DISPLAY_URL`.

I suggest consolidating all logic dependent on git provider. These classes look like the start of it although they probably should be renamed:

`ZCL_ABAPGIT_PR_ENUMERATOR / ZCL_ABAPGIT_PR_ENUM_GITHUB`

**Comment by larshp** [comment]
yea, sorry method GET_COMMIT_DISPLAY_URL and method GET_DEFAULT_COMMIT_DISPLAY_URL

**Comment by larshp** [comment]
yea, I think ZCL_ABAPGIT_PR_ENUMERATOR and ZCL_ABAPGIT_PR_ENUM_GITHUB should be moved to a new package along with the GET_COMMIT_DISPLAY_URL logic

**Comment by sbcgua** [comment]
what about $ABAPGIT_PROVIDER_API ? (package, I mean)

**Comment by mbtools** [comment]
No APIs anywhere else in AG. Just $abapgit_providers?

**Comment by sbcgua** [comment]
provider is not clear enough. provider of what ? The idea is that there is some *platform specific* logic. abapgit_platforms should also do by the way

**Comment by mbtools** [comment]
+1 for abapgit_git_platform

**Comment by larshp** [comment]
`$abapgit_git_platform` sounds good to me

**Comment by larshp** [comment]
I'm starting this now

**Comment by larshp** [comment]
todo: ZCL_ABAPGIT_PR_ENUMERATOR and ZCL_ABAPGIT_PR_ENUM_GITHUB
