### ISSUE TITLE
Installation error: DBSQL_TABLE_UNKNOWN

### ISSUE THREAD

**Issue by HuprichTo** [abapGit/abapGit#4088]
Hello Guys, 

today i tried to reinstall abapGit on our Test System (apparently a previous Version was deleted some time ago). 
So what should I say to recreate the issue , i created new new Programm ZABAPGIT_FULL, inserted the source code and when I try to execute the programm it fails with above named error. 

Would love to hear from you how I can solve this issue. 

SIncerely
![2020-10-28 12_07_37-Laufzeitfehler - Beschreibung der Ausnahme](https://user-images.githubusercontent.com/73161936/97428416-3d19ad80-1916-11eb-8bfe-9570ea38df8f.png)

**Comment by christianguenter2** [comment]
Can you check table ZABAPGIT in SE11? Does it exist? Is it active?

**Comment by HuprichTo** [comment]
Yeah thx for the fast reply, 

after se11 i could detect that it is defined, but wasn't created yet. So I changed to se14 and created the dbtab. 

**Result**: Works now, Issue can be closed, thanks for the Help
