### ISSUE TITLE
Remote is not refreshed at refresh

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4090]
Only when restarting abapGit

![image](https://user-images.githubusercontent.com/5888506/97437432-be2b7180-1923-11eb-8c7e-a556222ab46a.png)

but remote is at

![image](https://user-images.githubusercontent.com/5888506/97437460-c7b4d980-1923-11eb-8f30-cd15f2d116f8.png)

@mariusraht2

**Comment by mariusraht2** [comment]
Ok, refresh should then reset the current commit and redetermine the branch hash.

**Comment by larshp** [comment]
fixed for branches and tags in https://github.com/abapGit/abapGit/pull/4091

**Comment by mariusraht2** [comment]
Fixed? 
![image](https://user-images.githubusercontent.com/45243391/97440649-051b6600-1928-11eb-91f9-0e879f233f8f.png)

**Comment by mariusraht2** [comment]
Ok, we are just reducing the remote calls by saving the selected commit hash locally instead of always getting it from remote again.

**Comment by mariusraht2** [comment]
Plus obviously this isn't compatible with #3040: The user selects a commit hash and then nothing happens because we don't return the selected commit in REPO_ONLINE..

**Comment by larshp** [comment]
the remote is now refreshed when clicking refresh, it was not before, there is no functionality to select a commit, so the commented code in get_selected_commit does not break any existing functionality

closing

**Comment by mariusraht2** [comment]
Ok, now I got it :)

**Comment by larshp** [comment]
but feel free to use issue #3040 to describe the direction and design of the changes, or ask questions related to that change
