### ISSUE TITLE
UI: Icons for online repo, user id, and transport

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4098]
I'm not sure why our cloud icon has an arrow in it? Why not just
![image](https://user-images.githubusercontent.com/59966492/97500851-b4673580-1946-11eb-9a11-9160b81585b4.png)

Add icons for user id:
![image](https://user-images.githubusercontent.com/59966492/97500902-cb0d8c80-1946-11eb-8eb0-96c08e85ee03.png)

Change icon for transport from:
![image](https://user-images.githubusercontent.com/59966492/97500920-d365c780-1946-11eb-9d71-53dbe4c95487.png)
to
![image](https://user-images.githubusercontent.com/59966492/97500956-dc569900-1946-11eb-9aa6-9b435fc43385.png)

https://fontawesome.com/icons/cloud?style=solid
https://fontawesome.com/icons/user?style=solid
https://fontawesome.com/icons/truck?style=solid

**Comment by flaiker** [comment]
The transport icon used to be the one you want to change it to and was changed after some discussion because it was apparently more intuitive to some people than the truck.

**Comment by flaiker** [comment]
#2153 , remembered it wrong, there was no truck before ?

**Comment by mbtools** [comment]
Understood. I will try to get SAP to change the truck ;-)

**Comment by mbtools** [comment]
Fontawesome has grown significantly. There are several different trucks available now.
