### ISSUE TITLE
Pull new abapGit Version leads to dump 

### ISSUE THREAD

**Issue by HuprichTo** [abapGit/abapGit#4100]
Hello again guys, 

right now I'm trying to pull the latest Version of abapGit into my SAP System for test purposes. The current Version is 1.100, i downloaded the latest zabapgit_standalone an hour before manually. 
So i go into the abapgit repos, select pull (Over advanced Reset Local leads to the same error), after that it downloads and a message shows up that "abapgit was updated and will restart itself", **and then: dump**

So after this pull abapgit is broken and I have to reset the zabapgit code manually from the web. 

Would be nice if someone could help me. 

With best wishes 

![abapgit_repos_overview](https://user-images.githubusercontent.com/73161936/97543437-83c7e000-19c8-11eb-8f81-191f73ad825c.png)
![abapgit_repos_pull](https://user-images.githubusercontent.com/73161936/97543449-888c9400-19c8-11eb-92ab-99e5257a697d.png)
![2020_10_29_09_09_26_Runtime_Error_Description_of_Exception](https://user-images.githubusercontent.com/73161936/97543455-8c201b00-19c8-11eb-9b38-58c375195962.png)

**Comment by larshp** [comment]
thanks, see https://docs.abapgit.org/guide-upgrade.html#troubleshooting

**Comment by HuprichTo** [comment]
Okay thank you lars for the hint to the documentation, it **works now.** I deleted all diffs via se24 and restarted abapgit_standalone. After that I executed the Force Pull and now the Version is up to date. 

Thanks again and best wishes
