### ISSUE TITLE
TABL Pull with Foreign-Key fails

### ISSUE THREAD

**Issue by snapIBR** [abapGit/abapGit#4103]
We are using abapGit Version 1.100.0, issue reproduceable on SAP_BASIS 750 and 753.

When trying to pull from a repository (regardless wheter it's online or offline) that contains a table with foreign key definitions, activation of the table fails.
![grafik](https://user-images.githubusercontent.com/73654335/97591430-e8eaf800-19ff-11eb-8196-88e6b6a6776e.png)
(Structure ZABAPGIT_FK_3 does not exist)

Our table definition is as follows:
![grafik](https://user-images.githubusercontent.com/73654335/97591631-1a63c380-1a00-11eb-8635-ac852780e03b.png)
![grafik](https://user-images.githubusercontent.com/73654335/97591742-35363800-1a00-11eb-9721-ec5bf4bb20e6.png)

Serialized representation of the table:
`<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_TABL" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <DD02V>
    <TABNAME>ZABAPGIT_FK_3</TABNAME>
    <DDLANGUAGE>D</DDLANGUAGE>
    <TABCLASS>TRANSP</TABCLASS>
    <CLIDEP>X</CLIDEP>
    <DDTEXT>abapGit: Foreign Key Test mit Standardtab</DDTEXT>
    <CONTFLAG>C</CONTFLAG>
   </DD02V>
   <DD09L>
    <TABNAME>ZABAPGIT_FK_3</TABNAME>
    <AS4LOCAL>A</AS4LOCAL>
    <TABKAT>0</TABKAT>
    <TABART>APPL0</TABART>
    <BUFALLOW>N</BUFALLOW>
   </DD09L>
   <DD03P_TABLE>
    <DD03P>
     <TABNAME>ZABAPGIT_FK_3</TABNAME>
     <FIELDNAME>MANDT</FIELDNAME>
     <POSITION>0001</POSITION>
     <KEYFLAG>X</KEYFLAG>
     <ROLLNAME>MANDT</ROLLNAME>
     <ADMINFIELD>0</ADMINFIELD>
     <NOTNULL>X</NOTNULL>
     <COMPTYPE>E</COMPTYPE>
    </DD03P>
    <DD03P>
     <TABNAME>ZABAPGIT_FK_3</TABNAME>
     <FIELDNAME>MATNR</FIELDNAME>
     <POSITION>0002</POSITION>
     <KEYFLAG>X</KEYFLAG>
     <ROLLNAME>MATNR</ROLLNAME>
     <CHECKTABLE>MARA</CHECKTABLE>
     <ADMINFIELD>0</ADMINFIELD>
     <NOTNULL>X</NOTNULL>
     <SHLPORIGIN>P</SHLPORIGIN>
     <SHLPNAME>S_MAT1</SHLPNAME>
     <SHLPFIELD>MATNR</SHLPFIELD>
     <COMPTYPE>E</COMPTYPE>
    </DD03P>
    <DD03P>
     <TABNAME>ZABAPGIT_FK_3</TABNAME>
     <FIELDNAME>DESCRIPTION</FIELDNAME>
     <POSITION>0003</POSITION>
     <ROLLNAME>TEXT20</ROLLNAME>
     <ADMINFIELD>0</ADMINFIELD>
     <NOTNULL>X</NOTNULL>
     <COMPTYPE>E</COMPTYPE>
    </DD03P>
   </DD03P_TABLE>
   <DD05M_TABLE>
    <DD05M>
     <TABNAME>ZABAPGIT_FK_3</TABNAME>
     <FIELDNAME>MATNR</FIELDNAME>
     <FORTABLE>ZABAPGIT_FK_3</FORTABLE>
     <FORKEY>MANDT</FORKEY>
     <CHECKTABLE>MARA</CHECKTABLE>
     <CHECKFIELD>MANDT</CHECKFIELD>
     <PRIMPOS>0001</PRIMPOS>
     <DOMNAME>MANDT</DOMNAME>
     <DATATYPE>CLNT</DATATYPE>
     <LENG>000003</LENG>
    </DD05M>
    <DD05M>
     <TABNAME>ZABAPGIT_FK_3</TABNAME>
     <FIELDNAME>MATNR</FIELDNAME>
     <FORTABLE>ZABAPGIT_FK_3</FORTABLE>
     <FORKEY>MATNR</FORKEY>
     <CHECKTABLE>MARA</CHECKTABLE>
     <CHECKFIELD>MATNR</CHECKFIELD>
     <PRIMPOS>0002</PRIMPOS>
     <DOMNAME>MATNR</DOMNAME>
     <DATATYPE>CHAR</DATATYPE>
     <LENG>000018</LENG>
    </DD05M>
   </DD05M_TABLE>
   <DD08V_TABLE>
    <DD08V>
     <TABNAME>ZABAPGIT_FK_3</TABNAME>
     <FIELDNAME>MATNR</FIELDNAME>
     <DDLANGUAGE>D</DDLANGUAGE>
     <CHECKTABLE>MARA</CHECKTABLE>
     <DDTEXT>Foreignkey Material-ID</DDTEXT>
    </DD08V>
   </DD08V_TABLE>
  </asx:values>
 </asx:abap>
</abapGit>
`

**Comment by mbtools** [comment]
I tried to reproduce it but do not get any error. Here's my test repo: https://github.com/mbtools/TEST_TABLE_FK

Do you get the same error with my repo?

**Comment by flaiker** [comment]
Is it normal for the client field to show up in a foreign key definition?

**Comment by mbtools** [comment]
Yes. That’s the typical suggestion by the system.

**Comment by snapIBR** [comment]
Depending on our SAP_BASIS Version we get different error messages, but with the same cause.
753:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/73654335/97700135-9c5cf680-1aab-11eb-9e55-50d900adfa8d.png)
750:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/73654335/97700198-b565a780-1aab-11eb-8e31-5cc8dc628994.png)

The deserialization of the transparent table seems to happen in 3 subsequent phases:
1) DDIC
-> Here only the table is sucessfully deserialized, created and activated
2) ABAP
-> no objects for this phase
3) LATE
-> here the table incl. foreign key is deserialized

In the Late Phase (Method ZCL_ABAPGIT_OBJECTS=>DESERIALIZE_OBJECTS) the activation happens twice (once for ddic and once for non-ddic objects).

    CASE is_step-step_id.
      WHEN zif_abapgit_object=>gc_step_id-ddic.
        zcl_abapgit_objects_activation=>activate( is_step-is_ddic ).
      WHEN zif_abapgit_object=>gc_step_id-abap.
        zcl_abapgit_objects_activation=>activate( is_step-is_ddic ).
      WHEN zif_abapgit_object=>gc_step_id-late.
        " late can have both DDIC (like TABL with REF TO) and non-DDIC objects
        zcl_abapgit_objects_activation=>activate( abap_true ).
        zcl_abapgit_objects_activation=>activate( abap_false ).
    ENDCASE.

In the late phase the DDIC part of the activation works fine. After that the table is created and would work including foreign key.
However, the second call of the "activate" method causes issues when function module RS_WORKING_OBJECTS_ACTIVATE is called.
There the field DD02V_WA-TABCLASS is changed from value "TRANSP" to "INTTAB".

We had success creating the table when we skipped the second activate call during debugging. The table and its foreign keys were successfully created.

**Comment by mbtools** [comment]
Thx for the analysis. The object shouldn’t be in the second activation list. I will take a look.

**Comment by larshp** [comment]
can we add a test case to https://github.com/abapGit-tests ?

**Comment by mbtools** [comment]
We already have test case for foreign keys https://github.com/abapGit-tests/TABL_foreign_key. I fixed it based on the description above (double activation didn't make sense anyway) but wasn't able to reproduce it. 🤷‍♂️

**Comment by larshp** [comment]
ok
