### ISSUE TITLE
Endless pulling in case if subpackage already exists in the target system

### ISSUE THREAD

**Issue by ThePlenkov** [abapGit/abapGit#4108]
Hi!  

Here is a simple scenario:

1 - There is a package FOO_BAR which we wanted to move via git to a new system. All worked as expected. FOO_BAR was created in the target system - no new changes afterwards.

2 - we decided to go further and to move whole package FOO. So we created a new git project and tried to pull it via abapgit.
This led to situation when changes from package FOO_BAR were always shown as new. Pull/ force pull didn't help

what helped: during step 1 package FOO_BAR was created as a standalone without a parent. 

what could be improved: it would be nice if abapgit would suggest package reassignment also in case if packages already exist

**Comment by ThePlenkov** [comment]
i found workaround only after debugging this code:

`  METHOD zif_abapgit_sap_package~list_subpackages.

    DATA: lt_list     LIKE rt_list.

    SELECT devclass FROM tdevc
      INTO TABLE lt_list
      WHERE parentcl = mv_package
      ORDER BY PRIMARY KEY.               "#EC CI_SUBRC "#EC CI_GENBUFF

    rt_list = lt_list.
    WHILE lines( lt_list ) > 0.

      SELECT devclass FROM tdevc
        INTO TABLE lt_list
        FOR ALL ENTRIES IN lt_list
        WHERE parentcl = lt_list-table_line
        ORDER BY PRIMARY KEY.             "#EC CI_SUBRC "#EC CI_GENBUFF
      APPEND LINES OF lt_list TO rt_list.

    ENDWHILE.

  ENDMETHOD.`

we can see that program tries to find existing subpackages. if package FOO is already in the system and package FOO_BAR is also in the system, but not as a child of FOO, in this case this code won't find it - and pull won't be applied to its content unfortunately.

**Comment by larshp** [comment]
thanks 

@ThePlenkov can you help making a public repository which can be used to reproduce the issue? along with the steps needed

package reassignment: this would break a lot of things, most importantly transparency to the developer

**Comment by mbtools** [comment]
reproduce:

1. Pull https://github.com/abapGit-tests/DEVC_main_sub to `$FOO` (ignore diff of appl.comp)
2. `SE80`, change `$FOO_SUB` package and remove parent package (or delete `$FOO_SUB`)
3. Refresh repo in abapGit and try to force pull
4. Package `$FOO_SUB` will not be updated

**Comment by mbtools** [comment]
Instead of "endless pulling" or trying to automatically reassign the existing package, you now get an error message.  See #4331
