### ISSUE TITLE
messages lost after changing master language

### ISSUE THREAD

**Issue by tricktresor** [abapGit/abapGit#4134]
repo https://github.com/keremkoseoglu/addict was pushed to github with master language TR.
Import was not possible in my SAP system. Import also was not possible with "advanced - open in master language",
Because the turkish language is not installed in my system, 

So in consultation with Kerem I changed the repos master language from TR to EN in .abapgit.xml

I was able to import sources into my system. They were imported now with master language EN.

All sources are now different to the master repository because of the different language.
All turkish texts are now  stored with language EN.

No problem with most sources but one: In the Message class the texts are lost.

Original message class: https://github.com/keremkoseoglu/addict/blob/main/src/yaddict.msag.xml

```
<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_MSAG" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <T100A>
    <ARBGB>YADDICT</ARBGB>
    <MASTERLANG>T</MASTERLANG>
    <STEXT>ABAP Dictionary</STEXT>
   </T100A>
   <T100>
    <T100>
     <SPRSL>T</SPRSL>
     <ARBGB>YADDICT</ARBGB>
     <MSGNR>000</MSGNR>
     <TEXT>&amp;1 tablosunda &amp;2 anahtarı için kayıt yok</TEXT>
    </T100>
    ...
```
new master language: https://github.com/tricktresor/addict/blob/main/src/yaddict.msag.xml

```
<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_MSAG" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <T100A>
    <ARBGB>YADDICT</ARBGB>
    <MASTERLANG>E</MASTERLANG>
    <STEXT>ABAP Dictionary</STEXT>
   </T100A>
  </asx:values>
 </asx:abap>
</abapGit>
```

**Comment by flaiker** [comment]
Also see discussion in #3894

**Comment by mbtools** [comment]
Your second system is English only. Why don't you translate the messages from Turkish into English in your *first* system and push from there to Git? Then you should be able to pull all texts into your second system.

**Comment by tricktresor** [comment]
Because it's not _my_ repository... :)
yes of course this would be the best solution. 
However, the behaviour of the other repository objects is different to the message class. 
Messages should not get lost.

**Comment by mbtools** [comment]
You have a “Turkish” repo but your system doesn’t have that language installed. That’s scenario not covered by abapGit. 

Changing the main language (in abapgit.xml) or importing a different main language than what you are logged does not work and would need many adjustments (as discussed in other issues). So unfortunately no quick solution here

**Comment by larshp** [comment]
I'd say this works as expected, if the master language is English, and there are no English texts then they are not imported

**Comment by tricktresor** [comment]
I'd be with you if the behaviour of the other repository objects wasn't different. The short description for example will be stored in given master language. 
I understand the discussion mentioned above, that either way might be wrong:
1. store text in original text as new master language although the text has a different language
2. do not store text as the original language does not fit to master language

In my opinion the messages should be overtaken even if the original language does not fit to the master language just to have them. 
If the messages are gone, you have to compare with github source which messages are there which is much more effort than just _overwriting_ existing messages in SAP.

**Comment by larshp** [comment]
I think thats for the developer to decide, there is full transparency as to what happened after import. 

A default behavior taking LanguageA and putting into LanguageB would seem like a bug to me

**Comment by larshp** [comment]
but languages overall needs some cleanup, and all object types behaves differently(due to SAP standard)

starting with the right language, and keeping it is the easiest for the developer

**Comment by tricktresor** [comment]
Yes, I think this would be the best solution: Make sure that original language is EN and then do translations.
Thanks to all for your input!
