### ISSUE TITLE
SSL handshake with github.com:443 failed: SSSLRC_CONN_CLOSED

### ISSUE THREAD

**Issue by vkreddy59** [abapGit/abapGit#4142]
Hello All,

We are getting below error message when test ABAPGit connection test using report ZABAPGIT_TEST_SSL (using SE38 t-code).

We have installed the certificates from https://github.com & https://api.github.com by following the abapgit help documentation (ref.  https://docs.abapgit.org/guide-ssl-setup.html). 

Please help us to resolve this issue.

**_**ABAPGit - SSL Connection Check

Error Number     1

SSL handshake with github.com:443 failed: SSSLRC_CONN_CLOSED (-10)
Remote Peer has closed the network connection
SapSSLSessionStartNB()==SSSLRC_CONN_CLOSED
Also check transaction SMICM -> Goto -> Trace File -> Display End

Error Number     1

SSL handshake with api.github.com:443 failed: SSSLRC_CONN_CLOSED (-10)
Remote Peer has closed the network connection
SapSSLSessionStartNB()==SSSLRC_CONN_CLOSED
Also check transaction SMICM -> Goto -> Trace File -> Display End**_**

Logs from SMICM

_**_[Thr 140101169288960] *** ERROR => SecuSSL_SessionStartNB(): incomplete SSL handshake [ssslsecu.c   4955]
[Thr 140101169288960] *** ERROR => SSL handshake with api.github.com:443 failed: SSSLRC_CONN_CLOSED (-10)
[Thr 140101169288960] Remote Peer has closed the network connection
[Thr 140101169288960]
[Thr 140101169288960] SapSSLSessionStartNB()==SSSLRC_CONN_CLOSED
[Thr 140101169288960]
[Thr 140101169288960]  {0008924a} {root-id=42010AF0020B1EDB888C1679596F6F70} [icxxconn.c 2440]
[Thr 140101169288960]              GUI T19_U5435_M0, 200, VMENDU, NJ-RAW-069-136, time=22:02:00, W49, program=ZABAPGIT_TEST_SSL, high priority, memory=0, tasks=2, appl info=, tcode=SE38
[Thr 140101169288960]              role: Client, protocol: HTTPS, local: 10.240.2.11:47028, peer: 140.82.113.6:443_**_

_Regards,_
Vinay

**Comment by mbtools** [comment]
Did you check the system parameters?

Also, you need two certificates for Github.com and two for API.GitHub.com: one for root, one for intermediate CA.

**Comment by vkreddy59** [comment]
Hi Marc, 

Yes, system parameters looks good. I have installed certificates from girhub.com and api.github.com.

**Comment by larshp** [comment]
Hi,
a: did you follow SAP note 510007, section 7, for information on how to configure SSL
b: what SAP BASIS version are you running
c: is the system behind a proxy?

**Comment by vkreddy59** [comment]
Hi Lars,

a: did you follow SAP note 510007, section 7, for information on how to configure SSL --> Yes
b: what SAP BASIS version are you running --> 752 SP02
c: is the system behind a proxy? --> not sure, can you please guide me how to check this?

Regards,
Vinay

**Comment by larshp** [comment]
c: try asking your system admin

**Comment by mbtools** [comment]
Did you get it to work?

If not, try setting up a connection in SM59 first. Check on other connections like SAP-SUPPORT_NOTE_DOWNLOAD if there's a proxy maintained and copy that.

![image](https://user-images.githubusercontent.com/59966492/99265103-5021ee00-27ef-11eb-950b-9566cc34f368.png)

![image](https://user-images.githubusercontent.com/59966492/99265151-5adc8300-27ef-11eb-9591-fcbbc515aeea.png)

(instead of 'mbtools' use your github username and password, of course)

Connection test should result in status 200:

![image](https://user-images.githubusercontent.com/59966492/99265263-7fd0f600-27ef-11eb-97ad-ce060a35e8cb.png)

**Comment by larshp** [comment]
closing, no reply

**Comment by vkreddy59** [comment]
Hi Marc,

Issue is resolved yet. I have created type G RFC as you suggested, I am getting the following error when I do a connection test.

SSL handshake with github.com:443 failed:
SSSLRC_CONN_CLOSED (-10)#Remote Peer has closed
the network
connection##SapSSLSessionStartNB()==SSSLRC_CONN_CL
OSED##

![image](https://user-images.githubusercontent.com/74077000/99393343-3245ad80-2903-11eb-8c4b-7221cb29d670.png)

Note:- There is no path prefix maintained for RFC SAP-SUPPORT_NOTE_DOWNLOAD.


Regards,
Vinay

**Comment by vkreddy59** [comment]
> closing, no reply

Lars,

There was a delay in replying from my side but the issue is not yet resolved. Could you please help me to reopen the issue?

Regards,
Vinay

**Comment by vkreddy59** [comment]
> > closing, no reply
> 
> Lars,
> 
> There was a delay in replying from my side but the issue is not yet resolved. Could you please help me to reopen the issue?
> 
> Regards,
> Vinay

I can see it's open now, thanks for your help.

Regards,
Vinay

**Comment by mbtools** [comment]
Let’s see if basic connection to github works:

Change 443 to 80, login to “do not use user”, ssl to inactive. Check again

**Comment by vkreddy59** [comment]
Hi Mark,

I have changed the port to 80, login to "do not use user", ssl to inactive. Getting the error "Connection closed".

![image](https://user-images.githubusercontent.com/74077000/99398481-7d16f380-290a-11eb-98b8-93d786be20a6.png)

![image](https://user-images.githubusercontent.com/74077000/99398565-9881fe80-290a-11eb-877b-11f70fbebd2a.png)

![image](https://user-images.githubusercontent.com/74077000/99398453-725c5e80-290a-11eb-81bd-3d5f70c1aa71.png)

Regards,
Vinay

**Comment by mbtools** [comment]
Either your system isn't connected to the Internet at all or it's behind a firewall/proxy. You will have to talk to your SAP Basis administrator. 

Until then, you can still use abapGit with offline projects! Just import the ZIP file of the projects you like.

**Comment by vkreddy59** [comment]
Our system is connected to the internet as we are able to download SAP notes. Need to check with Network team if something is blocking because of firewall rules. We are using offline project option for now.

Anyway, thanks a lot for your time. I will work with network team & keep posted on the progress.

Regards,
Vinay

**Comment by larshp** [comment]
@vkreddy59 any progress? can we close the issue?

**Comment by larshp** [comment]
closing, no progress/reply

**Comment by vkreddy59** [comment]
> @vkreddy59 any progress? can we close the issue?

Sorry for the delayed response. You can close the issue. Our firewall is blocking github ip's. Management has decided not to allow multiple github ip's(github ip's) on multiple ports.

**Comment by larshp** [comment]
you can still use the offline option to install projects, https://docs.abapgit.org/guide-offline-install.html

https://github.com/larshp/abapGitServer provides the possibility to run a git server on the ABAP system, but note its limited wrt features

**Comment by vkreddy59** [comment]
Yes, thanks. We have been using offline option.
