### ISSUE TITLE
Switching offline repo to online sets branch to "master"

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4163]
Needs detection of default branch like "new online repo".
 
![image](https://user-images.githubusercontent.com/59966492/98820063-afe95500-23fb-11eb-8a6a-1ce9f43d99b1.png)

![image](https://user-images.githubusercontent.com/59966492/98819984-8c260f00-23fb-11eb-8335-4d5bc3ff2f6f.png)

**Comment by larshp** [comment]
ref https://github.com/abapGit/abapGit/pull/3983/files

**Comment by larshp** [comment]
so, this uses the old poup

I'll use this opportunity to suggest removing the switch offline <-> online feature :)

**Comment by mbtools** [comment]
I'm adding the switch to the new repo settings page and it will do a remove and recreate keeping the settings. We can remove switch, attach, and detach, afterwards.

**Comment by larshp** [comment]
popup to be refactored to html forms much like https://github.com/abapGit/abapGit/pull/4617

**Comment by mbtools** [comment]
Close by #4705
