### ISSUE TITLE
PDTS: Container element texts are not serialized

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#4164]
This is a todo for PDTS. 
PDTS works in principle, it will function correctly without the texts and the elements can still be identified by their technical and short names.

**Comment by abal-illumiti** [comment]
I believe this is not yet supported.
Thanks
-Aman

**Comment by pokrakam** [comment]
Is that a question? The status is still the same. PDTS works, and the main texts are OK.

**Comment by abal-illumiti** [comment]
Not sure if I should be expecting this.

![image](https://user-images.githubusercontent.com/47009831/121402638-2285c900-c928-11eb-8a1e-d2baaf934c9a.png)

**Comment by pokrakam** [comment]
PDTS has been added recently, please raise any other problems with PDTS objects as a new issue.

**Comment by pokrakam** [comment]
FYI, I have removed the experimental status from PDTS, please update to the latest version.

**Comment by mbtools** [comment]
stale. closing
