### ISSUE TITLE
HTTP-Receive: RC=411  Connect to github.com:443 failed: NIECONN_REFUSED(-10)

### ISSUE THREAD

**Issue by AiolosYang** [abapGit/abapGit#4166]
Hi Expert,
i got below issue when i use report : RSWF_TEST_HTTP testing https://github.com.
![image](https://user-images.githubusercontent.com/32993851/98881117-4719df80-24c4-11eb-9c5e-3a50f6cc626d.png)

i have done all steps as mentioned.
1. Tcode:strust import certifications. 
![image](https://user-images.githubusercontent.com/32993851/98881233-7e888c00-24c4-11eb-8e9f-2fa022206ae4.png)
2. rz10 also set these 3 parameters.
![image](https://user-images.githubusercontent.com/32993851/98881423-e9d25e00-24c4-11eb-9401-267d6eca7960.png)
3. server restarted.

please help！！！！！

**Comment by AiolosYang** [comment]
reason：sap server can not access to web.
issue resolved.
![image](https://user-images.githubusercontent.com/32993851/98889712-69682900-24d5-11eb-8264-3fa19cd8de34.png)

**Comment by atharvabharekar** [comment]
How do you check that the SAP server cannot access the web?

**Comment by larshp** [comment]
see https://docs.abapgit.org/user-guide/setup/ssl-test.html
