### ISSUE TITLE
Repository Log Feature

### ISSUE THREAD

**Issue by lucasborin** [abapGit/abapGit#4170]
It would be nice to have a log in the repository level informing who and when someone executed the pull to update the local objects because we would like to track who is importing the new tool version successfully, and who is leaving it without finishing the upgrade.

**Comment by larshp** [comment]
Hi,
On the list page, toggle detail, and it shows who last did a deserialize = pull, however it just shows the latest, does this help?

![detail](https://user-images.githubusercontent.com/5888506/98998273-2b4f2180-2536-11eb-833d-ff0c09854b3b.gif)

**Comment by lucasborin** [comment]
It is enough! Thanks @larshp  👍
