### ISSUE TITLE
Dialogs: Transition to HTML forms

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4171]
- [x] Enhance HTML forms 
- [x] Global abapGit settings
- [x] Personal abapGit settings
- [x] Repository settings
- [x] Change remote
- [x] Make online (Pending #4651)
- [x] Make offline (Pending #4651)
- [x] Package to zip (@g-back)
- [x] Background mode (@mbtools)

**Comment by g-back** [comment]
"Package to ZIP" functionality can also be HTML-ized, starting work on it

**Comment by mbtools** [comment]
I'm changing "Background Mode" to HTML and moving it to the repo settings.

**Comment by g-back** [comment]
Starting work on "Make Online"

**Comment by mbtools** [comment]
How about something like this? Add a new tab to Repo Settings for switching

![image](https://user-images.githubusercontent.com/59966492/112151897-03598400-8be2-11eb-903d-bb4047578258.png)

![image](https://user-images.githubusercontent.com/59966492/112147976-9643ef80-8bdd-11eb-8d3f-d981259cd902.png)

Combines several scenarios.

**Comment by larshp** [comment]
@mbtools 👍 good idea

**Comment by mbtools** [comment]
Completed with #4705
