### ISSUE TITLE
Error while creating repository, "Cannot find .abapgit.xml - Is this an abapGit repo?"

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4174]
Lost of non abapgit related files existed in the repository, the creation of the repo should not fail, its okay to show the error message in the repo screen

![image](https://user-images.githubusercontent.com/5888506/99058900-16a67400-259e-11eb-9ef3-01358277b355.png)

![image](https://user-images.githubusercontent.com/5888506/99058836-0393a400-259e-11eb-8707-8532df75c768.png)

**Comment by mbtools** [comment]
Hmmm. The message is coming from the same place. Not sure how to avoid it the first time but not the second.

https://github.com/abapGit/abapGit/blob/b25a67acea6672ec586e92b79f13ac3b08c7113f/src/zcl_abapgit_repo.clas.abap#L414-L416

Maybe just increase c_new_repo_size?

**Comment by larshp** [comment]
the problem, to me, is that the error is shown on the first screen

it made me assume that the repository was not recreated, however it was created

showing the error in the repository screen(second screenshot) is okay
