### ISSUE TITLE
downport, ALPHA = OUT

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4178]
https://github.com/abapGit/abapGit/pull/4161#discussion_r523422495

its 740sp2,
![image](https://user-images.githubusercontent.com/5888506/99148975-50a17400-268b-11eb-9fc9-4499a9999f5e.png)

**Comment by larshp** [comment]
I'll add it in https://github.com/abapGit/abapGit/pull/4177, give me an hour or two

**Comment by larshp** [comment]
abaplint fix = https://github.com/abaplint/abaplint/pull/1551

**Comment by sbcgua** [comment]
:+1:
