### ISSUE TITLE
Refactor: Remove dependencies from zif_abapgit_definitions

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4179]
`zif_abapgit_definitions` shall not depend on other classes or interfaces.

Current dependencies:
1. `zif_abapgit_object`
1. `zif_abapgit_xml_input`
1. `zcl_abapgit_repo`

Proposal for 1+2: Move to `zcl_abapgit_objects` or a new interface like `zif_abapgit_objects` (but that name could easily be confused with `zif_abapgit_object` ).

```abap
 TYPES:
    BEGIN OF ty_deserialization,
      obj     TYPE REF TO zif_abapgit_object,
      xml     TYPE REF TO zif_abapgit_xml_input,
      package TYPE devclass,
      item    TYPE ty_item,
    END OF ty_deserialization .
  TYPES:
    ty_deserialization_tt TYPE STANDARD TABLE OF ty_deserialization WITH DEFAULT KEY .
  TYPES:
    BEGIN OF ty_step_data,
      step_id      TYPE ty_deserialization_step,
      order        TYPE i,
      descr        TYPE string,
      is_ddic      TYPE abap_bool,
      syntax_check TYPE abap_bool,
      objects      TYPE ty_deserialization_tt,
    END OF ty_step_data .
  TYPES:
    ty_step_data_tt TYPE STANDARD TABLE OF ty_step_data
                                WITH DEFAULT KEY .
```

Proposal for 3: Move to `zif_abapgit_repo_srv`:

```abap
  TYPES:
    ty_repo_ref_tt TYPE STANDARD TABLE OF REF TO zcl_abapgit_repo WITH DEFAULT KEY .

**Comment by larshp** [comment]
currently its not optimal, but its also not a big problem AFAIK

1+2: can try moving it to the classes, but it might fail, due to the abapmerg'ed report

**Comment by mbtools** [comment]
the problem comes when you want to reuse `zif_abapgit_definitions` somewhere else (the installer ;-) ) and it drags the complete abapgit along via these dependencies. I will give it a try.

**Comment by larshp** [comment]
okay 👍
