### ISSUE TITLE
Idea: boilerplates cloning

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#4180]
Not sure if it is to AG or abaplint.
The idea: what if we have a template project - boiler plate ?
Maybe as a "best practice" suggestion. Or as a company ricef template.
It may contain several object, and copying of them will take time. What if we have "clone boilerplate" or "clone template" node ? Which would substitute a fragment in all object names ?

```
zmy_template
zcl_my_template_worker_class
zif_my_template_data_accessor
...
```

results in
```
zricef7367
zcl_ricef7367_worker_class
zif_ricef7367_data_accessor
```

**Comment by larshp** [comment]
something like this, https://github.com/larshp/abap-advent-2020-template

adjust the rename pattern in `abaplint.json`
```json
  "rename": {
    "output": "renamed",
    "skip": [],
    "patterns": [{"type": "CLAS|INTF", "oldName": "(.*)_rename", "newName": "$1_foobar"}]
  },
```

and run `npm run rename`

**Comment by sbcgua** [comment]
Heh, yeah. Exactly. Really cool progress with that :) i think i close the issue for now
