### ISSUE TITLE
Pull and reset local don't remove deleted objects

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4186]
I cannot get rid of these using either Pull or Reset Local (Force Pull).

![image](https://user-images.githubusercontent.com/5270359/99260737-15827a80-281c-11eb-9536-124921f16a3a.png)

Force pull just shows the message local objects will be reset but no dialog to select the class to delete it. Then the message to restart abapGit appears.

**Comment by flaiker** [comment]
Regression of #4162 or just me?

**Comment by larshp** [comment]
I think its a regression of something

**Comment by mbtools** [comment]
yes. `...or rstate = zif_abapgit_definitions=>c_state-deleted`
