### ISSUE TITLE
Repo view table columns for offline repos

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4190]
Seems like the state columns are accounted for in the table header even though they are not relevant for offline repos.

![image](https://user-images.githubusercontent.com/5270359/99297980-504ed780-2849-11eb-9a25-5eef24416ed1.png)

**Comment by larshp** [comment]
I think they are filled after clicking "import zip"

**Comment by flaiker** [comment]
Ah makes sense. Then an empty <td></td> is probably missing.
