### ISSUE TITLE
ZCL_ABAPGIT_OBJECT_SICF=>READ_TADIR called but does not exist

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4195]
https://github.com/abapGit/abapGit/blob/ff6725e7596bedd1f5b3fb3610df266246e576f0/src/zcl_abapgit_tadir.clas.abap#L256-L261

https://github.com/abapGit/abapGit/blob/a3faae98315d13e5bfca82ed42f0851e35cca5b7/src/objects/zcl_abapgit_object_sicf.clas.abap#L16-L23

Seems like a typo in ba787d373ed6da92763510ce4bc7aa0a4332dc3c

**Comment by larshp** [comment]
try deleting the dynamic all, its been this way for a while

**Comment by mbtools** [comment]
see comment in https://github.com/abapGit/abapGit/issues/3453. agree. we can delete the call since it seems to work fine without it

**Comment by flaiker** [comment]
> see comment in #3453. agree. we can delete the call since it seems to work fine without it

Thanks, I forgot about that issue.

I had some problems though with BMFR without the special handling in read_single. Though it may be different as SICF just has a dynamic suffix.
