### ISSUE TITLE
Improve error handling on deletion

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4197]
https://github.com/abapGit/abapGit/blob/5e629f19a7243140e9d7a0eb039a411c26e28f83/src/objects/zcl_abapgit_objects.clas.abap#L521-L532

The "report the error later" approach doesn't really work all that well when multiple errors occur, especially follow up errors. I ran into this in this scenario:

- Delete SHI3 -> reports error, structure is still used
- Delete SHI5 -> reports error via popup, SHI3 structure still exists

![image](https://user-images.githubusercontent.com/5270359/99413651-4b942d00-28f6-11eb-946c-ff44e690c5d6.png)

![image](https://user-images.githubusercontent.com/5270359/99413708-5e0e6680-28f6-11eb-8f02-e6ab8dc515d2.png)

You cannot see why the SHI3 structure failed to be deleted. I suggest collecting the errors in a log.

**Comment by mbtools** [comment]
Check if https://github.com/abapGit/abapGit/pull/4198 works for showing the log

**Comment by flaiker** [comment]
The log does show up! Not the message I found last time in the debugger but I guess the SHI3 object now was already partly deleted. I think generally SHI3 does not seem to support GHIER very well yet.

![image](https://user-images.githubusercontent.com/5270359/99511441-8c3c8680-2988-11eb-8aef-0e40ae8c4c39.png)

**Comment by mbtools** [comment]
The SHI* types should go into https://github.com/abapGit/abapGit/blob/master/src/zcl_abapgit_dependencies.clas.abap (there’s a case) in the right order
