### ISSUE TITLE
Devtoberfest 2020 - Vote for abapGit

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4204]
To all abapGit Contributors, Watchers, and Users
![Devtoberfest2020_](https://user-images.githubusercontent.com/59966492/99574409-607bc980-29a5-11eb-8cd6-c72af8a5977b.png)
We know that abapGit is a winner, no matter how the contest ends. 
But let's make a run for gold and **Vote for abapGit**! 

https://answers.sap.com/questions/13184551/devtoberfest-2020-contest-voting.html

#abapGit #Devtoberfest #EveryVoteCounts

![abapgit_logo](https://user-images.githubusercontent.com/59966492/99574200-0bd84e80-29a5-11eb-87cc-b15b1dbbbfd8.png)

**Comment by larshp** [comment]
Voting closes today, see https://blogs.sap.com/2020/11/09/devtoberfest-contest-voting/

> Voting will be open until Monday, November 23rd 2020.

last chance, closing issue
