### ISSUE TITLE
Illegal interruption of a class constructor for CL_CI_CHECKVARIANT============CP

### ISSUE THREAD

**Issue by GiantCrocodile** [abapGit/abapGit#4235]
Hello,

after deserializing the demo package of https://github.com/SAP-samples/abap-platform-refscen-flight/tree/On-Premise-2020, several crash dumps of the same type are thrown and some objects are not activated.

Basic crash dump information:

`Illegal interruption of a class constructor.`
`The current ABAP program "CL_CI_CHECKVARIANT============CP" had to be terminated because it found a statement that could not be executed.`
`During the class constructor flow for class "\CLASS=CL_CI_TEST_ROOT", a condition arose causing the class constructor to be left prematurely. This is not permitted because it results in an inconsistent state in the class.`

Crash occurred in line 48 of function `CREATE` of class `CL_CI_CHECKVARIANT`.

I think this happens because /DMO/ is no registered namespace or because these objects are created by SAP and thus shouldn't/can't be checked by ATC.

Happened in abapGit v1.102 or v1.101 on NW 755.

Best Regards,

**Comment by larshp** [comment]
during deserialization? what is the stack trace? if I remember correctly, abapGit does not call any CI(code inspector) by default

**Comment by GiantCrocodile** [comment]
Hi @larshp!

Yes, the objects were pulled from the mentioned Git repository and activated.

```
Active Calls/Events

No.   Ty.          Program                             Include                             Line
      Name

    1 EVENT        CL_CI_CHECKVARIANT============CP    CL_CI_CHECKVARIANT============CM002    48
      CREATE
```
```
Application Calls

Index Calls

    1 R=1 T=S S=<system_id> I=CL_CI_TESTS===================CP F=SCI_TESTS_VALIDATE C=100 U=<username>
```

I hope this helps, although it's quite less information. Do you refer to the `ABAP Control Blocks (CONT)` for this crash dump when you mean the stack trace?

**Comment by larshp** [comment]
if code inspector was run manually after abapGit deserialization, its really difficult to determine what is wrong and what/if to fix

need to be able to reproduce the error with a minimal example, providing the steps to reproduce

I personally do not have access to a S/4 2020 system that I can use for testing

**Comment by larshp** [comment]
and SAP has closed for issues in the repository, great

**Comment by GiantCrocodile** [comment]
I asked my colleague: He didn't execute CI manually before or after abapGit deserialization. He just pulled the repository and then  the objects were automatically activated. Some objects were not successfully activated thus he activated them manually.

**Comment by larshp** [comment]
for the missing activation: suggest trying to reproduce the issue in a public repository, with minimal number of objects, and opening this as a separate issue

**Comment by GiantCrocodile** [comment]
I think this was related to some coincident with a basis issues or something like that. I will close this for now as we can't reproduce or test this on our system right now. If this occurs again, I will reopen this issue and provide more details.
