### ISSUE TITLE
If there is no email registered for the current user then unit test ZCL_ABAPGIT_USER_RECORD fails

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4247]
If there is no email registered for the current user then unit tests for class ZCL_ABAPGIT_USER_RECORD fails

**Comment by mbtools** [comment]
Unit tests that depend on sy-uname are a bad idea (same with other sy-fields).

**Comment by larshp** [comment]
yea, not sure how to fix it, perhaps just delete the unit test
