### ISSUE TITLE
abapgit_standalone - put ZIF_APACK_MANIFEST into constant

### ISSUE THREAD

**Issue by Rino53** [abapGit/abapGit#4248]
Standalone version of abapgit could not run on systems with name prefixes restriction.
![image](https://user-images.githubusercontent.com/1096551/100237942-68151280-2f51-11eb-9601-df2692c410c4.png)
![image](https://user-images.githubusercontent.com/1096551/100237600-f63cc900-2f50-11eb-9798-e1d1b86d7ea9.png)
To run it on such a system we need to replace every 'ZIF_APACK_MANIFEST' char call with constant (already exist in source).
Then this constntant could be easealy maintained to run a program.
Solution is ready and tested. How can i propose pull request to file located here - https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap?
Linked issue: https://github.com/fidley/falv/issues/60

**Comment by larshp** [comment]
for contributing to abapgit, also see https://docs.abapgit.org/development/contributing.html

**Comment by flaiker** [comment]
By "name prefixes restriction" do you mean the naming convention settings in se03 ?

Note there is some magic somewhere to make ZIF_APACK_MANIFEST compatible with IF_APACK_MANIFEST on cloud systems which might also need to be adjusted.

**Comment by mbtools** [comment]
I wouldn't call it magic... more horror.

**Comment by mbtools** [comment]
Not a APACK replacement but #4684 will close this
