### ISSUE TITLE
Syntax Error ZCL_ABAPGIT_USER_EXIT=========CP (ZCL_ABAPGIT_REPO_ONLINE unknown)

### ISSUE THREAD

**Issue by habrahams** [abapGit/abapGit#4252]
Hi, 
I'm getting a shortdump doing a force pull from version 1.100.0 to the latest version.
![image](https://user-images.githubusercontent.com/16045067/100360719-019bfd00-3002-11eb-98b9-ae0c93bf41b0.png)

Also when trying to restore my abapgit version via the full report I get the following shortdump:
![image](https://user-images.githubusercontent.com/16045067/100360799-18daea80-3002-11eb-93cf-ad3a157698d7.png)

**Comment by larshp** [comment]
comment the code in ZCL_ABAPGIT_USER_EXIT and try again? alternatively delete ZCL_ABAPGIT_USER_EXIT, but keep a backup

**Comment by larshp** [comment]
@habrahams any luck?

**Comment by habrahams** [comment]
Yes, thanks @larshp , I commented out the code and did a reset local. You can close the issue if you'd like.
