### ISSUE TITLE
Package Structure

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4253]
I suggest a bit of regrouping of classes and interfaces into packages. This should reduce the size of / and /objects. Afterward, /objects will include only the serializer classes. 

$ABAPGIT_OBJECTS_CORE:

ZCL_ABAPGIT_DEPENDENCIES
ZCL_ABAPGIT_FILE_STATUS
ZCL_ABAPGIT_FOLDER_LOGIC
ZCL_ABAPGIT_OBJECTS_ACTIVATION
ZCL_ABAPGIT_OBJECTS_FILES
ZCL_ABAPGIT_SERIALIZE
ZCL_ABAPGIT_TADIR
ZIF_ABAPGIT_TADIR
ZCL_ABAPGIT_SKIP_OBJECTS

$ABAPGIT_OBJECTS_TEXTS:

ZCL_ABAPGIT_LONGTEXTS
ZCL_ABAPGIT_SOTR_HANDLER
ZIF_ABAPGIT_LANG_DEFINITIONS
ZIF_ABAPGIT_LONGTEXTS

$ABAPGIT_OBJECTS_ENH:

ZCL_ABAPGIT_OBJECT_ENHO_BADI
ZCL_ABAPGIT_OBJECT_ENHO_CLASS
ZCL_ABAPGIT_OBJECT_ENHO_CLIF
ZCL_ABAPGIT_OBJECT_ENHO_FUGR
ZCL_ABAPGIT_OBJECT_ENHO_HOOK
ZCL_ABAPGIT_OBJECT_ENHO_INTF
ZCL_ABAPGIT_OBJECT_ENHO_WDYC
ZCL_ABAPGIT_OBJECT_ENHO_WDYN
ZCL_ABAPGIT_OBJECT_ENHS_BADI_D
ZCL_ABAPGIT_OBJECT_ENHS_HOOK_D
ZIF_ABAPGIT_OBJECT_ENHO ENHO
ZIF_ABAPGIT_OBJECT_ENHS ENHS

$ABAPGIT_OBJECTS_OO:

ZCL_ABAPGIT_OO_BASE
ZCL_ABAPGIT_OO_CLASS
ZCL_ABAPGIT_OO_FACTORY
ZCL_ABAPGIT_OO_INTERFACE
ZCL_ABAPGIT_OO_SERIALIZER
ZIF_ABAPGIT_OO_OBJECT_FNC

$ABAPGIT_OBJECTS_TEST:

ZCL_ABAPGIT_OBJECTS_CI_TESTS
ZCL_ABAPGIT_PERFORMANCE_TEST
ZCL_ABAPGIT_TEST_SERIALIZE

Also, group some of the current objects in root to sub-packages.

$ABAPGIT_CTS:

ZCL_ABAPGIT_CTS_API
ZCL_ABAPGIT_DEFAULT_TRANSPORT
ZCL_ABAPGIT_TRANSPORT
ZCL_ABAPGIT_TRANSPORT_2_BRANCH
ZCL_ABAPGIT_TRANSPORT_MASS
ZCL_ABAPGIT_TRANSPORT_OBJECTS
ZIF_ABAPGIT_CTS_API

$ABAPGIT_REPO:

ZCL_ABAPGIT_DOT_ABAPGIT
ZCL_ABAPGIT_REPO
ZCL_ABAPGIT_REPO_CONTENT_LIST
ZCL_ABAPGIT_REPO_FILTER
ZCL_ABAPGIT_REPO_OFFLINE
ZCL_ABAPGIT_REPO_ONLINE
ZCL_ABAPGIT_REPO_SRV
ZIF_ABAPGIT_DOT_ABAPGIT
ZIF_ABAPGIT_REPO_LISTENER
ZIF_ABAPGIT_REPO_ONLINE
ZIF_ABAPGIT_REPO_SRV

**Comment by larshp** [comment]
looks good to me

but make sure to look into the open pull requests before moving everything, so we don't get a lot of conflicts

**Comment by mbtools** [comment]
Similar https://github.com/abapGit/abapGit/issues/1589. Needs a bit of quiet time, indeed

**Comment by larshp** [comment]
I think 

- $ABAPGIT_OBJECTS_TEXTS:
- $ABAPGIT_OBJECTS_ENH:	
- $ABAPGIT_OBJECTS_OO:
- $ABAPGIT_OBJECTS_TEST:
- $ABAPGIT_CTS:

can be done now

**Comment by mbtools** [comment]
Remaining
- [ ] $ABAPGIT_OBJECTS_CORE
- [ ] $ABAPGIT_OBJECTS_OO
- [ ] $ABAPGIT_REPO
