### ISSUE TITLE
No changes during upgrade or locked system/client

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4267]
abapGit should not allow changes to any local objects, if
- system is running an upgrade
- system is set to "not modifiable" (se03)
- namespace is set to "not modifiable" (se03)
- client is set to "repository objects not modifiable" (scc4)

In such cases, the serializer classes might already produce errors. However, a global check should be implemented to prevent
- deserialization
- remove of repos 
- uninstall of repos
- adding new repos

`zcl_abapgit_environment` looks like a good place for the check method. Is this class used by cloud-platform only? is it safe to add methods?

**Comment by larshp** [comment]
its okay to add methods in `zcl_abapgit_environment`

**Comment by larshp** [comment]
relevant method: `zif_abapgit_environment~is_repo_object_changes_allowed`
