### ISSUE TITLE
Several repos for same URL

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4269]
![image](https://user-images.githubusercontent.com/59966492/100686498-75187400-334c-11eb-90ea-43056f171fe7.png)

This should not be possible

**Comment by larshp** [comment]
hmm, I'm pretty sure there have been some checks for this implemented

**Comment by jrodriguez-rc** [comment]
It seems that only the package is checked, not the URL.
A quick fix could be to check if the URL is used in some registered repository, later this check could be extended to forks?

**Comment by larshp** [comment]
can this issue be closed?

**Comment by mbtools** [comment]
Closed by #4330
