### ISSUE TITLE
Cannot create repo (offline or online)

### ISSUE THREAD

**Issue by MBartsch71** [abapGit/abapGit#4270]
Hello,

I am not able to create repos with ABAPGIT anymore. I am on Mac with Platinum GUI.
Everytime after I filled out all fields and click on the create repo button I end up with this:

<img width="643" alt="Screenshot 2020-12-01 at 08 09 20" src="https://user-images.githubusercontent.com/20106101/100708553-cfe1b800-33ac-11eb-8ba3-469a1d06800c.png">

**Comment by larshp** [comment]
yea, the Java GUI doesnt work well with abapGit, see https://github.com/abapGit/abapGit#abapgit

try using the webgui? https://blogs.sap.com/2012/06/27/how-to-configure-web-gui-for-sap/

**Comment by MBartsch71** [comment]
Hi, 

ja WebGUI seems OK, its also a bit strange behaviour, but in the WebGUI itself.
But with ADT it works great, I forgot about that, but thanks for the hint with the WebGUI.

**Comment by larshp** [comment]
there will also be a real web edition some day, https://github.com/abapGit/web_edition
