### ISSUE TITLE
Optimize "change package" process

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4274]
In case an object is moved to another folder - i.e. the package assignment was changed -, abapGit deletes and then recreates the object. If the files are identical (local-sha1 = remote-sha1), abapGit shall only change the TADIR entry to the new package.

**Comment by larshp** [comment]
and the code already knows, there is a flag `packmove` set

**Comment by sbcgua** [comment]
To add: if object move locally, it should also detect it and push both delete and add - this is an action which is not obvious to new comers and cause issues (e.g. #4393 )

**Comment by mbtools** [comment]
maybe staging should be by abap object and not by file. `fugr` might be a concern but for the rest automatically determining which files to stage (add/delete) would work better.
