### ISSUE TITLE
Open in main language in standalone opens development version

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4276]
Scenario:

- You want to update abapGit and have installed the development version
- You don't use the development version for the upgrade since you last upgraded half a year ago and assume it will fail to upgrade such a large difference
- You download the current standalone version
- You execute the standalone version, open the abapGit repo, press pull
- You cannot pull as you are logged on in german while the main language is english
- The error message tells you you can press the Advanced -> Open in main language button
- You press the button. A new window is opened with logon language EN.
- The new window opened the old abapGit development version instead of the standalone report which you were trying to avoid in the first place. This is not easily identifyable as they look mostly identical except for the version number at the bottom.

**Comment by larshp** [comment]
ZCL_ABAPGIT_ENVIRONMENT->ZIF_ABAPGIT_ENVIRONMENT~IS_MERGED can be used to determine if its the standalone running

**Comment by mbtools** [comment]
It's opening abapGit (in the main language) using transaction ZABAPGIT which is part of the dev version repo. Unfortunately, the transaction for the standalone version is user-defined. We can find the code and use that one, but worst case there is no tcode for the standalone version.

**Comment by flaiker** [comment]
Just check if tcode ZABAPGIT exists and points to sy-repid ? If not disable the button.

**Comment by mbtools** [comment]
to stay consistent, let's use sy-cprog.

check if ZABAPGIT points to sy-cprog
- if yes use it
- if no, check if another tcode points to sy-cprog
- - if yes, use it
- - if no, disable button
