### ISSUE TITLE
Errors on pull for remotely deleted objects

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4277]
![image](https://user-images.githubusercontent.com/5270359/100996769-bfbb0b80-3559-11eb-93fb-bdad5666ccd5.png)

This is after executing a pull to update abapGit. Not sure what happended here. I guess deletions aren't done on pull but only on reset local (right?) but then the error message doesn't make much sense. The objects are all still there.

Executing pull again resulted in the same behavior.

Reset local then was able to clean everything up. Which I expected it to and planned on doing anyways but the error messages in the log on pull don't seem right. If remotely deleted object are to be ignored on pull then no import should be attempted for them.

**Comment by mbtools** [comment]
I was able to reproduce this with a different scenario. on pull, you should get a popup asking if objects should be deleted that do not exist anymore remotely.
