### ISSUE TITLE
Shortdump LIST_TOO_MANY_LPROS when switching through repos

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4279]
I was going through all repos in my system to check in updates based on serializer changes because of updating abapGit. Which means I opened abapGit, navigated into a repo, created a branch, committed everything and then pressed back to return to the overview list. I did this maybe 10 times and then got a shortdump.

![image](https://user-images.githubusercontent.com/5270359/101009609-58ee2000-3562-11eb-9c87-2ffb5ffa47bd.png)

![image](https://user-images.githubusercontent.com/5270359/101009785-65727880-3562-11eb-9dbd-49184ebf25a7.png)

![image](https://user-images.githubusercontent.com/5270359/101009923-71f6d100-3562-11eb-955e-d0eeefb47251.png)

Seems to be caused by #4028 as `CALL SELECTION-SCREEN` adds a new call hierarchy.

**Comment by larshp** [comment]
thanks, think I saw an existing issue regarding this, but cannot find it

**Comment by flaiker** [comment]
Yes I think we hypothesized about this scenario at some point somewhere.

**Comment by mbtools** [comment]
at least now we know the approx limit. we could check the size of the callstack and give the user the option to restart abapGit (like we do after the self-update).

**Comment by mbtools** [comment]
I reverted back to `LEAVE TO SCREEN 1001` and tried to reproduce the issue #4027 (#4028). The problem does not occur, because we removed the commit hash on the ATC page (which required the login). 

We should go back to `LEAVE TO SCREEN 1001`.
