### ISSUE TITLE
unable to pull views via abapgit

### ISSUE THREAD

**Issue by schealex** [abapGit/abapGit#4306]
Hi everyone,

we have a problem that we cannot pull (or reset for that matter) views over abapgit.
For testing i created a new package and repository and commited a maintenance view including table maintenance and tried pulling that on another system:

![vt1CCPRfOr](https://user-images.githubusercontent.com/3441348/101766633-5734d700-3ae3-11eb-9bf8-283bd1e3e66c.png)

is this a genereal problem or are we doing something wrong?

**Comment by larshp** [comment]
try checking the transport, one of the errors are raised at, 

![image](https://user-images.githubusercontent.com/5888506/101766886-bb579b00-3ae3-11eb-8005-f959cf1f14bc.png)

**Comment by schealex** [comment]
Hi lars thanks for the quick response, the transport is still empty.
I tried setting a break point at the specified location and subrc is 10 in this case.

**Comment by larshp** [comment]
while in the debugger after SUBRC 10 is raised, check the system variables to see if it carries additional error information,

```abap
SY-MSGID
SY-MSGTY
SY-MSGNO
SY-MSGV1
SY-MSGV2
SY-MSGV3
SY-MSGV4
```

**Comment by schealex** [comment]
does not carry any information other than the id, type and number.

![WU7esiGZt7](https://user-images.githubusercontent.com/3441348/101770409-b34e2a00-3ae8-11eb-85b2-529575fcd750.png)

**Comment by g-back** [comment]
![image](https://user-images.githubusercontent.com/27279305/101772552-c8788800-3aeb-11eb-944f-f6994875ee2f.png)

Does your user have a developer key on the system you are trying to pull?

**Comment by schealex** [comment]
yep my bad forgot to add that on the new test system. anyways the other errors still stay the same.
we dug a little deeper and it seems it's an activation problem with the view because of a missing join:

![szeUP5oVcZ](https://user-images.githubusercontent.com/3441348/101779825-08dd0380-3af6-11eb-83bc-b77058d8d985.png)
![WpBKSln1aa](https://user-images.githubusercontent.com/3441348/101779833-0a0e3080-3af6-11eb-9752-53160a8764aa.png)
![hQgJPnYFXd](https://user-images.githubusercontent.com/3441348/101779840-0b3f5d80-3af6-11eb-890f-64b564ec7dcc.png)

is there a known problem with transfering view clusters in abapgit?

**Comment by mbtools** [comment]
the join condition is missing. Is <DD28J_TABLE>part of the repo?

**Comment by mbtools** [comment]
Here's a test case https://github.com/abapGit-tests/VIEW_with_join. Does pulling work for you?

**Comment by schealex** [comment]
hey @mbtools thanks for taking the time to create a test case. i could pull that without any problems.
as regarding to our repository here is the DD28J_TABLE part from the view, seems like everything is there:

```

   <DD28J_TABLE>
    <DD28J>
     <VIEWNAME>/TVC/UI5_UID_C_V</VIEWNAME>
     <LTAB>/TVC/UI5_UID_H</LTAB>
     <LFIELD>MANDT</LFIELD>
     <OPERATOR>EQ</OPERATOR>
     <RTAB>/TVC/UI5_UID_C</RTAB>
     <RFIELD>MANDT</RFIELD>
     <SOURCE>F</SOURCE>
     <FRKTAB>/TVC/UI5_UID_C</FRKTAB>
     <FRKFIELD>SEQUENCE</FRKFIELD>
     <FRKDIR>E</FRKDIR>
    </DD28J>
    <DD28J>
     <VIEWNAME>/TVC/UI5_UID_C_V</VIEWNAME>
     <LTAB>/TVC/UI5_UID_H</LTAB>
     <LFIELD>MATNR</LFIELD>
     <OPERATOR>EQ</OPERATOR>
     <RTAB>/TVC/UI5_UID_C</RTAB>
     <RFIELD>MATNR</RFIELD>
     <SOURCE>F</SOURCE>
     <FRKTAB>/TVC/UI5_UID_C</FRKTAB>
     <FRKFIELD>SEQUENCE</FRKFIELD>
     <FRKDIR>E</FRKDIR>
    </DD28J>
    <DD28J>
     <VIEWNAME>/TVC/UI5_UID_C_V</VIEWNAME>
     <LTAB>/TVC/UI5_UID_H</LTAB>
     <LFIELD>SEQUENCE</LFIELD>
     <OPERATOR>EQ</OPERATOR>
     <RTAB>/TVC/UI5_UID_C</RTAB>
     <RFIELD>SEQUENCE</RFIELD>
     <SOURCE>F</SOURCE>
     <FRKTAB>/TVC/UI5_UID_C</FRKTAB>
     <FRKFIELD>SEQUENCE</FRKFIELD>
     <FRKDIR>E</FRKDIR>
    </DD28J>
   </DD28J_TABLE>
```

could this be an issue of a wrong sequence while activating?

**Comment by mbtools** [comment]
Able to reproduce with an updated test case (first one had DB view, but issues is with maint. view only):
https://github.com/abapGit-tests/VIEW_with_join

![image](https://user-images.githubusercontent.com/59966492/101969892-1331f700-3bf5-11eb-9883-3a9da61b30dc.png)

The maint view is referring to a foreign key relationship (source = F). The relationship is removed temporarily from the base table when trying to activate it and added back in a second run ("late" step, see `zcl_abapgit_object_tabl->deserialize`). But in between, the view being activated and missing when the relationship.

I will try to find a solution.

**Comment by mbtools** [comment]
I have a fix. See #4317
