### ISSUE TITLE
DDLS CX_SY_RANGE_OUT_OF_BOUNDS on serialize

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4309]
![image](https://user-images.githubusercontent.com/5270359/101806838-b9f29680-3b14-11eb-9564-0a54b0044462.png)

ZCL_ABAPGIT_OBJECT_DDLS->FORMAT_SOURCE_BEFORE_SERIALIZE

![image](https://user-images.githubusercontent.com/5270359/101806962-dd1d4600-3b14-11eb-8bab-4d5e859eccaa.png)

CV_STRING is initial

![image](https://user-images.githubusercontent.com/5270359/101807086-fe7e3200-3b14-11eb-91a3-11aaac2168f6.png)

The relevant CDS view is probably inconsistent as well (reimport after system copy) which is actually why is was checking in abapGit what's up with it....

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/pull/4143 @jrodriguez-rc

**Comment by jrodriguez-rc** [comment]
@flaiker some test case?

**Comment by flaiker** [comment]
No, I ran SDDLAR to manually activate the view (didn't work in ADT) and then abapGit worked as well.

**Comment by jrodriguez-rc** [comment]
There would probably be some inconsistency in the CDS

**Comment by flaiker** [comment]
Oh definitely, 40 transports errored on import because CTS was unable to correctly determine the import sequence based on the CDS dependencies.
