### ISSUE TITLE
background job is canceled

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#4315]
Server is a VM with the latest AS ABAP demo, which is manually started when I need to use it. For this reason, I've scheduled a background run of ZABAPGIT_STANDALONE after the event SAP_SYSTEM_START. Well, the job was being invariably canceled. 

In the log I see:
"Overwrite odd package CLAS ZCL_ABAPGIT_DEPENDENCIES undecided"
"Job canceled after system exception ERROR_MESSAGE"

I only have localy objects so this isn't a repeat of #3857 
After using ZABAPGIT to force pull, with a fair number of warnings on that class and files being changed, the subsequent job ran to completion. 

Should I schedule ZABAPGIT instead? I originally opted to use the standalone version so it wouldn't change itself when running in background.

**Comment by mbtools** [comment]
It should be "overwrite of package..." (fixed in https://github.com/abapGit/abapGit/pull/4316). 

The background pull sets overwrite to yes, so I'm not sure how you get the message:
https://github.com/abapGit/abapGit/blob/master/src/background/zcl_abapgit_background_pull.clas.abap#L38

Or is this your own implementation of `zif_abapgit_background`?

**Comment by AndreaBorgia-Abo** [comment]
No custom implementations except at [logon](https://github.com/sandraros/abapGit-user-exit-logon-by-rfc).
So, in my case, simply updating the standalone report will prevent this issue, correct?

**Comment by mbtools** [comment]
I would update both versions once manually: first ZABAPGIT_STANDALONE, then use stand-alone to update ZABAPGIT dev version.

Then your scheduled job should work again.

**Comment by AndreaBorgia-Abo** [comment]
Yup, it worked already twice in a row, thank you.
Closing now.
