### ISSUE TITLE
ABAP Cloud : Eclipse - FOLDER_LOGIC (PREFIX to FULL)

### ISSUE THREAD

**Issue by chiragpoddar12** [abapGit/abapGit#4325]
How can we change the FOLDER_LOGIC from PREFIX to FULL using ECLIPSE/ABAP Dev Tools. I know we can do it in OnPrem system by using the ABAP GUI, but I am connected to the ABAP Cloud Environment and it does not allow me to open the GUI there. 

MY ERROR: PREFIX: Unexpected package naming (<PACKAGE_NAME>) you might switch to FULL folder logic.

**Comment by larshp** [comment]
I dont think there is an option to change it in via Eclipse

If its not possible to use SAP GUI, then try changing the `.abapgit.xml` file directly in git

**Comment by chiragpoddar12** [comment]
I already have a package created with multiple sub-packages. The tool does not allow me to stage the root package itself as the sub-packages do not follow the PREFIX requirements.

![Capture](https://user-images.githubusercontent.com/6632044/102139047-3824a500-3e55-11eb-92a9-bbf914e5de6b.PNG)

**Comment by larshp** [comment]
delete everything that has been imported, and imprt again? if possible

**Comment by larshp** [comment]
@chiragpoddar12 any luck?

**Comment by peterli-code** [comment]
I am facing the same basic issue.  There appears to be no easy way to delete a sub-package ( or a workaround renaming option ) in my case so I am completely stuck and cannot progress to download a Z package containing the offending Z sub-package over to my prepared GitHub repos.
A complete showstopper and such a time waster. This shows how immature abap cloud is IMHO. Apologies for this gripe but needs to be highlighted to sap.
![SCP_crap](https://user-images.githubusercontent.com/68171678/106267569-c1cfdc80-6221-11eb-80e6-d00c3582a58d.PNG)

**Comment by larshp** [comment]
@ThomasPloski can you help?

**Comment by AndreaBorgia-Abo** [comment]
> If its not possible to use SAP GUI, then try changing the `.abapgit.xml` file directly in git

I just ran into the same issue, this was my attempted workaround:
1. clone the repo to a PC
2. fix the .abapgit.xml file and populate folder structure with package descriptors
3. [commit and push](https://github.com/AndreaBorgia-Abo/ABAP-RAP-CP13)
4. unlink repo from cloud
5. relink to same base package and pull
6. Even if I was ok with losing all objects in the cloud, it still wouldn't let me stage the existing subpackage

**Comment by larshp** [comment]
@chiragpoddar12 any news?

**Comment by larshp** [comment]
closing, no reply
