### ISSUE TITLE
Add Package to mutliple other packages

### ISSUE THREAD

**Issue by fischmir** [abapGit/abapGit#4340]
Hey there,

we are unsure how to handle dependencies between multiple packages.

Let's assume we have 2 separate packages "A" and "B" with totally different approaches. However, both use the same method from a class, which belongs to package "C".

As per my understanding we could define "C" as being a subpackage from "A". In that case, package "A" could be (probably) activated in a new system, because the used class from package "C" is available (if subpackages are NOT ignored).

But do we handle package B in that case? Can "C" be a subpackage from "A" AND "B" at the same time?

Can anyone give us an direction?

Thanks,
Christian

**Comment by larshp** [comment]
well, it depends on what you want to accomplish

are you setting up CI, using git for software distribution? or something else?

all of the above works, it just depends on the goals which is smartest

**Comment by mbtools** [comment]
Simple approach: 3 repos A, B, C and document that A & B require installation of C first

[APACK](https://docs.abapgit.org/ref-apack.html) approach: same repos but for A & B you specify the dependency in the APACK implementation

If C does not have to be independent, add it as a subpackage to A. However, then all of A becomes a dependency for B.

**Comment by fischmir** [comment]
Ok, thank you. We will test APACK.
