### ISSUE TITLE
How to use abapGit with GitLab 2FA/MFA?

### ISSUE THREAD

**Issue by GiantCrocodile** [abapGit/abapGit#4350]
Hello,

I would like to use abapGit with an On-Premises GitLab instance where 2FA/MFA is enabled. When I enter my username and password in the login dialog, I get an HTTP 401 error. Accessing the Git repos from abapGit via username + personal access token does work. Logging in to the GitLab instance via a browser does work too: It asks for the 2FA/MFA information after the login via username and password. Does this have to be implemented on your own?

https://docs.abapgit.org/guide-authentication.html#two-factor-authentication doesn't help me.

Best Regards,

**Comment by larshp** [comment]
abapGit works much like raw command line git, I expect also only personal access tokens to work for raw command line

**Comment by GiantCrocodile** [comment]
Makes sense @larshp. The documentation is a bit unprecise then, right? If a token is the only supported way, it's not a MFA I think? I mean, you just need the token; no second credentials.

**Comment by larshp** [comment]
yea, just the token

yea, the documentation might be unprecise, github recently disabled the 2FA hack, plus it was deleted from abapgit, https://github.com/abapGit/abapGit/pull/4039

**Comment by mbtools** [comment]
And then there was the attempt to use OAuth2 https://github.com/abapGit/abapGit/issues/3766 

Unit SAP supports storing user-specific credentials for 3rd party apps, we can forget about getting this topic resolved.

**Comment by larshp** [comment]
@GiantCrocodile any suggestions for how to improve the documentation?

**Comment by larshp** [comment]
closing
