### ISSUE TITLE
UI - form render(), default iv_form_class ?

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4365]
looks like the `iv_form_class` parameter can be defaulted?

![image](https://user-images.githubusercontent.com/5888506/103459096-f2008a00-4d0c-11eb-97d4-4ca83fa2397b.png)

**Comment by sbcgua** [comment]
Imho, this will tangle the class with css which is not that good

**Comment by larshp** [comment]
there are multiple css classes defined in https://github.com/abapGit/abapGit/blob/master/src/ui/zcl_abapgit_html_form.clas.abap

as a developer, I dont have any clue what to put into the iv_form_class parameter, I just looked up the where-used and copied that, so now there are 5 places with the same form_class

**Comment by sbcgua** [comment]
Yeah, true. Some room for improvement, i agree. In-class css styles were not most clean code indeed
