### ISSUE TITLE
Pull objects with different package

### ISSUE THREAD

**Issue by jrodriguez-rc** [abapGit/abapGit#4386]
About changing objects from a package to another, I was updating the abapGit client with the reorganization of `/repo` objects.

The objects that need to be moved to a new package are first deleted and then created again.

Interface zif_abapgit_dot_abapgit was deleted, causing a syntax error in `zif_abapgit_persistence`
![image](https://user-images.githubusercontent.com/56556686/103886979-9eae8300-50e2-11eb-82db-84a7a6d82876.png)

I don't know why, but now every time I try to change some code, o trying to create the interface `zif_abapgit_persistence`, the system throws a dump
![ezgif-7-3c524be696b4](https://user-images.githubusercontent.com/56556686/103887469-5f346680-50e3-11eb-9303-8d5dcc0d616b.gif)

**Comment by mbtools** [comment]
We already suggested just changing tadir (https://github.com/abapGit/abapGit/issues/4274).

in case of any inconsistencies with the developer version, it's always best to delete the inconsistent object(s) and pull again using the standalone version.

**Comment by jrodriguez-rc** [comment]
The problem is that when I try to create/modify/delete any object a dump occurs
![image](https://user-images.githubusercontent.com/56556686/103907822-0cb67280-5102-11eb-9b35-bd3493096c4c.png)
![image](https://user-images.githubusercontent.com/56556686/103907854-163fda80-5102-11eb-86dd-c30426e53559.png)

**Comment by mbtools** [comment]
the error is in SAPLSKEY. i'm taking a guess here... you had an enhancement in this function group that was referring to abapGit code. ;-)

**Comment by jrodriguez-rc** [comment]
Yep, that is the problem. I could fix it by transporting abapGit from another system.

I'll close the issue if this is already in #4274
