### ISSUE TITLE
Duplicated files (in different sub/packages) is not processed properly

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#4393]
Some strange bug ... not sure what causes it

There is a duplicated object in subpackages - https://github.com/sbcgua/ag-bug1

The ag shows no changes
![image](https://user-images.githubusercontent.com/15635498/104095765-64d7ab00-52a1-11eb-8d58-4f55ef104750.png)

The stage though suggests removing root files (which is kind of correct ... but UI is not consistent in general)
![image](https://user-images.githubusercontent.com/15635498/104095788-7f118900-52a1-11eb-9198-95459d1f52b5.png)

**Comment by mbtools** [comment]
Are you saying that this repo was a result of using AG?

**Comment by sbcgua** [comment]
not this one, but other was. I'm pretty sure it can be repeated: move th program to a sub package, commit just added file and it should be the same

**Comment by sbcgua** [comment]
Even if it is not, it should be a warning at least

**Comment by mbtools** [comment]
got it. that should not be possible, indeed.

**Comment by mbtools** [comment]
I fixed staging with https://github.com/abapGit/abapGit/pull/4403

The other way around (duplicate remotely), when I try to clone https://github.com/sbcgua/ag-bug1, I get several warnings already. That should be fine, no?

![image](https://user-images.githubusercontent.com/59966492/104248747-1577b300-5438-11eb-8145-d95dc6565308.png)

**Comment by sbcgua** [comment]
> when I try to clone ...
Yes but:
- you can still pull it
- and then pull it again (because 2 remote files remain A)
- and then the repo is clear
- yet, stage shows the 2 files

At larger scale, assume there is a bigger repo, with more files like this (warnings ! not errors!) - the direct way to issues. What do you do, if you see these messages ? I personally just pull :)))))))) (very unsecure of me to confess ... but I'm sure I'm not alone)

P.S. I think it is something with the saved state ...
P.P.S will check #4403

**Comment by mbtools** [comment]
Agree. Warning isn't sufficient. It needs to error out during pull.
