### ISSUE TITLE
HTTP 405 error in new online dialog

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4401]
If the URL has one or more trailing spaces, you get an error when selecting "clone":

HTTP error 405 occured: Error in HTTP Request: Invalid version(44) 

![image](https://user-images.githubusercontent.com/59966492/104235093-772d2280-5422-11eb-9766-9853fd7d8a69.png)

**Comment by larshp** [comment]
also see https://github.com/abapGit/abapGit/issues/4284, which should have fixed this issue?

**Comment by mbtools** [comment]
it was an older standalone version in another system
