### ISSUE TITLE
UI: "Back" and bookmarked page

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4408]
Currently, the "Back" button (F3) will go to the previous page. However, in case a page has been bookmarked before (as a "jump-off"), then "Back" should go to the bookmark.

For example, the new "Repository Settings" are a collection of pages or "tabs". Repo overview or repo view are bookmarked when navigating to the settings. After navigating between various settings tabs, "back" should go back to the bookmark.

Details:
- Navigation via `zcl_abapgit_gui->handle_action` (i.e. `go_back` and `go_back_to_bookmark`) are working fine (example "Back" button on settings form)
- Navigation via "Back" (F3) is performed in `zabapgit_forms` `form exit` which always corresponds to `go_back`
https://github.com/abapGit/abapGit/blob/master/src/zabapgit_forms.prog.abap#L102

Idea:
- If a bookmark is included in stack, then `form exit` jumps to bookmark. If not, `form exit` goes to previous page

**Comment by larshp** [comment]
set each tab to be "page replacing" ? then it would work as expected?

**Comment by mbtools** [comment]
cool! works. PR coming
