### ISSUE TITLE
CL_BLUE_SOURCE_OBJECT_DATA not found on SAP_ABA 702 release

### ISSUE THREAD

**Issue by eljoaco** [abapGit/abapGit#4410]
Hi,

The class is not present in our system release. 

![image](https://user-images.githubusercontent.com/29739737/104607773-747c3880-5681-11eb-911c-b0c47fe8d3c7.png)

Any posible solution?

Thanks!

**Comment by larshp** [comment]
thanks, for now, you can comment out the class `zcl_abapgit_object_bdef`, and then activate

the abapgit code should be changed to a dynamic reference instead, #4012

**Comment by g-back** [comment]
The variable `ls_old` is unused anyway - just has to be removed.

**Comment by larshp** [comment]
heh, okay, I got it, https://github.com/abapGit/abapGit/pull/4411, sec

**Comment by eljoaco** [comment]
Ok, thanks!

**Comment by larshp** [comment]
@eljoaco try again, latest version

**Comment by eljoaco** [comment]
Thanks @larshp,  its working fine

**Comment by larshp** [comment]
👍 closing
