### ISSUE TITLE
ROWORCOLST problem with decision from #1722

### ISSUE THREAD

**Issue by DerGuteWolf** [abapGit/abapGit#4425]
With #1722 #1791 a ROWORCOLST setting of 'C' is always serialized as blank.

We frequently use abapGit with tables set to column store. However this is setting is not carried over by abapGit (cf above).

Some of these tables have FullTextIndizes (FTI). When now the table is deserialized the column store setting in ROWORCOLST of 'C' is removed which gives afterwards an error for the table because FTI Indizes are only valid if this is set explicitly to 'C' and are not valid if this is set to blank. This error prevents activation of the table and dependent stuff. After every(!) pull we have for every(!) such table manually(!) access the technical settings of the table and set this to C and then we can activate the technical settings (which thankfully activates all dependent stuff).

So could we amend the change from #1722 #1791 with a mechanism in deserialize that if the field ROWORCOLST is there and the value is blank, it is set to C?

If this would be ok for you, I can do this as a test in our system and provide you with a pull request.

**Comment by mbtools** [comment]
It's the typical case of a "new feature in a newer release". imho, the field should be serialized with the proper value (ie. R or C) if it exists in a given release (no mapping of field content). If imported on a lower release, you will get a diff like with any field that doesn't exist.

**Comment by larshp** [comment]
if its blank, and ROWORCOLST exists in the system, default the value to 'C'

**Comment by DerGuteWolf** [comment]
I created pull request #4430

**Comment by larshp** [comment]
@DerGuteWolf can this issue be closed?

**Comment by larshp** [comment]
closing
