### ISSUE TITLE
SAP GUI for HTML: Issue using "Back" button

### ISSUE THREAD

**Issue by gregorwolf** [abapGit/abapGit#4433]
Hello abapGit Team,

I've installed the current abapGit version 1.104.0 by cloning the repository on a S/4HANA 2020 FPS01. This installation was done using the Windows SAP GUI.

When I the transaciton code ZABAPGIT using WebGUI (SAP GUI for HTML), click on the button "New Online" and then click the button "Back", I see the following screen:

![Screenshot 2021-01-22 at 09 28 40](https://user-images.githubusercontent.com/2639535/105466285-4952a400-5c94-11eb-85dd-598e4c3b202d.png)

so it looks like another WebGUI is started inside the abapGit Web Control. When I then navigate back and try to start abapGit again I get this error message:

> 400 Session Timed Out Session SID:ANON:saps4hsrv_S4H_03:AaX1POg6fvZq33p3Nk_ORU28OEyTBKwaPGB5NtKI-ATT does not exist
> - Error: ICMENOSESSION (-11) Version: 7810 Component: ICM R/3 Handler Date/Time: 2021-01-22 09:28:48 Module: http_r3hdl.c Line: 1328 Server: saps4hsrv_S4H_03 Error Tag: {-}

Is there support for WebGUI in abapGit?

Best regards
Gregor

**Comment by larshp** [comment]
same problem on 751, just it gets nested instead of showing the splash screen,

![image](https://user-images.githubusercontent.com/5888506/105467769-6f794380-5c96-11eb-9c41-934d190db496.png)

**Comment by larshp** [comment]
back handled in https://github.com/abapGit/abapGit/blob/master/src/ui/core/zcl_abapgit_gui.clas.abap, I dont think "use browser navigation" will work

**Comment by mbtools** [comment]
I have tried many things but no success. At least, I was able to extract the core abapGit HTML viewer logic into a small test program which can be used to reproduce the issue. 

https://gist.github.com/mbtools/26989c0f8a18797e41d20facae6f4fc7

**Comment by larshp** [comment]
abapGit screens/pages are stateful, much like classic Dynpros

classic Dynpros have a stack of screens, CALL SCREEN adds to the stack, LEAVE TO SCREEN 0 pops the current screen of the stack and goes back to the previous

I expect the same of abapGit, keep a stack of the screens/pages, going back pops, calling page pushes, replace screen = replaces top of the stack

**Comment by larshp** [comment]
the same approach, `mt_stack` would be the page stack corresponding to a typical dynpro call stack

a call to call_page() pushes to the mt_stack, back pops from the stack, rerendering into the same dynpro whenever a page changes

**Comment by mbtools** [comment]
Exactly. in webgui `show_URL` doesn't properly replace the content but creates a new nested frame. I don't see how AG has anything to do with this behaviour or could work around it.

**Comment by larshp** [comment]
hmm, I think this is due to the way HTML <form> are handled by SAP

the abapGit HTML form code is good, just handling by SAP is buggy, probably best to spend time on getting the web_edition running

**Comment by mbtools** [comment]
note 3024355 clearly says that `go_back` is not supported on HTML GUI 👎 

if I understand it right, with HTML GUI you have to rely on F3 or browser back button, which I don't think raises events. 

Do we remove the "Back" button completely? Or just on HTML GUI? Other ideas?
