### ISSUE TITLE
Error: Component MAIN_LANG_ONLY not found in target 

### ISSUE THREAD

**Issue by mariusraht2** [abapGit/abapGit#4434]
On online repo creation I get the following error, if I click on 'Clone Online Repo':
![image](https://user-images.githubusercontent.com/45243391/105468647-7c4a6700-5c97-11eb-834d-c7169917e0e8.png)

![image](https://user-images.githubusercontent.com/45243391/105468586-705ea500-5c97-11eb-80ec-34cef95a5c32.png)

I try to initially setup abapGit with the online repo.

**Comment by larshp** [comment]
probably a regression after https://github.com/abapGit/abapGit/pull/4432

**Comment by larshp** [comment]
reproduced,

![image](https://user-images.githubusercontent.com/5888506/105470549-fa0f7200-5c99-11eb-9a86-3bee622c484d.png)

**Comment by larshp** [comment]
@mariusraht2 try again, latest version

**Comment by mariusraht2** [comment]
@larshp Thanks - works again :)
