### ISSUE TITLE
file pattern for namespace objects wrong

### ISSUE THREAD

**Issue by Ennowulff** [abapGit/abapGit#4446]
in ZCL_ABAPGIT_OBJECTS_FILES filename, the slashes of the SAP namespace will be replaced by #. So far so good, but later on in SET_FILES the files will not be found, because of the pattern "#namespace#objectname*". 
 The # is an escape character in CP operations.

I suggest the following change:
`  METHOD get_file_pattern.`
`    rv_pattern = filename( iv_ext = '*' ).`
`    REPLACE ALL OCCURRENCES OF '#' IN rv_pattern WITH '##'.`
`  ENDMETHOD.`

**Comment by mbtools** [comment]
That has been fixed already:
https://github.com/abapGit/abapGit/blob/master/src/objects/core/zcl_abapgit_objects_files.clas.abap#L279

**Comment by Ennowulff** [comment]
Argh... Always forget to update to latest version before opening issues... 
Thanks 
Enno
