### ISSUE TITLE
GUI, default theme css is commented out in HTML

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4461]
Hi,
When running https://github.com/abapGit/web_edition, the default css theme is commented out.
What is the background for changing the HTML after the page is rendered? @mbtools @sbcgua ?
After the page is rendered its rendered, I would expect no trickery?

![image](https://user-images.githubusercontent.com/5888506/105962586-50a4f380-6080-11eb-8075-02529c1c7ff1.png)

![image](https://user-images.githubusercontent.com/5888506/105962607-569ad480-6080-11eb-90a5-5bef606310d4.png)

**Comment by sbcgua** [comment]
hmm, the mechanism responsible is the CSS postprocessor which translates CSS with variables to without variable to support IE. But it leave the link to build css ... so it should work, strange.

**Comment by mbtools** [comment]
i thought is was combining all relevant the css-files into one css i.e. common + default + selected theme.

**Comment by larshp** [comment]
heh 😁 

anyhow, something to fix, not the highest of priorities

**Comment by sbcgua** [comment]
Ah, just came to my mind ! bundle.css is created on the fly. It is not an asset. Is web_edition aware of such objects ?

**Comment by mbtools** [comment]
looks to me like `css/bundle.css` is added as an asset:
https://github.com/abapGit/abapGit/blob/master/src/ui/core/zcl_abapgit_gui_html_processor.clas.abap#L160-L164

the path of it might be the problem

**Comment by larshp** [comment]
fixed in https://github.com/abapGit/web_edition/commit/f3eebed5bdc9773d9f9eb4710860c6a39f1ad23d, closing
