### ISSUE TITLE
empty abap source on first commit

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#4469]
The first commit of a new (active) report has an empty source component, just the XML is valid. System is AS ABAP 7.52 SP04 Demo, once it happened with Windows GUI 7.6 and once with 7.70, always using ZABAPGIT, not the standalone version.

[First](https://github.com/AndreaBorgia-Abo/ABAP-Examples/commit/cc09a74349a755c6ceafe5c537e638d8974e112d)
[Second](https://github.com/AndreaBorgia-Abo/ABAP-Examples/commit/5d83fda3938eee0f82875f9ecade09712a73f48a#diff-ee97dd18e0ecb578cda06c045b4af5da23eca5cb7045aa4fb45f85fe1288ad4f)

Anything I should watch out for? I have already tried going back to the repo list and reselecting my repo, no go.
Seems to make no difference whether I am in the editor or not.

**Comment by larshp** [comment]
hmm, I've not seen this before, I guess the report was activated? did you try clicking the "diff" to check what was committed?

**Comment by mbtools** [comment]
Odd. Break-point in `zcl_abapgit_object_prog->serialize` to see if code is read properly.

Side note: I will come back to https://github.com/abapGit/abapGit/issues/3382 eventually. With that, you will be able to view any local or remote file directly in AG.

**Comment by AndreaBorgia-Abo** [comment]
@larshp I believe I had just activated the report, my bad for not checking the commit: I went directly to "stage" and "commit all", being the initial version I did not expect anything funny.
@mbtools thanks for the tip, I'll keep it in mind in case it happens again. Side note: cool project!

**Comment by larshp** [comment]
@AndreaBorgia-Abo suggest we close this issue? unable to reproduce

**Comment by AndreaBorgia-Abo** [comment]
@larshp I agree, I'll open a new one if and when I am able to reliably reproduce it

**Comment by AndreaBorgia-Abo** [comment]
It happened again, slightly different case: report was already activated, clicked "add" then "commit selected".
The main test program was [skipped](https://github.com/AndreaBorgia-Abo/ABAP-Examples/commit/7c7b464a6d0f487f405846ac150aff8a3f5db703), but the CDS views are present.

**Comment by mbtools** [comment]
It looks to me like this might suffering from - what I believe is - a bug in READ REPORT. https://github.com/abapGit/abapGit/issues/4568. Unless the statement specifies STATE 'A', it might return the inactive source which in this issue here is empty. I will suggest a trap in the serializer to catch such situations and return the active code for PROG.

**Comment by AndreaBorgia-Abo** [comment]
@mbtools at least in this case, it wasn't the first activation of the report, not by a long shot, so there should have been an older active version. Anyway I subscribed to that other report, thanks.
