### ISSUE TITLE
Updating abapOpenChecks - issue with deletion of class ZCL_AOC_PARSER 

### ISSUE THREAD

**Issue by GiantCrocodile** [abapGit/abapGit#4479]
Hello,

I pulled the latest version of abapOpenChecks' master branch and after some trouble with the transport type and original system of the objects, I got this one left:

![grafik](https://user-images.githubusercontent.com/6271057/106454253-c0551d00-648a-11eb-9660-c76d0b63bf75.png)

Pressing pull again doesn't do anything. According to the object list the object is deleted on the repository but I can find it here: https://github.com/larshp/abapOpenChecks/search?q=zcl_aoc_parser. So I suspect it's not deleted. Refreshing the object list in abapGit doesn't help too. All other objects of abapOpenCheck are up2date and were activated without issues. The log doesn't show any error or warning, only green messages.

NW 753
abapGit 1.105.0

Best Regards,

**Comment by mbtools** [comment]
The status is certainly wrong. Before fixing it, some questions:
- Does the class exist in your system?
- Did you change branches or the URL of the repo recently? 
- Go to Database Utility and view the repo XML. Does it contain an entry for this class? It should be as follows:

```xml
<FILES>
      <item>
       <PATH>/src/parsing/</PATH>
       <FILENAME>zcl_aoc_parser.clas.abap</FILENAME>
       <SHA1>f51105234d4f6e7396465326717d9646ea4cfdc3</SHA1>
      </item>
      <item>
       <PATH>/src/parsing/</PATH>
       <FILENAME>zcl_aoc_parser.clas.macros.abap</FILENAME>
       <SHA1>f0afbd38c18d05c44ebf0b8be81db21d29499355</SHA1>
      </item>
      <item>
       <PATH>/src/parsing/</PATH>
       <FILENAME>zcl_aoc_parser.clas.testclasses.abap</FILENAME>
       <SHA1>a4bce44b4ab375f4f72b00e8f9e4a1a2d6eff204</SHA1>
      </item>
      <item>
       <PATH>/src/parsing/</PATH>
       <FILENAME>zcl_aoc_parser.clas.xml</FILENAME>
       <SHA1>3307232c32e14c9b3ad71f7b88e8eae98635a5ee</SHA1>
      </item>
     </FILES>
```

- What happens with Advanced > Forced Pull?

**Comment by GiantCrocodile** [comment]
Thank you for your reply!

1. Yes, class `zcl_aoc_parser` does exist in `ZABAPOPENCHECKS_PARSING`.
2. No, I didn't change anything. I just chose the repository which was created by someone else before the system copy (the system I work on is a copy of a different system where abapGit + repositories were already set up) and tried to update it.
3. There are proper entries for the 4 files with matching checksums.
4. I don't see a `Advanced > Forced Pull` option. I only see a `Forced Stage` option.

**Comment by mbtools** [comment]
put break-point at `zcl_abapgit_file_status=>calculate_status` at

```abap
        " Check if same file exists in different location
        READ TABLE lt_remote ASSIGNING <ls_remote>
          WITH KEY filename = <ls_local>-file-filename.
        IF sy-subrc = 0 AND <ls_local>-file-sha1 = <ls_remote>-sha1.
```

What's sy-subrc? Are the sha1 the same?

**Comment by mbtools** [comment]
Very similar to https://github.com/abapGit/abapGit/issues/1066

**Comment by GiantCrocodile** [comment]
I've done `Reset Local (Force Pull)` and it deleted the object and recreated the object (2 dialogs were shown). From an user's point of view I would expect that either it's clear that empty objects are being cleaned up and thus no damage can be done or this action should be done by regular pulling withou having to do a force pull.

From a performance side: Is it a good idea to delete the whole object and to recreate the whole object again just to clean up the unused parts or can we just remove those empty ones without removing the whole object?

Thank you for your help @mbtools!

**Comment by larshp** [comment]
@GiantCrocodile yea, agree, pull requests welcome

Also relevant: https://github.com/abapGit/abapGit/issues/4282 & https://github.com/abapGit/abapGit/issues/3684

**Comment by larshp** [comment]
suggest closing this issue, we got it covered in other issues

**Comment by larshp** [comment]
@GiantCrocodile try again, this should be solved with https://github.com/abapGit/abapGit/pull/4510

**Comment by mbtools** [comment]
Unfortunately that's was part of what I removed from 4510. I have adjusted the description accordingly

**Comment by larshp** [comment]
@mbtools can you help updating this issue with the latest status?

**Comment by mbtools** [comment]
Since #4733 there's only one popup for "Forced Pull". The process still deletes the complete object and recreates it but it happens behind the scenes so no more confusion for the users. Closing.
