### ISSUE TITLE
SOTS/SOTR: Refactor 

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4480]
SOTS and SOTR may exist once per package and will contain short/long texts of other objects (like enhancement implementations). However, they are handled differently in abapGit.

![image](https://user-images.githubusercontent.com/59966492/106491158-91d44380-6484-11eb-9c7b-f8eb6ed9245a.png)

- SOTR (Short Texts) are serialized as part of the object XML that they belong to (using `ZCL_ABAPGIT_SOTR_HANDLER`). `R3TR SOTR <package>` is hidden in the repo view.
- SOTS (Long Texts) are serialized as a separate `R3TR SOTS <package>` object and therefore visible in the repo view

Test repo: https://github.com/mbtools/TEST_SOTR (tx SOTR_EDIT)

Issue 1: SOTR may contain texts that are *not* related to existing objects. These texts are not serialized. 

![image](https://user-images.githubusercontent.com/59966492/106492492-f8a62c80-6485-11eb-8e34-f3db6ba9a26c.png)

Issue 2: SOTS serializes all texts (nothing missing like for SOTR). However, each text becomes a separate file and it's hard to tell which object they actually belong to.

![image](https://user-images.githubusercontent.com/59966492/106492076-86cde300-6485-11eb-999b-36aea44b6886.png)

![image](https://user-images.githubusercontent.com/59966492/106492335-ceed0580-6485-11eb-8dd8-ee167e5fdbf3.png)

We could ignore both issues. Or have a more consistent approach:

1. Add serializer class for `SOTR` (similar to `SOTS`)
2. For `SOTR` and `SOTS` serialize only texts that are *not* related to existing objects
3. Move object-specific `SOTS` texts to the object they belong to

**Comment by larshp** [comment]
for a class, as far as I remember, the developer goes to edit a class in order to create or edit the texts? And the texts are deleted when the developer deletes a class, so from a developer perspective it is part of the class object? Though, it might work differently for other objects, I dont know

**Comment by mbtools** [comment]
I found a definitive list of objects supporting SOTR/S:
LSOTR_SYSTEM_SETTINGSF01, FORM GET_OBJECT_TABLE

Usually, I would say all these texts should be maintained via their regular object editors. However, I'm not sure if that's the case for all of these.

It lists for example XSLT, but I can't see how there's any text to be edited in SE80 > XSLT maintenance (but I'm not too familiar with this).

BTW, SICF is listed there but `zcl_abapgit_object_sicf` does not include these texts -> Bug. I will open an issue.

**Comment by mbtools** [comment]
Issue 3: Neither SOTR nor SOTS texts are being uninstalled properly:

Typically, you can find lots of leftover entries in table `SOTR_HEAD/SOTR_HEADU` with `CREA_NAME = <your user>`.

**Comment by mbtools** [comment]
Issue 4: Filename contains the package name

Issue 5: Aliases (#5103)

Proposed solution:

In general, OTR texts (short and long) should be part of the object they belong to. This way you see proper diffs and deleting/updating texts impacts only the original object (like an enhancement with texts). For this to happen, we need `zcl_abapgit_sots_handler` (in addition to `zcl_abapgit_sotr_handler`) and to include it for all object types that support OTR. We should also check that both types of texts are deleted properly.

Neither SOTR nor SOTS should be serialized as separate objects. My proposal is to include any texts, that are *not* already included with other objects, in the `package.devc.xml`.  This would avoid the problems with filenames for SOTS/SOTR and reduce the number of overall files.

**Comment by boy0korea** [comment]
> Neither SOTR nor SOTS should be serialized as separate objects. My proposal is to include any texts, that are _not_ already included with other objects, in the `package.devc.xml`. This would avoid the problems with filenames for SOTS/SOTR and reduce the number of overall files.

I agree add to `package.devc.xml`.

I think finding OTR not included with other objects is heavy job.
The easier way may be finding OTR with alias.
It can happen that there exists some OTR not included with other objects and dose not have alias.
No problem. They are orphans and can not be used anymore.

**Comment by mbtools** [comment]
Issue 6: Dynpro send in background (#5420)

**Comment by mbtools** [comment]
Summary: 

- [ ] SOTR may contain orphan texts
- [ ] SOTS serializes all texts into separate files
- [ ] Neither SOTR nor SOTS texts are being uninstalled properly
- [ ] Filename contains the package name
- [ ] Aliases (https://github.com/abapGit/abapGit/issues/5103)
- [ ] Dynpro send in background (https://github.com/abapGit/abapGit/issues/5420)
