### ISSUE TITLE
Current Master Branch

### ISSUE THREAD

**Issue by NLengner** [abapGit/abapGit#4483]
Hi, 

for your information:
I want to create a Report, which creates a xml file, which shows me the current master branch on all Reports in the Git Repository that are on the product systems.
My question: Is there a method/way to get the current Master sha1? With the API I will get the current/newest Version sha1.
[example.pdf](https://github.com/abapGit/abapGit/files/5910027/example.pdf)

Yours sincerely
NLengner

**Comment by larshp** [comment]
following will get all branches,

```abap
DATA(lo_list) = NEW zcl_abapgit_git_transport( )->branches( 'https://github.com/abapGit/abapGit.git' ).
DATA(lt_list) = lo_list->get_all( ).
BREAK-POINT.
```

**Comment by NLengner** [comment]
Thank you.
