### ISSUE TITLE
Error: In order to add /src/ecc/package.devc.xml, you have to remove /src/nw/package.devc.xml 

### ISSUE THREAD

**Issue by ed-holland** [abapGit/abapGit#4485]
Made some package attribute changes and an additional sub package.

Issue is that i can not commit package changes due to the above message.
![image](https://user-images.githubusercontent.com/53995991/106875148-a0b23480-66d6-11eb-8f07-c3f37c688139.png)

If i then try to commit only the NW package the message is revered
![image](https://user-images.githubusercontent.com/53995991/106875303-cfc8a600-66d6-11eb-929b-6c0df712b95f.png)

What should the error message prohibit?

**Comment by larshp** [comment]
I think the intention is to avoid having multiple files with the same object, the DEVC might be a special scenario

ref https://github.com/abapGit/abapGit/pull/4403

as temporary workaround, just comment the following code in `zcl_abapgit_gui_page_stage`,
![image](https://user-images.githubusercontent.com/5888506/106883231-035bfe00-66e0-11eb-95ec-fcbadc3240a5.png)

**Comment by ed-holland** [comment]
Workaround implemented and committed the change.
