### ISSUE TITLE
Check if object is is part of "abapGit Package"

### ISSUE THREAD

**Issue by BlackmanCC** [abapGit/abapGit#4486]
I would like to check during transport (task) release, if an object is part of a package linked to a git repo, 
to give the developer an info message not to forget pushing to repo.

Any hints or tips how to do this? I would like to check for a given package, if it is linked to a repo and a transport
task is being released.

**Comment by larshp** [comment]
I did some stuff in https://github.com/abapGit/background_modes/blob/master/src/zcl_abapgit_tran_to_bran.clas.abap quite a while ago, but not exactly the same scenario

Suggest something like this:
1: list all objects in transport, find unique list of packages
2: list all abapGit repos, for each package in list check if itself or one of the parent(might be multiple levels) packages equals

list all abapGit repos via https://docs.abapgit.org/development/api.html#list

**Comment by BlackmanCC** [comment]
Thanks a lot. I forgot to check the API info.

**Comment by larshp** [comment]
feel free to share the code you come up with, it might help other people
