### ISSUE TITLE
Happy 100k 🎉

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#4493]
Dunno if anyone noticed but abapGit has passed 100k LoC
![image](https://user-images.githubusercontent.com/25539927/107064511-7eeaa780-67d3-11eb-981b-a48b54683a4b.png)

My sincere thanks to all contributors' dedication and hard work that has made this an amazing project!

**Comment by bigld** [comment]
![image](https://user-images.githubusercontent.com/4643389/107065181-c295df00-67dc-11eb-843f-2461c28ddc0d.png)

**Comment by mbtools** [comment]
It's an amazing piece of software. I've been using it for about 2 years. The interface been ABAP and git (github.com) is rock solid and has worked flawlessly for me! Pull, stage, commit, branches, etc. is all very reliable.

100k means more features (woohoo) but also more code to maintain. More active contributors are always welcome! 

Most disappointing: Although SAP is promoting or even relying on abapGit (for example, when moving code to cloud), there are pretty much zero contribution from them.

**Comment by larshp** [comment]
@bigld yea, but one of the original ideas was having all the features easily accessible, eg by copy pasting

@mbtools 👍 

100k lines or moving to 200k lines might be troublesome to copy pasta into a system, hmm

**Comment by pokrakam** [comment]
> 100k lines or moving to 200k lines might be troublesome to copy **pasta** into a system, hmm

Are you referring to spaghetti code or lasagne architecture? 😆

**Comment by larshp** [comment]
closing, discussion
