### ISSUE TITLE
Pull Repo: ERROR while importing Object

### ISSUE THREAD

**Issue by seniorFreshmen** [abapGit/abapGit#4506]
This issue references to [Pull Repo: ERROR while importing Object [...] from the DB #729](https://github.com/sapmentors/abap2xlsx/issues/729) in Repo `ABAP2XLSLX` 

**System**: SAP ERP, Netweaver 7.50
**Problem**: `.INCLUDE BAPIBUS1006002_CENTRAL ` in Structure `ZEXCEL_S_ORG_REL ` has more fields than expected

While initially Pulling the ABAP2XLSX repo an error is occurring:
![image](https://user-images.githubusercontent.com/45813255/106883164-e9bab680-66df-11eb-8c96-2c7dab308f6c.png)

Structure: 
![image](https://user-images.githubusercontent.com/45813255/106887291-4076bf00-66e5-11eb-9645-fd05cf02be0e.png)

Like @sandraros detected: 

> In your system, it seems that .INCLUDE BAPIBUS1006002_CENTRAL is at the 109th position, but in my S/4HANA 1709 system, it's at the 108th position. So it means that in your system one of the previous SAP structures has more fields.

**Comment by mbtools** [comment]
https://github.com/sapmentors/abap2xlsx

We should remove `<position>` from serialization. During deserialize, components just need to be numbered sequentially. `DDIF_TABL_PUT` will take care of the rest. 
https://github.com/abapGit/abapGit/blob/master/src/objects/zcl_abapgit_object_tabl.clas.abap#L718
