### ISSUE TITLE
Pull of CLASENH ENHO object -> File not found: <classname>.enho.em<001>.abap

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#4515]
Error while pulling the CLASENH ENHO `ZCL_RIS_SHM_METADATA` object of this [repository](https://github.com/sandraros/ADT-7.52-Trial-faster-Alt-F8):
![image](https://user-images.githubusercontent.com/34005250/107881080-d9c28400-6ee2-11eb-8a3d-993f4b5bc768.png)

The issue is that abapGit considers that the include numbers (`...em002...` to `...em004...` in the screenshot above) and the editorders should match. That's incorrect. See the below line in method `DESERIALIZE_INCLUDES` of class `ZCL_ABAPGIT_OBJECT_ENHO_CLASS` which fails:
- Bug:
  ![image](https://user-images.githubusercontent.com/34005250/107882077-b221ea80-6ee7-11eb-8f62-55f704c98b15.png)
- the source file corresponding to the method `zz_include` is `zcl_ris_shm_metadata.enho.em002.abap` (and not `...em001.abap`):
  ![image](https://user-images.githubusercontent.com/34005250/107882137-0331de80-6ee8-11eb-8a2e-e48f25149ab2.png)

For information, the XML contains nothing about the include numbers:
![image](https://user-images.githubusercontent.com/34005250/107881977-26a85980-6ee7-11eb-84b7-c88bf2ae5c06.png)

To reproduce, ABAP 7.52 SP 1, enhance the class `CL_RIS_SHM_METADATA`, push and pull:
- Create method `ZZ_GET_LEGACY_METADATA` (assigned to include `ZCL_RIS_SHM_METADATA======EM001`, with editorder 1)
- Create methods `ZZ_CONSTRUCTOR, ZZ_INITIALIZE, ZZ_GET_LEGACY_METADATA2` (assigned to includes `...EM002, EM003, EM004`, respectively with editorders 2 to 4)
- Delete method `ZZ_GET_LEGACY_METADATA`
- Internally, we now have the "editorder" reassigned from number 1 but not the EM include numbers, i.e. the includes are `...EM002, EM003, EM004` respectively for methods `ZZ_INITIALIZE, ZZ_CONSTRUCTOR, ZZ_GET_LEGACY_METADATA2`, and the are respectively assigned the editorders 1, 2 and 3.

**Comment by mbtools** [comment]
Yes, needs a fix
https://github.com/abapGit/abapGit/blob/master/src/objects/enh/zcl_abapgit_object_enho_class.clas.abap
https://github.com/abapGit/abapGit/blob/master/src/objects/enh/zcl_abapgit_object_enho_clif.clas.abap

The content of `lt_includes = io_class->get_enh_method_includes( ).` should be serialized or added to the `TAB_METHODS` xml.

PR welcome :-)

**Comment by sandraros** [comment]
The solution is more complex than expected because if the repository contains EM002 but not EM001, abapGit pull creates the includes starting from ...===EM001 and consequently there is a difference between ABAP and repository.
Instead of having files named with emxxx, a solution is to name them using the method names, like `<classname>.enho.em_<methodname>.abap`.
With the current PR, it works well for me but if the repository contains old names, and someone pushes with new names, I had a case where one old name was kept in the repository. Here you can see that em003 is not deleted from the repository after stage:
![image](https://user-images.githubusercontent.com/34005250/108607063-501d2580-73be-11eb-817e-5487ea938a72.png)
Need your help to understand why em003 file is not deleted. Thanks.

**Comment by mbtools** [comment]
You have to explicitly select the file on bottom of the staging page. Since there are no local changes now, you have to do Advanced > Force Stage.

**Comment by sandraros** [comment]
Right, great, thanks!
