### ISSUE TITLE
Root CA needed for ABAP Git SSL Setup

### ISSUE THREAD

**Issue by Petchimuthu017** [abapGit/abapGit#4516]
Hello,

We are facing certificate errors even after uploading certificates from github.com as mentioned in the ABAP Git documentation. From our Basis team we got to know that we need Root CA which can resolve this issue. Kindly Share the correct Root CA for connecting github.com with our on premise system.

Thanks & Regards,
Petchimuthu M

![image](https://user-images.githubusercontent.com/67868509/108057635-e547b380-7078-11eb-895e-85ac898cf15c.png)
![image](https://user-images.githubusercontent.com/67868509/108057999-64d58280-7079-11eb-80f8-3812d3a83564.png)

**Comment by larshp** [comment]
see https://docs.abapgit.org/guide-ssl-setup.html

**Comment by mbtools** [comment]
Here are the current certificates. valid until May 2022:

[github.com.certificates.zip](https://github.com/abapGit/abapGit/files/5988917/github.com.certificates.zip)

**Comment by Petchimuthu017** [comment]
Thankyou so much for your timely help!
