### ISSUE TITLE
Bitbucket connection issue

### ISSUE THREAD

**Issue by Sdfraga** [abapGit/abapGit#4523]
Hello,

I am using an enterprise Bitbucket account to manage my repos.
Today when trying to connect to Bitbucket from abapGit, user credentials are prompted, but..

![image](https://user-images.githubusercontent.com/16186872/108168444-9b51e280-70f7-11eb-9fec-96bbd285bd24.png)

What?? OK..let's switch branches:

![image](https://user-images.githubusercontent.com/16186872/108168562-cc321780-70f7-11eb-8f19-44667765bdb1.png)

Humm..OK, let's deep dive (using callstack from the error message, an amazing feature!!)

![image](https://user-images.githubusercontent.com/16186872/108168736-174c2a80-70f8-11eb-977f-7b6c3bf9a41b.png)

Breakpoint at ZIF_ABAPGIT_POPUPS~BRANCH_LIST_POPUP from class ZCL_ABAPGIT_POPUPS, let's see what are the branches for my repo after the following line is exectuded:

`lo_branches    = zcl_abapgit_git_transport=>branches( iv_url ).`

And the result is:

![image](https://user-images.githubusercontent.com/16186872/108169682-529b2900-70f9-11eb-8b61-a4de4dffd244.png)

Oh, something went wrong with the authentication...let me connect to bitbucket via the web client:

![image](https://user-images.githubusercontent.com/16186872/108169239-bec95d00-70f8-11eb-94c0-8c4ddf6ac9e4.png)

and ensure _I am not a Robot.... OK. Done! I'm in. 
Let's try again abapGit:

![image](https://user-images.githubusercontent.com/16186872/108169358-e6202a00-70f8-11eb-8302-3b11baf12199.png)

Success!
So it seems like abapGit is not managing well this specific case. 
Does anyone had this case already?

Thanks
S

**Comment by larshp** [comment]
heh, can you help checking what the HTTP status code is? does bitbucket send 200 for this reply?

**Comment by Sdfraga** [comment]
Yap, that's a 200...

![image](https://user-images.githubusercontent.com/16186872/108171599-07cee080-70fc-11eb-91ec-1548873026de.png)

**Comment by christianguenter2** [comment]
We also use bitbucket enteprise and colleagues had this occasionally too. I'd appreciate if we could handle that :-).

**Comment by larshp** [comment]
the git code should throw an error if the reply is not properly formatted during reference discovery

**Comment by larshp** [comment]
@Sdfraga try setting a breakpoint here, and paste the contents of `iv_data` into this issue
![image](https://user-images.githubusercontent.com/5888506/108347628-05928200-71e1-11eb-86e7-805c843b7b6b.png)

**Comment by Sdfraga** [comment]
![image](https://user-images.githubusercontent.com/16186872/108466563-1d6f1200-7284-11eb-8015-d6853aa82830.png)

**Comment by larshp** [comment]
the tabluated view? the HTML view might hide stuff

**Comment by Sdfraga** [comment]
![image](https://user-images.githubusercontent.com/16186872/108466751-7343ba00-7284-11eb-84a4-a502ad849209.png)

**Comment by Sdfraga** [comment]
should we test the content of iv_data for 230ERR or CAPTCHA and raise an exception if found?

**Comment by larshp** [comment]
I'll have a look, I dont exactly remember the protocol, but something like "000" is the channel

**Comment by larshp** [comment]
ref https://github.com/git/git/blob/master/Documentation/technical/pack-protocol.txt
