### ISSUE TITLE
Background logic aborts complete processing when a repo encounters an exception

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#4527]
abapGit :  1.105.0
ABAP : 750

When running the abapGit in background mode, if a repo processing fails due to any exception( ex: Unauthorized access, 404 not found etc..) then the background cancels with failed message. This prevents other packages from processing. It would be nice to handle the exception, add this message to list processing and continue with other packages.

How to replicate issue:
1. Setup minimum two repositories with background mode( Automatic push, auto author as an example )
2. Enter incorrect credentials for first repository  so that it would fail 
3. Enter correct credentials for second repository so that we expect this to be processed

**Spool Output**
![image](https://user-images.githubusercontent.com/29766214/108311125-6c339200-7219-11eb-9406-13c737e552cf.png)

**Background Job Log**:
![image](https://user-images.githubusercontent.com/29766214/108311231-95542280-7219-11eb-9954-e5bdaecb8993.png)
![image](https://user-images.githubusercontent.com/29766214/108311299-b74da500-7219-11eb-8fc2-06c7cbd65eff.png)

The job cancelled when it encountered first exception. I would except to handle this exception, write the error message to the spool and then continue with next repository. 

I would suggest to make changes something like below which handles the exception, writes the message to the log in RED color and continue with next repository instead of aborting the remaining processing.

![image](https://user-images.githubusercontent.com/29766214/108311758-71dda780-721a-11eb-998f-d6f278994940.png)

Regards,
Yellappa.

**Comment by larshp** [comment]
yea, thanks, instead of WRITE suggest adding the error to `li_log`, pull requests welcome 😄

**Comment by yellappam** [comment]
Will make the changes accordingly. Please expect delay as I am new to open community and Github :)

**Comment by larshp** [comment]
no worries

**Comment by yellappam** [comment]
After fix: Package1 has error. It logged the error and continued with next package.

![image](https://user-images.githubusercontent.com/29766214/108464501-26dc9680-72e5-11eb-899c-0d1a7fbe97a1.png)
