### ISSUE TITLE
show the BG and lock icons in the repo overview

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4528]
![image](https://user-images.githubusercontent.com/5888506/108320203-c6553880-71c2-11eb-8e24-4f0f04356c4a.png)

show in repo list,
![image](https://user-images.githubusercontent.com/5888506/108320283-e258da00-71c2-11eb-99a4-3fec43c6a229.png)

**Comment by sbcgua** [comment]
Could be tightly packed at the beginning. The online/offline icon might be not needed by the way - it is clear from the URL (probably, not sure). One downside - the star is interactive (clickable) but the lock/bg will not be. Hmmm.

**Comment by larshp** [comment]
yea, I think most people are not using the features, plus all is wide-screen now'a'days

but perhaps remove the "https://" from the url column?

**Comment by sbcgua** [comment]
> but perhaps remove the "https://" from the url column?

Yeap, makes sense, can leave it in a tooltip

**Comment by larshp** [comment]
on hold until https://github.com/abapGit/abapGit/pull/4541 is merged

**Comment by larshp** [comment]
actually, for now I just would like the lock icon, which is already in memory

the background is more difficult, and might break some performance
