### ISSUE TITLE
Wall Messages

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4530]
Suggest a new feature where it's possible for the users of abapGit to define "Wall Messages", on the repository overview screen, and for each repo. As a starting point just simple text or HTML?

This text can help to explain the policies of using abapGit, who is responsible for updating abapGit in the system, who uses it etc.

![image](https://user-images.githubusercontent.com/5888506/108347949-78036200-71e1-11eb-9fc5-4292b068fb47.png)

![image](https://user-images.githubusercontent.com/5888506/108348067-9bc6a800-71e1-11eb-83a7-677069c9a966.png)

**Comment by mbtools** [comment]
I can see that being useful. Things that you don't need (to read) every day should be hidden by default or have a user option to click and confirm it.

For repos, I would rather see us go for markdown and the option to display the readme on the repo view.

**Comment by larshp** [comment]
markdown: then we need to ship a markdown renderer, which could be 1000s of lines, just for this smaller feature

**Comment by christianguenter2** [comment]
Regarding readme #1102

**Comment by larshp** [comment]
this is not a readme, its a per system text, which can be set by users, for internal purposes

**Comment by christianguenter2** [comment]
Yeah, I like the idea. Just linked the issue because Marc mentioned displaying the readme.

**Comment by jfilak** [comment]
I would be happy with a short text provided by the user exit:

```
This is a production instance of abapGit, feel free to fix bugs but do not attempt to experiment with the source code. If you want to develop abapGit, use your private system from ABAP Trial in Docker.

Visit "https://our.corporate.url/for/more/details".
```

**Comment by larshp** [comment]
Or on repo level

`This repository is updated/pulled by me@corp.com, please contact me if changes are required, bugs, comments, questions etc.`

**Comment by larshp** [comment]
@jfilak something transportable, eg. a user exit would work best for you right?

**Comment by jfilak** [comment]
Yep, sure, a new method in the existing user exit would be enough. I would already do that, if it was really annoying me. Right now, every once in a while, I have to send an angry email to someone who thought it's a great idea to do this and that with abapGit in our development systems.

**Comment by larshp** [comment]
@jfilak see #4653
