### ISSUE TITLE
diff page rendering, stop showing diffs after first 10k?

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4537]
on the diff page, suggest stop rendering diffs after 10k lines have been rendered

it hangs the window, and the user will not have any value of showing a mega diff

**Comment by mbtools** [comment]
It's the complexity of the HTML. Too many DOM nodes. It's probably better to turn off syntax highlighting if the diff page becomes too large. But thousands of diffs will do the same.

**Comment by larshp** [comment]
just stop after a maximum of something, could limit the DOM nodes, but what if there are 100k lines of diff, without syntax highlighting, it would give the same problem

**Comment by FreHu** [comment]
Another option is to render the diffs collapsed, but you still have to transfer the html

**Comment by larshp** [comment]
might help frontend rendering, but the user also waits for backend rendering

alternatively we need to add events for uncollapse, which is complexity

**Comment by larshp** [comment]
okay, not super important, closing for now
