### ISSUE TITLE
Auto creation of package during new online doesnt work

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4538]
ref https://github.com/abapGit/abapGit/pull/4431

click "new online",
![image](https://user-images.githubusercontent.com/5888506/108512472-92147180-72c1-11eb-97a8-9b40d91f42c5.png)

and clicking the package after creation,
![image](https://user-images.githubusercontent.com/5888506/108512499-99d41600-72c1-11eb-9098-e9ce28034837.png)

**Comment by mbtools** [comment]
I assume it's because the repo is empty and not because it's private, right?

**Comment by larshp** [comment]
yea, I was just testing with a private repo

looking briefly at the code, it looks like it creates the package on pull? in this case I'm initializing a new empty repo

**Comment by mbtools** [comment]
it's what I would expect: an empty repo with just .abapgit.xml. 

But the message should be a warning or not be shown at all.

**Comment by mbtools** [comment]
or we create the root package automatically like in the pull case
