### ISSUE TITLE
Strip certain details from serialized XMLs

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#4540]
replaces #3705

Possibility to strip certain details out of diff e.g. when deploying between different system versions there are some new attrs added. Thus the objects always have diff. Or. A system with different set of languages. Would be nice to strip certain languages. Technically I'd see it as some kind of XML postprocessor, which would enable to delete certain XML parts according to set of XPath rules, entered in some freely enterable "deployment config"

E.g. (DTEL)

![image (2)](https://user-images.githubusercontent.com/15635498/108604887-404f1280-73b9-11eb-9e4c-63213eecf31a.png)

![2021-02-19_21h05_17](https://user-images.githubusercontent.com/15635498/108558756-120efb80-7303-11eb-8f11-cebb78473404.png)

Implementations options:
- From @larshp: "suggest an user exit as a starting point, the user can choose to do whatever with the files after they are pulled from git"
- some kind of free-entry input as a param to deserialization to list Xpath-like rules to apply to local and remote files before analysing the difference

**Comment by mbtools** [comment]
Many of the rules will be related to release differences (ie. new fields in new releases). I think an exit is better since we can share the exit code as a repo and continuously enhance the rules.

**Comment by sbcgua** [comment]
I'm OK with exit. But I just think that the code would be very typical. The "strip config" could look something like:

```
DTEL:/DOKIL/DOKSTATE
VIEW(mysubpkg*):/some/path
SHI3:/TREE_HEAD/BUFFERVAR
```

So it can be universal. Totally fine to start with a user exit though. Just logging the idea (or I forget them myself ... :)

**Comment by sbcgua** [comment]
It can also be a part of repo (or .abapgit ... though not sure, probably a separate file would be better). Which will need native support from AG side

**Comment by sbcgua** [comment]
a bit offtopic but a repo can contain a deployment config to declare strip settings and sequence of deserialization - that would be cool !

**Comment by larshp** [comment]
also a sidenote: personally I'd probably do this outside abapGit(if I want to do this), running some script to change the XML, generate one branch or zip for each target

**Comment by sbcgua** [comment]
Not that easy:
- Issue 1: I already though about it, this approach will fix **remote** files but not local which are created dynamically. Serialization should do the stripping too.
- Issue 2:

**Comment by larshp** [comment]
merged, can this issue be closed?

**Comment by sbcgua** [comment]
yeap.
