### ISSUE TITLE
Refactor: Split repo settings and checksums in persistence

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4555]
Currently the repo meta data contains all checksums:
https://docs.abapgit.org/ref-database-util.html#repository-meta-data

In case of many repos or repos with many objects, reading and transforming the XML takes a long time (`zcl_abapgit_persistence_repo->from_xml`). 

Suggestion:

Remove the checksums from the `REPO` entry and put them into a separate `REPO_CHKSUM` entry. 

Things to consider:

- Performance: list of checksums can become very large. Probably faster to store in fixed-length format than in XML
- Consistency: Checksums are not kept by branch causing issues with switching branches (#3997)

**Comment by larshp** [comment]
* Migration: probably add some general mechanism to check if the migration has run

consistency: see https://github.com/abapGit/abapGit/issues/3997#issuecomment-734223107

**Comment by mbtools** [comment]
implementation started in #5328

**Comment by sbcgua** [comment]
Can be closed ?
