### ISSUE TITLE
Collapse/expand panel for messages on main screen

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#4565]
abapGit: 1.104.0
ABAP: 750

We have some packages with long list of unsupported objects( around 50 pages ) and need to scroll through every time. Is it possible to add collapse/expand panel for messages?

![image](https://user-images.githubusercontent.com/29766214/109384906-e15b4180-7954-11eb-8cfd-cd8aef890194.png)

**Comment by mbtools** [comment]
the obvious answer is to put custom development and Analysis Office documents into separate packages. 

if the AO docs should be part of the repo, feel free to create a serializer class. they are a BW object so the generic serializer could work (copy `ZCL_ABAPGIT_OBJECT_ASFC` to `ZCL_ABAPGIT_OBJECT_AAOE`). however, these are blobs that will blow up the size of your repo.

Some collapsing makes sense when the number of messages gets bigger. The output of the log is here:
https://github.com/abapGit/abapGit/blob/master/src/ui/zcl_abapgit_gui_page_repo_view.clas.abap#L825

If it needs JS, then add it to 
https://github.com/abapGit/abapGit/blob/master/src/ui/zabapgit_js_common.w3mi.data.js

another alternative would be to add a user exit to filter the log

**Comment by yellappam** [comment]
It was an example only. For now, collapse option works.

**Comment by larshp** [comment]
Alternatively, change the error messages to a single error message like "Object type AAOE not supported, 20 objects ignored", not super informative, but I guess the user will figure out how to look up the details if needed

**Comment by yellappam** [comment]
Most of the messages are related to unsupported objects. We can group such kind of messages per object type like you suggested "Object type AAOE not supported, 20 objects ignored". The check is happening inside ZCL_ABAPGIT_OBJECTS=>SERIALIZE which we can leave it as is. We can filter unsupported objects before serializing. Below is the place where we can add a method something like **filter_unsupported_object**.

![image](https://user-images.githubusercontent.com/29766214/109453109-1a5ef780-7ab6-11eb-8d32-ec4d4e7363d2.png)

**Comment by yellappam** [comment]
Filtering unsupported objects in advance also reduces load on the system during parallel processing. Currently, unsupported object also serializes using additional work process( in parallel mode ).

**Comment by larshp** [comment]
hmm, yea, note that figuring out which objects are supported by object might be slow, as it creates an object

so something where each object type is only checked once

**Comment by yellappam** [comment]
As part of our custom tool, we are using ZCL_ABAPGIT_OBJECTS=>SUPPORTED_LIST to identify unsupported object types. This method gives the list in less than a second. It executes check once per object type and we can use this for filtering before serialization.

**Comment by yellappam** [comment]
I can create a PULL request if you agree with the solution.

**Comment by larshp** [comment]
yea, lets try it

**Comment by larshp** [comment]
@yellappam did the grouping solve your issue? Over time abapGit will support more objects, so less warnings should hopefully be shown, suggest closing

**Comment by yellappam** [comment]
@larshp - Yes, the grouping has solved my issue.
