### ISSUE TITLE
Handling of inactive code

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4568]
If a program exists only as an inactive version (but no active code at all), then it is currently serialized and you are able to stage the program. 

According to #4567, the such objects shall not be serialized at all.

**Comment by mbtools** [comment]
@yellappam, I could not reproduce the issue using https://github.com/abapGit-tests/PROG (AG 1.105 on 750 SP 19). When I make a change and just save, AG still serialized the active version and there's no diff:

![image](https://user-images.githubusercontent.com/59966492/109397936-7d5e5c00-7907-11eb-9989-f169bba667b8.png)

Can you test with this repo? Test with 1.105?

**Comment by yellappam** [comment]
@mbtools - Below are the steps to replicate the issue with 1.105.

1. Before making changes

![image](https://user-images.githubusercontent.com/29766214/109399062-548ca400-79a5-11eb-91fc-300f62c23227.png)

2. Make a change to the program, save  and **close the window**. Now, refresh AG

![image](https://user-images.githubusercontent.com/29766214/109399093-90276e00-79a5-11eb-8a82-5e807675e1d3.png)
![image](https://user-images.githubusercontent.com/29766214/109399100-a3d2d480-79a5-11eb-8e23-25cc074818b9.png)

AG indicates that program is in inactive state and this looks good.

3. Make second change to the program, save and **close the window**. Now, refresh AG

![image](https://user-images.githubusercontent.com/29766214/109399132-d5e43680-79a5-11eb-8931-29ee1ad2fe4e.png)
![image](https://user-images.githubusercontent.com/29766214/109399146-eb596080-79a5-11eb-9100-d746f1f7ae4c.png)

This time it shows diff and below is the screenshot.
![image](https://user-images.githubusercontent.com/29766214/109399163-01672100-79a6-11eb-84d9-cf883cdcfe70.png)

**Comment by mbtools** [comment]
I tried this and never get a diff. I even tried logging off in between. Still no diff. Hmmmm

Which SAP Basis release and SP do you have?

**Comment by yellappam** [comment]
Basis release : SAP_BASIS 753	0003
ABAP: SAP_ABA	75D	0003

**Comment by yellappam** [comment]
We have another system with below version and will testing the same scenario here if the behavior is different. Will post the results.

SAP_BASIS	750	0015
SAP_ABA	        750	0015

**Comment by yellappam** [comment]
Same behavior in the below version

SAP_BASIS 750 0015
SAP_ABA 750 0015

![image](https://user-images.githubusercontent.com/29766214/109401979-100a0400-79b7-11eb-8f97-4230e19611ae.png)

**Comment by yellappam** [comment]
Another point which might be different. I am using SAP GUI to make the changes instead of Eclipse. Are you using Eclipse?

**Comment by yellappam** [comment]
In the debug mode, this is the code which is reading the contents from program

![image](https://user-images.githubusercontent.com/29766214/109402298-a0494880-79b9-11eb-857c-af16fce91e92.png)

![image](https://user-images.githubusercontent.com/29766214/109402287-8dcf0f00-79b9-11eb-8a17-69cf279a7b5d.png)

**Comment by mbtools** [comment]
this is very strange. i was away from my system and just started AG again and it DID show the diff! Then I restarted AG and the diff was gone again. I made another change (nr.4) and the diff is back:

![image](https://user-images.githubusercontent.com/59966492/109402420-b73d5b80-7923-11eb-9bd0-e7b124350a3d.png)

restarted AG, diff gone:

![image](https://user-images.githubusercontent.com/59966492/109402461-10a58a80-7924-11eb-9f9a-e4f20bfc927d.png)

i will take a break and think about this...

**Comment by mbtools** [comment]
I'm using Sapgui. Same line of code. Read report does not seem to consistently return active code. That's kernel functionality.

**Comment by mbtools** [comment]
we're not the first to find this problem with `READ REPORT`:

https://github.com/abapGit/abapGit/blob/main/src/objects/oo/zcl_abapgit_oo_serializer.clas.abap#L145

Conclusion: `RPY_PROGRAM_READ` can't be trusted to return only active code if there's an inactive version. it's really something SAP must fix since this function is used a lot also by SAP. 

Options:
1. Do nothing
2. Wait for SAP fix
3. Implement workaround in AG (`if active.. call function ... else. read report... state 'A'. endif`, or just use `READ REPORT`)

@larshp ?

**Comment by mbtools** [comment]
AG is probably missing a call to `RS_WORKING_AREA_PREPARE`:

https://help.sap.com/doc/abapdocu_756_index_htm/7.56/en-US/index.htm?file=abapread_report_internal.htm
https://help.sap.com/doc/abapdocu_756_index_htm/7.56/en-US/index.htm?file=abapinsert_report_internal.htm

Suggest refactoring `READ/INSERT/DELETE REPORT` usage into separate class so we can implement consistent and correct handling of the situations where these statements are necessary.

**Comment by mbtools** [comment]
Pointless to wait for SAP fix. I implemented a workaround in #6557 😃
