### ISSUE TITLE
Version check and update for standalone program

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4571]
Checking if a new version is available and providing an option to install it is a common feature in many software packages. It would be nice to offer this feature also for the standalone version:

- Get current version via https://shield.abap.space/version-shield-json/github/abapGit/abapGit/src/zif_abapgit_version.intf.abap/gc_abap_version
- Get current code via https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap

**Comment by larshp** [comment]
wouldnt it be easier for the user just to install the dev version? and easier to maintain

**Comment by mbtools** [comment]
you mean everyone should use the dev version? ;-)

i have no idea what percentage is using standalone vs dev but i guess it's the majority. just a nice to have feature

**Comment by sbcgua** [comment]
It's probably easier to parse the file from the github directly. Also it will not require additional SSL cert

**Comment by albertmink** [comment]
> wouldnt it be easier for the user just to install the dev version? and easier to maintain

Yes and but what if in the ABAP system there is a forked abapGit? (And it is not my fork)

**Comment by mbtools** [comment]
Other improvements pretty much take care of this:
https://github.com/abapGit/abapGit/pull/5739, https://github.com/abapGit/abapGit/issues/5784 (https://github.com/abapGit/abapGit/pull/5793)
