### ISSUE TITLE
TYPE: Inactive version serialized for type-pools

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4585]
https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_type.clas.abap#L95

Only the active version should be serialized.

**Comment by yellappam** [comment]
When a new type-pools is created, SAP creates active version by default. SY-SUBRC is always set to 0 for the first function module call as there is always an active version hence, second function will never be called. Anyhow, it is good to delete the second call as we don't need any inactive version, if any.

![image](https://user-images.githubusercontent.com/29766214/109719844-1d6cfb80-7c0e-11eb-9f76-0cab16795818.png)

![image](https://user-images.githubusercontent.com/29766214/109719512-a0418680-7c0d-11eb-8111-486386b3c431.png)

![image](https://user-images.githubusercontent.com/29766214/109719633-cd8e3480-7c0d-11eb-8f30-b5fb56fb518b.png)

**Comment by mbtools** [comment]
yeah, i saw it in debugging too. we can remove the second call
