### ISSUE TITLE
LOG: Return code for parallel serializer

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4586]
If parallel serializer raises exceptions, `sy-subrc` is appended to the log messages:

![image](https://user-images.githubusercontent.com/59966492/109540267-3b145680-7a90-11eb-93ac-ec181db0c003.png)

I suggest removing the return code. If you need to know, put a break-point at 
https://github.com/abapGit/abapGit/blob/main/src/objects/core/zcl_abapgit_serialize.clas.abap#L353

**Comment by larshp** [comment]
note that log refactoring is ongoing, so wait a bit starting this task, https://github.com/abapGit/abapGit/pull/4590
