### ISSUE TITLE
UI occasionally does not render

### ISSUE THREAD

**Issue by admiralmaggie** [abapGit/abapGit#4588]
Hello,
It appears that explorer occasionally does not render the HTML UI and shows a blank page. Any pointers on how to troubleshoot this? Screen isn't hung. I can back out without an issue. I can also right click and view the IE context menu.

Running SAPGUI 7.60 Patch 8.

Cheers,
Aaron

![image](https://user-images.githubusercontent.com/11258981/109553496-1b395e80-7aa1-11eb-873a-3e2ddc44e273.png)

**Comment by mbtools** [comment]
Right-click on the black > view source. Was there any HTML returned? 

Which GUI theme, which abapGit theme are you using? Try using a different combination.

**Comment by admiralmaggie** [comment]
It does return the code. If I select all (CTRL+A) and copy (CTRL+C), I can paste the UI elements in notepad so it does render but something weird is happening with the display. I'm using the default theme with abapGit. Good idea about switching themes. I will try that and report back...

**Comment by admiralmaggie** [comment]
Seems like this is just me since no one else is having problems. I'm closing the issue.
