### ISSUE TITLE
build failed with abapLint error in zcx_abapgit_exception

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#4602]
./src/zcx_abapgit_exception.clas.testclasses.abap[48, 9] - Attribute or constant "private_method" not found in "cx_sy_dyn_call_illegal_method" (check_syntax) [E]

Didn't touch zcx_abapgit_exception

https://github.com/christianguenter2/abapGit/runs/2039029215?check_suite_focus=true
![image](https://user-images.githubusercontent.com/17437789/110105828-2940f500-7da9-11eb-8d0a-a78fcf20656b.png)

**Comment by larshp** [comment]
try again, https://github.com/abaplint/deps/pull/44

**Comment by christianguenter2** [comment]
Well that was fast :-) Works again.
