### ISSUE TITLE
Object types supported byt abapGit-plugins are reported as unsupported 

### ISSUE THREAD

**Issue by jfilak** [abapGit/abapGit#4610]
The unsupported object grouping is the most probably the root cause as **zcl_abapgit_objects=>supported_list** returns only the list of natively supported objects:
https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_objects.clas.abap#L1277

Can I change it to include all supported objects?

**Comment by larshp** [comment]
yea, think the value should be `abap_false` which is the default value for the parameter

**Comment by mbtools** [comment]
`supported_list` should have an input parameter `iv_native_only` (default `abap_true` to be compatible) that's passed on to `is_supported`. then check which places should call `supported_list` with `iv_native_only = abap_false`

**Comment by jfilak** [comment]
```
$ grep -r supported_list src/
src/ui/zcl_abapgit_gui_page_debuginfo.clas.abap:    lt_types = zcl_abapgit_objects=>supported_list( ).
src/objects/zcl_abapgit_objects.clas.abap:    CLASS-METHODS supported_list
src/objects/zcl_abapgit_objects.clas.abap:  METHOD supported_list.
src/objects/core/zcl_abapgit_serialize.clas.abap:    lt_supported_types = zcl_abapgit_objects=>supported_list( ).
src/objects/zcl_abapgit_objects.clas.testclasses.abap:    lt_types = zcl_abapgit_objects=>supported_list( ).
```

All occurences should get *all* supported objects.
We would have problem only with 3rd party code relying on the having only **native** objects.

**Comment by mbtools** [comment]
makes sense
