### ISSUE TITLE
running migrations over RFC causes errors because of DynPro dialogs

### ISSUE THREAD

**Issue by jfilak** [abapGit/abapGit#4612]
I need to create the APACK interface in the dark mode.

I am afraid that the dynpro dialog for the interface is there on purpose, right? Otherwise, I would love to apply the following patch 

```diff
     CALL FUNCTION 'SEO_INTERFACE_CREATE_COMPLETE'
       EXPORTING
         devclass        = '$TMP'
+        suppress_dialog = 'X'
       CHANGING
         interface       = ls_interface_properties
       EXCEPTIONS
```

Or I can make it configurable. However, the solution would be a little bit complicated becase the method is called inderectly (*zcl_abapgit_migrations=>run( )*).

**Comment by mbtools** [comment]
Current APACK is a pain and doesn't work for example with namespaced repos at all. I'm planning on a replacement with similar data in .abapgit.xml. 

I'm ok with suppress_dialog = 'X' (need to check on 702 compatibility with there params).

**Comment by larshp** [comment]
yea, all dialogs should be suppressed where possible

**Comment by larshp** [comment]
lemme do this, note that the parameter does not exist in 702, so something like the below will work

![image](https://user-images.githubusercontent.com/5888506/110476230-07fe4280-80e2-11eb-93a1-8928d9a59f2d.png)

**Comment by larshp** [comment]
merged, closing
