### ISSUE TITLE
Problems when staging objects with spaces in filename

### ISSUE THREAD

**Issue by mkaesemann** [abapGit/abapGit#4613]
We have recently started working with OData services and when we have services with generated annotation models, we get filenames with spaces (e.g. objects of type IWVB, IWSV or IWMO, but also some SICF IDs) that can't be staged.

The error "Unable to stage XY. If the filename contains spaces, this is a known issue." is trioggered in `STAGE_SELECTED` of `ZCL_ABAPGIT_GUI_PAGE_STAGE` and is caused by the fact that the system can't find the filename extracted from <ls_item> in ms_files-status.

Since the referenced issue #3073 is closed and had a different source, I looked into this and found that the problem is caused by the fact, that the filename in <ls_item> conatins NO-BREAK spaces (`U+00A0`), while `ms_status-files` uses regular spaces.
The NO-BREAK spaces are then replaced by the `cl_http_utility=>unescape_url( escaped = ev_filename )` call in `SPLIT_FILE_LOCATION` of `ZCL_ABAPGIT_PATH`, which doesn't help.

I've added a replace statement to `SPLIT_FILE_LOCATION` of `ZCL_ABAPGIT_PATH`, which solves the issue:
```abap
    "Replace No-Break Spaces, because the real filename may contain normal spaces
    REPLACE ALL OCCURRENCES OF REGEX '[[:space:]]'
      IN ev_filename WITH ` ` IN CHARACTER MODE
      IGNORING CASE.
```

**Comment by mbtools** [comment]
There are only two places for the mapping between objects and filenames:
`ZCL_ABAPGIT_OBJECTS_FILES->FILENAMES' and 'ZCL_ABAPGIT_FILE_STATUS->IDENTIFY_OBJECT`

The replace statement should be added to the first method to escape the no-break space with %A0. No other changes should be necessary

**Comment by mbtools** [comment]
Note: regular spaces in filenames should be fine (test with https://github.com/abapGit-tests/SICF).

**Comment by mbtools** [comment]
We don't have test cases for IWMO and IWSV. If you have a minute, please add them to https://github.com/abapGit-tests/IWMO and https://github.com/abapGit-tests/IWSV. Thanks :-)

**Comment by mkaesemann** [comment]
I did find `ZCL_ABAPGIT_OBJECTS_FILES->FILENAMES`, but that one is used to create the filenames in ms_status-file, where there are no no-break spaces. The no-break spaces only appear in the filename that is split to retrieve path and filename.
I'll have a look at `ZCL_ABAPGIT_FILE_STATUS->IDENTIFY_OBJECT` if time permits.

**Comment by mbtools** [comment]
I see. The issues might to be in the processing of the form data and should be fixed there.

Please check if `ZCL_ABAPGIT_HTML_ACTION_UTILS->PARSE_FIELDS` is returning the filenames properly.  I always thought it should be replaced by standard `cl_http_utility=>string_to_fields` so this might be a test case to show why.

**Comment by mbtools** [comment]
@mkaesemann Michael, could you please check if adding the following line fixes the problem? It's more general than just patching `zcl_abapgit_path`.

```abap
      REPLACE ALL OCCURRENCES OF ` ` IN lv_obj_name WITH '%20'.
```

https://github.com/abapGit/abapGit/blob/main/src/objects/core/zcl_abapgit_objects_files.clas.abap#L240

**Comment by larshp** [comment]
guess this issue can be closed?

**Comment by fooxbr11** [comment]
Ok, thanks @larshp, i create it.

#7267
