### ISSUE TITLE
Login language

### ISSUE THREAD

**Issue by nomssi** [abapGit/abapGit#4622]
While trying to upload an offline repository I got:

Current login language 'DE' does not match main language 'EN'. Select 'Advanced' > 'Open in Main Language' 

but I could not find "Open in Main Language" in the menu. I can vaguely recall it existing many iterations ago, or I am missing something.

best regards,
JNN

**Comment by mbtools** [comment]
`ZABAPGIT` tcode will automatically exist for the dev version. If you are using the stand-alone version, you have to create a tcode for program `ZABAPGIT_STANDALONE` yourself.

**Comment by nomssi** [comment]
Thank you all for the feedback.
