### ISSUE TITLE
DDLS: deserialization crashes with a runtime error because of dependencies

### ISSUE THREAD

**Issue by filak-sap** [abapGit/abapGit#4624]
As far as I know, the serialization first deletes object and then re-creates it. This approach most probably does not work for CDS because the runtime ensures that "database" is always consistent, so it's not possible to delete a CDS view if there are dependent views.

**Symptoms**

```
An exception has occurred in class "CX_DD_DDL_DELETE". This exception was not 
caught 
in procedure "ZIF_ABAPGIT_OBJECT~DESERIALIZE" "(METHOD)" or propagated by a 
RAISING clause. 
Since the caller of the procedure could not have anticipated this 
exception, the current program was terminated. 
The reason for the exception occurring was: 
Object could not be deleted
```

**CL_DD_DDL_HANDLER=>IF_DD_DDL_HANDLER~DELETE**

```
    ...

    if syst-subrc <> 0 or rc > 4. "RC may also be caused by dependently
      "activated objects.
      read table deltab into delwa index 1.
      if delwa-errflag = 'X'.
        "DDLS039: Ddl Source could not be deleted
        perform stdo_smi1 in program radbtout using prid 'E' 'DDLS039' name.
        set_error_mess_'039' 'E' name '' '' ''.
        create object ex
          exporting
            textid = cx_dd_ddl_delete=>deletion_error.
        ex->set_error( error = error ).
        raise exception ex.
      endif.
    endif.

    ...
```

**Comment by filak-sap** [comment]
Pulling the same repository on a different system didn't cause any error ...

**Comment by mbtools** [comment]
it tries to delete the CDS view only if something else went wrong:
https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_ddls.clas.abap#L266

but then it dumped so it didn't get to raise the error in AG. putting a bp on catch cx_root and checking lx_error should give insight.

**Comment by yellappam** [comment]
I have had same dump on S/4HANA 1909 version with AG 1.104 but, didn't check the error message :(. I think, it was due to dependencies.

**Comment by jfilak** [comment]
@larshp Could you please create a new & empty repository named "DDLS_dependency" in the organization https://github.com/abapGit-tests/ - I have found a volunteer (@kegyescsaba) who is willing to create the minimal example demostrating the problem.

**Comment by larshp** [comment]
done,

https://github.com/abapGit-tests/DDLS_dependency

thanks

**Comment by juriadasek** [comment]
I have a similar problem with this repo: https://github.com/juriadasek/TEST_JA_CYCLIC 
It contains a small example of CDS views which I cannot pull nor activate using AbapGit, because there is a cyclic dependency.

**Comment by larshp** [comment]
@juriadasek thanks, I've created https://github.com/abapGit-tests/DDLS_cycle can you help opening a pull request with your example to that repository

we'd like to keep track of all the examples for future reference and testing

**Comment by kegyescsaba** [comment]
Hi @larshp, I have created a pull request for the DDLS dependency. I have added a minimal CDS view structure, there are two sets of CDS views that are connected with an association.
Could you open a new branch in the DDLS repository? Errors are raised if a field is changed that is reached through an association. I would upload these changes into the new branch.

**Comment by larshp** [comment]
@kegyescsaba I've added you as a collaborator in the repository, if you accept the invite you should've have access to create the branch 😄

**Comment by kegyescsaba** [comment]
@larshp Thank you! I have created the new branch, renameField, and I have merged my changes into that branch.
In both branches we have almost the same CDS stucture, but the name of one field is changed. In the main it's NameText, in the other branch it's ItemNameText. 
When you switch branches and try to pull there will be activation errors, because a field has been renamed which is access in the root entity(ZCSK_R_PRODUCTSTP), through an association.
I think this is a scenario which we have ran into during active development. 
Should I provide more details about the problem or this scenario?

**Comment by jfilak** [comment]
**Idea:**
I don't think we can parse the CDS views and detect the dependencies. Also a project should not probably contain hundreds of CDS views which must be created in the right order. So, I think of adding a new config option to .abapgit.xml which would contain manually maintained order of activation (I came from the C/C++ world where you usually define build order manually, so I don't see any problem in that).

**Comment by mbtools** [comment]
how does an ordered list overcome the problem when it's a cyclic dependency?

**Comment by jfilak** [comment]
> how does an ordered list overcome the problem when it's a cyclic dependency?

Eh, correct, not the cycle but at least renamed fields.

**Comment by mbtools** [comment]
Closing in favor of https://github.com/abapGit/abapGit/issues/5524
