### ISSUE TITLE
TADIR - read_single, no exception thrown

### ISSUE THREAD

**Issue by g-back** [abapGit/abapGit#4625]
https://github.com/abapGit/abapGit/blob/da43c34fc4f91ae8a9446f74d4df6ba7905085d5/src/objects/core/zcl_abapgit_tadir.clas.abap#L429-L438

This method has a `RAISING` in its signature  but does not throw an exception if the object is not found.
Either raise the exception when not found or remove exception from signature to make it clearer for the caller.

**Comment by mbtools** [comment]
there used to be code related to SICF. you can remove the exception and the comment
