### ISSUE TITLE
Search help popup - does not always return correct value

### ISSUE THREAD

**Issue by g-back** [abapGit/abapGit#4626]
Example `TADIR-OBJECT`:
When selecting a value two values are returned:
![image](https://user-images.githubusercontent.com/27279305/110771810-37848a80-825b-11eb-98bc-7e133ec0b79d.png)

Suggest to first try to read the exact fieldname, and if not found the first value instead of always selecting the first entry in the return table:
https://github.com/abapGit/abapGit/blob/d7f74bd49c28779fec09148851fffac064e14f82/src/ui/zcl_abapgit_popups.clas.abap#L891-L895

**Comment by mbtools** [comment]
indeed, search help can return multiple fields. your logic sound good
