### ISSUE TITLE
Display commit status in header

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4630]
It's Easter soon, maybe the bunny brings some goodies:

I would love to see the status of the last commit (green check or red x) next to the commit id in abapGit (like on Github):

![image](https://user-images.githubusercontent.com/59966492/110823655-9dd8cf80-8292-11eb-9a38-ff11df328850.png)

![image](https://user-images.githubusercontent.com/59966492/110824191-1dff3500-8293-11eb-931e-0176e0cbcfa3.png)

...and of course if I click on the icon it takes me right to the log.

a user-exit should be possible

**Comment by larshp** [comment]
a user exit would be okay

for abapGit there is no need to show it, as its always green, its a prerequisite to merge to the default branch

**Comment by larshp** [comment]
btw, it might be possible to use https://github.com/abap-openapi/generated-github to get the status

**Comment by sbcgua** [comment]
don't forget about anonymous API calls limit ... it is quite small

**Comment by mbtools** [comment]
thanks to the new `ZIF_ABAPGIT_EXIT~WALL_MESSAGE_REPO`:

![image](https://user-images.githubusercontent.com/59966492/113426008-1d117d00-93d3-11eb-9aec-855361425729.png)

You can click on the icon and jump right to the check results 😄 

https://gist.github.com/mbtools/5e760ba6d0a37e8457651a068a0484a5
