### ISSUE TITLE
Transport to zip - Error finding super package 

### ISSUE THREAD

**Issue by aakash-sap** [abapGit/abapGit#4643]
Is it not possible to transport objects to ZIP from TR which contains objects from different package?

**Comment by mbtools** [comment]
no

`zcl_abapgit_transport=>find_top_package`:
* assumption: all objects in transport share a common super package

the export to zip simulates serializing a repo. therefore, all objects must belong to a package (or sub-packages of it).

**Comment by larshp** [comment]
a abapGit repository contains settings like the folder logic, which influences how the zip is built

it very much depends on what you want to use the resulting zip for, you can quite easily build a small program that implements some custom logic

alternatively, add a super package and a repo for that

**Comment by larshp** [comment]
@aakash-sap did above help?

**Comment by larshp** [comment]
closing, no reply
