### ISSUE TITLE
JS init error during staging

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#4647]
AG :  1.104.0
SAP_BASIS	750	0015
SAP_ABA	750	0015

Getting below message during stage logic randomly. Not sure how to replicate the issue consistently. Is this issue fixed in the latest version?

![image](https://user-images.githubusercontent.com/29766214/111395274-54203700-8721-11eb-8015-d3c747ed1f42.png)

**Comment by larshp** [comment]
are you using sap gui on windows or java?

**Comment by yellappam** [comment]
> are you using sap gui on windows or java?

sap gui on windows

**Comment by larshp** [comment]
hmm, I have not seen that error before

**Comment by yellappam** [comment]
I have received the error message a couple of times but don't know exactly how to replicate it. If I see any common pattern, I will post it here.

**Comment by mbtools** [comment]
kind of a known issues. `zcl_abapgit_html_action_utils` is all custom to process form/post data and has some flaws. this becomes evident if the post data becomes larger and/or has characters that need escaping/unescaping.

See https://github.com/abapGit/abapGit/issues/2448 for examples with the commit page. 

Here's a test prg that shows how parsing is not correct. Most of the class should be replaced with standard `cl_http_utility` (for example `string_to_fields`).

**Comment by mbtools** [comment]
the concern was noted in the code `* do not use cl_http_utility as it does strange things with the encoding` but I don't think this was actually proven to be true.

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/pull/4615 might be related since it's also dealing imho with characters (like `space`) that are not escaped properly.

**Comment by AndreaBorgia-Abo** [comment]
FWIW, I'm seeing the same issue:
![immagine](https://user-images.githubusercontent.com/25269970/145206913-9df26411-5b48-4b55-8c4a-f83739124699.png)

AG: 1.113.0
GUI: Java 7.70rev4
SAP: 7.52SP04 demo

**Comment by mbtools** [comment]
If this is still reproducible, please follow the instructions here to pinpoint where it goes wrong in the JavaScript:
https://docs.abapgit.org/development/debugging.html

**Comment by AndreaBorgia-Abo** [comment]
Hopefully @yellappam will be able to reproduce it on Windows!
Now with AG 1.114.0 I can reproduce it only on Linux with the JavaGUI (7.70rev5 now) but this is unsupported so I won't waste everybody's time.

**Comment by AndreaBorgia-Abo** [comment]
@yellappam I used my own repo but the issue shows up also when using abap2xlsx, only with the JavaGUI however.

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/pull/5508 has fixed a few things related to escaping special characters, for example in links. Is this still an issue?

**Comment by mbtools** [comment]
Yes, please check. "JS init" errors are rare but we still want to fix them :-)

**Comment by AndreaBorgia-Abo** [comment]
> Yes, please check. "JS init" errors are rare but we still want to fix them :-)

Ok, with "SAP GUI for Java 7.80 beta 16" I can still see the JS error.
aG is 1.116.0 (dev version) and backend is the usual NPL demo.

**Comment by mbtools** [comment]
I was able to reproduce it with SAP GUI for Java 7.80 rev 1

It happens on the Diff/Patch page and is caused by a JS call to `restoreScrollPosition();`. The method uses `window.sessionStorage` which raises an exception in Java GUI. Fix coming up

**Comment by mbtools** [comment]
@AndreaBorgia-Abo fix for Diff/Patch is in #5901 

@yellappam Stage isn't using scroll-position so the fix doesn't apply if you have a reproducible case, please reopen or better open a new issue. TY

**Comment by AndreaBorgia-Abo** [comment]
Will try and report back during the weekend, thank you :)

**Comment by yellappam** [comment]
> @AndreaBorgia-Abo fix for Diff/Patch is in #5901
> 
> @yellappam Stage isn't using scroll-position so the fix doesn't apply. if you have a reproducible case, please reopen or better open a new issue. TY

I haven't had the issue for a long time. I will close and open new if encounter it again.
