### ISSUE TITLE
Data: Error when trying to commit

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4650]
Files for one table look ok but "unpack not ok" error when trying to commit to repo

```json
/data//mbtools/cmds.config.json 
{
  "name": "/MBTOOLS/CMDS",
  "type": "TABU",
  "where": []
}
```
```json
/data//mbtools/cmds.tabu.json 
[
  {
    "command": "CALC",
    "shortcut": "=",
    "clsname": "/MBTOOLS/CL_COMMAND__CALC",
    "description": "Calculate"
  },
  { 
    "...": "..."
  }
]
```

```abap
ZCL_ABAPGIT_GIT_TRANSPORT->RECEIVE_PACK 
lv_line = `66e5c990075279e729a73f48a0d0be119b90ec1b ccb967b390c61924a761c676aec68f522b1d8614 refs/heads/main# report-status#`

lv_string = '0029#0024unpack index-pack abnormal exit#001eng refs/heads/main failed#00000000'
```

![image](https://user-images.githubusercontent.com/59966492/111676946-fd008c00-881e-11eb-9345-30856d31d750.png)

**Comment by larshp** [comment]
I guess its due to the namespaces which are not escaped yet, `/data//mbtools/cmds.tabu.json`

**Comment by mbtools** [comment]
Oh right. Too many / in the file names. Will fix it and work on deserialize since it would come in handy for my repos now.
