### ISSUE TITLE
SRVC: Service Consumption Model

### ISSUE THREAD

**Issue by xvercruysse** [abapGit/abapGit#4668]
Hi, when transporting an RAP application from one ABAP Cloud system to another, I noticed that the Service Consumption Model objects are not yet supported in abapGit.

![image](https://user-images.githubusercontent.com/13088771/112464570-f369ad80-8d63-11eb-940d-94d92cd0cc27.png)

**Comment by mbtools** [comment]
maybe you can help test SRVD - Service Definition https://github.com/abapGit/abapGit/pull/4529 ?

and maybe you are able to use that (`zcl_abapgit_object_srvd`) as a template for SRVC? pull requests are welcome

**Comment by larshp** [comment]
FYI @ThomasPloski

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.
