### ISSUE TITLE
Namespace does not exist message for non existing namespace

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4670]
I get the warning "Namespace /ABC/#DEF/ does not exist. Create it in transaction SE03" (namespace anonymized). It's correct it doesn't exist but it also shouldn't as there are no objects in it nor is this a valid namespace.

The cause seems to be a DOCT object which is wrongly analyzed by the regular expression.

OBJ_TYPE: DOCT
OBJ_NAME: /ABC/DEF/DR_VERIFY
PATH: /src/#abc#something/
FILENAME: #abc#def#dr_verify.doct.xml

https://github.com/abapGit/abapGit/blob/8f0532d01576a46e93f2e1e7da7c062b56e417df/src/objects/core/zcl_abapgit_file_status.clas.abap#L497

**Comment by mbtools** [comment]
that kind of object name might cause other issues since it certainly looks like a namespaced object (although in this case it has more than 2x / ). always surprises with SAP...

we could exclude this particular object type from the loop. or do you think a more general solution is necessary?

**Comment by flaiker** [comment]
I would just change it to `#([a-zA-Z0-9]+)#.*\..*\.xml`, no?

**Comment by mbtools** [comment]
that would work (assuming /ABC/ is really namespace in this case and not part of the object name).

RS_NAME_SPLIT_NAMESPACE doens't like this object name though... odd

![image](https://user-images.githubusercontent.com/59966492/112503373-25423a80-8d8b-11eb-9d56-4d851be805b2.png)

**Comment by mbtools** [comment]
let's just change the regex

**Comment by flaiker** [comment]
I tried RS_NAME_SPLIT_NAMESPACE with the actual name which didn't work for me either. SE61 can edit the object just fine though or even create new ones with this naming scheme. We have 37 DOCT objects in the system matching this pattern and 160 R3TR objects with `/*/*/*` names so I think we should account for it.

**Comment by mbtools** [comment]
the function is used in `ZCL_ABAPGIT_TADIR->ADD_NAMESPACES` but it won't cause errors for the DOCT objects. it just ignore those. changing the regex should be ok

**Comment by mbtools** [comment]
#4671
