### ISSUE TITLE
PDTS: Unit tests fails if experimental features are not enabled

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#4678]
![image](https://user-images.githubusercontent.com/17437789/112715596-68aebd00-8ee1-11eb-88bd-6bfe08f35c00.png)

**Comment by larshp** [comment]
I think this unit test is only executed if "experimental features" are enabled?

**Comment by christianguenter2** [comment]
Yes, that's right. But it shouldn't fail if they are not enabled?
