### ISSUE TITLE
CX_RS_* is unknown

### ISSUE THREAD

**Issue by lucasborin** [abapGit/abapGit#4692]
![image](https://user-images.githubusercontent.com/5233413/114062833-5718ce00-986e-11eb-8d0a-e16b52644df3.png)

From: https://raw.githubusercontent.com/abapGit/build/main/zabapgit.abap

To: SAP_BASIS	756/0001

**Comment by lucasborin** [comment]
`cx_rs_cancelled`, `cx_rs_existing`, and `cx_rs_not_found`

**Comment by larshp** [comment]
object type = ODSO

**Comment by mbtools** [comment]
I suspect your system does not contain SAP_BW. There's probably more that needs to be changed. Try to remove the complete class 'zcl_abapgit_object_odso' (definition and implementation) from the program.

**Comment by lucasborin** [comment]
No, it does not. To solve the issue, I replaced these three catches with `cx_root` temporarily. 

By the way, there is a dynamic call to an `ODSO` class a few lines above.
I am not sure if it is feasible, but, can we do the same with exceptions?

**Comment by mbtools** [comment]
not worth trying to make this more fancy than cx_root. #4694 will take care of it.
