### ISSUE TITLE
Generic serializer does not clear user/date fields

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4696]
Object types based on `ZCL_ABAPGIT_OBJECTS_GENERIC` contain user names and date/timestamps in the serialized output. 

Example (see first diff for `IWMO`):

![image](https://user-images.githubusercontent.com/59966492/114432180-afc6ce80-9bc0-11eb-85ee-5bb471eaf6b1.png)

Suggestion: Definition "clear/fill" rules and pass to generic class

Rule:

```abap
TYPES:
  BEGIN OF ty_rule,
    tabname TYPE tabname,
    fieldname TYPE fieldname,
    clear_rule TYPE enum,
    fill_rule TYPE enum,
  END OF ty_rule.
```

Rule Types:
- clear only (no fill)
- clear and fill with sy-uname
- clear and fill with sy-datum
- clear and fill with sy-uzeit
- clear and fill with timestamp

**Comment by yellappam** [comment]
@mbtools  - I don't find below enum in my system. Are you referring to [enumerations](https://blogs.sap.com/2017/08/15/enumerations-in-abap/)?

![image](https://user-images.githubusercontent.com/29766214/156949192-c80c764d-10a1-4cec-91be-770a0dbbe734.png)

**Comment by mbtools** [comment]
Closed by https://github.com/abapGit/abapGit/issues/5391, #5519, #5520
