### ISSUE TITLE
Export namespaced packages to ZIP

### ISSUE THREAD

**Issue by AZn5ReD** [abapGit/abapGit#4700]
I can't export any namespaced packages to ZIP (containing '/').
The export of packages without '/' in the name is working fine though.
The error message I get is : "Package XXX doesn't exist".

![image](https://user-images.githubusercontent.com/1781837/114694971-5f17b880-9d1b-11eb-8f8b-6e083afac2eb.png)

**Comment by larshp** [comment]
thanks 👍 

looks like there is something wrong in the escaping of package names

as a temporary workaround, just adjust the package name in the debugger 😄

**Comment by AZn5ReD** [comment]
Yeah, I changed the package name in `iv_package` with the '/' characters and it works :

![image](https://user-images.githubusercontent.com/1781837/114697643-74421680-9d1e-11eb-95a7-64db79a36d98.png)

Probably the `REPLACE ALL OCCURRENCES OF '/' IN iv_package WITH '#'.` line to remove ? 🤔 

Thanks ! 😄

**Comment by larshp** [comment]
@AZn5ReD try again, latest version, fixed by @g-back thanks 👍
