### ISSUE TITLE
Unit tests for zcl_abapgit_persist_settings clear settings

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#4709]
Title says it all: If I run these unit tests then the global settings are cleared and overwritten with a single value:
```
  <SETTINGS>
    <PROXY_URL>http://proxy</PROXY_URL>
   </SETTINGS>
```

**Comment by mbtools** [comment]
these test only run when "critical unit test" setting is enabled. 

![image](https://user-images.githubusercontent.com/59966492/117266365-7860e000-ae55-11eb-8b93-4f8d8d5a4720.png)

however, if you allow the tests to run, they fail:

![image](https://user-images.githubusercontent.com/59966492/117266297-667f3d00-ae55-11eb-9180-560ce97426ff.png)

it appears the tests are from a time before settings where stored as XML and are therefore not relevant anymore. I will delete them.
