### ISSUE TITLE
enable/allow list of objects - opposite of .gitignore

### ISSUE THREAD

**Issue by jfilak** [abapGit/abapGit#4713]
Did you ever consider having a positive list of objects you want to version? I have to deal with a package which has 13k objects and we need to version only 7 of them.

The positive list should speed up processing of the repo. Currently, it takes 3 minutest open abapgit with that package.

**Comment by jfilak** [comment]
I think it would be enough to not serialize objects that were not added to the repo and just exists in the package.
Also, keeping these objects on the bottom of object list would help too.

**Comment by larshp** [comment]
Hi,
As you know, the right thing is to move the objects to a specific package.

Anyhow, I suggest using https://docs.abapgit.org/ref-exits.html#change_tadir as a workaround, it can be used to simulate different TADIR contents. And add a wall message to tell the user that its magic, https://docs.abapgit.org/ref-exits.html#wall_message_repo 🧙

**Comment by jfilak** [comment]
Hmm, chaging package assignment is not possible - those things are much older than me. The user exit does not look bad. Thank you for the hints.
