### ISSUE TITLE
Replace GET_R3TR_OBJECT_FROM_LIMU_OBJ

### ISSUE THREAD

**Issue by vonglan** [abapGit/abapGit#4715]
I noticed (in my own project) that this SAP function module does not behave as expected. Especially, for some subobject types, it does not return the main object, but the development class:

- DTED
- DOMD
- TABT
- MESS
- SOTT

I do not know what the effect is in ABAPGit (where it is used in ZCL_ABAPGIT_TRANSPORT->RESOLVE), but I suspect that it can lead to unwanted effects.
A good replacement seems to be function TR_CHECK_TYPE (just using parameters wi_e071 and we_tadir).

**Comment by mbtools** [comment]
This is part of the "Transport to Branch" feature. The intention is to derive a list of objects from the transport entries which might be object parts (LIMU). Agree, the function should be replaced. Feel free to submit a pull request

**Comment by larshp** [comment]
The side effects in core abapGit is limited, transport to branch is an isolated feature

**Comment by vonglan** [comment]
Hi, thanks for the encouragement. I have no experience with Pull Requests yet. And I use ABAPGit mainly with ZIP so far, because of firewall problems etc. So, maybe it is better if someone else does the change. (On the other hand, I wouldn't mind some coaching in these topics.)

**Comment by larshp** [comment]
feel free to join the slack, https://abapgit-slackinviter.herokuapp.com (its open to everyone) and we will guide you through it

basically:
1: download and install the latest abapGit via zip
2: perform the updates in the system
3: download to zip
4: fork abapGit, https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
5: clone the fork via command line git to local pc
6: unzip the files and update the cloned files
7: commit the changes to the fork
8: open a pull request, https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by vonglan** [comment]
Ok, thanks. I am confident I can do that.
How about testing? I don't know the "transport to branch" feature. I could just ensure that locally (in the method) the new code works identical (except for the shortcomings) to the old code.

**Comment by larshp** [comment]
test it locally first, someone will also take a look when the PR is opened, and review the changes

**Comment by vonglan** [comment]
I created the pull request.

**Comment by vonglan** [comment]
... but forgot to copy the DATA declarations, sorry.
