### ISSUE TITLE
Clean-up after adding "Remote Settings"

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4718]
The following items are replaced by the "Remote Settings" (#4705) and should be changed

- [x] Branch > Switch to PR
remove menu item
- [x] Advanced > Checkout commit
remove menu item
- [x] Advanced > Make Offline / Online
remove menu items and popups
- [x] Advanced > Change Remote
remove menu item and popup

- [x] To reach "Remote Settings" more easily, I suggest to add an "Edit" icon behind the URL

![image](https://user-images.githubusercontent.com/59966492/115986514-d1588a80-a5b0-11eb-9992-d89efb646fa6.png) ![image](https://user-images.githubusercontent.com/59966492/115986412-57280600-a5b0-11eb-960b-7002aeea4229.png)

**Comment by sbcgua** [comment]
Good idea with edit icon

> Advanced > Change Remote: remove menu item and popup

Did you mean "Add item" ?

**Comment by mbtools** [comment]
No. Do we still need the menu item if we have the one-click edit icon?

**Comment by sbcgua** [comment]
That's about toolbar and menu duplication ...
But in this particular case, maybe it is OK to remove, because the remote setting **is** accessible from 2 places, so I think you're right, we can remove that item too.

**Comment by g-back** [comment]
I can do the removal parts @mbtools - unless you've already started 🙂
