### ISSUE TITLE
Limit size of branch overview

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#4719]
The abapGit repo's branch overview has been struggling for some time but now it has reached the size where it dumps with `STRING_LENGTH_TOO_LARGE`
Suggest limiting the size, along the lines of `git log -100`

**Comment by larshp** [comment]
yea 👍

**Comment by pokrakam** [comment]
Hmm, was hoping for a quick fix but the whole branch handling and display logic falls apart. No coincidence that there are several "todo" and "refactoring" comments in there, so I guess fair enough. 
I have a partial solution which shortens simpler repos but dumps for abapGit. Won't be able to solve all of it for time reasons today and the refactoring todo will probably have to remain.

**Comment by pokrakam** [comment]
I have learnt why this hasn't been done yet.. 
Several attempts to come up with at least a temporary hack just to 'make it work' have only had limited success on smaller repos. The comment that best sums it up is `"TODO refactor`

The fundamental issue is that the linear logic relies on a single source, in multiple places it uses sorting to get the initial commit to the top/bottom. I could get it working by cutting the fetched commit list when the cut is at a point where only one sequence exists:
```
      |       o--o---o--o
      |      /      /    \
a--o--|--b--o--o---o------o---o~Main
      |
```
The original 'Init' commit is `a` and cutting the history results in `b` becoming the first commit. That works in `pokrakam/4719`

But it falls apart when you have multiple origin and multiple ending commits.
```
               |
        o---o--|----b      o--o~Branch1
       /       |     \    /
  o---o--o-----|--c---o--o--o
 /      /      |     /       \
a------o-----o-|----d---------o~Main
               |
```
Now we have a history that starts with `b`, `c` and `d`. The branching diagram wasn't designed for that, and the sort logic falls apart. 

Another 'hack' approach is to follow the commit chain after n commits to find a single strand and cut it there. IMHO that's just another band-aid hack, but it can work. 

Long term this needs to be refactored.

**Comment by larshp** [comment]
yea, well, probably just removed, there is better tooling than abapgit to show this

**Comment by mbtools** [comment]
It's really a feature for the remote side which has all the git history. I don't see any use for it on the ABAP side. +1 for removing it.

**Comment by pokrakam** [comment]
I personally don't use it, though I think the graph display is neat.
But sometimes I click on Branch Overview because I think it's a list of branches (as per screenshot above), and my laptop starts warming the room up. 
Was hoping there would be something simple like a `git log` that could be parsed. 
![image](https://user-images.githubusercontent.com/25539927/116109183-77d58600-a6ac-11eb-9621-2f50a3ead703.png)

**Comment by pokrakam** [comment]
It's all by design of course `" assumption: all branches are created from master, todo`
