### ISSUE TITLE
user exit: event handler

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4722]
abapGit is missing an easy way to extend it with new features that are *not* suitable for abapGit itself. For example, it would be nice to link to a new page from a wall message (#4653). Another use case would be redirecting menu items to a custom page rather than standard abapGit, for example using a company-specific solution to replace "Advanced > Run Code Inspector".

Suggestion: Add a user-exit to the event handler

```abap
CLASS zcl_abapgit_gui_router
 METHOD zif_abapgit_gui_event_handler~on_event.

    " Custom event handling
    rs_handled = zcl_abapgit_exit=>get_instance( )->on_event( ii_event ).
```

In the exit, you have the option to react to any abapGit UI event. This could be a new event like a "sapevent:my_action" link in a wall message to processing an existing event like "sapevent:repo_code_inspector" for the example above.

**Comment by sbcgua** [comment]
Could be a nice feature. By the way I'd add some kind of indication which exits are there and activated. Somewhere at debug page, or maybe a small indication at main. Not sure. I mean exits (unexpected behaviour) are usually very confusing for people, so we should indicate it somehow
