### ISSUE TITLE
Consider making abapgit use less than 100% of browser window width

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#4734]
I am trying to reduce visual clutter in the main page and came to the conclusion that there are only 3 _really_ important columns:
- name
- branch 
- actions
- (navigation to repo url can also be added to the online repo icon)

By hiding repo url and package in the detail section, I get this on 50% of a 1920px screen.
![image](https://user-images.githubusercontent.com/5097067/116566659-37be0f80-a907-11eb-930f-2d884743d1b7.png)

On fullscreen though, it looks strange
![image](https://user-images.githubusercontent.com/5097067/116567275-c29f0a00-a907-11eb-84cb-5814dd1add5e.png)

In general, abapgit puts way too much horizontal space between things and it becomes easier to find things if you shrink the window to 50%.

![image](https://user-images.githubusercontent.com/5097067/116567485-f4b06c00-a907-11eb-9c63-8668e3bc000e.png)
![image](https://user-images.githubusercontent.com/5097067/116567509-faa64d00-a907-11eb-990e-2968367c1e09.png)

![image](https://user-images.githubusercontent.com/5097067/116567609-13aefe00-a908-11eb-896d-d8ce0908e08f.png)
![image](https://user-images.githubusercontent.com/5097067/116567637-1ad60c00-a908-11eb-8941-7006d8b29780.png)

This makes me think that abapgit should be designed for some fixed width like 1024px instead of 100% of the screen width, except for some cases like side-by-side diff.

@sbcgua @mbtools  what do you think?

**Comment by sbcgua** [comment]
- reduce visual clutter
  - I think package is useful
  - And URL is not, I'd get rid of it too ...
  - but it would be useful to see, if the repo is switched from the default url to PR. Needs experiments, because the straight forward solution (adding url part to the branch) would probaly look long and ugly. maybe. needs an experiment.

- abapgit should be designed for some fixed width like 1024px
  - hehe, I think we discussed it some time ago and I suggested the same ;) But getting back to constructive, in reality some dynamic way to switch thing could be useful. Ideally automatic (needs normal CSS support). Or maybe with user settings, hmm.
  - yeah, branch label looks lonely on the right, especially since commit is on the left. And the new edit button. And since it's color coded ... maybe it makes sense to move all to the left. maybe.
  - "Commit action" - agree, however it need some proper mechanism to attach menu items from lower level components. But conceptually I think it is the right direction. All commands are to the right, except stage and commit.

**Comment by flaiker** [comment]
I somewhat agree. Can you find the personal settings button?

![image](https://user-images.githubusercontent.com/5270359/116575571-0d705000-a90f-11eb-9c9f-efc19f02e6a9.png)

Though exit and new window (and since 770 the GOS button) are also all the way over there so really it's also a SAP GUI problem. Full screen ALV also cannot stretch any further than 1080p on the newer metrics (even smaller on the older ones) since dynpros have a maximum width.

**Comment by FreHu** [comment]
> I think package is useful

Usually people keep the repository name and the package name the same. How about for the overview, just have a package icon column where the icon has an alt text with the package name and is an adt link to the package?

> but it would be useful to see, if the repo is switched from the default url to PR

I agree, but a majority of users probably don't switch origins often and instead switch branches

> Though exit and new window (and since 770 the GOS button) are also all the way over there so really it's also a SAP GUI problem.

abapgit navigation should be possible without using the sapgui buttons though

**Comment by mbtools** [comment]
Placement:

I'm a big fan of not inventing things again. The Fiori guidelines are excellent in this regard (https://experience.sap.com/fiori-design-web/action-placement/). Menus and action buttons are placed on the right. Menu on top, actions on bottom. Sure, AG is not Fiori but it's what SAP users are used to (more and more) and it makes sense to align with this design.

So, yes, staging and commit pages need some work. 

Width:

Just a question of CSS ;-). I'm for "centered with width 100%, max-width: 1280px" for our page content in general (with some exceptions, GH also uses max-width:100% for the split diff). This works well for Github for example and I think it's save to assume that devs don't have tiny 1024 screens anymore. 

Clutter:

My vision for the overview page is to have two modes: 
- "consumer/deploy" mode: no or little clutter, view similar to dotabap.org or https://wordpress.org/plugins/ with an icon, description, and version number of the solution (actions: install, uninstall, run app, settings of app, if this applies). 
- "developer" mode: technical details similar to what we have today. The full URL is not necessary, but a button to jump to the remote (URL as link hint) would still be helpful. I would keep the package name, too.

**Comment by FreHu** [comment]
> I think it's save to assume that devs don't have tiny 1024 screens anymore.

half of a full HD screen is 960px :)

Ideally the repositories should be selectable with a checkbox column and instead of the action column, actions would be in a toolbar.
https://experience.sap.com/fiori-design-web/table-bar/#components

This would also enable actions to be run on multiple repositories (syntax check, pull).

> "consumer/deploy" mode: no or little clutter, view similar to dotabap.org or https://wordpress.org/plugins/ with an icon, description, and version number of the solution (actions: install, uninstall, run app, settings of app, if this applies).

+ display changelog button!

**Comment by FreHu** [comment]
I remembered I actually use the url too, after a commit I click it to go open a PR.

What about merging the url and branch columns? Either

[url][branch][switch button]
or
[branch][url][switch button]

This is also good for offline repositories which have both of these columns empty, now it's just one empty column.

**Comment by sbcgua** [comment]
Merging or getting them nearby ? "Merging" - no, please - the branch is a frequently used button and the url is not, so merging would make UX worse. Moving branch to the left to the url ? Probably will look better. All "Remote" to the left, all local to the right - makes sense. Maybe also remove "https://" from urls to make it shorter.

**Comment by pokrakam** [comment]
> Usually people keep the repository name and the package name the same.
> ...
> I agree, but a majority of users probably don't switch origins often and instead switch branches

I wouldn't rely on this assumption without any usage stats. I see a typical use case of users cloning a repo and tinkering with it in their `main` branch and switching origins to see differences / get updates. There's no need for branches for your typical GitHub contribution via clone.
(PS, I note that Github has finally introduced "Fetch Upstream")

Personally I find the package useful too, I use it to navigate to the source on my system.

**Comment by FreHu** [comment]
From what I've seen internally people use branches, but for open source projects forks are used more. So I suppose we should ideally keep everything.

The main problem I was solving is forgetting to switch branches before clicking stage. I think this is solved 
- with the smaller width it is less likely to not see the branch
- you can now switch it from the stage screen anyway

But as I like to say, there are no solutions, only different sets of problems.

Now, this looks fine:
![image](https://user-images.githubusercontent.com/5097067/118127364-e2e7c200-b3f9-11eb-911b-579c6241bdc6.png)

But there is ugly wrapping if the names are long
![image](https://user-images.githubusercontent.com/5097067/118127704-54277500-b3fa-11eb-9c07-6ec3d6b3b4ab.png)

And if the url is super long, you will not see the action buttons at all.
![image](https://user-images.githubusercontent.com/5097067/118127902-8507aa00-b3fa-11eb-813a-1103a44c3540.png)

Some ways to make more space are:
- Add checkboxes to select repo and put common action buttons in the table header. This is the long term correct solution.
- Icons for package/branch could be placed in the column header instead of each column.
- make home page slightly wider than the other pages

As for the column order, I am leaning towards name, package, url, branch (so branch remains near action buttons and remote-related columns are next to each other)

**Comment by pokrakam** [comment]
What about abbreviating long URLs? 
`site.com/somesuperlongurl/withacrypticloadofhashcharactersthatnobodyreadsanyway`
`site.com/somesuperlong...anyway`
I'm speculating the host and top hierarchy is the main thing people are interested in.

FWIW, I don't use the action links. I prefer to click on the repo and work off a dedicated page, but that's just me.

**Comment by mbtools** [comment]
- You can wrap long words https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/
- Don't display URLs, see https://github.com/abapGit/abapGit/pull/4771#issuecomment-841060060
