### ISSUE TITLE
Join commit screen with stage/patch

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#4735]
In the commit screen, the list of staged files is just repeated. Maybe it would be useful to join these two pages.
![image](https://user-images.githubusercontent.com/5097067/116585553-d010c000-a918-11eb-90bd-d036d2503d51.png)

Similarly the commit screen can be placed at the bottom of the patch screen. Although it would look slightly bad here, it makes 
more sense than the current navigation.

![image](https://user-images.githubusercontent.com/5097067/116585775-064e3f80-a919-11eb-9ad9-71cbb2cf8f97.png)

Having fewer steps would also reduce confusion. Without action buttons, to patch you go 
`repo->stage->patch->[go to bottom]->[go to top]->stage->commit`
which becomes
`repo->stage->patch->[go to bottom]->commit`
to stage you do
`repo->stage->commit selected->commit`
which becomes
`repo->stage->commit selected`

**Comment by mbtools** [comment]
It does seem like one step can be eliminated. However, I was thinking of moving the selection of files to a checkbox column in the repo view (with some option like "select all, none, local diffs"). Then "Stage" would take the selected files on to the current "Commit" page (with files on top and form on bottom, action button bottom right like other forms). "Patch" could move to the "Advanced" menu.

**Comment by FreHu** [comment]
i agree, selecting objects for staging directly from the repo view is the better approach

**Comment by larshp** [comment]
note the different view options in the repo view

personally, I'd like not to scroll, there might be a lot in the staging list

**Comment by FreHu** [comment]
there is the _view changes only_ filter for that, but repo does not have a fulltext search

**Comment by FreHu** [comment]
and #3267

**Comment by mbtools** [comment]
the stage filter/view options would be nice to have on the repo view (but it's JS and quite a task to make this happen)
