### ISSUE TITLE
Stage in new branch

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#4736]
"stage in new branch" would be a very nice feature. Imho it can be a field at commit page rather then a command at the repo view

_Originally posted by @sbcgua in https://github.com/abapGit/abapGit/issues/3451#issuecomment-651590901_

Alternatives:
- allow switching branches on stage screen
- add setting to always ask for branch before staging

**Comment by sbcgua** [comment]
allow switching branches on stage screen - +1
