### ISSUE TITLE
Changing remote should be added to repo overview

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#4737]
The new icon which is next to the repo url in repo detail should be added to repo list.

**Comment by larshp** [comment]
for reference, the icon is
![image](https://user-images.githubusercontent.com/5888506/117018626-f6f23c00-acf4-11eb-8f24-6e25374e8aa8.png)

**Comment by mbtools** [comment]
We already have "Action > Settings" on the overview. Adding the icon saves one click. Instead of the icon, a better option would be to remember the last tab used in settings (for repo and global).

**Comment by wozjac** [comment]
Do yo mean something like this? 
![2021-08-22_22-25-47](https://user-images.githubusercontent.com/20969653/130369135-0670d836-fe72-4549-9638-ca5021446fb2.gif)
