### ISSUE TITLE
Missing Screens, long xml

### ISSUE THREAD

**Issue by isseurope** [abapGit/abapGit#4740]
We are making customized MIR4 transaction from standard function group MR1M (copied to Z function group). We pushed the function group to github, main function group xml file that contains info about screens is over 70 000 lines. After we pulled into different SAP system, only 49 of 122 screens is visible and program dumps if non existent screen is called (obviously :) ). All screens including missing ones are present in xml file. GUI Status and GUI Title are not pulled at all, in xml they are after screens. I am guessing the xml is too long.

Attached file should be without .txt. GitHub does not support xml files.
[zzmmag_mir4.fugr.xml.txt](https://github.com/abapGit/abapGit/files/6405677/zzmmag_mir4.fugr.xml.txt)

Edit: Found out copied function group FDCB only has 21 000 lines and no screens have been pulled for this group. So it might not be xml length.

**Comment by mbtools** [comment]
the xml looks ok. you should have a file per include in the repo. pulling over 700 includes will take some time. 

PS: Why copy all of this? Isn't it possible to use enhancements?

**Comment by isseurope** [comment]
Yes there is .xml and .abap for each include. Over 1400 files in repo. It seems that everything else is OK, except screens, statuses and titles. Pull takes around 20 seconds.
Second FG FDCB which we are trying to pull is much smaller but the screens are still missing. 

As a workaround I put the FG into transport, downloaded using CG3Y and imported to the other SAP - everything got imported. But this is a process we are trying to get rid of. 

We tried going enhancement route, but since we are making many alterations, copying it like this seems like easier way to go.

**Comment by mbtools** [comment]
I reviewed the code but there's nothing obvious that's wrong. How many entries do you have in `it_dynpro` in `zcl_abapgit_objects_program->deserialize_dynpros`? Debug from there

**Comment by isseurope** [comment]
There is 121 entries in `it_dynpro` which seems to be correct

But I found that function RPY_DYNPRO_INSERT on line 52707 returns exception 6 - illegal_field_value for screen 6020.
I imported two FG that are problematic using transports, screen 6020 doesn't raise any errors and activates fine, although in the second FG that is copied from FDCB screen 0010 (first screen in the list) contains field that does not exist in dictionary on target SAP and cannot be activated. There are different component versions on source and destination SAP, which is probably the problem.

Is it possible to pull everything without checking for errors and fixing those errors locally before activation?

**Comment by larshp** [comment]
Try running https://docs.abapopenchecks.org/checks/87/ on the source system before committing to git

abapGit uses the APIs provided by the standard system to insert and update artifacts, ie. we cannot(and should not) work around the errors, errors should be fixed in the source system

**Comment by isseurope** [comment]
I ran the check on both screens that throw exception in source system with message: The objects passed the chosen checks without any finding.

**Comment by larshp** [comment]
okay, any additional information when the exception `illegal_field_value` is raised? any message in `sy` variables?

**Comment by isseurope** [comment]
In sy-msgv1: Field OIFILTER does not exist in table RM08M (in active version). This is for screen 6020 of SAP standard FG MR1M.
I checked in se11 RM08M really does not contain field OIFILTER both in source and destination SAP system, but field in screen exists in both. If I run check on that screen, I do not get any error and it activates fine.

**Comment by larshp** [comment]
heh, well, we cannot do much about that in abapGit

if the screen is inconsistent, we cannot use the API to import the screen

**Comment by isseurope** [comment]
Is it possible to ignore that screen so it doesn't get pushed/pulled? I know how to put a file into ignore, but screens are part of the big xml, so it would ignore too much.

**Comment by larshp** [comment]
you can try modifying the XML in the repository manually

**Comment by isseurope** [comment]
Thanks for all the assistance. I guess we will have to combine abapGit and transports to make it work.

**Comment by larshp** [comment]
I recommend fixing the screen, remove the field from the screen, you probably don't want inconsistent screens for the future developers
