### ISSUE TITLE
Follow up to new remote dialog: how to switch back from a PR

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#4742]
@mbtools 

Hmmm how to revert to the origin ? :)))

![image](https://user-images.githubusercontent.com/15635498/116726407-e5a2ea00-a9eb-11eb-9786-40cc98eafb47.png)

**Comment by mbtools** [comment]
Just pick a branch (or tag or commit) and save

**Comment by sbcgua** [comment]
It worked. Thanks. :+1:

Although it is not very obvious.
OK. Closing.
