### ISSUE TITLE
Bitbucket returns wrong Content Type 

### ISSUE THREAD

**Issue by ubabap** [abapGit/abapGit#4750]
Abapgit version  is 1.101.0.
 Trying to clone a bitbucket  repository (company one, not bitbucket.org ) endet up with an error, but still  the package was assingend and it is in AbapGit as connection. 
Any action fails with Wrong Content-Type sent by server. Server is returning simple html (text/html;charset=UTF-8) when abapgit expects application/x-git-upload-pack-advertisement.

ZABAPGIT_TEST_SSL returns no error. (url shown in abapgit  used, and link is working   )

I'd expect to get any kind of authentication. But never got one. 

Sorry for raising that maybe wrongly.
I could not find that in a known issue or any search, but can't imagine it is something new.

Best regards, 

Uli

**Comment by larshp** [comment]
First try using the latest abapGit version, note that is possible to have multiple standalone versions installed

**Comment by mbtools** [comment]
in `zcl_abapgit_http_client->check_smart_response` add the following line

```abap
     IF lv_content_type <> iv_expected_content_type.
        lv_data = mi_client->response->get_cdata( ).  "<<< check the response content
        zcx_abapgit_exception=>raise( 'Wrong Content-Type sent by server - no fallback to the dumb protocol!' ).
      ENDIF.
```

content of `lv_data` should tell you more.

**Comment by larshp** [comment]
@ubabap any luck?

**Comment by ubabap** [comment]
Yes, thank, I close the 'issue' Got to remove the still shown respository (wrong package used ...)  and created it again.   Newly created one with actual standalone is working (  With the first attempt i got an error, but still the repo had been created.  maybe the response was just a logon html  )  .
