### ISSUE TITLE
Problem when serializing DB-Tables (method clear_dd03p_fields of class zcl_abapgit_object_tabl)

### ISSUE THREAD

**Issue by Linsken** [abapGit/abapGit#4754]
Hello there!
I just recently started using abapgit but I was not able to pull db-tables into other systems. After some debugging I found that in method clear_dd03p_fields of class zcl_abapgit_object_tabl is a loop (without where) which clears some components of the table (tabname, position and ddlanguage). These empty fields are omitted when serzializing these objects into xml...
I think this leads to errors when pulling the table...
Thank you for all your efforts! 
Cheers Alex 

![grafik](https://user-images.githubusercontent.com/11721948/117266695-d097e200-ae55-11eb-9ff6-0c59ff7a1c2c.png)

**Comment by larshp** [comment]
Thanks for the bug report

Are you running the latest abapGit version on both systems?

Is this something you can reproduce in a public repository? Just create a dummy TABL, verify that pulling into a different system does not work.

**Comment by mbtools** [comment]
these fields are now automatically determined during deserialize. if your repo still contains these fields in the tabl xml, then you should update the repo from the original system (using the latest abapGit version)

**Comment by Linsken** [comment]
the pulling system is the latest as developer edtion (abap 1909). i will try to update abapGit in this system and retry. i was not aware that the xml content changed between those versions...
Thanks for your help!

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/blob/main/changelog.txt#L27

**Comment by Linsken** [comment]
Oh I see :) Thanks a lot! Such a great tool.
Cheers
