### ISSUE TITLE
NW version dependent include list during deserialization

### ISSUE THREAD

**Issue by stockbal** [abapGit/abapGit#4756]
## Problem
I have the use case where I want to implement a new feature in one of my open source projects.
Unfortunately I have to inherit a SAP standard clause for the feature. Unfortunately this class does only exist starting with NW 750. 

### My idea
Create a new interface which will be implemented in the class which inherits from the SAP class.
In the coding I will create the new class dynamically

```abap
DATA: interface_in_class TYP REF TO zif_static_interface.

TRY.
    CREATE OBJECT intf_type TYPE ('ZCL_NW_DEPENDENT').
  CATCH cx_sy_create_object_error.
ENDTRY.
```

## Proposal
Obviously the class `ZCL_NW_DEPENDENT` cannot not be activated in systems with NW < 750.
I would propose to add a new file to the root of an abapGit repository called `.abapGit_src_filters.json`.

This file would have the following structure:
```json
{
  "deserialize": [
    {
      "minimum_nw_version": 750,
      "files": [
        {
          "type": "CLAS",
          "name": "ZCL_NW_DEPENDENT"
        }
      ]
    }
  ]
}
```
As the name of the property `include` suggests, we could also add a property `exclude` to filter out specific source files, depending on the NW version - not quite sure if there is use case for that ;).

During deserialization abapGit would check the files against this mapping file. Basically it is just a a more fancy *ignore* file.

**Comment by mbtools** [comment]
i see two cases
1. you want your solution deployable to lower releases (although the particular class would not work)
2. you want to prevent deploying on lower releases

The first case, is like abapGit itself. It can be deployed down to 702 but certain classes work only on more recent releases (like `zcl_abapgit_object_bdef`).  The solution is to make everything dynamic (https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_bdef.clas.abap). Not pretty but works.

For the second case, simply set the requirements in your repo settings to "SAP_BASIS 750".

**Comment by stockbal** [comment]
Yeah, but the 1st case won't work at all. The class can only be activated with syntax errors. 
I would have to create the class dynamically inside a subroutine pool if I want to ensure the deployability to lower releases which is not at all pretty.

The other solution which I have done in another project is to create different release branches, which increases the overhead if I am doing changes to the repository that are compatible to all branches.

**Comment by flaiker** [comment]
Isn't there also a possibility to put the class that implements the interface inside a package that's switchable by a business function in the switch framework? If I recall correctly the syntax check is skipped and the objects inside the package are invisible to the outside if the switch is off.
The other obvious solution is to deliver the objects with a different release requirement in a separate repository.

**Comment by larshp** [comment]
1: do everything possible to keep one branch/codebase

2: suggest setting up some CI to automatically create the other branch, eg `https://www.gnu.org/software/sed/manual/sed.html` can do a lot

**notes regarding option 2**
As a open source developer, its nice to have transparency, git offers this, if you have two branches, you can switch and test any one of them on any system. Plus setup static analysis(abaplint), which will help finding errors.

From a git client perspective, I think it should avoid doing logic, eg. changing the code. Its difficult enough to update the abap artifacts correctly. Plus how will the user know, install some code and get some different code into the system(magic)

**Comment by stockbal** [comment]
Regarding option 2 (CI):

After reading the comments I was thinking along the same direction as well. 
This automatic branch creation sounds like a good idea. So in the use case I decribed the CI steps (e.g. GitHub Action) would be the following:
1) Create the lower NW version branch (e.g. branch-740)
2) Delete all files in the created branch which would could not work anyway on this system
3) *Force* push the branch

I have one question though. How would I handle the case when a developer wants to make some changes to the general codebase but only has a NW-740 system? 
1) Clone *branch-740*
2) Make necessary changes
3) Push to remote
4) Merge changes into default branch *main*
5) CI triggers the recreation of *branch-740* ???

**Comment by larshp** [comment]
last question: communication 😄 add a description in the readme that its not allowed

instead of a different branch, you can also choose to have a different repository for the mirror

note that pushing to the branch is much like setting up a github pages branch, so there might be actions like https://github.com/peaceiris/actions-gh-pages that can help to do the heavy work

**Comment by larshp** [comment]
@stockbal can this issue be closed?

**Comment by stockbal** [comment]
I think so.
