### ISSUE TITLE
Support proxy bypass in GNU format

### ISSUE THREAD

**Issue by ThePlenkov** [abapGit/abapGit#4761]
Hi!

reviewing proxy implementation I see that wildcards are supported but in a very strange way.

For example: if we have repo URL like that: https://git.comp.com/projects/abapGit.git 

bypass proxy `*.comp.com` wont work. `*.comp.com*` will work.

So what the proposal is:
- support domains without *: `.corp.com`
- support comma separated list: `*.aventail.com,home.com,.seanet.com`

Spec taken from here https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html

Thanks!

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/blob/main/src/http/zcl_abapgit_proxy_config.clas.abap#L106

It's implemented as a range check using the URL. It should check the domain only. Then `*.comp.com` would work. You get the domain using `zcl_abapgit_url=>host( iv_repo_url )`.

Multiple values can be entered but they need to be on separate lines. I don't see the need for the comma separated list.

But if you like, pre-process the `lt_proxy_bypass` in the method above, to convert the formats your mentioned into ranges. As always, pull requests are welcome.

**Comment by larshp** [comment]
close?

**Comment by ThePlenkov** [comment]
I think so - if it's there already - i don't mind to use it like this. Thank you!
