### ISSUE TITLE
write_protected set to true because get_active_comp_upgrade returns F, which shouldn't be a possible value? 

### ISSUE THREAD

**Issue by j-rockel** [abapGit/abapGit#4762]
I've been trying to find out why all the (not manually set to write-protected) repos on the sytem i'm working on are being shown as write protected and show up as such every time i start abapgit again despite changing it in local settings. 

As far as i can tell
- the setting of write_protected to true happens in METHOD zif_abapgit_persist_repo~list.
- because the case where write_protected is false and zcl_abapgit_factory=>get_environment( )->is_repo_object_changes_allowed( ) = abap_false happens
- because in is_system_changes_allowed lv_is_upgrade is set to true for ??? reasons
- sy-subrc after calling UPG_GET_ACTIVE_COMP_UPGRADE is 0
- ls_upginfo-putstatus is F, which is not listed in the possible values (value range of UVERS-PUTSTATUS) at all

does anyone know what the F stands for / how to proceed here?

**Comment by mbtools** [comment]
Your system is still in an "upgrade" status. I don't know what F means but it's not a status for a completed upgrade (which would be no entry in UVERS or one with PUTSTATUS=`+`. 

Check the status in transaction SPAM

**Comment by j-rockel** [comment]
thanks! that helped
