### ISSUE TITLE
Issue with parallel commits

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4776]
On a few occasions, I committed changes from AG to a Github repo and nothing was changed in Github. It's like the commit never existed remotely. However, there's no error in AG either and therefore checksums on the repo are updated. After a refresh in AG, the old diffs are visible again.

I was now able to reproduce this:

- In Github, edit README.MD and make a small change (don't commit yet)
- In AG, edit an object of your repo, stage, select the object and go to commit page (don't commit yet)
- Go back to GH and commit, quickly flip to AG and commit as well

Result, only the README.MD was committed. 

Are we missing some error handling in `zcl_abapgit_git_porcelain`?

**Comment by mbtools** [comment]
response:
`000eunpack ok#009fng refs/heads/main cannot lock ref 'refs/heads/main': is at 625990aec9a9ebacbb99021804ce07bb6c350d05 but expected 77d2cfba9595de4c247d26b12cd40ce6cb75d61e#00000000`

doesn't match current checks -> needs a fix

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/blob/788d649feba7c1cfbcf90671da169c3b88d8b804/src/git/zcl_abapgit_git_transport.clas.abap#L248
