### ISSUE TITLE
Regenerate SAP_ALL profile after pulling some authorization object

### ISSUE THREAD

**Issue by juriadasek** [abapGit/abapGit#4782]
Hi guys,

I have added a new authorization object (AO) into our repository. This AO is successfully tracked by abapgit which is great and it can be pulled into a new system. However profile SAP_ALL does not contain this new AO.

Issue description: Profile SAP_ALL is automatically regenerated when transport with a new AO arrives into a target system and field SAP_ALL_GENERATION is set to ON in the table PRGN_CUST. However this is not the case after doing abapgit pull. 

Proposal: Add support for regeneration of profile SAP_ALL using abapgit. Something similar is already doing the report AGR_REGENERATE_SAP_ALL, which regenerates SAP_APP for every client in the system, so its logic can be taken as an example.

What do you think about it?

Thanks,
Juraj

**Comment by mbtools** [comment]
You should be able to do this in an exit https://docs.abapgit.org/ref-exits.html#deserialize_postprocess

Check is `is_step` contains any AOs and trigger the SAP_ALL generation.

**Comment by jfilak** [comment]
@mbtools are we sure this should be only a user exit which is not installed by default with abapGit?

I am not so skilled in ABAP matters but wouldn't all users appreciate that SAP_ALL automatically recieves AOs upon pull by abapgit if SAP_ALL_GENERATION is ON in the table PRGN_CUST?

**Comment by mbtools** [comment]
I'm with you. I just gave a hint for a quick solution. A general solution is preferred, of course. 

Adding regenetate to `ZCL_ABAPGIT_OBJECT_SUSO` is an option. It would slow things down, however, if many auth.objects are imported.

**Comment by mbtools** [comment]
here's the required call:

```abap
  CALL FUNCTION 'PRGN_AFTER_IMP_SUSO_SAP_ALL'
       EXPORTING
            IV_TARCLIENT  = '000'
            IV_IS_UPGRADE = space
       TABLES
            TT_E071       = TT_E071
            TT_E071K      = TT_E071K.
```
