### ISSUE TITLE
Error when commiting to GitLab - Missing flush-pkt

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#4795]
When I try to commit (or create a new branch etc.) to GitLab (public cloud version), I get this error.

Missing flush-pkt
![image](https://user-images.githubusercontent.com/17437789/119808185-2bb47600-bee4-11eb-9def-b4e8c483d642.png)

![image](https://user-images.githubusercontent.com/17437789/119809000-f4929480-bee4-11eb-8191-483247a0bf7a.png)

Although the commit is created in GitLab. After refreshing the repo in abapGit the state is clean.
Maybe it has something to do with recently improved error handling #4778.

https://github.com/abapGit/abapGit/blob/946180abda363d85fdfa1b3d4795ba17f6d45ba4/src/git/zcl_abapgit_git_transport.clas.abap#L219

**Comment by mbtools** [comment]
According to specs 00000000 is required but apparently gitlab uses only 0000. Oh well, we can just tweak the if a bit.

**Comment by larshp** [comment]
there are git capability negotiations in the beginning of the protocol

https://git-scm.com/docs/protocol-capabilities

this might be related to using or not using side-band

**Comment by christianguenter2** [comment]
Same error with Bitbucket as they also use 0000. I prepare a fix.
