### ISSUE TITLE
Git Protocol Error

### ISSUE THREAD

**Issue by skezkhepatmelathil** [abapGit/abapGit#4805]
Hello, 

 When trying to Push the latest code changes from our SAP 
On-Premise system to abapGit using the report ZABAPGIT. system throws an error. Please find the screen shot attached. 
`snip, removed, please dont share docx files -Hvam`

Regards,
Santosh

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/120178591-f4a6d300-c209-11eb-9f9c-e60d83e83c22.png)

**Comment by larshp** [comment]
@skezkhepatmelathil thanks, are you running the latest version? some fixes in this area just before the weekend, https://github.com/abapGit/abapGit/pull/4796

**Comment by skezkhepatmelathil** [comment]
@larshp : I used the version available on 25th May, I will try to upgrade, if there is a latest version available after the said date. Thank you.

**Comment by larshp** [comment]
there have been multiple changes, https://github.com/abapGit/abapGit/commits/main

not sure it will fix it, but its not really worth debugging on old versions

**Comment by skezkhepatmelathil** [comment]
@larshp : I did the upgrade now and its still the same error.

**Comment by larshp** [comment]
how many files are you staging? try staging just one and see if the error persists

**Comment by skezkhepatmelathil** [comment]
Even with 1 file, I get the same error.

**Comment by larshp** [comment]
hmm, try:

a: verify that you can commit to the repository using the same username/email/password using command line git
b: try committing anything to a dummy repository using abapGit

**Comment by larshp** [comment]
ok, try narrowing it down to identify the issue

I cannot reproduce...

**Comment by skezkhepatmelathil** [comment]
looks like if number of files exceed then I am seeing this error. around 20 files got committed.

**Comment by mbtools** [comment]
we need more data. please post a screen shot of Utilities > Debug Info (from main menu).

also set a break-point in `ZCL_ABAPGIT_GIT_TRANSPORT->RECEIVE_PACK`. what's the value of `lv_buffer`?

**Comment by skezkhepatmelathil** [comment]
![image](https://user-images.githubusercontent.com/45766385/120214333-9cd19180-c234-11eb-9192-2f6180fb31c0.png)

Value of LV_buffer = 00779ccdc2fa6c585f791d0b6a281bfbbec33a474ee8 e52b517f2cd16f95527f1c7e41c1474b278bbfbc refs/heads/master# report-status#0000

**Comment by mbtools** [comment]
could you please try replacing line 43+45 with the following? does this capture the response?

```abap
    DATA lv_response TYPE xstring.

    lv_response = lo_client->send_receive_close( lv_xstring ).

    lv_string = zcl_abapgit_convert=>xstring_to_string_utf8( lv_response ).
```

**Comment by skezkhepatmelathil** [comment]
here is the screen shot after the suggested change. 
![image](https://user-images.githubusercontent.com/45766385/120312565-2c308080-c2d9-11eb-9a21-7f4c4d8f3599.png)

**Comment by mbtools** [comment]
Sorry, I really can't tell why you are not getting any response data AND no error code.

**Comment by mbtools** [comment]
Go to transaction SMICM and increase the trace level Goto -> Trace Level -> Increase, reproduce and then display the trace with Goto -> Trace File -> Display End (or search for "TRC-LEVEL"). Remember to decrease the trace level once done.

- Check if there are errors during SSL negotiation. 
- Look for "HTTP request (raw)" and "HTTP response (raw)" and check return code/errors

**Comment by skezkhepatmelathil** [comment]
yes i do see some errors
![image](https://user-images.githubusercontent.com/45766385/120337890-02388780-c2f4-11eb-9c71-016f86f6bdc2.png)

**Comment by mbtools** [comment]
Let's check some basics. Run the SSL test program with the trace:
https://docs.abapgit.org/other-test-ssl.html
- Do you get "ok" for both github.com and api.github.com?
- Any errors in the trace?
 
If there are errors, your SSL config is not ok. Check https://docs.abapgit.org/guide-ssl-setup.html and SAP Note 510007.

If there are no errors, SAP Support should have a look (send them the complete trace).

**Comment by skezkhepatmelathil** [comment]
After executing the report, it says ok for both links. 
![image](https://user-images.githubusercontent.com/45766385/120449998-46796580-c390-11eb-9638-c7224e1f1fba.png)

I will contact SAP for the same. Thank you.

**Comment by mbtools** [comment]
use component:BC-CST-IC for your support ticket

**Comment by skezkhepatmelathil** [comment]
Sure, Thank you. I created a SAP incident. Will update you once its resolved.

**Comment by skezkhepatmelathil** [comment]
Hello, I contacted SAP and here is the response I received from them ..

"As i can see in attachment screenshot regarding the ICM trace, This issue did not belong to SAP ICM side, As in log it clearly said No data from server received.

Error -  ERROR => IcmReadFromPartner(id=6/7248): No data from server received, role: Server, (rc=MPI_EBROKEN: pipe broken/canceled/7) 

2733879 - ICM: ERROR => IcmReadFromPartner(id=): No data from server received

Resolution
 You need to check the following:
 
 - There is some issue with the client, causing the client to close the connection prematurely.
 - The frontend client has a response timeout that expires while the client waits for response from the server.
 - There is some firewall, Proxy, etc. between the frontend and the server that closes the connection after a period of time 

Regards,
Santosh

**Comment by mbtools** [comment]
AG uses the default timeout for HTTP connection. Check and try to increase 
icm/HTTP/client/keep_alive_timeout
icm/conn_close_timeout
icm/conn_timeout
icm/keep_alive_timeout

Another approach is trying to reproduce it with another system in your network. If the other system does not have the issue, then you can compare config.

**Comment by skezkhepatmelathil** [comment]
Hi, 

  Tested the same in another system and it also has the same issue. 
**NOTE**: ZABAPGIT version  1.89.0 works in one of our other system. Is there a way for us to install the same version in the current system?

**Comment by mbtools** [comment]
1.89 is very old. You can install and run multiple versions of the stand-alone abapGit report. However, there might be changes with the DB persistence (XML in table ZABAPGIT). So there's no guarantee that this will work properly with older versions.

**Comment by skezkhepatmelathil** [comment]
we increased the value of these parameters : 
icm/HTTP/client/keep_alive_timeout
icm/conn_close_timeout
icm/conn_timeout
icm/keep_alive_timeout

And it still does not work.

**Comment by mbtools** [comment]
in 1.89, is the value of `lv_buffer` in `ZCL_ABAPGIT_GIT_TRANSPORT->RECEIVE_PACK` the same or different? what's the difference?

**Comment by larshp** [comment]
@skezkhepatmelathil any news?

**Comment by larshp** [comment]
closing, no reply
