### ISSUE TITLE
Better Styling, Less Diffs

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4810]
I'm starting an effort to improve code styling and reduce the number of diffs we are getting when making changes. 

There are no plans to enforce these rules and it's understood that over time deviations will occur again. Nevertheless, the diffs due to using different editors or releases (gui, adt, vscode) will be significantly reduced.

The following adjustments will be made:

- Consistent description of objects: "abapGit - ..." (with title case)
- Pretty print all code
- Avoid comments before class definition (not compatible with lower releases)
- Replace "space dot" with "dot" in class definition
- Identifier in class implementation statement in lower case
- Method implementations sorted alphabetically
- Ensure all public, protected, private sections exist
- No chaining of method, attribute, type definitions 
- Whitespacing before and after data statements

**Comment by larshp** [comment]
it must be enforced, or it will just be neverending work and diffs to figure out

**Comment by mbtools** [comment]
once it's cleaned up, we can put rules in place. but some variations between SE80 and Eclipse are hard to enforce.

**Comment by mbtools** [comment]
will pause here until we are ok with this

**Comment by larshp** [comment]
1: Consistent description of objects: "abapGit - ..." (with title case)
I think we should add a abaplint rule before adjusting the descriptions

2: Pretty print all code
This should already be done? the abaplint rule is enabled?

3: Avoid comments before class definition (not compatible with lower releases)
agree, how many examples do we have of this kind? plus need abaplint rule

4: Replace "space dot" with "dot" in class definition
say I make a change in SE80, it will add "space dot" in potentially 100s of places, personally I don't like fixing this manually in SE80

5: Identifier in class implementation statement in lower case
as far as I remember, SE80 and the pretty printer changes this based on some rule, its not something that the developer decides

6: Method implementations sorted alphabetically
If the developer moves the code around in Eclipse, we should force the developer to change it back?

7: Ensure all public, protected, private sections exist
yea, well, hmm

8: No chaining of method, attribute, type definitions
nice to have, but not super important IMHO

9: Whitespacing before and after data statements
nice to have, but not super important IMHO

**Comment by pokrakam** [comment]
> 6: Method implementations sorted alphabetically
> If the developer moves the code around in Eclipse, we should force the developer to change it back?

Or for that matter if the developer moves it around in the SE24 source based editor... 
There is a code guideline that suggests keeping related methods together. 
Wasn't there already a discussion about this on here?

**Comment by flaiker** [comment]
> Wasn't there already a discussion about this on here?

#2321 and related issues and pull requests maybe?

**Comment by pokrakam** [comment]
Yep, that was the one, thanks!

**Comment by larshp** [comment]
@pokrakam please add a link to the reference

**Comment by pokrakam** [comment]
Clean Code Ch. 5 Formatting / Vertical Ordering: 
_In general we want function call dependencies to point in the downward direction. That is, a function that is called should be below a function that does the calling. This creates a nice flow down the source code module from high level to low level.
..._
Martin, Robert C.. The Robert C. Martin Clean Code Collection (Collection) (Robert C. Martin Series) . Pearson Education. Kindle Edition. 

Just for fun I'm going to raise this in Style Guides. Maybe they'll have influence to get SE80 to stop messing with even its own ordering.

**Comment by pokrakam** [comment]
Done: https://github.com/SAP/styleguides/issues/221

**Comment by mbtools** [comment]
Everyone is free to address these issues for their own repos using the serialize_postprocessing exit (https://github.com/abapGit/abapGit/pull/5194). Closing
