### ISSUE TITLE
Webdynpro runtime objects, existence

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#4826]
Hi,
I think the intention with this old code is to avoid serializing the auto generated web dynpro classes, typically named `/1BCWDY/something`, this somehow made it into the INTF code,

https://github.com/abapGit/abapGit/blob/18c9b404f139266747313deb3249c4c8186e78d2/src/objects/zcl_abapgit_object_intf.clas.abap#L272-L280

suggest removing from INTF, and then in the CLAS serializer checking if the name starts with `/1BCWDY/` then ignore

**Comment by mbtools** [comment]
I think the code is correct. Here's an example

![image](https://user-images.githubusercontent.com/59966492/120984127-a306c700-c77a-11eb-8d4c-225e98579409.png)

![image](https://user-images.githubusercontent.com/59966492/120983622-2bd13300-c77a-11eb-8ad1-c9539f1dc1a4.png)

![image](https://user-images.githubusercontent.com/59966492/120983588-21169e00-c77a-11eb-8569-de215b411d14.png)

**Comment by larshp** [comment]
hmm, ok, closing
