### ISSUE TITLE
Many unclear diffs regarding field LANGU to SYST_--2DLANGU

### ISSUE THREAD

**Issue by abap-weasel** [abapGit/abapGit#4828]
After updating ABAPGIT I have the DIFFS like this for every DOMA. Anyone else experiencing this?

![image](https://user-images.githubusercontent.com/47646214/121198728-a8473d00-c872-11eb-9220-0fb3618b20ee.png)

**Comment by larshp** [comment]
thanks, it is not intended, some parts of https://github.com/abapGit/abapGit/pull/4815/files#diff-93ce42cb467fe5ed03329718888876e52eb2d31c18599b3df89d3c953d1917f7 should be rolled back

**Comment by larshp** [comment]
I'll open a PR, sec

**Comment by abap-weasel** [comment]
Looking through recent commits, this may be a side effect from #4815 or #4807 @mbtools

**Comment by larshp** [comment]
@abap-weasel try testing #4829

**Comment by abap-weasel** [comment]
Diffs regarding LANGU field reverted and everything back to normal. Thanks @larshp 👍

**Comment by larshp** [comment]
cool, I'll merge it

**Comment by larshp** [comment]
closing
