### ISSUE TITLE
Object Type PDWS not supported

### ISSUE THREAD

**Issue by sarkaa4** [abapGit/abapGit#4830]
I am trying to move the change of a Workflow object but it ignores it. Is there a different way of doing it? I am trying to stage.

![PDWS](https://user-images.githubusercontent.com/62158122/121410436-93c97a00-c930-11eb-836a-7b385f86113d.jpg)

**Comment by pokrakam** [comment]
Workflows are not supported yet, see [Supported Object Types](https://docs.abapgit.org/ref-supported.html)
I am currently working on it, might have something in a month or so. You can try the XML import/export feature of the WF builder but I've had mixed results with it.

As this is already documented and linked to an issue I think we can close this issue unless you have any further questions?

**Comment by pokrakam** [comment]
Can we close this as we have #154 for it? 
I do really want to get this done but am unfortunately in a high workload in this annoying thing called day job. Looking forward to some quiet time over Christmas...
