### ISSUE TITLE
commit rejected: "Commit: Author name empty"

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#4832]
Trying to update a class on my samples' repo:
![immagine](https://user-images.githubusercontent.com/25269970/121603006-6b34a380-ca48-11eb-807f-9ff3443bc6ca.png)

Howerver in zcl_abapgit_services_git=>commit the field is_commit-author_email is dirty and this triggers the error:
![immagine](https://user-images.githubusercontent.com/25269970/121603241-be0e5b00-ca48-11eb-8742-55c9a4293d97.png)

I haven't changed the project, the user profile or the repo since last commit about a week ago; if this isn't somehow related to the GUI (Java now, possibly Windows last week) I have no clues. I'll have a look again soon, for the moment here is the report.

**Comment by mbtools** [comment]
Put break-point at `zcl_abapgit_gui_page_commit->parse_commit_request` to check if the GUI event data is handed over properly from the HTML viewer event (or even before that at `zcl_abapgit_gui_event->constructor`).

**Comment by AndreaBorgia-Abo** [comment]
Looks like email is already dirty in the constructor, using the Java GUI:
![immagine](https://user-images.githubusercontent.com/25269970/121801833-b6fa6f00-cc39-11eb-8932-2061420be662.png)

I'm going to try the same commit from the Windows GUI:
![immagine](https://user-images.githubusercontent.com/25269970/121802705-0773cb80-cc3e-11eb-8608-a04593f96a07.png)

Field is empty as expected, [commit](https://github.com/AndreaBorgia-Abo/ABAP-Examples/commit/c01883f33f924be6a30dd07e742c788ee6baf3d3) succeeds.

I guess this means we can close it because the Java GUI is unsupported, right?

**Comment by FreHu** [comment]
@filak-sap might know something about this

**Comment by jfilak** [comment]
I don't suffer from this problem with my JavaGUI.

**Comment by AndreaBorgia-Abo** [comment]
I'm using 7.70 with SapMachine, on Linux

**Comment by jfilak** [comment]
```
SAP GUI for Java 7.50 rev 9.6
(Version ID 075000040906)
2020-05-04 06:32:28 +0200
mo-f75228bd7, 750_REL, 1994460
Java VM: SAP SE Version 11.0.7
OS: Linux(amd64) Version 5.11.19-100.fc32.x86_64
```

**Comment by mbtools** [comment]
I can confirm the issue with Java GUI 7.70 rev 1. postdata is incorrectly padded with spaces and null values. imho, an SAP bug. 

![image](https://user-images.githubusercontent.com/59966492/121882596-0c557f80-cd11-11eb-9f59-d1af9c5299da.png)

**Comment by AndreaBorgia-Abo** [comment]
@mbtools thanks, I'll see what I can do. In the meanwhile, no Java for git :D

**Comment by AndreaBorgia-Abo** [comment]
SAP GUI for Java 7.70 rev 2
(Version ID 077000040200)
2021-06-11 08:03:48 +0200
gclm0108, 760_REL, 2072854
Java VM: SAP SE Version 11.0.11+9-LTS-sapmachine
OS: Linux(amd64) Version 5.10.0-7-amd64

![immagine](https://user-images.githubusercontent.com/25269970/123518205-24c88100-d6a5-11eb-9f3a-b9e6457c455f.png)

@mbtools looks like rev2 is fine, are you able to confirm?

**Comment by AndreaBorgia-Abo** [comment]
I thought 7.70rev2 had fixed this issue because because a quick test showed IT_POSTDATA looking good but, no, this is still open.

**Comment by AndreaBorgia-Abo** [comment]
Upgraded to rev3 and ran a couple of test: with a very short description, IT_POSTDATA contains one line only and the commit works. With a longer description, the second line is bogus and will trigger the error:
![immagine](https://user-images.githubusercontent.com/25269970/130364843-b7f7265d-3a31-46e4-bbac-51c891a6c6aa.png)

**Comment by sandraros** [comment]
I don't know if it's worth comparing with 7.60 that I use and which works fine. Here's what I obtain with this [minimal potentially-reproducible code](https://gist.github.com/sandraros/f03cb1e7d8fe6f52701c84fa1b7d4ca9) when I click the button "ABAP call": I can see in method flush_event_parameters of cl_gui_html_viewer that it gets the POSTDATA size `305` from the second parameter of the GUI event, and method get_sapevent_postdata of cl_gui_html_viewer gets the initial_charset `utf-8` then retrieves the 305 bytes from the POSTDATA and decodes from "utf-8". My system: SAP GUI Windows 7.60 + ABAP 7.52 SP 0.

**Comment by mbtools** [comment]
Please test https://github.com/abapGit/abapGit/pull/4903

**Comment by AndreaBorgia-Abo** [comment]
@sandraros @mbtools it's gonna be a few days before I have a chance to test but I will get to it! In the meanwhile, thanks.

**Comment by AndreaBorgia-Abo** [comment]
@sandraros thank you for the gist, even though it did not initially trigger the bug it was extremely valuable: removing one line from the payload pushed it below the line length and then I got the hash markers for null, with 7.70rev3 Java on my Linux laptop (the server was the same one at home).

**Comment by AndreaBorgia-Abo** [comment]
Upgraded now to 7.70rev4 and ran the test program again: situation is unchanged, workaround is still needed.

**Comment by AndreaBorgia-Abo** [comment]
I've tried with a couple of contacts but it got nowhere, so the least I can do is keep checking every new release :)

**Comment by sandraros** [comment]
or direct discussion with Frank Krause from SAP, he quickly answers to any SAP GUI-related question in SAP Community.

**Comment by AndreaBorgia-Abo** [comment]
[Done.](https://answers.sap.com/questions/13544691/incorrectly-padded-postdata-with-java-gui.html)

**Comment by AndreaBorgia-Abo** [comment]
Rolf-Martin Woersinger from SAP answered: if anyone is using the Java GUI professionally (I am not), could they possibly file the Incident he's asking for? Thanks.

**Comment by sandraros** [comment]
I can do it with my company S-user, but I won't be able to provide an access to a SAP system (owned by other teams of my company I don't even know). If anyone has a better option, priority to you...

**Comment by mbtools** [comment]
attach the sample prg from the blog, so SAP can reproduce it in their system. don't think access will be necessary

**Comment by AndreaBorgia-Abo** [comment]
They wanted a trace from the Java GUI, that I can do!

**Comment by sandraros** [comment]
That would be nice if you can do the trace, I'll open the ticket and attach everything you provide. Thanks!

**Comment by AndreaBorgia-Abo** [comment]
@sandraros here comes the 7.70rev4 tracelog: I can confirm that the bug is still triggered with your sample program, but curiously enough in the trace it seems to be decoded correctly. Well, they'll ask for more tests, in that case.
[trace770rev4.txt](https://github.com/abapGit/abapGit/files/7677990/trace770rev4.txt)

@jfilak could you run a test with your older GUI version and trace that too? Just comment out one line in the [example above](https://github.com/abapGit/abapGit/issues/4832#issuecomment-907630994) and you're good to go,

**Comment by sandraros** [comment]
Ticket opened. If you don't mind, I set the "low" priority, so probably a few days before we get a feedback.

**Comment by sandraros** [comment]
@AndreaBorgia-Abo Fresh news from SAP:
"We finally have been able to look into the issue and found the reason. The fix is planned to be part of 7.70 rev 5. "
"Please return the incident if you are interested in a test version to verify the fix before the rev 5 shipment."
Are you interested to test the beta version?

**Comment by mbtools** [comment]
I will trust that it's fixed... (Jun 2021, "it's an SAP bug" https://github.com/abapGit/abapGit/issues/4832?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDIwNDU3MTE0NjI6NTk5NjY0OTI%3D#issuecomment-860597943 )

**Comment by sandraros** [comment]
@mbtools Sorry to pollute the issue ;-) @AndreaBorgia-Abo I'll continue the discussion in https://answers.sap.com/questions/13544691/incorrectly-padded-postdata-with-java-gui.html

**Comment by AndreaBorgia-Abo** [comment]
Final update: fixed in upcoming release.
