### ISSUE TITLE
SOBJ Business object types

### ISSUE THREAD

**Issue by abap-weasel** [abapGit/abapGit#4835]
Object type SOBJ not supported

**Comment by rayatus** [comment]
I'm working on it by using that GENERIC serializer.
Rigth know testing it a little bit and pending to double check abapGit conventions.

Also thinking about adding SOBJ test in "[abapGit tests](https://github.com/abapGit-tests)" but not sure how to proceed in here. Any suggestion in here?

**Comment by larshp** [comment]
create a pull request to https://github.com/abapGit-tests/SOBJ

one scenario per repository, let me know if you need more repositories

**Comment by mbtools** [comment]
Supported. Closing
