### ISSUE TITLE
Function call not compatible with 702

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#4847]
Cannot use functional methods in CALL FUNCTION:

https://github.com/abapGit/abapGit/blob/887e7dd3321dfd913127a2d7e035f18e9225e80f/src/ui/zcl_abapgit_gui_router.clas.abap#L733-L738

**Comment by mbtools** [comment]
of course... it's nice to support 702 but it's also a pain. thanks for fixing and having Lars create a rule for it so I don't mess it up again 😄
