### ISSUE TITLE
spurious difference in abap2xlsx ZEXCEL_S_ORG_REL

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#4865]
It's not quite like #4506 because the structure is already present in both NPL (7.52SP04 demo) and A4H (HANA 1909 demo).
In NPL after a pull from either upstream or my own fork, there are no differences shown.
In A4H the local copy appears to have a trailing extra field, SEX:
![Screenshot_20210706_232801](https://user-images.githubusercontent.com/25269970/124668976-ec4d5200-deb1-11eb-82d9-9655f5b2a235.png)

The structure appears to be identical in both A4H and NPL, 121 fields, with SEX  in line 95. The additional field is NOT listed in the repo because it's an INCLUDE. Using "advanced, reset local" makes no difference. It's not a matter of GUI either, Java or Windows give the same output on both systems: A4H has an extra local field, NPL does not.

Where should I look to find the cause?

**Comment by mbtools** [comment]
The includes are SAP-standard and it looks like in A4H SAP has defined an extra foreign key relationship for the `SEX` field. If these relationships are indeed inherited from the include structure, then they should not be included in the serialized output for the object that contains the include.

**Comment by AndreaBorgia-Abo** [comment]
BAPIBUS1006_CENTRAL_PERSON-SEX indeed has a foreign key:
![immagine](https://user-images.githubusercontent.com/25269970/125114539-610ad100-e0ea-11eb-9bb9-34c1c4678ae4.png)

However, ZEXCEL_S_ORG_REL has none:
![immagine](https://user-images.githubusercontent.com/25269970/125114681-91526f80-e0ea-11eb-97c6-ec99c9eae5db.png)

Is ZCL_ABAPGIT_OBJECTS, method SERIALIZE the correct spot to check?

**Comment by mbtools** [comment]
structures are serialized by `zcl_abapgit_object_tabl`

**Comment by AndreaBorgia-Abo** [comment]
First debug round:
1. in class ZCL_ABAPGIT_SERIALIZE, method ADD_OBJECTS (ZCL_ABAPGIT_SERIALIZE): set lv_force to 'X'
2. breakpoint in class ZCL_ABAPGIT_OBJECT_TABL,  METHOD zif_abapgit_object~serialize will now trigger
3. io_xml->add( iv_name = 'DD08V_TABLE' : deleting line for SEX makes difference disappear, so far so good.

Second attempt:
* method CLEAR_DD03P_FIELDS (ZCL_ABAPGIT_OBJECT_TABL) removes nested structures from ct_dd03p
* DELETE lt_dd08v WHERE noinherit = 'N' : does nothing because that field and many more have Y
* LT_DD08V shows SEX with CHECKFLAG blank

Could we perhaps add the following line?
DELETE lt_dd08v WHERE checkflag = ''
after
DELETE lt_dd08v WHERE noinherit = 'N'.

Hmm, nope, I get spurious differences in these:
ZEXCEL_S_CONVERTER_FCAT
ZEXCEL_S_CONV_FIELDCATALOG

Well, I'm attaching lt_dd08v... is there any reasonable way to decide that this field has to go?
```
TABNAME	FIELDNAME	DDLANGUAGE	CHECKTABLE	FRKART	CLASFIELD	CLASVALUE	CARD	CHECKFLAG	DDTEXT	ARBGB	MSGNR	NOINHERIT	CARDLEFT
ZEXCEL_S_ORG_REL	AUTHORITY	E	*	REF			CN	X				Y	1
ZEXCEL_S_ORG_REL	CORRESPONDLANGUAGE	E	*	REF			CN	X				Y	C
ZEXCEL_S_ORG_REL	COUNTRY	E	*	REF			CN	X				Y	1
ZEXCEL_S_ORG_REL	DEPARTMENT	E	*	REF			CN	X				Y	1
ZEXCEL_S_ORG_REL	FUNCTION	E	*	REF			CN	X				Y	1
ZEXCEL_S_ORG_REL	INDUSTRYSECTOR	E	*	REF			CN	X				Y	1
ZEXCEL_S_ORG_REL	LEGALFORM	E	*	KEY			CN	X				Y	1
ZEXCEL_S_ORG_REL	MARITALSTATUS	E	*				CN	X				Y	1
ZEXCEL_S_ORG_REL	NAMCOUNTRY	E	*	REF			CN	X				Y	C
ZEXCEL_S_ORG_REL	NAMEFORMAT	E	*	REF			CN	X				Y	C
ZEXCEL_S_ORG_REL	POBOX_CTRY	E	*	REF			CN	X				Y	C
ZEXCEL_S_ORG_REL	PO_BOX_REG	E	*				CN	X				Y	C
ZEXCEL_S_ORG_REL	PREFIX1	E	*					X				Y	
ZEXCEL_S_ORG_REL	PREFIX2	E	*					X				Y	
ZEXCEL_S_ORG_REL	REGIOGROUP	E	*	REF			CN	X				Y	C
ZEXCEL_S_ORG_REL	REGION	E	*	REF			CN	X				Y	C
ZEXCEL_S_ORG_REL	SEX		*	KEY			CN					Y	1
ZEXCEL_S_ORG_REL	STR_ABBR	E	*	REF			CN	X				Y	C
ZEXCEL_S_ORG_REL	TIME_ZONE	E	*	REF			CN	X				Y	C
ZEXCEL_S_ORG_REL	TITLE_ACA1	E	*					X				Y	
ZEXCEL_S_ORG_REL	TITLE_ACA2	E	*					X				Y	
ZEXCEL_S_ORG_REL	TITLE_SPPL	E	*					X				Y	
ZEXCEL_S_ORG_REL	VIP	E	*	REF			CN	X	h			Y	1

```

**Comment by larshp** [comment]
well, it is a difference between the systems, and the foreign keys for include structures are part of the original structures, so from my point of view the difference is correct?

I'd suggest for examples in abap2xlsx to be sef-contained, don't use any SAP standard stuff, this will also make it work on more kinds of systems(Steampunk sometime?)

**Comment by AndreaBorgia-Abo** [comment]
@larshp I was hoping there was a way to characterize these minor differences and have abapGit ignore them silently. 
Do we already have a bug for that in abap2xlsx? Other than the DDIC cleanup, I mean.

Back on track, I guess this bug can be closed, then?

**Comment by larshp** [comment]
you can choose to implement a abapGit user exit to ignore the difference, but it is a difference IMHO, and thus should be shown

**Comment by AndreaBorgia-Abo** [comment]
Line of thought is: difference derives from object which is both standard and external to the repo, so abapGit can't change it, might as well ignore it.

Which exit did you suggest? PRE_CALCULATE_REPO_STATUS? PRE_CALCULATE_REPO_STATUS?

Anyhow, closing now.

**Comment by larshp** [comment]
well, it would have to be installed on all clients, not something that would be part of the vanilla abapGit...
