### ISSUE TITLE
Unexpected unpack status error with abapGitServer

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#4872]
When committing to abapGitServer, an error is returned
_Git protocol error: Unexpected unpack status_

The issue originated with #4778 which fails on the AGS response. I don't know if the issue is with abapGitServer or abapGit.  

When committing to GitHub, I get the response:
```
000eunpack ok
0017ok refs/heads/main
00000000
```
but committing to AGS I get:
```
0013#000eunpack ok
001e#0019ok refs/heads/master
0009#00000000
```
It appears that either the band is not removed, or the band is added twice by AGS.

See also https://github.com/larshp/abapGitServer/issues/156

Reverting `zcl_abapgit_git_transport` to before #4778 resolves the issue, but it would be better to fix it.

**Comment by mbtools** [comment]
issue is on server side. see  larshp/abapGitServer#156
