### ISSUE TITLE
404 error inspite of correct URL

### ISSUE THREAD

**Issue by abal-illumiti** [abapGit/abapGit#4881]
Not sure one of the user is getting this error. From auth perspective he has all he needs

![image](https://user-images.githubusercontent.com/47009831/127511351-bd0f86da-cc47-44e2-b9ad-8103dd5f4df1.png)

![image](https://user-images.githubusercontent.com/47009831/127511588-f39f5c6a-f358-4228-be93-5fa1fac4fde8.png)

Thanks
Aman

**Comment by larshp** [comment]
is the user using password or PAT?

note that yesterday and tomorrow there are brownouts for password authentication, 
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

**Comment by abal-illumiti** [comment]
user is using a token due to MFA enabled for our org. May be try to renew the token and try ??

Thanks
-Aman

**Comment by larshp** [comment]
try via command-line git and see what it says?

any special characters in the repository name?

**Comment by abal-illumiti** [comment]
No special characters. It works for me and 2 other developers.. Just for one this error pops up.

**Comment by larshp** [comment]
try via command line

**Comment by larshp** [comment]
@abal-illumiti any luck?

**Comment by larshp** [comment]
closing, no reply
