### ISSUE TITLE
OOPS: Support for Persistence Service classes 

### ISSUE THREAD

**Issue by WillianGruber** [abapGit/abapGit#4883]
Hello,

I was looking at the code but couldn't figure out if abapGit supports persistence classes (CL*, CB* and CA*) and shared memory classes
Table SEOCLASSDF, Field CATEGORY with values 10, 11 and 45

Specifically about persistence classes, does abapGit supports mapping persistence and generator settings?
![image](https://user-images.githubusercontent.com/56033692/127616832-74eaf381-3e58-4b52-abb0-3bdd48a52f7e.png)
![image](https://user-images.githubusercontent.com/56033692/127616923-34c983b2-b288-485c-ac51-e2fb5d0dfe36.png)

Thank you,

**Comment by larshp** [comment]
Hi,
I'm not sure, but try 😄 

Install the dev edition https://tools.hana.ondemand.com/#abap and try there first

**Comment by mbtools** [comment]
We already have a test case https://github.com/abapGit-tests/CLAS_persistent

**Comment by WillianGruber** [comment]
@mbtools by what I see, there is no mapping or generaton settings serialized in that test... should we include it?

**Comment by larshp** [comment]
yeap, pull requests welcome :)

let us know and we'll create another repository under https://github.com/abapGit-tests for storing test data

**Comment by mbtools** [comment]
`SHMA` is already supported (https://docs.abapgit.org/ref-supported.html). I change title to `OOPS`

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.
