### ISSUE TITLE
Object type SRFC doesn't exist on older versions

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#4899]
RFC Service object SRFC is auto-generated on newer systems when creating an RFC FM. It is listed as an importable object on old versions but the repo import fails due to a syntax error. 

My suggestion is to skip importing if the feature is not available. 

However this does have two side-effects: It will always show up as a diff (may or may not be desired), and it also means that committing back could delete it in the repo, which may also be unwanted. Also raised #4898 to discuss this aspect as a general issue as this may impact several object types.

**Comment by larshp** [comment]
Can you help to add a screenshot of the syntax error? Where does the error occur?

**Comment by pokrakam** [comment]
OK, it's been a bit of a mission to reproduce, in the end created the serialised XML by hand :) 
Repo https://github.com/pokrakam/abapGit_4899

It's not as bad as I first thought, it does continue deserialisation after error. The error is 
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/25539927/130292050-9dab228b-ab95-4328-b4b5-8fb7b27f21a2.png">

The issue with my original encounter was that a whole raft of objects are not deserialized the same way and small diffs remain. e.g. Search Help's `fuzzy_similarity` attribute is not available on older systems. This made it seem that the SRFC stopped the rest of the deserialisation, but fortunately not. 

HOWEVER, with DDLS it dumps on 7.31 
The test repo contains branches: 
SRFC - includes SRFC
DDLS - includes a DDLS
main - includes both

As discussed on #4898, it would be better to provide an "unsupported on this version" message rather than the error above.

**Comment by pokrakam** [comment]
Sorry on holiday at moment, can test on Monday.

**Comment by pokrakam** [comment]
@mbtools thanks, I gave it a whirl and the error message is clearer. Both SRFC and DDLS give out an appropriate message on a 7.31 system,
However it now puts a complete stop to the entire pull. So if one such object is contained in a repo the whole thing is unusable. However I think these PRs are a good step in the right direction, a more flexible solution is the topic of #4898

**Comment by mbtools** [comment]
You should be able to pull all other objects. I will hold off with merging until that's fixed. I will get to it next week

**Comment by AndreaBorgia-Abo** [comment]
> However this does have two side-effects: It will always show up as a diff (may or may not be desired), and it also means that committing back could delete it in the repo, which may also be unwanted.

Oh, nice to know I'm not seeing things :) Just pulled aG on a 740 system and the two SRFC objects are indeed showing up as local-only. All objects are otherwise active, no need to reopen, right?
