### ISSUE TITLE
authentification problems 

### ISSUE THREAD

**Issue by Ennowulff** [abapGit/abapGit#4900]
I have problems authentificating for my private organization. :(
Updated abapGit to latest Version 1.109.0

the password dialog appears requesting username and password/token.
I enter the data and nothing happens. I have to enter the password again and then the message 

`Access to resource forbidden (HTTP 403)`

I reassured that I have admin privileges on the project. 
Access to other projects of other private organizations also do not work.
Access to other "normal" projects work fine.
My colleague @Georgios-G has the same trouble.
So it seems it might have something to do with the organization...?

Any suggestions what I can do?

Thanks
~Enno

**Comment by larshp** [comment]
What are you using for git hosting?

If github, note that tokens are required since Friday last week, see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

**Comment by Ennowulff** [comment]
yes, github. just updated to 2FA.
Also required 2FA in the organization.
I tried to understand what to do from the blog but I didn't get it... 😢

**Comment by larshp** [comment]
create a PAT, https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token and use that instead of the password

**Comment by Ennowulff** [comment]
thanks @larshp ! Just found out.
also created SSH keys and passphrases before... 😄 

that brings my password manager to the limit.
