### ISSUE TITLE
Logos for Repositories

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4901]
It would be nice to be able to maintain a logo (icon) for each repository. The logo shall be included in the repo (as MIME object?), maintained in repo settings (new field in dot_abapgit?), and displayed in the list of repositories. 

The logos could also be used on https://dotabap.org/ (instead of the logo of the repository owner) and https://abaplint.app/.

**Comment by larshp** [comment]
there is https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/customizing-your-repositorys-social-media-preview

**Comment by mbtools** [comment]
Nice. Calling the graphql API works but requires an implementation for each provider (as you have started with). I was thinking more of making it part of the ABAP repo (not provider specific metadata). But maybe we add an exit to pull in the current GH or GL logo if that's already maintained.

**Comment by larshp** [comment]
hmm, I think this is nice to have, low priority

also some users might not be directly connected to the internet, we dont want to do this on server side?

anyhow, suggest closing
