### ISSUE TITLE
[SICF] Same object with different ids

### ISSUE THREAD

**Issue by jrodriguez-rc** [abapGit/abapGit#4902]
There is a problem with these objects when the package is transported into a system and then configure with abapGit (to import changes in my case).

When the SICF object is transported it generates a new id, which is different from the original system, causing that the service is detected as new:
![image](https://user-images.githubusercontent.com/56556686/130229444-1f3e8960-632a-42e7-95de-64cfafc5d33d.png)

Maybe the file in the repository should be the full path of the service, instead of the generated id:
![image](https://user-images.githubusercontent.com/56556686/130229552-a7a24009-4aa6-499b-87b4-5a300e54dcec.png)

What do you think about this possible change?

**Comment by larshp** [comment]
what are the steps to reproduce this error? the SICF is imported with CTS, and afterwards abapGit is configured

the full path is used, https://github.com/abapGit/abapGit/blob/18c9b404f139266747313deb3249c4c8186e78d2/src/objects/zcl_abapgit_object_sicf.clas.abap#L298

**Comment by jrodriguez-rc** [comment]
Those are exactly the steps.

The method `read_sicf_url` seems that is only to determine the TADIR entry in the case of several services with the same name but different paths.

**Comment by mbtools** [comment]
The hash is based on the path ("url"). Since you have different hashes (as part of the filenames), it looks to me like the paths of the sicf nodes are not identical. 

The remote path is `/sap/bc/apc/rslt/ish_apc_patient/`. What is the path locally?

**Comment by jrodriguez-rc** [comment]
Yes, you are right, the namespace `/rslt/` service was not imported and CTS created `ish_apc_patient` service under `apc` node `/sap/bc/apc/ish_apc_patient/`
