### ISSUE TITLE
Unauthorized access to resource (HTTP 401)

### ISSUE THREAD

**Issue by one-solution** [abapGit/abapGit#4908]
Hi all,

I have had the following problem for about 2 weeks.

When I click on the GitHub link via the ZABAPGIT_STANDALONE report, I have to enter user and password and unfortunately I get the following error message -> 
Unauthorized access to resource (HTTP 401). Check you credentials

![image](https://user-images.githubusercontent.com/44028195/131132151-2ff363e3-987a-44f1-b6df-0d28b6089ba4.png)

![image](https://user-images.githubusercontent.com/44028195/131132787-ef5f49ef-ff05-4b26-b3d2-9977ecba55ea.png)

The credentials are valid because I can use them to log in via browser.

Report ZABAPGIT_TEST_SSL does not bring any errors. So the certificates are still valid for me.

Where do we have the problem?

Thank you.

Best,
Marco

**Comment by Sadullah-TANRIKULU** [comment]
excellent solution @larshp thanks sooooooo much =)
