### ISSUE TITLE
"Cannot switch origin twice" in remote settings is confusing

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#4919]
Note: this is unrelated to the PR in the screenshots, I can reproduce with any of the open PRs.

Switching to PR works just fine the first time:
![image](https://user-images.githubusercontent.com/5097067/131243581-56ffda78-599d-46b1-8454-7262e293a131.png)
If I click save again, I will get an error even though I didn't change anything
![image](https://user-images.githubusercontent.com/5097067/131243589-0551ab5f-1b34-48d3-bc96-d731a92bd81a.png)
This also causes the repo page to not work
![image](https://user-images.githubusercontent.com/5097067/131243593-7869cc50-aafb-428b-842a-63067dbf112b.png)

The trick in both cases is to switch the branch back to main.
![image](https://user-images.githubusercontent.com/5097067/131243653-4a9632d5-63e2-46ce-9848-167c60090a59.png)

This is confusing, I know you can only have one kind of remote checked out at once, but 
- the remote settings shouldn't do anything if the form didn't change
- I don't understand why the second interaction has different results

**Comment by mbtools** [comment]
Try #4921
