### ISSUE TITLE
Cloning repositories doesn't work anymore

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#4923]
Cloning arbitrary repositories doesn't work anymore.
e.g. https://github.com/xinitrc86/zthread.git
![image](https://user-images.githubusercontent.com/17437789/131310530-386cb452-8880-4440-a304-2462127ba110.png)
![image](https://user-images.githubusercontent.com/17437789/131310905-56a282be-26e9-48cb-849e-3a85108bc0fa.png)

Seems that bug was introduced with #4920

**Comment by larshp** [comment]
ugh, @christianguenter2 are you looking into a fix?

**Comment by christianguenter2** [comment]
I'll try

**Comment by larshp** [comment]
@christianguenter2 I've opened https://github.com/abapGit/abapGit/pull/4924

**Comment by larshp** [comment]
we can comment the code for now, and then there is time to get it working

I also tried adding a TRY CATCH, but there is more stuff failing...

**Comment by christianguenter2** [comment]
hm, TRY CATCH works for me, other errors seem related to missing packages due to cancelled cloning.

**Comment by christianguenter2** [comment]
yeah, let's comment it

**Comment by larshp** [comment]
for automatic package creation, the package does not exist before until after pull, in this case it dumps

**Comment by christianguenter2** [comment]
Yes, that's right

**Comment by christianguenter2** [comment]
fixed by #4924
