### ISSUE TITLE
No Github login via 2FA

### ISSUE THREAD

**Issue by preinboth** [abapGit/abapGit#4931]
The login via 2FA, which github now requires, does not work for me in abapGit. I can neither log in with a password nor with 2FA via abapGit.

My Github account has of course been converted to 2FA.

Error message:
`Unauthorized access to resource (HTTP 401). Check your credentials `

Is this a bug in abapGit, or which screw do I have to turn?

**Comment by jfilak** [comment]
Did you use Token for Password?

**Comment by preinboth** [comment]
I entered my token in the password field.

**Comment by larshp** [comment]
check https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

ref #4908, #4900

**Comment by preinboth** [comment]
@larshp 
Ah ok, abapGit needs the Personal Token, not the 2FA Token. Thanks :-)
