### ISSUE TITLE
Object Type FDT0 BRF+ Apps not supported by ABAPGIT

### ISSUE THREAD

**Issue by sharmaalok2482** [abapGit/abapGit#4948]
Whether BRF+ Applications will be supported in the future ?

**Comment by larshp** [comment]
try

https://github.com/abapGit/abapGit/issues/33 has been closed

but looks like https://docs.abapgit.org/ref-supported.html is not updated yet

**Comment by larshp** [comment]
@sharmaalok2482 did above help?

**Comment by sharmaalok2482** [comment]
Yes Thanks
