### ISSUE TITLE
Inactive or Objects with Syntax Error can be commited

### ISSUE THREAD

**Issue by sharmaalok2482** [abapGit/abapGit#4949]
I was able to push Inactive or Objects with Syntax Error to repository . Is this right behavior?

**Comment by larshp** [comment]
inactive: abapGit [should serialize only the active object](https://docs.abapgit.org/development/serializers.html)

syntax errors:
git as such is just files, and developers can make any changes to these files from anywhere

typically CI is set up, https://www.atlassian.com/continuous-delivery/continuous-integration

for the development of abapGit, we use pull requests and [abaplint](https://abaplint.org) to check for syntax errors before merging

**Comment by mbtools** [comment]
There's known issue with inactive sources: 
https://github.com/abapGit/abapGit/issues/4568#issuecomment-796697641

**Comment by larshp** [comment]
@sharmaalok2482 did above help?

**Comment by sharmaalok2482** [comment]
Yes thanks
