### ISSUE TITLE
Missing checkout commit feature

### ISSUE THREAD

**Issue by mrsetosan** [abapGit/abapGit#4955]
Hi there.

I updated to the current version 1.109.0. In this version I am missing the feature "Checkout commit" as advanced options for an online repository.
![abapgit](https://user-images.githubusercontent.com/25388472/133563965-8cfd35df-bb87-4d2f-bef9-892889b2ca7f.png)

Is this feature not supported anymore?

I couldn't find any hints in release notes that it has been removed.

Thank you for your support.

**Comment by larshp** [comment]
its hidden under the repo settings

![image](https://user-images.githubusercontent.com/5888506/133564910-15461356-7725-488a-9f44-585a8883a705.png)

![image](https://user-images.githubusercontent.com/5888506/133564872-085addaa-56f7-4742-a8c5-ec886d0552af.png)

**Comment by mrsetosan** [comment]
@larshp ahh, thank you very much.

Its quite hidden :).
