### ISSUE TITLE
ABAPGIT in BackGround

### ISSUE THREAD

**Issue by sharmaalok2482** [abapGit/abapGit#4956]
How traceability will be maintained if ABAPGIT is running in Background and pushing changes to Repos ?

**Comment by larshp** [comment]
traceability?

for "Automatic push, auto author", the author of the commit will be the developer that last changed the object(determined from SAP standard tables), this is of cause not always correct if different developers changed the object between automatic pushes. But its the same in standard SAP

![image](https://user-images.githubusercontent.com/5888506/133590625-ff21b01d-2956-4f86-ae48-bb6fb135bca1.png)

**Comment by sharmaalok2482** [comment]
Thanks it helps.

**Comment by sharmaalok2482** [comment]
Whether every developer has to enter Path Token to schedule job in  Background  for different packages or repositories as in foreground system asks for Path Access Token to push changes to Azure Repository.

**Comment by larshp** [comment]
just one token is required

git as such does not differentiate between users, only way to guarantee identities is via signing
