### ISSUE TITLE
Activation state is serialized for kernel BAdIs implementations but not for classic ones

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#4958]
I just disabled a bunch of BAdI implementations and noticed only the kernel BAdIs showing up as diffs in abapGit. That is somewhat unexpected.

https://github.com/abapGit/abapGit/blob/a72d3314cb839fdc0beaf1609714029a7a478327/src/objects/zcl_abapgit_object_sxci.clas.abap#L280

https://github.com/abapGit/abapGit/blob/a72d3314cb839fdc0beaf1609714029a7a478327/src/objects/enh/zcl_abapgit_object_enho_badi.clas.abap#L90

**Comment by mbtools** [comment]
I think the serialized definition of `sxci` is correct. It should always serialize the active version and not show any diffs if there's an inactive version as well. However, the object should be shown with the `inactive` icon in AG.  

Looks like an SAP bug to me. Inactive classic BAdIs are not listed in `se80` > Inactive Objects either since there's no entry for them in table `dwinactive` (on 750). I will add a workaround for `sxci`. 

I will check `enho` after

**Comment by mbtools** [comment]
I don't see any issues with `enho`. `enho` have the object state (act/inact) which AG shows correctly. In contrast to classic badis, the `enho` have a separate runtime flag for activating. If you flip it, you will see a diff. This way you can actually ship enhancements to customers that don't run until the customer turns them on.

**Comment by flaiker** [comment]
Classic Badis don't have that extra flag? I can transport inactive classic Badis just fine so my assumption was either for both technologies the activation state is serialized or for neither of them.

**Comment by flaiker** [comment]
Note active and activation state is ambigous: There the normal activation state of the implementing object, the class, then kernel badis seem to also have an activation state on their own. In addition to that there's the switch wether the Badi implementation should be called at runtime for both technologies. I am referring to that one.

**Comment by mbtools** [comment]
Classic Badi: https://github.com/abapGit-tests/SXCI

![image](https://user-images.githubusercontent.com/59966492/135896929-2de00742-aac3-42a5-87ce-25d1af50ef1c.png)

The state of the object can be active or inactive. I don't see another switch for the runtime behavior (this is 750).

New Badi: https://github.com/abapGit-tests/ENHO-BADI_IMPL

![image](https://user-images.githubusercontent.com/59966492/135897471-21ae3a99-9ab9-4f4e-a545-e360f0095872.png)

The state of the object can be active or inactive, but there's also a separate flag for the runtime.

As usual, we check the object state (`is_active`) and render it accordingly. No diffs. After #5006, this also works for the classic Badis. 

When you turn off the new Badi, you get the diff:

![image](https://user-images.githubusercontent.com/59966492/135898108-d7ace39a-ba75-4752-b241-2d249581ddec.png)

![image](https://user-images.githubusercontent.com/59966492/135898135-2a070ac9-8e34-46fd-88b4-5a9ab0cc81a1.png)

**Comment by flaiker** [comment]
> The state of the object can be active or inactive. I don't see another switch for the runtime behavior (this is 750).

As I understand it (correct me if I am wrong, I can check in my system tomorrow): this is the switch for the runtime behavior so the equivalent to the "implementation is active" checkbox. There is no equivalent to the active / inactive of kernel badi implementations in classic Badi implementations. Therefore #5006 is incorrect to implement a workaround as this is intended behavior. That's why it doesn't show up in the object activation list and why you can transport it in "inactive state" (=deactivated). The field should rather be serialized. There is no inactive state of the kernel badi implementation for abapGit to access.

**Comment by mbtools** [comment]
understood. you can certainly see it that way. for me, when SAP literally calls something "inactive" (see screenshot above) and then does not show it under "Inactive Objects" that's at least bad design (I say "bug"). 

Anyway, I'm ok with implementing it your way. I will adjust the PR accordingly.

**Comment by flaiker** [comment]
Oh it's definitely very misleading and fortunately named better in the kernel badis. The hint is there usually isn't a button to "deactivate" next to the activate button :)
Thanks!
