### ISSUE TITLE
Auto Pretty Print

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4963]
When dealing with several repositories that use different pretty-print settings, one quickly runs into diffs. For example, one repo requires upper case keywords, the other repo requires all lower case. 

Idea: 

Add optional settings to the repo defining case and indent. When serializing code, abapGit shall pretty-print the code according to those settings (instead of the current user settings). 

Result:

The remote repo will be kept in a consistent "pretty" state.

**Comment by larshp** [comment]
yea, well, it should be a feature of the editor, but we are quite stuck with SE80/ADT as SAP supported editors

guess adding as optional is okay

**Comment by FreHu** [comment]
this would cause inconsistent pretty printing unless you want to rely on abaplint or the native pretty printer to do it, as you can't reliably tell what is a keyword

**Comment by mbtools** [comment]
It works quite well for me:
https://gist.github.com/mbtools/71aa345a8ccb8f375568f9f337569154

However, the gist is limited to the main CLIF code since the exit doesn't work for other sources. Also, the repo metadata isn't available where code is serialized in abapGit. So an implementation for all sources would be invasive.
