### ISSUE TITLE
SSL handshake with github.com:443 failed: SSSLERR_PEER_CERT_UNTRUSTED (-102) on SAP Hana 2.0

### ISSUE THREAD

**Issue by Enzo1975** [abapGit/abapGit#4964]
Hello all. I have read all documents about this issue but I don't have solved my problem. I attach the screenshot. 

ZABAPGIT_TEST_SSL output
![image](https://user-images.githubusercontent.com/32358379/134163286-553715a7-d523-4da1-9e68-98024739cd32.png)

RZ10
![image](https://user-images.githubusercontent.com/32358379/134163439-dfa20984-7c97-4bf8-9aa8-ea33db4e6114.png)

STRUST
![image](https://user-images.githubusercontent.com/32358379/134163572-ae241294-6541-46c0-a52a-70ca2c16015d.png)

Hana System
![image](https://user-images.githubusercontent.com/32358379/134163808-d6efe1ec-147d-40f7-808e-de40834472d0.png)

**Comment by larshp** [comment]
try uplading the digicert certificate in trust,

![image](https://user-images.githubusercontent.com/5888506/134164037-3225b122-b40c-4c21-a088-d484ac944df3.png)

**Comment by larshp** [comment]
first/top choice

**Comment by Enzo1975** [comment]
I think that the problem is in RZ10.

ssl/client_ciphersuites=**918:PFS:HIGH::EC_P256:EC_HIGH** 
![image](https://user-images.githubusercontent.com/32358379/134167239-7318fada-c833-4960-917c-55bab3bef852.png)

**Comment by larshp** [comment]
try uploading the digicert certificate in STRUST, 

guess your local pc is on some VPN/antivirus setup, the SAP server might connect directly

**Comment by Enzo1975** [comment]
solved!. Thanks a lot.
