### ISSUE TITLE
Create repository from ZIP / Use as transport tool

### ISSUE THREAD

**Issue by vonglan** [abapGit/abapGit#4971]
I am currently (mis)using ABAPGit to transport Z-Coding from our normal R/3 system to a sandbox (empty) S/4 system.

For use cases like this, it would be convenient to have a function "New Offline from ZIP" besides "New Online" and "New Offline" in the repository list (in the target system).

**Comment by vonglan** [comment]
Ah, I just saw [in the documentation](https://docs.abapgit.org/ref-packages.html ) that the package name is not part of the repository. However, it is in the filename of the ZIP file.
But the repository name is not available, or is it?

**Comment by mbtools** [comment]
You can name the offline repository and use any package as you like (*). Then import the ZIP. 

(*) An exception is repositories using a namespace. Then the package you use also has to be in this namespace.

**Comment by vonglan** [comment]
I know I can do this (I just did it yesterday).
My suggestion is: Maybe this use case is so popular,  that it would be worth while to have a direct function button (and automatic use of the package name from the ZIP file) for it.

**Comment by mbtools** [comment]
For example, the file name would be `abapGit-main.zip`. What should be the package? `$abapgit`, `zabapgit`? The package also determines transport paths. So I don't think it's something to automate.

I think it would be nice, though, if we could specify the "recommended target package" in the repo settings (.abapGit.xml). Then we could use that for the initial pull if the user doesn't enter a package. This would work for online and offline repos.

**Comment by vonglan** [comment]
The ZIP file names that the program creates for me (when I export a Z package from an SAP system into a ZIP) are always named with the package:
ZS_DEV_TOOLS_COMMON_20210924_100837
ZBAS_20210923_140543
ZX_MULTI_USE_INCLUDES_20210924_100659

**Comment by mbtools** [comment]
I thought you meant the file download from GitHub for example. If you use the AG export, you are right. You could add "ZIP to Package" here:

![image](https://user-images.githubusercontent.com/59966492/135098446-70b3fba8-36db-4b5e-9204-6b4a08e1fa01.png)

I'm not sure if this is something for everyone. You could use a copy of `ZCL_ABAPGIT_GUI_PAGE_EX_PCKAGE` to get started.

**Comment by vonglan** [comment]
Ah, I was not thinking of that part of the process (in the source system), but the other (in the target system).

I would think that many people use (or would like to use) abapGit as an occasional transport tool between systems (for sandbox systems, or occasional distribution of tool packages to other system lines). But I think that it is up to you ("core team") to decide.

It is just a convenience function, so I would not implement it unless you decide that it is worth while.

**Comment by mbtools** [comment]
Your requirements are going more into the direction of an "ABAP Package Manager" (apm). This has been discussed in various places:

https://github.com/abapGit/abapGit/issues/3152, https://github.com/abapGit/abapGit/issues/217, https://github.com/abapGit/abapGit/issues/2236, https://github.com/abapGit/abapGit/issues/2892

I'm working on something like this but don't have any timeline yet.

**Comment by vonglan** [comment]
Well, my suggestion is not about things like dependencies, it is much simpler.

On the other hand, [this comment in one of the issues you mentioned](https://github.com/abapGit/abapGit/issues/217#issuecomment-416171753) - for example - sounds sensible to me.

I close the issue for now. It was just a suggestion.
