### ISSUE TITLE
WDCC - Allow config types other than 00, example 07 for LPD

### ISSUE THREAD

**Issue by Lutzi3** [abapGit/abapGit#4972]
For WDCC (Webdynpro Component Config) at the moment only config type 00 is supported/ hardcoded:
METHOD zif_abapgit_object~serialize.
....
    ls_config_key-config_id = ms_item-obj_name+0(32).
    ls_config_key-config_type = '00'.

To open this up to ls_config_key-config_type = ms_item-obj_name+32(2). would allow other development types. 
One example is 07 which is used for cross client Fiori launchpad config (catalogs and groups). So this would enable the storage and distribution of Fiori launchpad developments.

**Comment by larshp** [comment]
sounds good, pull requests welcome 😄
