### ISSUE TITLE
Generate version before pull

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#4987]
As part of the pull process, it would be nice to have an option to generate a version for the version history before AG changes the object (for objects that support version history). 

Seems pretty easy to do by calling function `SVRS_AFTER_CHANGED_ONLINE_INT`.

Note: Makes sense only for local packages since pulling with transportable packages generates the version automatically.

**Comment by pokrakam** [comment]
Does a version generated by this FM persist after transport?

**Comment by mbtools** [comment]
yes, i believe so

**Comment by mbtools** [comment]
Can be done by adding the function to `DESERIALIZE_POSTPROCESS` exit 
https://docs.abapgit.org/ref-exits.html#deserialize_postprocess
