### ISSUE TITLE
Hint to open shortcuts overview is possibly incorrect

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#4995]
This tiny popup which appears when you load each page
![image](https://user-images.githubusercontent.com/5097067/135680493-f03af3fc-e9f6-4e6f-8d8f-3fec8411c008.png)

![image](https://user-images.githubusercontent.com/5097067/135680582-e741bbb8-49cb-4771-bdfa-d375384794cb.png)

I need to press `shift+?`, not `?` to both trigger and close this window (IE11 control, windows)

is the description inaccurate or is it some kind of browser quirk?

**Comment by mbtools** [comment]
What keyboard layout do you have? On English, `?` needs `shift`:

![image](https://user-images.githubusercontent.com/59966492/135687037-ea1f6318-ff18-412f-8134-02b0e322f502.png)

The JS is using `key` and `keyCode` (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#properties). Maybe it should be just `keyCode` for the `?`

https://github.com/abapGit/abapGit/blob/main/src/ui/zabapgit_js_common.w3mi.data.js#L1625

**Comment by sbcgua** [comment]
> But you're right in that there is actually no ? key on the US English keyboard. What I call the ? key is actually the / key, and ? can be typed by pressing the keys Shift+/. So I think Shift+/ is the most accurate description of what to press to invoke this popup.

I'd disagree, current description is accurate. You need to press "?" to get help. Whatever way I choose. I can switch to Ukrainian and press Shift+7 - that will open help. And it is consistent.

For the benchmark.
- Gmail, Shift + / opens help, which states
![image](https://user-images.githubusercontent.com/15635498/135727630-2122f868-6989-4642-8e76-0b35dd16b427.png)
- Github, press Shift + / opens help. [Help article](https://docs.github.com/en/get-started/using-github/keyboard-shortcuts) states:
![image](https://user-images.githubusercontent.com/15635498/135727650-ad40b1eb-892f-48d9-bdfc-8b2ccc774bf5.png)

**Comment by FreHu** [comment]
i will leave this be
