### ISSUE TITLE
Repo list - revise available commands

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#4996]
In the past these commands were columns in the repo list and took too much space, but this is no longer a problem. Commands are now also filterable per online/offline repo and have shortcuts.
![image](https://user-images.githubusercontent.com/5097067/135681371-f93d30ea-6c7a-4bc3-896c-445ea2bec22a.png)

There is also the minor inconsistency that `Check` actually runs code inspector because previously there was no space for two links. But I personally don't need the syntax check option as I prefer to define a check variant with just syntax check enabled and use that.

I would personally like to add `Diff` as well as `Selective Pull` to the menu. `Remove` would make sense (it's not unsafe, you can just add it again if you accidentally remove a repo), but `Uninstall` should remain an advanced option.

**Comment by mbtools** [comment]
Sure. Just call it 'Pull' but call the `Selective Pull` 

PS: Maybe we should replace the old `Pull` with the `Selective Pull` anyway?

**Comment by FreHu** [comment]
Agreed with only having one pull option as I find the hidden one better. I'll add the menu items after #4997

**Comment by sbcgua** [comment]
+1 for Diff ...
