### ISSUE TITLE
Is ZCL_ABAPGIT_GUI_PAGE_CODI_BASE needed as a separate abstract class ?

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5000]
Is there a reason to have ZCL_ABAPGIT_GUI_PAGE_CODI_BASE as a separate **abstract** class ? Seems like it is used only in the **real** ZCL_ABAPGIT_GUI_PAGE_CODE_INSP

Where used:
![image](https://user-images.githubusercontent.com/15635498/135744988-6945523d-5e29-45f3-9b7b-8df9ac288b42.png)

**Comment by mbtools** [comment]
Syntax check is subclass, too
https://github.com/abapGit/abapGit/blob/main/src/ui/zcl_abapgit_gui_page_syntax.clas.abap

**Comment by sbcgua** [comment]
Yeah, thanks, hmmm ... does it makes sense to separate them into a subpackage ? and rename to be like `sci_base`, `sci`, `sci_syntax` ? hmmm ... 
Closing for now.
