### ISSUE TITLE
Performance issue in method ZCL_ABAPGIT_OBJECT_FUGR->ZIF_ABAPGIT_OBJECT~CHANGED_BY

### ISSUE THREAD

**Issue by JoergNaundorf** [abapGit/abapGit#5016]
We identified a performance issue in the method ZCL_ABAPGIT_OBJECT_FUGR->ZIF_ABAPGIT_OBJECT~CHANGED_BY.
In our special case we have a function group for enhancing material master and there are 521 includes (from Standard) within. The method is called for every include line in the "repo list". So we have 521x521 single selects which lasts on our S/4 System 600+ seconds. 
The SELECT within a LOOP should be replaced with a SELECT ... FOR ALL ENTRIES:

```
    IF lt_includes IS NOT INITIAL.
      SELECT unam AS user udat AS date utime AS time FROM reposrc
        APPENDING CORRESPONDING FIELDS OF TABLE lt_stamps
        FOR ALL ENTRIES IN lt_includes
        WHERE progname = lt_includes-table_line
        AND   r3state = 'A'.                              "#EC CI_SUBRC
    ENDIF. 
```

Next step should be avoiding calling the method for every single include of the same function group again. So you can minimize the count of selects in our case from 271.441 first to 521 and then to 1. Sounds good, or not? ;-)

**Comment by mbtools** [comment]
Good find. Please try #5017

**Comment by larshp** [comment]
@JoergNaundorf try #5019

**Comment by JoergNaundorf** [comment]
That was the right thing :-) it was the repo content list. Now changed_by is only called once - so we have only one Select instead of 271.441 :-)

**Comment by mbtools** [comment]
close this?
