### ISSUE TITLE
Commit page: improve obligatory field handling 

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5029]
Currently we validate obligatory fields in business logic and error looks like this.
![image](https://user-images.githubusercontent.com/17437789/136752343-f50ab93c-1c7b-41b5-baac-c7ff4e6e860b.png)

I think we can improve that a bit and mark fields e.g. like here with asterisk after the label and specific error message and field highlighting.
![image](https://user-images.githubusercontent.com/17437789/136752270-2db2637c-e2f1-4167-b484-0bbe4687a889.png)

**Comment by mbtools** [comment]
Draft:

![image](https://user-images.githubusercontent.com/59966492/137404491-a021fd38-7e63-41ce-b7f5-915ce05ef722.png)

![image](https://user-images.githubusercontent.com/59966492/137404519-7a910f5b-c7c4-4290-ad21-49beff1eb4fe.png)

With staged files on top:

![image](https://user-images.githubusercontent.com/59966492/137404792-5a601394-a5b6-4344-9833-c8d33d37c77b.png)

I'm not sure about the position of the file list. Maybe it should be a user setting.
