### ISSUE TITLE
Patch Page: "Freeze" top of page

### ISSUE THREAD

**Issue by g-back** [abapGit/abapGit#5035]
I'm not too big on HTML, so I'm not sure about the proper terminology.

It would be cool if on the patch page (could also work well on other pages ) the top area could be "frozen". By this I mean that the area remains visible even if you scroll down. 
This way you don't have to scroll to the top to stage or refresh.

![image](https://user-images.githubusercontent.com/27279305/137136615-7dc2768e-74f9-4e39-8e30-a58d2874fa78.png)

Thoughts?

**Comment by mbtools** [comment]
Indeed that would be nice. The term is "sticky". There's a way to do it with CSS but it works only with newer browsers. I don't think it works with IE11 control of SAPGUI. It should with 770 and the Chrome control. Not sure about Java or web GUI. 

It might also need a bit of restructuring the HTML, so we get a DIV at the top that we can make sticky.
