### ISSUE TITLE
Not possible to change theme and icon scaling

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5038]
I cannot change theme and icon scaling in personal settings. It's not possible to choose an entry in the list.

![grafik](https://user-images.githubusercontent.com/17437789/137581956-ddd5de90-e00b-49ce-8d84-c46d1ba59c87.png)

~~Also documentation seems out of sync.~~
https://docs.abapgit.org/guide-settings-personal.html
![grafik](https://user-images.githubusercontent.com/17437789/137582058-bf401461-d224-4346-a500-13e2617e6d3c.png)

**Comment by christianguenter2** [comment]
You're right. That's interesting.

**Comment by mbtools** [comment]
Some observations: 

- The `<span>` is between `<input>` and `<label>`. Probably responsible for the line-breaks. Maybe the `<span>` should go inside the `<label>`. 

![image](https://user-images.githubusercontent.com/59966492/141854843-388c32ee-72c5-4ac1-81d8-e4d4846f861f.png)

- `<span>` nodes are added to `<input type="HIDDEN"...>`. Causes strange link numbers. 

![image](https://user-images.githubusercontent.com/59966492/141855579-3ff89e0b-7cc7-409b-b0c0-0b94e79b927e.png)

I'm not sure if either are related to the issue, though.
