### ISSUE TITLE
Add User-Exit in zcl_abapgit_oo_serializer methods

### ISSUE THREAD

**Issue by AlexandreHT** [abapGit/abapGit#5050]
Method `serialize_abap_clif_source` in `zcl_abapgit_oo_serializer` contains a user exit (`custom_serialize_abap_clif`) that enables me to perform a custom Pretty print different from the one I use on my system (cf. https://gist.github.com/mbtools/71aa345a8ccb8f375568f9f337569154).

Such a User Exit is missing in the following methods:
- `serialize_locals_def`
- `serialize_locals_imp`
- `serialize_macros`
- `serialize_testclasses`

Thanks,

**Comment by mbtools** [comment]
it should be a "code post-processing" exit and also available for object types like `prog`, `fugr`, `type`, and others that have embedded code.

**Comment by larshp** [comment]
user exit referenced = https://docs.abapgit.org/ref-exits.html#custom_serialize_abap_clif

Suggest a new exit `SERIALIZE_POSTPROCESS`, which can be used to change everything

**Comment by AlexandreHT** [comment]
Ideally, user exit execution could be restricted to push. (My use case : Code pushed to public git repo should be formatted but code pulled from other repo (eg. abap2xlsx) should be copied as is, in order to avoid false flag diff after import).
