### ISSUE TITLE
Suggestions for performance optimization at serialization

### ISSUE THREAD

**Issue by Fmueller17** [abapGit/abapGit#5054]
Hello,

I’m working on a SAP project with several 1000 Z-Objects in a git repository. In SAP we have one root package with several sub packages to manage these objects.

It takes a long time (also in parallel mode) until ABAPGIT serializes all the objects in the repository for staging.
I analyzed ABAPGIT a little bit and found two general suggestions for performance optimization.

First one is a pre-filter based on transports to select only the relevant objects (see my pull request #5053  for details).

The second one is that ABAPGIT currently serializes all objects one by one. This means that it executes for each object small selects to the database to get the relevant data.
It would be much faster to package objects with the same object type and select the relevant data with one select from the database for the whole package.
This would increase the performance extremely especially for dictionary objects like data elements, domains, structures, tables and so on. 

Best regards
Frank

**Comment by larshp** [comment]
So, to get this started, I suggest,

**Step 1**
* Add a method `set_object_filter` to `ZCL_ABAPGIT_REPO`, taking a new `zif_abapgit_definitions=>ty_tadir_tt` as input, note that this matches with input parameter `serialize->files_local( IT_FILTER`
* Hook the filter into the repo logic
* Add unit tests

**Step 2**
* On the repository overview page, add a hover dropdown
* when the user clicks the option in the dropdown, the user enters the filter
* click ok, and the staging page is shown
* when the user commits, the user returns to the repository overview page

**Comment by Fmueller17** [comment]
@larshp I adjusted my coding. I replaced my selection screen that was in a function group with the SAP Standard function module TRINT_SELECT_REQUESTS

![grafik](https://user-images.githubusercontent.com/59128840/140659537-06d0af93-abeb-4536-81d0-55c4332ea544.png)

I also tried to add the sub menu to zcl_abapgit_gui_page_repo_over. This is not so easy because the class does not support ZCL_ABAPGIT_HTML_TOOLBAR. It supports only ZCL_ABAPGIT_HTML. So I did it some how (
see [https://github.com/Fmueller17/abapGit/blob/fmueller17/pre_sel/src/ui/zcl_abapgit_gui_page_repo_over.clas.abap#L437](url) for details )

But I need some support with the CSS, because it looks currently so
![grafik](https://user-images.githubusercontent.com/59128840/140660277-d35b40d6-2964-48fb-a7c0-c665eb5d8ba2.png)

**Comment by larshp** [comment]
@Fmueller17 the pull request #5053 changes around 1000 lines of code, with around 200 issues reported by static analysis. If you split the change up into multiple steps which are focused, it makes it much easier to help

**Comment by Fmueller17** [comment]
@larshp sorry I used form based SE80 and it changed the intend. Now only 22 Issues left. I added the main logic to the new class ZCL_ABAPGIT_REPO_PRE_FILTER to touch as less as possible of the existing abapGit coding.

**Comment by FreHu** [comment]
I suggest something like this as a quick solution, the dropdowns can be added as followup
![image](https://user-images.githubusercontent.com/5097067/140701885-765c864e-0ca0-435b-a5c8-65adfb173eca.png)
```abap
    lv_stage_link = ii_html->a(
      iv_txt   = |Stage|
      iv_act   = |{ zif_abapgit_definitions=>c_action-go_stage }{ lc_dummy_key }|
      iv_class = |{ lc_action_class } { lc_online_class } | ).

    ii_html->add( action_link( lv_stage_link ) ).

    lv_stage_link = ii_html->a(
      iv_txt   = |<sup>Transport/Task</sup>|
      iv_act   = |{ zif_abapgit_definitions=>c_action-go_stage_transport }{ lc_dummy_key }|
      iv_class = |{ lc_action_class } { lc_online_class } | ).

    ii_html->add( action_link( lv_stage_link && lc_separator ) ).
```

**Comment by Fmueller17** [comment]
@FreHu thank you. I will adjust it in this way this evening.

**Comment by Fmueller17** [comment]
So I adjusted the menus and removes all abaplint errors. The diff tool shows in some cases that I changed complete methods. But this is not the truth. The reason is, that the pretty printer in SE80 sorts somehow the methods.

<img width="580" alt="grafik" src="https://user-images.githubusercontent.com/59128840/140803506-1184a887-97d4-4f1b-b206-3182a483cec9.png">
<img width="1611" alt="grafik" src="https://user-images.githubusercontent.com/59128840/140803596-b9649c61-c660-421b-afbb-c1c532fa968d.png">

I did some tests. For me it looks fine. Maybe you will find the time to test it, too.

**Comment by larshp** [comment]
@Fmueller17 see comment in https://github.com/abapGit/abapGit/issues/5054#issuecomment-962567954, adding a global singleton is easy and it works, but it can cause issues if forgetting to reset. Also the filter should be a common concept for both online and offline repositories, ie. I expect the changes for step 1 to happen in `ZCL_ABAPGIT_REPO`

**Comment by Fmueller17** [comment]
@larshp I tried to touch as less as possible of the existing abapGit coding. That's why I used the singelton concept. Is this ok for you?
Regarding the offline repository. I think we can add there also the pre filter. Maybe in a next version, because the handling there looks different to the online repository.

**Comment by larshp** [comment]
see my suggestion in https://github.com/abapGit/abapGit/issues/5054#issuecomment-962567954

online/offline: `GET_FILES_LOCAL` is the same for both subclasses

**Comment by Fmueller17** [comment]
@larshp ok, maybe I will find some time at the weekend to have deeper look on it.

**Comment by Fmueller17** [comment]
@larshp I added to the offline repository 
![grafik](https://user-images.githubusercontent.com/59128840/141651317-658efb3a-202e-4a39-89d4-eda34a8ff269.png)

![grafik](https://user-images.githubusercontent.com/59128840/141651328-4181b096-c47d-43df-96e6-2cbda1d15239.png)

**Comment by Fmueller17** [comment]
@larshp I adjusted the coding. I removed the singleton and added an instance of the pre filter interface to a lot of methods as optional parameter. I added also abap unit tests. Your tests can not handle local friends, so I made the private method that I want to test protected and inherited from the class. (I can not test the public methods because this would require transports.) 

But now I'm facing an issue during your checks, were I don't know how I can bypass the error.
[issue](https://github.com/abapGit/abapGit/runs/4555265352?check_suite_focus=true#step:4:236)
![grafik](https://user-images.githubusercontent.com/59128840/146473849-a27f4de9-1c01-42c5-8ee5-c687b12748f4.png)

The coding looks ok for me. How can I bypass this error?
![grafik](https://user-images.githubusercontent.com/59128840/146473653-1d6c8098-136d-4fb4-9c7a-37738a01400e.png)

Is it maybe because of the generic type csequence or the generic type any of the SAP Standard Method?
![grafik](https://user-images.githubusercontent.com/59128840/146473766-c332fdc9-2560-4d07-88f6-4d11ef81e9a7.png)

**Comment by Fmueller17** [comment]
@larshp I changed the obsolate class cl_aunit_assert to the class cl_abap_unit_assert now are all errors and suggestions fixed.
I also added a logic to select always all packages and sub packages. Else there would be a suggestion to remove them during staging if you select a transport that has no objects of the package that you want to stage.

So I found no more bugs.
It would be nice if you could check it and then accept the pull request. #5053

**Comment by Fmueller17** [comment]
I did a refactoring as discussed with @larshp and @mbtools and split the PR in Backend Logic #5226 and Backand + GUI Logic #5227 so the pull request is #5053 is obsolate.

**Comment by Fmueller17** [comment]
I refactored the action links in the pull request #5227 into a toolbar. For details see also #5229

**Comment by larshp** [comment]
all merged now

**Comment by Fmueller17** [comment]
Done
