### ISSUE TITLE
Repo list: 'Show All' is available although everything is shown

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5058]
![grafik](https://user-images.githubusercontent.com/17437789/138841899-94ac6074-e313-4f4b-a1fc-672de74dde06.png)

![grafik](https://user-images.githubusercontent.com/17437789/138841758-4d09240c-1373-4187-98db-eb1421c47bd7.png)

I'd suggest to show then hint only when there is more to be shown.

**Comment by larshp** [comment]
hmm, quick look, I dont think this is possible without sacrificing performance, suggest closing
