### ISSUE TITLE
SICF: suggest to change serialized xml file name from obj_name to URL of icf node

### ISSUE THREAD

**Issue by boy0korea** [abapGit/abapGit#5064]
The problem is obj_name of SICF is generated when length of node name is longer than 15.

Test Case:
1. Create WebDynproABAP application (length > 15)
2. Commit
3. Delete application and create same name again
4. Commit

Test Result: 
- 2 files created despite of same URL

Sugestion:
Keep longname info in internal table.
See below types.
> 
     TYPES:
      BEGIN OF ty_item_longname,
        obj_name_fake TYPE tadir-obj_name,
        obj_type_orig TYPE tadir-object,
        obj_name_orig TYPE tadir-obj_name,
        longname      TYPE string,
      END OF ty_item_longname .
    TYPES:
      ty_item_longname_th TYPE HASHED TABLE OF ty_item_longname WITH UNIQUE KEY obj_name_fake .

`longname` is for external name (filename, item list display) and `obj_name_fake` is for internal object name (in program).
`obj_name_fake` is hash value of `longname`.
longname of SICF is URL.

for example:
- current version
![image](https://user-images.githubusercontent.com/75079431/138997926-f0a315df-7de4-4bb0-9b63-ece60c414956.png)
- developing for longname
![image](https://user-images.githubusercontent.com/75079431/138990818-13c1d100-f3fb-4782-9496-7458efdfdc5d.png)

**Comment by mbtools** [comment]
Hi @boy0korea 

sometimes things take a while, but I finally refactored the serializer interface and made changes to `zcl_abapgit_object_sicf` to address the issue with services generated for WD applications with names longer than 15 characters. 

The final piece is included in https://github.com/abapGit/abapGit/pull/6275.

Best,
Marc
