### ISSUE TITLE
Strip maintenance view generation comments

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5073]
What about removing generation comments from maintenance views ?
Somehow they are not overwritten with force pull (which might be another way to solve the issue). But on the other hand if the history of changes is in git why need those pseudo history in comments ?

![image](https://user-images.githubusercontent.com/15635498/139470480-0f29a55b-c254-4841-924a-afd6d8e87bdc.png)

UPD:
Also. In the context of deploying products to clients. Maintenance views are regenerated from time to time for technical reasons and thus introduce those diffs _at client side_. Which is not supposed.

**Comment by mbtools** [comment]
Both test repos show this issue:

https://github.com/abapGit-tests/FUGR_maintenance_view/search?q=generation
https://github.com/abapGit-tests/FUGR_maintenance_view_variant/search?q=generation

generation date/time and the generator version should be stripped

**Comment by larshp** [comment]
hmm

**Comment by larshp** [comment]
merged, closing
