### ISSUE TITLE
DYNP deserialization does not properly update field attrs (OUTPUT_FLD)

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5078]
Strange issue: deserialization to target system does not update a couple of fields properly. Update ! (the screens were there before. Force pull does not help.

Origin (see output)
![image](https://user-images.githubusercontent.com/15635498/139529157-4d40e2a3-1c1c-4234-9357-ef4a098af28f.png)

Target
![image](https://user-images.githubusercontent.com/15635498/139529170-450c924e-a1d0-4cd2-a0e3-a24aaf31547e.png)

![image](https://user-images.githubusercontent.com/15635498/139529182-d482bdaa-b7a5-4e67-a3a8-df4fa54c8720.png)

~~Also "TEXT" is not updated in some cases~~ - see below

**Comment by mbtools** [comment]
There were some changes/fixes related to `TEXT` #5072 #4973. Might be related.

I don't know about `OUTPUT_FLD`. Same release on source and target? Which release?

**Comment by sbcgua** [comment]
seems like #5072  has solved the `Also "TEXT" is not updated in some cases` part indeed.

`OUTPUT_FLD` - yes, same release. Actually a system copy even.

**Comment by mbtools** [comment]
I think the problem is in `zcl_abapgit_objects_program->deserialize_dynpros`... It does not distinguish between new or update. Since therre's no `RPY_DYNPRO_UPDATE`, we probably have to delete and the insert the new definition:

https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_objects_program.clas.abap#L430

**Comment by sbcgua** [comment]
Implemented forced deletion but it didn't help. Deeps debug showed that (maybe will be useful for someone):
- RPY_DYNPRO_INSERT calls RPY_DYNPRO_CVT_FROM_EXTFORMAT (conversion to fields int format)
- RPY_DYNPRO_CVT_FROM_EXTFORMAT calls I_ADD_DEFAULTS_IN which sets output flag for all editable fields

So probably will have to adjust the screen. Maybe it is not a AG bug. Though it is strange because I can do this combination f field properties manually, but it is overriden on creation. Hmmm

**Comment by sbcgua** [comment]
OK, seems to be resolved in another way. So closing - not an AG issue.

P.S. **MAYBE** it makes sense to separate definitions of DYNPROS in another file other than main xml.
