### ISSUE TITLE
Commit Page Update follow up [repo header missing]

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5079]
After #5048 (which is a really nice and clear redesign, thanks Marc!) the repo header disappeared from the commit page. Which is a regression imho, because it is very inconvenient not to see which repo and page you are committing too. And it is easy to make a mistake after a short distraction. I'd propose to get the header back. Maybe with clickable branch like in stage page (to adjust the target branch). @mbtools 

![image](https://user-images.githubusercontent.com/15635498/139529845-835a069c-81d9-417d-b438-66d8653df77c.png)

P.S. Also, I'd say the summary leaves some room for improvement. The coloring is very similar to the main form and so it is not immediately visible where to enter commit comment, which also may change it's place. I think it should be redesigned a bit. I'll probably come with some suggestions separately. I think it should be closer to how it's done in diff page

![image](https://user-images.githubusercontent.com/15635498/139529939-476ad354-f119-4bc4-a132-7db705da598c.png)

**Comment by mbtools** [comment]
Yes, I copied some other form to start with and forgot to add the repo topbar to it. 😮 

I like the suggestion with the three colored boxes. 😃

**Comment by larshp** [comment]
also, the current branch used to be shown?

**Comment by larshp** [comment]
and the repository name / url?

**Comment by sbcgua** [comment]
yeap, there was a standard header before
