### ISSUE TITLE
SAP GUI for Java: New commit page is non-functional (mac)

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5082]
:(

![image](https://user-images.githubusercontent.com/15635498/139585074-b85c879f-1747-4f36-9708-3431cff1f2d4.png)

It keeps asking name email and comment.

@mbtools

**Comment by mbtools** [comment]
odd. the other forms like "settings" work? i will test tomorrow on another machine that has JavaGui installed 

It might be related to https://github.com/abapGit/abapGit/issues/2448 due to the `@`

**Comment by mbtools** [comment]
Hmmm. I tested with 7.70 rev 3 (latest) and the commit form works without problems 🤷 

![image](https://user-images.githubusercontent.com/59966492/139679883-e58c9e07-3769-4132-b137-ebd26c740854.png)

**Comment by sbcgua** [comment]
The version I used was 7.4 ... will check how it goes with a newer one

**Comment by christianguenter2** [comment]
@mbtools did I get you right, you've been able to commit with SAPGUI for Java without problems?
It doesn't work for a colleague of mine with this error but he's on MacOS.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/17437789/140976470-2ac922bf-a9a0-4bb9-8e05-36d755292943.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/17437789/140976586-99e031bf-1d07-4b49-8bb9-2cec2130c053.png)

It once was fixed with #790 actually.

**Comment by mbtools** [comment]
Yes, indeed. Same version.

![l1u7vqeB02](https://user-images.githubusercontent.com/59966492/140995230-1d2e2476-531b-49d8-a758-5efa14697835.gif)

**Comment by mbtools** [comment]
Retested with Java GUI. 7.80 rev 1

![image](https://user-images.githubusercontent.com/59966492/205346214-35c71f00-bfec-40cb-839c-93ca3b10bb3a.png)

There is some bug here. After "Stage" the add/remove column does not show the "add" link.

JavaGUI:

![image](https://user-images.githubusercontent.com/59966492/205346552-ea77f0a5-75f3-42b1-9fd3-ca58836dec50.png)

[
 WinGUI for comparison:

![image](https://user-images.githubusercontent.com/59966492/205346610-feaeaada-8f9e-4d8c-bb29-4f4f11d6ec40.png)
]

After clicking "add" in the column header, it seems like it's working 

![image](https://user-images.githubusercontent.com/59966492/205346901-fbddfc69-e3f7-4321-bd70-2459dc1f331a.png)

but clicking "Commit" leads to the error described above

![image](https://user-images.githubusercontent.com/59966492/205347235-57745975-b370-4061-abd7-eb1d43b271f8.png)

`StageHelper` is using `window.sessionStorage` which does not seem to work on JavaGUI:

![image](https://user-images.githubusercontent.com/59966492/205351204-996c2f51-d3bc-4023-ab32-df2b4bcb11c8.png)

My JS skills aren't good enough to fix this 😉

**Comment by AndreaBorgia-Abo** [comment]
![immagine](https://user-images.githubusercontent.com/25269970/219874568-3d18e150-70ef-4700-90ff-115d5841ea04.png)
Same Java GUI, this time on Linux.
(aG is developer version 1.121.0)

**Comment by mbtools** [comment]
SAP GUI for Win 8.0 issue is due to Chrome-based control (https://github.com/abapGit/abapGit/issues/4841) 

See https://docs.abapgit.org/guide-sapgui.html

**Comment by AndreaBorgia-Abo** [comment]
Reinstalled 8.00, switched control, checking soon...

**Comment by christianguenter2** [comment]
7.80 rev 4 'Add Filtered and Commit' doesn't work. Nothing happens.
![grafik](https://github.com/abapGit/abapGit/assets/17437789/05cab4b8-6b4d-4457-8b22-914457446ba9)

**Comment by christianguenter2** [comment]
I try to draw SAPs attention to this issue.
](https://blogs.sap.com/2022/05/25/sap-gui-for-java-7.80/comment-page-1/#comment-693974)

**Comment by christianguenter2** [comment]
Colleague of mine raised an issue at SAP. Let's see where that goes.

**Comment by christianguenter2** [comment]
> Colleague of mine raised an issue at SAP. Let's see where that goes.

Good news!

Case at SAP was successful. With unofficial release 7.8 rev5.2 the issues are fixed and according my colleague abapGit with Java Gui is fully functional on his Mac with ARM processor. I assume it will be released 7.8 PL 6 in the near future. Kudos to SAP support who did a great job 🥇

**Comment by mbtools** [comment]
7.8 PL 6 is available. Anyone available to test this?

https://me.sap.com/softwarecenterviewer/73555000100200015948/MAINT

**Comment by christianguenter2** [comment]
Installed it and did some tests. Looks good at first sight. Asked my colleague who uses it on mac regularly to more testing.

**Comment by AndreaBorgia-Abo** [comment]
FWIW tested on Linux against A4H, commit worked
![grafik](https://github.com/abapGit/abapGit/assets/25269970/eb5e3e3a-4329-4d5c-ac01-cdd4870ba941)

**Comment by mbtools** [comment]
Here are the actions to test (because they use JS to trigger event): 

On staging: 
- commit (looks like it works 👍 )
- filtering
- patch (and then stage)

On diff:
- refresh local
- refresh all

Vimium-links, yank mode:
- yank_to_clipboard

**Comment by christianguenter2** [comment]
:heavy_check_mark: working
- commit
- filtering
- patch
- refresh local 
- refresh all

:x: not working
- hotkeys
- vimium features
- command palettes

**Comment by larshp** [comment]
but overall, its pretty good news?

**Comment by christianguenter2** [comment]
> but overall, its pretty good news?

Yes absolutely. All major features working.

**Comment by christianguenter2** [comment]
Feedback from colleague testing on mac "works wonderfully".
