### ISSUE TITLE
Get rid of double settings page

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#5088]
We can merge the two separate settings to eliminate confusion. 
- Tabs for global settings will always be shown
- If the page is opened with a repo key, the repo settings tabs will be shown

![image](https://user-images.githubusercontent.com/5097067/139739373-9866a34b-062f-407b-8301-867065d5f79b.png)
![image](https://user-images.githubusercontent.com/5097067/139739437-7b6d447a-2bb0-42b3-acb0-7695409cf587.png)

Just keep one of the settings buttons
![image](https://user-images.githubusercontent.com/5097067/139739633-60fffffd-a578-4471-ae4c-b743282a5734.png)

**Comment by mbtools** [comment]
On the repo page, get rid of button 2 and call the repo settings from button 1? Is that what you mean?

![image](https://user-images.githubusercontent.com/59966492/139742126-1516d7c6-1a37-4aa4-9088-21af02381123.png)

On the repo page, the button should then probably say "Repo Settings" to make clear that it's different. Sounds good.

**Comment by FreHu** [comment]
Yes, I always press the button with the text by accident and have to go back. I also find it difficult to navigate new users to the correct settings.

**Comment by sbcgua** [comment]
I guess it makes sense to change the icon for one of them. But not merge - it would be less convenient

**Comment by sbcgua** [comment]
hmmm ... all most obvious were used ... https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=settings&m=free :)
Maybe user/cog ? Or maybe create a new one like that git logo + cog ?

**Comment by mbtools** [comment]
As you can see in #5282, the suggestion to change one of the setting icons wasn't so great. 

I propose the following changes:

- Remove "Global/Personal Settings" and "Utilities" from the Repo View. They are not related to a repo and rarely used from there. So removing will simplify this view and avoid the confusion
- Replace the cog-icon in the Repo View menu with "Settings"

Overall a much cleaner and consistent look:

![image](https://user-images.githubusercontent.com/59966492/150585835-43adc58f-371c-4291-8efa-e227fed53bdb.png)

**Comment by larshp** [comment]
looks good to me
