### ISSUE TITLE
Switch tag/branch overview performance

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#5090]
attempting to switch tag instantiates `zcl_abapgit_branch_overview` which can take forever to fetch all the objects and then possibly fail anyway due to the exception below
![image](https://user-images.githubusercontent.com/5097067/139741793-d4e3381b-72d9-4358-b393-2209bef9d8c8.png)

**Comment by larshp** [comment]
need #2215

**Comment by mbtools** [comment]
`zcl_abapgit_branch_overview` does not exist anymore.
