### ISSUE TITLE
Creating new branch at commit page

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5091]
Follows #5087 @mbtools 

> I see the commit as the final step, where you confirm what will actually happen. Switching things will confuse and the file statuses will be incorrect (we would have to refresh from remote and calc diff again). Switching or creating branches should happen on the staging page.

- I agree that **switching** at commit page is a bad idea
- but **creating new branch** is actually good, and it is a proper place in terms of flow

How it happens now: I stage, choose the files, maybe validating the diffs also, (so spending some time), then "Ah, I had to switch the branch!", and I do create a branch directly from the stage page, which also triggers re-fetch and re-serialization so it is slow and annoying. It would be nice to specify a branch name and then AG would create and push in one step.

Well, maybe this option should be at stage page ... but intuitively I would expect it at the latest moment before the commit. Also the commit page has an appropriate form, while at stage there is no good place for it. And also "new branch" would not create conflicts.

imho.

**Comment by FreHu** [comment]
What about a user setting to show a warning popup before comitting to master/main?

**Comment by sbcgua** [comment]
Mmm, I don't think so. There maybe projects with and without this requirement. Also projects (like in my case) when it is needed some times. Both "productive" and opensource - for opensource I usually commit to master but sometimes to branches ... so certainly it is not not the most frequent feature. But it happens. And currently it is inconvenient.

**Comment by sbcgua** [comment]
Actually, to define it properly, the inconvenience goes mostly from the fact that re-serialization takes time ... otherwise creating branch from stage is not terrible

**Comment by mbtools** [comment]
Creating a new branch does make sense on the commit page. Same as on GH: 

![image](https://user-images.githubusercontent.com/59966492/139850487-47c29a44-46bc-4324-a562-f57503e91325.png)

so +1 for adding an input field to the commit form. 

Protecting the main branch is a feature on the remote side already. If it's protected, you will get an error in AG. I'm not sure if the git protocol reveals the branch protection to prevent users from even trying to push to `main`.
