### ISSUE TITLE
Performance problem, READ TABLE CT_TADIR

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#5095]
thanks to @Fmueller17 for the measurements,

![image](https://user-images.githubusercontent.com/5888506/140024553-b54fe8ed-4f92-4546-8db9-de654f1790b5.png)

![image](https://user-images.githubusercontent.com/5888506/140024266-890adc43-70fc-47aa-823c-56c803d8758d.png)

**Comment by Fmueller17** [comment]
I will work on it. When I find the time.

**Comment by larshp** [comment]
closing

@Fmueller17 if you have time, can you post the newest measurements in this issue?
