### ISSUE TITLE
Serialization of SAP Standard Includes in a Z-function group

### ISSUE THREAD

**Issue by Fmueller17** [abapGit/abapGit#5099]
We have an enhancement of the material master in a Z-function group. This Z-function group contains a lot of SAP Standard Includes. AbapGIT generates during the serialization also files that contains these SAP Standard Includes. Is this a bug? Will the deserialization overwrite the SAP Standard Includes?

**Comment by mbtools** [comment]
The repository must include only objects that are part of the associated SAP package (or sub-packages). Therefore, none of the SAP standard includes should be serialized.

https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_fugr.clas.abap#L594

The select above is not sufficient to filter out includes that are part of standard function groups (since they don't have a `tadir` entry). 

Determining the function group and then package will take too long. Try adding a `select for all entries` on `trdir` for the includes and eliminate all that have `cnam` and `unam = 'SAP'` (or `like 'SAP%'`).

**Comment by Fmueller17** [comment]
@mbtools 
I made a test and created a new function group with the include LSEWBSYM.
![grafik](https://user-images.githubusercontent.com/59128840/140183579-c1de0995-6f7d-4c91-9ef9-619009c1eba9.png)

It will be staged
![grafik](https://user-images.githubusercontent.com/59128840/140183810-1ffb06b6-bae9-40f1-90ed-246423f4a79a.png)

I tried to find out how SE80 is determining the package and the original function group
![grafik](https://user-images.githubusercontent.com/59128840/140184121-ce567470-65ff-4462-9578-385a3213eb05.png)

I found this coding, it determines the function group of the include
![grafik](https://user-images.githubusercontent.com/59128840/140184543-ce2bcbb6-df65-4d82-95ec-3200379d3973.png)

![grafik](https://user-images.githubusercontent.com/59128840/140184686-599f1837-e311-4e98-b35c-788019fbcbab.png)

I think we should add it to the method.

What do you think?

**Comment by mbtools** [comment]
Let me see if I understand: For each include, determine the function group based on the logic in your screenshot and compare it to the function group we are serializing. If it's different, then skip this include. 

Sound good to me.

**Comment by Fmueller17** [comment]
Thanks @mbtools I will take care on it, when I find some time.

**Comment by Fmueller17** [comment]
@mbtools I solved it with the pull request #5134 

the include LSEWBSYM will be excluded from staging and the repo view

![grafik](https://user-images.githubusercontent.com/59128840/141654455-d0365d73-e7e9-42c4-9e33-d9591a2f0f26.png)

![grafik](https://user-images.githubusercontent.com/59128840/141654494-fc5fd33e-5190-480f-8dc3-15763d0f8c42.png)

![grafik](https://user-images.githubusercontent.com/59128840/141654392-0cb36cde-f291-4387-81a1-baa8cc0d8a0b.png)

**Comment by mbtools** [comment]
how the serialize runtime for your big repo after this change?

**Comment by Fmueller17** [comment]
@mbtools 
I checked it whith the Serialization Performance Test Tool:

Only the FUGR with the Material Master enhancement **without** the new check: 5,797720 sec.
Only the FUGR with the Material Master enhancement **with** the new check: 0,550587 sec.

The whole repository (7.587 objects) **without** the new check :165,141670 sec.
The whole repository (7.587 objects) **with** the new check: 139,610175 sec.

**Comment by mbtools** [comment]
good improvement. as I mentioned, you might want to look into DB tuning next.
