### ISSUE TITLE
OTR with alias

### ISSUE THREAD

**Issue by boy0korea** [abapGit/abapGit#5103]
[Online Text Repository (OTR)](https://help.sap.com/viewer/44ea407a679c4dd192f184fa5ca0fdc7/LATEST/en-US/499ab0ced160200de10000000a42189c.html)

OTR is used in WDA, BSP, ...

The main key filed of OTR is SOTR_HEAD-CONCEPT and it is generated value.
The alternative key of OTR is SOTR_HEAD-ALIAS_NAME and it is unique name.
OTR without alias are useless outside WDA or BSP but OTR with alias are meaningful.
In ABPA code, OTR text can get using `CL_WD_UTILITIES=>GET_OTR_TEXT_BY_ALIAS( )`.

TADIR object type for short OTR is SOTR.
TADIR object type for long OTR is SOTS.
SOTR or SOTS exists just 1 line for the package.
If this object type exists, it means the package have one or more OTR.
If not exsist, there is no OTR.

How about serialize OTR with alias?
The serialized file name will be "package.sotr.xml", "package.sots.xml".

**Comment by mbtools** [comment]
We already have https://github.com/abapGit/abapGit/issues/4480 to discuss SOTR/SOTS. There are several issues with it mentioned there. Let's close this and discuss in #4480
