### ISSUE TITLE
need help, AJSON deep structures

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#5104]
We want to convert JSON to ABAP types, see https://github.com/abapGit/abapGit/blob/a6685f03ca57f85cf88774acb567ee7c5d3a0ac0/src/objects/zcl_abapgit_ajson_cnt_handler.clas.abap#L57

Is it possible to handle deep structures with AJSON? We found tables and other types on the ajson Readme page, but what about the deep structures?

Thanks,
Albert

**Comment by larshp** [comment]
suggest making a small example, eg a REPORT that can be copy pasta'ed to reproduce the issue

**Comment by albertmink** [comment]
AJSON does deep structures. // closing
