### ISSUE TITLE
Documentation: Split off into separate repository

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5110]
The size of docs has increased over time to ~2.5 MB. When working on the developer version, this data is fetched by abapGit unnecessarily and quite frequently. 

Also changing docs triggers CI processes unnecessarily and after merging requires rebasing other PRs which triggers CI again. 

The suggestion is to move the docs into a separate repository.

**Comment by larshp** [comment]
yea, I cannot think of why not, leave the issue open for some days, then we can move it

**Comment by mbtools** [comment]
Note: screen shot for readme is in /docs/img

**Comment by larshp** [comment]
something like this, https://github.com/abapGit/docs.abapgit.org/pull/1 ?

**Comment by mbtools** [comment]
That's it

**Comment by larshp** [comment]
hmm, might want to move it with history, https://stackoverflow.com/questions/41811986/git-move-directory-to-another-repository-while-keeping-the-history, need some time to look into that

**Comment by mbtools** [comment]
history would be nice. maybe try importing all and then deleting /src/ etc.

https://docs.github.com/en/github/importing-your-projects-to-github/importing-source-code-to-github/importing-a-repository-with-github-importer

**Comment by larshp** [comment]
hmm, yea, hmm, it will give too much history 😄

**Comment by larshp** [comment]
like this https://github.com/abapGit/docs.abapgit.org ?

**Comment by flaiker** [comment]
Adding to the other links I used this one which should have now only gotten the commits that affected the /docs folder and also filtered their content: https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by larshp** [comment]
documentation is up, https://docs.abapgit.org

but icons are broken

**Comment by mbtools** [comment]
all done. thanks!
