### ISSUE TITLE
Community Call, December 2021

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#5118]
Time: 7nd December, 15:00 CET

Duration: 1 hour scheduled, no recording, in English

Invitations: Open for all, message me your email address [on Slack](https://abapgit-slackinviter.herokuapp.com/), and I'll forward you the invite

Agenda

* Welcome
* Please add suggestions in the comments below, and I'll update this list

**Comment by mkysoft** [comment]
Adding customization/transaction tables data to repo.

**Comment by pokrakam** [comment]
If we run out of topics, we can always look at / discuss some of the more general issues. #5110 looks like something to discuss.

**Comment by larshp** [comment]
will send an inviation out sometime in januaray
