### ISSUE TITLE
Avoid double action runs

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5147]
Suggest to change from

```yaml
on:  
  push:
  pull_request:
```

to

```yaml
on:  
  push:
  pull_request:
    branches:
      - main
```

**Comment by larshp** [comment]
yea, well I did try, but I could not get it working

**Comment by larshp** [comment]
well, now there are 8 steps instead of 6, it makes it worse IMHO

**Comment by larshp** [comment]
and build + test is skipped on merge, which is bad

**Comment by mbtools** [comment]
looked easy but too many options. going back to what it was

**Comment by larshp** [comment]
😀

**Comment by larshp** [comment]
close?

**Comment by mbtools** [comment]
i've tried other "action filter" solution. nothing really working great.
