### ISSUE TITLE
TABL - wrong deserialization of foreign keys

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5152]
Issue. **In the original system** there is a strcture with check tables. In an include !

![image](https://user-images.githubusercontent.com/15635498/142729188-9900619b-a48c-4fff-abc6-92ba82172a66.png)

The DD08L contain noinherit flag = N (so "inherit=yes")

![image](https://user-images.githubusercontent.com/15635498/142729250-16a2a7d1-f2b2-4c15-adc6-546f2837fc9c.png)

Thus TABL object removes it from the XML

![image](https://user-images.githubusercontent.com/15635498/142729275-5ed34a73-d5da-425c-8f60-977ad5d8b6c7.png)

In the target system, the same object produces a diff. Force pull does not help. Note the noinherit = Y. Apparently, the records are autoadded 

![image](https://user-images.githubusercontent.com/15635498/142729322-0725d46f-ea90-44e1-b4dd-d79869bfa712.png)

By the way DD08L contains the records. And the SE11 does not show them which is strange (or I'm just mixing the tables)

![image](https://user-images.githubusercontent.com/15635498/142729514-dc000447-3890-4862-a288-c852649c7055.png)

Apparently records are auto added in `DDIF_TABL_PUT` but not 100% sure. Also not sure why this happened in the first place. As I understand stripping inherited records added relatively recently. But this looks like a bug because force pull does not help, it should  fix things. I'm see it in at least 2 target systems.

**Comment by mbtools** [comment]
I think there was some relation to standard includes (SAP namespace) and those being different in different releases leading to different inherited settings. 

In general I believe, if something is inherited it should not be part of the object. In the case above, I'm not sure if the setting is part of the include or the table (or both). hmmm

**Comment by sbcgua** [comment]
No, the include is also own. And one of the target systems is the original's copy

> In general I believe, if something is inherited it should not be part of the object. In the case above, I'm not sure if the setting is part of the include or the table (or both).

Sure, that makes sense. I think serialization is correct in this case. Setting is a part of the include. But the DD08L record is then associated with the compound structure.

**Comment by sbcgua** [comment]
Just made a test: creating a new structure (ZTEST) with that include does adds DD08L and DD05P records for the ne structure (ZTEST) ... so it would be expected to preserve it with the deserialization

**Comment by mbtools** [comment]
here's the history https://github.com/abapGit/abapGit/issues/4897 #4865

**Comment by sbcgua** [comment]
Looks line `Add_for_deleted` routine of `DDIF_TABL_PUT` scans DB for existing and not explicitly received records of `DD08L` and adds them to the table definition but with the forces `Y` flag for `noninherited`. This is exactly what happened in my target systems ...

**Comment by sbcgua** [comment]
Ok, a lot of SE11 debugging ... it does expand table structure on the way and recreates the FKs. Here is a full stack for history

```
RS_WORKING_OBJECTS_ACTIVATE
  RS_WORKING_OBJECT_ACTIVATE -> activate_object @483
    activate_ddic_objects @95
      lcl_dd_worklist=>activate @1139
        RS_DD_WORKLIST_ACTIVATE
          DD_WORKLIST_ACT
            DD_MASS_ACT_C3
              ma_lev_activate_c3 @342
                start_function_parallel
                  start_task
                    app_call_function
                      DD_MASS_ACT_PARALLEL
                        mt_act @158
                          mt_tabl_act
                            DD_TABL_ACTM
                              DD_TABL_INNER_ACT
                                expand_include(rattbutl) @251
                                  DD_TABL_EXPAND
                                    expand_dd03p
```
For me it seems like a simple fix ... will PR ... but ... maybe some DD gurus should validate...

**Comment by mbtools** [comment]
Will have a look this week. Let's add your test case to https://github.com/abapGit-tests?q=tabl
