### ISSUE TITLE
Command palette shows only favorite repos if "Only Favorites" is checked

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5154]
... which is inconvenient.

**Comment by mbtools** [comment]
Yes, but "only favs" was implemented so we don't have to read all repo metadata (performance). It will take some refactoring of the persistence like #4555 to allow instantiating all repos again.

**Comment by FreHu** [comment]
Marc is right, the repo name is in the xml so everything would have to be deserialized. 
But maybe there could be a threshold for this behavior - if the system has <100 repos (I was optimizing for a system with 700+), the performance will be acceptable.
