### ISSUE TITLE
Serialization removes content of include (FUGR)

### ISSUE THREAD

**Issue by ed-holland** [abapGit/abapGit#5155]
AG: 
![image](https://user-images.githubusercontent.com/53995991/142876315-13d06c86-2873-4b82-9604-03189fe40deb.png)

We have includes that originate in one function group and are reused in several other function groups.
This has worked fine so far. Now AG is upgraded and the include is now seen as empty locally although it contains code.
![image](https://user-images.githubusercontent.com/53995991/142876117-da4348ba-3bca-4a7b-a4f1-8aaccc94433b.png)

Top definition of FUGR
![image](https://user-images.githubusercontent.com/53995991/142876430-12470acd-adf5-406c-a66b-9c335409802e.png)

It seems the serialization is ignoring the content. It also sees the changer as UNKNOWN.

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/pull/5134

If an include belongs to a different function group, it is only serialized as part of that function group.

**Comment by mbtools** [comment]
On a side note, I consider it not good practice to reuse function group includes this way. Make reusable code a stand-alone include or better put the code in a class 😉

**Comment by ed-holland** [comment]
Since i have worked with Abap (I'm a R/2 guy), these best practices have changed over time.
Just wrapping everything in classes has not increased readability for me, but with that i am probably a dying breed.

If this is the way that serialization will stay (it worked fine with the release from 3 months ago) i will have to adapt even though this means changing AddOn packaging.

**Comment by mbtools** [comment]
I like the good old includes, too. 

However, the old approach had two big disadvantages:
- It would serialize reused SAP includes -> big no-no for public repos
- It would serialize reused includes multiple times -> trouble if one of the copies is changed 
Both are a potential performance issue as well.

In short, the new approach is the way to go.

**Comment by ed-holland** [comment]
Ok, will rename the includes outside the fugr.
