### ISSUE TITLE
repo overview ordering similar to native git

### ISSUE THREAD

**Issue by jfilak** [abapGit/abapGit#5164]
I often need to deal with huge packages where I care only about few objects.
I version only the objects I am interested in and I leave the other objects as untracked (some super simple "add to ignore would be nice").

In the repo overview, I would love to see  the following order:
- Modified objects remote (or both sides)
- Only remote objects (new remote objects)
- Modified objects local
- Only local objects (new local objects)
- Unmodified objects

**Comment by mbtools** [comment]
Did you try clicking on the "Status" column header? Sorting up or down gets you pretty close to what you describe. 

![image](https://user-images.githubusercontent.com/59966492/143486083-3c07d7ab-d46c-46f4-ad61-ddf485b039f3.png)

**Comment by jfilak** [comment]
Nice tip!
Can we make the "descending" sorting default at least?
However, I still believe the native like grouping would be usefull.
Even more, I don't need to see the list of all unmodified objects, what's the added value of having them listed?

**Comment by christianguenter2** [comment]
I think 'View' > 'Changes only' could be your friend. I there are no modified objects it looks like this.
![grafik](https://user-images.githubusercontent.com/17437789/143488444-7b2ab9bf-f7d2-455e-9a08-9af95c35e762.png)

**Comment by jfilak** [comment]
Good tip again. Thank you!
How can I make that default?

**Comment by sbcgua** [comment]
as far as I remember it should autosave to user profile (or maybe per repo - I don't remember)

**Comment by mbtools** [comment]
View settings are indeed user-specific. Sort order is currently not saved.

**Comment by flaiker** [comment]
@jfilak #5257 should help, can this be closed?

**Comment by jfilak** [comment]
Thank you!
