### ISSUE TITLE
Tutorial Videos

### ISSUE THREAD

**Issue by yasinnaal** [abapGit/abapGit#5167]
I wish if you can create short tutorial Videos explaining the project, benefits with real full examples. It will be very very helpful.

**Comment by larshp** [comment]
Suggest attending abapconf, https://www.abapconf.org/#/agenda

@mbtools has a session regarding abapGit 😄 

there is also some material linked from https://docs.abapgit.org/other-articles-and-presentations.html

**Comment by yasinnaal** [comment]
Ok Thanks
