### ISSUE TITLE
Problematic formatting for WAPA entries

### ISSUE THREAD

**Issue by DerGuteWolf** [abapGit/abapGit#5178]
cf attached screenshot.

With those long names, proper display needs a very wide monitor, has even then still problems with aligning name and diff indication. 
Furthermore a lot of space is "wasted" on the left.

![Scrolling Screenshot](https://user-images.githubusercontent.com/638512/144859007-e75b49db-1d64-409d-aa97-e957efe6cf1e.png)

This is vwith 1.113.0

**Comment by mbtools** [comment]
The quick solutions are
- flip to folder view or
- don't display files
which I would recommend for projects with deep package structures and a large number of objects anyway. 

Adding line breaks into the path doesn't make this better I'm afraid. The problem is the repeating parts of the path. So here's an idea:

The first line for the files of an object could be the main object name (everything up to and including the `.wapa` in your case).
Subsequent lines would be only the remaining part of the filename (subobjects).

I will give it a try.

**Comment by mbtools** [comment]
Here's what it could look like for a `.fugr`:

![image](https://user-images.githubusercontent.com/59966492/144868599-4deee228-ae98-46dc-bfec-c7dd796c3574.png)

Certainly solves your problem... but as you can see in https://github.com/abapGit/abapGit/pull/5169, there was no consensus on shortening the path/filenames. 

My suggestion would be an exit where everyone can implement their own logic.

**Comment by DerGuteWolf** [comment]
Your idea looks very good!

Not displaying File (Paths) is problematic when I want to see which files/FMs exactly changed.

Using folders does not completly solve the problem, since it is still veeeery wide.

Exit would be nice, but this needs to ensure that the diff markers are the correct lines (which is currently not the case, see my screenhot above).

**Comment by mbtools** [comment]
we can certainly change the min.width of the diff column so it won't wrap.

**Comment by mbtools** [comment]
can you test https://github.com/abapGit/abapGit/pull/5180? is this wide enough to avoid wrapping of the status column?

**Comment by DerGuteWolf** [comment]
yes, 100px would be enough, although 70px would also be enough, however 60px is not enough

**Comment by mbtools** [comment]
if the list is aggregated then it shows `diff(x) [-|-]` including the number of files. that why I put it to 100

**Comment by DerGuteWolf** [comment]
ok, but in the aggregated list I don't have the problem since the long file paths aren't shown.
In the folders view it is
x changes [-|-]
so even longer but of course also even less likely to give problems.

BTW: I exclusivly use the display with filenames as we most of the times push on NetWeaver 7.50 and pull on 7.55 (S/4HANA) (and pull on ABAP Environment, but this is a different story...) and this causes certain inherent differences, so I need to look at the files to see if and what is really different.

**Comment by mbtools** [comment]
I see. I will reduce to 70px

I also have filenames on all the time. the exit will give the option to shorten the display, for example, in the way I have shown above.

**Comment by DerGuteWolf** [comment]
@larshp thanks for the user exit. I would need also #5180 to get a complete solution. Even outside WAPA the display is problematic currently:
![example screenshot](https://user-images.githubusercontent.com/638512/145189879-cc9d9562-827d-407e-9cdd-8483e01657f6.png)

**Comment by DerGuteWolf** [comment]
@mbtools Unfortunatly I can't reopen since @larshp and not me closed this incident.

**Comment by mbtools** [comment]
does this work now using the exit?

**Comment by DerGuteWolf** [comment]
The combination of 5180 *and* shortening via user exit *and* full screen display (ie detaching SAP GUI in eclipse) works, but is not pretty since a lot space is wasted on the left side
![image](https://user-images.githubusercontent.com/638512/152063584-5691fbf2-e308-4cd9-a8a8-23acbf2ca7f4.png)

**Comment by mbtools** [comment]
the shortening should apply to the other wapa.ui5... files, too. but they don't have an extension. the extension is also relevant for syntax highlighting and editing directly in the remote repo (ie GitHub, VScode etc).

from your wapa_fiori test repo, it looks like these are either `.js` or `.json` files. any other possibilities?

so serialize should detect the format and add them with extension to `io_xml`. and deserialize should ignore the extension, of course. i'll give it a try...

**Comment by DerGuteWolf** [comment]
I don't really know, since I have treated the deployed fiori apps as a Blackbox and have not really thought about editing the individual files inside the sap system since there are strange cross references and shadow lists, etc. We change in the original vsc/bas project and redeploy. We use however abapgit for distribution between our and some costumers sap systems.

**Comment by mbtools** [comment]
we decided against #5317. so it's back to the shortening exit. Add some logic there to detect these "UI5..." files and replace the beginning with "...".

**Comment by mbtools** [comment]
but in your last [screenshot](https://github.com/abapGit/abapGit/issues/5178#issuecomment-1027358507) it still shows the full object name with namespace as part of the file name. 

instead of
`#neo#skd01_srv_hub_o2_op/#neo#skd01_core_com.wapa.ui514783ac34137995942bbb3596b85d3761cb5b436`
they should just look like this:
`...ui514783ac34137995942bbb3596b85d3761cb5b436` 

this should make the filename column only half as wide

**Comment by DerGuteWolf** [comment]
Yes, I could make stuff even smaller.
But still a lot of space is wasted on the left.

**Comment by DerGuteWolf** [comment]
IMHO the easiest gain would be an option to reduce the left most grey area which is completely empty

**Comment by mbtools** [comment]
#5323
