### ISSUE TITLE
Pulling a BSP App (WAPA) does not update the changed files anymore

### ISSUE THREAD

**Issue by DerGuteWolf** [abapGit/abapGit#5179]
With current version 1.113.0 (tried both with head version and with standalone version) I tried to repeatedly pull a package from an internal repo which contains among other stuff some BSP applications (which are in fact fiori applications). Changes in the files of the BSP applications were correctly detected and shown, I selected in every try "overwrite local object" upon pull but neither with pull nor with selective pull the files were updated in the system despite repeated attempts. I tried this then with standalone version 1.109.0 where it worked immediatly.
I have another internal repo where also a BSP/Fiori App with updates is shown but is not updates with pull. I kept this repo in this state. Is there anything I could do to diagnose this problem?

**Comment by mbtools** [comment]
There were only two changes between 1.109 and 1.113 related to WAPA:
- Removal of JUMP code (no relation to your issue)
- Change of SELECT / SORT
https://github.com/abapGit/abapGit/commit/f108143a9098788e143eb9b771306c0c3dd5e05d#diff-a146c502d6c6557558300dde73cdf308c3666cfe90d367ad6f02f4ade2b28cfa

I would say the change of the SELECT was ok but maybe you give it a try with the older code (select without the order by and using sort).

**Comment by DerGuteWolf** [comment]
ok, I reverted the change in src/objects/zcl_abapgit_object_wapa.clas.abap regarding to ORDER BY/SORT in the current version and tried again to pull. This was still unsuccesful.

I would rather assume the cause is somewhere in an interaction of changes with regards to pull/force pull/reset local with regards to some wapa specific stuff.

I debugged this a bit. For one file of the wapa the diff display shows 23 line changed, 6 lines added on the remote. During pull zcl_abapgit_object_wapa->zif_abapgit_object~deserialize is called, and these two lines
      lt_remote_content = to_page_content( mo_files->read_raw( iv_extra = lv_extra
                                                               iv_ext   = lv_ext ) ).
      lt_local_content = to_page_content( get_page_content( lo_page ) ).
both retrieve 23 lines for this file instead of the 29 expected lines for lt_remote_content .

I would say something is messing with mo_files .

**Comment by mbtools** [comment]
mmm, mo_files->read_raw get it's directly from the remote file without touching the content. 

i suspect there are some different end-of-line characters present. to_page_content splits using LF. maybe the page edited directly in the repo and it used CRLF?

**Comment by DerGuteWolf** [comment]
No, certainly no manual editing. We deploy our Fiori apps with the ui5 tooling task to the NetWeaver 7.50 system and then push the package. abapgit repo is then used to bring the abap coding and the fiori apps to other systems.

**Comment by mbtools** [comment]
We will need a test repo to track this down. We don't have any Fiori apps anyway for CI. Could you please push an example to https://github.com/abapGit-tests/WAPA_Fiori?

**Comment by larshp** [comment]
@DerGuteWolf can you help pushing an example, as noted by Marc?

**Comment by DerGuteWolf** [comment]
ok, did some tests. Problem does not appear with first but only on pulling subsequent changes. I am a bit unsure how to give an example for this.. but will debug a bit more first

**Comment by DerGuteWolf** [comment]
After lots of debugging I am not so much wiser. What I that during deserialization in zcl_abapgit_object_wapa-mo_files-mt_files gets appended with an entry for the same filename but with the local content by the line `ls_local_page = read_page( <ls_remote_page>-attributes ).` because in read_page mo_files->add_raw is called giving:
![image](https://user-images.githubusercontent.com/638512/151681905-6025adfa-ec9a-410c-99f9-91cbc9c19b1d.png)
and 
`      lt_remote_content = to_page_content( mo_files->read_raw( iv_extra = lv_extra
                                                               iv_ext   = lv_ext ) ).`
calls zcl_abapgit_objects_files->read_raw which calls zcl_abapgit_objects_files->read_file which in
`      READ TABLE mt_files ASSIGNING <ls_file>
          WITH KEY file
          COMPONENTS filename = iv_filename.`
reads the newly added line with the local content instead of the original line with the remote content.
Therefore nothing is changed because `IF ls_local_page = <ls_remote_page> AND lt_local_content = lt_remote_content.` then decided nothing needs to be changed.

**Comment by DerGuteWolf** [comment]
1.109 uses `READ TABLE mt_files ASSIGNING <ls_file> WITH KEY filename = iv_filename.` in zcl_abapgit_objects_files->read_file which picks up the first entry which contains the remote content and thus everything works as expected.

The key used in the current version is defined in zif_abapgit_definitions as `WITH NON-UNIQUE SORTED KEY file COMPONENTS filename`

**Comment by DerGuteWolf** [comment]
@larshp / @christianguenter2 / @christianguenter3 Could you give me some advice in what directions a fix should go?
Is it intented that `mt_files` contains local **and** remote entries?

**Comment by mbtools** [comment]
good debugging definitely a bug. during `deserialize` it must not add anything to `mo_files`. Let's fix that part and see if it takes care of the issue:

I suggest passing a flag to `read_page` so it calls `add_raw` only during serialize: 

https://github.com/abapGit/abapGit/blob/884a71e00e341f8dcc794cd734681351e57f95f3/src/objects/zcl_abapgit_object_wapa.clas.abap#L236-L239

**Comment by mbtools** [comment]
i merged your test repo. there's one thing that looks incorrect: every file should have a proper extension. However, there are a bunch of files without one. from the content they should be `.js` or `.json`:

![image](https://user-images.githubusercontent.com/59966492/151695498-f5f9bfa2-27ba-4c83-a960-402dbe1c3520.png)

we should check why that is the case and fix it.

**Comment by DerGuteWolf** [comment]
@mbtools  I think is due to the strange way of deployment of fiori apps. IMHO it is better not to mess with this.... this is simply a non-editable deployment, only suitable for use by the sap/bc/ui5_ui5 logic and for forwarding to other system via transport or abapgit. You have change in the original repo and redeploy in order to change stuff.

**Comment by DerGuteWolf** [comment]
@mbtools  yes, I thought also of a change like you proposed (I was just a bit unsure how this is meant to be), IMHO it should take care of things.

**Comment by mbtools** [comment]
we use abapgit-test only for small test cases. 

for public projects it's best to list them on https://dotabap.org/. 

there is also a suggestion to run those via CI https://github.com/abapGit/CI/issues/76

**Comment by DerGuteWolf** [comment]
Yes, but the problem here is for having an automatic test you would need first pull the first version and then pull some changes eg from a different branch. I agree to keep abapgit-test only for small tests, but I wanted a real world example because I knew about the strange files used by sap when deploying fiori apps... I am unsure what to do here...

**Comment by mbtools** [comment]
understood. the current CI isn't able to run such multi-step process. 

if you want something to run on regular basis, a custom prg using the API is the way to go:
https://docs.abapgit.org/development/api.html

**Comment by mbtools** [comment]
please go ahead

**Comment by DerGuteWolf** [comment]
Regarding the question of an kernel bug I found meanwhile that what we see is the *intended* behaviour. The order is determined by the lazy update of the secondary index and according to https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abenitab_key_secondary_duplicates.htm
"the order of the duplicates with respect to the table key of the target table is determined in accordance with the insertion order of the individual lines. The duplicate line that was last inserted into the table is sorted before all other duplicates."

**Comment by mbtools** [comment]
Fixed by #5310
