### ISSUE TITLE
WebGUI: File Diff dumps

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5181]
WebGUI dumps while navigating to file diff from Stage page.

![grafik](https://user-images.githubusercontent.com/17437789/144908769-9bb7be20-4220-45f5-9f4b-1a5655ec51c6.png)
![grafik](https://user-images.githubusercontent.com/17437789/144908764-f5a58946-25e2-4f8c-8b78-5e6ac3da08c3.png)

READ TABLE fails because path is encoded.
![grafik](https://user-images.githubusercontent.com/17437789/144909745-8123e139-4323-416c-bac6-3f3af2fae0bb.png)
![grafik](https://user-images.githubusercontent.com/17437789/144910178-9432261a-45d8-49de-bbf3-54170d96cc85.png)

Same issue when object contains namespace.

**Comment by mbtools** [comment]
I think it's the known problem of decoding the response properly (like I mentioned in https://github.com/abapGit/abapGit/issues/4647#issuecomment-800934086).

**Comment by christianguenter2** [comment]
Yeah, though a bit different scenario.
