### ISSUE TITLE
Enablement of AIFC development object for AIF content in abapgit

### ISSUE THREAD

**Issue by D047539** [abapGit/abapGit#5195]
AIF developments, like AIF interfaces can be transported with the [AIF Content Delivery Tool](https://help.sap.com/viewer/4db1676c3f114f119b500bd80ccd944d/202110.000/en-US/13f753cfe3df4437b3b1434d1170a6ae.html). An own repository table and transport object "R3TR AIFC" was introduced for transporting AIF content. A developer can compress C-Table entries from dev system into a blob-like repository table with TADIR entry, this will be transported and extracted in the target system.

In the future there will be more and more scenarios where it is necessary to use AIF developments in the onPremise and the cloud world. 
For that reason, we are looking for a possibility to transport an AIF interface developed (by customer) in an onPremise landscape into S4 cloud landscape.  The usage of ABAP Git will allow scenarios like this. 

I did a first implementation for the abapGit version in NW Infinity Development System to get a first feeling about what is needed to enable AIFC development object in abapGit.
The new AIFC serializer zcl_abapgit_object_aifc is stored in fork [D047539/abapGit: Git client for ABAP (github.com)](https://github.com/D047539/abapGit) and branch aifc (see [abapGit/src/objects at aifc · D047539/abapGit (github.com)](https://github.com/D047539/abapGit/tree/aifc/src/objects) ).

I am looking forward to your feedback and the discussions. Can you also tell me the next steps in order to trigger the approval process?

**Comment by larshp** [comment]
cool 👍 

Next step will be to [open a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

Quickly looking through the code:
* Run the pretty printer for the class definition
* use `TYPE c LENGTH 6,` instead of `TYPE char6,`, we would like to reduce dependencies into DDIC

**Comment by D047539** [comment]
thanks a lot for your feedback.
I triggered the pull request #5197. 
What's next? What are the next steps?

**Comment by larshp** [comment]
can you help with some hints on how to test this, creating the AICF object? The link in the first comment to help.sap.com seems to not work?

**Comment by D047539** [comment]
please try this link: https://help.sap.com/viewer/4db1676c3f114f119b500bd80ccd944d/202110.000/en-US/13f753cfe3df4437b3b1434d1170a6ae.html

**Comment by larshp** [comment]
merged

**Comment by mbtools** [comment]
Follow-up in #5250. Closing
