### ISSUE TITLE
Paths not visible in repo view

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#5200]
How do I get the file path to show up again?

With these settings

![image](https://user-images.githubusercontent.com/5270359/145724986-ea2f6004-012d-4023-bd2f-3f7138bdb4c6.png)

It looks like this

![image](https://user-images.githubusercontent.com/5270359/145724982-2d9df9e1-21a8-4062-85d8-95c910311612.png)

With "File Paths" deselected it looks like this

![image](https://user-images.githubusercontent.com/5270359/145725001-06aacb02-1257-4020-9c89-74990930630d.png)

**Comment by christianguenter2** [comment]
Looks like a regression from #5185.
https://github.com/abapGit/abapGit/blob/c7e4af3be2d196f578b49165889738b44fc7e79f/src/ui/zcl_abapgit_gui_page_repo_view.clas.abap#L1044-L1050
If userexit isn't implemented error occurs.
