### ISSUE TITLE
Error when activating ZABAPGIT_STANDALONE, Formal parameter "NO_AUTH_CHECK" does not exist.

### ISSUE THREAD

**Issue by snggh** [abapGit/abapGit#5204]
Hello,

I got error when activating abapGit standalone following instructions in [this guide](https://docs.abapgit.org/guide-install.html) as below :

<img width="460" alt="image" src="https://user-images.githubusercontent.com/9331718/145577820-2ce10191-0950-4e24-85e8-773c6e2da6d4.png">

`Formal parameter "NO_AUTH_CHECK" does not exist. exist.`

I've searched the internet for my issue but I don't find anyone else experiencing the same problem as me.

I'm using SAP_BASIS 731

<img width="280" alt="image" src="https://user-images.githubusercontent.com/9331718/145741155-66d17c90-8695-4297-969a-52801908ee6d.png">

Thanks in advance.

**Comment by larshp** [comment]
@snggh thanks for the bug report, try again, latest version
