### ISSUE TITLE
Error Message must be adjusted for Offline-repo: "Select Advanced -> 'Open in Main Language' not available

### ISSUE THREAD

**Issue by fischmir** [abapGit/abapGit#5207]
Hey there,

I am trying to create an offline-repo. Language of Git is 'EN', whereby current system is maintained in 'DE'. Therefore the message itself is correct, but the item in the referenced can not be found.

If I remember correct, changing the language is available for online-repos only, right?

Therefore, the message might be adjsuted.

![image](https://user-images.githubusercontent.com/29099751/145772115-9fda398a-fc76-44be-9cbd-4d974c02d9ea.png)

**Comment by FreHu** [comment]
abapgit doesn't allow changing the main language
![image](https://user-images.githubusercontent.com/5097067/145789342-13693686-9997-42da-85e2-9c26fe03d8c4.png)

You could do it by changing the abapgit.xml, but i'm not sure of the consequences. At the very least you should get a lot of diffs from all the texts changing

**Comment by flaiker** [comment]
> Therefore the message itself is correct, but the item in the referenced can not be found.

For technical reasons the "Open in main language" feature is only available using the development version. The message does not reflect that apparently. I assume you are using the standalone version (one huge report)?

**Comment by g-back** [comment]
I think you only have to assign a TCODE for the standalone report:
https://github.com/abapGit/abapGit/issues/4622#issuecomment-796075425
