### ISSUE TITLE
Pass transport to object classes `zcl_abapgit_object_xxxx`

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5209]
Several object type classes require the transport number for deserializing or deleting objects (recent example #5199). 

The current solution works but is a bit cumbersome (and not transparent to the object classes). 

Suggestion:

Pass the transport number to the constructor and hold it as a protected attribute in `mv_transport` (similar to `ms_item` and `mv_language`):
https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_objects.clas.abap#L438-L441

All  `zcl_abapgit_object_xxxx` class constructors will have to be adjusted. It's a bit of work but will standardize and simplify the implementation of the classes when it comes to handling transportable objects.

**Comment by larshp** [comment]
transports are not needed for serialization, only deserialization

**Comment by larshp** [comment]
yea, so its a field needed for methods create, update, delete ....

**Comment by mbtools** [comment]
ok, so add `iv_transport` to `deserialize` and `delete` (not to `constructor`). Actually, easier change since it's the interface:
https://github.com/abapGit/abapGit/blob/main/src/objects/zif_abapgit_object.intf.abap#L21-L33

**Comment by larshp** [comment]
yea, we dont want to leak too much to the constructor, as its outside of interface

**Comment by mbtools** [comment]
- [ ] Update interface and related calls
- [ ] Adjust object classes that use transport number
