### ISSUE TITLE
SRVB (Service Binding) is lost in version 1.113.0

### ISSUE THREAD

**Issue by MDJoerg** [abapGit/abapGit#5212]
Hi,

after installing the current ababgit version 1.113.0 the SRVB objects was displayed as "deleted". With the same system and abapgit version 1.109.0 all is fine. See screenshot. The objects are created in partner namespace (/*).

![grafik](https://user-images.githubusercontent.com/41207683/145857202-cdb15495-5a3f-40ee-b935-0071fdb22247.png)

Please check the last implementations for SRVB. 

Thank You!

Regards
Joerg

**Comment by mbtools** [comment]
@shyambalachandran  could you please have a look?

**Comment by larshp** [comment]
@MDJoerg what is your SAP_BASIS version?

probably related to https://github.com/abapGit/abapGit/pull/4976, as a temporary workaround you can grab the code from before the PR

**Comment by MDJoerg** [comment]
> @MDJoerg what is your SAP_BASIS version?
> 
> probably related to #4976, as a temporary workaround you can grab the code from before the PR

Hi Lars,

I use a S4HANA 2020FPS0, SAP_BASIS	755, SAP_ABA	75F.

After resetting class zcl_abapgit_object_srvb to source of 1.109.0 the service binding is detected as unchanged - expected behavior.

Best regards
Joerg

**Comment by shyambalachandran** [comment]
Hi All,
I will look into this. Will contact if I need some help

**Comment by christianguenter2** [comment]
Same here. Existence check fails because BADI implementation isn't found.
![grafik](https://user-images.githubusercontent.com/17437789/146345339-23e31836-83c1-4cfd-b2a6-1a163e37b9d2.png)
![grafik](https://user-images.githubusercontent.com/17437789/146345641-fb27dd00-618d-45ec-9221-ba198b3b964d.png)
![grafik](https://user-images.githubusercontent.com/17437789/146345745-895a40c9-072a-43b6-8933-77b0e64a211c.png)

**Comment by mbtools** [comment]
looks like SAP has not configured the badi correctly. it needs a default implementation or the error must be caught in the SAP code. i don't see any SAP Notes about it.

**Comment by larshp** [comment]
@shyambalachandran any updates?

**Comment by shyambalachandran** [comment]
Hi @larshp , we are looking into it. Unfortunately, no positive updates as of now.

**Comment by christianguenter2** [comment]
@shyambalachandran any updates? Is there any way we can support you?

**Comment by shyambalachandran** [comment]
@christianguenter2 , sorry for the delay.
We are trying to fix the issue without touching the Service Binding or Framework logic. Currently that is taking more time than we anticipated. It would need some more time unfortunately. I will keep you posted on the progress.

**Comment by shyambalachandran** [comment]
Hi All,
Have provided a fix. Should solve the issue

**Comment by MDJoerg** [comment]
@shyambalachandran 
I have checked the current code with the compiled abapgit version (1.114.0). The SRVB object was found now. 
Thank you!

**Comment by larshp** [comment]
cool, thanks all, merging 👍 🚢 always ship on fridays 😁

**Comment by shyambalachandran** [comment]
@larshp , should I close this issue( I am not sure how )? Or would this be done from your end?

**Comment by larshp** [comment]
yea, close, thanks
