### ISSUE TITLE
abapgit does not create ICF node of webdynpro application in ABAP2XLSX

### ISSUE THREAD

**Issue by ojnc** [abapGit/abapGit#5228]
After installing ABAP2XLSX ZDEMO_EXCEL_WDA01 does not work
After  debugging found WebDynpro needs a ICF Node /sap/bc/webdynpro/sap/zdemo_excel_wda01
which abapgit does not create

Deletion and regeneration of application creates ICF node

**Comment by mbtools** [comment]
Duplicate of https://github.com/abapGit/abapGit/issues/5064. 

SICF is a tricky object since it has system-specific tadir entries (objects keys). I mentioned a few other issues with it in https://github.com/abapGit/abapGit/issues/5064#issuecomment-954742820

**Comment by ojnc** [comment]
Thanks! 
ABAP2XLSX team did some workaround.
I am back to learning SAP; issues make me stronger on SICF & Debugging.
Proverb 19:21 divine interruptions!

I had great success with DOI (needs SAPGUI)
Had a beautiful spreadsheet with print preference all set
Uploaded and ready in a "blob" table; I just filled up some cells

ABAP2XLS will be useful to me to deliver XLSX via web and 
situations where user has no licensed MS-Office installed

Thanks again!
