### ISSUE TITLE
Deserialize WDYN "invalid alias" (OTR)

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#5232]
Steps to reproduce
- Clone https://github.com/sandraros/abapgitbug_wdyn_otr 
- Pull to a package which is not `$abapgitbug_wdyn_otr` (which is the original package I used to create my objects)
- Error "invalid alias":
  ![image](https://user-images.githubusercontent.com/34005250/146688131-d386541b-a687-4886-a5d9-9da2dfbca648.png)

I think that the OTR I have created using `SOTR_EDIT` is required to have an alias with the creation package as prefix (e.g. `$ABAPGITBUG_WDYN_OTR/DOWNLOAD`). If one pulls to another package, the alias will become incoherent.

**Comment by mbtools** [comment]
XML must not contain package name:

![image](https://user-images.githubusercontent.com/59966492/146688865-2004e83e-7111-48e5-aed6-b06270828072.png)

SOTR refactor already mentions this in https://github.com/abapGit/abapGit/issues/4480, issue 5.

**Comment by sandraros** [comment]
Thanks 👍. #4480 didn't describe the problem clearly, it's why I created this one. For information, I'm a newbie in WebDynpro/OTR, just working on it due to https://github.com/abap2xlsx/abap2xlsx/issues/923, I won't be able to propose a fix.

**Comment by mbtools** [comment]
a2x is becoming more popular. I will try to find some time after Christmas to get this and the sicf thing fixed.

**Comment by sandraros** [comment]
For information, no urgency at my side, I have changed the WebDynpro in abap2xlsx to not use the OTR text anymore.

**Comment by mbtools** [comment]
Finally got around to this #5750
