### ISSUE TITLE
No object directory entry for object R3TR W3MI Z....

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#5233]
When moving from [the branch](https://github.com/abap2xlsx/abap2xlsx/tree/sandraros/check-demo-regressions) for [abap2xlsx PR 902](https://github.com/abap2xlsx/abap2xlsx/pull/902) to master, I always get this error:
![image](https://user-images.githubusercontent.com/25269970/146813512-1fdb2ff5-ecb9-4c8e-b0bf-de92c01e13cd.png)

Funny thing is, the objects are indeed gone from SMW0. This with JavaGUI 7.70rev4, I'll have a look with the Windows GUI in case it matters.

**Comment by mbtools** [comment]
these objects exist only in the branch, so if you switch to master and pull (if that's what you mean by "moving"), then the objects should be deleted. However, there shouldn't be an error message. hmm

**Comment by AndreaBorgia-Abo** [comment]
Indeed that's what I meant, sorry for being unclear... yes, the deletion is expected, it's the error message that I find odd.

**Comment by mbtools** [comment]
looks like the deletion is happening twice. try removing this line:
https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_w3xx_super.clas.abap#L103

**Comment by AndreaBorgia-Abo** [comment]
Removing that line takes care of the spurious error message and the objects are still deleted as expected.
SAP_BASIS	752	0004	SAPK-75204INSAPBASIS	SAP Basis Component

**Comment by mbtools** [comment]
it looks a lot like this was fixed with https://github.com/abapGit/abapGit/pull/2741 (a long time ago), which ignores errors related to TADIR deletion.

which version of abapGit were you using?

**Comment by AndreaBorgia-Abo** [comment]
Most likely v1.113.0
Not 100% sure since I am checking this now but abapGit is among the repos that are automatically pulled at system startup so it's a fairly safe bet.
Anyhow, plan for today is to finally get around and review that PR so I can re-test

**Comment by AndreaBorgia-Abo** [comment]
Switching from master to the PR branch and back, at first I could not reproduce it anymore, even without [removing the line](https://github.com/abapGit/abapGit/issues/5233#issuecomment-998261966)

However, I noticed that TR_TADIR_INTERFACE was returning sy-subrc = 0 for all W3MI objects previously failing, hence no exception was logged in calling method DELETE. This gave me a clue: what if ZDEMO_EXCEL_CHECKER is indirectly changing the state of the W3MI objects in such a way that it fails there?

Hey, presto: after a run of the proposed demo checker, I can get all those errors again when switching from the PR branch back to master. I'll stop here for the moment, I really need to push either that PR or its newer sibling out of the door today.

**Comment by mbtools** [comment]
I had a look at the checker. It looks like it checks if tadir entries exist before writing the w3mi objects. Not sure if this was the case earlier. Looks to be ok now and no changes to abapGit are necessary.

https://github.com/abap2xlsx/abap2xlsx/blob/master/src/demos/zdemo_excel_checker.prog.abap#L1297-L1305

**Comment by AndreaBorgia-Abo** [comment]
I'll recheck and confirm / add infos.

**Comment by AndreaBorgia-Abo** [comment]
Now with AG 1.114.0. 
Since I have dependent objects outside this repo, I do get other errors as well but the key point is that it still complains when deleting, now the issue may be reproduced by alternating between tags 7.15.0 (with W3MI objects) and 7.14.0 (without).

**Comment by mbtools** [comment]
I tried to reproduce it by switching between 7.15 and 7.14 but did not get the error above. I tried with `$` as well as `Z` packages. All W3MI are deleted properly (except for one which exists in 7.14 already). 

I tried repeatedly reproducing it using https://github.com/abapGit-tests/W3MI, too, going back and forth between `main` and `remove_w3mi` branches. Used `$` as well as `Z` packages. One transport for the complete scenario, or releasing between creating the MIME object and deleting it. 

This was on 7.54 (docker image) with latest AG.

abap2xlsx is now nicely split with the demos in a separate repo. My general recommendation for customers would be to uninstall whatever they have and then reinstall the regular and demo repos.

**Comment by mbtools** [comment]
do you still need this fixed?

**Comment by AndreaBorgia-Abo** [comment]
Using A4H minisap (the NPL minisap is busy with the dependency issue I updated earlier), I removed "demos" as standalone repo, created tags in my repo to match 7.14.0 and 7.15.0 upstream, then tried alternating between them.
Using NPL with your test repo also no issues, so it's either been fixed in general or gone in my system for the time being, so closing the issue.
