### ISSUE TITLE
Support for Authentication via Access Token for Gitlab/GitHub

### ISSUE THREAD

**Issue by kfowlks** [abapGit/abapGit#5234]
Hello,

Recently, Our Organization has put our GitLab instance behind a SAML authentication provider (Okta). The only allowed git authentication method is SSH and Access Tokens. I have seen other Git clients implement Access token (Auth) e.g. SAP Web IDE. Has there been any thought on implementing Access Token Authentication in abapGIT?

Thanks 

Kevin

**Comment by mbtools** [comment]
I'm afraid you are out of luck on this one. abapGit uses HTTP(S) and I don't see a way to use SSH instead.

**Comment by larshp** [comment]
personal access tokens works with abapGit, https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by flaiker** [comment]
> The only allowed git authentication method is SSH and Access Tokens.

This seems unusual. Or did you maybe mean two methods are allowed: either SSH _or_ Access Tokens over HTTPS? HTTPS is supported, including using access tokens. SSH is not supported at all (and Web IDE doesn't support it either as far as I know).

https://docs.abapgit.org/guide-authentication.html

https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html

**Comment by kfowlks** [comment]
Hi, @flaiker & @larshp 

Correct! Access Tokens via HTTPS is also allowed. So, If I understand correctly the abapGit client will work with Access Tokens on GitLab? Do I select HTTPS as the auth method and use my Access Token as my password?

- Kevin

**Comment by christianguenter2** [comment]
@kfowlks 
works for me with our gitlab instance

Username: oauth
Passwort: <access_token>

https://knasmueller.net/gitlab-authenticate-using-access-token

**Comment by mbtools** [comment]
Did you get it to work?

**Comment by treee111** [comment]
> @kfowlks works for me with our gitlab instance
> 
> Username: oauth Passwort: <access_token>
> 
> https://knasmueller.net/gitlab-authenticate-using-access-token

on our Github Enterprise instance, I also like that - works flawless.

**Comment by kfowlks** [comment]
Hi, Guys 

@treee111  and @larshp 

I'm just getting back into the office, I'll give it a try with our gitlab instance and report asap.

Thanks for all the assistance

- Kevin

**Comment by kfowlks** [comment]
Hi, Guys

As many have you stated it **does** work just by using the username and the token as a password for HTTPS auth. This ticket can be closed thanks for all the assistance.
