### ISSUE TITLE
unauthorized access to resource (http 401)

### ISSUE THREAD

**Issue by Deepaks74** [abapGit/abapGit#5235]
Hi Team 

When i try to commit ABAP git into the repository i get a error as 

unauthorized access to resource (http 401).  check your credentials 

Have recheck the all the details and there is no issue . How to fix the same .

**Comment by larshp** [comment]
check your credentials, does it work on command line using classic git?

**Comment by mbtools** [comment]
Did you get it to work?

**Comment by Deepaks74** [comment]
yes just created the personnel access token and it worked fine . thanks

**Comment by larshp** [comment]
👍 closing

**Comment by mohan-dandu** [comment]
I am also facing the same issue, even after creating the personal access token, could you please help me? Thanks

**Comment by mbtools** [comment]
@mohan-dandu please review the docs and test program. If this does not help, create a new issue
https://docs.abapgit.org/guide-ssl-setup.html
https://docs.abapgit.org/guide-ssl-test.html
