### ISSUE TITLE
`APIS` object type

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#5238]
@ThomasPloski the following file

https://github.com/SAP-samples/cloud-abap-rap/blob/main/src/%23dmo%23cx_rap_generator%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20clas.apis.xml

is for a `APIS` object type, which is not supported by abapGit?

**Comment by flaiker** [comment]
There are also lots of other objects types listed as supported by abapGit here:

https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/b31aa03640b940d5981ce2af1cd0a019.html?locale=en-US

that are not listed here:

https://docs.abapgit.org/ref-supported.html

Also are the "cloud versions" of the object handlers different? This comment indicates objects are deserialized to inactive state which is not the case in the public version (CLAS/INTF/...).

> All objects imported with abapGit are imported as inactive, except the ones that don’t have an inactive state. Therefore, you have to activate all the imported objects after the import.

**Comment by christianguenter2** [comment]
Hm, indeed, looks like there are additional object handlers in the cloud.
![grafik](https://user-images.githubusercontent.com/17437789/148556251-e4eaa98f-0488-4c6b-a783-68fd818fe5e0.png)
![grafik](https://user-images.githubusercontent.com/17437789/148556239-db0f2e1e-5d6b-43a2-b34f-a1f0ccca6ade.png)

**Comment by larshp** [comment]
@ThomasPloski

**Comment by ThomasPloski** [comment]
Hi community,

The following object types only exist in an SAP BTP ABAP Environment (aka Steampunk and embedded Steampunk):

- SCO1
- SCO2
- SCO3
- SIA1
- SIA2
- SIA3
- SIA5
- SIA6
- SIA7
- SIA8
- SIA9
- SAID

Therefore, the contribution of the respective object handlers for these object types is not planned, since these object types will not be part of a SAP system, in which SAP BTP (aka (e)Steampunk) is not installed.

**Comment by ThomasPloski** [comment]
The contribution of the APIS object handler is currently discussed by the object owners. 

As soon as a decision has been made I will share this information with you.

**Comment by mbtools** [comment]
@ThomasPloski now we have embedded steampunk... how about contributing all these object types?

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.
