### ISSUE TITLE
Repo View: Should order by path also consider object name?

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5259]
If we sort by path object name isn't considered. I think working like that it doesn't add much value and it's a bit confusing, at least for me. What about considering path + object name? And also sorting file names accordingly?

![grafik](https://user-images.githubusercontent.com/17437789/148680574-99a09b9a-7ed8-4047-97e1-736314a92340.png)
https://github.com/abapGit/abapGit/blob/79961a1f20c92eac456886ab5d48bddb86be0c1d/src/ui/zcl_abapgit_gui_page_repo_view.clas.abap#L236-L237
![grafik](https://user-images.githubusercontent.com/17437789/148680503-0fbcf00f-1568-4ddf-b204-3411decda79c.png)
![grafik](https://user-images.githubusercontent.com/17437789/148680506-afd258a0-bf49-4d55-9480-fc8ff8617e36.png)

**Comment by flaiker** [comment]
Yes, I would expect sorting by path to sort by the path displayed in the column (including the actual filename).
