### ISSUE TITLE
Inactive objects after activation issue/solving without leaving activation dialog (?)

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#5265]
This one will be tough to reproduce, here for reference, in case someone can investigate.

abapGit 1.114.0
ABAP 7.52 SP 0

After the activation in the context of pull explained in #5262 (after activating manually the transformation, and activating the rest via abapGit), I see all pulled objects in inactive state:
![image](https://user-images.githubusercontent.com/34005250/148806557-54d92db1-e75c-4cd0-8425-c621b01a9174.png)

I don't know why it happened, the first pull/activation failed because of #5262, I kept the activation popup opened, I went to another session to activate the transformation, then I went back to the activation popup, it seemed to activate everything correctly (no syntax error) but they are all in inactive state.

I restarted abapGit, impossible to pull because it was already pulled/in sync. Same list of inactive objects.

I had to go to the Inactive Objects, activated all of them:
![image](https://user-images.githubusercontent.com/34005250/148807279-942537ee-cc42-412f-8cbf-a4db3600e416.png)

A first abapGit Refresh and abapGit shows an empty version:
![image](https://user-images.githubusercontent.com/34005250/148807783-eb42fd11-60a4-47ec-ab1f-d65e9fac065e.png)

Example:
![image](https://user-images.githubusercontent.com/34005250/148809474-da19d3f1-cc87-4caa-bc42-506c3b4262d5.png)

A second abapGit Refresh and now everything is back to normal.

**Comment by mbtools** [comment]
Because you have the dependencies on the `xslt` objects, I would say this has the same root cause as #5262

**Comment by sandraros** [comment]
Thanks. Let's close it. :)
