### ISSUE TITLE
Audit: proxy authentication storage

### ISSUE THREAD

**Issue by schealex** [abapGit/abapGit#5272]
Hi guys,

we've got the question from the auditors how and where the proxy authentication is stored within abapGit.

Thanks in advance.

Regards
Alex

**Comment by larshp** [comment]
it depends a lot on your setup, looking at https://github.com/abapGit/abapGit/blob/main/src/http/zcl_abapgit_proxy_auth.clas.abap abapGit stores it in memory = it does not store it

you might also have proxy authentication stored in SICF or in SM59, which is then used in abapGit without abapGit knowing

**Comment by mbtools** [comment]
Some more details: 

All proxy settings that are persisted in abapGit are documented here: 
https://docs.abapgit.org/guide-settings-global.html

abapGit itself does not persist proxy user or password. Both have to be entered by the user.

abapGit provides exits that allow defining custom connection parameters like an RFC destination. You can see in abapGit > Utilities > Debug Info, if any exits are implemented. Such RFC HTTP connection might contain the proxy user and password. 
https://docs.abapgit.org/ref-exits.html#exits

For completeness, there's also a small chance that someone modified abapGit and hardcoded something. That's easy to detect by comparing the code to what's on GitHub.

**Comment by schealex** [comment]
Thanks for the fast responses guys. So from what I've understood, if you use the global settings the user and password has to be entered each time and is not persisted?

The RFC exits sound like the way to go because that way we can use the sap standard for the proxy settings.

**Comment by mbtools** [comment]
yes and yes

**Comment by schealex** [comment]
Thanks guys
