### ISSUE TITLE
UI: Center Popups 

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5275]
Try to center as many popups as possible:

- [x] `zcl_abapgit_popup` #5274
- [x] Refactor "set_starting_pos" (make reusable by other classes)
- [x] `zcl_abapgit_log_viewer->show_log`
- [x] `zcl_abapgit_exception_viewer->show_callstack`
- [x] `zcl_abapgit_requirements_helper->show_requirement_popup`
- [x] `zcl_abapgit_apack_helper->show_dependencies_popup`
- [x] `zcl_abapgit_free_sel_dialog->free_selections_dialog`
- [x] `zcl_abapgit_popups->popup_select_tr_requests`

Consolidate more popups into `zcl_abapgit_popup` and center them:

- [x] `zcl_abapgit_objects->compare_remote_to_local`
- [x] `zcl_abapgit_requirements_helper->requirements_popup`
- [x] `zcl_abapgit_xml->display_version_mismatch`

**Comment by larshp** [comment]
yea, well, could also spend time on getting rid of gui popups, https://github.com/abapGit/abapGit/issues/3417

**Comment by mbtools** [comment]
sure, just 3x as much effort 😉 . we will get there eventually
