### ISSUE TITLE
FUGR: Standard includes added to serialization

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#5283]
I have a custom function group which includes standard includes. During the function group serialization, it includes some of the standard includes in the serialization. Example package can be found in the link https://github.com/yellappam/ABAPGIT_FUGR_STANDARD_INCLUDE.git

**Below are the steps to replicate:**
1. Create an empty custom function group
2. In the TOP include, include standard include **mmmgtrbb**.
![image](https://user-images.githubusercontent.com/29766214/150451295-9ff6dd8e-0d0d-409b-987a-c827a4a5f71d.png)

3. In the abapGit, it now includes a few standard includes which are highlighted below
![image](https://user-images.githubusercontent.com/29766214/150451441-b781db56-934e-4b3b-b582-998df364cdfe.png)

**Analysis:**

The standard includes are not present in TADIR table hence, below LOOP is not removing them from the list.
![image](https://user-images.githubusercontent.com/29766214/150451715-51ffdf1e-a4ec-4f05-81fd-7dc529102e50.png)

**Proposed Solution:**

Select TRDIR entries for the selected includes and exclude the includes which are created by user **SAP**.
![image](https://user-images.githubusercontent.com/29766214/150451950-106b5712-4720-4716-abc2-5a98e46b0a87.png)

Please check and let me know if there is any better solution. I am happy to  submit PR once reviewed.

**Comment by larshp** [comment]
are you running the latest version? had some changes in November which might help, https://github.com/abapGit/abapGit/pull/5134

**Comment by yellappam** [comment]
> are you running the latest version? had some changes in November which might help, #5134

I am using abapGit version: 1.104.0. Let me check with latest version change and let you know incase the issue still exists.

**Comment by mbtools** [comment]
This was fixed, indeed. The following removes such includes:

https://github.com/abapGit/abapGit/blob/cb90be9ce7a2f28ecabc2f3dba9bf3d668492752/src/objects/zcl_abapgit_object_fugr.clas.abap#L682

**Comment by mbtools** [comment]
FYI, between 1.104 and latest 1.114, there have been over 540 commits with 654 files changed! Please update more frequently 

https://github.com/abapGit/abapGit/compare/v1.104.0...v1.114.0

**Comment by yellappam** [comment]
> FYI, between 1.104 and latest 1.114, there have been over 540 commits with 654 files changed! Please update more frequently
> 
> [v1.104.0...v1.114.0](https://github.com/abapGit/abapGit/compare/v1.104.0...v1.114.0)

We are using this for S/4HANA migration hence, not updating it frequently. As and when major issue is identified, we are patching our system. We will update abapGit once migration is complete.

**Comment by larshp** [comment]
or just do a local patch to the version you have installed

**Comment by yellappam** [comment]
The issue has already been fixed in #5134
