### ISSUE TITLE
new APACK version considered only by restarting abapGit

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#5284]
Steps to reproduce:
- Start abapGit, open your repository having an existing APACK class
- Using your favorite ABAP editor, edit the APACK class and change the version
- In abapGit, in your repository, click "Refresh"
- You can see that `.apack-manifest.xml` has not been recalculated, it doesn't contain the new version defined in the APACK class

Workaround: restart abapGit before clicking "Refresh".

Request: is it possible to not restart abapGit, by executing the APACK class in an RFC session so that to always consider the latest APACK class?

**Comment by mbtools** [comment]
I understand the issue and have seen it myself. APACK is just an ugly implementation using code instead of metadata (sorry). 

It's not really a big deal to restart manually until we have something better, is it?

**Comment by sandraros** [comment]
Sure! Let's close this issue and PR then, thanks!
