### ISSUE TITLE
Inconsistent Repo Metadata

### ISSUE THREAD

**Issue by harigajula** [abapGit/abapGit#5286]
Hi Team,

I am executing the ZABAPGIT_STANDALONE 
[DUMP.zip](https://github.com/abapGit/abapGit/files/7925031/DUMP.zip)
program and encountering with an error message as "Inconsistent Repo Metadata". No selection screen is displayed.

I have downloaded the latest version from Github and replaced the source code but still the issue remains.
Please suggest me the fix.

Method - FROM_XML

**Comment by larshp** [comment]
did you have a very old abapGit installed previously?

anyhow, check the contents of database table `ZABAPGIT` and take a backup, if you dont have very much configured, then clear the contents of the ZABAPGIT database table
