### ISSUE TITLE
Hotkeys displayed on wrong menu items

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5288]
For example, in repo view, it shows `[s]` on hover for "Force Stage" but the key is just for "Stage".

**Comment by christianguenter2** [comment]
Hm, but the hotkeys works also for "Force Stage". Stage and Force Stage trigger both the same action `zif_abapgit_definitions=>c_action-go_stage`. So I'd say the tooltip isn't that wrong. Maybe we can improve the hotkey description to reflect that fact?

**Comment by mbtools** [comment]
close in fav of #5013
