### ISSUE TITLE
Translations of DOMA fixed values not serialized for languages for which the DOMA short text has no translations

### ISSUE THREAD

**Issue by DerGuteWolf** [abapGit/abapGit#5296]
When in a domain (DOMA) only the fixed values are translated but not the short text of the domain itself, the translations of the values are not serialized into the git repo.

Reason is that in zcl_abapgit_object_doma->serialize_texts the list of the languages to be processed is determined only by dd01v and not also by dd07v AND the CONTINUE in the language loop with "OR ls_dd01v-ddlanguage IS INITIAL" .

Unfortunatly UNION for SELECT is only available from 7.50 on...

Also you have to make sure to keep the derializer happy.
I used this in 750 and it seems to work:
```abap
    SELECT DISTINCT ddlanguage AS langu
      FROM dd01v
      WHERE domname = @lv_name
      AND ddlanguage <> @mv_language
    UNION DISTINCT SELECT DISTINCT ddlanguage AS langu
      FROM dd07v
      WHERE domname = @lv_name
      AND ddlanguage <> @mv_language INTO TABLE @lt_i18n_langs. "#EC CI_SUBRC

    LOOP AT lt_i18n_langs ASSIGNING <lv_lang>.
      lv_index = sy-tabix.

      CALL FUNCTION 'DDIF_DOMA_GET'
        EXPORTING
          name          = lv_name
          langu         = <lv_lang>
        IMPORTING
          dd01v_wa      = ls_dd01v
        TABLES
          dd07v_tab     = lt_dd07v
        EXCEPTIONS
          illegal_input = 1
          OTHERS        = 2.
      IF sy-subrc <> 0." OR ls_dd01v-ddlanguage IS INITIAL.
        DELETE lt_i18n_langs INDEX lv_index. " Don't save this lang
        CONTINUE.
      ENDIF.

      IF ls_dd01v-ddlanguage IS INITIAL.
        ls_dd01v-ddlanguage = <lv_lang>.
      ENDIF.
```

Some more background: I stumbled upon this because a translation of all "A5 User Interface Texts" does NOT translate the DOMA short text, while eg DTEL short texts are translated. You need to also translate "G5 Technical Short Texts"-"DOMA Domains":
![image](https://user-images.githubusercontent.com/638512/151564214-31cb26bc-55ca-4c3a-9389-7ca3590971b1.png)

**Comment by DerGuteWolf** [comment]
MSAG seems to suffer from the same problem

**Comment by mbtools** [comment]
Try with #5304

**Comment by DerGuteWolf** [comment]
#5304 works for me. @mbtools  should I create a new issue and a PR for the similar problem with MSAG?

**Comment by mbtools** [comment]
yes, new PR for MSAG
