### ISSUE TITLE
Question: BitBucket 2FA and App Password Experience

### ISSUE THREAD

**Issue by mkaesemann** [abapGit/abapGit#5301]
Atlassian announced that they will ending support for basic authentication via password for Bitbucket API and Git over HTTPS and I have tried to analyze what this might mean for our setup with abapGit and the company repos in Bitbucket.
My firts attempt was to activate to 2FA in Bitbucket and use the app passwords for login, similar to the token setup used with gitHub, but this does not seem to be working (I receive a 401).
Since I'm not an authentication wizard, I have no clue on how to best analyze this and find out how we can contonue to use abapGit with Bitbucket, so any help or pointers that any of you can provide would be appreciated.
Does anyone have any experience how to use abapGit with Bitbucket without using Basic Authentication?

**Comment by larshp** [comment]
https://bitbucket.org/blog/deprecating-atlassian-account-password-for-bitbucket-api-and-git-activity

**Comment by larshp** [comment]
can you git clone via command line and the approach mentioned in https://stackoverflow.com/questions/39886995/how-to-access-bitbucket-using-app-password ?

**Comment by mkaesemann** [comment]
Wow. That was fast :-)
And very helpful, because the command line approach described in the stackoverflow article helped me to figure out that the issue was actually the user name. 
The Atlassian documentation states to use "your normal Bitbucket username", but does not mention that if one previously logged in with the e-Mail address as the username, that isn't actually working. 
It has to be the user name itself, not the e-mail address. 

Thanks for the help. And if someone has the same problem and finds this issue:
Use the Username, not the e-Mail address and create an app password in Bitbucket.
