### ISSUE TITLE
Deserialize JSON

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#5305]
Deserializing ABAP file formats objects results in
![image](https://user-images.githubusercontent.com/38354196/151926314-e8c24aca-f3b1-4161-a6ed-54c2721a790b.png)

Remote states there is a JSON file, however internal logic will ignore them here
https://github.com/abapGit/abapGit/blob/main/src/objects/core/zcl_abapgit_file_status.clas.abap#L567

**Comment by larshp** [comment]
yup, there is currently an assumption that each object has an xml file, this must be changed

**Comment by mbtools** [comment]
Have a look if #5313 is sufficient to fix this

**Comment by albertmink** [comment]
closed with #5313
