### ISSUE TITLE
JSON highlighter in diffs is missing

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#5318]
Not the must urgent one, but the coloring for diffs is very basic. Compare
![image](https://user-images.githubusercontent.com/38354196/152170508-145f22c1-0bf4-47c7-8cc2-f639f87b6b1d.png)
with
![image](https://user-images.githubusercontent.com/38354196/152170834-0dcd86c2-446b-4140-af4c-e254d572eb7c.png)

**Comment by albertmink** [comment]
Also
![image](https://user-images.githubusercontent.com/38354196/152326245-50909c57-091e-470d-b6a6-9d960589aedf.png)
vs
![image](https://user-images.githubusercontent.com/38354196/152326436-72e73cab-88b7-4b36-80b6-ff62d24e72db.png)

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/blob/main/src/syntax/zcl_abapgit_syntax_json.clas.abap

**Comment by mbtools** [comment]
It might seem easy to do but it's quit difficult to implement since highlighted code it full of html tags that must be taken into account for colouring the diffs in a line. 

I'm close to getting a port of a JS htmldiff done.

**Comment by mbtools** [comment]
Highlight parts of line that have changed is in #2804
