### ISSUE TITLE
Unsupported object type message does not consider ignore list

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#5321]
`zcl_abapgit_serialize->filter_unsupported_objects` does not currently take the ignore list into account.

Should
![image](https://user-images.githubusercontent.com/5097067/152330906-62ff99d9-8435-409f-b378-f78320350588.png)
be shown if my ignore list contains `*.apis.xml`?

**Comment by mbtools** [comment]
Do you have `APIS` objects in the repo and you ignore them? Why?

**Comment by FreHu** [comment]
hmm, i didn't realize they were in the repo, they're not entirely supported yet so i'm not sure how they got there 
#5238

**Comment by larshp** [comment]
APIS are supported in Steampunk, https://github.com/abapGit/abapGit/issues/5238, so they might come from a Steampunk system, fyi @ThomasPloski

**Comment by larshp** [comment]
@FreHu above is from "ZCL_ABAPGIT_OBJECT_BY_SOBJ" ie. https://github.com/abapGit/abapGit-Plugins, suggest deleting not using the code from this repo

**Comment by FreHu** [comment]
this would have been committed from a system where i maintain the release contracts

**Comment by filak-sap** [comment]
There are gazillion of not yet supported object types in packages we have to maintain. If we stop using the plugins, we get gazillion of error messages.

**Comment by FreHu** [comment]
i'd rather not depend on the plugins, for now we won't need to have the apis in our repo and can maintain them on the central system
