### ISSUE TITLE
Repo page - paths under object name

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#5322]
I randomly tried this change and I think it's just straight up better. Any good reasons why we would not want the paths under the object name?
![image](https://user-images.githubusercontent.com/5097067/152335484-e7089439-846d-49c8-a263-9f6453ef9b15.png)
![image](https://user-images.githubusercontent.com/5097067/152335620-eb71b807-c32a-456e-86dd-a48748577799.png)
![image](https://user-images.githubusercontent.com/5097067/152335722-eac582ec-073d-438c-a94f-166ca1ff65af.png)

**Comment by larshp** [comment]
heh, no, looks very good IMHO 😄

**Comment by FreHu** [comment]
breaks sorting by path, but that's like sorting by package->object, so you could just use the folders view
