### ISSUE TITLE
spurious "activation failed" error

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#5325]
[I have lv_rc=4](https://github.com/abapGit/abapGit/blob/83534ecfeb7be3fe80846ae1872081ec8569ad74/src/objects/core/zcl_abapgit_objects_activation.clas.abap#L166) and I get an [activation failed message](https://github.com/abap2xlsx/abap2xlsx/issues/986); at this point in time there are NO inactive objects for the user and forcing the value leads to a normal installation with all demos running correctly.

Two installations of abap2xlsx tag 7.15.0 on HANA, same story, same workaround:

1) yesterday evening in an internal company system, version S4CORE105, offline ZIP method
(note: in this case, there was an older installation that I had to clean because it was a mixed bag of local / transportable objects, someone had tried the CR import from another system, grrrrrr!)

2) this morning in a customer system, version SAPK-10401INS4CORE, online access

**Comment by mbtools** [comment]
Just this week we made some improvements when it comes to activation. See #5303 and #5312

Which object type(s) are involved in your case?

**Comment by AndreaBorgia-Abo** [comment]
@mbtools both times, time pressure prevented me from digging and documenting. Off the top of my head, at the last activation round the popup showed a few structures and the transformations, all of them. I'll spin a new A4H (HANA1909) in the next day or two and try again, that should allow for a clean slate test.

**Comment by AndreaBorgia-Abo** [comment]
I must have something that bugs love, because [I keep finding them](https://github.com/abapGit/abapGit/issues/5327) when I'm looking for something else :)

Anyway, starting from an empty A4H docker system, create online repo with package name ZABAP2XLSX, create CR and this is the first attempt:
![saplogon_nu1WaobRPy](https://user-images.githubusercontent.com/25269970/152594642-6af7c9b6-d3ef-4706-b318-13f49ae83495.png)

Second attempt, these are the reportedly inactive objects:
(I do not see them in the transportable objects from another session
![saplogon_5gExb6Bj76](https://user-images.githubusercontent.com/25269970/152595173-3b6d5b0b-79f6-4779-addd-2f333d81063a.png)

At this point, I force lv_rc to 0, first time:
![saplogon_cbvChFuJt7](https://user-images.githubusercontent.com/25269970/152595817-a07683d3-e2e4-4378-99e6-42ea0055be0d.png)

Second time:
![saplogon_pzHJa1BJjU](https://user-images.githubusercontent.com/25269970/152596253-6b5f2c0f-9a7e-4754-953a-bd6d12afb600.png)

At this point there are some residual spurious differences in the project:
![saplogon_TCvOhfQDkQ](https://user-images.githubusercontent.com/25269970/152596632-e1412bb9-6ab7-4fa5-a104-b8d07a148676.png)

![saplogon_R1mVdRQZZK](https://user-images.githubusercontent.com/25269970/152596739-624f4ee4-c171-4f30-b858-a309f8777f64.png)
![saplogon_ByStJXaHgh](https://user-images.githubusercontent.com/25269970/152596787-d0fae8da-d14c-4b0c-a092-07183e627329.png)
![saplogon_dvHlrNhfxg](https://user-images.githubusercontent.com/25269970/152596804-20feacab-2a7a-4bdc-b752-043fca5e398f.png)

All the project objects are active and the demos run just fine.

**Comment by mbtools** [comment]
I tested main and demo repos with v1.115.0 on 7.54. Both can be pulled without errors (just some warnings due to reserved field names)

Suggest closing

**Comment by AndreaBorgia-Abo** [comment]
I'll retest on new container, then close, thanks.

**Comment by AndreaBorgia-Abo** [comment]
Respun a new A4H container, updated certificates, installed current abapGit standalone, created ZABAP2XLSX package, pulled current abap2xlsx repo, all went well, closing, thanks :)
