### ISSUE TITLE
Provide pop-up, if recent branch does not exist on remote repo

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#5331]
Whenever the PR gets merged, the local repository does this
![image](https://user-images.githubusercontent.com/38354196/152760896-c525074d-2299-482c-bb52-1ab76ed074f3.png)
❓ Does it make sense to provide a pop-up that let's you confirm to switch to `main` or select any other branch or cancel? I am not an UI designer, but a very lazy click-through-the-menu person 😃

**Comment by larshp** [comment]
popups are a mess, plus what if there are no branches? the error message is nested into the git code, we dont want to add popups there, other refactoring are more important => low priority

**Comment by FreHu** [comment]
i agree with both of you, this is a pain point but complicated to change. I thought of adding a "prune" function to the list page which would go over everything and reset nonexisting branches to main, but this might involve multiple login popups appearing, you don't necessarily have permissions everywhere...

Some ideas for future:
- what if we added a html branch list option to the repo page with a switch button? this would make it easier to navigate from the deleted branch

**Comment by FreHu** [comment]
another problem is you can't delete the branch you are currently on, even if it doesn't exist
