### ISSUE TITLE
SSFO: Jump doesn't work

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5335]
https://github.com/abapGit-tests/SSFO.git

**Comment by g-back** [comment]
Did a little debugging, it does not execute the object specific jump method because `jump_wb` method of the "gui jumper" does not return an error, even though it does nothing.

**Comment by christianguenter2** [comment]
Maybe we should switch logic here and first call the object specific jump logic and if that's not succesful the generic one?
https://github.com/abapGit/abapGit/blob/c1dcebd8aadb4e94cc616359e05b4eef7d740398/src/objects/zcl_abapgit_objects.clas.abap#L980-L990

@mbtools what do you think?

**Comment by mbtools** [comment]
We should change the order indeed. However, we need to get the info from the object class whether the jump was executed or not. That's the same problem we currently face with WB jump going first. 

I expect the SAP function to return subrc <> 0. Can you investigate if this is just a SSFO issue or occurs also with other object types?

**Comment by christianguenter2** [comment]
SSFO is the only one I'm aware of. Everything else (I tested) works.
I prepare a PR.
