### ISSUE TITLE
CI - Repositories reusing/extending abapGit functionality

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#5336]
making a list, and checking it twice

when doing refactoring in abapGit, we would like to discover syntax errors in dependent repositories as soon as possible, ie. on PR

I think anyone should be able to add stuff in the list, they just need to update the repos so we dont keep getting errors over and over

* https://github.com/abapGit/abapGit-Plugins
* https://github.com/abapGit/CI
* https://github.com/abapGit/abapgit-review-example
* https://github.com/abapGit/background_modes
* https://github.com/abaplint/abaplint-sci-client
* https://github.com/Marc-Bernard-Tools/ABAP-Lint-Ext-for-abapGit

**Comment by flaiker** [comment]
> I think anyone should be able to add stuff in the list, they just need to update the repos so we dont keep getting errors over and over

Maybe the GitHub dependency feature would be useful? Couldn't get it to work though, but may be because I tried it in a fork, not sure.

![image](https://user-images.githubusercontent.com/5270359/153179115-f5f48cc9-dee4-482b-a7f9-7b2dba87e52f.png)

https://github.com/flaiker/CI/blob/main/package.json

**Comment by larshp** [comment]
the dependency graph only works with these ecosystems: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems

**Comment by larshp** [comment]
heh, as we are talking about this, there is now an API planned, https://github.com/github/roadmap/issues/467

**Comment by larshp** [comment]
full list,
![image](https://user-images.githubusercontent.com/5888506/153383652-422f5b47-a398-45f5-a4e8-4e4c04fd8911.png)

**Comment by sbcgua** [comment]
Maybe also this: https://github.com/sbcgua/abapgit_xml_stripper_plugin but as it appeared to be not working on the standalone AG version I'm not using it in fact :(

**Comment by larshp** [comment]
a few hours later... updated list,

![image](https://user-images.githubusercontent.com/5888506/153456380-8e68b9c2-81fc-47ef-a404-3e654b133b16.png)

**Comment by larshp** [comment]
done, closing

https://github.com/abapGit/abapGit/runs/5257578608
