### ISSUE TITLE
CLAS: Code Inspector - Missing CI-Check documentation

### ISSUE THREAD

**Issue by fanningert** [abapGit/abapGit#5339]
When I create a custom Code inspector check, the documentation is stored in SE61 with the documentation class CA and attribut 0000. Can you add this to the serialization of classes?

In the transport request this documantation is added with this entry.
LIMU	DOCU	CAZCL_CI_GENERAL_SUBCI          0000

Regards Thomas

**Comment by mbtools** [comment]
Closing this in favor of #5373

Note: It's not a trivial enhancement. Not sure if/when someone will get to this. Feel free to give it a shot.
