### ISSUE TITLE
Unable to Export existing Z Packages from SAP to Bitbucket Repo using abapgit

### ISSUE THREAD

**Issue by deepkkarnati** [abapGit/abapGit#5342]
when i try to push the existing Z package to Repo (repo already exist) in Bitbucket (onpremise) i am getting below error(screen shot1)

if i change the Repo URL to root path (like https://bitbuckethostname/scm/ab/),i am getting second error

Please suggest on how to push/upload the zpackages fro ECC to Bit repo

<img width="664" alt="error2" src="https://user-images.githubusercontent.com/99335838/153205810-6e15636e-4019-4e31-b93b-0e7d541069ae.png">
<img width="351" alt="repo1 error" src="https://user-images.githubusercontent.com/99335838/153205812-284b9772-29b4-4eac-a7a1-d9f216c06377.png">

**Comment by larshp** [comment]
see https://github.com/abapGit/abapGit/issues/5301

**Comment by larshp** [comment]
is it already versioned/created in abapGit? try clicking "show all" in the overview page, and check the list

**Comment by deepkkarnati** [comment]
it is not versioned or created in abapGit. 

on ECC system this Z pacakge is created in the standard way,now i am trying to push that code to Bit Repo

**Comment by larshp** [comment]
in the overview page, click "show all", and check the list, did you do this?

![image](https://user-images.githubusercontent.com/5888506/153245920-1706b43f-cae1-4b77-a7ee-68865dd9f664.png)

**Comment by deepkkarnati** [comment]
even though i select the "show all",it is only showing the package i created initially on abapGit
<img width="956" alt="Error3" src="https://user-images.githubusercontent.com/99335838/153250764-f30f9f20-ac3e-4044-8482-3e3b2f8cdd16.png">

**Comment by larshp** [comment]
ok

what is your package structure, is there a relation between package Z_ECO and TESTABAPGITPCKG ?

**Comment by deepkkarnati** [comment]
Nothing like that

**Comment by mbtools** [comment]
"ERR repository not found"

Some git hosts require `.git` at the end of the URL. Apparently your Bitbucket host is configured this way

"Repository ... already versioned as ..."

You already created an online repository for this URL (the correct on with `.git`). Therefore you cannot create another repo (with a different package for it). If you want the repo in a different package, you first have to remove or uninstall the old repo (`SE1ABAPGIT`).

**Comment by deepkkarnati** [comment]
Hello Marc,
what basically you are saying is "it is not possible to map  different Z* packages (existing package on ECC) to one repo (.git).
does this mean,lets say i have 10 Z* packages on ECC, i need to create 10 different  Repos (.git) in bitbucket ?

Thanks

**Comment by mbtools** [comment]
no. there are two options:

Example:

```
ZTOP_PACK
> ZSUB_PACK_1
> ZSUB_PACK_2
```

1. One repo for `ZTOP_PACK` (which includes also `ZSUB_PACK_1` and `ZSUB_PACK_2`)

or

2. Two repos for `ZSUB_PACK_1` and `ZSUB_PACK_2`

But you can't do both.

**Comment by deepkkarnati** [comment]
lets say i have Z_ECO1,Z_FI,Z_EWM,Z_ABC packages in ECC (all are core packages,non of them are sub package of other)
do i need create different  Repos for all above main packages ?
