### ISSUE TITLE
FUGR: Different Includes Sorting Order between S/4HANA and non S/4HANA

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#5346]
Hi,

We are using abapGit as part of S/4HANA migration project. When we migrate a function group from non S/4HANA to S/4HANA system, we are getting some differences for few function groups. It is due to missing sorting order for the function group includes. Below is my analysis for method ZCL_ABAPGIT_OBJECT_FUGR~INCLUDES.

1. The function module 'RS_GET_ALL_INCLUDES' behaves differently between S/4HANA and non S/4HANA system. In non S/4HANA system, it is not returning an include ending with T00 and this is the reason the existing code is adding this if missing.

**non S/4HANA System**:
![image](https://user-images.githubusercontent.com/29766214/153776848-71ac289c-4dc8-495e-95de-84b76f27b332.png)

**S/4HANA System**:
![image](https://user-images.githubusercontent.com/29766214/153776875-6d36b889-cc21-4bf3-986d-aa6dfc871576.png)

2. The final .fugr.xml file will have different sorting order.

**non S/4HANA System**:
![image](https://user-images.githubusercontent.com/29766214/153777011-047df29d-6d36-44a3-8c8a-622bff336e0d.png)

**S/4HANA System**:
![image](https://user-images.githubusercontent.com/29766214/153777037-7cb52a13-78d4-4d81-becb-0efd9430446c.png)

Note that include LZFG_HOST_PLUT00 is having different row in the file. This is creating conflicts during merge process.

**Suggested Solution**:
Sort the internal table RT_INCLUDES at the highlighted line.
![image](https://user-images.githubusercontent.com/29766214/153777162-73793f01-3d79-4a1f-a544-5d02e67d528a.png)

Regards,
Yellappa.

**Comment by larshp** [comment]
nice find, yes, sort it, pull requests welcome
