### ISSUE TITLE
Enterprise GITlAB  - Unauthorized access to resource (HTTP 401). Check your credentials 

### ISSUE THREAD

**Issue by shanvelc** [abapGit/abapGit#5353]
Hi All,

I am trying to connect enterprise GITLAB private project to SAP system.
Connectivity worked and its asking for authentication.
I have created personal access token with API scope and provided the username and token but i am getting Unathorized acces did i miss anything.Thanks

**Comment by larshp** [comment]
try using command line git to see if cloning that way works

**Comment by shanvelc** [comment]
Sorry how to use it?

**Comment by larshp** [comment]
https://docs.gitlab.com/ee/gitlab-basics/start-using-git.html#clone-with-https

**Comment by christianguenter2** [comment]
Also see #5234

**Comment by shanvelc** [comment]
Thanks to both of you. i used oath2 as user name and it worked.

**Comment by larshp** [comment]
cool, closing
