### ISSUE TITLE
Repo view path name layout

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#5355]
I must say I really do not like the path layout introduced in #5323 (sorry @FreHu, no offence, really appreciate all the other great stuff you've done!). Is it a huge effort to make this optional?

Personally I prefer higher information density and it is now way too spread out and I can see less. I now quite literally have half the info I had before on my screen, my view of 12 objects has been reduced to 6:
<img width="2257" alt="image" src="https://user-images.githubusercontent.com/25539927/154124316-11fd471e-1739-4529-acf5-da4942f1f7ac.png">

Onto the subjective opinion part: visually I also find it awkward with everything crammed to the left with oodles of space on the right, I am almost always primarily interested in the objects and much prefer them on their own without the fluff in between. I find it makes the object list harder to scan through.

**Comment by christianguenter2** [comment]
You can hide the file paths. Maybe that helps a bit?
![grafik](https://user-images.githubusercontent.com/17437789/154135324-a139189b-700e-4b4e-94c6-b03f41acee55.png)
![grafik](https://user-images.githubusercontent.com/17437789/154135123-d7820fe4-7c86-4dde-a1fa-05300969ac13.png)

**Comment by FreHu** [comment]
One of the other great things I've done is the "show changes only" filter :-). Based on your screenshot it should improve the number of visible objects quite a lot.

As for everything now being on the left, there are some more things to consider:
- long file paths issue
- you can have abapgit on a primary monitor with reduced size and still see the paths

**Comment by pokrakam** [comment]
Yes, "show changes only" is better, but IMHO still not as nice to scan for an object. But then maybe that's just me :) I'm not a fan of multiline lists with header/detail in the same column.
@christianguenter2 Yes that helps but hides which file has changed. Maybe we can mark that somehow? 

Maybe it's just my use case that exacerbates the issue? Moving objects between SAP versions there are often insignificant changes in the XML metadata. To me I got used to the position of the `diff` marker being significant, xml is at the bottom, code is top or middle.
<img width="445" alt="image" src="https://user-images.githubusercontent.com/25539927/154164311-b32abca8-4e9c-413e-bc22-02e97f6a0e08.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/25539927/154164394-2627f311-ef1b-4f53-aef9-717808723ee4.png">

Anyhow, I can work with switching views so if I'm a minority and the consensus is that the current format should stay then I'm OK with that.

**Comment by FreHu** [comment]
I also had a plan to move the status to the left (#3268), as well as play with the borders. But my attempt so far looked a bit weird because
- stage has no object names
- stage only shows changes

I'll try to sumbit a draft later today so we can experiment

**Comment by sbcgua** [comment]
@pokrakam Do you use file view just to identify significant/insignificant changes ? Is it the only usecase?

I always hide files, I find them clutter the view and reduce observability, especially in large repos. Usually the fact that object has been changed is the most important. +changes first or changes only features makes me my optimal workspace. Sometimes I switch to file-view for cases like object changed its package but this is it. Of course this is only my opinion and practice, but what I want to say is that it might be a matter of habit.

Addressing the "identify significant/insignificant changes" problem. Maybe it makes sense to aggregate changes to the object level? E.g. label-like markes to specify if the hidden files contains `xml`, `abap`, `ut`, `bin` (or maybe just by file extension to not overcomplicate)

**Comment by pokrakam** [comment]
@sbcgua yes, it's not just about significant/insignificant, but in general I'm always looking at the type of change. It's mainly about metadata vs. content. So my file view has always been on, mainly because I want to know what changed. 
It was a nice arrangement: scan down a clean list to take in the objects and glance at the expansion to the right to see what type of change it was. I find a mixed vertical list less readable. But we are talking first-world problems here :-)

I like your suggestion, is in the same direction as I meant with "mark that somehow". 

But I'm ok with the idea of let's use it for a while and see.

**Comment by FreHu** [comment]
another option would be to allow hiding object names - if you're used to looking at path+status, by the time you look at the object name on the right, you already know it from the path. But then the possibility of ADT navigation is lost.

**Comment by FreHu** [comment]
Attempts at border improvements:
fatter-thinner
![image](https://user-images.githubusercontent.com/5097067/154323281-8f496133-2d81-456d-a535-2dc5ff7dc217.png)
below object only
![image](https://user-images.githubusercontent.com/5097067/154323264-3e621994-dd71-46b3-9f93-a5b2d816ed28.png)

Titles from the status could be shown on row hover, this requires decoupling the texts
![image](https://user-images.githubusercontent.com/5097067/154323630-b8801d0b-982b-4227-b44c-7f84c32b09de.png)

**Comment by sbcgua** [comment]
Hmmm, imho, thin lines + no lines inside object would be the best ...

Status on row hover: I'd say the title on row hover will always inevitably close something on the screen - this could be annoying. Just a feeling.

**Comment by sbcgua** [comment]
![image](https://user-images.githubusercontent.com/15635498/154336106-02b8d55b-811b-4d74-adb7-0b6b7ad440e5.png)

Hmmm ...???

1) tags show changed categories (or just file extensions ... but I'd emphasize UTs)
2) Also not bad with current row hover, though see 5 ...
3) color may signify what exactly was deleted (I'm not big fun, I think too many colors is bad)
4) By the way why we need label border around changed_by ? Doesn't it look overemphasized ?
5) By the way the row hover color looks a bit not in line with other colors. in particular blueish object names. Maybe smth like this ?

![image](https://user-images.githubusercontent.com/15635498/154337645-a54fd863-abc1-42c0-b8b1-57ae59aaaeb9.png)

**Comment by flaiker** [comment]
Could also do something like this to remove width while keeping separate columns (removing obj_name and type from filename as they are in the previous columns assuming that always matches)

| Type | Path | Name | File | Changed by |
|-|-|-|-|-|
| CLAS | /src/objects | ZCL_ABAPGIT_OBJECTS | .abap | DEVELOPER |
| | | | .xml| |
| W3MI| /src/ui | ZABAPGIT_CSS_THEME_DEFAULT | .data.css | DEVELOPER |
| | | | .xml  |

**Comment by FreHu** [comment]
> 1. tags show changed categories (or just file extensions ... but I'd emphasize UTs)

I like the tags concept a lot. I would add a DDIC tag (not every xml change is that insignificant). Maybe even custom tags through user exit eventually...

> 2+5. Also not bad with current row hover, though see 5 ...

Your hover is different than mine, the color must be wrong in the one of the themes. I would unite it to the lighter grey in my screenshots.

> 3. color may signify what exactly was deleted (I'm not big fun, I think too many colors is bad)

too many is bad, but green/yellow/red will be in pretty much every application

> 4. By the way why we need label border around changed_by ? Doesn't it look overemphasized ?

@mbtools made these for username/package/transport, I don't care either way but they are currently consistently styled everywhere

> ![image](https://user-images.githubusercontent.com/15635498/154337645-a54fd863-abc1-42c0-b8b1-57ae59aaaeb9.png)

@flaiker recently there was a user exit added to shorten file names, I think this might get confusing but I haven't looked at it closely yet.

What about subobject types? They could be shown in the type column too

**Comment by mbtools** [comment]
now we are mixing things... 
- keep this issue about view WITH file names
- open another issue for view WITH object names only (no files)
- open another issue about formatting of user/transport/package
thx

**Comment by FreHu** [comment]
I agree this needs to be split up.

To reduce the number of points, easy things which can be in a small PR are:
- hover color
- borders
- reduce line height (currently it's 1.5 which is part of the reason the view is so spaced out)

I would also separate out the tag feature.

**Comment by mbtools** [comment]
Stale. Closing
