### ISSUE TITLE
Repo view CSS adjustments

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#5359]
https://github.com/abapGit/abapGit/issues/5355#issuecomment-1042204426

- hover color in one of the themes
- borders
- reduce line height (currently it's 1.5 which is part of the reason the view is so spaced out)

**Comment by mbtools** [comment]
i would go for borders above/below tadir objects only. separate objects and files using smaller font-size.

reduced line-size for files is ok but limited by size on state icons

**Comment by sbcgua** [comment]
reduced line size for files is probably good. But pleeeese keep 1px border :) 🙏
