### ISSUE TITLE
APACK Manifest in customer /namespace/

### ISSUE THREAD

**Issue by Ennowulff** [abapGit/abapGit#5363]
Hey! I just ran into the following issue:
I found it was a good idea to define the dependencies of my own products using /-namespace by using ZIF_APACK_MANIFEST.
It turned out it was not a good idea as I cannot expect the customer to have abapGit installed.

in this [discussion](https://github.com/abapGit/abapGit/pull/2485#discussion_r319923441) I found a hint about how to implement an /namespace/APACK interface. If I understood correctly then there is no solution for that so far.

Any suggestions how to deal with this issue and use the apack manifest in own products?
@SebastianWolf-SAP @larshp @DerGuteWolf 

thanks
Enno

**Comment by SebastianWolf-SAP** [comment]
Unfortunately, there is no suggestion from my side. The idea hasn't gained much traction over the last 2 years, so there was also virtually no further development (at least nothing that I'm aware of). 

But maybe times have changed in the meantime. If there is enough interest, I might be able to reserve a bit of time for improvements.

**Comment by Ennowulff** [comment]
Thanks for your fast response, @SebastianWolf-SAP !
at least there needs to be a way to define an alternative APACK manifest to (Z)IF_APACK_MANIFEST for each package IMHO.
Maybe somewhere in the abapgit repository settings?
![image](https://user-images.githubusercontent.com/75187288/154517860-bd11c3c7-0ea2-4974-b80a-6370da0c2807.png)

**Comment by Ennowulff** [comment]
there is no 😢 reaction
