### ISSUE TITLE
pull fails on XSLT with tt:call-method, if classic program refers to this class

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#5365]
This is another [minimal test case](https://github.com/sandraros/test-abapgit/tree/issue-5365) (branch `issue-5365`) which concerns issues related to XSLT activation. It's almost the same as #5262, but I think it's worth documenting them in separate issues so that we can have all test cases if we agree on a fix (I am working on it). For information, we also have a third test case, which is https://github.com/abap2xlsx/abap2xlsx/issues/993 (with different abapGit behavior, I am also trying to build a minimal test case for it).

My system is ABAP 7.52 kernel 753 SP 500 (before the kernel indicated in the note 2859159 - link below).
I have abapGit 1.114.0, latest pull.

Marc has nicely explained the general problem [here](https://github.com/abap2xlsx/abap2xlsx/issues/993#issuecomment-1040918350), so I just copy/paste it:
> This project contains XSLT and if those objects don't activate properly, then nothing else will work (due to Ddic and code dependencies).
> Therefore, please check SAP note https://launchpad.support.sap.com/#/notes/2859159 first and make sure you have the right kernel version running.
> Secondly, run the very latest version since we continuously improve things like #5303 which shows inactive TABL objects correctly (note: similar handling of other DDIC types is still missing).
> To have a reproducible case, uninstall the complete repo and install it again. Attach output of Utilities > Debug info and screenshot after initial pull.

# To reproduce
- Install the fix #5369 (otherwise there will be some errors not related to transformation)
- New Online https://github.com/sandraros/test-abapgit → Switch to branch `issue-5365`:
  ![image](https://user-images.githubusercontent.com/34005250/154805711-8a9cf241-985d-4aa8-8b1f-625a3276eb54.png)
- Pull → "Activation cancelled. Check the inactive objects. ":
  ![image](https://user-images.githubusercontent.com/34005250/154816914-c156e80b-3e41-4a86-b12a-0c970c81cdfe.png)
- Pull again does the same as above

**Comment by sandraros** [comment]
So that the test case above pulls correctly, I think that #5369 and #5370 are also needed.

**Comment by mbtools** [comment]
Retested https://github.com/sandraros/test-abapgit/tree/issue-5365. Works fine with v1.115.0

Fixed by #5393
