### ISSUE TITLE
Issues concerning DDIC objects with reference types

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#5366]
Activation issues for these DDIC objects:
- Data Element of type reference
- Structure with component being a data element of type reference
- Table Type with line type being a data element of type reference

# To reproduce
- New Online this repository: [branch "issue-5366"](https://github.com/sandraros/test-abapgit/tree/issue-5366)
- Pull → "No active version found for TTYP ZTESTTABLETYPE", "Row type OBJECT is not active or does not exist", "Table Type ZTESTTABLETYPE could not be activated":
  ![image](https://user-images.githubusercontent.com/34005250/154812861-d45264a6-27df-4f3a-a3fd-1ae591793d92.png)

**Comment by mbtools** [comment]
I think we have most of those test cases (except DTEL). Can you please check as well?

https://github.com/abapGit-tests?q=ref&type=all&language=&sort=
