### ISSUE TITLE
CLAS/INTF: Missing documentation for attributes, events ,methods

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5373]
Documentation types supported by abapGit:

```
CL		Class
IF		Interface
```

Not supported:

```
CA		Class attribute
CE		Class event
CO		Class method
IA		Interface attribute
IE		Interface event
IO		Interface method
```

`CA` is also used by Code Inspector (see #5339).

Enhancements of `zcl_abapgit_object_clas/intf->de/serialize_docu` are required.

**Comment by frij-aws** [comment]
+1 on this. I was just about to enter an issue on the same topic. Very interested in this feature

**Comment by mbtools** [comment]
It's not that difficult to implement. Just a bit of coding work

1) It's a loop over all class components and calling `serialize_docu` (https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_clas.clas.abap#L393).

2) `serialize_docu` needs to be enhanced to import the `id` and full component name (not just class). 

3) When adding the data to the `xml`, `iv_name` needs to be different for each call. So keep `LINES` and `I18N_LINES` for the class and append the component name for other calls (`LINES_<component>`).

4) `deserialize` needs to do the same in reverse. To simplify `deserialize`, I would also add a list of the components to the `xml` during `serialize`

Want to give it a try, Jon?

**Comment by frij-aws** [comment]
I can't make any promises but if I can carve out some time I'll fork and take a whack at it.

**Comment by frij-aws** [comment]
I have a commit for this functionality.  Can you assign this issue to me?

**Comment by frij-aws** [comment]
it seems like the pull request isn't linked to this issue; can someone link it for me?  I don't think I have permission.  It's pull request 5575

**Comment by mbtools** [comment]
You just have to mention "Closes #xyz" in the PR description :-)

**Comment by frij-aws** [comment]
Interesting, so "[resolves](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) #xyz" doesn't do it?

**Comment by mbtools** [comment]
"resolves" should work, too, but it needs to be in the description not the title ;-)
