### ISSUE TITLE
SAP Abap Version

### ISSUE THREAD

**Issue by timbolski** [abapGit/abapGit#5375]
Hi, we need to export some code to an older version (731) but we have used a lot of the new syntax in 740. Is abapGit valid back to 702?
Are there plans to allow abapGit start using the newer syntax?
What thought has gone into where the line is drawn to using newer syntax and refraining from using it? Any discussion or links are appreciated.
Tim

**Comment by larshp** [comment]
yes, we aim to have abapGit 702 compatible, https://github.com/abapGit/abapGit#readme, there might be a few syntax sneaking in every now and then, but just open an issue. abaplint runs for version 702 to check syntax on every push, https://github.com/abapGit/abapGit/pull/5374/checks?check_run_id=5279452610

sometime we will move to using 740 syntax, but its not at the top of the list. However we will still publish a 702 version

suggest using https://rules.abaplint.org/downport/ to automatically downport to 702 syntax, but do manually look through the changes, ABAP is a crazy language 😄

**Comment by mbtools** [comment]
I think your question is more about your own code. As Lars wrote, abapGit itself supports SAP release 7.02 and higher. [For some good consulting $$$, I might be convinced to make a version that could run on lower releases]. 

This is independent of the syntax that you use for your own code. abapGit will not make any changes to your own code when you create a repository and push the code to it. In particular, there's no magic downport in abapGit.

Therefore, you when you try to import your repo (which uses 7.4 syntax) into a lower release, it will result in syntax errors. The code will be imported so you can edit and adjust it manually.

Alternatively, you can try to use abaplint to downport your repository. This will happen within GitHub i.e. ourside of any SAP system.  You can see an example of such workflow [here](https://github.com/abapGit/downport).

**Comment by timbolski** [comment]
Yes, my question relates to our code that we need to down port to 731 for a customer. Unfortunately, we won't have abapGit into this customer (we do at 2 others) so we will need to fix in our 750 system and send a transport.

**Comment by mbtools** [comment]
well, do a quick calc on how much time you would need and how much $$$ that would mean. might be worth for the customer to use abapGit

**Comment by timbolski** [comment]
I try to convince many of my customers to use abapGit. Usually get stuck with the blocker types (with no imagination for doing things better), unfortunately.

**Comment by mbtools** [comment]
I know, SAP shops can be quite traditional. Try the level "above" the blockers or the business-side who is funding the project. They might be convinced by "$-saved".  -

**Comment by larshp** [comment]
@timbolski feel free to join our Slack channel, https://abapgit-slackinviter.herokuapp.com/, its public invites for everyone

can we close this issue?

**Comment by timbolski** [comment]
Hi Lars,

                Yes, we can close the issue. I am trying to get abaplint working now.

 

tim

**Comment by larshp** [comment]
feel free to open issues/questions regarding abaplint in the abaplint repository

closing
