### ISSUE TITLE
Duplicate key runtime error when creating/connecting to online repo

### ISSUE THREAD

**Issue by jdgx** [abapGit/abapGit#5380]
Hi all,

I get a duplicate key runtime error (`cx_sy_itab_duplicate_key`) when connecting to a certain online repository for a package with several sub-packages, see source code/call stack below.

History (as far as I remember): I had an online repository running for sub-package B of super-package A, which was running smoothly. Then I tried to add  an online repository for A (including all sub-packages), which failed because B was already connected to git. So I removed the repository for B and afterwards I tried to add the repository for A (including all sub-packages) again, and then the runtime error occurred. The online-repository for A was created, but the runtime error occurs every time I try to connect. I already tried to remove and add the repo for A again, but the issue is still there.

I have the feeling that some leftovers from the original repo for B or from the failed attempt to add the repo for A are causing trouble.

Any idea how this could be solved?

Best,
Jonathan

![2022-02-24-abapgit-duplicate_key-code](https://user-images.githubusercontent.com/87188377/155522073-8c2bf29f-2bbd-473a-b43c-7e9e4aeee1f3.png)
![2022-02-24-abapgit-duplicate_key-call_stack](https://user-images.githubusercontent.com/87188377/155522103-375f0f3c-dd66-4574-abac-be1adafc0e72.png)

**Comment by mbtools** [comment]
Hi Jonathan,

the root cause is related to OTR texts (object type `SOTS`). What is the value for `iv_extra`? 

For a more detailed analysis, identify the package causing the problem. It's in ms_item-obj_name. Then look up table `SOTR_HEADU` for this package (field `PAKET`). This will give you the concepts (of the texts) which you can then lookup in `SOTR_TEXTU`. Fields `CONCEPT`, `LANGU`, and `OBJECT` should make a unique filename (=`iv_extra`). Maybe there are some special characters? 

Best,
Marc

**Comment by jdgx** [comment]
Thanks for the quick reply. There seems to be an issue with case sensitivity. In my case for the given package `sotr_textu-langu` has different values on DB, but some of these values only differ by case. E.g. there is an entry with SAP language code "D" (= iso code "DE" = German), but also another entry for "d" (= iso code "SH" = Serbo-croation); the same happens for C/c = Czech/Catalan.
In the file name and `iv_extra` the langauge code is always converted to lower case. Hence the clash.

**Comment by mbtools** [comment]
Can you test https://github.com/abapGit/abapGit/pull/5381?

**Comment by jdgx** [comment]
With #5381 it works without issues, thanks!

One general question: To test this correction, I just changed manually the few lines of code in the standalone abapgit program. But in case of larger changes this would be cumbersome. Is it possible to generate the standalone abapgit for a given pull request or commit?

**Comment by mbtools** [comment]
yes, it is. In remote settings, simply pick the PR and save. Then you can pull the changes. After testing, go back to the settings and pick a branch like main and save. Pull to get back to the original source.
