### ISSUE TITLE
Can't start abapGit in SAP GUI for Java due to Type conflict during a function module call

### ISSUE THREAD

**Issue by gregorwolf** [abapGit/abapGit#5385]
With the PR #5354 src/ui/zif_abapgit_popups.intf.abap was changed: 

```
- !iv_icon_button_1         TYPE icon-name DEFAULT space
+ !iv_icon_button_1         TYPE clike DEFAULT space
```

See: https://github.com/abapGit/abapGit/commit/4ac0183df271fb9dd79daef2cb2e83af6e680c19#diff-dc275cf67a77776534caa65faf419e460c02a61ab7ac7e9092babc99eb4d065fR47

This causes a dump when starting abapGit in SAP GUI for Java due to Type conflict during a function module call.

**Comment by larshp** [comment]
argh

**Comment by larshp** [comment]
@gregorwolf can you help testing #5386?

**Comment by larshp** [comment]
closing, confirmed working in https://github.com/abapGit/abapGit/pull/5386
