### ISSUE TITLE
[IWSG] - Clear metadata fields

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#5391]
As part of serialization, IWSG object type uses generic class ZCL_ABAPGIT_OBJECTS_GENERIC. This object type has certain metadata fields which are creating diffs.

Table having metadata fields such as user name and timestamp.
![image](https://user-images.githubusercontent.com/29766214/156677484-9284e52a-1469-40cc-9063-ce3bdd1be625.png)

Diffs in abapGit
![image](https://user-images.githubusercontent.com/29766214/156677564-129362f3-9b84-44d4-8b7a-0854ea55fd3f.png)
![image](https://user-images.githubusercontent.com/29766214/156677608-e7179693-5ff8-49f8-bcdc-535c6eec787d.png)

As it is using generic class, I don't think adding logic here make sense to clear these metadata fields. We might come across similar issue for other object types which might have different names for the metadata fields. Please suggest a solution.

**Comment by larshp** [comment]
thanks, can you help with a corresponding PR?

**Comment by yellappam** [comment]
Here, the tables are dynamic and metadata fields are also dynamic based on object type. I am looking for suggestions where to make the changes. I am thinking, as the fields are specific to given object type, we can move this generic logic to IWSG class and clear metadata fields there. Please let me know if anyone has other ideas.

**Comment by mbtools** [comment]
Same as https://github.com/abapGit/abapGit/issues/4696 😉 

Of course, we could do all in the IWSG class but then we can't use that logic in other classes based on generic. Some kind of rule-based approach as hinted in #4696 would be ideal. 

PS: Clearing is only one side. You also have to fill the fields during deserialize.

**Comment by yellappam** [comment]
#4696 recommendation looks good to me. I will work on this.

**Comment by yellappam** [comment]
@mbtools - I will work on the below object types. Will submit PR separately for each object type.

IWMO, IWOM, IWPR, IWSV, IWVB
