### ISSUE TITLE
[Standalone] ABAP_LANGUAGE_VERSION not found

### ISSUE THREAD

**Issue by lucasborin** [abapGit/abapGit#5394]
Using the [ZABAPGIT_STANDALONE](https://raw.githubusercontent.com/abapGit/build/main/zabapgit.abap):

![image](https://user-images.githubusercontent.com/5233413/157302266-84ea065d-ad65-4f3b-b1e2-8deb16005ccb.png)

![image](https://user-images.githubusercontent.com/5233413/157301894-ee721fed-f3ee-4b53-a992-21e9352f9444.png)

![image](https://user-images.githubusercontent.com/5233413/157301962-b98b5bc2-8f8e-4596-968e-b242a66f2b71.png)

![image](https://user-images.githubusercontent.com/5233413/157302056-77aa2826-09c3-487d-950c-f477e5a709ea.png)

Navigating, it includes the:

![image](https://user-images.githubusercontent.com/5233413/157302153-fcebc6e8-575b-43d6-9f60-239464424168.png)

Should we remove it?

![image](https://user-images.githubusercontent.com/5233413/157302825-b16316b5-c335-4049-966f-065004ea4f0d.png)

Ps: S4CORE - 107 (SAP internal version), ABAPGIT - 1.114.0

**Comment by christianguenter2** [comment]
As a quick fix change `ASSERT` to `CHECK`.

**Comment by larshp** [comment]
@lucasborin can you help with creating a PR?

**Comment by ThomasPloski** [comment]
I will provide a PR for that. There was a structure change which needs to be considered.

**Comment by mbtools** [comment]
Did #5395 fix it?

**Comment by lucasborin** [comment]
Sorry guys, busy week. Let's continue in the PR directly.

**Comment by lucasborin** [comment]
Issue fixed.
