### ISSUE TITLE
basic authentication problem

### ISSUE THREAD

**Issue by mindvortex** [abapGit/abapGit#5400]
I was using abapgit with basic authentication without any issue. Yesterday when I connect my bitbucket repo with username and password , I got 401 Unauthorized.

I can connect my bitbucket repo on browser with same credentials.

![image](https://user-images.githubusercontent.com/20014388/158568233-39cd0529-8641-49cb-b954-5cd0c3dd9048.png)

**Comment by larshp** [comment]
see https://github.com/abapGit/abapGit/issues?q=is%3Aissue+bitbucket+is%3Aclosed

make sure to use the correct username as described in https://stackoverflow.com/questions/39886995/how-to-access-bitbucket-using-app-password

**Comment by mindvortex** [comment]
Thanks for quick reply !
