### ISSUE TITLE
Pulling failed when creating enterprise services for RFC functions.

### ISSUE THREAD

**Issue by mkiii** [abapGit/abapGit#5405]
CL_WS_MD_VIF_FIELD 
IF_WS_MD_VIF_FIELD~SET_TYPE
me->inactive-typeref = type->get_name( ).
When using  getname() for field 'DATAS',  program crashed and triggered system runtime errors.
![image](https://user-images.githubusercontent.com/8252523/159878481-14f70823-2c5c-4044-be44-3cf8ba3da634.png)
Field 'DATAS' is Table Type whose line type is Structure.
![image](https://user-images.githubusercontent.com/8252523/159876401-8339af7f-7a08-439c-af13-d5a16b5bdb41.png)
![image](https://user-images.githubusercontent.com/8252523/159878977-e918c0a9-c429-4edc-bdd2-96eb0f39ca08.png)
![image](https://user-images.githubusercontent.com/8252523/159879063-f0e512ed-f483-4016-92c4-d11b23edb910.png)
![image](https://user-images.githubusercontent.com/8252523/159876780-c6217db5-e5ad-434e-b1ff-f52a29966805.png)

**Comment by mbtools** [comment]
Can you create a test repo that contains only the object which causes the dump and post a link to the repo?

**Comment by mbtools** [comment]
I took some time to reproduce this using your zip file. However, the objects are in a non-standard language (Chinese?) and also require ERP or S4. I'm unable to run a test with this. 

Do you have an example that works in NetWeaver only and is in English?

**Comment by mkiii** [comment]
I'm afraid not have an English Netweaver environment.  

After removing "zmes_schedule_sync_service.webi.xml" from zip file，other development objects have been imported in S4H successfully.  AbapGit still helps a lot.

**Comment by mbtools** [comment]
no action
