### ISSUE TITLE
Long SAP package names

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5410]
If the package hierarchy contains longer name that do not fit to the custom namespace (does not begin with Y/Z/NAMESPACE), then neither folder logic `prefix` nor `full` will work.

This can happen if the folder structure is predefined by 3rd party (as for example exercism.org).

Example:

```
/concept
/concept/largest-series-product
/practice
/practice/kindergarten-garden
```

With very short package name `ZE` and `prefix` logic:

```
ZE
  ZE_CONCEPT
    ZE_CONCEPT_LARGEST-SERIES-PRODUCT " too long
  ZE_PRACTICE
    ZE_PRACTICE_KINDERGARTEN-GARDEN " too long
```

With `full` logic:

```
ZE
  CONCEPT " not valid
    LARGEST-SERIES-PRODUCT " not valid
  PRACTICE " not valid
    KINDERGARTEN-GARDEN " not valid
```

Proposal:

Introduce a new folder logic named `mixed` which will use the root package name as prefix but *not* add the folders recursively.

```
ZE
  ZE_CONCEPT 
    ZE_LARGEST-SERIES-PRODUCT 
  ZE_PRACTICE 
    ZE_KINDERGARTEN-GARDEN 
```

**Comment by flaiker** [comment]
This only affects repos where the folder structure was created outside of the ABAP system or if the target namespace / prefix is different and uses more characters, right?

I don't think abapGit needs to support this. Mixed would also fail if the folder name is just too long?

**Comment by mbtools** [comment]
It's also relevant for regular ABAP development. Depends on the naming conventions of the importing system. Some customers are very strict about it. if they require a certain prefix, the current prefix logic might  not work for them (due to name length).

**Comment by flaiker** [comment]
Seems wrong for customers to enforce their package naming conventions on external software but I guess technically it's their namespace :/

**Comment by mbtools** [comment]
It's the beauty of AG that customers can pick and fit it to their package conventions. One less hurdle preventing adoption :-)
