### ISSUE TITLE
Grid buttons out of screen

### ISSUE THREAD

**Issue by lucasborin** [abapGit/abapGit#5418]
![image](https://user-images.githubusercontent.com/5233413/160906397-fb20e39a-4811-4111-9c00-657d650bddb2.png)

This particular repository uses the 'full' mode and contains a file with 173 characters (path+name).
Consequently, the screen is not big enough to display the whole object name and the other columns (like actions).
As a workaround, I can force zoom out to see/use them. 

It affects the leading and stage pages.

**Comment by mbtools** [comment]
Which object type is causing the problem? Can you share an example of such filename?

**Comment by lucasborin** [comment]
> Which object type is causing the problem? Can you share an example of such filename?

Local Test Class, 

/#dmbe#integration/#dmbe#publishable_documents/#dmbe#mm_contracts/#dmbe#mm_mapping_steps/#dmbe#mm_optionality_steps/#dmbe#cli_mm_create_option_itm.clas.testclasses.abap

**Comment by mbtools** [comment]
Nice package hierarchy and with namespaces, too. 😀 

We do have an [exit](https://docs.abapgit.org/ref-exits.html#adjust_display_filename) to shorten the filenames but it's not called on the staging page. I will check if that can be implemented (there's some JS that might depend on the name).

Adding a word-break to the CSS could be an option.

**Comment by mbtools** [comment]
See #5424
