### ISSUE TITLE
Dynpro in background processing

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5420]
Some object types lead to dumps when processing in background:

![image](https://user-images.githubusercontent.com/59966492/160922536-311926f4-21a8-4aff-8f01-698211d183f2.png)

- [x] ENHC, ENHS, ENSC: calls `cl_enh_factory=>get_enhancement[_spot|_spot_comp]` 
  set parameter `run_dark = abap_true`

- [x] TRAN: calls `RPY_TRANSACTION_INSERT`
  set parameter `suppress_corr_insert = abap_true` and add `corr_insert()`

- [x] SPRX: calls `cl_proxy_data=>delete_single_proxy`
  set parameter `suppress_dialogs = abap_true` 

- [x] SOTS: calls `btfr_create`
  to be investigated -> moved to #4480
  
Need to check if these parameters exist in 702.

**Comment by mbtools** [comment]
The above parameters exist in 702 :-)

**Comment by AndreaBorgia-Abo** [comment]
> The above parameters exist in 702 :-)

I'm getting an activation error because of "suppress_dialogs" missing on a SAP_ABA	SAPKA74003 when loading the single-source report.

**Comment by mbtools** [comment]
#5430
