### ISSUE TITLE
Performance: Mouse Hover

### ISSUE THREAD

**Issue by lucasborin** [abapGit/abapGit#5423]
The hover feature, available in the stage view, has a performance issue when you have a huge number of files to commit.
For instance, there are ~7.8k changes to commit here. It is an unusual scenario. We are converting an offline repo to be online.

Besides, if you let the mouse on the grid, activating the hover function, you will get stuck when you scroll up or down as the hover function takes too long to be performed. If you let the mouse off the grid, the scroll runs fine. 

![2022-03-30_17-43-27](https://user-images.githubusercontent.com/5233413/160928118-d85beb38-5228-478a-ba15-414743bd08ae.gif)

**Comment by mbtools** [comment]
close?

**Comment by lucasborin** [comment]
That's a workaround when you are pushing something assigned to transport. Unfortunately, that's not the case here. 

A feasible solution would be having a user configuration to enable/disable the hover function. In this case, I would simply disable the hover until I organize the sync of the pending objects. Anyway, up to you to decide if you want to keep it as it is. If so, we can close this thread.

**Comment by lucasborin** [comment]
Ok, that's a good temporary solution. Thanks for your support. :)
