### ISSUE TITLE
CLAS: Deserialize fails for workflow attributes

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5449]
Test https://github.com/abapGit-tests/CLAS_wf fails

![image](https://user-images.githubusercontent.com/59966492/161817992-907acc5f-954e-45aa-9e46-5f572a2851ec.png)

![image](https://user-images.githubusercontent.com/59966492/161818328-de9c5e4d-38e5-495c-847c-70337654f059.png)

Attributes are save first in `zcl_abapgit_oo_class->create`. However, it looks like they are overwritten by `deserialize_source`.

**Comment by flaiker** [comment]
So this can be solved by filling `<ls_vseoattrib>-state` and `<ls_vseoattrib-exposure` in `zcl_abapgit_oo_base->convert_attrib_to_vseoattrib`. State can (must) be `seoc_state_implemented`. Exposure however needs to be correct to work. It would have to be extracted from the source code which seems very cumbersome. One could also save it redundantly in attributes, which in my opinion would be fine here, however unfortunately the initial value for exposure, `0`, is `seoc_exposure_private`. These attributes will mostly be public (but key can be private and protected as well, readonly raises as skippable syntax error...). So there would be a little migration scenario where the values in the XML would be swapped or some kind of helper attribute or not used value (or ignore this as usage of this feature might be close to none).

I tried deserializing to inactive first if attributes is not initial as `cl_oo_section_source->revert_attributes` says:

```
*     keep attr. of business classes or work flow artifacts, as no source code representation
      attrib-attbusobj = wa_vseoattrib_old-attbusobj.
      attrib-attkeyfld = wa_vseoattrib_old-attkeyfld.
```

and takes the values from the inactive version (exposure also seems to have to match for this though). Not sure where this falls back to the active version stated above, but should be the same logic.

I would probably suggest to add EXPOSURE to ATTRIBUTES and maybe swap the values for PRIVATE and PUBLIC in the XML on serialize / deserialize if compatibility is wanted here.

**Comment by mbtools** [comment]
Too much for me to follow 😄  It's not working now so I don't see any need for compatibility. Feel free change as needed.

**Comment by larshp** [comment]
CLAS attributes works, for almost all cases, this is a special workflow related test case? ie. the title of the issue is misleading

**Comment by flaiker** [comment]
Yea, sorry, the implementation from SAP doesn't seem to happy about these attributes existing either :) I'll create a PR.

> CLAS attributes works, for almost all cases, this is a special workflow related test case? ie. the title of the issue is misleading

Correct, these are the two checkboxes that show up in SE24 if the interface `IF_WORKFLOW` is implemented.
