### ISSUE TITLE
TOBJ: abapGit CI fails

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5451]
Test https://github.com/abapGit-tests/FUGR_maintenance_view_variant.git fails

Deserializing in AG leads to the following errors:

![image](https://user-images.githubusercontent.com/59966492/161940670-131c43ea-dd1f-4097-9ea7-8919c165a123.png)

The following manual steps get everything done:
1. Table `ZAGUNITTEST` is only partially acitve > Activate it
2. Selective pull view `ZAGUNITTESTV`
3. Selective pull view `ZAGUNITTESTV_SINGLE`
4. Selective pull tobj `ZAGUNITTESTVV` and `ZAGUNITTESTV_SINGLEV`
5. Selective pull fugr `ZABAPGITTEST_TMG`

![image](https://user-images.githubusercontent.com/59966492/161941679-f76f8df4-a753-4041-a22a-3ca329850289.png)

Looking at https://github.com/abapGit/abapGit/issues/2720 it seems this used work automatically and without errors (aside from the TADIR issue which was fixed). Any idea @christianguenter2 @flaiker ?

**Comment by flaiker** [comment]
Hmm, activation sequence maybe? 3 years is quite some time ago. I can reproduce the same error:

![image](https://user-images.githubusercontent.com/5270359/161947997-7d634e46-781b-44f0-a12b-e296aa7f083f.png)

`git bisect` is a bit annoying to use because of the following error (I guess there would be some kind of value help to checkout individual commits which is not needed for this use case):

![image](https://user-images.githubusercontent.com/5270359/161950671-141355ca-f4cf-4a17-a3c7-df78df3c3d8e.png)

**Comment by mbtools** [comment]
There was a change to the order logic in https://github.com/abapGit/abapGit/pull/5198. I tried running it with older AG versions but it still failed. mmm

**Comment by mbtools** [comment]
Root cause: maintenance views are created only in `LATE` phase. Therefore, the `zagunittestv_single` is not created yet, when the activation of the `DDIC` phase happens leading to the error.

https://github.com/abapGit/abapGit/blob/d0167ff97dcf6f90ed2721c40d194a5fb34f3ea0/src/objects/zcl_abapgit_object_view.clas.abap#L147-L152

The maintenance view(s) must be created during `DDIC` phase as well. Removing the above code achieves this. However, the following test case will fail: https://github.com/abapGit-tests/VIEW_with_join 

Idea: During `DDIC`, create maintenance views without the part that causes the error. During `LATE`, update the maintenance view with complete settings.

**Comment by mbtools** [comment]
Another error related to TOBJ: "Error from OBJ_GENERATE"

This happens if the underlying DDIC object is changed while in the same abapGit session. It was reproducible, for example, in CI runs when two repos contained the same VIEW but based on different TABLs. This is caused by buffering DDIC definitions in ABAP module pool `SAPMTOBJ` (include `MTOBJT02` tables `GT_DD...`). There's no well-defined method of resetting these buffers. 

Solution: 
- For CI, test repos should not share any objects between repositories
- For other repos, restart abapGit
-
