### ISSUE TITLE
CLAS: Some test includes aren't deserialized

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5454]
Clone repo https://github.com/pokrakam/exercism-abap-local.git
For some classes test includes cannot be pulled while it worked for others.
![grafik](https://user-images.githubusercontent.com/17437789/162131778-1610cfcf-0412-4726-a1cb-070d6ec9b03b.png)
![grafik](https://user-images.githubusercontent.com/17437789/162131944-21db4beb-bd5c-4c7f-b7f3-d1563af4772b.png)

**Comment by mbtools** [comment]
There are duplicate files in the ignored folders. Should be fixed by #5427 😉  

Let us know if this works. Then we can go ahead with https://github.com/exercism/abap/pull/82

**Comment by christianguenter2** [comment]
No, still doesn't work with the mentioned fix.

**Comment by mbtools** [comment]
I see. You were using Mike's local version. I was referring to the actual Exercism repo at https://github.com/exercism/abap which with https://github.com/exercism/abap/pull/82 should work for AG.

The problem with Mike's repo is that some XMLs are missing the test class flag:
`<WITH_UNIT_TESTS>X</WITH_UNIT_TESTS>`

**Comment by christianguenter2** [comment]
Ok, thanks. That constellation is working.
![grafik](https://user-images.githubusercontent.com/17437789/162383970-ad722814-076a-41d1-aa5e-617547195046.png)

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/issues/926

**Comment by pokrakam** [comment]
Bah, that's because I created some of the classes using abaplint in VSCode and drag-n-dropped the test classes over from Exercism. I was not aware of `with_unit_tests`. Updated in the abap-local repo.
