### ISSUE TITLE
Value helps should be optional

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#5460]
In my opinion value helps should help the user to enter a correct value if he does not know it. If the user does know the value, he may enter it manually, which may be faster or prevent unnecessary lookups. Some examples:

1. Checkout commit
  I may want to checkout a specific commit I found somehow (for example when using `git bisect`). I cannot copy paste the commit hash into the input field. But I also cannot use the value help because there are "too many commits". I assume the checkout functionality would work just fine but I cannot use it.
  ![image](https://user-images.githubusercontent.com/5270359/162255968-0341583f-9a65-4a35-91f9-5400f0c2f0bc.png)

2. Checkout tag
  Same issue as with checkout commit.
  ![image](https://user-images.githubusercontent.com/5270359/162256294-2dfaa3a2-4c63-4ec9-b61b-1d1509e338b1.png)

3. Normally the value help will work fine but also may have lots of values (branch list for example). If you know the exact value it feels unnecessary to have to (manually) search for it in the popup dialog. Often `POPUP_TO_DECIDE_LIST` is used which doesn't even offer search functionality.

Preventing manual entry and enforcing value helps does help with validation. But in the examples I have in mind the error handling needs to be on a higher level anyways (since branches / tags / commits may just have disappeared on the remote after refresh).

Suggested solution: Simply enable input for these fields:

![image](https://user-images.githubusercontent.com/5270359/162258674-204593f2-06d2-4287-bdd7-d355a51207ce.png)

Also the error message for value helps that failed to load could be adjusted when called from the toolbar to redirect the user to the settings page where he may enter the value manually.

**Comment by mbtools** [comment]
💯 right. Go for it

**Comment by flaiker** [comment]
> Simply enable input for these fields

Past self was very funny there...

Maybe like this?

![image](https://user-images.githubusercontent.com/5270359/163673396-5f1924fe-ed19-4bbc-b05e-b8af206b2b4d.png)

**Comment by mbtools** [comment]
This looks better. HTML form definitions are pretty static. Maybe we introduce a show/hide feature for form elements that can be changed dynamically.

**Comment by mbtools** [comment]
sounds good
