### ISSUE TITLE
After checksums rework

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5468]
follows #5328, collecting tails and issues...
- remove `list_favorites` in repo_srv. Because this is more filtering related to UI that the backend logic
- review logic for offline repo checksums
- ... ???

**Comment by mbtools** [comment]
- `list_favorites` is a useful [API](https://docs.abapgit.org/development-guide/api/api.html#list)
- Offline checksums work well since #6638

Closing
