### ISSUE TITLE
Repo settings unsaved changes popup

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#5484]
If I open the repo settings and press back I get dialog telling me there are unsaved changes. I didn't change anything though?

![image](https://user-images.githubusercontent.com/5270359/164982572-83c0fe40-7607-40de-8478-5d87ff05020e.png)

This only occurs on the Repository tab. It seems like is_dirty returns true because of line breaks in the ignore list. Saving doesn't help.

`mo_form_data->mt_entries`:
![image](https://user-images.githubusercontent.com/5270359/164982863-15670ef1-4b24-4ee4-8b65-53ebf4284403.png)

`io_form_data->mt_entries`:
![image](https://user-images.githubusercontent.com/5270359/164982869-28f3f550-8e19-405e-a41b-90754913afe0.png)

Also this check seems to only occur when pressing the back button on the form. Pressing F3 or changing the tab to another settings page discards unsaved changes without warning.

**Comment by mbtools** [comment]
Yeah, content of textarea fields is tricky. Same with "back" logic which in some cases uses an explicit event and in others the HTML control feature (plus it does not work properly in HTML GUI). Don't spend too much time on these ;-)

**Comment by flaiker** [comment]
Oh don't worry, I am already at my monthly web dev limit refactoring the remote settings page ;)
