### ISSUE TITLE
abapDoc/shorttexts not supported?

### ISSUE THREAD

**Issue by preinboth** [abapGit/abapGit#5494]
During a branch change I noticed that all my abapDoc and shorttexts were removed. i.e. any documentation of the project is no longer available.

Is this a bug or a feature? :-)

**Comment by larshp** [comment]
are you running the latest version? can the issue be reproduced?

**Comment by preinboth** [comment]
update from abapGit I had done 2h ago.

**Comment by preinboth** [comment]
Problem is not reproducible.  Error occurred in the repository https://github.com/abapTools/abapHtmlButton.
Any idea what might have gone wrong?

**Comment by mbtools** [comment]
AbapDocs are part of the source code. So they are pushed/pulled as part of the clas.abap files. 

Maybe the code was pulled into a lower release that does not support abapdoc and then pushed back to the remote repo? But even then abapdoc should have been handled just like other comments. 🤷‍♀️

**Comment by mbtools** [comment]
With abapgit you can always checkout an older commit (in repo remote setting. No need to panic 😀

**Comment by preinboth** [comment]
The panic stemmed from the fact that in each Branch the shorttexts disappeared.
