### ISSUE TITLE
Remove "strange" tags

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5496]
AG shows a couple tags that are *not* visible on GH (and don't fit to AG versions):
- 0.113.0
- 1.25.2

![image](https://user-images.githubusercontent.com/59966492/165811700-da8019fb-8d7a-4f5f-ba81-13678091cf2a.png)

**Comment by flaiker** [comment]
Also visible on GitHub for me:

![image](https://user-images.githubusercontent.com/5270359/165932516-e3c0b79b-d8be-472f-9819-575098bb7561.png)

https://github.com/abapGit/abapGit/tags?after=v1.93.0

**Comment by mbtools** [comment]
I didn't scroll back far enough. It would help if the tags in AG would be in chronological order.
