### ISSUE TITLE
Hovering over buttons

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#5516]
I like the new commit (and push) dialog very much.
I wanted to hit `Commit`, but was unsure because nothing happened before actually hitting the button.
I expected that there is some indication that I am hovering over the button.
![image](https://user-images.githubusercontent.com/38354196/166220184-acd0d586-6d03-41e3-a98f-59a5e856a003.png)
Compare with 'Cancel' in this screenshot.
![image](https://user-images.githubusercontent.com/38354196/166220433-95d7297e-6d2e-406b-bc1f-74cdd4bd9a6d.png)

**Comment by mbtools** [comment]
Looks like an old version. Current "Commit page":

![image](https://user-images.githubusercontent.com/59966492/166225355-77d9a6ba-51bf-402a-b7d9-6850dce8333d.png)

**Comment by albertmink** [comment]
Haha I thought I had the new one. Turns out it is the old one 😱
