### ISSUE TITLE
OTGR: Syntax error NW 752 SP04

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5525]
Formal parameter "IM_EXPLICIT_ELEMENTS_ONLY" does not exist.
![grafik](https://user-images.githubusercontent.com/17437789/166642845-6ba07059-d854-4a53-85f8-66a3728df615.png)

**Comment by blahbap** [comment]
I too get this error on 7.50 SP 21

**Comment by larshp** [comment]
temporary workaround = just comment the code if you are not using the OTGR object type

**Comment by blahbap** [comment]
Thanks Lars, will do

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/pull/5518
