### ISSUE TITLE
Pragma and Pseudo Comments

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5537]
Currently abapGit contains both, pragmas and pseudo comments

1. Should we remove or replace all pseudo comments?

Example:

```abap
EXCEPTIONS
  OTHERS  = 1 ##FM_SUBRC_OK.  "#EC CI_SUBRC
```

2. Should we remove all pramas and pseudo comments that are not supported by abaplint?

**Comment by mbtools** [comment]
I would say, just use pragmas but keep all that take care of syntax warnings (as of 7.5?)

**Comment by larshp** [comment]
yea, well, only nice to have

need something that can be enforced automatically
