### ISSUE TITLE
Activation of standalone report fails

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#5556]
I cannot activate the standalone report, see
![image](https://user-images.githubusercontent.com/38354196/168597629-0bf552d0-b658-4238-82c7-99e0a94ef29e.png)

Git blame says, the type has been introduced in https://github.com/abapGit/abapGit/pull/5495

**Comment by albertmink** [comment]
cannot reproduced. I had breakpoints somewhere deep in the activation process that disturbed the activation.

**Comment by Qiont** [comment]
https://github.com/mbtools
