### ISSUE TITLE
Syntax error in latest ZABAPGIT_STANDALONE version

### ISSUE THREAD

**Issue by GeorgReichert1** [abapGit/abapGit#5565]
Hello,
the latest version of the ZABAPGIT_STANDALONE report from https://raw.githubusercontent.com/abapGit/build/main/zabapgit.abap produces a syntax error and can therefore not be activated. The shown error is "Type "RSTLOGO" is unknown.".

Best regards
Georg

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/issues/5556

**Comment by larshp** [comment]
what ABAP/SAP version/kind of system are you activating it on?

**Comment by larshp** [comment]
temporary workaround is commenting the code in the method, its for jumping to BW objects, not core functionality

**Comment by GeorgReichert1** [comment]
Im trying to activate the report in the UIA system, client 000. Do you need further information?

**Comment by mbtools** [comment]
@GeorgReichert1 could you please list the content of table `cvers` from your system?

**Comment by mbtools** [comment]
@GeorgReichert1 try the latest version

(still curious about your `cvers` data)

**Comment by GeorgReichert1** [comment]
Hi there,
with the latest update, the report can now be activated. Thanks a lot!
The content of the cvers table is:
VALUE #( ( COMPONENT ='AOFTOOLS' RELEASE ='500_700' EXTRELEASE ='0006' COMP_TYPE ='C'  )
 ( COMPONENT ='HOME' RELEASE ='DEV' EXTRELEASE ='0000000000' COMP_TYPE ='M'  )
 ( COMPONENT ='LOCAL' RELEASE ='DEV' EXTRELEASE ='0000000000' COMP_TYPE ='L'  )
 ( COMPONENT ='SAP_BASIS' RELEASE ='757' EXTRELEASE ='0' COMP_TYPE ='S'  )
 ( COMPONENT ='SAP_GWFND' RELEASE ='757' EXTRELEASE ='0000000000' COMP_TYPE ='S'  )
 ( COMPONENT ='SAP_UI' RELEASE ='757' EXTRELEASE ='0000000000' COMP_TYPE ='S'  )
 ( COMPONENT ='SW_COMP_FOR_TEST_42' RELEASE ='753' EXTRELEASE ='0' COMP_TYPE ='S'  )
 )
 Best regards
Georg

**Comment by mbtools** [comment]
No SAP_ABA either. Interesting. Thanks!
