### ISSUE TITLE
Short Dump in Version 1.114.0 & 1.115.0

### ISSUE THREAD

**Issue by NeumannJoerg** [abapGit/abapGit#5570]
As I could not find any existing bug report for this issue, I created my own - hope I did not miss an existing one.
If you have questions, just ask - I'll try to provide any detail you might need.

# Symptom
Short dump when opening a repository by clicking on a repository name on the start screen.

abapGit displays the following messages via the status indicator:
- Fetch remote files
- Serialize $_OBJECT_NAME, 1 threads

At some point before displaying the contents of the repository, abapGit just dumps.
![abapGit_runtime_error](https://user-images.githubusercontent.com/86975244/169101066-31f394ff-191d-4500-a7cd-ab18d9378768.png)

# Affected version(s)
The issue occurred with version 1.114.0 (Standalone AND developer version).

I updated the standalone version by uploading the .abap-file provided on https://abapgit.org.
This did not change anything, so the latest version 1.115.0 seems to be affected as well.

# Source Code Position
The dump occurs in line 40.689 (Method ZCL_ABAPGIT_GUI_PAGE_REPO_VIEW->apply_order_by):
```
SORT lt_code_items STABLE BY (lt_sort).
```

The problem is, that lt_sort[1] looks like this:
```
VALUE #( name       = 'TRANSPORT'
         descending = abap_false
         astext     = abap_true )
```

While the line_type looks like this:
```
  TYPES:
    BEGIN OF ty_repo_item,
      obj_type   TYPE tadir-object,
      obj_name   TYPE tadir-obj_name,
      inactive   TYPE abap_bool,
      sortkey    TYPE i,
      path       TYPE string,
      is_dir     TYPE abap_bool,
      changes    TYPE i,
      lstate     TYPE ty_item_state,
      rstate     TYPE ty_item_state,
      files      TYPE ty_repo_file_tt,
      changed_by TYPE syuname,
      packmove   TYPE abap_bool,
    END OF ty_repo_item .
```

Please note, that there is no column named ```TRANSPORT```.

# Workaround
I was able to fix the short dump using the database utility.
I edited the file having ``type = 'USER'`` and ``key = $_MY_USER_NAME`` and replaced the line:
```
   <ORDER_BY>TRANSPORT</ORDER_BY>
```
with
```
   <ORDER_BY/>
```
This fixed the issue and I was able to work again.

# How to reproduce
Open any random repository, that contains objects, that have been transported in the past.
You should see a column "Transport".

Click on the column header.
![abapGit_the_fatal_click](https://user-images.githubusercontent.com/86975244/169100734-8141bbed-0421-4380-9acd-8efbab9baef4.png)

You will see the status indicator again and soon after that, abapGit will dump.
![abapGit_runtime_error](https://user-images.githubusercontent.com/86975244/169101066-31f394ff-191d-4500-a7cd-ab18d9378768.png)

My user profile is immediately changed by that click (```TRANSPORT``` will be set as the new value for ```ORDER_BY```).
From now on abapGit will dump whenever I try to open a repository.
To make abapGit usable again, the workaround described above has to be applied.

**Comment by mbtools** [comment]
@NeumannJoerg try the latest version

**Comment by NeumannJoerg** [comment]
@mbtools Wow... That was quick :-)
Thanks a lot!

I just updated our developer version using the standalone version.
After that I reproduced the short dump and broke my user profile on purpose.

Result:
- the developer version (updated) works
- the standalone version (untouched) dumps (as expected)

=> Test successful

The version number of our developer version is still 1.115.0.
Is that on purpose?

**Comment by mbtools** [comment]
there's no schedule for creating a new version. it's a bit of works to compile the changelog but we will try to update it more frequently.

**Comment by NeumannJoerg** [comment]
Thanks for the info.

Just wanted to make sure, that this was not an accident, since the version number seems to be a constant in the code.
So far I have no clue, if the number is increased manually or by some highly sophisticated tools.

I now updated the standalone version as well and now both versions are working.
