### ISSUE TITLE
Dump: Serialization Timeout

### ISSUE THREAD

**Issue by lucasborin** [abapGit/abapGit#5573]
Once I click in Stage:

![image](https://user-images.githubusercontent.com/5233413/169302895-cac7bef7-2728-449a-9e07-d06889fecd1a.png)

![image](https://user-images.githubusercontent.com/5233413/169302995-12a6302e-af5b-40a8-95fc-52e6c1d66fbb.png)

![image](https://user-images.githubusercontent.com/5233413/169303061-543376dc-cc94-44c0-8236-3e215654eed8.png)

abapgit - 1.115.0

parallel processing turned off 

Is there any way to skip all the ECATT objects?

**Comment by larshp** [comment]
try with a selective pull, deselect the objects to skip

what is the size of the largest XML file? the timeout should reset at commit, and deserialize does commits for each object

![image](https://user-images.githubusercontent.com/5888506/169305174-27c6d6eb-de76-4a67-b90d-4923c4365504.png)

**Comment by lucasborin** [comment]
Hey Lars, we are trying to push on the stage section. The serialized file that is causing a dump is not in the remote repository yet. Is there any way to check the XML file size in this case?

**Comment by lucasborin** [comment]
I found a way, and the .xml file has 9.63 MB

**Comment by larshp** [comment]
quickly looking through https://github.com/abapGit/performance-test/blob/main/src/zabapgit_performance_test.prog.abap it can serialize a single object, try choosing the object, and run it via `SE30`

**Comment by lucasborin** [comment]
![image](https://user-images.githubusercontent.com/5233413/169387103-9a64ba69-17dd-4130-9319-87c8c6615fd1.png)

**Comment by larshp** [comment]
what is the dialog timeout on the server? 10 minutes?

two suggestions
1: check the code and trace to see if there are any easy optimizations
2: try adding COMMIT WORK before or after each object is serialized, this should reset the timeout

![image](https://user-images.githubusercontent.com/5888506/169455183-a5f95755-c6aa-4df5-ae8d-2ddc5c093317.png)

**Comment by mbtools** [comment]
FYI, a quick way to skip all objects of a given type it to remove the type at the end of `zcl_abapgit_objects=>supported_list( )`

**Comment by lucasborin** [comment]
Would it be possible to exclude all specific types using the ´abapgit.xml´? 
I tried `*.ectd*`, `/*.ectd*`, `/**/*.ectd*`, but no success.

Ps: the object is under a sub-package.

**Comment by larshp** [comment]
you can simulate a different TADIR, https://docs.abapgit.org/ref-exits.html#change_tadir

**Comment by mbtools** [comment]
the ignore logic works with abap `CP` 
https://github.com/abapGit/abapGit/blob/f18a8ee82b693513b9c0cb7e24d5f5cc6676acd2/src/repo/zcl_abapgit_dot_abapgit.clas.abap#L242-L248

However, we serialize *all* TADIR objects and use `is_ignore` only during deserialize. This is because the file names are only available *after* serializing an object. So this won't help in your case.

**Comment by mbtools** [comment]
Do you need more help with this, @lucasborin? Close?

**Comment by mbtools** [comment]
I enhanced the ignore feature. Try with https://github.com/abapGit/abapGit/pull/5648

**Comment by lucasborin** [comment]
Way better now. Solved the bug, and also improved the performance!

**Comment by mbtools** [comment]
merged
