### ISSUE TITLE
CLAS: Selective Pull for deleted interface methods doesn't work

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#5578]
I added a method to zif_abapgit_gui_event_handler and want to reset to the state of upstream/main. This doesn't work. While the method gets removed from the interface the method implementations are not removed from the implementing classes on selective pull.

I think this was discussed previously but I am not sure we have an open issue for this case (I couldn't find it).

Overview:
![image](https://user-images.githubusercontent.com/5270359/169537186-57d1dbfd-d714-49c1-b26c-bb2aba7fbe58.png)

Diffs:
![image](https://user-images.githubusercontent.com/5270359/169537225-c120f47c-8b64-4d52-bd2a-6d60645e3fbb.png)

Selective Pull:
![image](https://user-images.githubusercontent.com/5270359/169537289-91df136b-b43a-4448-9e7f-370a4f6e2373.png)

Note the interface itself already doesn't have the method in question anymore and has no diff.

In SE24 I get this warning:

![image](https://user-images.githubusercontent.com/5270359/169537763-1bddf45d-793c-451c-aeac-b40f8a2bd022.png)

The method in question isn't listed in the form based editor.

In the source code based editor it's there:

![image](https://user-images.githubusercontent.com/5270359/169537905-07a217aa-2824-4da4-8590-2b1bae1f900d.png)

Regenerate sections didn't help.

Clean up method includes did help and showed this popup:

![image](https://user-images.githubusercontent.com/5270359/169538069-e1abcb93-a150-4ad8-b7cd-893f32fadcfe.png)

The buttons are in the menu in SE24:

![image](https://user-images.githubusercontent.com/5270359/169539246-01dd43ac-6e87-469f-a0ba-2e9c1d91244d.png)

**Comment by flaiker** [comment]
Function module `SEO_CLASS_REPAIR_CLASSPOOL` does the deletion of non existing interface method includes in implementing classes when Clean Up -> Method includes is pressed.

**Comment by flaiker** [comment]
Which used to be called specifically for an issue with the abapGit exception class (removed in a1cc7f8668ffe1985a451ebc682cbaf641a7d445).

https://github.com/abapGit/abapGit/blob/bb0591f12eb9df7257c6bb454910927ca13791e9/src/objects/zcl_abapgit_object_clas.clas.abap#L591-L606

**Comment by mbtools** [comment]
I don't see why adding "repair" in abapGit is necessary. 

In the system where the interface was changed, the classes using the interface need to be changed too. either manually or using the clean-up (since SAP doesn't do it automatically). then push all changes - interface and classes - to the repo. 

The target system then needs to pull interface and class changes together, of course.

**Comment by flaiker** [comment]
> The target system then needs to pull interface and class changes together, of course.

That won't work though? My example above should be comparable to if we were to remove a method in let's say `zif_abapgit_object` and also manually remove it in all object handler classes, commit, merge, now the changes are in main and they are consistent. If someone pulls these changes to update abapGit only the change in the interface definition will be pulled, not the method removals in the implementing classes causing tons of diffs that you cannot get rid of (without pressing repair in every class or using uninstall and reinstalling completely from scratch). Or am I missing something?

**Comment by flaiker** [comment]
Interesting, now I also got this popup after changing to edit mode in the class that implements the interface with the deleted method.

![image](https://user-images.githubusercontent.com/5270359/170027919-4741535d-43b5-412d-a9ef-ce3ea03a29ad.png)

![image](https://user-images.githubusercontent.com/5270359/170027940-16862a1d-963d-4bda-a817-10d468502c1d.png)

![image](https://user-images.githubusercontent.com/5270359/170027980-2eda0ecc-2ac9-484a-b6fd-4bcd53529d1b.png)

Anyways, test case:

- Clone https://github.com/flaiker/test-interface-method-deletion branch main, pull
- Switch to branch delete-method, advanced, selective pull, mark all

The interface is adjusted and doesn't show diffs, the class does not get updated to the remote version, at least not regarding the deleted method.

![image](https://user-images.githubusercontent.com/5270359/170028639-3af06168-27ee-4753-8c28-a595dc022041.png)

![image](https://user-images.githubusercontent.com/5270359/170028665-21a4c3cf-c0ab-4b18-a56c-50d75b532b5c.png)

**Comment by mbtools** [comment]
thx for the test case. it's indeed a bug. we don't want to call "repair" for all classes "just in case". let's see if we can make it conditional
