### ISSUE TITLE
Table content serialization: dump ITAB_DUPLICATE_KEY

### ISSUE THREAD

**Issue by NicolasBusson** [abapGit/abapGit#5582]
Dear contributors,
I'm facing a dump when I try to create a new online repository with /data/ folder containing data from some customizing tables:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/82606868/169759961-5aaf0f25-3551-4ca0-a0db-0587e8199237.png">
I opened pull request number #5577 last week to provide a fix, but it seems that the issue lies in the ajson project. So I opened another pull request in this project too : https://github.com/sbcgua/ajson/pull/103. However, it looks like this bug had already been fixed (that's why both pull requests are now closed).
So how can we know if corrections made to ajson have been copied to abapgit? Am I allowed to add test data to https://github.com/abapGit-tests/data_custom_table to make it easier for you to reproduce this dump?
Best regards,
Nick.

**Comment by larshp** [comment]
I think there are some issues with the mirroring, https://github.com/abapGit/abapGit/actions/workflows/ajson_mirror.yaml

**Comment by larshp** [comment]
#5584

**Comment by larshp** [comment]
@NicolasBusson try again, #5584 merged

**Comment by NicolasBusson** [comment]
Hi @larshp ,
Problem fixed! thank you very much. I'm closing this issue then.
Regards
