### ISSUE TITLE
Git Protocol Error for large package

### ISSUE THREAD

**Issue by nbehere** [abapGit/abapGit#5590]
We have referred to the issue below and tried all the steps mentioned in here for resolving our error.  (For reference)
https://github.com/abapGit/abapGit/issues/4805
We have the latest ZABAPGIT code installed.  
SSL Setup test is also working fine. 
The package we are trying to synch up with Github repository has more than 26K objects. 
The Serialization works fine. (takes a while but ends without errors) Then Staging also works fine. 
The last step of Commit All is where we get the Git Protocol error.
We have tried selecting just a few objects instead of all, then we get the Out of Memory error. 

Debugging the code we found that 
lv_xstring has values but lv_string is blank after the conversion method (xstring_to_string_utf8)

•	In the method RECEIVE_PACK, the below line of code is clearing the value of the lv_string. The method xstring_to_string_utf8 that calls from RECEIVE_PACK is having some issue in converting the data to UTF8. 
lv_string = zcl_abapgit_convert=>xstring_to_string_utf8( lv_xstring ). 
•	As lv_string value is BLANK then it set the “lv_error” as 'Unexpected empty reply' in method check_report_status. Next, lv_string is not INITIAL so throws an error “GIT PROTOCOL ERROR” during committing the code from ABAPGIT.
Can you please suggest a resolution for this issue

thanks

**Comment by mbtools** [comment]
@larshp Why no handler here? Shouldn't the string <-> xstring methods raising an exception?

**Comment by larshp** [comment]
I dont expect something like this to happen, it should be able to convert the string to xstring not failing on size

I guess something else is wrong...

**Comment by mbtools** [comment]
the size problem would show as a dump. that's not it.

`0xF8-0xFF` are not valid in utf8. it's probably something like that leading to one of the codepage exceptions. The user should see "Codepage conversion error" instead of the "Unexpected empty reply". By reducing the number of objects, you could then find out which one causes the issue.

**Comment by mbtools** [comment]
if you get the problem again, please use the latest version. it will give a better error message related to the codepage conversion.
