### ISSUE TITLE
abapGit picks up "translations" to 늑 / 1Q language code for Translation Object Detective

### ISSUE THREAD

**Issue by gregorwolf** [abapGit/abapGit#5595]
Hello abapGit Team,

today I came around a quite interresting issue. @pksingh78 currently tries to fix the SCI issues in the abap2xlsx project (https://github.com/abap2xlsx/abap2xlsx/issues/1012 and https://github.com/abap2xlsx/abap2xlsx/issues/1013). As the ABAP Developer edition isn't available he does that in the customers sandbox system. Each time we continue working we see differences like this in abapGit:

![Screenshot 2022-05-27 at 08 27 02](https://user-images.githubusercontent.com/2639535/170643293-9bf2e245-6a0a-4b6f-9e7b-31dec26c006e.png)

To track down the issue I've looked at the issue with the translations using the language key 늑 I looked at the issues with object type MSAG:

![Screenshot 2022-05-27 at 08 28 16](https://user-images.githubusercontent.com/2639535/170643453-9e02c06b-fcff-417f-ba30-5aa2d27b0bfc.png)

The translations for this object are stored in table T100:

![Screenshot 2022-05-27 at 08 35 39](https://user-images.githubusercontent.com/2639535/170644479-5c0d07fb-99b2-4ff0-bdfd-e69261294c66.png)

So I found that 늑 has the two letter code 1Q and the description "Technical Code 1". A Google search revealed that in this system the:

[Translation Object Detective](https://help.sap.com/docs/ABAP_PLATFORM_NEW/ceb25152cb0d4adba664cebea2bf4670/88a3d3cbccf64601975acabaccdfde45.html?locale=en-US)

is active. By running the report RS_LXE_FILL_TECH_LANG the language 1Q is filled with a "translation" that contains the technical object name. So you can easily identify which SE63 object you need to translate when logging on with language 1Q.

But I think this translation should not be included in the abapGit language export. What do you think?

Best Regards
Gregor

**Comment by gregorwolf** [comment]
In our concrete case for abap2xlsx the language serializers of the following object types would need to be adjusted:

- [ ] MSAG
- [ ] CLAS
- [ ] PROG
- [ ] DTEL
- [ ] DOMA
- [ ] TABL

**Comment by gregorwolf** [comment]
I would suggest to define a constant c_translation_detective in class ZCL_ABAPGIT_OBJECTS_SUPER that is then added to the selection e.g. for the MSAG object type:

![Screenshot 2022-05-27 at 09 04 27](https://user-images.githubusercontent.com/2639535/170648743-b1caf27a-42c9-4747-b23c-afcae6799be0.png)

**Comment by mbtools** [comment]
Always something new with abap... :-)

`ZCL_ABAPGIT_LXE_TEXTS=>GET_INSTALLED_LANGUAGES` uses function `SYSTEM_INSTALLED_LANGUAGES`. Does that call include the `1Q` language?

**Comment by gregorwolf** [comment]
In my ABAP Developer Edition I've activated the 1Q language as described in the documentation I've linked above. That is the return of `SYSTEM_INSTALLED_LANGUAGES`:

![Screenshot 2022-05-29 at 11 02 50](https://user-images.githubusercontent.com/2639535/170860456-3dd5032a-8b4b-4983-a11c-ce4696081de8.png)

**Comment by flaiker** [comment]
I'd guess we should also filter in these out in `ZCL_ABAPGIT_LXE_TEXTS=>GET_INSTALLED_LANGUAGES` then.

I thought about how we can be somewhat sure we adjusted every select. You said you were able to install 1Q in the developer edition. So if we run all abapGit-tests repos via CI in a system that has 1Q installed everything that's still to be adjusted should show up as a diff, right?

**Comment by mbtools** [comment]
@flaiker yes, assuming that the object class supports translations and that we have a CI test case for it (with at least one description for each possible text element (some classes have several) and that the tests cover short and long texts. Overall, that's currently a lower coverage ratio.

certainly yes to adjusting `ZCL_ABAPGIT_LXE_TEXTS`.

on a side note, I find the `E,EQ,1Q + E,EQ,2Q` in the returned range a bit difficult to digest when you read the select/delete statements which might have another condition for language on top of this (like `<> main_language`). Using a single inclusive range of languages to select would be easier to understand.

**Comment by flaiker** [comment]
I opened #5601. Feel free to suggest a different approach to the select conditions. I personally like the current way of letting the runtime merge them when executing the SELECT statement instead of doing it by hand which adds lines and room for error. The range returned is inclusive with exclude conditions so it doesn't filter everything out when it's empty, which it will be in most systems (this admittedly is a bit confusing at first sight).

**Comment by mbtools** [comment]
Close? or do you have other object types that need this fix?

**Comment by AndreaBorgia-Abo** [comment]
> As the ABAP Developer edition isn't available he does that in the customers sandbox system.

The docker image is indeed not available but [7.52SP04](https://blogs.sap.com/2019/10/01/as-abap-7.52-sp04-developer-edition-concise-installation-guide/) is! Granted, not as modern but not too shabby either.

**Comment by mbtools** [comment]
Closed by #5601
