### ISSUE TITLE
CMHC: Cloud Management Health Check

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#5602]
Just found this, Z-namespace seems to be allowed including temp packages. Might not be useful in onpremise, not sure.

![image](https://user-images.githubusercontent.com/5270359/170963399-1c8967e1-cadc-4a91-b08d-c1fde44b168c.png)

https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/b31aa03640b940d5981ce2af1cd0a019.html?locale=en-US doesn't list it either.

**Comment by mbtools** [comment]
how do you get to this maint screen?

**Comment by flaiker** [comment]
I navigated to package SZN and double clicked on the entry :shrug: For creation I right clicked on the folder and selected new. I haven't looked up the tcodes or checked if any exist.

**Comment by flaiker** [comment]
Transaction code is `SCLMS_HC_LIST`

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.
