### ISSUE TITLE
Dump when returning from deletion per database utility

### ISSUE THREAD

**Issue by JSB-Vienna** [abapGit/abapGit#5612]
Hi,
I've been deleting a repository entry of an deleted SAP package via the database utility. This works properly, but when clicking the back button to return to the repository list I've got a dump. The entry is deleted and everything else seems to be ok.

I've used the latest version of the standalone report. Find attached the dump, a screen shot of the call stack in your exception class.

Best regards, Jens

![image](https://user-images.githubusercontent.com/30773503/171918315-b40bfdcf-6b01-4bc8-ab99-d14121ac4f37.png)
[OBJECTS_OBJREF_NOT_ASSIGNED_NO_20220603_192209.zip](https://github.com/abapGit/abapGit/files/8834594/OBJECTS_OBJREF_NOT_ASSIGNED_NO_20220603_192209.zip)

**Comment by mbtools** [comment]
Hi Jens,

we can't possibly harden abapGit against manual changes of the persistence (i.e. changes or deletions using DB utility). Why did you have to use the DB utility? If you tells us more about that situation we might be able to fix or avoid it.

Marc

**Comment by mbtools** [comment]
no response. closing

**Comment by JSB-Vienna** [comment]
Hello Marc,
sorry for the delayed reaction. Maybe the answer will help you anyway.
I used the DB utility to delete the entry from the list of projects, guessing it was the purpose of it. Since the package wasn't available anymore, it seemed the right way.
Should I create a new issue, including a linkage to this one?
Jens
