### ISSUE TITLE
Exception when package is in repo but not a subpackage in system

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5623]
@Zeatynis "I have a situation when I decided I want to unjoin one subpackage of a central repository package. I don't want to serialize it anymore. So I changed this subpackage assignment and now I am stuck. I cannot stage to repo.

I have this error:
Package ZREPO_XML_WS already exists but is not a subpackage of ZREPO. Check your package and folder logic or assign ZREPO_XML_WS to package hierarchy of ZREPO to match the...

But when I jumped for this package to clear ls_item-devclass abpagit reacted correctly. It recognized every object from this package as removed and when I stage I have an option to remove these objects from my repo.
![obraz](https://user-images.githubusercontent.com/9119187/172227584-2cba210b-4a3f-4858-ab65-058d8abc3383.png)

_Originally posted by @Zeatynis in https://github.com/abapGit/abapGit/issues/4904#issuecomment-1147780623_

**Comment by Zeatynis** [comment]
> yea
> 
> the workaround is removing the folder in the remote manually, using classic git client

Yea, I know the workaround 😄  But this time I am almost certain that such situation should be handled well by abapgit 😉

**Comment by mbtools** [comment]
Can you help testing #5628?

**Comment by Zeatynis** [comment]
@mbtools, just by pulling newest abapgit and checking on my/test repo?

**Comment by mbtools** [comment]
it's not merge yet. you have to use the developer version, then go to "settings > remote" for the abapgit repo and select the pull request 5628. then you can pull the fix to your system and test it with your own package/subpackage repo.

**Comment by Zeatynis** [comment]
I apologize for my Internet Explorer-worthy reflexes. I confirm, that this solution works. I only am thinking if it is possible to classify these objects (within package and the package itself) like other deleted objects - to have a possiblity to stage with "remove" option. Without a need to do it somewhere else.
