### ISSUE TITLE
Question: Can an auth-check for abapGit-execution be implemented?

### ISSUE THREAD

**Issue by BaerbelW** [abapGit/abapGit#5629]
Hi All!

I hope that this is the correct place to ask a question which might turn into a "feature request". If not, please let me know where to ask instead. Thanks!

I'm currently looking into what all needs to be set in place to potentially start utilizing abapGit where I work. One big issue is that only specific users should be able to execute the program in designated systems. Because of this, I've been looking into how authorization-checks can be implement in abapGit and found the relevant information in the documention:
[https://docs.abapgit.org/ref-authorizations.html](https://docs.abapgit.org/ref-authorizations.html)

I followed the instructions and placed a simple check into the include & class implementation and then set a breakpoint to see when it would get triggered. This seems to be fairly late in the process and not right at the beginning when the program gets started, which is where we would like to have it. Our preferred option is to basically prevent execution by anybody who doesn't have the needed auths.

Apart from the time of execution of the auth-checks, none of the pre-defined options for c_authorization really fits our needs (note that "create_repo" shows up in the code but isn't mentioned yet in the above documentation):
```
INTERFACE zif_abapgit_auth.

  TYPES: ty_authorization TYPE string.

  CONSTANTS: BEGIN OF c_authorization,
               uninstall             TYPE ty_authorization VALUE 'UNINSTALL',
               create_repo           TYPE ty_authorization VALUE 'CREATE_REPO',
               transport_to_branch   TYPE ty_authorization VALUE 'TRANSPORT_TO_BRANCH',
               update_local_checksum TYPE ty_authorization VALUE 'UPDATE_LOCAL_CHECKSUM',
             END OF c_authorization.
```
Is there a means to trigger an auth-check right at the beginning of the abapGit program and display a message on the screen if a user doesn't have the required authorizations?

Thanks much and cheers
Bärbel

**Comment by flaiker** [comment]
Hi Bärbel,

> Our preferred option is to basically prevent execution by anybody who doesn't have the needed auths.

can't you just authorize the transaction / program "normally" by restricting access to `S_TCODE` for abapGit and `S_PROGNAM` / `S_PROGRAM` for `SA38`? Or are you looking for a solution where restrictions should apply even though the user has `SAP_ALL`?

Of course if these users are developers on development systems then preventing workarounds will be tough to enforce either way.

**Comment by BaerbelW** [comment]
Hi Fabian,

thanks for your quick reply! I'll have to check with our basis team if S_PROGNAM would be an acceptable option from their perspective.

Yes, developers can obviously circumvent basically all auth-checks in a dev-system but that would then be a clear violation of our written guidelines they agreed to adhere to before getting their developer key.

SAP_ALL is not really an issue as far as I'm aware.

**Comment by larshp** [comment]
we can always just add STARTUP to the list, and add the corresponding call to the user exit on startup

more is more, there will always be various requirements for authorizations

```abap
  CONSTANTS: BEGIN OF c_authorization,
startup             TYPE ty_authorization VALUE 'STARTUP',
               uninstall             TYPE ty_authorization VALUE 'UNINSTALL',
               create_repo           TYPE ty_authorization VALUE 'CREATE_REPO',
               transport_to_branch   TYPE ty_authorization VALUE 'TRANSPORT_TO_BRANCH',
               update_local_checksum TYPE ty_authorization VALUE 'UPDATE_LOCAL_CHECKSUM',
             END OF c_authorization.
```

**Comment by larshp** [comment]
there is also https://docs.abapgit.org/ref-exits.html#wall_message_list and https://docs.abapgit.org/ref-exits.html#wall_message_list which can be used to display warning/information/rule messages on how/if/when to use abapGit, but its information only

**Comment by BaerbelW** [comment]
Thanks, Lars!

I like the idea with 'STARTUP' as that sounds like a good fit for our "use case".

**Comment by larshp** [comment]
@BaerbelW can you help testing https://github.com/abapGit/abapGit/pull/5630, and check if it will work for you?

**Comment by BaerbelW** [comment]
@larshp - Sure, if you let me know how and where to test (I'm new to this!), I'll do that on Friday. At a guess, I'll have to copy abapGit again to overwrite the current code I have in our system?

**Comment by larshp** [comment]
just switch to the branch and click pull, you can switch back to `main` after testing

![switch](https://user-images.githubusercontent.com/5888506/173862660-3d430735-d31b-402d-b061-8453cfe10ded.gif)

**Comment by BaerbelW** [comment]
The „just“ may not be quite as straightforward as I don‘t have a clue about dealing with Github (apart from asking questions). I also don‘t have a local dev-environment. I can only run and test programs in our actual ERP sandbox system. Sorry about that.

**Comment by larshp** [comment]
the corresponding zip file can be downloaded from https://github.com/abapGit/abapGit/archive/refs/heads/hvam/startup.zip

and then https://docs.abapgit.org/guide-offline-install.html and/or https://docs.abapgit.org/guide-import-zip.html

**Comment by BaerbelW** [comment]
Thanks, Lars! I'll try on Friday when I'm back at work with access to the sandbox system and let you know.

**Comment by BaerbelW** [comment]
@larshp 
Hi Lars,
please excuse my newbie questions but how does the zip-file for the changes go along with the standalone abapGit program I created in SE38 via copy & paste as one big program called ZABAPGIT_REPORT? I simply put it in $tmp so am already at a loss when I get asked to fill out the fields after going to "New offline" as indicated in the documentation:
![grafik](https://user-images.githubusercontent.com/18588108/174237242-b5bad3fc-eeed-4688-88b3-b428f932e32a.png)

**Comment by christianguenter2** [comment]
You're installing the abapGit developer version right now. Meaning all global objects, especially classes, are created. 
Repo name could be anything, e.g. abapGit would make sense. Package is then either $abapgit or zabapgit depending on if you intent to transport or not. Most likely the former. After importing you can use transaction code ZABAPGIT to start abapGit dev version.

**Comment by BaerbelW** [comment]
Hi Christian,

hmmm, I actually hadn't intended to install the abapGit developer version in our SAP-systems. Is that a prerequisite? We are currently only looking into if and how abapGit could be used. If the developer version is needed I'd have to get internal approval before creating all these global objects.

Cheers
Bärbel

**Comment by christianguenter2** [comment]
Good question. AFAIK it is a prerequisite. 
The standalone report is created in the build process of the main branch (which is executed via GitHub actions after a pull request is merged into main branch). But there's also a test build which is executed for every pull request which also creates the standalone report. But I don't know if the results of the test build are accessible somewhere.
https://github.com/abapGit/abapGit/runs/6901230479?check_suite_focus=true
![grafik](https://user-images.githubusercontent.com/17437789/174257364-11329d17-6151-46c9-b260-e54aca9c6eb0.png)

Note there's also the possibility to create the standalone report manually by doing the steps of the build with the branch of the pull request.

**Comment by BaerbelW** [comment]
Thanks for the clarification, Christian!

Trying to understand this Github-lingo is like learning a new language as I'm not actively using Github and have only "passively" heard about activities like pull requests or merges - but mostly in other contexts. 

Given that I'm currently just dabbling with the standalone abapGit program in a sandbox system, the easiest for me would be to know what has changed in the code where. I'd then just manually add the bits and pieces where needed. So, for me change insructions like what is included in OSS-Notes to highlight the related code-changes would be fine. Once a new official version of abapGit becomes available I can overwrite the current code completely.

**Comment by g-back** [comment]
The generated standalone report could be downloaded here:
https://github.com/abapGit/abapGit/actions/runs/2502734327

In the bottom section there's an "Artifacts" section.

**Comment by larshp** [comment]
merged, https://raw.githubusercontent.com/abapGit/build/main/zabapgit.abap will be updated in a few minutes

**Comment by christianguenter2** [comment]
> The generated standalone report could be downloaded here: https://github.com/abapGit/abapGit/actions/runs/2502734327
> 
> In the bottom section there's an "Artifacts" section.

@g-back Ah, thanks. Good to know. Must have had tomatoes on my eyes.

**Comment by BaerbelW** [comment]
Thanks All - both for humoring me and updating zabapgit so quickly!

It works as expected and displays an error message directly when trying to execute the program and not fullfilling the check criteria in the exit:
![grafik](https://user-images.githubusercontent.com/18588108/174279753-175f9233-d172-4c7e-9282-cb0cfe1bba31.png)

Cheers and have a nice - and not too hot - weekend!
Bärbel

**Comment by larshp** [comment]
@BaerbelW cool, then the issue can be closed?
