### ISSUE TITLE
How to edit the attributes inside the internal table?

### ISSUE THREAD

**Issue by ngsuityan** [abapGit/abapGit#5636]
Hi, I am new to SAP ABAP. How to edit the internal table attributes? want to add one more row but not sure how to do. Any suggestion and teaching is appreciated..

![image](https://user-images.githubusercontent.com/83693028/174773472-bd6e31de-c087-4fbf-bbbe-daba820b2ef8.png)

**Comment by larshp** [comment]
Hi,
It looks like the question is related to general ABAP code, this repository is for abapGit

Suggest opening a question on https://answers.sap.com

closing
