### ISSUE TITLE
W3MI: Sorting order changed in S/4HANA

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#5644]
The highlighted internal table has different sorting order in S/4HANA and results in diffs. It needs to be sorted immediately after function module call

![image](https://user-images.githubusercontent.com/29766214/175187163-c2353b73-3d65-4041-9884-70b85faa5f90.png)

Left Side: S/4HANA 2020
Right Side:  SAP_ABA	750
![image](https://user-images.githubusercontent.com/29766214/175187227-25c2ffb3-0e6c-4e34-8510-e09d813e0864.png)

**Comment by christianguenter2** [comment]
@yellappam
Can you update one of these test cases?
https://github.com/abapGit-tests/W3MI.git
https://github.com/abapGit-tests/W3MI_names.git

**Comment by yellappam** [comment]
@christianguenter2 Do you mean to update the repo with my example?

**Comment by christianguenter2** [comment]
Yes. Adding your example somewhere. I tried to reproduce the issue but wasn't able to do that.
