### ISSUE TITLE
Object Type DDLX causes commit by 'UNKNOWN' author

### ISSUE THREAD

**Issue by Mcreve** [abapGit/abapGit#5646]
When committing to a repository using CDS and RAP objects, the framework seems to not allocate this file type to the user that changed it.

![image](https://user-images.githubusercontent.com/10981432/175254239-cb1e38ff-106f-455d-b13c-6fee1b9e5ad4.png)

**Comment by mbtools** [comment]
`changed_by` is not implemented to `DDLX`

https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_ddlx.clas.abap#L110

User-specific data is cleared properly during serialization but saving the correct user during deserialization is left to SAP code.

**Comment by larshp** [comment]
pull requests welcome to fix the method
