### ISSUE TITLE
Replace `client specified` with `using client`

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5650]
`client specified` is [obsolete](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapselect_client_obsolete.htm) and [not supported in ABAP for Cloud](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapselect_client.htm). 

One usage in abapGit:
https://github.com/abapGit/abapGit/blob/8555d1a0da6400fc04dbb0e3851e69bf76e5b720/src/utils/zcl_abapgit_user_record.clas.abap#L170-L182

**Comment by flaiker** [comment]
Isn't USING CLIENT only >= 7.5x?

**Comment by mbtools** [comment]
740sp5. https://github.com/abaplint/abaplint/issues/2580

Probably needs some dynamic solution to work with all releases and cloud. 

Can someone with ABAP cloud try to activate and run this statement? Does it cause syntax error? Runtime error?

**Comment by christianguenter2** [comment]
Gives error 'The addition "SELECT-CLIENT-SPECIFIED" is not valid in the restricted language scope.' in ABAP in the cloud.
![grafik](https://user-images.githubusercontent.com/17437789/175867748-ff039734-3614-40a9-938b-9d314402798c.png)

**Comment by christianguenter2** [comment]
Btw. `USING CLIENT` gives the same error.

**Comment by mbtools** [comment]
Multitenancy Development Guideline
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/9d994c89909c49e2957db840d7eace5c.html#database-table-access

Looks like we have to disable this part for BTP.
