### ISSUE TITLE
corrupt repository?

### ISSUE THREAD

**Issue by sherlick1** [abapGit/abapGit#5651]
Hi

I seemed to have corrupted my ABAPGIT repository.  I was trying to update one of my projects but the pulled failed.  During my attempts to fix it, I accidently "removed" not "uninstall" the ABAPGIT project.  When I tried to re-add the ABAPGIT project, I kept getting an error that the package ZABAPGIT already existed so I couldn't add ABAPGIT back to my list of projects in my repository list.  I then decided to use a new package (ZABAPGIT1) and managed to add ABAPGIT back to my list of installed projects in my repository list.  However, now when I do a new pull I get the following error message: "Folder logic: length = 0, parent: ZABAPGIT1, child: ZABAPGIT1_".

Any one tell me how I can fix this error?  I think something is corrupt in the file used to hold the list of installed projects but I am can't seem to locate this file or where it is installed on my system.  

I am on SAP S4/HANA 1909.  SAP GUI 777, patch 5

Attached is my "Debug Info" file with a txt extension.  I couldn't attach with an html extension.

[abapGit_Debug_Info_20220624_075230.txt](https://github.com/abapGit/abapGit/files/8976020/abapGit_Debug_Info_20220624_075230.txt)

**Comment by mbtools** [comment]
Let's try this... no guarantees. (Worst case you can delete the abapGit code and reinstall it)

- Get the latest version of zabapgit_standalone (https://raw.githubusercontent.com/abapGit/build/main/zabapgit.abap) and install it in your system
- Run the standalone version, go to the DB Utility and do a backup (https://docs.abapgit.org/ref-database-util.html)

- Find the `REPO` entry related to abapGit and edit it
- Change `<PACKAGE>ZABAPGIT1</PACKAGE>` to `ZABAPGIT` and save
- Exit standalone version and restart it
- The abapGit repo should be in the repository list with the correct package
- Open it and run a pull if there are any diffs

**Comment by sherlick1** [comment]
Hi Marc

 

Thank you for the suggestion.

 

I have performed the steps below.  I still get this error:

 

“Folder logic: length = 0, parent: ZABAPGIT, child ZABAPGIT_”

 

Looks like the package changed but there something wrong with the repository.

 

Should I delete the abapGit code and reinstall it?  Any thoughts as to what my happen to my current list of projects that are already installed?

 

Stephen

**Comment by mbtools** [comment]
you have a backup, so you can get the list of repos back if necessary.

`zabapgit_` is not a valid package name. It looks like the package hierarchy for `zabapgit` is not correct. 

First, clean-up the entries related to abapGit:

- go back to DB Utility 
- delete the `REPO` and `REPO_CS` entries for "abapGit" (keep all others, of course)

Then delete all objects in ZABAPGIT and any sub-packages. 

Now install the developer version as documented:
https://docs.abapgit.org/guide-install.html#install-developer-version
