### ISSUE TITLE
Dump when pulling repo with objects of type BDEF

### ISSUE THREAD

**Issue by wurzka** [abapGit/abapGit#5657]
Due to latest code changes in SAP development environment, we are getting dumbs when pulling a repo with objects of type BDEF. The reason for this is a type change in our latest development systems. As a consequence [this assignment](https://github.com/abapGit/abapGit/blob/8555d1a0da6400fc04dbb0e3851e69bf76e5b720/src/objects/zcl_abapgit_object_bdef.clas.abap#L242) leads to dumbs.
This problem can only be reproduced in SAP systems with this code change.

To solve this problem, we suggest to change this type assignment
https://github.com/abapGit/abapGit/blob/8555d1a0da6400fc04dbb0e3851e69bf76e5b720/src/objects/zcl_abapgit_object_bdef.clas.abap#L232
to
`CREATE DATA lr_metadata  TYPE ('CL_BLUE_SOURCE_OBJECT_DATA=>TY_OBJECT_DATA-METADATA'). `

I would like to create a pull request that does that change. In order not to have to create a fork, I would like to have rights to contribute. Can you assist please, @larshp?

**Comment by larshp** [comment]
I dont have access to do abapGit development in any systems that supports BDEFs

@ThomasPloski can you help?

**Comment by wurzka** [comment]
I can do the changes but would prefer having rights to contribute to this repository without having to fork.

**Comment by larshp** [comment]
@wurzka try again

**Comment by christianguenter2** [comment]
> I can do the changes but would prefer having rights to contribute to this repository without having to fork.

What's the reason for not forking the repo?

**Comment by wurzka** [comment]
@larshp works, thanks!

@christianguenter2  For this single issue, there is no reason why forking is worse. For further issues it would be better to be able to open pull requests so others can also contribute to them easily
