### ISSUE TITLE
SSST: Style with warning cannot be pulled

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5665]
Pull test case
https://github.com/abapGit-tests/SSST branch: test_tab.
Which is a smartstyle with this warning.
![grafik](https://user-images.githubusercontent.com/17437789/175916400-fd730469-7809-4c45-8355-5adc2d87b479.png)

Then an unrelated message appears and the status is not deserialized
![grafik](https://user-images.githubusercontent.com/17437789/175917626-a87ce086-5366-4fa1-a780-969f9569699e.png)

and one can no longer use system navigation buttons
![grafik](https://user-images.githubusercontent.com/17437789/175916152-e5bfe72b-afd5-473b-950c-7a58afaf63eb.png)

Reason is that some list output is generated which blocks. It appears after e.g. starting debugging.
![grafik](https://user-images.githubusercontent.com/17437789/175916237-50feccb0-1769-436e-bde7-6b6edbdfef6b.png)

**Comment by mbtools** [comment]
CI didn't catch this one https://ci.abapgit.org/ since it ran in batch. Oh well.

**Comment by mbtools** [comment]
I missed that you had a branch. Yes, CI only pulls `main`. Can we merge your test branch?

**Comment by christianguenter2** [comment]
Done.
