### ISSUE TITLE
Transport to Branch: Objects are not staged

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#5673]
abapGit version: 1.115.0

When transport to branch is used multiple times for the same transport number then stage logic not working. Below are the steps to replicate.

1. Stage pending changes, if any

![image](https://user-images.githubusercontent.com/29766214/177021577-f745735d-f221-45a8-a079-a63fb73bfa28.png)

2. Make change to at least one object. I have modified one data element

![image](https://user-images.githubusercontent.com/29766214/177021608-9b4c94c6-e40c-4c38-91c7-e0ea570623fa.png)

3. Use "Transport to Branch". Branch created and all the relevant objects staged. Up to this point, all look good.

![image](https://user-images.githubusercontent.com/29766214/177021634-63b7688e-9b11-414b-9819-9714800657af.png)

4. Now, delete the newly created branch and set previous branch active. Branch DR1K902736 deleted and master set to active branch. Notice that the object status has been modified and it shows "remote modified"

![image](https://user-images.githubusercontent.com/29766214/177021717-19d02006-41e0-4f74-8c48-aa153c7c7f61.png)

5. Repeat "Transport to Branch" with same transport request number. Notice that branch is created but object is not staged.

![image](https://user-images.githubusercontent.com/29766214/177021775-dc4e5da1-d9b3-4de1-aeb2-9c1e37ce547f.png)

Since the status has been changed from "local modified" to "remote modified" the below logic is not staging the same objects when second time used. I believe, either status needs to be fixed or below logic need to include remote modified as well. Any thoughts?

![image](https://user-images.githubusercontent.com/29766214/177021874-2f07025c-a762-4376-af7a-a8efcaeb375e.png)

**Comment by mbtools** [comment]
AG doesn't keep the object status by branch. Therefore, when switching branches, we can't reliably determine whether the local or the remote side was changed. 

Removing `not lstate is initial` would turn this into a "forced stage". In other words, also objects without changes would be selected. Maybe that actually makes more sense when it's based on a transport.

**Comment by yellappam** [comment]
I have also observed another point where deleted objects are not staged due the below code which is restricting the deleted objects not be be added to the transport object list.

![image](https://user-images.githubusercontent.com/29766214/177037170-00c8a23e-a45c-45e6-a9e3-cabc2b804941.png)

![image](https://user-images.githubusercontent.com/29766214/177037235-66abcced-5b7d-4489-9a8c-f5f6b07b2560.png)

**Comment by yellappam** [comment]
> AG doesn't keep the object status by branch. Therefore, when switching branches, we can't reliably determine whether the local or the remote side was changed.
> 
> Removing `not lstate is initial` would turn this into a "forced stage". In other words, also objects without changes would be selected. Maybe that actually makes more sense when it's based on a transport.

Thank you for the clarification on the diff status. I think we need to change where condition to "lstate is not initial or rstate is not initial"  and accordingly adjust the logic inside the loop.

**Comment by larshp** [comment]
well, it will also not work, there is not enough information, as suggested a few years ago it should be changed to

* file only exists locally
* file only exists remotely
* differences
* matches

its easy to implement, easy to understand => it will work instead of trying to fix these bugs in a neverending story

**Comment by mbtools** [comment]
I would agree if we can define how we visualize the diffs. Which side is "green" and which is "red"?

**Comment by larshp** [comment]
diffs, display the same way as a github pull request

**Comment by yellappam** [comment]
> well, it will also not work, there is not enough information, as suggested a few years ago it should be changed to
> 
> * file only exists locally
> * file only exists remotely
> * differences
> * matches
> 
> its easy to implement, easy to understand => it will work instead of trying to fix these bugs in a neverending story

Do we need these additional validations? My understanding is for every supported transport object, there would be file(s) in the local which we can stage it without these additional validations. 

![image](https://user-images.githubusercontent.com/29766214/177059275-1c2e4fd0-a072-4ec9-9318-30cf89b1e43c.png)

**Comment by mbtools** [comment]
The code looks correct to me. If the local state is `A` or `M`, then the object needs to be added. If it's `D` then it needs to be removed. 

We check `delflag` to see if there is an inconsistency between the local state and what's recorded in the transport. As you wrote above, the local state is not correct (which is a known issue). For example, if the transport contains a deleted object (`delflag = 'X'`), then the status calculation must *not* result in `A` or `M` (the object doesn't exist anymore). There are a few exceptions where SAP does not set the `delflag` when deleting the object (there are more like `W3MI` so the if needs some additions). 

You could try "Advanced > Update Local Checksums" after switching branches.

(see also https://github.com/abapGit/abapGit/issues/3684)

**Comment by yellappam** [comment]
It is good to have the checks if inconsistency is expected. Has there been an inconsistency between transport object status and abapGit status?

**Comment by yellappam** [comment]
> zcl_abapgit_transport_objects

@mbtools - The highlighted IF condition needs to be removed otherwise, it is not staging the deleted objects during transport to branch. Currently, I have deleted this in my local system. Is there a reason for the IF condition?

**Comment by yellappam** [comment]
> I have also observed another point where deleted objects are not staged due the below code which is restricting the deleted objects not be be added to the transport object list.
> 
> ![image](https://user-images.githubusercontent.com/29766214/177037170-00c8a23e-a45c-45e6-a9e3-cabc2b804941.png)
> 
> ![image](https://user-images.githubusercontent.com/29766214/177037235-66abcced-5b7d-4489-9a8c-f5f6b07b2560.png)

@mbtools - The highlighted IF condition needs to be removed otherwise, it is not staging the deleted objects during transport to branch. Currently, I have deleted this in my local system. Is there a reason for the IF condition?

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/blob/96cd546c7ee129fb63180107f8623aab3dfe0923/src/cts/zcl_abapgit_transport.clas.abap#L279-L285

Yes, the `if` is not correct. It should add an entry to `rt_tadir` in any case. `ls_tadir` will be initial if the object is already deleted completely. you will have to set `object` and `obj_name`.

**Comment by yellappam** [comment]
I will adjust the code as part of overall changes of this bug.

**Comment by yellappam** [comment]
@larshp - Sorry it has been a long time since I had my last work on this. I was on a long vacation and completely missed this one. I may not get some time for another 3 months due to other priorities. I am happy for someone to pick up this otherwise, I can work on it when I get some time.
