### ISSUE TITLE
Enable OAUTH2 login to GitHub (and other services)

### ISSUE THREAD

**Issue by Daniel-Giron** [abapGit/abapGit#5674]
Hello,
I have looked into past discussions about various SSO features in the abapGit programs: #3113 and #3798.
I see that enabling the ABAP server to perform OAUTH2 login was previously attempted at #3766.
Two years have passed, maybe we can reopen the issue?
It's something that I would love to use in my current organization with GitHub Enterprise, and we can't really use passwords or tokens due to company policy.

**Comment by larshp** [comment]
pull requests welcome, might want to place some parts of it in separate repo

**Comment by mbtools** [comment]
no action
