### ISSUE TITLE
Syntax error '"LT_COMPONENTS" is not a structure or internal table with header line' when activating ZABAPGIT_STANDALONE

### ISSUE THREAD

**Issue by DirkBor** [abapGit/abapGit#5678]
Hello, 
I get this syntax error when I try to activate the newest version of ZABAPGIT_STANDALONE.
We have 	SAP_BAS 7.31 and SAP_ABA 7.31 running.
In method "**get_descriptions_compo_subco**" of class: "**kHGwlUKtFBXjILcBRBJOnvUCODLJDd**" .
the system throws this syntax error.
**"LT_COMPONENTS" is not a structure or internal table with header line**.		

How could it be fixed?
Best regards
Dirk
![image](https://user-images.githubusercontent.com/108811282/177557126-f5f76272-04f7-4fb1-b474-573f8093be4d.png)

**Comment by christianguenter2** [comment]
`MOVE-CORRESPONDING` for internal table was introduced with NW 7.40 SP05.
https://blogs.sap.com/2014/02/06/abap-news-for-release-740-sp05/

**Comment by christianguenter2** [comment]
@DirkBor try latest build

**Comment by larshp** [comment]
next time this happens, it should be caught by the linter, check added in 2.91.6
