### ISSUE TITLE
WAPA: Serialization with a binary file

### ISSUE THREAD

**Issue by jrodriguez-rc** [abapGit/abapGit#5681]
There is a problem in the serialization of BSP application that has a binary file, in my case a FontAwesome otf file:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/56556686/178230819-86a2ff4f-df80-4143-a3f4-8d05a9a5f526.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/56556686/178231052-3635d24b-4039-43d3-907d-21b6380993b0.png">

The problem seems to be that the "page content" (otf file) is converted from string into xstring, but it is already a binary content
<img width="929" alt="image" src="https://user-images.githubusercontent.com/56556686/178231486-56fe4f3c-47fd-41dc-8305-52c7a032ed18.png">

If we could determine that the file is binary content the conversion to xstring will be skipped, just moving the content to the xstring without conversion

**Comment by jrodriguez-rc** [comment]
The error was from the beginning, but it brings up from #5638

**Comment by mbtools** [comment]
Use `zcl_abapgit_utils=>is_binary` to check

https://github.com/abapGit/abapGit/blob/main/src/utils/zcl_abapgit_utils.clas.abap#L52

**Comment by mbtools** [comment]
A .js certainly should not be considered binary. Maybe check is xml_source is_binary before all these itab/string conversions.

**Comment by jrodriguez-rc** [comment]
Hmm, it seems that P_XML_SOURCE is only returned when content is plain and when it is binary P_XML_SOURCE  is empty, returning only P_CONTENT

https://github.com/jrodriguez-rc/abapGit/blob/978c81f90af482c90f86d006ffc0df4264f6126b/src/objects/zcl_abapgit_object_wapa.clas.abap#L177-L190

**Comment by mbtools** [comment]
Tried with https://github.com/abapGit-tests/WAPA_Fiori but that doesn't have any binary page content either. 🤷

**Comment by jrodriguez-rc** [comment]
It was created with WebIDE some time ago.

I tried to create a new application with the same in WebIDE and BAS, but at the deployment, it was removed:
<img width="171" alt="image" src="https://user-images.githubusercontent.com/56556686/195582977-7bc57b08-3d7d-430a-a1ce-6be3f59eceaf.png">
<img width="291" alt="image" src="https://user-images.githubusercontent.com/56556686/195583013-baced322-d2ca-4389-b2d1-cf0be351269f.png">

**Comment by mbtools** [comment]
Hi @jrodriguez-rc, I tried a bunch of ways but was not successful in reproducing it. Per SAP, binary files are stored in the MIME repository (of the corresponding BSP app): https://sapui5.hana.ondemand.com/#/topic/5a814d9945d148b0a1ad941791c3c723

If binaries like the `otf` file are not stored as a MIME, please open an issue with SAP. 

As I wrote, it's possible that a BSP page or fragment contained some data that could not be converted to UTF-8. If the error happens again, please check `iv_string` to see what data exactly it has. Should this be binary data, then SAP is not storing it properly and should be fixing it. If it's "text data", then check what in the data prevents the conversion. What is the codepage of the source system? 

Downloading the app via program /UI5/UI5_REPOSITORY_LOAD might help inspect the individual files. 

Unless it's reproducible, I suggest closing https://github.com/abapGit/abapGit/pull/5687 
(we can always come back to it if necessary)
