### ISSUE TITLE
dependency error on older version, ok on newer

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#5688]
Setup: [NPL 7.52SP04](https://blogs.sap.com/2019/10/01/as-abap-7.52-sp04-developer-edition-concise-installation-guide/) and [A4H HANA1909](https://blogs.sap.com/2021/02/15/sap-abap-platform-1909-developer-edition-available-soon/) demos, both running [current](https://github.com/abapGit/abapGit/commit/d0e2314bad33be2cffc3ce4511074cf67183ae6f) abapGit.

As part of https://github.com/abap2xlsx/abap2xlsx/pull/1025 I need to switch from main to PR branch and back; the PR branch has removed a [reference to a table type from a class](https://github.com/abap2xlsx/abap2xlsx/pull/1025/files#diff-89e092a5a5cd9182ab304cfaf0a8633e2a22f7ddb63366377714e9a24c5a75c8), the [table type itself](https://github.com/abap2xlsx/abap2xlsx/pull/1025/files#diff-54b393f643f60bc3b8a32c6f81ee60bbdfe0fd5e0d81b3ca93492041500cc24f) and the [underlying row type](https://github.com/abap2xlsx/abap2xlsx/pull/1025/files#diff-9eeedfa733d260e5f826c9cc6275f8a957695e1cab5aa30db3053f19d4e617de).

A4H can switch back and forth without issues, multiple times; NPL, when switching back to main, always throws an error:
![immagine](https://user-images.githubusercontent.com/25269970/179359843-ff567647-3cca-425b-b157-0920f0af0d23.png)

I already checked that I am marking the checkboxes to delete the two local objects, that's not the issue apparently; workaround was multiple selective pulls along the dependency chain, that is class, table, row. EDIT: actually it is enough to selective pull the code changes, then the two DDIC structures can be processed together and removed.

**Comment by AndreaBorgia-Abo** [comment]
Ok, I have created a ["pre" tag](https://github.com/AndreaBorgia-Abo/abap2xlsx/releases/tag/aG_5688-pre) to represent the main branch and a ["post" tag](https://github.com/AndreaBorgia-Abo/abap2xlsx/releases/tag/aG_5688-post) to represent the PR branch, since I normally remove branches from my fork after merging. 

Switching back to main here corresponds to jumping from "post" to "pre"; error still happens in NPL with a [slightly newer aG](https://github.com/abapGit/abapGit/commit/ecc7de248ce761e57c5c27c9aec8a65f1604c5a6).

Here is the content of ct_tadir at the end of the method for NPL:
```
	R3TR	TTYP	ZEXCEL_T_SHEET_STYLE	$ZABAP2XLSX	750001
	R3TR	TABL	ZEXCEL_S_SHEET_STYLE	$ZABAP2XLSX	750002
```
and for A4H:
```
	R3TR	TTYP	ZEXCEL_T_SHEET_STYLE	$ZABAP2XLSX	750001
	R3TR	TABL	ZEXCEL_S_SHEET_STYLE	$ZABAP2XLSX	750002
```

So, aG does the right thing, correct? On to RSDEPEND: since it wants a program as input, I have used [ZABO_ABAP2XLSX_BUG_1020](https://github.com/AndreaBorgia-Abo/ABAP-Examples/blob/main/src/github/zabo_abap2xlsx_bug_1020.prog.abap) and ran it right after the SORT at the end of the method. I'm attaching the output, I can't really parse it even after reading the documentation for note 1230076.

[NPL-depend-after-sort.txt](https://github.com/abapGit/abapGit/files/9229067/NPL-depend-after-sort.txt)

**Comment by mbtools** [comment]
I can't find anything wrong in AG and don't have an NPL to reproduce it. If this is still an issue, can you set a break-point in NPL function `RS_DD_DELETE_OBJ` for all `MESSAGE` statements? Which `MESSAGE ... RAISING dialog_needed` is causing the problem?

**Comment by AndreaBorgia-Abo** [comment]
Thanks for the tips, I'll try and replicate it during the holidays, then update the ticket or close it.

**Comment by AndreaBorgia-Abo** [comment]
Restarted NPL after a long time, reset the license, upgraded first standalone aG and then the devel repo,
Running the devel version, I attempted jumping from "pre" to "post" (away from "main"), got the same error message.
![grafik](https://user-images.githubusercontent.com/25269970/205436268-7b9fbb3d-b46d-412b-ab9e-98dd43a06b76.png)
Both objects only bail out in the point above.
Repeated tests on A4H, still no issue there (be that for the different system version, be that simply chance, who knows...)

**Comment by mbtools** [comment]
the bp on `CALL FUNCTION 'RS_EU_CROSSREF'` to see where the object is still used

![image](https://user-images.githubusercontent.com/59966492/222825106-b7e07a9e-6a8a-49c4-9387-5dbdf6f85d74.png)

**Comment by AndreaBorgia-Abo** [comment]
Now with aG 1.122.0 devel version, FORM CHECK_CROSSREF_DARK, INCLUDE LSDYYU06: it stops once for each object.

i_findstrings = one line only, with ZEXCEL_T_SHEET_STYLE 
o_founds = ZCL_EXCEL_WORKSHEET===========CU

i_findstrings = one line only, with ZEXCEL_S_SHEET_STYLE
o_founds = ZEXCEL_T_SHEET_STYLE

The workaround, leaving the two DDIC objects out of the first pull, still applies.

**Comment by mbtools** [comment]
I'm afraid we won't be able to fix this on lower releases. The option to force deletion just isn't available. Therefore, when AG tries to delete these DDIC objects before the usage in the class is removed, it will error.

**Comment by AndreaBorgia-Abo** [comment]
Yeah, that was also my idea. Now, in this specific use-case it is totally acceptable but at work where we have larger packages that have to be supported on fairly old systems this might not be ideal :(

**Comment by mbtools** [comment]
how often do you delete DDIC?

**Comment by AndreaBorgia-Abo** [comment]
I'll leave this question to @mssoftag but my take is that it is could be not so rare. If we manage to bring our existing codebase into git as we'd like, then switching between branches for bugfixing and testing might well be a thing.

**Comment by AndreaBorgia-Abo** [comment]
Yes, we can always reopen this later. I've started using aG on a new development subpackage internally, the question of what to do with the existing codebase is still open.
