### ISSUE TITLE
Type "IF_ADT_LOCK_HANDLE" is unknown

### ISSUE THREAD

**Issue by bolarsson** [abapGit/abapGit#5705]
For some of my development I am still forced to use an ancient SAP system 7.02 - I can't upgrade until the customers do. 
I've just installed the latest version of zabapgit_standalone, and I get the above syntax error. 
![image](https://user-images.githubusercontent.com/29232319/182787902-620397a1-80d5-4cae-b42f-03884e57f9d2.png)

Does abapGit still support 7.02?

Thanks in advance,
Bo Larsson

**Comment by larshp** [comment]
> Does abapGit still support 7.02?

that is the intention, yes. But we do change the code all the time, and sometimes it breaks stuff on older and/or newer versions

**Comment by larshp** [comment]
@bolarsson try this, https://github.com/abapGit/abapGit/pull/5706, ie. just comment the method and implementation

the AFF code is not in use yet

**Comment by bolarsson** [comment]
The temporary workaround fixed the issue for me. Thanks.

**Comment by larshp** [comment]
thanks for the bug report

the fix has been merged, https://github.com/abapGit/build will automatically update in a few minutes

closing
