### ISSUE TITLE
Downport 7.02: cl_abap_unit_assert=>assert_true

### ISSUE THREAD

**Issue by bolarsson** [abapGit/abapGit#5710]
In the ABAP Unit test class for ZCL_ABAPGIT_OBJECT_INTF, ltcl_serialize, the method assert_true( ) is used twice.

The method cl_abap_unit_assert=>assert_true( ) does not exist on 7.02. 
Replace with `cl_abap_unit_assert=>assert_equals( act = lv_is_equal exp = abap_true ).`

I'd do it myself but I don't think I can created branches and pull requests.

**Comment by larshp** [comment]
Hi,
Check https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by bolarsson** [comment]
Thanks. I'll give it a try.
