### ISSUE TITLE
AbapDoc generation in CI?

### ISSUE THREAD

**Issue by Zeatynis** [abapGit/abapGit#5715]
Hello,
have you heard about any plugin/tool which can generate documentation in HTML/MD format based on the current code pushed to git server? I wanted to have always up to date documentation. I thought that it can be achieved by running this plugin/tool in CI after pushing to master branch.

I ask here because this tool must be strictly connected to abapgit template of files (xml, abap).

**Comment by larshp** [comment]
https://abapedia.org generates lists of the artifacts and methods, however does not handle abapdoc (yet)

**Comment by flaiker** [comment]
https://github.com/i302574/abap-doc-export is a candidate but doesn't seem to have made it far.

**Comment by larshp** [comment]
and most of https://github.com/SAP/abap-file-formats-tools now runs in transpiler/open-abap runtime, part of what it does is reading and parsing the abapdoc, however generates json schema instead of documentation

**Comment by flaiker** [comment]
For generation in the ABAP stack there's currently an improvement request to be able to call the abapdoc generation in eclipse in CI.

**Comment by larshp** [comment]
For generation in the ABAP stack: IMHO its a bad idea, spinning up a ABAP stack, pulling the code, generating HTML.

Alternatively call the source system where the commit comes from to generate the documentation, however, it does not necessarily have the same code as in git

**Comment by flaiker** [comment]
Oh for sure, I was more thinking of having access to a central system where the code is anyways (central development system scenario) and living with the desync between committed state and active state, as that generator in SAP standard is the only one that's finished / working currently as far as I know.

**Comment by larshp** [comment]
@Zeatynis ok to close?

**Comment by Zeatynis** [comment]
Yeah, sure. Just a little summary: all these solutions are far from perfect. Abapedia didn't work for me. It's strictly connected with transpiler which doesn't work with void types. I may be wrong though 😄

**Comment by larshp** [comment]
Abapedia does not transpile, it just takes the objects and makes html pages for it

**Comment by Zeatynis** [comment]
> Abapedia does not transpile, it just takes the objects and makes html pages for it

If so, I'll check it again.

**Comment by Zeatynis** [comment]
OK. I thought that if it uses abaplint it also uses transpile. Anyway it worked. I just needed to handle void types.
