### ISSUE TITLE
Character set conversion for one or more characters is not possible 

### ISSUE THREAD

**Issue by jddtrejo94** [abapGit/abapGit#5721]
in the option to open the package i can't see the information and  i have this message

![ERROR](https://user-images.githubusercontent.com/110943937/184924644-31f9735c-95f8-4661-87dd-ed60f82724cd.png)

**Comment by mbtools** [comment]
your repository has only a readme (https://github.com/jddtrejo94/Dev). so the issue is related to an object in your Z-package. 

try setting a break-point where the exception is probably raise:
https://github.com/abapGit/abapGit/blob/787bc605b078bfef8783093f608c3405f95b0ae9/src/utils/zcl_abapgit_convert.clas.abap#L221

then check the call-stack to find out which object type (`zcl_abapgit_object_<type>`) it's related to. In that class the value of attribute `ms_item` will tell you which object is causing the problem.

**Comment by jddtrejo94** [comment]
I only have a program in my packege,  as it is in the following image

![image](https://user-images.githubusercontent.com/110943937/184944228-2f0a44b9-65b9-4c10-8ff0-ff1d51508824.png)

my break-point doesn't stop in this exception

![image](https://user-images.githubusercontent.com/110943937/184948198-2b468529-6877-46c5-94ba-e14b3fd46866.png)


thanks for answering me

**Comment by larshp** [comment]
@jddtrejo94 try placing the breakpoint 4 lines down, at `zcx_abapgit_exception=>raise_with_text( lx_error ). ` as suggested by Marc

**Comment by jddtrejo94** [comment]
Hello dudes

I found the error, but to be honest, i don't know why i have this error, can someone guide? please.

![image](https://user-images.githubusercontent.com/110943937/185509425-239d2ea7-0455-4677-b845-e84f4f434c02.png)

**Comment by larshp** [comment]
check the call-stack to find out which object type (`zcl_abapgit_object_<type>`) it's related to.

**Comment by mbtools** [comment]
My guess is that it's a non-Unicode system. string_to_xstring_utf8_bom might have a bug if iv_string is empty.

**Comment by jddtrejo94** [comment]
I work with ECC non-Unicode system, is there a possibility to do something to solve this error?

**Comment by mbtools** [comment]
what is the callstack at the break-point?

**Comment by jddtrejo94** [comment]
to be honest, i'm not sure what is the callstack at the break-point dude,

i was investigating and i have this data

![image](https://user-images.githubusercontent.com/110943937/185698519-c969bdd1-4d91-4335-ae9f-078f43e76188.png)

![image](https://user-images.githubusercontent.com/110943937/185698548-515e716c-cc57-4d81-bc3a-fadbaa398fb2.png)

isn't that data the callstack?

**Comment by mbtools** [comment]
yes, that's the callstack. the problem is a regression of #5638. fix coming up

**Comment by mbtools** [comment]
please test the following change to method `serialize` (line 55384):

```abap
   "unicode systems always add the byte order mark to the xml, while non-unicode does not
    "this code will always add the byte order mark if it is not in the xml
    TRY.   "<<<INS
        lv_mark = zcl_abapgit_convert=>xstring_to_string_utf8( cl_abap_char_utilities=>byte_order_mark_utf8 ).
      CATCH zcx_abapgit_exception ##NO_HANDLER.   "<<<INS
    ENDTRY.   "<<<INS
```

**Comment by jddtrejo94** [comment]
I want to tell you thanks @mbtools 

I could fix the error with your help.
