### ISSUE TITLE
Error "Wrong Adler checksum" is shown when pulling the latest code from Github

### ISSUE THREAD

**Issue by bluebaby1** [abapGit/abapGit#5722]
Error "Wrong Adler checksum" is shown when pulling the latest code from Github,is anyone know how can we resolve this issue?
I also try to update local checksums (the path is “Advanced”->”Update Local Checksums”) the error is still there.
Appreciate if you can shed some lights on this issue.

![image](https://user-images.githubusercontent.com/63991138/185026864-971744c7-a7e8-4cd0-985e-5f094dfcca3f.png)

**Comment by larshp** [comment]
Hi @bluebaby1 

A: Make sure to [update to latest abapGit version](https://docs.abapgit.org/guide-upgrade.html)
B: What type of git server are you connecting to? github.com, gitlab.com, other?

**Comment by bluebaby1** [comment]
Dear Larshp,

Thanks a lot for your valuable input.
B: What type of git server are you connecting to? github.com, gitlab.com, other?
==>we're connection to github.com

**Comment by larshp** [comment]
@bluebaby1 the repository url ends with "-samples" is this a public repository? If its public then we can try reproducing the error...

**Comment by bluebaby1** [comment]
Dear Larshp,

the repository url is a public repository.Kindly help to analysis this issue.
The address is: https://github.com/SAP-samples/logistics-business-network-gtt-standardapps-samples.git

![image](https://user-images.githubusercontent.com/63991138/185048604-872df47a-74d4-4d0b-bb2a-ca83c102bafb.png)

If you go back and re-run the program,press the > button,the error still there.
![image](https://user-images.githubusercontent.com/63991138/185048647-5a92b9ef-f329-4813-9694-cc4cdaa9920f.png)

![image](https://user-images.githubusercontent.com/63991138/185048667-d5d2e703-6cf4-4d66-82ff-1c7a30de9805.png)

Seems the error located in line 103706 of method zlib_decompress
![image](https://user-images.githubusercontent.com/63991138/185050498-3418bf94-3cb8-4742-bb24-5cde4fce0f54.png)

**Comment by larshp** [comment]
thanks, I've reproduced the error,
![image](https://user-images.githubusercontent.com/5888506/185052617-8549f9c9-f703-499c-b670-b21c9c792163.png)

**Comment by larshp** [comment]
as a temporary workaround, you can create a offline project, and [import via zip](https://docs.abapgit.org/guide-import-zip.html)

**Comment by bluebaby1** [comment]
Thanks a lot for your prompt reply,let me try to use offline mode and try again.
Thanks again.

**Comment by bluebaby1** [comment]
Just checked the online mode with latest version 1.116.0 (Standalone Version),it's the seem error.
Use offline mode seems no issue.
Thanks a lot.

**Comment by larshp** [comment]
keep the issue open for now, there is a bug somewhere in zlib and/or adler

https://github.com/abapGit/abapGit/blob/main/src/zlib/zcl_abapgit_zlib.clas.abap

https://github.com/abapGit/abapGit/blob/main/src/utils/zcl_abapgit_hash.clas.abap#L71

**Comment by bluebaby1** [comment]
Dear Larshp,

Thanks a lot for your update.

**Comment by larshp** [comment]
@bluebaby1 can you help testing https://github.com/abapGit/abapGit/pull/5723 ?

**Comment by bluebaby1** [comment]
Thanks a lot Larshp,let me check the issue 5723 and will update the status in this issue.

**Comment by bluebaby1** [comment]
Dear Larshp,
I'm not sure how can I do the testing for issue #5723,can you provide more information to me?
Thanks in advance.

**Comment by larshp** [comment]
if running the standalone report, get it from https://github.com/abapGit/abapGit/actions/runs/2875127564

if using the developer edition switch to branch https://github.com/abapGit/abapGit/tree/hvam/zlib1708

**Comment by bluebaby1** [comment]
Dear Larshp,

Following the guides of issue #5723,I've changed my local code,it works fine. Thanks a lot for your kindly support.
![image](https://user-images.githubusercontent.com/63991138/185279822-aad06d69-be02-400a-82b8-758abbd9a716.png)

**Comment by bluebaby1** [comment]
As the issues was fixed,I'll close this issue now.Thanks a lot for your kindly support.

**Comment by larshp** [comment]
merged, https://raw.githubusercontent.com/abapGit/build/main/zabapgit.abap will be updated in a few minutes
