### ISSUE TITLE
suggestion: Check Variant in ABAPGit while staging - should'nt it just check only those objects to be added into Commit?

### ISSUE THREAD

**Issue by rayatus** [abapGit/abapGit#5725]
While working on #4835 I set up my local enviroment to run a specific CI variant

![image](https://user-images.githubusercontent.com/12736990/185620858-88b04201-4063-401d-8f38-417d15cd1887.png)

and when trying to commit a specific serializer for that SOBJ then abapGit scans all objects 

![image](https://user-images.githubusercontent.com/12736990/185620143-dfb11c48-3188-4369-a25a-008f2110a5c7.png)

wouldn't it be easier if that check was executed only for those objects that were selected to be commited?

![image](https://user-images.githubusercontent.com/12736990/185621191-e1a9c5a5-0b54-4aba-bac0-88ff4b78cba6.png)

as if not, then it is not really interesting "blocking commits" if errors found but also time spend checking objects not interested in.

**Comment by mbtools** [comment]
you make the assumption that changes impact only the changed object(s). however, they can certainly impact other objects, too (even objects outside of your package/repo). 

in general, your check variant would apply to the complete repo. so checking all objects is the way to go. it's worth the few seconds it takes to run.
