### ISSUE TITLE
theme sync does not work with Quartz dark

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#5729]
Using Windows GUI 7.70 PL8, currently the newest. Been using Quartz Dark for a long time, just noticed now that you could change the theme within abapGit and tried the "sync with GUI" option:
![immagine](https://user-images.githubusercontent.com/25269970/186492591-e6df39f3-d005-4ad0-a9a4-4d3783194cee.png)
For Belize, saving the new theme settings immediately changes the look, no need to restart.
For sync, there is no visible reaction, even restarting the program.

Is this to be expected since this particular theme is unsupported?

**Comment by fabianlupa** [comment]
There's no Quartz or Quartz Dark theme implemented for abapGit so there's no sync. One may argue when Quartz Dark is the GUI theme then the abapGit Dark theme should be used when sync is enabled, not sure how that fits, I personally haven't used it.

The relevant `CASE` block is here:

https://github.com/abapGit/abapGit/blob/29a9201a3bdc7686ce35f94a52aed6a729b5abdf/src/zcl_abapgit_settings.clas.abap#L314-L319

**Comment by AndreaBorgia-Abo** [comment]
Good, I would have tagged this as "question" because I had a feeling this was the case even without looking at code.
Thanks for the answer, I'll set it manually and be on my way.
