### ISSUE TITLE
missing method, report is activated anyway

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#5734]
Using ZABAPGIT, dev version, updated now.
On a customer system, I upgraded abap2xlsx to version 7.16.0
Released the CR and moved it to Quality, deleting the demos and the subpackage.
Next, I installed the demos as local package but forgot to select the corresponding version tag, thus importing ZDEMO_EXCEL51 which references method CONVERT_TO_TABLE, added AFTER releasing 7.16.

The report is activated anyway:
![immagine](https://user-images.githubusercontent.com/25269970/187473264-de4f3923-a130-4e05-9b30-7b69c03fa984.png)

Is this the intended behaviour or a bug?

**Comment by mbtools** [comment]
yes. AG deserializes classes and interfaces in active version (without syntax check). this avoids any issues related to dependencies that regularly exist between classes, for example, and we don't have to figure out/sort what would be a working activation order.

**Comment by AndreaBorgia-Abo** [comment]
ok, so nothing to see here, moving on :)
thanks.
