### ISSUE TITLE
Icon scaling default setting

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#5737]
For me the default icon scaling setting "Automatic" has never worked. The icons are always way too big on any scale larger than 100%. I also saw screenshots in documentations and some videos where the icons looked equally ridiculous.

For reference:

### 100% small

![image](https://user-images.githubusercontent.com/5270359/188309852-9b05a158-5056-465e-851b-5024bd586751.png)

### 100% automatic

![image](https://user-images.githubusercontent.com/5270359/188309869-e9d41778-08ff-4bcb-93e8-1580b0fe2656.png)

### 150% small

<img width="828" alt="image" src="https://user-images.githubusercontent.com/5270359/188309906-4872c033-932e-4e45-b8ef-4cc44fcccee6.png">

### 150% automatic

<img width="828" alt="image" src="https://user-images.githubusercontent.com/5270359/188309893-e4b8896c-f7c4-4772-a854-764652c0b259.png">

This is on SAP GUI 8.00 Beta with Edge as the browser control, multi monitoring scaling awareness enabled, Quartz Dark as the theme and on Windows 11. I also tried older themes that do not natively support the scaling and IE control instead of Edge. All look terrible. Maybe some GUI upgrade broke this?

The small setting works just fine for me. Unless I am missing some configuration where automatic actually does something useful I suggest at least changing the default to small.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/5270359/188310140-88d9034b-8a53-4479-a19c-1d02eac95dd2.png">

https://github.com/abapGit/abapGit/blob/366a30a0e01eeccef7d565f5ae1367f59e86c25d/src/zcl_abapgit_settings.clas.abap#L372

https://github.com/abapGit/abapGit/blob/366a30a0e01eeccef7d565f5ae1367f59e86c25d/src/zcl_abapgit_settings.clas.abap#L390

**Comment by mbtools** [comment]
the setting overwrites the CSS but it doesn't work right, indeed:

https://github.com/abapGit/abapGit/blob/763fbad76c182d90de7516e560bcabedfaa9be2a/src/ui/zabapgit_icon_font_css.w3mi.data.css#L8-L10

https://github.com/abapGit/abapGit/blob/763fbad76c182d90de7516e560bcabedfaa9be2a/src/ui/zabapgit_icon_font_css.w3mi.data.css#L29

https://github.com/abapGit/abapGit/blob/c04f7b8d7ff4f2332af9fe1e4648d57003966369/src/ui/zcl_abapgit_gui_page.clas.abap#L160-L165

https://github.com/abapGit/abapGit/blob/763fbad76c182d90de7516e560bcabedfaa9be2a/src/ui/core/zcl_abapgit_html.clas.abap#L141-L148

- automatic: leaves the style as defined in CSS
- large: doubles the size for all icons
- small: avoids the doubling when the "pixel metric => 2" (which I guess means it's HDPI)

Goes back to https://github.com/abapGit/abapGit/pull/2609. The setting is intended for [High DPI displays](https://doc.qt.io/qt-5/highdpi.html). However, we lost the "High DPI" description when changing the popup. I will add it back and update the docs.

**Comment by mbtools** [comment]
Changing the zoom factor is unrelated. It matters only if your display is HDPI. I don't have any so can't test.

**Comment by fabianlupa** [comment]
I also don't have any HDPI displays I guess. I just have the common use case of having a 13 inch laptop with 1080p and the default UI scaling on Windows is 125% to 150% for that screen size and resolution combination. I assumed if I had picked the 4k option then it would be 200% and no other difference. That would classify as HDPI? And that would be somehow handled differently not using the OS scaling option?

**Comment by mbtools** [comment]
I updated the docs (https://github.com/abapGit/docs.abapgit.org/pull/178) and comments in the code (https://github.com/abapGit/abapGit/pull/6583). 

Conclusion: 

If automatic does not work for a display configuration, a user can force the icons to be smaller or larger in their personal settings. If you work with different machines, then you might have to switch your settings accordingly.
