### ISSUE TITLE
cannot remove unused method

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#5743]
Tried both the standalone version (27.08.2022) and the current devel version but aG is (silently) refusing to remove zif_abapgit_popups~branch_popup_callback ( #5742  ) from my A4H system.
Manually removed the method, remaining diff was just the classname (case changed) and then it could actually update it.

**Comment by mbtools** [comment]
Yeah. https://github.com/abapGit/abapGit/issues/5578
We haven't found a working solution.
