### ISSUE TITLE
ALL INTF FILE  pull failed

### ISSUE THREAD

**Issue by agateliu** [abapGit/abapGit#5761]
![image](https://user-images.githubusercontent.com/65578850/190342008-54484b22-ab13-473d-b5f7-5491ee2e2a5b.png)
![image](https://user-images.githubusercontent.com/65578850/190342234-b1e50874-8bec-42d6-8442-5e11552f8260.png)
![image](https://user-images.githubusercontent.com/65578850/190342305-914652d5-001a-4ca4-8875-8fb179409023.png)
![image](https://user-images.githubusercontent.com/65578850/190342392-f43d5c1e-7cd1-4859-a73c-2f6cc9c965e1.png)
![image](https://user-images.githubusercontent.com/65578850/190342524-1d460728-1d06-489f-833a-2d12b66a7258.png)
![image](https://user-images.githubusercontent.com/65578850/190342706-eadc75ef-eee4-4b05-b5ea-cc961c8ac330.png)

**Comment by larshp** [comment]
is experimental features enabled on your system? the JSON handling of INTF should be activated only behind this feature flag

![image](https://user-images.githubusercontent.com/5888506/190344080-c0358789-541a-4484-a828-b6d077c02659.png)

**Comment by mbtools** [comment]
no response. closing
