### ISSUE TITLE
Metadata diff NW 752/04

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5766]
I have this diff in my NW752/04 system with latest abapGit.
![grafik](https://user-images.githubusercontent.com/17437789/191219211-d5709814-1bb9-404c-9029-d737402d87b6.png)
![grafik](https://user-images.githubusercontent.com/17437789/191219271-0b2d1405-9f34-419a-90d2-ee18fa7f551e.png)

Doesn't occur on other systems with NW > 752.
#5755
https://github.com/sbcgua/ajson/pull/132

**Comment by larshp** [comment]
@christianguenter2 try again

https://github.com/abapGit/abapGit/pull/5771

**Comment by christianguenter2** [comment]
Works. Closing.
