### ISSUE TITLE
abapGit Developer version APACK

### ISSUE THREAD

**Issue by simonegaffurini** [abapGit/abapGit#5767]
Hello, I see that this repository is currently not implementing the APACK interface.

I think it would be useful if it did: in our current scenario, we have a Z package with its APACK class and inside that package our abapGit user exit implementation. 

Because abapGit developer version is a dependency of our Z package we should have it as one, however my current understanding of APACK is that it on each repository pull it will look for the dependency met condition, which will fail in this case.
This is because this repo is not implementing APACK, but rather its keeping the dev version number in an interface.

Is there a specific reason why it is not implemented? Thanks

**Comment by mbtools** [comment]
Some reasons:
- AG doesn't have any dependencies
- APACK would work only with your Z-package but not with namespaces like /name/package
- Using APACK generates code which can become an issue when transporting your solution 
- APACK is extra maintenance effort 

I will leave it to @larshp to decide if we should add it.

**Comment by larshp** [comment]
I would like _not_ to add apack to abapGit. AbapGit supports the features of apack, but does not use it

There is https://github.com/abapGit/abapGit/issues/2236 which will hopefully be implemented sometime

@simonegaffurini any additional information for your scenario? Worst case, if the Z package is installed, and there is no abapGit in the system, it will result in syntax errors? Which will help the developer to understand something is missing

**Comment by simonegaffurini** [comment]
Hi, yes I am guessing the worst case scenario, you will get syntax errors, but that's what happens with any dependency not met.
Ideally I wanted to have a specific version of abapGit installed because that's the one we used for development and I guarantee it works with my user exit, granted it most likely will work with the latest too.

Looking at your comments I am starting to think APACK was not intended the way I see it. I thought it was more like a package.json in a node project where the version of the stable package is kept along with the possible dependencies, but this
`AG doesn't have any dependencies`
and the issue @larshp mentioned, are putting me off.
Is there a roadmap? I'd like to understand better where the concept of versioning and (possible) dependency of abapGit repositories will become in the future.

**Comment by mbtools** [comment]
There is no roadmap. AG is a community project with a handful of active contributors. Everything depends on volunteers.

The intensions for APACK were similar to what you expected. However, some things didn't work well (see above) and contributions to this feature stopped. 

You can of course make contributions yourself (pls discuss details beforehand), or sponsor someone to help build what's needed as is common in many other open source projects.

**Comment by larshp** [comment]
@simonegaffurini in general, I recommend building setups that help you moving forward, instead of helping to stay behind on old versions

due to the nature of ABAP, its not possible to treat it like NPM when there is persistency involved

**Comment by simonegaffurini** [comment]
@mbtools ok, so I am guessing APACK will be removed at one point for a new similar feature that will require a different implementation
@larshp APACK is not far from creating something like NPM. Sure it's missing a centralized registry, but here's what could happen:
First of all when installing a package with APACK, dependencies should always be checked (this should happen already, right?). You could have problems if you have two or more packages using the same dependency but with a different version, so the user should be notified and take actions, but I don't see any work around for this.

So install the dependencies with the right version; It can happen like this:
1- If git url is declared in the dependency, create an online repo. AbapGit will pull from the repository tagged like the version declared in the dependency (tags with the version are standard approach in git when making releases).
2- If no git url is declared on the dependency, allow a user exit where the zip of the package is expected to be returned. This allows user to implement their own private registry. If the zip is returned then install it as an offline repo.
The git url approach is useful when using public repositories, the user exit approach with private organization repositories.

This is the reason why I was asking for APACK on the abapGit repo, releases with the version are already made, but it's just missing that one file, like in NPM, that makes it a "true" package (and allows AG to trigger all the version checks).
Is this idea of using APACK completely out of its scopes? If it is, then how was it intended to be used?

**Comment by larshp** [comment]
consider git the central repository => https://github.com/abapGit/abapGit/issues/2236 => then the zip package workaround is not needed for private organizations

**Comment by simonegaffurini** [comment]
Then APACK is already working somewhat like NPM :)
Is it already pulling from the tag declared in the dependency version? If not, it should as it's the only versioning git provides.
I don't see differences with #2236 then.

If you decide to not implement apack in your repo, then you are forcing projects to not have that package as a dependency, because how else would abapGit check the current installed version of a package? Maybe you can check the repo current pull branch? Not really ideal, I could pull from latest then switch to a specific version and the check would pass.

**Comment by simonegaffurini** [comment]
Closing for the same reason of issue #5962
