### ISSUE TITLE
Syntax error on 731

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5769]
![image](https://user-images.githubusercontent.com/15635498/191590302-a3190603-a115-4981-8584-efbe73097746.png)
![image](https://user-images.githubusercontent.com/15635498/191590354-799fc3fb-16d8-49d4-87b2-58e33a25ab9d.png)

```
maybe ?
        zcx_abapgit_exception=>raise(
          iv_text     = lx_sql->get_text( )
          ix_previous = lx_sql ).

```

**Comment by mbtools** [comment]
yup. `get_text` works in all releases

**Comment by larshp** [comment]
@sbcgua try again

**Comment by sbcgua** [comment]
:+1:
