### ISSUE TITLE
Syntax error in ZCL_ABAPGIT_AJSON in 7.02

### ISSUE THREAD

**Issue by schneidermic0** [abapGit/abapGit#5772]
There is a syntax error in the test classes of `ZCL_ABAPGIT_AJSON`.

The tests are using `CL_ABAP_UNIT=>ASSERT_TRUE( ... )` and `CL_ABAP_UNIT=>ASSERT_FALSE( ... )`. These methods are not available in release 7.02.

**Comment by schneidermic0** [comment]
I will provide a pull request to fix the issue.

**Comment by schneidermic0** [comment]
@larshp Is this something you want to identify automatically by abaplint?

**Comment by larshp** [comment]
note that the fix must be made to https://github.com/sbcgua/ajson, and then the abapgit code is mirroed from there

**Comment by schneidermic0** [comment]
Thanks for the hint

**Comment by larshp** [comment]
abaplint: I would like to, but I dont want to maintain it. It checks against https://github.com/abaplint/deps, but I dont have time to miaintain ~10 different of these repositories

**Comment by schneidermic0** [comment]
If fixing the AJSON repository will lead to an automated fix in this repository, we can close this issue.

I have created an issue https://github.com/sbcgua/ajson/issues/133 and a pull request https://github.com/sbcgua/ajson/pull/134/files

**Comment by schneidermic0** [comment]
I think we can close this issue
