### ISSUE TITLE
Restrict ZABAPGIT to $packages (named packages)

### ISSUE THREAD

**Issue by ojnc** [abapGit/abapGit#5777]
**I  want users only to be able to export import packages starting with $ i,e, temporary packages**

Objective nobody should be able to export packages that are Z-code IPR of a company. 

The standalone version is so powerful and complete that if any user is able to install the standalone 
in say another name ex YSECRETGIT they might be be able to export import packages they are not supposed to.

Please suggest a solution to make abapgit 100% secure with no paths of bypassing security.

One can install standalone and pull full official repository.
However someone can install secretly another standalone copy in  another name.

Is it possible to change ZABAPGIT and related objects to alien sourcec system ID like XBA
And check program executing from source system XBA.
Then vulnerability would be perhaps partly addressed.

Regards
Jayanta@Kolkata

**Comment by larshp** [comment]
true, developers can publish stuff they have access to, that via

* copy paste
* https://github.com/palermo-consulting/sap-mass-abap-download-program
* https://wiki.scn.sap.com/wiki/display/ABAP/SAPlink
* or using abapGit which might be the easiest approach

but basically, if a person has access to something, that person can use that information for anything

as such, I recommend trusting developers that have been hired for professional services, if the professional services does not follow common best practice, there is typically lawful measures which can be taken

anyhow, we can add a user exit in https://docs.abapgit.org/ref-exits.html, to only allow for some specific packages to be versioned, but not this will be customer specific

**Comment by ojnc** [comment]
Agree 100% 

If you have any ready code on Restricting Packages, kindly mail to ssscal@gmail.com (as I am closing the case!).
Esp if you cannot add comments to a closed case?

CHANGE_TADIR looks attractive in case I do not hear from you!

Thanks for your excellent and prompt reply.

Regards
Jayanta@Kolkata

**Comment by mbtools** [comment]
Are your developers allowed to see the Z-packages in other tools like SE80 or ADT? Are they allowed to write their own programs in DEV? Are they able to debug in DEV?

If the answer to any of these is "yes", then, I'm afraid putting more security into abapGit is pointless. A malicious developer would easily find another way to get the code/IP.  For example, anyone can get the stand-alone version and take out any security check they don't like and paste it into any SAP system where they have developer access.

In short, you have to trust any developer on an SAP system anyway. 

PS: Have a look at https://docs.abapgit.org/ref-authorizations.html. You might be able to use it or extend it to prevent certain actions.

**Comment by ojnc** [comment]
My present assignment role is consultant.

Will keep ABAPGIT a secret swiss-knife for my own $JNCTMP

Unless some one has worked on real git ex ReactJS development on a shared repository
it will be difficult to explain ABAPGIT

Regards and Thanks
Jayanta

**Comment by larshp** [comment]
well, you dont need to explain why to use git for development, look at other ecosystems like ReactJS its natural to version code in git

**Comment by ojnc** [comment]
2004-2014 was in SAP ABAP and did a lot of development
2014-Oct21 did everything under the sun! including ReactJS
Nov21 decided to try Docker 1909  provided bt SAP and got hooked
Sep22-Oct22 a short 2 month project on S4HANA 1809

I do not want to keep any room for questions as I exit and seek further Self Study in 1909

**Comment by ojnc** [comment]
https://docs.abapgit.org/guide-uninstall.html

One Suggestion

I copied standalone to YTRY1 and under Advanced did Uninstall
475 objects were there in the $ABAPGIT and no hiccups in Uninstall

**Comment by ojnc** [comment]
I plan to work till 2026 
If I get long term opportunity will educate developers on ABAPGIT

I saw https://docs.abapgit.org/ref-exits.html
but could not figure out the solution to restrict packages

Searched standalone for METHOD.*_package
Many hits

  METHODS save IMPORTING iv_package TYPE devclass OPTIONAL
  METHOD export_package.
  METHOD check_package.
  METHOD get_package.
  METHOD load_package.

These look attractive for plugging in codes for PACKAGE name restrictions
Also to track usage in SAP LOGs

Please suggest if time permits
Regards
Jayanta
