### ISSUE TITLE
Add single objects and more than one package to an offline repo

### ISSUE THREAD

**Issue by coguci** [abapGit/abapGit#5782]
Hi experts,
we want to deliver some programs via offline repo (zip-down/-upload) from one system to another.
Many programs use objects from different packages. Is it possible to add these objects, or the whole package that these objects are in, to the same repository as where the program to be transported resides?
One information: we cannot use online repos.

Thanks for you help.
Best regards,
Sebastian

**Comment by mbtools** [comment]
A repo or zip is always based on an SAP package and sub-packages. So you either combine all objects into one package hierarchy (=all-in-one zip) or you use several packages which have to be installed in a particular order (=zips-with-dependencies).

**Comment by coguci** [comment]
OK, that's a pity. Then I'll have to create different packages. Thanks for your quick answer.
