### ISSUE TITLE
Make abapgit build repo a complete abapgit repo

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5784]
Would be nice to have build repo clone-able. Mainly for update purposes. So that current standalone version is copied to backup and used to pull the most updated. It has a real use case when remote desktop is very restricted to copy paste from web (yet abapgit is whitelisted ...)

P.S. extra idea: duplicate abapgit version tags to build-repo so that built progs are also tagged and revertable

**Comment by mbtools** [comment]
Here's the .abapgit.xml for a start:
https://github.com/abapGit/build/pull/1

**Comment by sbcgua** [comment]
Yeah, I'll have a look at build script then

**Comment by sbcgua** [comment]
OK, artifact renaming done. For the tags - I'll be checking it later today. It may be a bit more complicated. Since there are independent auto-tag job and build job ... not sure how to properly unite the results ... probably one more job dependent on the both

**Comment by larshp** [comment]
maybe replace action "peaceiris/actions-gh-pages" with custom logic in the ".sh" script

**Comment by sbcgua** [comment]
it would mean that the `build` must depend on `auto-tag`. But I think that it makes sense to keep build independent: sucessfull commit -> successful build and deploy. I'll check it later today but currently i'm more inclined on the third job that will require both build and tag to complete successfully.

**Comment by sbcgua** [comment]
sadly build-auto-tag failed for 1.118. So waiting for another occasion ...

**Comment by sbcgua** [comment]
@larshp do you mind to toggle another version ? e.g. 1.118 ? Otherwise we will wait till 119 to test it once again. Not a problem either though ...

**Comment by larshp** [comment]
toggle? how to do that?

**Comment by mbtools** [comment]
I will look at your UI changes. How about doing 1.119.0 once they are merged?

**Comment by sbcgua** [comment]
hmmm ... I think #5790 is not good enough for a new version. But maybe #5814 is. 
Anyway, imho, no rush with this.

**Comment by mbtools** [comment]
It worked! https://github.com/abapGit/build/tags

**Comment by sbcgua** [comment]
🎉
