### ISSUE TITLE
Dump on non-unicode systems, UTF-8 marker

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5785]
![image](https://user-images.githubusercontent.com/15635498/193253652-a58b8145-8bd0-47d9-a7e2-12b9a588f4b3.png)
![2022-09-30_11h52_44](https://user-images.githubusercontent.com/15635498/193253681-7728c8f8-09eb-41ec-89c4-3e3f835d82fd.png)
![2022-09-30_11h52_21](https://user-images.githubusercontent.com/15635498/193253691-7f9b0e2f-d665-434d-a8ab-e8a1fdc787aa.png)

Before this exception was completely ignored
![image](https://user-images.githubusercontent.com/15635498/193253922-d5f1e0ef-8060-4b25-8fae-a7d20f4a788b.png)

**Comment by mbtools** [comment]
Not catching the xstring conversion errors led to all sorts of other issues. the calling method needs to handle it.

https://github.com/abapGit/abapGit/blob/16656d8141fdd86734fe9cca1d9748505b4be487/src/xml/zcl_abapgit_xml.clas.abap#L167-L171

Not sure how we can add the byte-mark to a string on non-Unicode systems. If you want to restore the previous behavior, just remove the `assert` (`lv_mark` initial).

**Comment by sbcgua** [comment]
it didn't work. removing re-raising from `zcl_abapgit_convert=>xstring_to_string_utf8` helped. Assert removal solved just part of it. But I didn't dive into it. Non unicode system ... well, they still happen ...
