### ISSUE TITLE
NW 752 SP04: Code Inspector doesn't show dumping unit test

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#5800]
Prerequisites: [plugins](https://github.com/abapGit/abapGit-Plugins) installed
For abapGit repo run:
Advanced > Run Code Inspector > SWF_ABAP_UNIT

Code Inspector result pages shows now findings.
![grafik](https://user-images.githubusercontent.com/17437789/193819360-5f71aca2-f3c3-4a37-9dbc-157311d29113.png)

But actually one unit test fails with a shortdump.
![grafik](https://user-images.githubusercontent.com/17437789/193819881-74825de2-7949-44e7-b0c9-290942fcbd5e.png)
![grafik](https://user-images.githubusercontent.com/17437789/193819922-e30eb85f-fe31-466c-a151-389586308405.png)

Whereas on higher releases the failed unit test is recorded properly. See #5798.

Running unit tests for class ZCL_ABAPGIT_OBJECTS explicitly works as expected.
![grafik](https://user-images.githubusercontent.com/17437789/193820268-d99d7555-fdb6-4cb8-84e5-3a5d6dbce5f8.png)

Not sure whether we can do something about this. At first sight this seems like a bug in standard which is fixed in higher releases.

**Comment by mbtools** [comment]
isn't the point of UTs to catch/prevent dumps? certainly a bug.

**Comment by mbtools** [comment]
SAP issue. suggest closing
