### ISSUE TITLE
unable to create subpackage in Package

### ISSUE THREAD

**Issue by HuprichT** [abapGit/abapGit#5807]
Hi guys, 

i would like to create a Git Repository with one Super package and some subpackages in it. Unfortuantely I am receiving this Error when I try to add a Subpackage: 
![image](https://user-images.githubusercontent.com/45813255/194023507-3e5989b7-5722-4fd8-8ef3-b18bbb0ffa52.png)

These are the Steps which leads to this Error
1. Create Repository in Github
2. Create Online-Repo in abapgit, create the designated Package
3. After that, create a Subpackage in the new created Package
4. During refresh in abapgit, the above mentioned Error occurs.

How can I resolve this?

**Comment by larshp** [comment]
What is your package structure, and what is the repository settings?

See https://docs.abapgit.org/settings-dot-abapgit.html#folder-logic for additional information regarding folder logic/setup

**Comment by HuprichT** [comment]
thanks for the Hint, i changed Folder Logic in the Repo Settings from "Prefix" to "Full", now its working
