### ISSUE TITLE
Object handler for SMBC

### ISSUE THREAD

**Issue by sepp4me** [abapGit/abapGit#5808]
Contribute object handler for R3TR SMBC

**Comment by mbtools** [comment]
Pull requests are welcome and count towards https://hacktoberfest.com/ 😺

**Comment by xtough** [comment]
There is already a JSON-based ABAP File Format for SMBC: https://github.com/SAP/abap-file-formats/tree/main/file-formats/smbc
We should avoid creating 2 formats for the same object type!
