### ISSUE TITLE
CLAS,ENHO: Post methods inactive and empty after repository pull

### ISSUE THREAD

**Issue by simonegaffurini** [abapGit/abapGit#5809]
Hello, I am having issues with a bug, everytime I do these operations I always have to manually re implement everything.
My package X has an online repository.
I created a few enhancements post methods for the classes of my package X in package Y.
When I pull package X, all my enhancements become inactive and the post method is gone.
Can you please try to recreate this scenario and see if it can be fixed?
Thanks

**Comment by mbtools** [comment]
sorry, no one here has time to setup test cases like this. please provide a repo that we can use to reproduce the issue.

**Comment by christianguenter2** [comment]
I can confirm this is a bug. And I had it also occasionally, but somehow forget to file a bug report. Anyhow, as I'm also interested in getting this one fixed (though thinking that won't be an easy one) I prepared two test repos.

First one contains the class.
https://github.com/christianguenter2/CLAS

Second the enhancement enhancing the class via post-exit and implicit source code enhancement.
https://gitlab.com/christianguenter/test_enho_clas

Class looks like this after cloning both repos.
![grafik](https://user-images.githubusercontent.com/17437789/194127793-c5d62b3b-e266-4fad-8f1b-f0deb810fd96.png)

The issue can be reproduced with switching to branch test in the first repo and pull.
Then the post-exit disappeared.
![grafik](https://user-images.githubusercontent.com/17437789/194128009-e65de5fa-8dfe-46c2-8985-4f14b694b5d8.png)

And the enhancement is inactive.
![grafik](https://user-images.githubusercontent.com/17437789/194128097-4b34e3e4-30c3-46d6-945c-b039f7c0699b.png)

After activating the enhancement manually, this diff appears and selective pull recreates the enhancement.
![grafik](https://user-images.githubusercontent.com/17437789/194128291-b1f893ca-1efc-44e3-9fd7-55c54d58947f.png)

Note that the implicit source code enhancement is not affected.

@simonegaffurini is your package Y also managed by abapGit? If yes you can use it to recreate the enhancement.

Some notes which might help fixing the issue
`CL_ENH_FACTORY=>FIND_ENHANCEMENTS` can discover the enhancements

![grafik](https://user-images.githubusercontent.com/17437789/194129834-1eef2db8-751a-407a-8954-d31e9d8ba1d1.png)
![grafik](https://user-images.githubusercontent.com/17437789/194129826-95737140-1131-436d-89ba-f42666ef0965.png)

Whereas `SEO_CLASS_TYPEINFO_GET` just reveals the generated enhancement attribute
![grafik](https://user-images.githubusercontent.com/17437789/194130086-c54bb284-0c34-4224-a4cf-b3d6096c5ed2.png)
![grafik](https://user-images.githubusercontent.com/17437789/194130073-1f2b38e3-bb9f-4e5b-b216-092d17c1139e.png)

**Comment by mbtools** [comment]
Thanks for the examples! It can be reproduced with a single repo by switching between main and test branch:
https://github.com/mbtools/CLAS

Fix coming up

**Comment by larshp** [comment]
@simonegaffurini & @christianguenter2 : can you help testing the fix from @mbtools in https://github.com/abapGit/abapGit/pull/5810 ?

**Comment by simonegaffurini** [comment]
Hello, thank you @christianguenter2 for the test repo and @mbtools  for the fix.
@larshp I tested it and it seems to work fine.
Unless you want to do more tests, this issue can be closed
