### ISSUE TITLE
CDS and generated objects do not work for me

### ISSUE THREAD

**Issue by ojnc** [abapGit/abapGit#5815]
SAPUI5 application Simple SAP Airlines Model from a very comprehensive example by Amit Diwane
https://blogs.sap.com/2020/06/26/sap-abap-programming-model-for-fiori-list-report-application-part-1/
https://blogs.sap.com/2020/06/26/sap-abap-programming-model-for-fiori-list-report-application-part-2/
https://blogs.sap.com/2020/06/26/sap-abap-programming-model-for-fiori-list-report-application-part-3/

Amit Diwane may be currently a SAP India Employee 

I tried to export but import never worked
Reason may be generated objects like the 2 BOPF objects

**If I start from scratch reading the articles thing work ultimately!**

I have success with small hiccups for normal packages but never with $AMITDIWANE
**where less than 10% of the objects written by human effort**

If relevant please see
[https://drive.google.com/drive/folders/1mt_hMirXXLWBIie3YOdDX0TOgL-x6KAt](https://drive.google.com/drive/folders/1mt_hMirXXLWBIie3YOdDX0TOgL-x6KAt)

It has the full export as well as a stripped down version that also fails.

Regards
Jayanta@Kolkata

`8.10.2022            Dynamic List Display                                                                     `

|Obj. Type|Description                                                 |Object Name                             |
|----|----|----|
|BOBF     |BOPF: Business Object Model                                 |ZIDEMO_DDL_SFLIGHT                      |
|BOBF     |BOPF: Business Object Model                                 |ZIDEMO_DDL_SPFLI                        |
|CLAS     |Class (ABAP Objects)                                        |ZCL_AU_IDEMO_DDL_SFLIGHT                |
|CLAS     |Class (ABAP Objects)                                        |ZCL_AU_IDEMO_DDL_SPFLI                  |
|CLAS     |Class (ABAP Objects)                                        |ZCL_A_LOCK_IDEMO_DDL_SFLIGHT            |
|CLAS     |Class (ABAP Objects)                                        |ZCL_A_LOCK_IDEMO_DDL_SPFLI              |
|CLAS     |Class (ABAP Objects)                                        |ZCL_D_IDEMO_DDL_SFLIGHT_ACTION          |
|CLAS     |Class (ABAP Objects)                                        |ZCL_D_IDEMO_DDL_SPFLI_ACTION_A          |
|CLAS     |Class (ABAP Objects)                                        |ZCL_IDEMO_A_COPY                        |
|CLAS     |Class (ABAP Objects)                                        |ZCL_IDEMO_D_CALCULATEKEYVALUES          |
|CLAS     |Class (ABAP Objects)                                        |ZCL_IDEMO_V_VALIDATECOUNTRY             |
|DDLS     |Data Definition Language Source                             |ZDEMO_DDL_SCURX                         |
|DDLS     |Data Definition Language Source                             |ZDEMO_DDL_SFLIGHT                       |
|DDLS     |Data Definition Language Source                             |ZDEMO_DDL_SPFLI                         |
|DDLS     |Data Definition Language Source                             |ZIDEMO_DDL_SFLIGHT                      |
|DDLS     |Data Definition Language Source                             |ZIDEMO_DDL_SPFLI                        |
|DDLX     |CDS metadata extension                                      |ZXDEMO_DDL_SFLIGHT                      |
|DDLX     |CDS metadata extension                                      |ZXDEMO_DDL_SPFLI                        |
|INTF     |Interface (ABAP Objects)                                    |ZIF_IDEMO_DDL_SFLIGHT_C                 |
|INTF     |Interface (ABAP Objects)                                    |ZIF_IDEMO_DDL_SPFLI_C                   |
|IWMO     |SAP Gateway Business Suite Enablement - Model               |ZDEMO_DDL_SFLIGHT_CDS           0001    |
|IWMO     |SAP Gateway Business Suite Enablement - Model               |ZDEMO_DDL_SPFLI_CDS             0001    |
|IWOM     |SAP Gateway: Model Metadata                                 |ZDEMO_DDL_SFLIGHT_CDS_0001_BE           |
|IWOM     |SAP Gateway: Model Metadata                                 |ZDEMO_DDL_SPFLI_CDS_0001_BE             |
|IWSG     |SAP Gateway: Service Groups Metadata                        |ZDEMO_DDL_SFLIGHT_CDS_0001              |
|IWSG     |SAP Gateway: Service Groups Metadata                        |ZDEMO_DDL_SPFLI_CDS_0001                |
|IWSV     |SAP Gateway Business Suite Enablement - Service             |ZDEMO_DDL_SFLIGHT_CDS              0001 |
|IWSV     |SAP Gateway Business Suite Enablement - Service             |ZDEMO_DDL_SPFLI_CDS                0001 |
|IWVB     |SAP Gateway Business Suite Enablement -Vocabulary Annotation|ZDEMO_DDL_SFLIGHT_CDS_VAN       0001    |
|IWVB     |SAP Gateway Business Suite Enablement -Vocabulary Annotation|ZDEMO_DDL_SPFLI_CDS_VAN         0001    |
|MSAG     |Message Class                                               |ZBOPF                                   |
|SICF     |ICF Service                                                 |A4H00100000000100O2TMQPDL0AXGC2ZZH2Y8XW1|
|SICF     |ICF Service                                                 |A4H00100000000200O2TMQPDL0AXGC2ZZH2Y8XW1|
|STOB     |Structured Object                                           |ZDEMO_DDL_SCURX                         |
|STOB     |Structured Object                                           |ZDEMO_DDL_SFLIGHT                       |
|STOB     |Structured Object                                           |ZDEMO_DDL_SPFLI                         |
|STOB     |Structured Object                                           |ZIDEMO_DDL_SFLIGHT                      |
|STOB     |Structured Object                                           |ZIDEMO_DDL_SPFLI                        |
|SUSH     |Assignment: Service --> Authorization Objects               |9C0E06124657F929D9761B7BCEE830HT        |
|SUSH     |Assignment: Service --> Authorization Objects               |B03E664206AEF8E017FBAB149A2A37HT        |
|TABL     |Table                                                       |ZSIDEMO_DDL_SFLIGHT                     |
|TABL     |Table                                                       |ZSIDEMO_DDL_SFLIGHT_D                   |
|TABL     |Table                                                       |ZSIDEMO_DDL_SPFLI                       |
|TABL     |Table                                                       |ZSIDEMO_DDL_SPFLI_D                     |
|TABL     |Table                                                       |ZSK_IDEMO_DDL_SFLIGHT_DB_KEY            |
|TABL     |Table                                                       |ZSK_IDEMO_DDL_SPFLI_DB_KEY              |
|TTYP     |Table Type                                                  |ZTIDEMO_DDL_SFLIGHT                     |
|TTYP     |Table Type                                                  |ZTIDEMO_DDL_SPFLI                       |
|TTYP     |Table Type                                                  |ZTK_IDEMO_DDL_SFLIGHT_DB_KEY            |
|TTYP     |Table Type                                                  |ZTK_IDEMO_DDL_SPFLI_DB_KEY              |
|VIEW     |View                                                        |YDEMO_FLIGHT                            |
|VIEW     |View                                                        |YDEMO_SCURX                             |
|VIEW     |View                                                        |YDEMO_SPFLI                             |
|VIEW     |View                                                        |YIDEMO_SFLIGHT                          |
|VIEW     |View                                                        |YIDEMO_SPFLI                            |

**Comment by mbtools** [comment]
BOPF is not supported by regular AG (https://github.com/abapGit/abapGit/issues/165). 

You can try using the AG plug-in https://github.com/abapGit/abapGit-Plugins (install in addition to AG).

**Comment by ojnc** [comment]
IF I toggle **@OData.publish: true** and **@OData.publish: false** should not the problem get solved?
For me it does not.
_**Any solutions would be a great help!**_

 I think if you can advise a minimal manual intervention solution it would be a great help.
 
 **A section in your docs on trouble shooting and workarounds would also be welcome.
As well as traps and pitfall areas to avoid!**

Regards
Jayanta

**Comment by mbtools** [comment]
AG is completely built and maintained by a few people in their spare time for free. 

If someone pays me for this kind of work, I'm happy to spend time on particular issues or documentation. 😀 

PS: GitHub has an easy-to-use sponsor button

**Comment by ojnc** [comment]
Your team can write a page on traps and pitfalls and disclaimersc.
Telling about the **traps and pitfalls upfront** means you save your enthusiastic users a lot of time.
Paul Hardy in his book has a chapter - no warnings!!

Same with Eclipse ADT; SE24 SE11 beats ADT by 100 miles!

BTW I love ATD and abapgit but have learnt the ropes, the good parts and bad parts the hard way!

Regards
Born again old ABAPer 
Jayanta

**Comment by mbtools** [comment]
Closing in favor of https://github.com/abapGit/docs.abapgit.org/issues/66
