### ISSUE TITLE
Cross dependency impacts abapgit for me

### ISSUE THREAD

**Issue by ojnc** [abapGit/abapGit#5816]
I am using abapgit for now almost 10 months
More as personal tool rather than evangelist!
Great help for me and will serve me well as next 4 years I may be more mentoring!

Have discovered that this process below I now follow 
is 100% glitch free as there may be _impact of cross dependency_  with many changes

After 1st time import if I need to re-import I go to Advanced and Uninstall.
Recreate off-line zip repository and then import and pull.

Works very well with my small repositories
as also large complex packages like ABAPGIT and ABAP2XLSX - almost always painless.

I encountered CDS cyclic dependency even in BLOGS examples
https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-us/abenddic_cds_cycle_problems.htm

Punch line in above link "This would have to be done in every target system of a transport."

Regards
Jayanta@Kolkata

**Comment by mbtools** [comment]
A complex topic. There's a bit more about it in https://github.com/abapGit/abapGit/issues/5524

**Comment by ojnc** [comment]
CDS cycles are complex I agree.
 
But in abapgit package itself one should **update by standalone** and not the tcode ZABAPGIT
as crash can happen midway when the underlying classes etc half way updated.
This if explicitly advised would save puzzled users who wish to pull the latest!
I discovered the hard way.

Regards
Jayanta@Kolkata

**Comment by larshp** [comment]
can we close this issue? https://github.com/abapGit/abapGit/issues/5524 is open for cyclic CDS

**Comment by ojnc** [comment]
**Yes! Please Close this.**
I found out the monolithic ZABAPGITSTANDALONE works fine.
Also for ABAPGIT I uninstall and reinstall after a few weeks,
The new version of ABAPGIT gets installed painlessly'

ABAPGIT is my favourite discovery.
Serves my requirements well.

Regards
Jayanta
