### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by simonegaffurini** [abapGit/abapGit#5820]
Hello, I am suddenly experiencing a blank screen when running the zabapgit transaction.
The latest build report works fine, in fact I pulled the last release from it just to be sure I was up to date, however I still can't see anything when running the transaction.
The HTML source is empty
![image](https://user-images.githubusercontent.com/87023474/195425832-6dd62137-db88-42d1-9968-c4e51f7e6517.png)
I tried debugging just to be sure it was none of my exit class methods and there are no calls when creating the screen.
Also tried uninstalling and installing everything from the standalone report.
Has this ever happend? I don't think there's any way to let you reproduce the issue.
Any tips?

**Comment by mbtools** [comment]
Odd. Can you download v1.117.0 from https://github.com/abapGit/abapGit/releases/tag/v1.117.0 and try that?

**Comment by mbtools** [comment]
Also attach the output of Repo Overview > Utilities > Debug Info 

![image](https://user-images.githubusercontent.com/59966492/195469764-0b7771c2-3e10-46ce-a004-806dd3703fc2.png)

**Comment by simonegaffurini** [comment]
Hi @mbtools I tried downgrading to 1.117.0 and I still get the same blank screen with <HTML></HTML>.
I cannot open Debug Info of the developer version because there's no way to access it, but I can open it from the standalone version. This is debug info for the standalone:
<HTML lang="en"><HEAD> 
          <LINK href="css/bundle.css" rel="stylesheet" type="text/css">   </HEAD><BODY class="centered"><DIV class="not_sticky"><DIV class="debug_container" id="debug_info"><H2>Environment</H2><TABLE><TBODY><TR><TD>abapGit version:</TD><TD>1.118.0</TD></TR><TR><TD>XML version:    </TD><TD>v1.0.0</TD></TR><TR><TD>GUI version:    </TD><TD>7600.1.3</TD></TR><TR><TD>APACK version:  </TD><TD>1</TD></TR><TR><TD>LCL_TIME:       </TD><TD>1665648086 +0000</TD></TR><TR><TD>SY time:        </TD><TD>20221013 100126 3600</TD></TR><TR><TD>SY release:     </TD><TD>756 SP 0000000002</TD></TR></TBODY></TABLE><BR><P><TABLE><TBODY><TR><TD>Browser:</TD><TD>Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko</TD></TR><TR><TD>Frontend time:</TD><TD>Thu Oct 13 2022 10:01:25 GMT+0200 (ora legale Europa occidentale)</TD></TR></TBODY></TABLE><P></P></DIV><DIV class="debug_container" id="exit_info"><H2>User Exits</H2><DIV>No user exits implemented (include ZABAPGIT_USER_EXIT not found)</DIV></DIV></DIV></BODY></HTML>

**Comment by simonegaffurini** [comment]
Actually, notice the log says **include ZABAPGIT_USER_EXIT not found** which is not true, I do have a user exit.
So what I did was delete the user exit class and now the developer version works.
I'd like to help find the bug causing this, so if you think I should debug in any specific point let me know, otherwise I can close the issue and find what the problem with my exit is.

**Comment by mbtools** [comment]
Great. Just in general, you might want to update you SAP GUI since 760 patch 1 is very old.
