### ISSUE TITLE
Disable "experimental" feature for stand-alone version

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5827]
The "experimental mode" and "run critical unit tests" are not visible in the Personal Settings dialog of the stand-alone version but are still effective if turned on using the developer version. 

Disable the "experimental mode" and "run critical unit tests" during *runtime* of the stand-alone version. 

Code for setting maintenance:

https://github.com/abapGit/abapGit/blob/c90ec52c4275019231c9db9c1971a2e31e3c95cf/src/ui/zcl_abapgit_gui_page_sett_glob.clas.abap#L162-L172

**Comment by marcushoepfner** [comment]
> Originally, stand-alone also showed the experimental mode. However, per definition, these features are not stable. They are meant for developers enhancing abapGit and therefore should be effective only in the developer version (where you can debug them in a sensible way as well).

+1
