### ISSUE TITLE
Create missing test cases for CI

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5829]
Test org (https://github.com/abapGit-tests) is missing repos for the following object types supported by abapGit:

- [x] CMPT - Code Composer Template
- [x] CUS2 - Customizing Attributes
- [x] DIAL - Dialog Module
- [x] DOCV - Documentation (Independent)
- [x] ECSD - eCATT System Data Container (in [ECATT](https://github.com/abapGit-tests/ECATT))
- [x] ECSP - eCATT Start Profile (in [ECATT](https://github.com/abapGit-tests/ECATT))
- [x] ECTC - eCATT Test Configuration (in [ECATT](https://github.com/abapGit-tests/ECATT))
- [x] ECTD - eCATT Test Data Container (in [ECATT](https://github.com/abapGit-tests/ECATT))
- [x] ECVO - eCATT Validation Object (in [ECATT](https://github.com/abapGit-tests/ECATT))
- [x] ENHS - Enhancement Spot
- [x] ENSC - Composite Enhancement Spot
- [x] G4BS - SAP Gateway OData V4 Backend Service (in [G4BA](https://github.com/abapGit-tests/G4BA))
- [x] IAMU - Language-Independent IAC Binary Data (in [IARP_IASP_IATU_IAMU](https://github.com/abapGit-tests/IARP_IASP_IATU_IAMU))
- [x] IASP - Parameters of an IAC service (in [IARP_IASP_IATU_IAMU](https://github.com/abapGit-tests/IARP_IASP_IATU_IAMU))
- [x] IATU - Language-Independent IAC Templates (in [IARP_IASP_IATU_IAMU](https://github.com/abapGit-tests/IARP_IASP_IATU_IAMU))
- [x] IWMO - SAP Gateway Business Suite Enablement - Model (in [IWSV_IWSG_IWMO_IWOM](https://github.com/abapGit-tests/IWSV_IWSG_IWMO_IWOM))
- [x] IWOM - SAP Gateway: Model Metadata (in [IWSV_IWSG_IWMO_IWOM](https://github.com/abapGit-tests/IWSV_IWSG_IWMO_IWOM))
- [x] IWSG - SAP Gateway: Service Groups Metadata (in [IWSV_IWSG_IWMO_IWOM](https://github.com/abapGit-tests/IWSV_IWSG_IWMO_IWOM))
- [x] JOBD - Technical Job Definition
- [x] PRAG - Pragma in ABAP Source Code
- [x] SAMC - ABAP Messaging Channels
- [x] SAPC - ABAP Push Channels
- [x] SFPI - Form Object: Interface (in [SFPF](https://github.com/abapGit-tests/SFPF))
- [x] SHI8 - SFW Switch Assignment in Hierarchy Tool (in [SFSW_SHI8](https://github.com/abapGit-tests/SFSW_SHI8))
- [x] STYL - SAPscript Style
- [x] TOBJ - Definition of a Maintenance and Transport Object
- [x] UCSA - Unified Connectivity Service Assembly
- [x] W3HT - Web Reporting/Internet Transaction Server HTML Templ.

**Comment by g-back** [comment]
Could you create a repo for STYL?

**Comment by larshp** [comment]
@g-back I've invited you to the organization

**Comment by christianguenter2** [comment]
For ecatt objects 
ECAT
ECSD
ECSP      
ECTC
ECTD   
ECTD     
ECVO
we have https://github.com/abapGit-tests/ECATT.git I think that's sufficient?

**Comment by christianguenter2** [comment]
SFPI is part of https://github.com/abapGit-tests/SFPF. Imho it's sufficient as I see no advantage in having a separate test repo.

**Comment by mbtools** [comment]
Goes both ways: repos with several object type make debugging harder and runtime longer. But you also might expose dependency issues. 

In general, each object type should have its own test (esp for new types) but don't worry creating ones for the cases you mentioned.

**Comment by fabianlupa** [comment]
CMPT -> https://github.com/abapGit-tests/CMPT

**Comment by mbtools** [comment]
I created the missing test cases. We now have full test coverage for all object types supported by abapGit. 🥳 

FYI, UCSA can only be created in special systems so I had to fool my sap system (UCONFILLCUST-ALLOW_CREATION = 'X').
