### ISSUE TITLE
Set one default transport for all pulled packages

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5833]
Is there a way in AG (user exit?) to set one default transport for all pulls system-wide ?

My use-case: a standalone dev system, no transportation needed. All developers create their transports which, with time, start to conflict between each other. So idea is to force (as much as possible) to use one single transport for all users, to quickly release it when conflicts are unbearable.

If there is no such a feature, maybe create one ? as a setting or a user exit ?

P.S. maybe I'm inventing a bicycle ... Is there a way to completely disable **workbench** transports in a given system ?
P.P.S. option is to use $ package names. But it has some stupid issues with unit tests - I cannot right click unit test the whole $ package (!?!?!), also there are some weird messages about master language and I don't want to experiment with this on our multilanguage developments for clients.

**Comment by mbtools** [comment]
It should be $-packages and SAP should fix the issues you mentioned...

An exit makes sense for another reason: The transport popup is disrupting the flow and it would be nice to have the transport determined by code instead.

**Comment by goreraks** [comment]
May be the menu Standard Request under Utilities might be helpful here.
You can set a Transport as Standard Request so that any lockable/not lockable objects are recorded under that Transport only.

**Comment by larshp** [comment]
$ package names unit tests: the abapgit unit test feature can be used?

![image](https://user-images.githubusercontent.com/5888506/202887315-e300dd29-0a1a-4c3a-a22f-e568adb8a956.png)

**Comment by sbcgua** [comment]
Cool ! 🎉 Thank again @christianguenter2
