### ISSUE TITLE
Performance optimization on abapGit Stage/fetch_remote()

### ISSUE THREAD

**Issue by voidsteed** [abapGit/abapGit#5844]
Hi all,

One of my organization's current SAP package has more than 5000 Z-Objects, and we only one root package with no sub packages. 

We are using abapGit to sync to Azure DevOps. Majority of time is using it for one-way sync. I'm currently using zcl_abapgit_factory=>get_stage_logic( )->get( io_repo = lo_repo_online ii_obj_filter = lo_obj_filter_trans ) with an object filter thanks to #5054  The serialization time is way shorter than before. 

But when I was looking into get() implementation I saw the second step is io_repo->get_files_remote(), in this step, it uses the object filter too, but no matter what, it will always call the fetch_remote() method and it takes around 20-30 seconds for me since we have 5000+ object. Is it possible to just pull selected files instead of fetch_remote all the files in abapGit. If it is possible, could you share some sample code that I can play around? By the way, I'm using abapGit developer version and API programmatically.

Thanks!

**Comment by larshp** [comment]
currently abapGit uses git v1, which does not support filtering when pulling files

plan is to implement https://github.com/abapGit/abapGit/issues/2215

**Comment by voidsteed** [comment]
Thanks for the reply. Is it possible to improve performance on get_files_remote() or fetch_remote()? I already have the object filter.

**Comment by larshp** [comment]
yes, its possible, just requires work

**Comment by mbtools** [comment]
Fetch downloads the complete repo. Check if there are large typically binary files in folders unrelated to abapGit (outside of /src) and move those to another repo. 

Other than that as Lars wrote we need a port of v2 to ABAP.  Happy to test if you or your company implement it (can be independent of abapGit and we will integrate after).
