### ISSUE TITLE
Remove filter autofocus at repo overview

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5846]
Having that repo overview is quite an interactive page with multiple keyboard shortcuts, table navigation and etc., forced filter field autofocus on first display is very inconvenient. Filtering is by far not the most probable action after AG start.
If no-one objects I'll remove the autofocus and add a key-combination to focus it intentionally.
As a final touch to #5781

**Comment by mbtools** [comment]
agree

**Comment by sbcgua** [comment]
to fix after #5814

**Comment by sbcgua** [comment]
pls check #5859
