### ISSUE TITLE
UI - Repository List - Dark Theme broken in Version 1.118.0 

### ISSUE THREAD

**Issue by NeumannJoerg** [abapGit/abapGit#5848]
The dark theme seems to be broken in Version 1.118.0.
The background of the table used to be grey but is now white.
This makes it rather hard to read the text.

OLD:
![OLD](https://user-images.githubusercontent.com/86975244/199495431-33b400fa-d6d1-4e7c-b21c-8b97ccd94a73.png)

NEW:
![NEW](https://user-images.githubusercontent.com/86975244/199495486-6ecd6969-9300-4f71-95b4-bdd2e4f460f4.png)

To reproduce the issue, the dark mode must be activated under "Settings" -> "Personal" -> "User  Interface" -> "Theme".
![Settings](https://user-images.githubusercontent.com/86975244/199496809-f0299e01-e6b5-4314-92ac-fdda31e3c6b5.png)

**Comment by sbcgua** [comment]
@NeumannJoerg pls check #5859

**Comment by NeumannJoerg** [comment]
@sbcgua I just pulled the latest developer version, but that did not solve the issue.
The table background is still white.

**Comment by sbcgua** [comment]
The #5859 is not merged into the main branch yet, try to switch to that particular PR. (e.g. via the remote settings https://docs.abapgit.org/settings-remote.html)

**Comment by NeumannJoerg** [comment]
#5859 solves the issue, but I found another one.

The labels of all non-highlighted buttons seem to have the same color like the background.

![Dark Theme](https://user-images.githubusercontent.com/86975244/200292978-04ea8de1-17b7-4ceb-8a45-52ed999a26d4.png)

![Default Theme](https://user-images.githubusercontent.com/86975244/200292993-9d6f7c15-b031-45d6-af08-ceeb9a6eb7b4.png)

Do you want to handle this with this issue, or should I create a new one?

**Comment by sbcgua** [comment]
Hmm, are you sure you're using the right branch ? One more idea is that: are you using Chrome html control or explorer (I'm using Explorer - it seems to work)
![image](https://user-images.githubusercontent.com/15635498/201473052-408b186f-dfc6-401d-8cbe-5f818562fc8e.png)

**Comment by NeumannJoerg** [comment]
Hi,

I just re-pulled PR #5859 just to be sure.
Using the value-help, 5859 got resolved into this url: https://github.com/sbcgua/abapGit.git@ro-page/polishing

My SAP Gui is using Edge.
I just switched to Internet Explorer and now it works!

So the button-related issue seems to be edge-specific.
