### ISSUE TITLE
DOCV: Error "Separator '/' for namespace not paired or in wrong position"

### ISSUE THREAD

**Issue by abap-weasel** [abapGit/abapGit#5854]
We have just updated from abapgit 1.116 to latest 1.118 and now have an error in ZIP export.

There is an uncatched exception DELIMITER_ERROR of function RS_NAME_SPLIT_NAMESPACE in ZCL_ABAPGIT_OBJECT_DOCV that is being raised:
https://github.com/abapGit/abapGit/blob/93c8fcfb4fc514c80dc8728a5304c64a6adc55cd/src/objects/zcl_abapgit_object_docv.clas.abap#L50-L55

Error Message: e233(EU) "Separator '/' for namespace not paired or in wrong position"
While other calls of that function in  abapGit handle that exception, just doing that will probably not fix the issue for us.

The object are in our namespace and RS_NAME_SPLIT_NAMESPACE is called with name_with_namespace = "UO/NAMESPACE/NAME".  Probably that function needs to be changed as it cannot handle names of DOCV in a namespace with additional characters before /namespace/ ?

**Comment by mbtools** [comment]
It's a regression off https://github.com/abapGit/abapGit/pull/5756

Apparently, namespaces are handled differently by different document class. The logic is correct for `DT` but not for `UO`. Do you have namespaced objects in document classes `IN`, `MO`, or `UP`? If yes, what's their `tadir` entry?

**Comment by abap-weasel** [comment]
Unfortunately we don't have them. I found some for MO coming from SAP S/4HANA directly, if that helps:
R3TR	DOCV	MOEXIT_/SAPAPO/SAPLEDI1_001

**Comment by mbtools** [comment]
The MO example is not really a namespaced document. It's a description for customer exit in function group /SAPAPO/SAPLEDI1. So the f.group has a namespace but the document does not (but has `/` in the name)... SAP 🤷 I will change the PR to handle MO and IN like UO.

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/pull/5855 is ready for a test
