### ISSUE TITLE
abapGit install fails

### ISSUE THREAD

**Issue by JanTristanH** [abapGit/abapGit#5867]
Hello abapGit Team,

I'm trying to initially install abapGit version `1.118.0 (Standalone Version)` on a S/4HANA system with SAP_BASIS version 756.
The program starts fine, but when I try to click any button, I see the following message:

![image](https://user-images.githubusercontent.com/53378180/201280821-8e153031-61fe-4060-bc77-4689e2167d28.png)

This is true for all other actions as well (Different unknown actions, of course). `Goto Source` and `Callstack` links also not working.

What are the next troubleshooting steps I could take? Any help would be appreciated, thank you.

Best regards
Tristan

**Comment by christianguenter2** [comment]
What SAPGUI version do you use?
Make sure to use Internet Explorer Browser Control.
![grafik](https://user-images.githubusercontent.com/17437789/201289119-0d55e44b-b543-4ce7-a9a4-e6c980447a8a.png)

**Comment by JanTristanH** [comment]
Hi Christian,
Thank you very much for your fast reply. Changing the Browser Control already solved the issue 😄

**Comment by mbtools** [comment]
Ref https://github.com/abapGit/abapGit/issues/4841
