### ISSUE TITLE
incompletely generated objects

### ISSUE THREAD

**Issue by stud0709** [abapGit/abapGit#5870]
up to v116, there is a phenomenon that an object is not restored completely. You have to trigger an overwrite of the object as step 2 to have it restored completely. 

So far, I have seen it in transparent tables (foreign keys were missing) and classes (class was created empty at first).

**Comment by larshp** [comment]
@stud0709 can you help reproducing the issue?

**Comment by stud0709** [comment]
![2022-11-15_09h01_29](https://user-images.githubusercontent.com/31960113/201862818-47955f68-649f-4b3d-aaaa-c1b7bde8e62d.png)

I'll try... here's at least a screenshot - remote to the right - DD05M_TABLE is missing entirely. This is an offline repository.

**Comment by mbtools** [comment]
There have been several related fixes. Please always test with the latest version. TY

**Comment by mbtools** [comment]
stale. closing
