### ISSUE TITLE
classes activated despite errors in code

### ISSUE THREAD

**Issue by stud0709** [abapGit/abapGit#5871]
as of v.118, classes are activated despite errors in code (in my case, the exception class was not present in the target system). The IDE will show you the error if you open the file, but it is active.

**Comment by larshp** [comment]
abapGit pulls classes to active state, you can trigger the syntax check via

also make sure to setup static analysis on the git repository to make sure it has all objects, ie. checking consistency before import to a real system

![image](https://user-images.githubusercontent.com/5888506/201864069-4ab5c83a-a1a2-4e37-83d3-40ec6cdbb42c.png)

**Comment by stud0709** [comment]
thank you, I'll try it out
