### ISSUE TITLE
ABAPGit - Issue with import files from local 

### ISSUE THREAD

**Issue by IbrahimProg** [abapGit/abapGit#5877]
I'm trying to import project from local machine into SAP system using abapGit, but the main problem after imported I did not find the file, I followed the instructions which mentioned in website's ABAPGit but not work out.

**Comment by larshp** [comment]
does it display any errors?
how can the issue be reproduced, can you reproduce it with a ZIP file that you can share?
are you running the latest version?

**Comment by IbrahimProg** [comment]
No, there is no any error after imported, just jump into this window in below:
![abapGit](https://user-images.githubusercontent.com/45215606/202988427-2b19cb51-2f4d-4616-9e77-ff04bdc13bea.PNG)

**Comment by larshp** [comment]
which files are in the zip file, how did you retrieve/create it?

**Comment by IbrahimProg** [comment]
I imported from new offline repository:

![image](https://user-images.githubusercontent.com/45215606/202989278-00a5afed-35d0-4160-8a70-c0c6efc0fb20.png)

these files, which I'm trying imported from ZIP file:
![image](https://user-images.githubusercontent.com/45215606/202989685-0305ab6d-2ed9-4b18-a60e-40616b2f3a1f.png)

**Comment by larshp** [comment]
ok, the zip file does not follow the abapGit format

there must be a [.abapgit.xml](https://github.com/abapGit/abapGit/blob/main/.abapgit.xml) file to specify where the code is located

see https://github.com/abapGit/abapGit/archive/refs/heads/main.zip as an example

**Comment by IbrahimProg** [comment]
Its working now, thank you for your support!!
