### ISSUE TITLE
Usage of `cl_oo_source`

### ISSUE THREAD

**Issue by schneidermic0** [abapGit/abapGit#5895]
abapGit uses class `cl_oo_source`. This class has a predecessor with interface `if_oo_clif_source` and a new implementation starting with release 7.31. This interface is used by abapGit, too.

Since `cl_oo_source` is obsolete in new releases, I want to delete it in one of the upcoming SAP releases. 

I found following usages which are needed in release 7.02:

- https://github.com/abapGit/abapGit/blob/bf5199b8d2284fa7c664884d5c54c239cd0b9210/src/apack/zcl_abapgit_apack_migration.clas.abap#L92
- https://github.com/abapGit/abapGit/blob/c63d92e6f1dafd5565b6009c0da5bcb97195d612/src/objects/oo/zcl_abapgit_oo_serializer.clas.abap#L254
- And one comment ;) https://github.com/abapGit/abapGit/blob/c63d92e6f1dafd5565b6009c0da5bcb97195d612/src/objects/oo/zcl_abapgit_oo_serializer.clas.abap#L175

Can we replace the usages of `cl_oo_source` with dynamic calls?

**Comment by larshp** [comment]
yea, pull requests welcome

just make sure stuff still works on 702

**Comment by schneidermic0** [comment]
> - And one comment ;) https://github.com/abapGit/abapGit/blob/c63d92e6f1dafd5565b6009c0da5bcb97195d612/src/objects/oo/zcl_abapgit_oo_serializer.clas.abap#L175

The comment will be still valid after the refactoring. Therefore, I would keep it.
