### ISSUE TITLE
abap2xlsx: cannot activate Transformations, yet their status is active

### ISSUE THREAD

**Issue by kamilmirza** [abapGit/abapGit#5898]
as per title Transformations from abap2xlsx are in Inactive Object list yet their status is Active 
ABAP 7.40 SP 13
abapGit 1.119.0

![image](https://user-images.githubusercontent.com/6561475/204600739-39d1bccf-37a1-414e-9397-98c609e8ee08.png)
![image](https://user-images.githubusercontent.com/6561475/204602232-63285cad-f06e-41f7-aef8-c3e8a8a5ee7b.png)

upon activation, it says Activated but stays Inactive and their status remains Active

![image](https://user-images.githubusercontent.com/6561475/204602048-baa07567-cf8d-4f25-a0ac-ae5e4781042b.png)
![image](https://user-images.githubusercontent.com/6561475/204601659-dc64bd77-b528-4a94-8e27-ba8a27cf15bc.png)
![image](https://user-images.githubusercontent.com/6561475/204601790-8387e609-3f9d-44b3-9a0b-885962e8b702.png)
![image](https://user-images.githubusercontent.com/6561475/204601877-cd400717-413e-45b7-862b-646d5cbda971.png)

**Comment by kamilmirza** [comment]
found this SAP Note: [2859159](https://launchpad.support.sap.com/#/notes/2859159) from [here](https://github.com/abapGit/abapGit/issues/5262#issuecomment-1012426663)
maybe this will be useful?

**Comment by mbtools** [comment]
yes, that's the correct note.

**Comment by kamilmirza** [comment]
> yes, that's the correct note.

thanks
I'll ask my BASIS guy and will report back

**Comment by kamilmirza** [comment]
my BASIS guy said that this note cannot be Implemented on our system 😞
what now? 

![image](https://user-images.githubusercontent.com/6561475/206675526-0a1778e2-5d72-44bd-9ac3-117d11d55677.png)

![image_2022_12_06T05_36_59_684Z](https://user-images.githubusercontent.com/6561475/206675624-9b87c712-8d8f-402d-b3a1-96d65dda362c.png)

**Comment by mbtools** [comment]
the note is valid for 7.40 SP 21 to 23 (and included in SP 24). So either you ask SAP to downport it to SP 13 (unlikely but you could try) or you update your system to at least SP 21. Theoretically, you could implement the changes manually but it's quite a lot of work.

**Comment by mbtools** [comment]
stale. closing
