### ISSUE TITLE
Filter to select all labeled and all unlabeled repos

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#5904]
Idea: `label:*` should display all labeled repos, and `label:!` all unlabeled.

Not sure how to represent it in UI ... as no labels at all would hide label filter completely. Also it does not seem as a very frequent feature. I guess "?" help should be sufficient

**Comment by mbtools** [comment]
Maybe add "all" and "none" labels as defaults (unless there are no labels defined at all).

**Comment by sbcgua** [comment]
I wanted to avoid lettered names. Just in case the are used for real labels. Although i can hardly imagine real labels with these names ... hmmm
