### ISSUE TITLE
Offline repo with "ignore sub-packages"

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5924]
Offline repos do not have the option to ignore sub-packages

Offline:

![image](https://user-images.githubusercontent.com/59966492/206527291-22751cdb-13fd-4de4-8f0b-995f1814d2a4.png)

Online:

![image](https://user-images.githubusercontent.com/59966492/206527433-af204b75-4c50-4e72-8715-180d629520f6.png)

Is there any particular reason why this is missing?

**Comment by larshp** [comment]
I dont think so
