### ISSUE TITLE
Closing hotkeys popup with escape key

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5926]
If you press `escape` when showing the hotkeys popup, AG exits the current screen (browser back) instead of closing just the popup. 

![image](https://user-images.githubusercontent.com/59966492/206592632-406b2e82-b172-4476-91dd-38cce1faf437.png)

**Comment by sbcgua** [comment]
if I remember well (but not sure ... it was to long ago), esc is not catched within the JS, because SAP GUI processes it first. Just the matter of processing order.

Maybe try tacking this issue again, but if I remember well it was the real reason of the "Close window with ..." comment on top

**Comment by mbtools** [comment]
You mentioned it in https://github.com/abapGit/abapGit/pull/2897. 

Does not seem to be possible to capture Escape key. It's always handled by the SAP control.
