### ISSUE TITLE
DRUL: Test fails

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#5932]
https://github.com/abapGit-tests/DRUL fails in ABAP Dev Edition 

Changes from https://github.com/abapGit/abapGit/pull/5818 do not work in 7.54

![image](https://user-images.githubusercontent.com/59966492/207205817-298bade8-2f9e-4192-9ecc-4e879401ed72.png)

![image](https://user-images.githubusercontent.com/59966492/207205880-07608c91-74de-4b4c-a4e9-7fc786bebc99.png)

![image](https://user-images.githubusercontent.com/59966492/207205790-32b39a95-9da1-44f2-8a51-69d263e014ed.png)

**Comment by mbtools** [comment]
@uenal-akkaya our test repo fails after your change. Could you please have a look?

**Comment by mbtools** [comment]
@uenal-akkaya 
The test repo fails also with `cl_blue...2`. 
https://github.com/abapGit-tests/DRUL

![image](https://user-images.githubusercontent.com/59966492/208522297-6742ff22-3b14-49e0-aa50-53f97c7e7dd1.png)

Here's the statement that fails during deserialize:

![image](https://user-images.githubusercontent.com/59966492/208521888-17ccb5ca-d13a-4957-b607-e4b77570279f.png)

-  `i_object_data` is type `cl_blue_source_object_data2`
-  `l_object_data` is `ty_object_data_ref` which is:

```abap
    types:
      ty_object_data_ref type ref to cl_drul_wb_object_data.
```

Should we revert to `cl_drul_wb_object_data`?

**Comment by uenal-akkaya** [comment]
Is the new failing test from the current release or also from 7.54?

**Comment by mbtools** [comment]
7.54 SP 2

**Comment by larshp** [comment]
@mbtools did this work out?
