### ISSUE TITLE
dump in ZABAPGIT points back to standalone version

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#5937]
Two systems, SR2 and SR3, both used for development and with a long history before abapGit.
One of them (SR3) works normally, that is I can download the standalone report, use it to pull in the dev version, run the transaction and navigate to the aG repository: takes a while to rebuild but the list is shown and objects are up to date.
The other (SR2) dumps when I try to use the dev version to navigate to the aG repo, where I get this error:
` It was tried to call a not-implemented method "ZIF_ABAPGIT_REPO_CHECKSUMS~GET" in the class "ZCL_ABAPGIT_REPO_CHECKSUMS".
`
The interesting part is that navigating the source code from ZCL_ABAPGIT_REPO_CHECKSUMS to zif_abapgit_repo_checksums~get( ), I end up in the corresponding class of the standalone version, however this happens on both systems so I don't know what to make of it.
Tried removing the dev version and the standalone then starting again, tried also regenerating the navigation index at the package level and I've even tried regenerating the checksums via the Advanced menu, no go.

Info: SAP_ABA  
SR2: SAPKA73105
SR3: SAPKA74004

**Comment by mbtools** [comment]
Since https://github.com/abapGit/abapGit/pull/5328 checksums are persisted in a new format. At first start, the old format is migrated to the new one. If you use both standalone and dev versions in the same system, this might have caused the problem if one version expected migrated data and the other did not.

For a fresh start, use the standalone version and drop the `REPO` and `REPO_CS` entries (new checksum format). Then create a new repo for the dev version and pull.

**Comment by AndreaBorgia-Abo** [comment]
The standalone version is also freshly updated (today) on both systems but even after dropping REPO and REPO_CS for abapGIt and creating a new repo, the pull completes correctly but using the transaction to navigate still dumps.

**Comment by mbtools** [comment]
Created https://github.com/abapGit/abapGit/issues/5938

You only get checksums for files that have been pulled/updated at least once. Here's the complete set for the latest AG:

[abapGit_repo_cs.txt](https://github.com/abapGit/abapGit/files/10230446/abapGit_repo_cs.txt)

**Comment by AndreaBorgia-Abo** [comment]
Having now saved the set above, I tried again: no go, still dumps in the exact same spot. Other system is temporarily unavailable, can't double-check right now.

**Comment by mbtools** [comment]
`ZCL_ABAPGIT_REPO_CHECKSUMS` should look as below. `ZIF_ABAPGIT_REPO_CHECKSUMS~GET` is definitely there. If it does not, delete the class and pull it again. There might be an issue pulling class/interface on lower releases. 

![image](https://user-images.githubusercontent.com/59966492/207715404-711f35a4-67f6-4267-a751-0408ef948967.png)

PS: The navigation to the standalone version is "normal". I get this a lot that where-used shows an implementation in multiple versions of the standalone + the dev version.

**Comment by AndreaBorgia-Abo** [comment]
Yup, that apparently was the case, here are the two versions side by side::
![grafik](https://user-images.githubusercontent.com/25269970/207851861-b766ebb0-1205-4ca7-905c-e8456aa15e2b.png)
Now the dump has moved further on:
`zif_abapgit_sap_package~create( ls_package ).`
Suspecting something similar, I copied over the corresponding class fromSR3 to SR2 and then it could update itself, apparently ok.

**Comment by mbtools** [comment]
👍

**Comment by AndreaBorgia-Abo** [comment]
Any ideas about the root cause? System too old / lacking some Notes or incomplete handling in aG of some corner cases?
(gut feeling, from the little I know of the internals, is that some standard functions have errors)

**Comment by mbtools** [comment]
probably an incomplete pull. some classes/interfaces got updated and an error stopped the rest. if it's the wrong class, it will break AG. Worst case, using standalone to uninstall and reinstall should work... unless there's an issue with the persistence. and of course, SAP bugs don't make things better. 

it's quite surprising how well AG works given 116491 lines of ABAP.

**Comment by AndreaBorgia-Abo** [comment]
Indeed it is, I was quite surprised when I finally realized what had happened. There seems to be some issue with persistence on that specific system, the problem did not disappear when I removed and started from scratch. Anyway, I am closing it since your solution worked fine; ping me if you need testing on a relatively older version, of course.
