### ISSUE TITLE
UIAC, UIAD: support for new object types

### ISSUE THREAD

**Issue by michaelnicholls** [abapGit/abapGit#5958]
As technical catalogs are a good way to manage FLP content, would it be possible to add support for UIAC  and UIAD objects?

**Comment by mbtools** [comment]
Sure. We just need someone to code it: https://docs.abapgit.org/development/serializers.html

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.

**Comment by ViktoriaFreidel** [comment]
I just want to inform that description of #5958 was created long time ago. Currently has been decided to support only UIAD objects. UIAC object is not in a  focus anymore.
Could the description of #5958 be changed only for UIAD? It would be better to follow a process.
