### ISSUE TITLE
SFPF pull doesn't work

### ISSUE THREAD

**Issue by simonegaffurini** [abapGit/abapGit#5961]
Hello, I am using version 1.120.0 of abapGit and I am not able to pull two SFPF objects.
I already deleted the SFPI interfaces and tried pulling again, but only SFPI objects are created.
If I try to see the diffs in the sfpf.xdp file, I get "No diffs found", if I look for diffs in the sfpf.xml file, the page doesn't really work (I get js init error) but I can see that the local section is empty, while the remote has alot of stuff.
Is there a specific point you want me to debug to find the cause?
Thanks

**Comment by mbtools** [comment]
First check if our test repo works https://github.com/abapGit-tests/SFPF

I can't run the test bcs my systems don't have ADS installed. But if the test is successful, let's create a new test repo with your objects. 

Zcl_abapgit_object_sfpf handles the object in serialize and deserialize methods.

**Comment by simonegaffurini** [comment]
Hello, I am now trying that test repo. This is the result:
![image](https://user-images.githubusercontent.com/87023474/209875111-adbba07a-d8ff-4ac8-abaa-4fd31a076317.png)
this time, the sfpf object is created.
I still see some diffs, is it normal?
![image](https://user-images.githubusercontent.com/87023474/209875284-09470197-0cb6-428a-b1b2-6eefa24ad9cd.png)

**Comment by mbtools** [comment]
Since https://github.com/abapGit/abapGit/pull/2555 the layout is in a separate file. It looks like the test repo is still in the old format. 

You can just stage the version in your system (after the pull) and commit it to a new PR for the test repo, please. I will merge it

Uninstalling and pulling this new version should then work without diffs. Then we know it's working in general. 

Now how is your case different from the one that works?

**Comment by simonegaffurini** [comment]
It's kinda complex to share the repository because of the custom namespace and dependencies, otherwise I'd just share it.
Anyway, it looks like the .sfpf.xdp file is generated empty, and so it is committed like that in the repo, maybe this is the reason why I can't pull?
![image](https://user-images.githubusercontent.com/87023474/210178524-f591c86e-a902-4258-9c62-f5219e92a0d3.png)

**Comment by mbtools** [comment]
I merged the test repo. Thanks for the update.

For your test case, put a break-point in this method. It might not read form with namespaces properly:

https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_sfpf.clas.abap#L108

**Comment by simonegaffurini** [comment]
Turns out it's about language, after debugging that method. I am guessing my colleagues wrote part of it in english and part of it in italian.
![image](https://user-images.githubusercontent.com/87023474/210180803-4eb4b118-5920-4c8f-9b41-0ba03ead8cb7.png)
![image](https://user-images.githubusercontent.com/87023474/210180830-1512f479-a6dd-42fd-b3d4-261fd9087958.png)
here it's reading with language E.
I'll close the issue as it's something not related to abapGit and reopen only if I still have issues.
Thanks

**Comment by mbtools** [comment]
good find! 

In https://github.com/abapGit/abapGit/issues/5624, I suggested using an icon in the repo view to indicate if an object has a different original language. That would have helped

**Comment by simonegaffurini** [comment]
That would be helpful! In this case, serialization doesn't work at all, atleast in the issue you mentioned it asks to maintain on original language or change it.
An icon indicating the issue with the object would be good.
I'd go as far as saying that, in this case, it should be mentioned in the log, however I am not sure you can have this information.
