### ISSUE TITLE
User exit for APACK

### ISSUE THREAD

**Issue by simonegaffurini** [abapGit/abapGit#5962]
Hello, what are your thoughts on adding a new user exit as a fallback to APACK?
Let's say I call zcl_abapgit_apack_reader, it will look for the class implementing ZIF_APACK_MANIFEST or IF_APACK_MANIFEST.
In my case, IF_APACK_MANIFEST does not exist, so I am using ZIF_APACK_MANIFEST, however I have to manually remove the manifest class from tr everytime we have to transport to another system (abapGit is only available in dev).
What if there is a new user exit that returns the APACK interface given the repository?
I would create a manifest class like I am doing now, but implementing a new interface copied from ZIF_APACK_MANIFEST, that is transportable.
Perhaps the user exit could also skip the whole interface part and just expect the apack values in return, given the repository.

**Comment by mbtools** [comment]
This might also help with https://github.com/abapGit/abapGit/issues/5363 and https://github.com/abapGit/abapGit/issues/5767. 

Returning the apack values directly makes sense. Would it work also on target systems without the exit? 

Feel free to do a PR that we can use for testing various scenarios.

**Comment by simonegaffurini** [comment]
I am guessing it will depend on how the user is gonna implement the reading of the values based on the repo.
Personally, I don't really care about apack in target system, as it is a "copy" of my development system and I can see what version I am using there. There's also no real use of it in a target system, except knowing what version of repository is installed.
I am now working on the pr so it can be tested.

**Comment by simonegaffurini** [comment]
this actually adds a whole other level of complexity.
if you can declare apack values in a user exit, this will generate the .apack-manifest.xml file, however a pull wouldn't actually pull anything.
to fix this, you also need another exit (apack deserialize) that will allow you to modify the apack values, and it's only called if the apack has no class.
I am still testing this so I need a few more commits

**Comment by simonegaffurini** [comment]
Ok, I had a few tests and this is the PR ready for some more
[#5963](https://github.com/abapGit/abapGit/pull/5963)
So creating the APACK in a user exit is easy enough, however the problem comes with updating the local APACK.
AbapGit does not handle it, so I had to "treat it as an object" in the deserialization. This means that when pulling, this will show if there are differences
![image](https://user-images.githubusercontent.com/87023474/210178648-406c6773-61d8-4f22-a5c2-add6de51bc50.png)
if pulled, it will call the exit and expects the update implementation.
This all happens at the end of deserialization, so if there's an APACK class implementation, the user exit must not be called.
The only thing that's kinda wrong is that now, even if there's a class implementation (like all the repos before this feature) with diff local/remote, you will still be prompted to update the .apack-manifest.xml file. You may choose not to, but it will anyway because the implementation class is what matters in that case.  Can't be skipped, there's no way to know whether there's an implementation class or not in the deserialization checks part.

I am currently testing it with this implementation 
![image](https://user-images.githubusercontent.com/87023474/210178908-9905dc22-58a5-4c78-be4f-153d6e891ba6.png)
just changing the version in the .apack-manifest.xml file, but if you create the tmp table with all the apack values it will make more sense.

**Comment by mbtools** [comment]
hmmm. We're back to the original problem that APACK tried to solve: Specifying the dependencies *as part the repo*. 

If you create a repo based on the exit, every target system will also need to implement the exit (including new persistency) which defeats the point of APACK. 

I agree with your statement at the end that this should not be an exit but rather "a standard feature". However, this gets into a area of "versioning and package management" which is a bigger topic. 

- https://github.com/abapGit/abapGit/issues/217
- https://github.com/abapGit/abapGit/issues/2236
- https://github.com/abapGit/abapGit/issues/3152
- https://github.com/abapGit/abapGit/issues/3016

and complexities like https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527 (via Lars)

I understand the frustration. I'm feeling the same way. ABAP just has its quirks. I'm not sure we will ever get to where other language environments are. 

Back to your original issue: Why don't you transport `ZIF_APACK_MANIFEST` to your target systems (once)?

**Comment by larshp** [comment]
if doing add-on development and you dont want it as part of the customer installation, just remove apack during packaging, https://docs.heliconialabs.com/abap-product-development.pdf

**Comment by simonegaffurini** [comment]
Mmm I get the feeling this is something that needs more work.
Anyway, @mbtools instead of transporting ZIF_APACK_MANIFEST to target system, I'll just find a way to to exclude the implementation class on quality/prod systems instead (we already have an enhanced version of abapGit).
Transporting the interface it's just unpractical for us at the moment. We're converting each one of our company products to abapGit and a structured git with versioning and such, we have X amount of products on each system all using that interface and if for some reason it is not imported we're back to the initial problem. It is not a big deal because apack is only useful for us in the dev system and has no reason to be on quality/production.

@larshp thank you for that document, it's exactly what I needed! I'll checkout Nuve Platform as it sounds like the type of solution I was looking for.

I guess this issue can be closed, as the PR aswell.

**Comment by larshp** [comment]
what is your use-case for apack? if you have multiple products sharing code, I'll also recommend duplicating code instead of reusing, it makes it a lot easier to upgrade each product individually(if applicable)

**Comment by simonegaffurini** [comment]
At the moment, each one of our products has apack.
Whenever a new version is released on our central development system, the version is updated and when development branch is merged into master, if a newer version of apack is detected (compares sem version) a new release is automatically generated.
This is useful to us because if we start development today on a brand new system, we're using the latest release of the product, but a year from now if maintenance is needed, we can easily found out which version was used at the time and what changes were made since then.
It also looks like we're following the guidelines of document you just linked me.
The reason why it's unpractical for us to transport ZIF_APACK_MANIFEST is, like you said, products sharing code, in this case the interface. It means that the first ever step on a brand new system is transporting this interface to avoid syntax errors.
So the solution, in our case, is either have a copy of ZIF_APACK_MANIFEST for each product called ZIF_{PRODUCT}_APACK_MANIFEST and enhance the apack class to search for the class implementing it, or just avoid transporting the apack implementation class, as it is not useful in quality/production anyway.

**Comment by mbtools** [comment]
I see value of seeing directly in test/prod what version is installed. It might not be what's dev, for example, if a transport has not been released or imported yet. APACK assumes that you include the versioning as code so that it becomes part of the repo and therefore also any target system. 

Would a solution to https://github.com/abapGit/abapGit/issues/5363 help? In addition to `(z)if_apack_manifest`, we could look for an implementation of `/namespace/if_apack_manifest`. The namespace would be derived from the SAP package assigned to the repo.

**Comment by simonegaffurini** [comment]
Perhaps, altought I feel like a more flexible solution like described in #5363 with the interface name in .abapgit.xml would be better.

**Comment by larshp** [comment]
IMHO dont spend too much time on fixing apack

add a constant with the semantic version in your code, done? tho, you need to transport everything together for it to be indicative of the version in the following systems

**Comment by simonegaffurini** [comment]
After a review, I agree with larshp.
I'd use gCts or transport of copies for the type of issue I am describing.
I'm closing this issue, thanks
