### ISSUE TITLE
cannot pull abapGit: duplicate file error

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#5967]
![image](https://user-images.githubusercontent.com/5888506/210211697-eb5ca12d-2737-4ff7-a3ef-365d1a466061.png)

due to https://github.com/abapGit/abapGit/pull/5952 I cannot pull abapGit

![image](https://user-images.githubusercontent.com/5888506/210211474-2320ca55-a564-46b9-bb50-d6daf54bea05.png)

`PACKMOVE` is only set if the SHA1s match, which is also correct? as its used when TADIR-TDEVC is the only change needed. I.e. the flag cannot be used for this check? just check remote for duplicate filenames instead?

https://github.com/abapGit/abapGit/blob/main/src/objects/core/zcl_abapgit_file_status.clas.abap

temporary workaround: comment the code

**Comment by mbtools** [comment]
True, it does not work if objects are changed and moved to a different package at the same time. 

Checking only the remote sounds right. I will take a look.
