### ISSUE TITLE
XSLT object listed as inactive in aG / active in SE80

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#5969]
Here is me installing ABAP-Swagger on system SR2
![grafik](https://user-images.githubusercontent.com/25269970/210338069-ccd0a7db-e81a-482f-8f74-ff1b5da318df.png)
then I click to navigate to SE80:
![grafik](https://user-images.githubusercontent.com/25269970/210338287-4b7b2bc5-a427-4890-bf05-2e96c9052e66.png)
Expanding the list of inactive objects however gives this:
![grafik](https://user-images.githubusercontent.com/25269970/210338788-3a052a2b-1b12-4591-8f14-39a7566467c2.png)
(situation doesn't change even after repeated activations of this transformation)

Same happens with abap2xlsx:
![grafik](https://user-images.githubusercontent.com/25269970/210339464-3bf497c5-e640-4fbf-847f-94063390d8e1.png)

Next I tried with SR3, a slightly more recent system, same result for the transformation in ABAP-Swagger, cannot quickly check abap2xlsx because there is a ZMONSTERS package ( @hardyp might know something ;) ) which contains an older version among other things.

I had a look at previous closed issues related to XSLT, did not find a match. Not sure if this is really an issue, since the transformations apparently work. I suspect this is a system-dependent issue, I have not seen it on my local MiniSAP installations (which are, however, fairly recent in comparison, see:
SR2: SAPKA73105
SR3: SAPKA74004

**Comment by larshp** [comment]
is note Note 2859159 installed?  XSLT, ref https://github.com/abapGit/abapGit/issues/5262#issuecomment-1012426663

**Comment by AndreaBorgia-Abo** [comment]
Funny, I had seen the issue the comment belongs to but discounted it since I am not seeing activation errors on dependent classes. At the moment, I have no connection in SNOTE: once that is restored, I'll check and report back here, thanks.

**Comment by AndreaBorgia-Abo** [comment]
Nope, this note is not applicable: kernel is out of range.
I'm closing the issue.
