### ISSUE TITLE
Dump in Diff mode when "ignore comments" is activated

### ISSUE THREAD

**Issue by stud0709** [abapGit/abapGit#5983]
in Diff mode, there is a dump if you set the View menu to ignore comments

Version 1.120.0

![image](https://user-images.githubusercontent.com/31960113/211776858-817417d2-07fe-457a-ab99-3443057ac5ce.png)

**Comment by larshp** [comment]
@stud0709 try again, latest version, fixed by @christianguenter2

**Comment by stud0709** [comment]
@larshp @christianguenter2 works fine, great job! Many thanks!
