### ISSUE TITLE
Staging page/logic broken

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#5987]
Need help, since changes cannot be pushed to repository.

Steps to reproduce:
Enable experimental features.
Pull repository https://github.com/albertmink/testing_intf_aff and do something with the object.
Then, try to add/push/stage changes will result in this 
<img width="1084" alt="Screenshot 2023-01-12 at 08 57 43" src="https://user-images.githubusercontent.com/38354196/212010098-0c6ae8b0-b029-4662-aa83-7eb6730171fe.png">

**Comment by mbtools** [comment]
GUI 7.7 or 7.8 with Chrome control? https://github.com/abapGit/abapGit/issues/4841

**Comment by albertmink** [comment]
Confirm that it is GUI 7.8. Don't know anything about the chrome control.

Anyhow, did I missed the part with a workaround? Or can't I push via abapGit at all?

**Comment by mbtools** [comment]
abapGit is using SAPEVENT in links which do not work with Chrome HTML control (yet). SAP Notes [2901278](https://launchpad.support.sap.com/#/notes/2901278) and [3228419](https://launchpad.support.sap.com/#/notes/3228419) explain the problem. 

One workaround: In GUI settings, switch to IE control.

**Comment by albertmink** [comment]
Close this one, since the symptom is tracked already in #4841
