### ISSUE TITLE
Not all deserialized objects are added to transport

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6004]
Quite an eluding issue, I could not stably recreate it yet. But detected in 2 different systems (702 and 750) with 2 different code bases already. Latest AG in both cases. First time detected somewhen in September. Objects (some object, not all !) are properly deserialized but are missing in the transport then and had to be added manually (otherwise dump later in QA). The objects were modified (not newly added) classes. Some other classes were added properly

Will continue observations from my side.

**Comment by christianguenter2** [comment]
Not addressing the root cause but there is 'Advanced > Add All Objects to Transport' which might help.

**Comment by mbtools** [comment]
CI does a thorough job of checking transports. There's no issue adding new objects or deleting them. It must be a scenario where an existing object is modified. Such scenarios are not covered by CI at all. Might be worth investing and building a process that circles through a few branches of a test repo.

**Comment by Bituix** [comment]
I am getting the same issue  with 1.121.0 - Developer Version. Looks like for every Pull the changed objects are not being added to the transport.

In the past when I change a method the whole class was added to a TR with R3TR CLAS, but now  if I change a method nothing in being added to a TR.  I am adding  all objects using 'Advanced > Add All Objects to Transport' or adding manually to the transport.

**Comment by mbtools** [comment]
Please test https://github.com/abapGit/abapGit/pull/6047
