### ISSUE TITLE
Object selection dialog scrolls up on checkbox event

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#6010]
This dialog annoyingly scrolls all the way up when changing the state of a checkbox.

![image](https://user-images.githubusercontent.com/5270359/214321737-61111324-2a32-4b02-b140-3c9c78bf9ba0.png)

I haven't looked at the implementation but maybe a stable = x is missing?

**Comment by christianguenter2** [comment]
hm, works for me.
![abapGit_popup](https://user-images.githubusercontent.com/17437789/215261676-8d732457-cac5-4be7-8fb7-7b94f2c51cb4.gif)

**Comment by fabianlupa** [comment]
Hmmmmm indeed

![ALV Selection](https://user-images.githubusercontent.com/5270359/215262447-894601bf-ee1d-45b8-a9db-5dc25fb6c4d4.gif)

For me this change is required. Not sure if it's somehow GUI theme or backend version dependant. Then it works just like it does for you.

https://github.com/abapGit/abapGit/blob/20785fef7897648f04f02e7959509e51efbcf56f/src/ui/zcl_abapgit_popups.clas.abap#L436

```diff
---     mo_select_list_popup->refresh( ).
+++     mo_select_list_popup->refresh( s_stable = VALUE #( row = abap_true col = abap_true ) ).
```

**Comment by fabianlupa** [comment]
Ah found it. I assume your system is lower than BASIS 756? The defaults seem to have changed by the SALV refactoring. `REFRESH` is now an alias for an interface method in `IF_SALV_GUI_OM_TABLE_ACTION`. And these lines of code:

```abap
*<<< YI3K093295
  if s_stable is supplied.   " take stable settings of application into account
    me->r_controller->refresh( s_stable ).
  else.  "maintain old standard behavior of stable refresh always
    l_stable-row = 'X'.
    l_stable-col = 'X'.
    me->r_controller->refresh( l_stable ).
  endif.
*>>> YI3K093295
```
Do not work anymore as they are one level deeper down and using `IS SUPPLIED` doesn't work then.... Maybe note 3146971 helps, I'll check next week and open an incident if it doesn't, as otherwise this should "break" lots of applications.

**Comment by christianguenter2** [comment]
Interesting! I tested on 752.

**Comment by fabianlupa** [comment]
Note 3146971 indeed somehow fixed the issue ;)

**Comment by fabianlupa** [comment]
Welp, on 757 the issue returned on note 3146971 is no longer installable :(

**Comment by mbtools** [comment]
Well, then SAP needs to port the note to 757 (and higher)

**Comment by mbtools** [comment]
Needs SAP Note [3170260]https://me.sap.com/notes/3170260) and [3323691](https://me.sap.com/notes/3323691). Closing

Ref https://github.com/abapGit/abapGit/issues/5279
