### ISSUE TITLE
While getting Login with github profile credentials, It's throws an Error ?

### ISSUE THREAD

**Issue by SugguSandeep29** [abapGit/abapGit#6021]
Hi,

Even Through I providing right credentials it's throws an error 
How to make it correct 

![s](https://user-images.githubusercontent.com/68318127/215977234-a564e67c-e524-4523-8d60-168819af8045.jpeg)

Thank You,
SUGGU SANDEEP.

**Comment by larshp** [comment]
did you check any of these closed issues https://github.com/abapGit/abapGit/issues?q=is%3Aissue+401 ?

**Comment by mbtools** [comment]
https://docs.abapgit.org/guide-authentication.html

**Comment by SugguSandeep29** [comment]
Thank You @larshp & @mbtools 
Problem Got Solved 
As Need To Mention Token Which got generated the GitHub Settings>Developer Settings
![image](https://user-images.githubusercontent.com/68318127/216027766-4f48550e-4b89-447f-a0b4-ba6af3b676d5.png)
