### ISSUE TITLE
Pull Isssue In abapGit

### ISSUE THREAD

**Issue by SugguSandeep29** [abapGit/abapGit#6025]
HI

Firstly, I am able to push Objects from (AbapGit to GitHub_Repo_01) - Which Done Under (Package_01)
After that I am pulling same objects from GitHub_Repo_01 to new Package_02 with new workbench I am getting error, 
Help me with this issue. 

![Untitled](https://user-images.githubusercontent.com/68318127/216264080-2b54dc89-1ae5-47c4-8806-823882ade471.jpeg)

Thank You,
Suggu Sandeep.

**Comment by larshp** [comment]
package and path does not match, check the folder logic https://docs.abapgit.org/settings-dot-abapgit.html

**Comment by SugguSandeep29** [comment]
Hi @larshp visited the link & revised but not able to understand. 
Can you explain the steps, what i need to perform in following screen?

<img width="664" alt="image" src="https://user-images.githubusercontent.com/68318127/216287770-5b3a1ff7-41d2-4564-a289-72521b3828e4.png">

Thank You.

**Comment by mbtools** [comment]
what do you want to do? move all objects to a new package in the same system?

**Comment by SugguSandeep29** [comment]
Hi @mbtools 
Yes

**Comment by mbtools** [comment]
try pulling all changes. if possible, abapGit will try to assign all objects to the new package. 

If this is not possible. do a reinstall (assuming that your really have all changes saved in your repo):
- recreate the repo for package_01 again and completely uninstall it 
- then create a new repo for package_02 and pull everything.

**Comment by mbtools** [comment]
did you get this resolved?

**Comment by SugguSandeep29** [comment]
Thank You @mbtools & @larshp,
Problem got solved.
