### ISSUE TITLE
CALL_METHOD_NOT_IMPLEMENTED with devel version (but not standalone)

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#6035]
On a 731 system with the current dev version (https://github.com/abapGit/abapGit/commit/d856b4ed91c5c190e8ed6e1a47ce98a2ded05193), browsing a repository (tried abapGit and abap2xlsx) leads to a dump with CALL_METHOD_NOT_IMPLEMENTED; interesting enough, this does not happen with the standalone version and, according to memory, is a fairly recent issue (I've been using aG often on this system in the last days). Relevant fact: kernel was upgraded just last week (kernel release 722, sup pkg 1200, abap load 1780, cua load 41)

**Comment by larshp** [comment]
whats the name of the method?

**Comment by AndreaBorgia-Abo** [comment]
It was tried to call a not-implemented method "ZIF_ABAPGIT_REPO_CHECKSUMS~GET"
 in the class "ZCL_ABAPGIT_REPO_CHECKSUMS".
![grafik](https://user-images.githubusercontent.com/25269970/216635580-70097bde-ee7b-4685-a8ee-9a85c19fc7ba.png)

**Comment by larshp** [comment]
are there any diffs, are you running the latest dev edition?

**Comment by AndreaBorgia-Abo** [comment]
I have updated the repo before submitting the report, to the version linked above. One thing to try would be downloading the newer standalone and comparing with that one, hold on... nope, even the current standalone has no problems.
In the $abapgit package there are a number of warnings for unsupported pragmas (yellow) but no errors; in abap2xlsx just one warning.

**Comment by mbtools** [comment]
I never had this problem. The repo certainly contains the method implementation:

https://github.com/abapGit/abapGit/blob/main/src/repo/zcl_abapgit_repo_checksums.clas.abap#L176

Changing kernel requires recompile of all ABAP code. This is usually automatic. You could force activation manually or run SGEN

**Comment by AndreaBorgia-Abo** [comment]
@mbtools I ran the same test on another system where the kernel was not recently updated and had no problems, so it is definitely a code generation issue. I will liaison with Basis colleagues to re-run SGEN at a time when it is convenient and safe to do so. Closing now, thanks.

**Comment by AndreaBorgia-Abo** [comment]
We ran SGEN but the situation is unchanged: standalone still runs ok, devel version still dumps, on another system (also upgraded) there is no issue. Will update when we find out what's wrong.

**Comment by mbtools** [comment]
delete `zcl_abapgit_repo_checksums` and `zif_abapgit_repo_checksums`. then pull the dev version again using the stand-alone prg.

**Comment by AndreaBorgia-Abo** [comment]
Now I am really puzzled: it still  happens. Even tried removing and reinstalling the standalone version, in addition to the suggestion above.

**Comment by mbtools** [comment]
looks like deserializing the class or interface does not work on 731. bug in AG or SAP? 

or

there's an exit in place that changes things

let's use some hardcore tool to compare systems for the class and interface:

![image](https://user-images.githubusercontent.com/59966492/222492214-df967007-4d7d-4a00-acf4-7f2dcdba8302.png)

[zbc_table_browser.zip](https://github.com/abapGit/abapGit/files/10873618/zbc_table_browser.zip)

tool and output from my system is attached. run it in the 731 and then diff the outputs.

**Comment by AndreaBorgia-Abo** [comment]
Reopening to match current status of issue and attaching the output from our 731 systems.
First thing I notice is that we don't have entries in SEOREFTODO (for ZCL) and in SEOREFPROT (for ZIF), other differences are harder to read for me.

**Comment by mbtools** [comment]
these two tables are not relevant (a log)

next test: 
- delete class/interface
- recreate manually (se24)

**Comment by AndreaBorgia-Abo** [comment]
Deleted class ok, deleted interface ok, created interface, got odd (harmless?) XT465 message (Parameter LSM not in version 0462 of tp configuration), created class (3 files), restarted aG devel, successfully browsed own repository, started celebratory dance too soon... when I pulled the new changes and activated, I still got a dump... finished the pull with the standalone version and now the devel version also works.
Thanks, closing.

**Comment by mbtools** [comment]
funny thing, i recently got XT465 too. SAP Note [2346328](https://launchpad.support.sap.com/#/notes/2346328) - Source-code-based Class Builder (SE24): Display of unexpected message following activation.

**Comment by AndreaBorgia-Abo** [comment]
Anyhow, another pull of the devel version and the issue is there again, still with ZIF_ABAPGIT_REPO_CHECKSUMS~GET_CHECKSUMS_PER_FILE
However the usual trick of deleting and restoring class and interface apparently doesn't cure it. Oh well....

**Comment by mbtools** [comment]
I fixed XT465 when creating packages (https://github.com/abapGit/abapGit/pull/6141). Otherwise it remains a mystery

**Comment by AndreaBorgia-Abo** [comment]
I also updated the standalone version today so it should already be good; it's a bit annoying that I have to update manually but at least it works. What do you say, we leave it closed for now? After all, at the moment I only encountered this issue on one system.

**Comment by mbtools** [comment]
Agree 👍

**Comment by AndreaBorgia-Abo** [comment]
Direct links to sources, because lazyness!

ZIF_ABAPGIT_REPO_CHECKSUMS)

- [XML](https://raw.githubusercontent.com/abapGit/abapGit/main/src/repo/zif_abapgit_repo_checksums.intf.xml)
- [ABAP](https://raw.githubusercontent.com/abapGit/abapGit/main/src/repo/zif_abapgit_repo_checksums.intf.abap)

ZCL_ABAPGIT_REPO_CHECKSUMS )

- [XML](https://raw.githubusercontent.com/abapGit/abapGit/main/src/repo/zcl_abapgit_repo_checksums.clas.xml)
- [ABAP](https://raw.githubusercontent.com/abapGit/abapGit/main/src/repo/zcl_abapgit_repo_checksums.clas.abap)
- [Local](https://raw.githubusercontent.com/abapGit/abapGit/main/src/repo/zcl_abapgit_repo_checksums.clas.locals_imp.abap)
- [Test](https://raw.githubusercontent.com/abapGit/abapGit/main/src/repo/zcl_abapgit_repo_checksums.clas.testclasses.abap)

**Comment by AndreaBorgia-Abo** [comment]
Once more, cleaned up, redownloaded sources, verified that dev version was again working correctly.

Let aG redownload the class (because of a spurious formatting issue, suits my purpose anyway) and the dump is back.

Verified that class still has method implementation of zif_abapgit_repo_checksums~get, doubleclicked to navigate... and promptly ended up in the standalone source. Gut feeling is that aG is innocent here, I had a look [among the support notes](https://launchpad.support.sap.com/#/solutions/notesv2/?q=CALL_METHOD_NOT_IMPLEMENTED%252520interface&sortBy=date&sortOrder=desc&filters=%255B%255B%257B%2522attribute%2522:%2522type%2522,%2522operator%2522:%2522EQ%2522,%2522low%2522:%252200200720410000000382%2522,%2522high%2522:%2522%2522%257D%255D%255D) but I am unsure which one, if any, to recommend to Basis colleagues.

**Comment by AndreaBorgia-Abo** [comment]
Using a system covered by our support contract, after applying the fix for #6234 directly in class zcl_abapgit_convert, I ran the dev version and managed to reproduce the issue but not the workaround: removing and recreating class and interface does not relink where-used correctly, it's even worse / better depending on how you look at it ;)

We'll now try to get SAP involved, will update here as needed.

**Comment by AndreaBorgia-Abo** [comment]
![oL5mYvlQ5o](https://user-images.githubusercontent.com/25269970/235158179-516a8ecc-105d-4932-b92c-1b5c2c5a332a.png)

Different place in the code, same result, same broken navigation.
I have now made a short animated gif with the whole sequence, we'll share it with SAP.

**Comment by AndreaBorgia-Abo** [comment]
Yet another try, different method, same issue.
