### ISSUE TITLE
I tried to push Objects from abapGit to GitHub Repository, It's accepting Only One Thousand Files, why not more than ? 

### ISSUE THREAD

**Issue by SugguSandeep29** [abapGit/abapGit#6066]
Hi 
I want to push more than 1K files, but it's getting truncate 

Thank You,
Suggu Sandeep.

**Comment by larshp** [comment]
the UI and/or github might truncate the viewing, but it should work pushing many files. Alternatively just push multiple times

can you help adding a screenshot of the actual problem?

**Comment by SugguSandeep29** [comment]
As Of Now Our Server is down,
What my problem is in my transport request there are more than One Thousand Development Objects,
Getting Staged in abapGit well & good, after the push into github repo. main branch accepting only One thousand files.

**Comment by larshp** [comment]
@SugguSandeep29 did you solve this issue, as https://github.com/abapGit/abapGit/issues/6074 was opened?

**Comment by SugguSandeep29** [comment]
Hi @larshp Not Yet 

<img width="957" alt="image" src="https://user-images.githubusercontent.com/68318127/218720157-bf1b34a4-9502-45bb-a6ec-1c44ab857178.png">

This is the issue I am facing while commit more than 1K+ Objects.

**Comment by larshp** [comment]
the above is a screenshot from github, abapGit cannot do anything about how github works

**Comment by SugguSandeep29** [comment]
Hi @larshp 

Tried Offline, it's working fine. 

Thank You.
