### ISSUE TITLE
partial update

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#6067]
Possibly related to #6050, when pulling the current development version on A4H (HANA1909 Docker image) using either the standalone version or dev I get this error message: 
`Error updating where-used list for CLAS ZCL_ABAPGIT_GUI_PAGE_REPO_VIEW. Check for syntax errors`
A syntax check of the code says:
`Method "RENDER_CONTENT" does not exist. There is, however, a method with the similar name "RENDER_ITEM".`
Since render_content does not exist on the remote, I copied the raw version from GH and activated it, then system was happy.
I could not replicate the issue with the older NPL minisap.

**Comment by larshp** [comment]
yea, I also got it earlier, go to the class and manually trigger clean up redefinitions

![image](https://user-images.githubusercontent.com/5888506/218309001-17db7ff5-6676-43c6-b588-6185ab884069.png)

**Comment by mbtools** [comment]
Since https://github.com/abapGit/abapGit/pull/5768 it automatically repairs classes. Looks like that logic could be improved.
