### ISSUE TITLE
Cannot delete annotated tag -> "Git protocol error: Funny refname"

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#6072]
I have this test repo with an annotated tag `t_anon`.
https://gitlab.com/christianguenter/test_tag.git
https://gitlab.com/christianguenter/test_tag/-/tags/t_anon

When I try to delete it from abapGit with 'Tag' > 'Delete' I get this error
"Git protocol error: Funny refname"
![grafik](https://user-images.githubusercontent.com/17437789/218502310-da51dbb5-8b44-4c7a-84bb-d770a3e08d9f.png)
![grafik](https://user-images.githubusercontent.com/17437789/218503289-3e12bc31-de7e-4e0e-ad0c-ea7a9a55cda6.png)

Same repository on GH gives "Git protocol error: Unexpected empty reply˙"
https://github.com/christianguenter2/test_tag.git
![grafik](https://user-images.githubusercontent.com/17437789/218505101-71282326-90a6-4e5e-98b6-68c5547e67aa.png)

Whereas lightweight tags can be deleted without problems.

**Comment by larshp** [comment]
this is something we should add to the integration test, https://github.com/abapGit/abapGit/blob/main/test/zcl_abapgit_integration_git.clas.testclasses.abap

spin up [gitea](https://github.com/go-gitea/gitea) in github actions and test against that

**Comment by mbtools** [comment]
Deleting lw tags didn't work on GH either. Can you please test https://github.com/abapGit/abapGit/pull/6095 on Gitlab?
