### ISSUE TITLE
How To find these Objects, which are ignored?

### ISSUE THREAD

**Issue by SugguSandeep29** [abapGit/abapGit#6074]
Hi 

<img width="335" alt="image" src="https://user-images.githubusercontent.com/68318127/218717706-f24a6564-4d89-4c6f-898b-7befdba3f0b3.png">

I came across this error messages after completing of Push From Abapgit to Github Repo.

Where can i find the files are of which ignored ?

Thank You,
Suggu Sandeep.

**Comment by larshp** [comment]
The object types mentioned are not supported by abapGit, thus ignored

pull requests welcome

**Comment by SugguSandeep29** [comment]
Oh Ok,
Thank You @larshp .
