### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by rossitsaivanova** [abapGit/abapGit#6075]
Dear Colleagues,
I have an issue with downloading a new enterprise repository from GitHub. I am using PAT.
![image](https://user-images.githubusercontent.com/52630851/219365924-2e116852-8955-4309-ac89-a3ec42a91a54.png)
I have write access to it and I cloned it via GitHub Desktop.

I read all issues related to error 403. I tried the solutions but no success till now.
I don't have problem to download public or private user repositories.

Any suggestions?

**Comment by larshp** [comment]
typically this happens when the PAT does not have access to the resource

double check the token, are you using classic or fine-grained tokens, does the enterprise use SSO etc.

**Comment by rossitsaivanova** [comment]
PAT is a classic one and has all options selected without expiration date.
We use SSO and PAT is authorized.
![image](https://user-images.githubusercontent.com/52630851/219426078-4e0be04c-6a25-463f-bd8c-bba45dc2b343.png)

**Comment by larshp** [comment]
try via command line

`git clone https://foo:PAT@https://github.com/your/repo`

**Comment by rossitsaivanova** [comment]
I executed the command successfully :)

Cloning into '***********'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 21 (delta 2), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (21/21), done.
Resolving deltas: 100% (2/2), done.

**Comment by larshp** [comment]
okay, any proxy setup between the SAP server and the internet?

**Comment by larshp** [comment]
the IPs of the SAP application server(s)

**Comment by larshp** [comment]
@rossitsaivanova can we close this issue, as not related to abapGit?

**Comment by rossitsaivanova** [comment]
Thank you for your support, Lars. I will find the proper setup :)
