### ISSUE TITLE
Improve pull decision dialog, deployment mode

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6090]
I find that the pull decision dialog is actually a very nice feature, showing deeper details on what will be done and gaining some control over deserialization sequence. It helps deploying code a lot. Yet there is a room for improvement. For me it boils down to a possibility to select a particular sub-package and deserialize only it, and then next and then next. In a wider sense - there should be a possibility to select/filter groups of object and process them only. The new feature that allows selecting categories of objects (DEVC, DDIC ...) is not granular enough.

Fortunately it is very easy to do :) Having that the dialog is an ALV :)

I'm going to rework the toolbar and that's it. But there is one pitfall - screen status. The existing screen status does not have more buttons. The standard SALV status, unexpectedly, does not have Cancel button (X). Any ideas about finding a reliably standard dialog screen status ?

Another option is to create one. And the standalone version should just generate it on the fly. Like the abapgit table. Or fixing the 1001 screen. Seems possible.

**Comment by mbtools** [comment]
I searched several hours and ended up writing a little tool to find a screen status with the additional "category select" button. There are no others in Basis that would work (I looked at all of them). 😞 

For larger projects, selecting by package can make sense. Dependencies to other packages will exist unless you have things very well structured (incl. package interfaces), but even then a "package pull" can be useful. 

Time to rewrite it in HTML (a new page)? 😉

**Comment by sbcgua** [comment]
> For larger projects ... things very well structured ...

Wouldn't claim for "very" but I'd say it's my case. ~10 subpackages. Dedicated packages for DDIC and error handling which are the basis for all others. And update deployment is often a pain. And some times it is in front of a customer  ... :( so looks ugly and raises questions, to abapGit in particular :( So really need some control here.

Long term I'd like to have something like explicit instruction for deserialization order right in the repo. Some kind of `.abapgit.deployment.txt` of whatever. But it will take more time. As we as the HTML page. In fact ALV is a perfect tool - filter + multi select - that's what is needed. And very few efforts to create. Another paid is translations ... guess I have to find some time for that too

**Comment by sbcgua** [comment]
Looks not bad imho ...
![image](https://user-images.githubusercontent.com/15635498/221353876-c5686c3d-932e-4a8f-aceb-e8a9724abcb5.png)


Current idea is to create the status for the full scale abapgit. And then a pragma for abapmerge to convert XML to code for the standalone version. The latter will autocreate on the first run. One caveat - it will probably not re-create if status updated ...

**Comment by mbtools** [comment]
Updates must be seamless, indeed. For dependencies between objects, it needs https://github.com/abapGit/abapGit/issues/3536#issuecomment-989761883 (Each object should have the deps in the xml). 

Yes, translations are  a pain. Should be based on LXE but in separate file(s) in /i18n/ folder (ie not in the XMLs).

**Comment by mbtools** [comment]
Sure, enhancing abapmerge is an option... just takes us further away from a plain HTML solution.

**Comment by sbcgua** [comment]
> Each object should have the deps in the xml
mmm what if it is circular ... but yeah ... towards the right direction anyway

**Comment by sbcgua** [comment]
> Should be based on LXE but in separate file(s) in /i18n/ folder (ie not in the XMLs)
Absolutely. #2539

**Comment by sbcgua** [comment]
> Sure, enhancing abapmerge is an option... just takes us further away from a plain HTML solution.

I doesn't, just that the current tool will be more convenient in the meantime :)
