### ISSUE TITLE
Community Call, 2023, Tuesday April 4th 15:00 CEST

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6091]
Time: Tuesday April 4th (15:00 CEST)

Duration: 1 hour scheduled, no recording, in English

Invitations: Open for all, message Lars your email address on [Slack](https://communityinviter.com/apps/abapgit/abap), and he'll forward you the invite

Suggested Agenda Items:

- Overall goal: Align longer term strategy, help prioritize bigger tasks
- UI concept, popups, separation from other layers
- Enhancing serializer interface `zif_abapgit_object`
  https://github.com/abapGit/abapGit/issues/4187
  https://github.com/abapGit/abapGit/issues/3536#issuecomment-989761883
  https://github.com/abapGit/abapGit/issues/6038

Feel free to add below

https://docs.abapgit.org/other-where-used.html
https://abapgit.org/sponsor.html

**Comment by AndreaBorgia-Abo** [comment]
@mssoftag this might also be interesting for us, because of the translations

**Comment by larshp** [comment]
April 4th 15:00 central europe time

**Comment by larshp** [comment]
in ~2 weeks from now, message me your email address on [slack](https://communityinviter.com/apps/abapgit/abap) to get the meeting invite

**Comment by larshp** [comment]
- ALV
- AFF

**Comment by larshp** [comment]
backlog,

- Translation concept
  https://github.com/abapGit/abapGit/issues/2539 
  https://github.com/abapGit/abapGit/issues/1886 
  https://github.com/abapGit/abapGit/issues/2368
- Refactoring `zcl_abapgit_objects` to use interface (plus some improvements)
- AFF update
- ALV

**Comment by mbtools** [comment]
Presentation: https://larshp.github.io/abapGitCC20230404/

PS: There's no recording
