### ISSUE TITLE
GSMP: Generic Simple Metric Provider for the Generic Simple Metric Framework

### ISSUE THREAD

**Issue by EkinTiras** [abapGit/abapGit#6113]
Hello everyone,

I just wanted to announce that we are currently working on an GSMP object handler for abapGit.

Regards,
Ekin

**Comment by EkinTiras** [comment]
Hello Everyone, 
I am at step 4: https://docs.abapgit.org/development/serializers.html and need a test respository for GSMP. 
Can someone create it and assign it to me? Thank you

**Comment by christianguenter2** [comment]
https://github.com/abapGit-tests/GSMP

**Comment by EkinTiras** [comment]
> https://github.com/abapGit-tests/GSMP

Thank you for your help. Can you also add me as a contributor, so that I can push my changes into the repository?

**Comment by larshp** [comment]
added

but you can also just fork the project, https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks
