### ISSUE TITLE
abapGit Usage Data

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6122]
We know too little about the usage of abapGit. How about adding a feature to collect usage stats?

Prerequisites:

- Voluntary
- Anonymous
- No impact on abapGit

Client (abapGit):

- Run data collection at startup (for example once a month or on-demand)
- Collect general system info (similar to debug info)
- Calculate stats based on persistency (one loop over zabapgit data)
- Save result in persistency (key "USAGE")
- Menu item to send data to server 

Server (usage.abapgit.org):

- Collect and persist usage data
- Keep only latest data (per system)
- Provide basic analytics

Filename:

- hash of sysid + sysno

Format:

- t.b.d. (csv?)

Stats:

- AG version for stand-alone and dev edition
- SAP Basis version
- DB & OS
- Number of repos
- Number of AG users
- Min/avg/max number of objects per repo

**Comment by larshp** [comment]
could be interesting, but could also be trouble

try searching for telemetry in vscode, https://www.roboleary.net/tools/2022/04/20/vscode-telemetry.html ...

**Comment by larshp** [comment]
https://www.reddit.com/r/dotnet/comments/15ljdcc/does_moq_in_its_latest_version_extract_and_send/

**Comment by mbtools** [comment]
maybe one day we'll do an offline survey
