### ISSUE TITLE
Show local state for offline repos

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6129]
This is a question related to #6128, raised by @mbtools 

Intention is to have more visibility on offline repo status (in particular useful for deployments):
- was it changed after the last sync ?
- last change user
- maybe file structure
- maybe serialized code (though this probably has very little value since it's easy to drill down in the object which is almost the same)
- unfortunately the real diff is not possible since there is nothing to compare with

It looks like this
![image](https://user-images.githubusercontent.com/15635498/222894781-a82cfaf9-e7d6-4b3a-964b-c21d00c13684.png)
![image](https://user-images.githubusercontent.com/15635498/222894792-d2ad7da5-4941-4deb-b940-b4ced788c6a6.png)

Now question is, if this feature should be switchable or be the only default (so an improvement over the current view) ?
![image](https://user-images.githubusercontent.com/15635498/222894818-563143a5-6972-41d6-b6dd-1fdb03bf7b64.png)

The new approach is certainly not worse or better than the old one, **except one thing** - speed of rendering. Offline repos do not serialize to be displayed, just TADIR is being read. (`ZCL_ABAPGIT_REPO_CONTENT_LIST->BUILD_REPO_ITEMS_LOCAL_ONLY`). Serialization takes time for larger packages.

**Question: is the speed important in this scenario ?** 

For me: probably not so much, I'd gravitate to making the new approach a default and the only one. Also it is a potential code simplification (though it is secondary). Are there any opinions, cases, experiences ?

**Comment by mbtools** [comment]
try to make it as similar to the online repo as possible... zip is just a different source. so AG should serialize objects. show diffs if remote source is available.

online could behave the same way if the remote site is not accessible (http not working), which makes it "offline".

could be the next step to simplify and have one repo class with different remote providers.

**Comment by mbtools** [comment]
#6211 improved it a bit. The status after importing the zip is now correct. 

Serializing also for offline and comparing to the checksums if no zip is loaded is the way to go.
