### ISSUE TITLE
The sub component IV_END_COLUMN cannot be converted to a Parameters

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#6131]
A4H (HANA1909 Docker), using standalone aG (from 04.02.2023) to upgrade devel from 1.121.0 to 1.122.0, got the following error:
```
The sub component IV_END_COLUMN cannot be converted to a Parameters
Import of object ZIF_ABAPGIT_POPUPS failed
```
I don't think this is another instance of #5578 because after refreshing the view there were no differences reported.
NPL (7.52SP04) with standalone aG (05.02.2023) had no issues.

**Comment by larshp** [comment]
I'm unable to reproduce updated both standalone and develop without syntax errors

**Comment by mbtools** [comment]
odd. only the default for `iv_end_column` was changed.

**Comment by AndreaBorgia-Abo** [comment]
It might as well be that the issue depends on the specific start / end commit of the jump, I reported it mostly so that I won't forget about it.

**Comment by larshp** [comment]
unable to reproduce? close?

**Comment by AndreaBorgia-Abo** [comment]
Yes, we might always reopen if needed.
