### ISSUE TITLE
change RFC group to other than parallel_generators

### ISSUE THREAD

**Issue by abap-weasel** [abapGit/abapGit#6133]
Looking for an option to use custom RFC group for parallel processing. Is it possible to change that in settings or so?

https://github.com/abapGit/abapGit/blob/a7c20da7a294d875384f843cbd83cceafdb83fb6/src/objects/core/zcl_abapgit_serialize.clas.abap#L259

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/issues/3280 

pull request for an exit welcome :-)
