### ISSUE TITLE
Customizing tables as part of repositories

### ISSUE THREAD

**Issue by ThomasErgin** [abapGit/abapGit#6136]
Dear Developers,
Since customizing often is an important part of SAP solutions, I'd like to add the content of customizing tables to my repositories. I've noticed a "Beta"-labeled feature for uploading table content to repositories. However, the downloading part has not been fully implemented yet. 

Therefore I've enabled my local version of ABAPGIT by changing 
ZIF_ABAPGIT_DATA_DESERIALIZER 
ZCL_ABAPGIT_REPO 
ZCL_ABAPGIT_DATA_UTILS 
ZCL_ABAPGIT_DATA_DESERIALIZER 
This allowed me to download customizing table data to my system, writing to the DB and adding the lines to the TR. I tried it for my repositories and it seems to work well.

Since the data deserialization feature has been laying around a while, I am hesitating to open a pull request for my changes. 
> Do you think this is a helpful feature? 
> Do you think it should be part of the main branch?
> Why did the data deserializer has not been continued so far?

Cheers

Thomas Ergin

**Comment by larshp** [comment]
problem is designing it so the user does not easily mess up something in the system

I think showing a full overview of the consequences/actions to the user, before confirming the changes might solve it

https://github.com/abapGit/abapGit/issues/3441

**Comment by larshp** [comment]
yea, that could be a nice start

**Comment by mbtools** [comment]
Hi Thomas,

we should evaluate the table delivery class `dd02l-contflag`. This defines how data is handled in tables in general. 

![image](https://user-images.githubusercontent.com/59966492/224039630-81a5d370-a7b7-484c-8386-727fbd89ad6c.png)

![image](https://user-images.githubusercontent.com/59966492/224039913-a264c314-2e00-4f7d-92ab-046cbf56beb7.png)

- `E`, `S`, and `W` should not be allowed at all
- `A`, `C`, and `L` are ok (after confirming in popup)
- `G` probably better to not allow changes 

Auth check makes sense of course. Use function `VIEW_AUTHORITY_CHECK` with `view_action = 'U'`

**Comment by mbtools** [comment]
delivered
