### ISSUE TITLE
"Repository Overview" or "Repository List"

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6142]
Overview is used in a few places, List in most places. 

Code:
https://github.com/search?q=repo%3AabapGit%2Fabapgit+%22repository+overview%22&type=code
https://github.com/search?q=repo%3AabapGit%2Fabapgit+%22repository+list%22&type=code

Docs:
https://github.com/search?q=repo%3AabapGit%2Fdocs.abapgit.org+%22repository+overview%22&type=code
https://github.com/search?q=repo%3AabapGit%2Fdocs.abapgit.org+%22repository+list%22&type=code

Suggestion: change "Overview" to "List"

**Comment by larshp** [comment]
🤷‍♂️
