### ISSUE TITLE
Add properties like git-commit-id-maven-plugin

### ISSUE THREAD

**Issue by IvxLars** [abapGit/abapGit#6151]
Similar to git-commit-id, it would be nice if abapGit could update a local source file with properties like git.tags, git.dirty, git.commit.id.abbrev etc.. like if abapGit could point to a file, and if it contained a specific property, it could be updated when abapGit did git actions.

This would allow users/testers of the software to see specificly what version of code was present on the system (given the properties were exposed to the user by the software developers)

**Comment by larshp** [comment]
I guess git-commit-id-maven-plugin (https://github.com/git-commit-id/git-commit-id-maven-plugin ?) calls the git client to determine the properties, suggest using https://docs.abapgit.org/development/api.html

The system can become git.dirty if someone changes a object, ie. without triggering abapGit, so having abapGit write this attribute at some time(triggered by user) would be wrong anyhow

**Comment by IvxLars** [comment]
Yes, I see the dirty flag as a problem to figure out without a manual triggering. Maybe hook into SAP compile engine? :)

The commit-id would still be nice to have access to as a user, even if dirty, although it will be way less trustable.

**Comment by larshp** [comment]
I guess git-commit-id-maven-plugin is triggered by the build/test process? Which then gets the information, I guess its not continuously kept up to date?

**Comment by IvxLars** [comment]
git-commit-id reads in the build process only, yes.

**Comment by mbtools** [comment]
stale. closing
