### ISSUE TITLE
filter option during selective pull on input field for filter conditions at object type or an object name.

### ISSUE THREAD

**Issue by alokranjanct333** [abapGit/abapGit#6152]
Hello Team, 

we are trying to use abapGIT for lift and shift from ECC system to S4HANA system but there are some object types like enhancements or append structure to the standard table that we do not want to import and mass deselect during import in the target system.  but as of now, there is no filter option available on the pop screen.

it would be nice to have an input field for filter conditions at object type or an object name.

![image](https://user-images.githubusercontent.com/19769040/225398544-c7e527d4-23f9-4cf3-bdef-0a873f24fa88.png)

**Comment by larshp** [comment]
try updating to the latest version, the pull dialog was changed in https://github.com/abapGit/abapGit/pull/6093

**Comment by alokranjanct333** [comment]
Thanks, Lars, this is an awesome and very useful feature.
As mentioned earlier we are using abapGIT for lift and shift from ECC to S4HANA system but getting a lot of errors due to object dependency is not available in the target system. we are doing our best to pull more and more objects based on the dependent packages from source to target, but we feel there could be a better way to achieve it.

Please help with your valuable inputs/ or better strategy if possible. Thanks in advance.

**Comment by larshp** [comment]
well, it depends, lots of questions to be answered

if it is custom dependencies that are the problem, then I recommend using https://github.com/marketplace/abaplint/ to verify the integrity of the repository before pulling

**Comment by alokranjanct333** [comment]
thanks, Lars for your valuable input, will try to follow it.

**Comment by sbcgua** [comment]
To find dependencies while in the system you can also have a look into this: https://github.com/sbcgua/crossdeps

**Comment by mbtools** [comment]
If you don't want objects in the target system, then why did you stage/commit them to the repository?

**Comment by alokranjanct333** [comment]
I want to pull reuired objects into the target system so I am staging them to the repository. I am using offline mode for this process. I am facing syntax issues related due to dependent objects missing in the target system and am looking for a better approach to perform it.

**Comment by alokranjanct333** [comment]
> To find dependencies while in the system you can also have a look into this: https://github.com/sbcgua/crossdeps

Sure, will check this point. Many thanks.

**Comment by larshp** [comment]
if using abapGit in a professional project, consider [supporting abapGit](https://abapgit.org/sponsor.html)

**Comment by larshp** [comment]
@alokranjanct333 did you solve the issue, can this issue be closed?

**Comment by mbtools** [comment]
The pull dialog has filter option since https://github.com/abapGit/abapGit/pull/6093
