### ISSUE TITLE
new online repo, trim/condense url

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#6156]
![image](https://user-images.githubusercontent.com/5888506/225838495-3d30549e-138d-4539-8cce-b2b9377c106a.png)

same as https://github.com/abapGit/abapGit/issues/4284

**Comment by mbtools** [comment]
I can't reproduce this. The URL is trimmed and save properly:

![image](https://user-images.githubusercontent.com/59966492/225909204-b0fc4aec-6049-4092-a7c7-909e02d3c0aa.png)

It looks like in your example there's another character in the URL between AQBG and the spaces at the end ;-)
