### ISSUE TITLE
Concurrent develop same object by different abaper

### ISSUE THREAD

**Issue by hock37wong** [abapGit/abapGit#6160]
Hi, how abapgit help to concurrent develop the same object by different abaper at the same time? Thanks

**Comment by larshp** [comment]
putting the sourcecode to git gives a better overview of what changed when

but branching in traditional ABAP systems is done by having multiple systems, in one system one developer can change a source file at a time

git is just files, allowing easy branching, anyone can edit files there(eg. using vscode)

**Comment by hock37wong** [comment]
Do we need to have SAP instance development environment for each abaper instead of to achieve  parallel development for same technical object in development box?

**Comment by larshp** [comment]
one SAP instance per developer will achieve parallel development, yes, https://www.nuveplatform.com can help you setting this up

depending on what your challenges or goals are, there might be other solutions

**Comment by hock37wong** [comment]
Hi @larshp , thanks for the recommendation. 

My current challenge is the technical object, example an abap report, when developer A make the change for change request 12345, and sometimes there will be a bug fix for the same abap report that assigned to developer B. Due to the abap report is locked by developer A, it need to revert/comment the change, then only can pass on to developer B to fix the bug. 

So, without setup the instance development environment, is there other way to solve the locking issue and able to parallel development without conflict? Thanks again.

**Comment by mbtools** [comment]
In short, no. 

@hock37wong, parallel development of the same object in the same system is not possible in ABAP. The typical landscape setup for emergency fixes bypassing the regular development flow (Dev > Test > Prod) is to have a separate bug fix system (Fix > Test > Prod, or Fix > Prod).

**Comment by jlootens** [comment]
Can abapGit help by logging all changes in a transport (call it #1), deleting transport #1 (releasing locks) whilst restoring the previous versions of the objects. Then, once the fix is done and transport (#2) released, provide a means to recreate #1 and showing where changes were made in #2 so they can be merged?

**Comment by larshp** [comment]
> Can abapGit help by logging all changes in a transport (call it #1), deleting transport #1 (releasing locks) whilst restoring the previous versions of the objects. Then, once the fix is done and transport (#2) released, provide a means to recreate #1 and showing where changes were made in #2 so they can be merged?

yes

however, IMHO, its better to build/evolve processes to try avoiding that situation all-together. That could be improving testing, reducing change sizes, etc.

**Comment by hock37wong** [comment]
> In short, no.
> 
> @hock37wong, parallel development of the same object in the same system is not possible in ABAP. The typical landscape setup for emergency fixes bypassing the regular development flow (Dev > Test > Prod) is to have a separate bug fix system (Fix > Test > Prod, or Fix > Prod).

Thank you @mbtools
