### ISSUE TITLE
After Pushing of Package Data, BRF+ Application not getting Push to Github Repo. 

### ISSUE THREAD

**Issue by SugguSandeep29** [abapGit/abapGit#6175]
Hi 

As my Transport gets refresh, while I push package data to Repository, BRF+ Application was not done. 

Thank You,
Suggu Sandeep.

**Comment by larshp** [comment]
Hi, which steps do you perform in the system?

Note, nothing automatically happens(unless its set up), like command line git push and pull happens upon request by the user

**Comment by SugguSandeep29** [comment]
FDT1

FDT/BRFplus: Customizing Application

**Comment by SugguSandeep29** [comment]
Thank You @larshp for solving my problem
