### ISSUE TITLE
Close command palette with escape key

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6177]
Currenty, command and repo palette are opened and closed by `F1` or `F2`. Either change this to `ESC` or at least add `ESC` as another key to close the palettes.

**Comment by sbcgua** [comment]
Very good idea, but there were some caveats if I remember well, I tried that for the initial feature. If I remember well, ESC was first captured by SAP GUI and not transfered to JS ... or something like that. But anyway, worth another try, certainly ESC would be the optimal way to close them

**Comment by mbtools** [comment]
i now remember. you had mentioned it in regards to hotkeys... https://github.com/abapGit/abapGit/issues/5926
