### ISSUE TITLE
Admin fields not cleared in NROB

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#6179]
https://github.com/abapGit/abapGit/blob/018e56cfcf8335bafa33c7468e18121084adada9/src/objects/zcl_abapgit_object_nrob.clas.abap#L283

![image](https://user-images.githubusercontent.com/5270359/228855832-b4554596-e055-4eda-969d-d2e016ad6ced.png)

Also there is an ISOLANG field and ABAP_LANGUAGE_VERSION on the remote version.

**Comment by fabianlupa** [comment]
Between 1809 and 2021 these fields were added to TNRO:

```
ABAP_LANGUAGE_VERSION	ABAP_LANGUAGE_VERSION	CHAR	1	0	0	ABAP Language Version
STATUS					R3STATE					CHAR	1	0	0	ABAP: Program Status (Active, Saved, Transported...)
CHANGED_AT				TIMESTAMPL				DEC		21	7	0	UTC Time Stamp in Long Form (YYYYMMDDhhmmssmmmuuun)
CHANGED_BY				SYUNAME					CHAR	12	0	0	User Name
UNAME					AS4USER					CHAR	12	0	0	Last Changed By
UDATE					AS4DATE					DATS	8	0	0	Last Changed On
UTIME					AS4TIME					TIMS	6	0	0	Last changed at
ENAME					AUTHOR					CHAR	12	0	0	Author of the Repository object
EDATE					AS4DATE					DATS	8	0	0	Last Changed On
ETIME					AS4TIME					TIMS	6	0	0	Last changed at
IGNORE_GROUP			NRIGNORE				CHAR	1	0	0	Ignore Settings for Groups in Cloud
```

And yes, the open source serializer does not account for this...

**Comment by larshp** [comment]
oh, thought this issue was fixed, anyhow good first issue, pull requests welcome

**Comment by larshp** [comment]
@fabianlupa try again, latest version

cannot really do anything about ISOLANG, as abapGit doesnt serialize it

**Comment by larshp** [comment]
closing

**Comment by fabianlupa** [comment]
Thanks! We somehow managed to update the SFLIGHT reference scenario and there are lots of other diffs. I'll open some more issues next week.

**Comment by larshp** [comment]
its just really difficult to test, due to missing new dev edition

**Comment by fabianlupa** [comment]
Now it looks like this:

![image](https://github.com/abapGit/abapGit/assets/5270359/7084496c-ca90-4072-a8ee-d9f9fec34281)

So I think the following tasks are still remaining:

- Clear ATTRIBUTES- UNAME, UDATE, UTIME

**Comment by larshp** [comment]
copy pasta, let me fix that, sec

**Comment by larshp** [comment]
@fabianlupa try this one https://github.com/abapGit/abapGit/pull/6280
