### ISSUE TITLE
Missing checksums after initial pull

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6188]
When pulling objects into a new abapGit repo, checksums of the pulled files are not written to the database (except for `.abapgit.xml`).

Example repo and checksums:

![image](https://user-images.githubusercontent.com/59966492/229614361-41870a70-0321-4185-8ea4-9db99d232ed8.png)

![image](https://user-images.githubusercontent.com/59966492/229614384-84c96764-6a06-4336-885c-4a05b61313a3.png)

Expected behavior:

Checksums for all files should be persisted (https://github.com/abapGit-tests/AQQU/tree/main/src).

Root cause:

https://github.com/abapGit/abapGit/blob/c5ed76c73a6766db7f9710de636a0c418ed6b882/src/repo/zcl_abapgit_repo_checksums.clas.locals_imp.abap#L235-L244

This comment is missing the case above. After initial pull, local files have not been serialized yet and therefore `it_local` does not contain any files of new objects (it only contains `.abapgit.xml`). 

@sbcgua can you please have a look how to update the `if sy-subrc <> 0` branch to get the proper checksums stored?

PS: This goes back to https://github.com/abapGit/abapGit/pull/5328.

**Comment by sbcgua** [comment]
will have a look
