### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by ro-fi** [abapGit/abapGit#6192]
Hello,

I'm following the procedures how to install abapGit from https://docs.abapgit.org/guide-install.html and https://help.sap.com/docs/btp/sap-business-technology-platform/install-and-set-up-abapgit.
I started SE38, created a new program, I followed the link https://raw.githubusercontent.com/abapGit/build/main/zabapgit_standalone.prog.abap and copied the code.
Attempt to activate returns an error: Line 36579: Type "CL_OO_SOURCE" is unknown.
I also found the closed issue: https://github.com/abapGit/abapGit/issues/5895

Where and how can I get code that contains the latest fixed version?

Thanks!

**Comment by larshp** [comment]
which version are you on? abapGit works from 702 and up

**Comment by ro-fi** [comment]
Hello,
It's 751: SAP_ABA	75I	0000	-		Cross-Application Component
Thanks.

**Comment by larshp** [comment]
I cannot find any static references to CL_OO_SOURCE, can you post a screenshot of the syntax error?

![image](https://user-images.githubusercontent.com/5888506/230091968-8a0a4171-9d93-4b58-9165-eae6f321d04d.png)

**Comment by ro-fi** [comment]
The code is from: https://raw.githubusercontent.com/abapGit/build/main/zabapgit_standalone.prog.abap (link from installation page)

<img width="900" alt="abap_git_error" src="https://user-images.githubusercontent.com/22345085/230128096-f584ff68-9ff6-4dac-a956-3d708380e04c.png">

**Comment by larshp** [comment]
it doesnt look like the source code from https://raw.githubusercontent.com/abapGit/build/main/zabapgit_standalone.prog.abap

![image](https://user-images.githubusercontent.com/5888506/230147505-b894ec04-dded-4998-964c-fc17039cde01.png)

**Comment by ro-fi** [comment]
Hello,
Mystery... the error is gone. Copied it again from https://raw.githubusercontent.com/abapGit/build/main/zabapgit_standalone.prog.abap 
and it's a different code. Checked IE history - visited the same page yesterday...
Thanks!

**Comment by larshp** [comment]
cool, closing
