### ISSUE TITLE
SLDD: Generic Application Access Rules (Definition)

### ISSUE THREAD

**Issue by ed-holland** [abapGit/abapGit#6215]
This object is used for Access Rule Definitions defined in transaction SLDW.

These rules are used to circumvent SQL Injections. Abap coding needs to be adjusted to use these rules.
The Rule definitions needs to be transported via the AddOn and GIT support will help with change management.
More information can be found in the SAP Guide "Securing_Remote_Function_Calls_RFC".

The details of this object seem to be located in the following tables:

SLDW_HEADER
SLDW_HEADERT (by Language)
SLDW_ELEMENTS

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion (#5912).
