### ISSUE TITLE
SUCD: Scenario for Switchable Authorization Check (Definition)

### ISSUE THREAD

**Issue by ed-holland** [abapGit/abapGit#6216]
This object is used for Switchable Authorisations defined in transaction SACF

These authorizations can be activated/deactivated by the customer without a code change. They allow for more or less security for the customer. Abap coding needs to be adjusted to use these type of authorization.

The Switchable Authorisations needs to be transported via the AddOn and GIT support will help with change management.
More information can be found in the SAP Guide "Securing_Remote_Function_Calls_RFC".

The details of this object seem to be located in the following tables:

TOBJ_CHK_CTRL_D
TOBJ_CHK_CTRL_DT (by Language)
TOBJ_CHK_CTRL_DH
TOBJ_CHK_CTRL_R

**Comment by fabianlupa** [comment]
> The Switchable Authorisations needs to be transported via __the AddOn__

Which Addon are you refering to? I remember using SACF without any additional components installed on the system.

**Comment by ed-holland** [comment]
Our own AddOns that we create using the AAK. We would like to have all that is contained in the AddOn, also to be in AG.

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion (#5912).
