### ISSUE TITLE
abapGit cannot connect to company repo

### ISSUE THREAD

**Issue by ro-fi** [abapGit/abapGit#6230]
Hello,
I've installed abapGit plugin for Eclipse and I'm trying to connect to my company internal github.
I can do it using http(s) from the browser (any browser) or using git plugin for Eclipse, but I cannot connect to it from the abapGit.

Eclipse: 2022-12.
abapGit: abapGit for ABAP Development Tools (ADT) 1.7.1 org.abapgit.adt.feature.feature.group
Eclipse EGit: 6.4.0.202211300538-r org.eclipse.egit.feature.group

Steps to replicate:
Open **abapGit Repositories** view, click Add and enter url copied from the github repo.
<img width="332" alt="abapgit-1" src="https://user-images.githubusercontent.com/22345085/232905071-54fc0e88-726e-4eef-8427-c06e4150b53b.png">

Eclipse network settings:
<img width="600" alt="abapgit-2" src="https://user-images.githubusercontent.com/22345085/232905363-b2a29617-476e-4c09-ad7f-046fe8454e13.png">

**Comment by larshp** [comment]
abapGit connects to git from the ABAP application server, so it must be possible for the application server to contact the git host

NIEHOST_UNKNOWN typically means that there is a network connection issue from the application server to the git host

**Comment by larshp** [comment]
no reply, closing
