### ISSUE TITLE
TABU: Data json objects deleted in background push

### ISSUE THREAD

**Issue by zag-steve** [abapGit/abapGit#6231]
Hi,

I have a repository set up with several data definitions. When this repository is set to push in the background the conf.json and the tabu.json files are deleted from the remote.

The deletion only occurs when actually running zabapgit in background. It does not happen when the simulating background mode in the gui,

Debugging setting sy-batch = 'X" I found that in ZCL_ABAPGIT_STATE_LOGIC method ZIF_ABAP_STATE_LOGIC~GET that the conf.json and tabu.json files are picked up on the remote but not for the local causing them to be deleted later in the process.

local:
![image](https://user-images.githubusercontent.com/7203077/232917697-45850146-1cd9-415e-bb4a-a20a6938ad76.png)

remote:
![image](https://user-images.githubusercontent.com/7203077/232917642-34a88681-f51f-4b5e-ab70-a20e594da96f.png)

push_deletions:
![image](https://user-images.githubusercontent.com/7203077/232918211-305c5100-d81f-4678-b1e4-ae10e189977d.png)

**Comment by mbtools** [comment]
Not really a bug but works as designed. We currently don't persist the data config locally. Therefore, the config is not available for a background push (which doesn't read from remote first).

**Comment by larshp** [comment]
pull requests welcome

**Comment by mbtools** [comment]
Also visible in job spool list:

![image](https://github.com/abapGit/abapGit/assets/59966492/166a0cef-fd87-4d1c-9bd6-62e3834bab43)

Found an easy fix...
