### ISSUE TITLE
Character set conversion for one or more characters is not possible

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#6234]
On the face of it, this might look like the return of #5721 but there are a couple of imho noteworthy differences:
1. it happens during installation of abapGit dev using the current standalone version
2. the same error is shown when creating an ABAP Project in Eclipse: I wanted to check the call stack, Eclipse started, tried adding a new project since this system was not yet known, got the same message in a popup

![grafik](https://user-images.githubusercontent.com/25269970/233572612-cb9fb49d-84b8-4d98-b07c-9ae0533115ff.png)
![grafik](https://user-images.githubusercontent.com/25269970/233575100-ab4c06a3-8230-411d-a6f7-007736f28f81.png)

Before we waste time on the first one, I am going to ask our internal IT to apply the [corrective note for ADT](https://me.sap.com/notes/1767013).  Then I will update this issue either as documentation (if solved) or with more info on the call stack,

**Comment by AndreaBorgia-Abo** [comment]
Note applied, Eclipse issue is solved, that in standalone aG is still present.

This is where it happens and the relevant field contents:
![grafik](https://user-images.githubusercontent.com/25269970/233603847-231890f2-228b-475a-994d-5a9359db8427.png)
![grafik](https://user-images.githubusercontent.com/25269970/233603950-205b9103-844c-4de5-ad12-144d7beff141.png)

System info:
SAP_BASIS SAPKB73105
SAP_ABA SAPKA73105
Kernel 720 Sup.Pkg lvl. 800

**Comment by larshp** [comment]
is it a unicode system?

**Comment by AndreaBorgia-Abo** [comment]
![grafik](https://user-images.githubusercontent.com/25269970/233621751-ae866753-3fc5-4fa9-b2f6-ed78d179e8f3.png)

**Comment by larshp** [comment]
https://github.com/oblomov-dev/abap2UI5/issues/183

**Comment by mbtools** [comment]
looks like non-unicode systems can't handle the BOM (first 3 bytes `EFBBBF`) 

please test this fix:

```abap
  METHOD xstring_to_string_utf8.

    DATA lx_error  TYPE REF TO cx_root.
    DATA lv_data TYPE xstring.
    DATA lv_length TYPE i.

    " Remove BOM for non-Unicode systems
    lv_data = iv_data.
    IF cl_abap_char_utilities=>charsize = 1 AND xstrlen( lv_data ) > 3 AND
      lv_data(3) = cl_abap_char_utilities=>byte_order_mark_utf8.
      lv_data = lv_data+3.
    ENDIF.

    lv_length = iv_length.
    IF lv_length <= 0.
      lv_length = xstrlen( lv_data ).
    ENDIF.

    TRY.
        IF go_convert_in IS INITIAL.
          go_convert_in = cl_abap_conv_in_ce=>create( encoding = 'UTF-8' ).
        ENDIF.

        go_convert_in->convert(
          EXPORTING
            input = lv_data
            n     = lv_length
          IMPORTING
            data  = rv_string ).

      CATCH cx_parameter_invalid_range
            cx_sy_codepage_converter_init
            cx_sy_conversion_codepage
            cx_parameter_invalid_type INTO lx_error.
        zcx_abapgit_exception=>raise_with_text( lx_error ).
    ENDTRY.

  ENDMETHOD.
```

**Comment by AndreaBorgia-Abo** [comment]
@larshp The quick hack from the linked issue does indeed not fix the exception: it goes only a little further.
@mbtools that works, thanks :) I was looking at RSCPINST to detect unicode in systems, different solution but this looks simpler.

**Comment by mbtools** [comment]
Fix: https://github.com/abapGit/abapGit/pull/6237

After applying the fix, could you please run the unit tests for `zcl_abapgit_convert` on the non-Unicode system?

**Comment by AndreaBorgia-Abo** [comment]
@mbtools 
![grafik](https://user-images.githubusercontent.com/25269970/233912901-d0bfdd48-1201-4d46-8d0b-70ca6929ab55.png)

**Comment by mbtools** [comment]
Thanks for testing!
