### ISSUE TITLE
Cannot run unit tests on NW release >=756 -> Not supported in your NW release

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#6236]
Running Advanced > Unit Test gives 
![grafik](https://user-images.githubusercontent.com/17437789/233647679-5bc05d41-ed97-42fc-9f0c-f5df9f2c2f9d.png)
![grafik](https://user-images.githubusercontent.com/17437789/233648020-c895a8c2-53f1-4ab2-beff-03fe2ac0ae59.png)

![grafik](https://user-images.githubusercontent.com/17437789/233648749-bdf44a7e-e5d1-4992-92f6-2f831a3e1b1e.png)

vs 752 SP04
![grafik](https://user-images.githubusercontent.com/17437789/233648178-07dbc97c-3854-40d5-96fd-c4f0cd396122.png)

**Comment by mbtools** [comment]
Can I get a 756 docker image, please? 😉

**Comment by larshp** [comment]
well, need to find another way to hack it

if there is no way to do it in ABAP, we can call the REST ADT API from ABAP
