### ISSUE TITLE
CLASNAME and TPCLASS shown in diff

### ISSUE THREAD

**Issue by dominikpanzer** [abapGit/abapGit#6248]
Hi,
when developing exception classes on ABAP steampunk the field <CLSNAME>ZCX....</CLSNAME> gets serialized. Importing this code into a 7.50 system works fine, but abapGit (1.123.0) shows a diff.

the same thing seems to happen with packages, but here the diff shows a field called <TPCLASS>X</TPCLASS>

the field doesn't seem to be important(?), should I simply "manually delete" it or push from the 7.50 system to overwrite the serialized infos in the repo?

Example:
https://github.com/dominikpanzer/RESULT-for-ABAP

**Comment by larshp** [comment]
whats the actual diff? can you help posting a screenshot?

**Comment by dominikpanzer** [comment]
![grafik](https://user-images.githubusercontent.com/54714566/235690208-d2d918f6-8ea0-4c14-8859-d85909a333c2.png)

**Comment by dominikpanzer** [comment]
![grafik](https://user-images.githubusercontent.com/54714566/235690542-59fe51fe-d419-4dd0-865e-6edbd75b2acf.png)

**Comment by larshp** [comment]
CLSNAME = https://github.com/abapGit/abapGit/blob/main/changelog.txt#L185, released 2022-09-19

**Comment by dominikpanzer** [comment]
well maybe it somehow doesn't work  for exception classes? "normal" classes work fine?
or maybe the abapgit version on the steampunk trial is older than the fix? is there any way to see the abapgit versionnumber?

it should have been this change, shouldn't it?
https://github.com/abapGit/abapGit/pull/5755/files

**Comment by mbtools** [comment]
#6251 fixes the diff for the package. 

The diff for the class is due to old version on BTP (I think it's very old, like 1.87). Current version clears the classname:

![image](https://user-images.githubusercontent.com/59966492/235902032-be1f25fe-4b7a-4c98-a4f0-3e9821b4e4e5.png)

![image](https://user-images.githubusercontent.com/59966492/235901998-58c30491-fcbf-4284-ba9a-ee10c7cc1153.png)

**Comment by dominikpanzer** [comment]
ok, thanks for the infos and the fix Marc!

**Comment by ConjuringCoffee** [comment]
Unfortunately, I'm still having this issue. 

This is from the CodePal repository where I just executed a pull and had this object overwritten:
![image](https://github.com/abapGit/abapGit/assets/72548231/be26d1f3-6655-40ce-849a-ede6ffe0bda8)

abapGit is on the latest version; I just updated it. 

Does the fix only work if the `<CLSNAME>` entry isn't already stored in git?

**Comment by mbtools** [comment]
Not your fault. The CodePal repo is not up-to-date.
