### ISSUE TITLE
SUSH - Deletion not permitted

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#6252]
Hmm, trying to update the SFLIGHT reference scenario from 2021 to 2022.

SU2X 041

![image](https://user-images.githubusercontent.com/5270359/235914935-b3fd10f9-daee-460e-8f02-2ac9838ec1f0.png)

![image](https://user-images.githubusercontent.com/5270359/235915021-610cb3a1-72da-427c-b2e2-8ec5c0bd846e.png)

![image](https://user-images.githubusercontent.com/5270359/235915061-948684b7-0a26-400e-86bb-704cceaaf597.png)

![image](https://user-images.githubusercontent.com/5270359/235915260-7e643791-aeb1-4a02-8903-427cfab8db78.png)

**Comment by fabianlupa** [comment]
![image](https://user-images.githubusercontent.com/5270359/235951546-a12704ba-5bf1-4f14-8bb2-cfffc0222fa0.png)

**Comment by mbtools** [comment]
i checked https://github.com/SAP-samples/abap-platform-refscen-flight and as far as I can tell, the `iwsv` objects are not part of the repo 😉

**Comment by fabianlupa** [comment]
Well well well, these IWSV objects do exist in TADIR but do not exist in /IWBEP/I_MGW_SRH, which is why exists returns false and they are removed from abapGit's TADIR read. Since they aren't on the remote either as you mentioned no diff and therefore no deletion I guess.

**Comment by mbtools** [comment]
i'm not familiar with these object types. to remove left-over tadir entries, add them to a transport and release it. 

if they are generated, then the generating object type is responsible for removing them (incl. tadir).

**Comment by fabianlupa** [comment]
Unfortunately I don't know how to re-create them correctly.

Also how can they be left over if DBTABLOG indicates they were just created? I would probably opt for uninstalling the repo completely, deleting any objects left in the packages and then pulling fresh at this point.

**Comment by mbtools** [comment]
are the screenshots from the first try to uninstall or a subsequent try? if you tried before, then iwsv were removed but leftover the tadir. or the iwsv objects are in an open transport (release would remove the tadir). 

cleaning up manually is certainly an option too

**Comment by larshp** [comment]
> I don't think it's worth it to historically reconstruct the issue. I'll try uninstall, cleaning up and reinstall.

so close?
