### ISSUE TITLE
Error "process_stage_list: empty list" on execution of commit with objects to be removed

### ISSUE THREAD

**Issue by mraht** [abapGit/abapGit#6253]
If I try to stage objects to be removed I get the following error when I click on "Commit Selected":
![image](https://user-images.githubusercontent.com/99023738/235984013-79b3aa3f-fab7-4cdd-9077-6ab3f02d47a3.png)

Restarting abapGit doesn't fix the error.

Version: 1.123.0 - Developer Version

**Comment by christianguenter2** [comment]
Works for me. Do you use SAP GUI for Windows and the the Internet Explorer browser control?
https://docs.abapgit.org/guide-sapgui.html#sap-gui-for-windows

**Comment by mbtools** [comment]
Please include the output of "Debug Info" (from the Tools Menu on the Repository List).

**Comment by mraht** [comment]
As requested: [abapGit_Debug_Info_20230504_201158.docx](https://github.com/abapGit/abapGit/files/11400243/abapGit_Debug_Info_20230504_201158.docx)

**Comment by mraht** [comment]
Ok, I had to set the browser control from Edge to Internet Explorer. Thanks @christianguenter2.
