### ISSUE TITLE
Illegal Type in ZCL_ABAPGIT_DATA_UTILS=>IS_CUSTOMIZING_TABLE

### ISSUE THREAD

**Issue by mabek** [abapGit/abapGit#6270]
Hi,

I am getting an Illegal Type dump in S4 2020 .
For  METHOD ('XCO_CP_ABAP_DICTIONARY')=>database_table parameter iv_name type SXCO_DBT_OBJECT_NAME is expected in my system so my suggestion is to change it to:

        CALL METHOD ('XCO_CP_ABAP_DICTIONARY')=>database_table
          EXPORTING
            iv_name           = CONV SXCO_DBT_OBJECT_NAME( iv_name )

**Comment by larshp** [comment]
try changing `iv_name           = CONV SXCO_DBT_OBJECT_NAME( iv_name )` to `iv_name = iv_name(16)`

**Comment by mabek** [comment]
Thank you!
I guess it is a cx_sy_dyn_call_illegal_type dump?
yes!


try changing iv_name           = CONV SXCO_DBT_OBJECT_NAME( iv_name ) to iv_name = iv_name(16)

That works too
