### ISSUE TITLE
Git cmd warning LF will be replaced by CRLF

### ISSUE THREAD

**Issue by norman003** [abapGit/abapGit#6287]
1. download zip
2. unzip zip
3. git add .
    RESULT
    warning: in the working copy of 'src/zabap.xml', LF will be replaced by CRLF the next time Git touches it
![image](https://github.com/abapGit/abapGit/assets/33376952/122a3b16-7ebc-41f8-9313-a9a9f82f8371)
4. git zip package
5. upload zip - then get difference by this
![image](https://github.com/abapGit/abapGit/assets/33376952/3a88f7dc-2d9a-47ed-abd0-5b3ed38f0e6d)

**Comment by larshp** [comment]
use config

**Comment by mbtools** [comment]
`.gitattributes` and `.editorconfig` specify to use `lf`. Configure your system to use those settings.
