### ISSUE TITLE
Diff ignore files delete when pull

### ISSUE THREAD

**Issue by norman003** [abapGit/abapGit#6288]
ignore files ok
![image](https://github.com/abapGit/abapGit/assets/33376952/476857d2-f9dc-44f9-99fd-8dcce1179368)
![image](https://github.com/abapGit/abapGit/assets/33376952/27343830-b44d-48e2-a5a4-aed6fb33b3a4)

when pull, I cancel
ignore files deleted
![image](https://github.com/abapGit/abapGit/assets/33376952/a5d86439-fdc7-48cb-a396-2cb273d724f9)

**Comment by larshp** [comment]
stage and commit changes before pulling
