### ISSUE TITLE
Push all source codes stored in ABAP version management

### ISSUE THREAD

**Issue by Srikar-Poshetti** [abapGit/abapGit#6293]
Push all the source codes which are maintained in the ABAP Version Management. Ex: for a report in SE38 we have 4 versions available, can we push all the 4 Versions to a branch in the remote? 

Did anyone ever tried or do we have this functionality? we are using SAP ECC and ABAPGit standalone version.

**Comment by mbtools** [comment]
This works if you commit to the repo every time you release a transport. 

However, I’m not aware of any tool to create the git history based on existing versions in the SAP version history.

**Comment by christianguenter2** [comment]
Maybe [abapTimeMachine](https://github.com/abapinho/abapTimeMachine) could be of some help to achieve something in this direction.
