### ISSUE TITLE
Add "name" to repository settings

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6294]
We are missing a way to store the name of a repository. Every user cloning a repo has to define their own display name or use the default based on the URL (which can be rather cryptic). 

Suggestion:

Add "Name" to the repo settings and store it in `.abapgit.xml`

Updated "Repo Settings" dialog...

- Add name and move version to top 
- Add grouping for "Texts", "Files", and "ABAP"
- Add ABAP Language Version to "ABAP" group

![image](https://github.com/abapGit/abapGit/assets/59966492/58991ce7-a10a-4278-9ea1-808b88932806)

![image](https://github.com/abapGit/abapGit/assets/59966492/46de38bc-46be-4a1b-98cc-f1021b50e5c6)

If a display name is defined in local settings, it overwrites the default, of course.

**Comment by larshp** [comment]
hmm, just dont have it default to something that is stored, it can get difficult if things are not named what they actually is

**Comment by sbcgua** [comment]
I think adding an "official" name to the repo config is a good idea. Same as "name" in the package.json and etc.

Just pls don't name it "repository name" :) just "name" would be fine.

**Comment by mbtools** [comment]
I updated the description and added screenshots for the suggested changes. (note: this will also fix #3509)
