### ISSUE TITLE
Dump at ZCL_ABAPGIT_FILE_DESERIALIZE=>FILTER_FILES_TO_DESERIALIZE (abap 731)

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6329]
![image](https://github.com/abapGit/abapGit/assets/15635498/df9d020e-3e46-4c6a-ac62-62fa1eaa8268)

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/pull/6328 ?

**Comment by sbcgua** [comment]
Yes, probably, looks like the same code. Closing for now.
