### ISSUE TITLE
As there is no password storage, how could we run a push in background ?

### ISSUE THREAD

**Issue by Taryck** [abapGit/abapGit#6330]
Hi all,

I've seen in previous discution that abapGit projet does not plan/want to store password.
How could we provide credential without user interactions in a background job for instance ?

Is there a way to provide crendential outside of abapgit ?
in a way to run without any user interaction in background.

If not I guess this is an interesting feature to provide.

I don't know if it's the right place for this discussion but I do not find any other way to ask about this topic.

Thanks in advance for your time.

**Comment by mbtools** [comment]
You can create an RFC destination (where you store the credentials) and supply it to abapGit via exit:
https://docs.abapgit.org/user-guide/reference/exits.html#create-http-client

**Comment by Taryck** [comment]
I guess I've got my answer in ZCL_ABAPGIT_PASSWORD_DIALOG=>POPUP
  METHOD popup.

    IF zcl_abapgit_ui_factory=>get_frontend_services( )->gui_is_available( ) = abap_true.
      PERFORM password_popup
        IN PROGRAM (sy-cprog)
        USING iv_repo_url
        CHANGING cv_user cv_pass.
    ELSE.
      "Extract user credentials from the environment...
      "Class ZCL_ABAPGIT_DEFAULT_AUTH_INFO is part of https://github.com/abapGit/ADT_Backend.
      "It stores the credentials of a private repository as long as the session exists.
      "Usually this class should belong to abapGit core and a refactoring is recommended.
      "As a temporary solution - and to avoid a DYNPRO_SEND_IN_BACKGROUND dump - a generic
      "call of the getter methods for username and password is implemented by PR#2635.
      TRY.
          CALL METHOD ('ZCL_ABAPGIT_DEFAULT_AUTH_INFO')=>('GET_USER')
            RECEIVING
              rv_user = cv_user.
        CATCH cx_root.
          RETURN.
      ENDTRY.
      TRY.
          CALL METHOD ('ZCL_ABAPGIT_DEFAULT_AUTH_INFO')=>('GET_PASSWORD')
            RECEIVING
              rv_password = cv_pass.
        CATCH cx_root.
          "check if old version with typo in method name exists
          TRY.
              CALL METHOD ('ZCL_ABAPGIT_DEFAULT_AUTH_INFO')=>('GET_PASSOWORD')
                RECEIVING
                  rv_password = cv_pass.
            CATCH cx_root.
              RETURN.
          ENDTRY.
      ENDTRY.
    ENDIF.

  ENDMETHOD.

I just need to create ZCL_ABAPGIT_DEFAULT_AUTH_INFO class with the methods.

Am I Correct ?

**Comment by Taryck** [comment]
May I suggest to add a no_dialog feature to prevent password popup event on foreground ?

With this small update :
class ZCL_ABAPGIT_PASSWORD_DIALOG definition
  public
  final
  create public .

public section.

  **class-data NO_DIALOG type ABAP_BOOL .**

  class-methods POPUP
    importing
      !IV_REPO_URL type STRING
    changing
      !CV_USER type STRING
      !CV_PASS type STRING .

  METHOD popup.

    IF zcl_abapgit_ui_factory=>get_frontend_services( )->gui_is_available( ) = abap_true **AND NO_DIALOG IS INITIAL**.

**Comment by mbtools** [comment]
PRs are welcome! Class-attribute needs to start with `g` (`gv_no_dialog`) and should be private with a set method.

**Comment by Taryck** [comment]
Thanks, Sure I could apply this rule.
However I can't create new branch for that purpose. How should I do PR if I can't create branch ?

**Comment by larshp** [comment]
do a fork and open a PR from the fork, https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by Taryck** [comment]
Done for the Fork and I guess done for the push.
If enhance the RFC Destination feature with a default implementation.
And fix the CREATE_BY_URL that do not support RFC destination (or any HTTP Client) with **prefix_path**.

Let me know
