### ISSUE TITLE
Performance Issue on `ZCL_ABAPGIT_GIT_PORCELAIN=>PUSH` for large stage

### ISSUE THREAD

**Issue by Taryck** [abapGit/abapGit#6332]
The READ TABEL line 30
          READ TABLE lt_expanded ASSIGNING <ls_exp> WITH KEY
            name = <ls_stage>-file-filename
            path = <ls_stage>-file-path.
Takes 99,5% of my running time with very large repo > 100k

I suggest to switch to :
          READ TABLE lt_expanded ASSIGNING <ls_exp> WITH **TABLE KEY search COMPONENTS**
            name = <ls_stage>-file-filename
            path = <ls_stage>-file-path.

and update : zif_abapgit_definitions=>ty_expanded_tt
to
  TYPES:
    ty_expanded_tt TYPE STANDARD TABLE OF ty_expanded WITH DEFAULT KEY
         **WITH NON-UNIQUE SORTED KEY search COMPONENTS name path**.

**Comment by larshp** [comment]
thanks, pull request welcome 😄

**Comment by Taryck** [comment]
No it's Within ABAPGIT code where insert occurs in // with READ
Later on Performance Issue occurs on
        WHEN zif_abapgit_definitions=>c_method-rm.
          DELETE lt_expanded **USING KEY search**
            WHERE name = <ls_stage>-file-filename
            AND path = <ls_stage>-file-path.

And in BUILD_TREES
* files
      LOOP AT it_expanded ASSIGNING <ls_exp> **USING KEY search** WHERE path = <ls_folder>-path.
        APPEND INITIAL LINE TO lt_nodes ASSIGNING <ls_node>.
        <ls_node>-chmod = <ls_exp>-chmod.
        <ls_node>-name  = <ls_exp>-name.
        <ls_node>-sha1  = <ls_exp>-sha1.
      ENDLOOP.
      
I'll try PR but they are painfull and I'm not sure to have the time for that.

**Comment by Taryck** [comment]
by the way :
WHEN zif_abapgit_definitions=>c_method-rm.
DELETE lt_expanded USING KEY search
WHERE name = <ls_stage>-file-filename
AND path = <ls_stage>-file-path.
is not efficient...
as delete with indexed table is slow (rebuild index)

So
    CONSTANTS del_chmod TYPE zif_abapgit_definitions=>ty_chmod VALUE 'DELETE'.
...
        WHEN zif_abapgit_definitions=>c_method-rm.
***          DELETE lt_expanded
*            WHERE name = <ls_stage>-file-filename
*            AND path = <ls_stage>-file-path.
          READ TABLE lt_expanded ASSIGNING FIELD-SYMBOL(<delete>) WITH TABLE KEY search COMPONENTS
            name = <ls_stage>-file-filename
            path = <ls_stage>-file-path.**
          ASSERT sy-subrc = 0.
          **<delete>-chmod = del_chmod.**

          CLEAR <ls_updated>-sha1.       " Mark as deleted

        WHEN OTHERS.
          zcx_abapgit_exception=>raise( 'stage method not supported, todo' ).
      ENDCASE.
    ENDLOOP.

*** Mass delete much faster.
    DELETE lt_expanded WHERE chmod = del_chmod.**

**Comment by mbtools** [comment]
@Taryck please test #6390. Would be nice to know how much faster it is (before/after)

**Comment by larshp** [comment]
@Taryck

**Comment by mbtools** [comment]
We don't have such large test cases. Would still be useful if you use the most recent version and let us know how much faster it is (before/after times) :-)
