### ISSUE TITLE
SAP GUI 8.00 SP>=03 / 7.70 SP>=13 chromium browser control not working properly

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#6339]
Follow up on #4841 
While chromium based browser control is basically working with SAPGUI 800 SP>=03 / 7.70 SP>=13 there are still some ~minor~ major issues. 

- [x] Hotkeys which trigger `sapevent` are not working on some pages (e.g. Repository List and Repository) while others are working (e.g. Stage)
- [ ] External links are broken. E.g. clicking on this link jumps to https://github.comchristianguenter2abapgit.git/
![image](https://github.com/abapGit/abapGit/assets/17437789/50533222-36a0-490a-b58c-671a1dce9174)
![image](https://github.com/abapGit/abapGit/assets/17437789/4859f808-42db-45ea-9b80-d2685df24cec)
- [ ] diff links are broken
![image](https://github.com/abapGit/abapGit/assets/17437789/d8cbf951-cfff-4a73-b3e0-ac2dc8e0079d)
![image](https://github.com/abapGit/abapGit/assets/17437789/09f9a1b8-5625-454e-b48a-03169b1929fb)
![image](https://github.com/abapGit/abapGit/assets/17437789/d8bfadb0-f44a-44c0-abb6-1c0c60eb71e2)

**Comment by christianguenter2** [comment]
Seems there's a new special way how edge control handles `SAPEVENT`...
![image](https://github.com/abapGit/abapGit/assets/17437789/5fbd95bc-abc6-40d4-b010-85eaf5d23c55)

**Comment by christianguenter2** [comment]
Links look like this
![image](https://github.com/abapGit/abapGit/assets/17437789/e6b5f90e-c41a-4ba4-a562-597c28979b77)

And are transformed to this when sent back to ABAP
![image](https://github.com/abapGit/abapGit/assets/17437789/7b44eb18-8669-4417-ba84-9a3b101c70e7)

**Comment by mbtools** [comment]
The edge solution must be compatible with previous apps. a) all is upper case which is wrong and b) characters are removed (I suspect there's more than slash missing). This is some SAP nonsense that should be fixed by SAP.

**Comment by christianguenter2** [comment]
I try to draw SAPs attention:
https://blogs.sap.com/2023/01/20/sap-gui-for-windows-8.00-is-coming-on-27th-of-january-2023-new-features-lifecycle-information/comment-page-1/#comment-680656

**Comment by christianguenter2** [comment]
News from SAP
![image](https://github.com/abapGit/abapGit/assets/17437789/81a280c9-54ce-43b8-88e1-9b7dd846ff0d)

**Comment by jacconijholt** [comment]
Setting the SAP Gui 8.0 Sp3 "Browser Control" to Internet Exploder is a temporary work around until SAP fixes this

![image](https://github.com/abapGit/abapGit/assets/24429365/378cf689-3112-4421-8df7-6940ac2d3eda)

**Comment by christianguenter2** [comment]
Fresh out the press: [3355910 ](https://me.sap.com/notes/3355910/E)

And an update to our favorite note [3331099](https://me.sap.com/notes/3331099/E)
![grafik](https://github.com/abapGit/abapGit/assets/17437789/1ae455d6-3795-4393-9906-40ade9ff9809)

**Comment by christianguenter2** [comment]
SAPGUI 8.00 PL3 Hotfix 1 was released today.
Update from [3355910](https://me.sap.com/notes/3355910/E)
![grafik](https://github.com/abapGit/abapGit/assets/17437789/42f2d5aa-6f24-46b6-8ee2-7a6aa8088159)

**Comment by mbtools** [comment]
I'm testing p3h1 and everything is working 🎉 so far so good

PS: With the edge control, the href links have a strange format but the result on the ABAP side is the same as with IE:

![image](https://github.com/abapGit/abapGit/assets/59966492/f7d4f5a3-73f3-4176-bee9-bd144903cf9d)

**Comment by mbtools** [comment]
same error here. i changed this line and it works for Edge... 

![image](https://github.com/abapGit/abapGit/assets/59966492/29d3ab92-3f6e-42a9-88fa-0a5dd268696b)

But it breaks IE. It just needs a way to distinguish between the two in JS.

**Comment by christianguenter2** [comment]
This seems to work. I'll do more tests and prepare a PR.
```javascript
  function getSapeventPrefix() {
    if (document.querySelector('a[href*="file:///SAPEVENT:"]')) {
      return "file:///"; //Prefix for chromium based browser control
    } else if (document.querySelector('a[href^="sap-cust"]')) {
      return "sap-cust://sap-place-holder/";
    } else {
      return "";
    }
  }

```
