### ISSUE TITLE
Add rku.it GmbH to Consulting and Partner

### ISSUE THREAD

**Issue by bibber0612** [abapGit/abapGit#6342]
Add rku.it GmbH to Consulting and Partner

**Comment by larshp** [comment]
hi, if you want to update the docs, please use https://github.com/abapGit/docs.abapgit.org/edit/main/src/user-guide/other/where-used.md to open a suggestion with the changes to the docs

**Comment by larshp** [comment]
closed with https://github.com/abapGit/docs.abapgit.org/pull/149
