### ISSUE TITLE
FUGR: Some subcreens (as part of function group) aren't imported

### ISSUE THREAD

**Issue by LuKo1** [abapGit/abapGit#6353]
Hello,

My problem is that I transferred the package from one system to another (in offline mode) and most of the subscreens were not imported.

Dynpros are part of the functional group.

I can only see these dynpros in the .xml file for import, but after import only a small part of them are in the object list and then in the system.

Dynpros are not found by FM RS_SCREEN_LIST.

Thanks for any advice.

**Comment by mbtools** [comment]
Try installing a test repo: https://github.com/abapGit-tests/FUGR_maint_view which contains a screen. Does this work properly?

Add your function group (or something similar) to https://github.com/abapGit-tests/FUGR_subscreens so we can debug.

**Comment by LuKo1** [comment]
Thank you, in my case some text elements overlap other elements (as radio buttons) on the screen. I spotted the error in FM 'RPY_DYNPRO_INSERT'. It was also mantioned in the Log, but I overlooked it. Thank you.
