### ISSUE TITLE
Keeping Same Remote Mode properties for two Pepo. from different accounts cannot make push/pull?

### ISSUE THREAD

**Issue by SugguSandeep29** [abapGit/abapGit#6354]
![image](https://github.com/abapGit/abapGit/assets/68318127/633e2b47-fe7f-4118-b728-b20408fb69e6)

The above picture defines.
1 - is my repository, it's got successful push 
2 - is my friend repository, it's not done successfully push.

Both Repository are of different GitHub Accounts but maintained same Remote Mode as pic. shown in below:

![image](https://github.com/abapGit/abapGit/assets/68318127/44ce8218-2999-481a-87fd-b0a9bee35a39)

As I followed according to official Website:

![image](https://github.com/abapGit/abapGit/assets/68318127/9ee08e93-e0b0-4226-b4de-61a8d3163a34)

Is it will be done at the time of Multiple Repositories push, which belongs to one GitHub Account ?

A bit getting confuse.

Thank You,
Suggu Sandeep.

**Comment by mbtools** [comment]
Check user and password for his repo in background settings

**Comment by SugguSandeep29** [comment]
@mbtools 
Should I give SAP Logon details?

**Comment by mbtools** [comment]
No. Does his repo work in general? Which version of abapGit are you using?

**Comment by SugguSandeep29** [comment]
@mbtools 
Yes, It's working fine, 
Standalone Version

**Comment by larshp** [comment]
> GitHub credentials in both of the Repo

yes

**Comment by SugguSandeep29** [comment]
@mbtools , @larshp 

Even though I am collaborator of the of my friend Repository account, 
It's getting Same issue.

**Comment by mbtools** [comment]
you have to enter the GH token in the password field:
https://docs.abapgit.org/user-guide/projects/online/authentication.html

**Comment by larshp** [comment]
@SugguSandeep29 what is the overall scenario? Why is there two repos with the same code? Having 2 sources of truth is always difficult, is one of them a fork, or?

**Comment by SugguSandeep29** [comment]
Hi @larshp @mbtools 

Scenario is.
My Friend Created Repo & I was collaborator of that repo.  

If I am performing Background, Only My Repo. Only getting Push done, 
My Freind Repo. not getting push done

**Comment by mbtools** [comment]
I'm still not sure about the details of this setup. If you want to discuss further, find me on slack https://communityinviter.com/apps/abapgit/abap
