### ISSUE TITLE
IF_PX_MAIN doesn't exist on 7.02

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#6357]
Syntax error when adding the standalone version in a 7.02 IDES system at:
https://github.com/abapGit/abapGit/blob/9075658c3f0998ee859b6c319950179c9a8564c3/src/objects/zcl_abapgit_object_intf.clas.abap#L210
Looks like it's for proxy interfaces. Since the code has been in place for some time I'm assuming it runs on productive installations. 

Unfortunately I have limited access to the system so won't be able to fix or test it. Would be great if someone could reproduce this elsewhere to verify whether it needs fixing or is a fault with that particular installation (missing component?).

**Comment by mbtools** [comment]
I occasionally test the standalone version on 702 and it's working fine. I suspect that the system in question is on a quit low SP level.

**Comment by pokrakam** [comment]
@mbtools is yours an IDES system, & if so have you patched it up?
If that's the case then it's likely a dodgy installation.

**Comment by mbtools** [comment]
I have a NW 7.02, no ides:

![image](https://github.com/abapGit/abapGit/assets/59966492/9191d954-27bf-4b28-b2dc-df794abd7e8f)

The interface was shipped in SP 08:

![image](https://github.com/abapGit/abapGit/assets/59966492/c5e9c515-190c-4fb7-9b21-d2c0f84ee43d)

**Comment by pokrakam** [comment]
Thanks @mbtools for verifying this. I can confirm this was a new 702 IDES instance, as such it was whatever old SP is on the SAP-delivered installation with no further SPs applied. 

Ironically the purpose of the system was to test backwards compatibility of a development and abapGit was the first thing that failed so the work had to be imported via transports. Not sure if it's worth the effort of seeing if this can be addressed, as it is feasible someone else may try to do this. I no longer have access to the systems in question so can't do anything from my end.

**Comment by larshp** [comment]
@pokrakam did you do static analysis with abaplint before importing? did it catch the right stuff?

**Comment by mbtools** [comment]
We could downport to 3.1H, too. I'm sure there's one of those systems out there. 😉 

702 SP 8 was released 2011-05-12. If anyone needs AG to support older software, PRs are welcome 😀

**Comment by pokrakam** [comment]
@larshp do you mean if I did an abaplint analysis of abapGit? No. Yes I linted the target objects, but that's not a 100% certainty, therefore they pulled a new 702 appliance from SAP to validate. There was a dependent class missing in 702 that abaplint didn't catch, but that's a different issue altogether. 

@mbtools I had a look on the CAL site and can see that it's all > 750. So I'm guessing they got the system from whatever SAP offers their partners. Unfortunately this was just a short piece of work and I am no longer involved so can't get any more details. I think it was an older SP.

**Comment by larshp** [comment]
true true, in https://github.com/abapGit/abapGit/blob/main/abaplint.json#L147 we're collecting stuff we know is incompatible
