### ISSUE TITLE
refactor ZCL_ABAPGIT_HTML_POPUPS?

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#6361]
ZCL_ABAPGIT_HTML_POPUPS is a new class for html based popups, however, it follows some of the same disadvantages as the old popup class

it will potentially become one class that needs to know about everything, pull requests, commits, code inspector variants, tags etc.

Suggestion:
make a new package, and have one global class for each popup. Which then can be instantiated where its needed

**Comment by mbtools** [comment]
+1

**Comment by larshp** [comment]
can be started after https://github.com/abapGit/abapGit/pull/6350 is merged

**Comment by sbcgua** [comment]
> that needs to know about everything

Hmm, no it should not, at least there was no such intent in the design. On the opposite it should be an abstract base component to be "composed" into a specific popup. Where item renderer controls the specifics.

I'm not 100% sure it is flexible enough to be honest ... But let's study on an example. What exactly was a problem for #6350 ?

Having said that, the class per popup certainly does make sense. My point is more about reusability of logic inside those. I'm sure 90% of the logic will be common.

**Comment by larshp** [comment]
we can put em all in the new package, then they can be refactored eg. with an abstract base component

**Comment by larshp** [comment]
I'm starting this task now
