### ISSUE TITLE
Missing JSON files break pull, correct procedure?

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#6367]
I enabled the experimental features to explore the translation functionality, tried pulling the current version of ABAP Logger and got the following errors (current aG devel):
![immagine](https://github.com/abapGit/abapGit/assets/25269970/0dc05e0a-9868-411f-b095-679dbdcff697)

This happens on both my MiniSAP installations, A4H (HANA1909) and NPL (7.52SP04); after turning the experimental features off again, the operation could be completed. I suppose this is related to [long texts](https://github.com/abapGit/abapGit/issues/2539#issuecomment-1499033883) 

1. what is the correct approach to pulling repos without translations in place?
2. how to deal with repos with and without translations in the same system?

**Comment by mbtools** [comment]
Unfortunately, there's a conflict between experimental features. remove the following lines:

https://github.com/abapGit/abapGit/blob/6369c57c5646e1e12b39aa69802c48f82cafee72/src/objects/aff/zcl_abapgit_aff_registry.clas.abap#L58-L59

**Comment by larshp** [comment]
I was wondering earlier today, perhaps we should just add multiple experimental flags

**Comment by AndreaBorgia-Abo** [comment]
In that case, I'd rather have them out of code in the user profile:

ag_exp_translation
ag_exp_magicsmoke
And so on and so forth

**Comment by larshp** [comment]
no magic settings, plus if suggesting `GET PARAMETER` its not compatible with ABAP Cloud

**Comment by AndreaBorgia-Abo** [comment]
Yes, GET is what I had in mind, pity for the cloud. I wanted to avoid
impacting the UI for the flags. A Badi perhaps?

**Comment by larshp** [comment]
I'd actually like to adjust the UI, make more flags, make it more visible what each flag means

yea, it requires adjusting the description, but its easy

**Comment by AndreaBorgia-Abo** [comment]
> Remove the following lines:

Thanks for the tip, I'll try that as soon as I can work on it,

**Comment by AndreaBorgia-Abo** [comment]
Right, of course the devel version on our internal system still gets [incorrectly updated](https://github.com/abapGit/abapGit/issues/6035) because reasons and the experimental flags are not available in the standalone version, I'll have to try later at home.

**Comment by AndreaBorgia-Abo** [comment]
Nope, even using the office installations, commenting out those two lines does not lead to a successful pull.
(one older system still cannot reliably pull because of #6035 and the other one works ok without translations)

I have enabled experimental features, checked "LXE translation" with language DE (the main project language is English in ABAP Logger and our system defaults to German, that kind of makes sense as a test)

**Comment by mbtools** [comment]
#6393 will allow enabling features independent of each other. 

Note, LXE is a repo setting and *not* related to the experimental feature flag (which is a global setting).

![image](https://github.com/abapGit/abapGit/assets/59966492/de7fb46f-a84f-4ba4-ab58-44fda35d5aac)

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/pull/6393 merged

**Comment by AndreaBorgia-Abo** [comment]
@mbtools thanks, that was quick!
Once I am back at work I'll do some more testing.

**Comment by mbtools** [comment]
Just keep in mind that so far LXE is enabled for a subset of object types:

https://github.com/abapGit/abapGit/blob/9f8862809068ac44ee47c7a5a8170a00517bcd04/src/objects/texts/zcl_abapgit_lxe_texts.clas.abap#L202-L216

**Comment by larshp** [comment]
@AndreaBorgia-Abo any updates?

**Comment by AndreaBorgia-Abo** [comment]
None at all, sorry, got sidetracked and I am once more away from home.
I'll try next week to find some time, no promises though.

**Comment by AndreaBorgia-Abo** [comment]
With fully up-to-date aG dev version, verified that LXE experimental in "global settings" is present, ticked "use LXE approach" in repo settings for abap-logger, added DE as extra language, pull works on both NPL and A4H.
(a spurious end of file difference remains but the class is activated).
Tomorrow I'll have a quick look in the office with our internal dev systems, for extra safety, but it looks like it is fixed.

**Comment by AndreaBorgia-Abo** [comment]
Ok, pulling abap-logger in our internal systems no longer triggers this issue; I've had once #108 (when running against our gitea instance and no time to investigate now) and I keep getting an end-of-file comparison difference which is harmless, but this issue is gone for me.
![grafik](https://github.com/abapGit/abapGit/assets/25269970/e293229a-f543-4e2c-acc2-e970e5a7b347)

**Comment by mbtools** [comment]
Re: end-of-file... AG always has an empty newline (0a) at the end of source code (in Diff, turn on View > Show Hidden Characters). The repo does not and needs to be updated.
