### ISSUE TITLE
CLAS SEOCOMPOTX stuff is not pulled and interfere with other packages

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6372]
And always remains a diff (in a non-origin system)

![image](https://github.com/abapGit/abapGit/assets/15635498/99631766-72be-483c-90b8-4683fb76f54d)

same for INTF

**Comment by sbcgua** [comment]
And also seems to interfere with other unrelated objects from another package ... hmm!!!
Is it possible to disable this feature ?

![image](https://github.com/abapGit/abapGit/assets/15635498/9b924508-706a-4152-a7b0-51028caddd5f)

**Comment by albertmink** [comment]
Do you have a mismatch of logon language and original language of the object?

**Comment by sbcgua** [comment]
No, it's EN-EN

**Comment by mbtools** [comment]
Looks like system is running in old version. Needs https://github.com/abapGit/abapGit/pull/5755, at least v1.118.0

Test with https://github.com/abapGit-tests/CLAS_docu

**Comment by sbcgua** [comment]
Latest
![image](https://github.com/abapGit/abapGit/assets/15635498/dec454a1-e0c9-4e86-9871-04ab955b55da)

**Comment by mbtools** [comment]
Strange. These are direct updates on DB:

https://github.com/abapGit/abapGit/blob/main/src/objects/oo/zcl_abapgit_oo_base.clas.abap#L260-L283
