### ISSUE TITLE
TABU: Cannot add table data to offline repo

### ISSUE THREAD

**Issue by mathieulawnik** [abapGit/abapGit#6378]
I have created an offline repository and would like to add table data to it. I clicked "Advanced > Beta - Data" and have added tables from a transport request. When I click "Back" there is no visible object type TABU in the repo.

My tables are of category A and their definitions are present in the repo.

**Comment by mbtools** [comment]
Do you mean that it's an offline repo?

I haven't tried but I think it's a limitation of the current design:
https://github.com/abapGit/abapGit/issues/6231#issuecomment-1514140449

**Comment by mathieulawnik** [comment]
Yes, an offline repo, sorry.

Does it mean that the only way to export table data is to an online repo ?

**Comment by larshp** [comment]
yea, its a bit tricky, it needs the remote attached for it to serialize, for offline repos it means first loading the zip,

![image](https://github.com/abapGit/abapGit/assets/5888506/b3fff009-6645-4889-ae39-fe5e73aaea5c)

**Comment by mathieulawnik** [comment]
Is there a way to bypass the need for an online repo ? I don't want to export sensitive data to an online repo, even a private one.

**Comment by larshp** [comment]
> Is there a way to bypass the need for an online repo ? I don't want to export sensitive data to an online repo, even a private one.

see https://github.com/abapGit/abapGit/issues/6378#issuecomment-1656554506 this is an offline repo with table data

**Comment by mbtools** [comment]
It's a missing feature

**Comment by mbtools** [comment]
I didn't intend to fix this but https://github.com/abapGit/abapGit/pull/6638 fixed this, too 😄
