### ISSUE TITLE
TABU: Dump when exporting table data when the table's type contains an include structure with a suffix

### ISSUE THREAD

**Issue by mathieulawnik** [abapGit/abapGit#6386]
I'm trying to export data from a custom table where the table type contains include structure "BAPIRET2" with suffix "Z".

I'm getting a dump on export because the suffix is ignored when transferring data from/to BAPIRET2 components.

First-level components:
![image](https://github.com/abapGit/abapGit/assets/139862035/585fffd7-0844-4020-9eb5-bb6a54270ed0)

Second-level components:
![image](https://github.com/abapGit/abapGit/assets/139862035/d0e7721b-e12a-4cbe-9f21-760882c3c4c7)

The dump happens on the second recursive call of method CONVERT_STRUC(). lt_comps contains names of second-level components without the suffix, however the parameter iv_data contains the full table type with suffixed components.
![image](https://github.com/abapGit/abapGit/assets/139862035/b4f9cc2f-3497-4651-84cd-cd55a3a3ad76)

**Comment by larshp** [comment]
note: the dump is in ajson code(perhaps the fix requires changes to ajson), but anyhow abapGit mirrors, so if there is a change to any of the ajson classes submit a fix to https://github.com/sbcgua/ajson

**Comment by mbtools** [comment]
the fix is merged into AG. please test @mathieulawnik

**Comment by mbtools** [comment]
Closed by https://github.com/abapGit/abapGit/pull/6405
