### ISSUE TITLE
Error message while exporting package

### ISSUE THREAD

**Issue by ATsikhanavets** [abapGit/abapGit#6389]
Hi all!
I get an error message while exporting package from the system which says 'Type "Z_DELIVERY_POS" is unknown'. It names the type which currently does not exist (but probably ever existed because in one of the reports there is a comment mentioning this type). I tried debugging that led to the short dump in the system. I still have options, but if somebody has met the same issue and knows the decision it would be much faster ))

Thanks in advance!

**Comment by larshp** [comment]
is `Z_DELIVERY_POS` in database table `TADIR`? maybe transaction `STDR` is required to fix the system state

**Comment by mbtools** [comment]
share the ouput of the dump

**Comment by ATsikhanavets** [comment]
> is `Z_DELIVERY_POS` in database table `TADIR`? maybe transaction `STDR` is required to fix the system state

There's no `Z_DELIVERY_POS` in table `TADIR`.

**Comment by ATsikhanavets** [comment]
> share the ouput of the dump

![image](https://github.com/abapGit/abapGit/assets/93209998/e457c510-591e-4a7e-87fa-20987e2e31c1)

**Comment by larshp** [comment]
@ATsikhanavets and the call stack?

**Comment by mbtools** [comment]
That's a dump of the debugger itself (program `RSTPDAMAIN`). I don't see how is this related to abapGit.

**Comment by mbtools** [comment]
Where in your repo is Z_DELIVERY_POS used? Do a full-text search on Github or wherever your repo is stored

**Comment by ATsikhanavets** [comment]
> Where in your repo is Z_DELIVERY_POS used? Do a full-text search on Github or wherever your repo is stored

There's only one mentioning of Z_DELIVERY_POS in the whole package and it's commented. I guess it was created and then deleted, but I can't trace it.
![image](https://github.com/abapGit/abapGit/assets/93209998/bcfdfbfa-51dd-4315-9203-088086f02617)

**Comment by mbtools** [comment]
When running export, which line in AG is raising the error message?

**Comment by mbtools** [comment]
no reaction. closing
