### ISSUE TITLE
Stuck in the object selection

### ISSUE THREAD

**Issue by lucasborin** [abapGit/abapGit#6407]
In the `1.124.0 - Standalone Version - Win - Edge` (updated today), I am not able to Pull a repository. It creates the popup to select the objects which should be brought from the remote version, but the screen does not execute the pull action when I click  on `Continue`. Actually, it creates the same popup, again. I cannot close the window or stop the transaction. I am stuck here. 

![image](https://github.com/abapGit/abapGit/assets/5233413/7b1f2ca9-e47c-4857-8e4b-56985acebac3)

Tech details:
* SAP Gui for Windows 800 PL 3 HOTFIX 1
* Browser Control: Edge (tested with IE, same issue)

**Comment by larshp** [comment]
hmm, maybe https://github.com/abapGit/abapGit/pull/6401 is relevant, try commenting those changes in the standalone and try the standalone

**Comment by lucasborin** [comment]
![image](https://github.com/abapGit/abapGit/assets/5233413/7a81e0ef-8715-46d9-a0f7-6e4aca050a33)

`E_SALV_FUNCTION` = `OK`

It looks like something in the alv framework...

**Comment by mbtools** [comment]
Yes, SAP changed something. Which sap version? sy-saprl or table covers "sap_aba"?

if it's 756, try SAP note 3146971 (mentioned here https://github.com/abapGit/abapGit/issues/6010)

**Comment by lucasborin** [comment]
`SAP_ABA` = `816`

Let me ask the ALV colleagues to check it. The abapgit side looks fine to me.

**Comment by lucasborin** [comment]
Fixed internally, thank you.

**Comment by mbtools** [comment]
hi @lucasborin 

looks like the issue occurred with another SAP colleague (https://github.com/abapGit/abapGit/issues/6477). Do you have more details or could get in touch with him?

Thx
Marc
