### ISSUE TITLE
Keep objects' original system

### ISSUE THREAD

**Issue by nununo** [abapGit/abapGit#641]
Hello!

I have 2 systems: A and B. 
Whatever is developed in A is transported to B.
But whatever is developed in B is not transported anywhere.

Currently, when I use abapGit to send things from A to B... all the objects are created as if they were originally developed in B.

This is dangerous because abapGit is not the norm to keep the systems in sync and so it is possible (I'd say probable) that someone will make changes in system B to objects originally transported from system A. These changes will never be sent to system A.

This is dangerous.

It would be great if abapGit could read the original system of an object and then force into the objects created in other systems.

This could be an option at repository level.

Thanks,
Nuno

**Comment by nununo** [comment]
Actually, losing the information of the original system is one of the main concerns people in my project have on adopting abapGit...

**Comment by larshp** [comment]
Suggestion:
Add a setting on repository level where the source system can be defined, and whenever doing a pull then make sure the source system is set for the updated objects.

**Comment by larshp** [comment]
this will also warn developers if they are trying to mess with something they are not supposed to, ie. choice to have the vanilla open source program implemented

**Comment by nununo** [comment]
What do you mean? Not even 7 years! ;-)
Thanks <3

**Comment by mbtools** [comment]
You can always sponsor me to speed things up 🤭
