### ISSUE TITLE
False diffs shown for last line of files

### ISSUE THREAD

**Issue by jelliottp** [abapGit/abapGit#6412]
For several repos I am stuck with what appear to be false diffs shown on the last line of files. Nothing is different and pulling the latest does not resolve it.

For example, I have pulled the latest changes for `code-pal-for-abap` and still I get this:
![image](https://github.com/abapGit/abapGit/assets/63249342/7ceceba4-a6cb-4159-9cda-751b5e93dfbd)

Any ideas? Could it have something to do with an empty line existing or not existing in these files?

**Comment by larshp** [comment]
its a newline / line feed at end of the file, which cannot be saved in the ABAP code(class includes and such), fix it in the upstream repo = https://github.com/SAP/code-pal-for-abap/pull/601

a .editorconfig helps with the file formatting, https://github.com/abapGit/abapGit/blob/main/.gitattributes and https://github.com/abapGit/abapGit/blob/main/.editorconfig, when opening/editing the raw files

**Comment by mbtools** [comment]
select "view > show hidden characters" to see the diff 😃

**Comment by mbtools** [comment]
Fixed with https://github.com/SAP/code-pal-for-abap/pull/601/files

**Comment by jelliottp** [comment]
Thanks, that helps. I have other repos where I see this so those need fixes pushed also.
