### ISSUE TITLE
Dump in `zcl_abapgit_convert=>class_constructor`

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6414]
Regression #6406 

![image](https://github.com/abapGit/abapGit/assets/59966492/77d6c640-9a10-4a01-b102-7e6e9bfa81b0)

![image](https://github.com/abapGit/abapGit/assets/59966492/5b14c8dd-d324-4889-a4c2-493437790261)

![image](https://github.com/abapGit/abapGit/assets/59966492/5bb824c4-bbf4-45ee-88cd-3c75900192cb)

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/pull/6415 merged
