### ISSUE TITLE
WebdynrPro Objects are not captured in the list

### ISSUE THREAD

**Issue by zayidu** [abapGit/abapGit#6423]
Hello Team, 

I couldn't find any WebdynPro objects in the staging level or at the modified level. Thanks for your prompt response.

**Comment by larshp** [comment]
try clicking "refresh" another time in the UI, plus double check that its the correct package being serialized

**Comment by zayidu** [comment]
I did it several times, still NO

**Comment by zayidu** [comment]
I could see the FG, CL but not the Webdynpro objects. Could you please help ?

**Comment by larshp** [comment]
first check if you are running the latest version?

**Comment by zayidu** [comment]
Yes its the latest version.

**Comment by mbtools** [comment]
All our WebDynpro test cases are successful:
https://ci.abapgit.org/src/0242ac1100021eebb1bbc829fae4fe35.smim.abapgit_ci_result.html#web_dynpro

If there's an issue, please add more details (screenshots, releases, etc).

**Comment by mbtools** [comment]
no response. closing
