### ISSUE TITLE
Consistent ABAP Language Version for CLAS, INTF, ...

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#6426]
With this issue, we track the progress for the adoption of a consistent ABAP Language Version (ALaV) for:

- [x]  Class 
  (contains `<UNICODE>X</UNICODE>`)
- [x]  Interfaces 
  (contains `<UNICODE>X</UNICODE>`)
- [x]  Function Groups 
  (contains `<UCCHECK>X</UCCHECK>`)
- [x]  Programs 
  (contains `<UCCHECK>X</UCCHECK>`)
- [x] Packages
  (can contain `<PACKAGE_KIND>5</PACKAGE_KIND>`)
- [x]  Enhancements (does not contain any ALaV flag but needs to be tested)

Use the functionality introduced in #6346 

Expectation when using ALaV feature:
- Result of serialize should not contain ALaV (i.e. the above data)
- Deserialize should set ALaV according to agreed rules

**Comment by mbtools** [comment]
Note: Most of this will be automatically handled via `zcl_abapgit_sap_report` which is called from the corresponding object type classes
