### ISSUE TITLE
Why shouldn't you have multiple namespaces in one repository?

### ISSUE THREAD

**Issue by ConjuringCoffee** [abapGit/abapGit#6433]
Hi all, I'm getting the following error message for one of my repositories:

> Package ZEXAMPLE is not part of the contained namespaces. Remove repository and use a different package

Let's say the customer namespace I'm using is /EX/. The package hierarchy looks like this:

- Parent package: ZEXAMPLE
- Child package /EX/EXAMPLE

This isn't an unusual scenario, and the repository looks good to me too. What are the effects of having multiple namespaces in one repository? What problems can be caused by this scenario?

**Comment by mbtools** [comment]
The point of namespaces is a clear separation of development objects and have some guarantee that others are not creating objects with the same name. The most prominent case is the development of ABAP add-ons where all objects belong to one namespace. 

Mixing non-namespaced things with namespaces does not make much sense to me because you lose the benefits mentioned above. Isn't the namespaced part a separate project? And `/ex/example` should be the root package of a/the repo?

PS: Since #6263, abapGit supports multiple namespaces per repo.

**Comment by ConjuringCoffee** [comment]
Thanks for the answer, Marc. Yes, I agree: Mixing namespaces usually doesn't make any sense. In our case, we had some internal developments that used to be done with a custom namespace, but the default convention reverted back to `Z`. That's why some of our developments are a mix of both namespaces - for now at least.

The message displayed by abapGit sounds more like "you've broken the repository because there are two namespaces and you need to fix it" and less like "we think this doesn't make sense". Usually, only real problems are displayed as errors there (e.g. objects not being supported).

I suggest to either remove the message or use different wording. Personally, I'd prefer to remove it because you confirmed that abapGit has no technical issue with multiple namespaces. This sound more like a job for ATC or abapLint checks.

If you want to keep the message, then I suggest rephrasing it to "Package ZEXAMPLE is not part of the contained namespaces" without the call to remove the repository.

I'd gladly submit a PR either way 😊

**Comment by mbtools** [comment]
Just removing the message won't be sufficient. Allowing this scenario would probably impact the folder logic. 

Feel free to change the message. You can also add a longtext to it.

**Comment by mbtools** [comment]
In general, we don't know which folder scenarios would work and which won't if you combine a regular root package with namespaced packages. The only [test case](https://github.com/abapGit-tests/NSPC) assumes root package is in a namespace and repo is using "prefix".

https://docs.abapgit.org/user-guide/repo-settings/dot-abapgit.html#folder-logic

You need at least two levels for testing...

For example:

- Parent package: ZEXAMPLE
- Child package /EX/EXAMPLE
- Child-Child package /EX/EXAMPLE_MORE

Theoretically, this should work with "prefix" but how does it work with "mixed" or "full"? Would we need a fix or a new error message?

**Comment by mbtools** [comment]
Thanks for the tests. Looks like it works fine in FULL mode and PREFIX/MIXED raise errors. 

Does https://github.com/abapGit/abapGit/pull/6446 work for you?

**Comment by ConjuringCoffee** [comment]
That works for me, thanks for the help!
