### ISSUE TITLE
Downport: Syntax errors in unit tests

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6436]
`cl_abap_unit_assert=>assert_true` and `assert_false` do not exist in 702. Use `assert_equals` instead.

- [x] ajson: https://github.com/sbcgua/ajson/pull/170
- [x] `zcl_abapgit_git_commit` https://github.com/abapGit/abapGit/pull/6437
- [x] `zcl_abapgit_services_repo` https://github.com/abapGit/abapGit/pull/6437

abaplint is not able to detect this issue, currently. Should we create a grep script to check all `*.testclasses.abap`?

![image](https://github.com/abapGit/abapGit/assets/59966492/eee9af1f-dce6-4487-ad38-110b6314bef3)

**Comment by larshp** [comment]
need some way of automating this, but well, sometime..
