### ISSUE TITLE
[CLAS/INTF] DB inconsistency in `seocompotx`

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#6442]
Creating objects of type CLAS/INTF via **pulling in abapgit** or **ADT** can result in different `seocompotx` entries. Background: Class component (meth, attri, ..) without description is expected to have seocompotx entry (with description = space).

Reproduce:
Pulling repository https://github.com/abapGit-tests/CLAS will create class `zcl_ag_unit_test` without entries in `seocompotx`, which is wrong.
vs
Creating the same class via ADT/SAPgui will result in entries `seocompotx`.

👋 We plan to provide a fix in abapGit

Further reading or how-you-break-things:
The logic in function module `seo_attribute_existence_check` (and others) is based on joins on `seocompotx`.

**Comment by mbtools** [comment]
In my system, `SEOCOMPOTX` contains 2,055,870 entries. 1,989,754 or 96.8% of them have an empty description field. 

May I suggest that SAP fixes the data model? 😉

**Comment by albertmink** [comment]
Off-topic: Some time ago, I worked on a consistency tool for metadata in the context of CLAS/INTF. This is of particular help in the context of support, where we find all kinds of inconsistency that should not be possible.
My conclusion on this topic: Finding inconsistency is both, easy and of limited use. Say there are two types. The ones, that are easy to fix and typically don't even harm the system and the other ones. Those are the ones that should not be possible, where all kind of really strange misalignment of DBs occur. Those cause severe manual effort to solve. Sometimes the source-code is wrong and it is not sufficient to generate the metadata from it. Sometimes is it the other way. Unless you don't apply a heuristic, I don't see a reasonable program that helps you in this situations.

**Comment by mbtools** [comment]
Also, customers like to run consistency check on SAP standard which creates more tickets for support 😀 

There are already several repair options in SE24. A tool that combines all of them and allows mass processing of classes would be much appreciated. 

Thanks for the fix 👍

**Comment by mbtools** [comment]
I created a tool to fix the inconsistencies caused by abapGit:
https://gist.github.com/mbtools/3bf797eed1161bd64c0d6610f804582a
