### ISSUE TITLE
Replace strings by constants that are already there

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#6458]
Replace hard-coded strings with ABAP Language Version (readable) e.g.
https://github.com/abapGit/abapGit/blob/b9a8de1ad2b22a556b7257176dc0409715d80a02/src/objects/aff/zcl_abapgit_json_handler.clas.abap#L187-L195
https://github.com/abapGit/abapGit/blob/b9a8de1ad2b22a556b7257176dc0409715d80a02/src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap#L557

with the constant `zif_abapgit_dot_abapgit=>c_abap_language_version` introduced in #6346

It is a pity, that the database equivalents are stored in `zif_abapgit_aff_types_v1=>co_abap_language_version` and nowhere near the readable ones.

**Comment by mbtools** [comment]
I would not mind if you copied the external values to `zif_abapgit_aff_types_v1` (to remove the dependency of AFF on dot abapgit). However, let's keep dot abapgit independent of AFF.
