### ISSUE TITLE
Set ABAP Language Version in settings page of repository

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#6459]
The concept of having a repository attribute for the ABAP Language Version (ALV) has been discussed and suggested in #6154.
PR #6346 implemented a basic functionality that determines the ALV in the current system and negotiate it further with the ALV from the settings (on repository level).

During testing your implementation that adopts the above described changes for object types CLAS, INTF and other source-based ones tracked in #6426, we found that we cannot set the ALV of a repository via abapGit. With that I mean, we cannot set the ALV in the settings page of the repository, e.g. in this screen 
<img width="978" alt="Screenshot 2023-09-01 at 11 50 47" src="https://github.com/abapGit/abapGit/assets/38354196/2426473a-21ba-4ea3-808f-e3bd6921b9bc">

**Comment by mbtools** [comment]
I'm in the process of some refactoring of repo settings and related UI. 

I can add the ALaV setting afterward as an experimental feature.

**Comment by albertmink** [comment]
I see, there is already an issue for tracking this feature.
➡️ Closing this issue here.
