### ISSUE TITLE
NW 752: Syntax error in latest abapGit 

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#6467]
Caused by #6457
![grafik](https://github.com/abapGit/abapGit/assets/17437789/231d1571-ca00-4be2-a914-8bd56deef106)
![grafik](https://github.com/abapGit/abapGit/assets/17437789/164f6b20-36df-48cf-9691-c4666b5ceddc)

**Comment by mbtools** [comment]
oh come on... i will check in 702...

**Comment by christianguenter2** [comment]
Seems like a copy&paste error.

**Comment by mbtools** [comment]
yeah, it didn't. my tests were using a copy of the code that didn't have the mistake. 

should be `FIELD-SYMBOLS <ls_subcomponent> TYPE LINE OF seo_subcomponents.`
