### ISSUE TITLE
Proposal - user exit to alter deserialization checks

### ISSUE THREAD

**Issue by frij-aws** [abapGit/abapGit#6471]
Currently there is a mechanism in `ZCL_ABAPGIT_BACKGROUND_PULL=>ZIF_ABAPGIT_BACKGROUND~RUN()`  which overrides the "overwrite" warning.  I'd like to propose supplementing this with a more general mechanism for overriding deserializing checks through a user exit:
```
INTERFACE zif_abapgit_exit
"
"
"
  METHODS change_checks
    CHANGING
      !cs_checks TYPE zif_abapgit_definitions=>ty_deserialize_checks .
```

and in `ZCL_ABAPGIT_BACKGROUND_PULL=>ZIF_ABAPGIT_BACKGROUND~RUN()`, after the loop that adjusts the `ls_checks-overwrite` decision field, a call to this exit:
```
    lo_exit = ZCL_ABAPGIT_EXIT=>GET_INSTANCE( ).
    lo_exit->change_checks( CHANGING cs_checks = ls_checks ).
```

I would personally use this to suppress the "package change" warning when doing pulls in background, but of course others might find their own creative and useful reasons to adjust the checks based on their own logic. 

One open question is whether this mechanism should be background-only (in which case it should really be called `change_checks_background()` or if it should be for both interactive and background pulls (in which case we should probably pass a parameter like `iv_interactive type abap_bool` to the exit (`SY-BATCH` isn't enough because of the possibility of API-based and RFC-based non-interactive invocation).  I welcome your thoughts.

**Comment by larshp** [comment]
background modes are also "user exitable" in itself, just add a new class implementing `zif_abapgit_background`

**Comment by frij-aws** [comment]
Ooh that's cool, I didn't know that.  

Hmm, if I'm reading the code right, `zif_abapgit_background` doesn't behave exactly like an exit does it? It seems like the implementation to use is chosen based on the persisted repo settings, `zabapgit-method`.  It's not clear to me how to change that field -- it doesn't look like it's in the UI as a configurable setting? I do see code in `ZCL_ABAPGIT_GUI_PAGE_SETT_BCKG=>SAVE_SETTINGS()` that looks like it's reading the field from a UI form (sorry, a little foggy on how the abapGit UI coding works) but I don't see the field on the screen.

I suppose a package change is a warning-worthy event because two different repos could contain the same object and so the pop-up is supposed to warn the user of the possible conflict. In this case I could imagine someone wanting a background pull to abort rather than charging ahead, so a customer tailoring the behavior to their preferences makes some sense.  In my case I want it to charge ahead and stomp all over everything :)

**Comment by frij-aws** [comment]
Works great, as far as I'm concerned this proposal can be closed with no action

**Comment by mbtools** [comment]
Cool. 

We're missing docs for this option 😉 
- mentioning the option here: https://docs.abapgit.org/user-guide/repo-settings/background-mode.html
- an example similar to https://docs.abapgit.org/user-guide/reference/authorizations.html under "References"

**Comment by larshp** [comment]
https://github.com/abapGit/docs.abapgit.org/pull/165
