### ISSUE TITLE
Q: Pop-up repeats and blocks me

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#6477]
Pulling abapGit ends up in a blocking pop-up situation, see
https://github.com/abapGit/abapGit/assets/38354196/86b76042-9224-4ef1-b192-479b415106d3

It's a Mac, it's SAPgui, so not the best combination I know, but maybe there is help out there.

**Comment by larshp** [comment]
also see https://github.com/abapGit/abapGit/issues/6407

**Comment by albertmink** [comment]
cannot reproduce
