### ISSUE TITLE
Warning about Edge browser control is displayed even when Internet Explorer browser control is used

### ISSUE THREAD

**Issue by kjetil-kilhavn** [abapGit/abapGit#6481]
In one of our systems (sandbox) the warning about Edge browser control is displayed regardless of which browser control I use. 
The development system in the same system line behaves as expected and only displays the warning when I use the Edge (Chromium-based) browser control.

After chasing ghosts such as system parameters and security settings I discovered that the reason is a repository with quotation marks in the display name - which causes a Javascript syntax error in the "repoCatalog" array.  
The syntax error message was: Expected '}'

Repository display name: ABAP2XLSX Demonstrate loss of formatting when using "Format as table"

**Comment by mbtools** [comment]
Closed by #6482
