### ISSUE TITLE
ECTD diff after import based on sort order

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#6489]
After first pull:

![image](https://github.com/abapGit/abapGit/assets/5270359/c8a56a48-1e94-42e0-b2b9-cbce568bf857)

After pulling again the sort order seems to have fixed itself but the field SORTLNR diffs.

![image](https://github.com/abapGit/abapGit/assets/5270359/b7a38319-f584-4270-aa62-8156f7cbd931)

This object already had the correct sort order after first pull but different SORTLNR:

![image](https://github.com/abapGit/abapGit/assets/5270359/9870754b-d7f4-4d9b-9c69-ebebf64859db)

After second pull the field still diffs, but got different numbers...

![image](https://github.com/abapGit/abapGit/assets/5270359/1ad0284a-adb5-413d-ba12-9c8ecdfd44e3)

Third pull even after restarting abapGit doesn't change anything anymore.

**Comment by mbtools** [comment]
I had looked at this before. The system is renumbering during import in a strange way. Keeping the numbers out of the XML is easy but I'm not sure how the deserialize needs to be adapted.

**Comment by fabianlupa** [comment]
I had a look just now and did I regret looking.... Anyway, found another issue. Somewhere down these gigantic classes in their inheritance forests was a call to update the variants in the test data container. Only the import parameter for new and changed variants was supplied, not for removed ones. I removed a variant from the TDC and committed to a new branch. Then switched back und pulled to get the variant back. After now switching to the new branch again and pulling I am unable to remove the variant using abapGit.
