### ISSUE TITLE
CLAS: Initial class category for child exception classes after first pull

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#6490]
When pulling multiple exception classes where none of which were in the system before pull, the field VSEOCLASS-CATEGORY is unset after first pull for child exception classes. It should have the value 40.

abapGit itself is affected by this with the exception ZCX_ABAPGIT_CANCEL. I assume when the child class ZCX_ABAPGIT_CANCEL is deserialized the base class ZCX_ABAPGIT_EXCEPTION is still empty or buffered and the class builder API clears the field assuming it's a normal class, possibly misguided by the deserialize to active approach.

![image](https://github.com/abapGit/abapGit/assets/5270359/b8541b95-8956-4dc3-a7e3-8af39f543274)

![image](https://github.com/abapGit/abapGit/assets/5270359/f9dd95d3-6fc9-4d52-b611-bc17df99deed)

A second pull fixes the diffs. Maybe the field could be explicitly updated on the first pull in such scenarios.

Edit: I haven't noticed this issue before. Could also be specific to the new developer edition (?).

**Comment by albertmink** [comment]
Possible starting point for git bisecting could be 4e3a139b2757b2f920316f8fa0def81e75134f0b I will have a look, tomorrow

**Comment by larshp** [comment]
I've seen it happen some times, think its much older than one week

**Comment by mbtools** [comment]
Here's a test repo https://github.com/abapGit-tests/CLAS_exceptions.

The child exception class is created as a regular class. Therefore, the exception longtexts are also missing:

![image](https://github.com/abapGit/abapGit/assets/59966492/c0b882f5-0b1b-4d6f-a439-c791c709c6e0)

**Comment by mbtools** [comment]
The source scanner is reverting the class category from `40` to `00` here:

![image](https://github.com/abapGit/abapGit/assets/59966492/c907250c-9a4e-49e0-a0b5-c79927b222af)

Up to that point, it looks like the class is created properly as an exception.

PS: Debugging OO-related SAP code is a major pain. Buffers and macros everywhere 🤕

**Comment by fabianlupa** [comment]
Great find! I think we had a similar thing happen before where the source scanner used an outdated / cached base and reverted. Though I couldn't find any issue / PR after some searching :(

This seems a bit more simple. I just swapped around order of the objects so the super class is deserialized first in the debugger.

![image](https://github.com/abapGit/abapGit/assets/5270359/7145bdc6-46fc-43a3-96a0-7f2523016507)

That then worked just fine. Here just like in the other examples the child class is alphabetically before the parent class. Maybe changing the order (somehow) in this special case would be an option.

> PS: Debugging OO-related SAP code is a major pain. Buffers and macros everywhere 🤕

Appreciate you taking the hit for the team :)

**Comment by mbtools** [comment]
It's the general issue of dependencies between objects of the same type. We will have to figure out how to close this gap eventually.
