### ISSUE TITLE
ECTD deleted variants on the remote are not deleted locally on pull

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#6491]
From https://github.com/abapGit/abapGit/issues/6489#issuecomment-1717954996

> Somewhere down these gigantic classes in their inheritance forests was a call to update the variants in the test data container. Only the import parameter for new and changed variants was supplied, not for removed ones. I removed a variant from the TDC and committed to a new branch. Then switched back und pulled to get the variant back. After now switching to the new branch again and pulling I am unable to remove the variant using abapGit.

Found it again in CL_APL_ECATT_UPLOAD->GET_VARIANTS_FROM_DOM_NEW, the call to CL_APL_ECATT_PARAMS->SET_VARIANTS( ).

This is SAP standard code. The GUI application appears unaffected by this though as it asks if all variants should be deleted on upload:

![image](https://github.com/abapGit/abapGit/assets/5270359/3955aba3-da06-4f7a-aebb-ed5cf97b4317)

In CL_GUI_ECATT_DATA_EDITOR->UC_UPLOAD_VARIANTS a replace mode for CL_APL_ECATT_EXT_DATA=>UPLOAD_VARIANTS is determined using the user decision. UPL_SET_TEST_DATA in the same class accounts for this by calling CL_APL_ECATT_PARAMS->DELETE_VARIANTS( '*' ) before CL_APL_ECATT_PARAMS->SET_VARIANTS( ). We can probably do the same somewhere. 

Edit: I may have mixed up the feature to download and upload just the variants or the whole test data container. I cannot find a way to update the whole test data container including its variants using the GUI, the object needs to be deleted first. However, the call to delete all variants should still work as both upload/download features appear to use the same classes.

**Comment by mbtools** [comment]
maybe in `ZCL_ABAPGIT_ECATT_VAL_OBJ_UPL->UPLOAD`

**Comment by fabianlupa** [comment]
I think it's `ZCL_ABAPGIT_ECATT_DATA_UPLOAD->UPLOAD` which looks a bit more difficult. To get access to `lo_params` in the same manner the easiest way would probably be to copy the implementation of `CL_APL_ECATT_DATA_UPLOAD->UPLOAD`, add the new `delete_variants` and move `ZCL_ABAPGIT_ECATT_DATA_UPLOAD` up one level in the inheritance tree. Otherwise you'd somehow have to attach the call between the initialization of the attributes and the `set_variants` call. Or call `set_variants` again in the subclass after the call of the parent implementation but `save` and `close_object` are already called then :shrug:

**Comment by mbtools** [comment]
I'm not using ECATT. Go for it. Just has to work with [this](https://github.com/abapGit-tests/ECATT) 😉

**Comment by fabianlupa** [comment]
I am only using it for the fancy editable ALV for test data in unit tests ;) I'll have a go add it and maybe add / adjust some test cases in the test repo.

(ALV stands for ABAP List Viewer by the way :P )

**Comment by mbtools** [comment]
+1 for ALV like this guy:

![image](https://github.com/abapGit/abapGit/assets/59966492/c56dcf0b-d67a-42fd-9ee6-1f18ca60af52)
