### ISSUE TITLE
IAMU: Serialize MIMEs as separate file

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6495]
Currently, ITS MIME objects are base64 encoded:
https://github.com/abapGit-tests/IARP_IASP_IATU_IAMU/blob/main/src/zag_test_servi99zag_test_mime.iamu.xml

Should be serialized as separate (binary) file

**Comment by larshp** [comment]
yea, I think SMIM + W3MI already does this

(its fun/sad that there are 3 different mime object types)

**Comment by mbtools** [comment]
Todo: Implement same as [W3MI](https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_w3xx_super.clas.abap) which introduced `v2` within serializer class.
