### ISSUE TITLE
Exit ON_EVENT does not allow overriding page specific actions

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#6497]
From https://docs.abapgit.org/user-guide/reference/exits.html#on-event:

> This exit allows you to extend abapGit with new features that are not suitable for abapGit itself. For example, you can link to a new page from a wall message. __Another use case is redirecting menu items to a custom page rather than standard abapGit__, for example using a company-specific solution to replace "Advanced > Run Code Inspector" (see #4722).

The highlighted part currently only seems to work specifically for general menu items, not for actions a level deeper on pages. I am attempting to override the navigation from the repo list to the repo page. However, the exit is called in `ZCL_ABAPGIT_GUI_ROUTER->ZIF_ABAPGIT_EVENT_HANDLER~ON_EVENT`. Which is _late_. `ZCL_ABAPGIT_GUI->HANDLE_ACTION` for this use case has 3 event handlers to go through with `ZCL_ABAPGIT_GUI_ROUTER` being the last one in the list. The action never reaches the exit as it is handled by the "default" implementation beforehand.

![image](https://github.com/abapGit/abapGit/assets/5270359/e616e9bd-245c-494b-bab9-6ad7e42ba3a9)

Technically having the general page routing last seems correct. I'd say the exit call should be moved though from:

https://github.com/abapGit/abapGit/blob/b1daa712268f14e2a0282e2640529603fa9bbc05/src/ui/routing/zcl_abapgit_gui_router.clas.abap#L674

To before the loop:

https://github.com/abapGit/abapGit/blob/b1daa712268f14e2a0282e2640529603fa9bbc05/src/ui/core/zcl_abapgit_gui.clas.abap#L285

Unless this is intentionally not supported and only new custom events should be supported as well as overriding specifically actions handled by the GUI router.

**Comment by mbtools** [comment]
Agree. Overwriting existing events should be possible in general. Let's move the call before the loop (and don't process the loop if the exit was handled).
