### ISSUE TITLE
Transport request pop-up for T package

### ISSUE THREAD

**Issue by juriadasek** [abapGit/abapGit#6505]
Hi guys,

I have a repository which contains only Z-objects. When I am doing pull, then it asks me for transport request. This is a bit weird because when creating Z-objects and package in the source system, I was not asked about any transport request. So, I have created a new transport and assigned it. After that pull finished successfully and when I checked this transport request in SE01, then there was no object assigned to it. 

I did some research and noticed that when my package on the target system is called `$TEST_JA`, then I am not getting any transport request pop-up while doing pull. However, when it is called `TEST_JA`, then abapGit asks for transport request. In my SAP system both packages are local and are not assigned to any transport.

I have noticed that in this case the transport request pop-up is controlled by this property: https://github.com/abapGit/abapGit/blob/82633f80f742c0b0effb89d83bf30779a9b5afa7/src/objects/core/zcl_abapgit_objects_check.clas.abap#L149
and that points to this condition: https://github.com/abapGit/abapGit/blob/82633f80f742c0b0effb89d83bf30779a9b5afa7/src/objects/sap/zcl_abapgit_sap_package.clas.abap#L51
That confirms that only packages which start with `$` do not require transport request in abapGit. 

I managed to find this documentation (https://help.sap.com/saphelp_gbt10/helpdata/EN/ea/c05da6f01011d3964000a0c94260a5/content.htm?no_cache=true) which says that packages beginning with T do not belong to a transport layer, they are local. 

I want to make sure that it is correct for abapGit to ask for transport request when pulling T package, or this is just a bug?

Thanks,
Juraj

**Comment by mbtools** [comment]
Very few people know about or use T-packages 😉 

The correct way would be to find the software component the package belongs to and get the properties of this software component (ie. the transport flag). Feel free to suggest a pull request.

**Comment by christianguenter2** [comment]
Seems like a gap in abapGit. Kudos for the detailed issue.

**Comment by christianguenter2** [comment]
> The correct way would be to find the software component the package belongs to and get the properties of this software component (ie. the transport flag). Feel free to suggest a pull request.

Hm, how to do that if the package does not yet exist?

**Comment by fabianlupa** [comment]
Had similar issues years ago and opted for $ packages instead. I think we have an old issue somewhere. Would be great if the logic wasn't hard coded using the package name.

**Comment by christianguenter2** [comment]
Also lot's of hard coding by SAP in fm `PB_POPUP_PACKAGE_CREATE` where software component LOCAL is determined.
![grafik](https://github.com/abapGit/abapGit/assets/17437789/fabdf029-15d6-4aa3-be61-f772c740c9d3)

**Comment by christianguenter2** [comment]
> > The correct way would be to find the software component the package belongs to and get the properties of this software component (ie. the transport flag). Feel free to suggest a pull request.
> 
> Hm, how to do that if the package does not yet exist?

Seems like FM `TR_PACKAGE_GET_DEFAULT_VALUES` is a good choice for that.
![grafik](https://github.com/abapGit/abapGit/assets/17437789/c36250a9-8220-4ba1-9a26-0f28cfeebf1f)

**Comment by fabianlupa** [comment]
If I recall correctly T / TEST packages make transports optional, while $ prohibits them and for everything else it's mandatory. Maybe that's indicated by those results.

**Comment by christianguenter2** [comment]
Yeah, seems like. Though it's quite inconsistent/confusing. E.g. when I create the package in SE21 the flag is defaulted to space for T-packages.

**Comment by mbtools** [comment]
The issue is related to new, non-existing packages only. Suggest simply changing it to

```abap
 rv_are_changes_rec_in_tr_req = boolc( mv_package(1) <> '$' AND mv_package(1) <> 'T'  ). 
```

**Comment by christianguenter2** [comment]
I think we need also adjust this logic, as depending on the KORRFLAG a TADIR entry for T-packages exists or not.
https://github.com/abapGit/abapGit/blob/82633f80f742c0b0effb89d83bf30779a9b5afa7/src/objects/core/zcl_abapgit_tadir.clas.abap#L92-L93

**Comment by mbtools** [comment]
I'm not sure if that's equivalent. I honestly don't know why local packages are not in TADIR. 🤷 (BW doesn't create TADIR entries for local objects either which is still a mystery to me) 

I would stick with the additional IF condition.

**Comment by christianguenter2** [comment]
Problem is that T-packages have TADIR entries if KORRFLAG = 'X' . So simple IF condition would lead to duplicate entries for these cases. Of course we can deal with that. 
Therefore I came to the conclusion that TADIR entries are directly related to transport recording of the package, but I'm not sure either. It's an edge case anyway.
