### ISSUE TITLE
SSFO: BG Job commits unchanged objects randomly

### ISSUE THREAD

**Issue by openPhiL** [abapGit/abapGit#6530]
Hi. 
I'm having this situation where my nighly job commits strange things that haven't been touched since years. 
it only happens to (some, but the same) SSFO objects and it looks like that:
![image](https://github.com/abapGit/abapGit/assets/43743230/f3cdf3db-9859-475f-903b-176577c2f1a9)

first analysis looks like the language selection is unsorted.
it starts in FB: ```SSF_READ_FORM``` line 45 /59 where all texts are read into ```t_objt```. 
![image](https://github.com/abapGit/abapGit/assets/43743230/61679c94-fe72-4f91-9494-3bfe26cce0dc)

and follows in FB ```SSF_READ_OBJ_TEXT``` where it is returned to whoever wants the available texts.

It seems to be only occurring on big forms combined with lots of supported languages, our ```t_objt``` has more than 10.000 entries, so I assume it is natural that the order of all those is not identically when not explicitly requested ). 

I remember that we had to do some work back when we migrated to HANA and manually added the sort command to all DB selects that were not sorted yet, as HANA does not sort by default. I assume SAP should have done that as well. 

Now.. what would you recommend..
Is that a fix that would implemented in your ```ZCL_ABAPGIT_OBJECT_SSFO``` 
or 
should we try SAP changing the FBs, adding a sort
or
do you have another approach to this?

Thanks
PhiL

**Comment by larshp** [comment]
I'd suggest fixing it in https://github.com/abapGit/abapGit/blob/main/src/objects/zcl_abapgit_object_ssfo.clas.abap

it might be a bit of a mess, as it got the ixml object

pull requests welcome

**Comment by larshp** [comment]
what is the XML path down to `<T_CAPTION>`? and does the problem only occur under `<T_CAPTION>` ?

**Comment by openPhiL** [comment]
it occurs here and there: 

/abapGit/sf:SMARTFORM/sf:VARHEADER/sf:item/sf:PAGETREE/sf:NODE/sf:SUCC/sf:item[1]/sf:NODE/sf:SUCC/sf:item[8]/sf:NODE/sf:OBJ/sf:WINDOW/sf:PROC_CTRL/sf:NODE/sf:SUCC/sf:item[6]/sf:NODE/sf:OBJ/sf:SECTION/T_CAPTION

/abapGit/sf:SMARTFORM/sf:VARHEADER/sf:item/sf:PAGETREE/sf:NODE/sf:SUCC/sf:item[1]/sf:NODE/sf:SUCC/sf:item[8]/sf:NODE/sf:OBJ/sf:WINDOW/sf:PROC_CTRL/sf:NODE/sf:SUCC/sf:item[4]/sf:NODE/sf:SUCC/sf:item[1]/sf:NODE/sf:OUTATTR/sf:OUTATTR/T_CAPTION

/abapGit/sf:SMARTFORM/sf:VARHEADER/sf:item/sf:PAGETREE/sf:NODE/sf:SUCC/sf:item[1]/sf:NODE/sf:SUCC/sf:item[8]/sf:NODE/sf:OBJ/sf:WINDOW/sf:PROC_CTRL/sf:NODE/sf:SUCC/sf:item[6]/sf:NODE/sf:SUCC/sf:item/sf:NODE/sf:OBJ/sf:SECTION/T_CAPTION

and many more.

but yes, it really does seem to only occur under `<T_CAPTION>`

I'm sorry, I havened tried to solve it yet my self.

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/pull/6609 should fix it. please test
