### ISSUE TITLE
Ignore sub packages in offline project

### ISSUE THREAD

**Issue by pely122** [abapGit/abapGit#6535]
I now have a  package named $test010 and sub package $test020
when i use offline object with "Ignore Subpackages" as checked, it is ok.
![image](https://github.com/abapGit/abapGit/assets/20834234/dc6e79c6-e63f-495a-b093-7545f8e2fd45)
but when i use online object, there is not have sub package in repo.
![image](https://github.com/abapGit/abapGit/assets/20834234/953413f9-bcfe-4f44-af32-a6d101ec7bb3)
So, what is the reason?

**Comment by larshp** [comment]
what is the local settings for the online repository? click "Local", 
![image](https://github.com/abapGit/abapGit/assets/5888506/bc0b5824-510f-4a7b-b9db-3f0742643255)

**Comment by mbtools** [comment]
I reproduced it with the following settings:

![image](https://github.com/abapGit/abapGit/assets/59966492/45475415-9494-479e-be37-33529bc10446)

The "ignore subpackages" flag is not saved

**Comment by pely122** [comment]
reinstall abapgit and the issue resolved
