### ISSUE TITLE
TOBJ: Serialization shows diffs on an HANA database 

### ISSUE THREAD

**Issue by einareiriksson** [abapGit/abapGit#6546]
The serialization method for TOBJ (ZIF_ABAPGIT_OBJECT~SERIALIZE) uses SAP FM CTO_OBJECT_GET that in line 119 selects from OBJS without order by.
If the object list contains more that one table this can cause a discrepancy between systems if the underlying database is an HANA database.

The outcome is that the TOBJ in question always shows up as changed on the diff list in the remote system where the HANA database returns the rows in different order than the pushing system.

Hard to recreate as this is a bit random, but best bet is to create a maintanance object for a table with a text table and clone to remote system.

Suggested fix would be to sort the tables returned from FM CTO_OBJECT_GET before serializing.

**Comment by larshp** [comment]
@einareiriksson thanks, sounds like a good change, would you like to open a pull request with the fix?

**Comment by larshp** [comment]
solved in #6547, closing
