### ISSUE TITLE
"ORDER BY PRIMARY KEY" does not make sense for views

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#6551]
Fresh download of standalone client, activation error on SAP_ABA 731-0005:

![grafik](https://github.com/abapGit/abapGit/assets/25269970/c3668dcc-b300-469a-9ee8-6fada8096c0f)

https://github.com/abapGit/abapGit/blob/b82924c3886cbb9921320e5b35a1a9252160feaa/src/objects/oo/zcl_abapgit_oo_base.clas.abap#L283

https://github.com/abapGit/abapGit/blame/b82924c3886cbb9921320e5b35a1a9252160feaa/src/objects/oo/zcl_abapgit_oo_base.clas.abap#L329

(PR incoming)

**Comment by larshp** [comment]
hmm, I wonder which version allows doing the ORDER BY PRIMARY KEY, couldnt find it in the release specific changes

**Comment by AndreaBorgia-Abo** [comment]
> couldnt find it in the release specific changes
No idea, but I can confirm that NPL (7.52SP04) MiniSAP already accepts it
