### ISSUE TITLE
Missing methods in local zif_abapgit_exit definition of abapGit standalone version 

### ISSUE THREAD

**Issue by ghost** [abapGit/abapGit#6570]
In the local definition of the interface zif_abapgit_exit of the abapGit standalone version the following method definitions are missing

```
  METHODS change_max_parallel_processes
    IMPORTING
      !iv_package       TYPE devclass
    CHANGING
      !cv_max_processes TYPE i.

  METHODS change_rfc_server_group
    CHANGING
      !cv_group TYPE rzlli_apcl.
```

This causes the following syntax error when compiling the standalone version as the interfaces are incompatible, if you have implemented the **ZABAPGIT_USER_EXIT** based on the developer version of the Interface, as this is included at line **127841** of the standalone program with the statement "**INCLUDE zabapgit_user_exit IF FOUND.**"

**_Method "ZIF_ABAPGIT_EXIT~CHANGE_MAX_PARALLEL_PROCESSES" is not declared or inherited in class "ZCL_ABAPGIT_USER_EXIT"_**

Solution: Add the missing definition to the interface of the abapGit standalone version as well as provide implementations for the methods in local class **ZCL_ABAPGIT_EXIT**

```
  METHOD zif_abapgit_exit~change_max_parallel_processes.

    IF gi_exit IS NOT INITIAL.
      TRY.
          gi_exit->change_max_parallel_processes(
            EXPORTING
              iv_package       = iv_package
            CHANGING
              cv_max_processes = cv_max_processes ).
        CATCH cx_sy_ref_is_initial cx_sy_dyn_call_illegal_method ##NO_HANDLER.
      ENDTRY.
    ENDIF.

  ENDMETHOD.
```

```
  METHOD zif_abapgit_exit~change_rfc_server_group.

    IF gi_exit IS NOT INITIAL.
      TRY.
          gi_exit->change_rfc_server_group( CHANGING cv_group = cv_group ).
        CATCH cx_sy_ref_is_initial cx_sy_dyn_call_illegal_method ##NO_HANDLER.
      ENDTRY.
    ENDIF.

  ENDMETHOD.
```

**Comment by larshp** [comment]
yea, if implementing ZABAPGIT_USER_EXIT then

> The list of user exits can change at any time, make sure to syntax check user exits after updating abapGit.

ref https://docs.abapgit.org/user-guide/reference/exits.html#overview

**Comment by omega750** [comment]
yep, I saw that bit, just thought I would raise the issue so that you had a ticket to include it in the next update of the standalone version...

**Comment by larshp** [comment]
the standalone is automatically updated when code is merged to main, https://github.com/abapGit/build

**Comment by mbtools** [comment]
in other words, if we add an exit, it's recommended to update all of these together:

- abapGit standalone version + zabapgit_user_exit
- abapGit developer version + zcl_abapgit_user_exit

**Comment by mbtools** [comment]
Ref https://github.com/abapGit/docs.abapgit.org/pull/175

**Comment by larshp** [comment]
@omega750 with the documentation update in https://github.com/abapGit/docs.abapgit.org/pull/175, is it possible to close the issue? I dont think we can do much more
