### ISSUE TITLE
FUGR: Can not import template dynpros

### ISSUE THREAD

**Issue by JSB-Vienna** [abapGit/abapGit#6580]
Hi all,

I tried to import template screens (dynpros) but got an error message, and screens with a higher number weren't imported. So, there are actually two issues in this case.

The solution for the first one is attached in a commented screenshot. Can't tell if it is worth solving
it, but from my understanding, should other object be imported although an error occurred during a previous object.

![No generation of template dynpros](https://github.com/abapGit/abapGit/assets/30773503/d4780058-d5e4-434c-9640-721e6ea87934)

Best regards,
Jens

**Comment by mbtools** [comment]
We can add the parameter but have to check if it exists in 702. 

In general, deserializing an object (like a program) fails at the first error. Continuing won't make much sense since the object would be incomplete anyway. There should be an error message and a diff, though.

**Comment by mbtools** [comment]
Parameter exists in 702 and I made a fix (#6582). I'm not familiar with templates. Can you create a small example in https://github.com/abapGit-tests/PROG_dynp_template, please?

**Comment by JSB-Vienna** [comment]
Thank you very much for your very fast reply. And yes, to mark it as different after the import could be enough. I thought at first I exported it incompletely, which is why I asked for the continuation.
Yes, I created an example.

**Comment by JSB-Vienna** [comment]
I've now truly created an example, but if I try to commit the changes in view Stage - add all, I get the error process_stage_list: empty_list. The version is from yesterday.
![image](https://github.com/abapGit/abapGit/assets/30773503/858710eb-d37b-437e-a7c9-8914a34eef28)

**Comment by mbtools** [comment]
what type and version of SAP GUI are you using?

**Comment by JSB-Vienna** [comment]
![image](https://github.com/abapGit/abapGit/assets/30773503/cc26631e-6cd6-4f28-8c45-2f02a38c5acc)

**Comment by mbtools** [comment]
the gui patch is a bit old (patch 14 contains an important fix). what the setting for browser control? If it's "Edge", switch it to "Internet Explorer" 
https://docs.abapgit.org/user-guide/setup/sapgui.html#general

**Comment by JSB-Vienna** [comment]
Thanks, that helped. I had read the discussion but wasn't aware that I had the wrong GUI version.
Uploading in the Git repository above is not possible, neither online nor offline. Attaching here is not possible. How can I provide you with files? Shall I send you the ZIP file via Mail? Or did I do something wrong?

**Comment by mbtools** [comment]
you can always fork the repo, then make changes to your fork and create a pull request to move the changes to the main repo.

however, i gave you write permission so you can update the test repo directly

**Comment by JSB-Vienna** [comment]
Sorry, I'm still not very familar with possibilities. And thank you for the invitation. 
I decided to learn something. So I've used now the way forking the repo to  [PROG_dynp_template_jsb](https://github.com/JSB-Vienna/PROG_dynp_template_jsb). I could upload it via ABAPGit as Online repository. So my system problems are solved too.
Hopefully the example helps.

**Comment by mbtools** [comment]
I merged your example and renamed the repo to https://github.com/abapGit-tests/FUGR_dynp_template. Upon testing in my system, I'm getting an error that table T001 does not exist. 

![image](https://github.com/abapGit/abapGit/assets/59966492/e7e1861e-7da6-450c-a8c7-a782a46f486b)

This table exists only in ERP, not in plain basis systems. Could you please change it to T002, for example? Ty

**Comment by JSB-Vienna** [comment]
Hi and sorry for that. Changed it to table T002TX which is part of package SI18N.
