### ISSUE TITLE
Dump on clicking some of packages in zabapgit - CX_SY_RANGE_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by ramprasad-b** [abapGit/abapGit#6586]
We get the below error when clicking on some of the packages in zabapgit transaction. I have selected the folder logic as ‘FULL’ in the settings. All packages can be seen but on clicking on some of the packages, it dumps saying too long string.

ategory               ABAP Programming Error
untime Errors         STRING_LENGTH_TOO_LARGE
xcept.                CX_SY_RANGE_OUT_OF_BOUNDS
BAP: Program          ZABAPGIT

Error Analysis
   An exception has occurred which is explained in more detail below. The
   exception is assigned to class 'CX_SY_RANGE_OUT_OF_BOUNDS' and was not caught
    in procedure
   "INDENT_LINE" "(METHOD)", nor was it propagated by a RAISING clause.
   Since the caller of the procedure could not have anticipated this
   exception, the current program was terminated.
   The reason for the exception is:
   An attempt was made in program "ZABAPGIT" to access a part of a string using
   an explicitly specified length.
   This length (202) was greater than the current length of the string
   (200) however.
   Access is not possible like this.

![image](https://github.com/abapGit/abapGit/assets/48615191/3ebccbf8-9cb3-4bba-9ad3-0a0e90b9c25d)
![image](https://github.com/abapGit/abapGit/assets/48615191/2a520c1f-da91-4bbf-92d0-8151544eeee1)

**Comment by larshp** [comment]
@ramprasad-b are you running the latest version?

**Comment by ramprasad-b** [comment]
Hi, This is the version.
INTERFACE zif_abapgit_ajson.

  CONSTANTS version TYPE string VALUE 'v1.1.9'

**Comment by larshp** [comment]
@ramprasad-b thats the ajson version, latest abapGit is v1.125.0, https://github.com/abapGit/abapGit/blob/main/changelog.txt

**Comment by larshp** [comment]
@ramprasad-b try https://github.com/abapGit/abapGit/suites/17679104279/artifacts/1011472747 from https://github.com/abapGit/abapGit/actions/runs/6663595825?pr=6587, I think there is some other bug, but still it should not dump

**Comment by ramprasad-b** [comment]
@larshp Thanks. System is in version 1.124.0.

**Comment by larshp** [comment]
okay, please try the build from https://github.com/abapGit/abapGit/suites/17679104279/artifacts/1011472747, to see if it works

**Comment by larshp** [comment]
@ramprasad-b try the latest build https://raw.githubusercontent.com/abapGit/build/main/zabapgit_standalone.prog.abap

**Comment by ramprasad-b** [comment]
Thanks @larshp . It works with latest v1.125.

**Comment by larshp** [comment]
👍 

closing
