### ISSUE TITLE
Question: Is VERSION CONSTANT no longer supported?

### ISSUE THREAD

**Issue by rayatus** [abapGit/abapGit#6594]
Hi guys, I just realized that in AG Standalone v1.125 the **Version Constant field + value** do not longer exists.
Are they replaced by any other way of version control?

following a screenshot of that field in  v1.124.0
 
![image](https://github.com/abapGit/abapGit/assets/12736990/e358a49a-f766-4ae6-a1c7-e313361bb7a0)

**Comment by larshp** [comment]
hmm, looks like it was lost as part of https://github.com/abapGit/abapGit/pull/6488/files the code behind the fields is still there, just not displaying, @mbtools

**Comment by mbtools** [comment]
looks like patching from AG didn't work as expected. I will add the field back
