### ISSUE TITLE
FYI. Old abapGit package removed but old classes still exist

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#6607]
Hi. Just for information (I don't have any problem except that I was surprised and I did a little cleanup).

I'm on ABAP 7.56. I have the latest abapGit version (pulled today), assigned to temporary packages ($abapgit*). The classes `ZCL_ABAPGIT_GUI_PAGE_DB_DIS` and `ZCL_ABAPGIT_GUI_PAGE_DB_EDIT` are still present in my system although they have been removed a while ago. They were still assigned to their old package `$abapgit_ui_db` which in fact didn't exist anymore.

For the cleanup, I did:
- Create `$abapgit_ui_db` (to be able to delete the classes; other solution could have been to simply reassign the classes to $tmp)
- Delete `ZCL_ABAPGIT_GUI_PAGE_DB_EDIT`
- Delete `ZCL_ABAPGIT_GUI_PAGE_DB_DIS`
- Delete `$abapgit_ui_db`

I tried to check if there were other objects in the same situation. They seem to be the only ones.

Please close the issue if you like (issue exists & closed, or not important).
Thanks for reading me.
Sandra

**Comment by mbtools** [comment]
Interesting find, @sandraros. By removing the ui_db package from the repo, it should have been shown as "deleted" in the repo view (together with the classes). On pull these objects should have shown in the popup so you can select and have them deleted. 

I will try to reproduce it

**Comment by mbtools** [comment]
I could not reproduce it. It looks to be working correctly.

1. Clone https://github.com/abapGit-tests/DEVC_main_sub with branch `issue_6607` (which has two sub-packages)
2. Switch to branch `issue_6607_sub2_del` (which is missing the second sub-package)
3. Pull

![image](https://github.com/abapGit/abapGit/assets/59966492/44079414-cc9d-4e9f-927a-fb4675e1fa20)

The program and sub-package show as "to be deleted" and are removed when you select them and click continue.

**Comment by sandraros** [comment]
Hi Marc, thanks for checking. I don't think I did anything special in the past, just pulling from time to time on my ABAP 7.52 SP 04 trial. I just saw the problem while doing something else, checking the list of objects named ZCL_ABAPGIT* in TADIR. Maybe it's me, maybe it was fixed in the past. 

Closing the case for now.

Thanks again.
