### ISSUE TITLE
New online repo: validation of package name

### ISSUE THREAD

**Issue by jfilak** [abapGit/abapGit#6645]
Can I add a check for SAP system type and skip the cl_package_helper=>check_package_name( ) on internal SAP systems?

It is kinda annoying to be prevented from versioning itnernal SAP packages on internal SAP systems.

**Comment by larshp** [comment]
sure, suggest calling this method

```abap
  METHOD zif_abapgit_environment~is_sap_object_allowed.

    rv_allowed = cl_enh_badi_def_utility=>is_sap_system( ).
    IF rv_allowed = abap_true.
      RETURN.
    ENDIF.

    rv_allowed = zcl_abapgit_exit=>get_instance( )->allow_sap_objects( ).

  ENDMETHOD.
```

**Comment by jfilak** [comment]
The invalid package name was reported here: https://github.com/abapGit/abapGit/blob/main/src/objects/sap/zcl_abapgit_sap_package.clas.abap#L391

**Comment by jfilak** [comment]
Well, I was trying to version a package which was created by ignoring the rules. In the case I try to version correctly created package, the check is OK.
