### ISSUE TITLE
Is abapGit handling licenses correctly?

### ISSUE THREAD

**Issue by ConjuringCoffee** [abapGit/abapGit#6654]
When using abapGit in an SAP system, we are not pulling the license file. There isn't really anywhere to put it and abapGit is set up to ignore it.

For example, the MIT License states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

abapGit is licensed under the MIT License too. When we are pulling the files into the SAP system, aren't we effectively breaking the license agreement? The "substantial portion" of the software is in the SAP system, but the license file is nowhere to be found.

I wonder if this means that the license should be included (automatically?) in the source code pulled into the system.

**Comment by larshp** [comment]
its in the entry program to abapgit, 

https://github.com/abapGit/abapGit/blob/60f01499e55b99a39e27ec6bda028ccd308c6d84/src/zabapgit.prog.abap#L6

which is pulled,

![image](https://github.com/abapGit/abapGit/assets/5888506/415e01f0-53fb-4b88-9e2c-366528c1b520)

**Comment by ConjuringCoffee** [comment]
Thanks, I didn't see that. What do you think about putting something into the user documentation? Something like:

> Please note that the repository's license file will not be pulled into SAP systems. If required by your license, make sure to reference or include it in one of your source code files.

**Comment by mbtools** [comment]
You have a good point @ConjuringCoffee. It's good practice to include the license in the (root/main) source as abapGit does. It doesn't have to be the full text. A link to the license or simply an SPDX license tag is ok, imho. But that's up to the owner. 

PS: I'm working on an extension that will let you view the license file in abapGit.

**Comment by larshp** [comment]
> Thanks, I didn't see that. What do you think about putting something into the user documentation? Something like:
> 
> > Please note that the repository's license file will not be pulled into SAP systems. If required by your license, make sure to reference or include it in one of your source code files.

yea, can you help opening a Pull Request with a suggestion?

**Comment by ConjuringCoffee** [comment]
Sure 👍
