### ISSUE TITLE
Export to zip creates file without zip suffix

### ISSUE THREAD

**Issue by tobiashofmann** [abapGit/abapGit#6658]
I created an offline repository for a package that contains some objects. I want to export these using the Export (zip) button/option.

<img width="1019" alt="image" src="https://github.com/abapGit/abapGit/assets/2013590/65a1c8cf-9943-4066-a275-5ab162fe3579">

In the dialog the the filename is given, the type is set to ZIP, but the suffix .zip is not included.

<img width="593" alt="image" src="https://github.com/abapGit/abapGit/assets/2013590/16559e54-9462-4b32-a0f9-f4f3e62cea48">

Clicking on save saves the filename, but without the suffix.

<img width="687" alt="image" src="https://github.com/abapGit/abapGit/assets/2013590/54100229-bff0-43ec-9bd5-ca6bc74cab8e">

It is not possible to open the file, as the file browser does not know what kind of file it is: unknown format

<img width="343" alt="image" src="https://github.com/abapGit/abapGit/assets/2013590/b8ff809b-eeae-46c0-8d92-32d6abe2f382">

Only after adding .zip it is possible to extract the file content.

Would be nict if it is possible to add the .zip suffix to the downloaded filename.

OS: MacOS
Version: 1.126.0 - Standalone Version
SAPGui: Java 7.80 rev3

**Comment by larshp** [comment]
seems okay in windows,
![image](https://github.com/abapGit/abapGit/assets/5888506/b6f6b3cb-3a4a-466c-8174-b33d1e2860eb)

**Comment by larshp** [comment]
try adjusting this method, https://github.com/abapGit/abapGit/blob/ba4cf57dcc37f634fde2ca8ac49d7cdaf86f11a2/src/ui/zcl_abapgit_frontend_services.clas.abap#L419

**Comment by mbtools** [comment]
add `.zip` here:

https://github.com/abapGit/abapGit/blob/ba4cf57dcc37f634fde2ca8ac49d7cdaf86f11a2/src/utils/zcl_abapgit_zip.clas.abap#L213-L213

**Comment by mbtools** [comment]
give it a try, @tobiashofmann
