### ISSUE TITLE
Repo: Switch to Offline not possible

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#6660]
Given any online repo, goto Remote Settings, Switch to Offline and save

![grafik](https://github.com/abapGit/abapGit/assets/17437789/2b3c90a3-ae36-4107-b662-534f31a1acb8)
![grafik](https://github.com/abapGit/abapGit/assets/17437789/bdc5b2b9-8045-443a-819f-8cdb8f008c19)
No message appears and when I try to navigate back I get this message and the changes are not saved
![grafik](https://github.com/abapGit/abapGit/assets/17437789/37aaf3c1-531b-415f-a59b-d9cd52300819)
After 'Switch to Online' it looks like this
![grafik](https://github.com/abapGit/abapGit/assets/17437789/9fc2222f-bd4e-4644-9a44-ff683d59a2e4)
The validation is from here
https://github.com/abapGit/abapGit/blob/e9d8c1d985158360a67f8dcb9b0660902e512e96/src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.abap#L849-L853
![grafik](https://github.com/abapGit/abapGit/assets/17437789/45234f45-2d35-43a1-bb92-ef89709d126a)

I assume it's a side effect from #6635? How has the check to be adjusted? We can we remove it?

**Comment by mbtools** [comment]
yes, remove the complete `if`. offline does not use the URL field anymore
