### ISSUE TITLE
Missing exception handling while using SAP XCO Development Kit causes dumps (CX_XCO_RUNTIME_EXCEPTION and subclasses)

### ISSUE THREAD

**Issue by gardian12** [abapGit/abapGit#6696]
While using the **abapGit Data** functionality dumps occurs due to not properly handled exception raised by the **_SAP XCO Development Kit_**.
The SAP XCO Development Kit throws a bunch of unchecked exceptions, which are all derived from **CX_XCO_RUNTIME_EXCEPTION**.

**First:**
That why, a simple catch at CX_XCO_RUNTIME_EXCEPTION will be the first defense to prevent dumps.

**Second,**
the root cause, why an existing table is not recognized by the XCO Tool has to be investigated.

abapGit source code to be fixed:

- at least: **ZCL_ABAPGIT_DATA_UTILS=>IS_CUSTOMIZING_TABLE**
- ZCL_ABAPGIT_DATA_UTILS=>LIST_KEY_FIELDS

Here is the dump log:

![image](https://github.com/abapGit/abapGit/assets/25589473/c7aa024c-7acc-459c-b0ad-7ddc4db30be8)

![image](https://github.com/abapGit/abapGit/assets/25589473/1690e75e-ab52-49bf-b4b3-ce54cbc435ff)

**Comment by gardian12** [comment]
Yes, I try a fix with your proposal

**Comment by mbtools** [comment]
closed by #6697
