### ISSUE TITLE
TABL produces a diff while adding `<ACTFLAG>U</ACTFLAG>` at remote

### ISSUE THREAD

**Issue by gardian12** [abapGit/abapGit#6700]
Object Type **TABL**

A simple local customizing table will have no diff at the system of development.
But at any remote systems the exact same table produces a diff.
The table is part of a **local package**, no transport layer added.

See screenshot:

![image](https://github.com/abapGit/abapGit/assets/25589473/b98aedfa-85d6-482b-bf90-6d8062774e22)

**QUESTION: Where does **`<ACTFLAG>U</ACTFLAG>`** stand for? What does the diff show?**

Many thanks.

**Comment by mbtools** [comment]
If `actflag` is not initial, the object is only partially active. Some dependencies could not be activated. Check the object in SE11.

**Comment by mbtools** [comment]
no answer. closing
