### ISSUE TITLE
Object should be removed, but has NO deletion flag in transport

### ISSUE THREAD

**Issue by jelliottp** [abapGit/abapGit#6710]
We have a situation where we have multiple packages/repos all residing on the same SAP system, and some code which invokes the abapGit Transport to Branch functionality.

There can then be the scenario where an object's package is reassigned from one repo to another. I would expect to be able to generate:

1. An add commit to the repo the object is newly assigned to
2. A remove commit to the repo the object was removed from

Currently #2 does not seem possible? The error `Object XYZ should be removed, but has NO deletion flag in transport` is thrown from `zcl_abapgit_transport_objects`. I'd like to better understand he reasoning for raising this exception rather than removing the object, and if there is a change I could make to allow for that.

**Comment by mbtools** [comment]
Some object types do not set the deletion flag. We exclude them here;

https://github.com/abapGit/abapGit/blob/45edfa7b0a7aa3c1b255a17d81c30ea9a7099091/src/cts/zcl_abapgit_transport_objects.clas.abap#L67-L76

Which object type is causing the issue in your case?

**Comment by jelliottp** [comment]
Yes, I noticed that but I'm typically just working with classes so not any of the excluded types.

However, In this scenario I'm not expecting the deletion flag to be set. The object still exists, just in another package.

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/blob/main/src/cts/zcl_abapgit_transport_objects.clas.abap

I think looking at `lstate` wont work, it does not always contain the correct value. Instead check if the object exists locally, if not, push the deletion

**Comment by jelliottp** [comment]
In this case though, `lstate` has correctly identified the object to be deleted from the repo. So why issue the exception rather than pushing the delete?

**Comment by larshp** [comment]
yea, well, perhaps its not good to assume SAP standard code does things consistently

**Comment by mbtools** [comment]
The complete if-block I mentioned should be removed since objects can be removed from a repo by either deleting them or by moving them to an outside package.

**Comment by jelliottp** [comment]
> The complete if-block I mentioned should be removed since objects can be removed from a repo by either deleting them or by moving them to an outside package.

This is what I was getting at, I agree. Here's the PR: https://github.com/abapGit/abapGit/pull/6729

**Comment by mbtools** [comment]
Welcome as a "contributor"... or shall we say "deletor" 😉 

Proofs the point that less is more 👍

**Comment by jelliottp** [comment]
Closing, PR merged
