### ISSUE TITLE
HTTP error 421 STRUST (due to injected certificate by Digital Guard?)

### ISSUE THREAD

**Issue by sandraros** [abapGit/abapGit#6720]
Hello,

I just reinstalled my ABAP trial system, with abapGit of course, I have read the chapter "[SAP Trust Manager](https://docs.abapgit.org/user-guide/setup/ssl-setup.html#sap-trust-manager)" but still I had a classic HTTP error 421, which I couldn't solve the classic way:
![image](https://github.com/abapGit/abapGit/assets/34005250/84b5070d-4033-4443-9568-04b178bfae8d)

There are only two certificates available for github.com:

![image](https://github.com/abapGit/abapGit/assets/34005250/357cc3d4-a6e2-4c78-863c-dab48d126f76)

The SMICM trace below shows that the certificates "github.com" and "Digital Guardian, Inc" do match with STRUST (respectively `CN=github.com, O="GitHub, Inc.", L=San Francisco, SP=California, C=US` and `CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1, O=DigiCert Inc, C=US`), but `CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US` is missing.

Maybe there's an option in the browsers to show up the root certificates, but I don't know it. If I'm not wrong, the root certificates can be obtained this way:
![image](https://github.com/abapGit/abapGit/assets/34005250/a17b4c0f-8427-41e0-a9cc-2042eb72780e)

Is it possible to improve the chapter "SAP Trust Manager" to explain how to get the missing root certificate or any alternative?

Or maybe a better solution, to explain how to install the missing certificate from the SMICM trace?

Thank you!
Sandra

Excerpt from SMICM trace (level 3):
```txt
[Thr 139675634906880] CCL[VERIFY]: Cli-00000011: Verification result of SSL server certificate (failed)
[Thr 139675634906880]  Verification result header:
[Thr 139675634906880]   Verification errors
[Thr 139675634906880]    The chain of certificates is incomplete or untrusted, missing certificate of
[Thr 139675634906880]     CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
[Thr 139675634906880]   Verified certificate:
[Thr 139675634906880]    Subject:                              CN=github.com, O="GitHub, Inc.", L=San Francisco, SP=California, C=US
[Thr 139675634906880]    Issuer:                               CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1, O=DigiCert Inc, C=US
[Thr 139675634906880]    Serial Number:                        0C:D0:A8:BE:C6:32:CF:E6:45:EC:A0:A9:B0:84:FB:1C
[Thr 139675634906880]    -----BEGIN CERTIFICATE-----
[Thr 139675634906880]    MIIFajCCBPGgAwIBAgIQDNCovsYyz+ZF7KCpsIT7HDAKBggqhkjOPQQDAzBWMQsw
...
[Thr 139675634906880]    3jSZCpwfqOHBdlxi9ASgKTU+wg0qw3FqtfQ31OwLYFdxh0MlNk/HwkjRSWgCMFbQ
[Thr 139675634906880]    vMkXEPvNvv4t30K6xtpG26qmZ+6OiISBIIXMljWnsiYR1gyZnTzIg3AQSw4Vmw==
[Thr 139675634906880]    -----END CERTIFICATE-----
[Thr 139675634906880]   Used signer certificate:
[Thr 139675634906880]    Subject:                              CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1, O=DigiCert Inc, C=US
[Thr 139675634906880]    Issuer:                               CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
[Thr 139675634906880]    Serial Number:                        07:F2:F3:5C:87:A8:77:AF:7A:EF:E9:47:99:35:25:BD
[Thr 139675634906880]    -----BEGIN CERTIFICATE-----
[Thr 139675634906880]    MIIEFzCCAv+gAwIBAgIQB/LzXIeod6967+lHmTUlvTANBgkqhkiG9w0BAQwFADBh
...
[Thr 139675634906880]    xRqhqjn1VtvChMQ1H3Dau0bwhr9kAMQ+959GG50jBbl9s08PqUU643QwmA==
[Thr 139675634906880]    -----END CERTIFICATE-----
[Thr 139675634906880]  Certificate verification result:
[Thr 139675634906880]   Certificate:
[Thr 139675634906880]    Subject:                              CN=github.com, O="GitHub, Inc.", L=San Francisco, SP=California, C=US
[Thr 139675634906880]   Verification result:
[Thr 139675634906880]    Status:                              Not successful
[Thr 139675634906880]    SignerStatus:                        Not successful
[Thr 139675634906880]    SignerVerificationResult:
[Thr 139675634906880]     Status:                              Not successful
[Thr 139675634906880]     Validity:                            Successful
[Thr 139675634906880]     BasicConstraints:                    Successful
[Thr 139675634906880]     KeyUsage:                            Successful
[Thr 139675634906880]     ObjectStatus:                        Not successful
[Thr 139675634906880]     SignerCert:
[Thr 139675634906880]      Certificate:
[Thr 139675634906880]       Subject:                              CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1, O=DigiCert Inc, C=US
[Thr 139675634906880]      Verification result:
[Thr 139675634906880]       Status:                              Not successful
[Thr 139675634906880]       SignerStatus:                        Not successful
[Thr 139675634906880]       SignerVerificationResult:            None
[Thr 139675634906880]  Trust in PSE:
[Thr 139675634906880]   Token URI                      : tokpse:/usr/sap/NPL/D00/sec/SAPSSLA.pse
[Thr 139675634906880]   Trusted certificate            : CN=anonymous
[Thr 139675634906880]   Trusted certificate            : EMAIL=support@digitalguardian.com, CN="Digital Guardian, Inc", O="Digital Guardian, Inc", L=Waltham, SP=Massachusetts, C=US
[Thr 139675634906880]   Trusted certificate            : CN=github.com, O="GitHub, Inc.", L=San Francisco, SP=California, C=US
[Thr 139675634906880]
[Thr 139675634906880] CCL[SSL]: Cli-00000011: Sending alert of level FATAL: certificate unknown [ssl3_send_alert]
[Thr 139675634906880] CCL[SSL]: Cli-00000011: Error 0xA0600203:
[Thr 139675634906880]     Peer not trusted
[Thr 139675634906880]     SSL3 client handshake failed
[Thr 139675634906880]
[Thr 139675634906880]   SSL:SSL_read(netin= 2459) handshake, processed= 2459
[Thr 139675634906880]   SSL:SiSend(sock=  32)== 0 (SI_OK)       (out=7 of 7)
[Thr 139675634906880]   SSL_get_state()==0x2131 "TLS read server certificate B"
[Thr 139675634906880] *** ERROR during secussl_read() from SSL_read()==SSL_ERROR_SSL
[Thr 139675634906880]   acli SSL session PSE "/usr/sap/NPL/D00/sec/SAPSSLA.pse"
[Thr 139675634906880]   session ciphersuites=150:PFS:HIGH::EC_X25519:EC_P256:EC_HIGH
[Thr 139675634906880]   AnonClient SSL_CTX 7f088809b2c0 pvflags=896 (TLSv1.2,TLSv1.1,TLSv1.0)
[Thr 139675634906880]   TLSextSNI server_name="github.com"
[Thr 139675634906880] secussl_read: SSL_read() failed  (536872221/0x2000051d)
[Thr 139675634906880]    => "Failed to verify peer certificate. Peer not trusted."
```

**Comment by fabianlupa** [comment]
The "Digital Guardian" certificate looks like an injected one in your company proxy setup? This is the chain for me and the export button at the bottom allows for directly exporting each of them.

![image](https://github.com/abapGit/abapGit/assets/5270359/24d4741f-3e90-4947-8d36-31e79228302d)

**Comment by sandraros** [comment]
Nice to know that people can see different certificates based on their configuration. I can't see any company proxy. Maybe my company is using Digital Guardian security software which would inject an alternate certificate for some reason. I couldn't find anything in the Web about Digital Guardian and injected certificates.

**Comment by mbtools** [comment]
Your suspicion is correct. I didn't know how certificate interception works but ChatGPT was helpful. Here's the explanation for reference:

Q: "You are an internet security specialist. How does certificate injection work to protect our network against data loss?"

A: "Certificate injection, also known as SSL/TLS certificate interception or SSL/TLS interception, is a method used by network administrators or security systems to inspect and monitor encrypted network traffic. It involves intercepting the SSL/TLS handshake process between a client and a server and replacing the server's digital certificate with a locally generated one.

The process of certificate injection typically works as follows:

1. The client initiates a connection to a server that uses SSL/TLS for secure communication.
2. The interceptor intercepts the client's connection request and presents a locally generated digital certificate to the client instead of the server's actual certificate.
3. The client, unaware of the interception, performs the SSL/TLS handshake process with the interceptor, believing it to be the legitimate server.
4. The interceptor then establishes a separate SSL/TLS connection with the actual server on behalf of the client.
5. The interceptor acts as a proxy, decrypting the encrypted traffic from the client, inspecting it for security purposes, and re-encrypting it before forwarding it to the server.
6. Similarly, the interceptor decrypts the encrypted traffic received from the server, inspects it, and re-encrypts it before sending it back to the client.

By intercepting and decrypting the SSL/TLS traffic, the interceptor gains visibility into the content of the encrypted communication, allowing it to analyze the data for security threats, such as malware, unauthorized access, or data loss prevention.

Certificate injection can be used to protect a network against data loss by allowing organizations to monitor and control the flow of sensitive information. It enables the inspection of encrypted traffic for potential threats, such as data exfiltration or leakage of confidential information.

However, it is important to note that certificate injection can introduce security risks if not implemented properly. It requires the installation of a trusted root certificate on client devices, which can potentially be abused by malicious actors to perform man-in-the-middle attacks. Therefore, certificate injection should only be implemented by authorized network administrators or security systems, and proper measures should be taken to secure the interceptor and the generated certificates to prevent misuse.

It is recommended to consult with cybersecurity professionals or experts to ensure the correct implementation and configuration of certificate injection for protecting your own network against data loss."

--

Looks like your browser "sees" the Internet through a different lens than the ABAP system, which isn't behind the DG software and requires the certificate chain mentioned by Fabian (+ the *.github.com in case of write requests). 

[github_certificate_chain.zip](https://github.com/abapGit/abapGit/files/13780433/github_certificate_chain.zip)

**Comment by sandraros** [comment]
Thanks. I'm not surprised that everything done on my company laptop is observed, interesting to see how it's done, and that if I surf via the ABAP Trial, the data is currently not decrypted via an injected certificate (yet).
Back to my issue, I'd be happy to have an ABAP program to read the certificates from the ICM trace and propose to upload them to STRUST 😉

**Comment by mbtools** [comment]
Does the trace include the missing certificate as `---BEGIN CERT... ---END CERT...` (in your case for CN=DigiCert Global Root CA)?

**Comment by sandraros** [comment]
Yes, with trace level 3, there is the chain of all certificates received and checked in STRUST. To simplify my question, I only mentioned MIIF... and MIIE... but there's also MIID... the one for CN=DigiCert Global Root CA.

The program could be something like that (in this example, the Web site is obtained from an existing RFC destination):
```
INCLUDE icmdef. " defines the constant DP_PLUGIN_OP_CHNG_PARAM.
INCLUDE tskhincl. " defines the constant OPCODE_ICM.
TYPES icm_lines_t TYPE STANDARD TABLE OF icm_lines WITH DEFAULT KEY.

START-OF-SELECTION.
  DATA icm_info_data TYPE icm_info.
  DATA icm_servlist2 TYPE TABLE OF icm_sinfo2.

  CALL FUNCTION 'ICM_GET_INFO2'
    IMPORTING  info_data   = icm_info_data
    TABLES     servlist    = icm_servlist2
*               THRLIST     = ICM_THRLIST
*               SERVLIST3   = ICM_SERVLIST
    EXCEPTIONS icm_error   = 1
               icm_timeout = 2
               OTHERS      = 6.

  " Credit: subroutine ICMAN_SET_PARAM in RSMONICM.
  DATA p_name  TYPE pfeparname VALUE 'rdisp/TRACE'.
  DATA p_value TYPE pfepvalue.
  DATA rc TYPE sysubrc.
  p_value = '3'.
  CALL 'ThSysInfo'                                        "#EC CI_CCALL
       ID 'OPCODE'    FIELD opcode_icm
       ID 'ICMOPCODE' FIELD dp_plugin_op_chng_param
       ID 'PNAME'     FIELD p_name
       ID 'PVALUE'    FIELD p_value.
  rc = sy-subrc.
  CASE rc.
    WHEN icmeok.
      MESSAGE s005(icm).
    WHEN icmenotavail.
      MESSAGE i032(icm).
    WHEN OTHERS.
      MESSAGE e006(icm) WITH rc.
  ENDCASE.

  CALL FUNCTION 'ICM_RESET_TRACE'
    EXCEPTIONS icm_op_failed      = 1
               icm_not_authorized = 2
               OTHERS             = 3.

  DATA lo_http_client TYPE REF TO if_http_client.
  cl_http_client=>create_by_destination( EXPORTING  destination = 'RFC_DESTINATION'
                                         IMPORTING  client      = lo_http_client
                                         EXCEPTIONS OTHERS      = 1 ).
  DATA request TYPE REF TO if_http_request.
  request = lo_http_client->request.
  request->set_method( 'GET' ).
  request->set_version( if_http_request=>co_protocol_version_1_1 ). " HTTP 1.0 or 1.1
  lo_http_client->send( EXCEPTIONS OTHERS = 1 ).
  DATA l_return_code TYPE i.
  DATA l_content     TYPE string.
  lo_http_client->receive( EXCEPTIONS OTHERS = 1 ).
  lo_http_client->response->get_status( IMPORTING code = l_return_code ).
  l_content = lo_http_client->response->get_cdata( ).
  lo_http_client->close( EXCEPTIONS OTHERS = 1 ).

  " Credit: subroutine ICMAN_SHOW_TRACE in RSMONICM.
  DATA p_filename      TYPE icm_lines-lines VALUE 'dev_icm'.
  DATA p_first_n_lines TYPE i               VALUE 0.
  DATA p_last_n_lines  TYPE i               VALUE 0.
  DATA(icm_linetab) = VALUE icm_lines_t( ).
  CALL FUNCTION 'ICM_READ_TRC_FILE2'
    EXPORTING  icm_filename      = p_filename
               icm_last_n_lines  = p_last_n_lines
               icm_first_n_lines = p_first_n_lines
    TABLES     lines             = icm_linetab
    EXCEPTIONS icm_open_failed   = 1
               OTHERS            = 2.

  TYPES ty_certificate_line  TYPE c LENGTH 64.
  TYPES ty_certificate_table TYPE STANDARD TABLE OF ty_certificate_line WITH EMPTY KEY.

  FIND REGEX `\[Thr [^\]]+\] -----BEGIN CERTIFICATE-----` IN TABLE icm_linetab MATCH LINE DATA(start_line).
  FIND REGEX `\[Thr [^\]]+\] -----END CERTIFICATE-----` IN TABLE icm_linetab MATCH LINE DATA(end_line).
  FIND REGEX `\[Thr [^\]]+\] ` IN TABLE icm_linetab MATCH LENGTH DATA(length).

  DATA(certificate_table) = VALUE ty_certificate_table( ).
  LOOP AT icm_linetab REFERENCE INTO DATA(icm_line) FROM start_line TO end_line.
    APPEND icm_line->lines+length TO certificate_table.
  ENDLOOP.

  " Credit: subroutine ICMAN_SET_PARAM in RSMONICM.
  p_value = icm_info_data-trace_lvl.
  CALL 'ThSysInfo'                                        "#EC CI_CCALL
       ID 'OPCODE'    FIELD opcode_icm
       ID 'ICMOPCODE' FIELD dp_plugin_op_chng_param
       ID 'PNAME'     FIELD p_name
       ID 'PVALUE'    FIELD p_value.
  rc = sy-subrc.
  CASE rc.
    WHEN icmeok.
      MESSAGE s005(icm).
    WHEN icmenotavail.
      MESSAGE i032(icm).
    WHEN OTHERS.
      MESSAGE e006(icm) WITH rc.
  ENDCASE.
```

**Comment by mbtools** [comment]
Nice idea! Could be a good addition to the SSL test tool we already have:

Turn on trace, run test, if test fails read trace file and capture missing certificates, update STRUST with missing certificates

https://github.com/Marc-Bernard-Tools/ABAP-Tools-for-abapGit/blob/main/src/zabapgit_test_ssl.prog.abap

We can steal the update of STRUST from my tools here:

https://github.com/Marc-Bernard-Tools/MBT-Package-Manager/blob/main/src/core/%23mbtools%23cl_setup.clas.abap#L206-L248

https://github.com/Marc-Bernard-Tools/MBT-Package-Manager/blob/main/src/core/%23mbtools%23cl_strust.clas.abap

I have no time for it though...

**Comment by mbtools** [comment]
If someone wants to pick this up, the info is above. Closing

**Comment by sandraros** [comment]
Code proposed here: https://github.com/sandraros/zcerti
Works in 7.52 SP04.

**Comment by mbtools** [comment]
Yes 👍 I put up the certificate fetcher so we can build an ABAP tool that does just that: update any expired certificates by pressing F8 or schedule it and don't worry about strust again. Just haven't had the time to get to it
