### ISSUE TITLE
Request for Documentation Adjustment

### ISSUE THREAD

**Issue by francisco-milan** [abapGit/abapGit#6722]
Dear abapGit Team,

  I am reaching out to bring to your attention a small correction needed in the documentation for the abapGit tool.

In the user guide under the "Getting Started" section, specifically in the installation guide at the following link: https://docs.abapgit.org/user-guide/getting-started/install.html, there is a minor error in Step 5.

Currently, it states: "5. Select 'Clone Online Repo'". However, the correct instruction should be: "5. Select 'Create Online Repo'".

I believe making this adjustment will help users navigate the process more smoothly. Your attention to this matter is greatly appreciated.

Thank you for maintaining such valuable documentation, and I look forward to seeing the correction in place.

Best regards,

Francisco Milan.

**Comment by francisco-milan** [comment]
![Screenshot 2023-12-27 165330](https://github.com/abapGit/abapGit/assets/36721657/758eab46-6820-4cf2-a213-af0dba545c0d)

**Comment by larshp** [comment]
merged, thanks
