### ISSUE TITLE
HAS_REMOTE_SOURCE refactoring might require manual intervention

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#6723]
I created a new repo and wanted to push my changes. To my surprise no changes were listed in abapGit.

As it turned out abapGit chose to ignore all changes as there apparently was no remote:

![image](https://github.com/abapGit/abapGit/assets/5270359/99a9bed8-177c-4b44-a5fd-ca98d4d4f560)

`ZCL_ABAPGIT_REPO->ZIF_ABAPGIT_REPO~HAS_REMOTE_SOURCE` looks like this in my system:

![image](https://github.com/abapGit/abapGit/assets/5270359/f213e73b-3169-4db2-8084-79dfd499b406)

In dd63de8294d127574d6a100237f1db5a4ab8233c this method was changed from being abstract and implemented in subclasses to an interface method implemented in the base class. This moving of a method with the same name between being defined directly in a class and in an interface was problematic before if I recall correctly. Here this is especially annoying though.

The actual implementation looks like this which wasn't pulled on update in my system (?):
https://github.com/abapGit/abapGit/blob/e86d47314018c0ff31c7dcbd7ee1c4d4116359c1/src/repo/zcl_abapgit_repo.clas.abap#L416-L418

Since an empty implementation was somehow pulled abapGit also couldn't find any remote for itself after the update and therefore didn't list any diffs to pull.... including for this method.... Assuming the update went just fine I didn't bother to check or update the standalone version to update.

Now I checked the standalone version. It does list some diffs, but not for this method? I then checked the class manually myself and found an inconsistency. This is the CS include which I assume is used to determine the changes:
![image](https://github.com/abapGit/abapGit/assets/5270359/57284869-820e-45d2-a89f-b4d364925eea)

And this is the CM include which is actually used at runtime:
![image](https://github.com/abapGit/abapGit/assets/5270359/9d9ad04f-d7d6-49ee-9298-0847611f1b11)

Note one has the interface prefixed and the other doesn't. There is no CM include for `has_remote_source` without the interface prefix. I added the prefix in ADT and now both includes are in sync again and abapGit works normally again. I once learned to never rely on the aliases in the implementation of interface methods, only the caller may use the alias, to avoid problems such as these. I suggest adding the `interface~` prefix in all implementations. Would maybe also be a good idea for a new abaplint check...?

A new year's tale ;)

**Comment by mbtools** [comment]
The implementation should certainly have the interface prefix. That's a bug in SAP to allow it without, imho. 

These aliases are a pain #5580. But it's quit some work to get rid of the remaining ones. Feel free to help 😉

**Comment by fabianlupa** [comment]
> Is it a bug in AG when deserializing the class or SAP code that updates the wrong include or doesn't update it at all?

Difficult to find out. I had one go at checking out the commit before, updating to current without the repo classes and the interface and then pulling only them while debugging.

<details>
<summary>Some notes</summary>
The interface is pulled first. Since the previous version of ZCL_ABAPGIT_REPO already implemented ZIF_ABAPGIT_REPO you have this situation after the interface is updated before the class is updated:

- ZCL_ABAPGIT_REPO->HAS_REMOTE_SOURCE is still abstract in the class
- ZCL_ABAPGIT_REPO->ZIF_ABAPGIT_REPO~HAS_REMOTE_SOURCE is now part of the class, but not implemented
- The alias HAS_REMOTE_SOURCE for ZIF_ABAPGIT_REPO~HAS_REMOTE_SOURCE does not yet exist in ZCL_ABAPGIT_REPO

On updating the class SEO_CLASS_CREATE_COMPLETE is not called because no attributes changed. REVERT_SCAN_RESULT on the public section source scanning the adds the alias and removed the abstract method definition. The first call to GET_METHOD_INCLUDES doesn't get any relevant include, since the method implementation doesn't exist yet and didn't before either (because abstract method). DETERMINE_METHOD_INCLUDE for the HAS_REMOTE_SOURCE doesn't find anything directly and also doesn't find anything using the alias resolver. The  method include is then generated without the prefix using SEO_METHOD_GENERATE_INCLUDE which also creates the `METHOD has_remote_source. ENDMETHOD.` frame. After the include generation abapGit correctly gets the include name and updates the source. Later abapGit updates CS include succesfully. Repair is triggered because FIND_REMOTE_DOT_ABAPGIT doesn't exist anymore. Note neither the CS include nor the method includes are committed yet (or at least are not accessable using READ REPORT or SE24 / SHOW_CLIF in another GUI window).

Repair identifies HAS_REMOTE_SOURCE as an interface method implementation and does not account for the alias. It attempts to find an include for `ZIF_ABAPGIT_REPO~HAS_REMOTE_SOURCE` but fails as the list has it as `HAS_REMOTE_SOURCE`. It then generates a new include for it with the empty implementation. The previously created include is identified as obsolete and an attempt is made to delete it. Which actually worked this time but obviously didn't the last time. Standalone version reports this  diff now:
![image](https://github.com/abapGit/abapGit/assets/5270359/a474ff2f-38e0-4152-a06d-5d5649059ae7)

Also the subclass redefinition were not adjusted and need another pull:
![image](https://github.com/abapGit/abapGit/assets/5270359/805f4e8f-142d-4cd5-82c2-a01c23044397)
![image](https://github.com/abapGit/abapGit/assets/5270359/8385e97b-7dda-435e-8bfe-568a74e64659)

The failed pull on the subclasses accidently cause the developer version to still work in this case...
</details>

So slightly different behavior but still bad. I assume the repair class pool utility was written before the source based editor was available and never updated. In the form based editor I assume it's not possible / very difficult to implement an interface method using the alias. Therefore it doesn't account for the aliases. I doubt it worth doing much of anything about this on our side.

**Comment by mbtools** [comment]
Nice analysis. As long as there are diffs, we can live with it. 

For AG itself, the answer is to eliminate the aliases. A general solution would be to drop the class and subclasses and recreate them. Figuring out under what circumstances this would be necessary, is rather complex and unlikely to get coded. Or we go for a general drop and replace of classes but that would have to be studied first.

**Comment by larshp** [comment]
hmm, I'm running into the same issue, there are no diffs in abapGit, due to the bug...

**Comment by larshp** [comment]
as a workaround, I pulled https://github.com/abapGit/abapGit/pull/6724 via STANDALONE, and the global version works as expected

**Comment by larshp** [comment]
@fabianlupa try pulling the latest version? unless you have done manual fixes?

**Comment by fabianlupa** [comment]
> @fabianlupa try pulling the latest version? unless you have done manual fixes?

I did the manual fix and was already struggling to reproduce the exact scenario.

**Comment by fabianlupa** [comment]
Close and leave it for reference?

**Comment by larshp** [comment]
time to close and unpin?

**Comment by fabianlupa** [comment]
:+1: Until next time ;)
