### ISSUE TITLE
Runtime error `SYSTEM_NO_ROLL` in background mode

### ISSUE THREAD

**Issue by ConjuringCoffee** [abapGit/abapGit#6727]
Hello abapGit community, 

I am encountering runtime error `SYSTEM_NO_ROLL` when executing the background mode. The memory is getting too full.

The background mode is initiated from method `RUN` of `ZCL_ABAPGIT_BACKGROUND`. It seems like each individual repository can be processed just fine. However, every instance of `ZCL_ABAPGIT_REPO_ONLINE` still remains in the session with a lot of data.  

Here's an excerpt from the dominator tree after a few repositories have been processed:
![image](https://github.com/abapGit/abapGit/assets/72548231/309bdbf3-5301-4c41-96b5-976fb8d1e792)

Each instance still needs memory because the tables `MT_LOCAL`, `MT_REMOTE` and `MT_OBJECTS` remain filled. I think it would be a good idea to somehow "reset" / "clear" a repository instance after it has been processed. 

Another cheap alternative could be to process each repository in a separate session using destination `NONE`.

What are your thoughts on this?

**Comment by larshp** [comment]
suggest adding a method in ZCL_ABAPGIT_REPO_SRV to clear the MT_LIST (take care of MV_INIT too?)

**Comment by ConjuringCoffee** [comment]
I'll try this and report back, thanks.

**Comment by larshp** [comment]
or alternatively try calling ZIF_ABAPGIT_REPO~REFRESH

**Comment by ConjuringCoffee** [comment]
@larshp, can you please re-open this issue? I'm getting the same error again, so some more optimizations are needed.

I suspect that `MT_OBJECTS` needs to be cleared as I mentioned in #6728, but I'll do some additional analysis first

**Comment by larshp** [comment]
@ConjuringCoffee just open another issue, with a link to this one, if its related
