### ISSUE TITLE
Change all injector classes to `FOR TESTING`

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6732]
Injector classes should only be usable in unit tests (but not in production code). 

```abap
CLASS zcll_abapgit_injector DEFINITION FOR TESTING...
```

https://github.com/search?q=repo%3AabapGit%2FabapGit%20injector&type=code

**Comment by mbtools** [comment]
Issue https://github.com/abapGit/abapGit/pull/3614

**Comment by larshp** [comment]
feel free to remove the skipping of longtexts in sci client
