### ISSUE TITLE
Objects missing in Github repository.

### ISSUE THREAD

**Issue by mirashirahul** [abapGit/abapGit#6734]
Hello Team,

I am using ABAPGit v1.125.0. I have mapped my package with online repo. While stating the objects, I found that some of the objects are missing. I am not able to push to online repo. Could you please help me if any one has faced this issue? I was referring issue https://github.com/abapGit/abapGit/issues/2297 but have some more questions about remove and recreate online repo. Does it mean I need to create new repo or can i use the existing online repo mapping with my package?

**Comment by larshp** [comment]
see https://github.com/abapGit/abapGit/issues/6723

try updating to the latest version via ZABAPGIT_STANDALONE

**Comment by mbtools** [comment]
From the Repo List, go to Debug Info. Download the output and attach it here (as zip)

**Comment by mirashirahul** [comment]
> From the Repo List, go to Debug Info. Download the output and attach it here (as zip)

I am getting error while reading report ZABAPGIT_USER_EXIT.

**Comment by mbtools** [comment]
comment all coding of `ZABAPGIT_USER_EXIT`. then debug info should work. You  can also attach the user exit coding

**Comment by mirashirahul** [comment]
> comment all coding of `ZABAPGIT_USER_EXIT`. then debug info should work. You can also attach the user exit coding

[ABAPGIT_Debug.pdf](https://github.com/abapGit/abapGit/files/13920105/ABAPGIT_Debug.pdf)

@mbtools: apologize for delayed response. Please find attached debug info.

**Comment by mbtools** [comment]
This looks very normal and up-to-date. 

It could either be that objects are part of the ignore list (.abapGit.xml) or they are generated by other objects and therefore excluded.

**Comment by mirashirahul** [comment]
> This looks very normal and up-to-date.
> 
> It could either be that objects are part of the ignore list (.abapGit.xml) or they are generated by other objects and therefore excluded.

Yes. It is generated by other objects and not excluded. Can we force to add the object into github 

![image](https://github.com/abapGit/abapGit/assets/91226073/d654e134-7d2b-4929-ae56-d549997274f3)

**Comment by larshp** [comment]
@mirashirahul it looks like a SAP object in SAP namespace, are you sure you want to commit it?

**Comment by mirashirahul** [comment]
> @mirashirahul it looks like a SAP object in SAP namespace, are you sure you want to commit it?

The object is custom object which was generated with standard object.

**Comment by mirashirahul** [comment]
> classes inheriting from `cl_sadl_gtk_exposure_mpc` are generated by DDLS objects i.e. CDS views. They are excluded by abapGit and created automatically when importing/pulling the corresponding DDLS object.
> 
> https://github.com/abapGit/abapGit/blob/c4639a3a12a4902bfdedd16a6570f1fd930faf7f/src/objects/zcl_abapgit_object_clas.clas.abap#L916-L919

Thank you for your valuable feedback.
