### ISSUE TITLE
Ignore Directory

### ISSUE THREAD

**Issue by Th0masMa** [abapGit/abapGit#6757]
Hello,

I would like to pull from my Git repository into an ABAP Cloud project (ABAP Trial) in ADT. Unfortunately, a package already exists in the ABAP trial, so I cannot carry out the pull. Is it possible to exclude a Git Repository Directory from the pull?

Best Regards
Thomas

**Comment by mbtools** [comment]
You can create the repo in abapGit with "ignore sub-packages" but that applies to all sub-packages. 

Or fork the repo on the git host and delete everything you don't want. Then pull.

**Comment by mbtools** [comment]
another alternative is to edit `.abapgit.xml` in your fork and add the directory to the ignored files:
https://docs.abapgit.org/user-guide/repo-settings/dot-abapgit.html#ignore-files

Did this help?

**Comment by mbtools** [comment]
no answer. closing
