### ISSUE TITLE
 ZABAPGIT HTTP Client error

### ISSUE THREAD

**Issue by hakimred** [abapGit/abapGit#6768]
Hello
I m getting "HTTP Client" error when i try to connect to ABAP repository (RAP) in github. Please advice.

Regards,
Abdul Hakim
![abapgit error](https://github.com/abapGit/abapGit/assets/35043777/930c7f63-58b2-450d-9254-9f8a3c44b650)

**Comment by christianguenter2** [comment]
Try putting a breakpoint here and check what's wrong with `cl_http_client=>create_by_url`
https://github.com/abapGit/abapGit/blob/cbf0326fb0b98c2859dd42212dd04b926818dce2/src/http/zcl_abapgit_http.clas.abap#L163

**Comment by hakimred** [comment]
> Try putting a breakpoint here and check what's wrong with `cl_http_client=>create_by_url`
> 
> https://github.com/abapGit/abapGit/blob/cbf0326fb0b98c2859dd42212dd04b926818dce2/src/http/zcl_abapgit_http.clas.abap#L163

![Error screenshot_abapgit](https://github.com/abapGit/abapGit/assets/35043777/1f5ecb5a-d5ca-4074-b9a0-ebb0c591ff80)

**Comment by christianguenter2** [comment]
yeah, and what's wrong inside `cl_http_client=>create_by_url`?

**Comment by hakimred** [comment]
> yeah, and what's wrong inside `cl_http_client=>create_by_url`?

:-)   Please find the exact location where the error is thrown. 
![ERROR_Screenshot_abapgit_01](https://github.com/abapGit/abapGit/assets/35043777/03c9f1c2-d96c-406d-a2b7-66de7db7a7a5)

**Comment by larshp** [comment]
abapGit uses the `ANONYM` PSE by default, try going to transaction `STRUST` and check it exists?

https://github.com/abapGit/abapGit/blob/cbf0326fb0b98c2859dd42212dd04b926818dce2/src/exits/zcl_abapgit_exit.clas.abap#L369

**Comment by mbtools** [comment]
Note: This was fairly well documented at https://docs.abapgit.org/user-guide/setup/ssl-setup.html#sap-trust-manager
