### ISSUE TITLE
Fix typos and adjust comments within the codebase

### ISSUE THREAD

**Issue by francisco-milan** [abapGit/abapGit#6777]
Dear abapGit Team,

I wanted to bring to your attention that I have identified a few typos within the codebase. Some of these are visible in error messages presented to abapGit users, while others are part of the comments in the code.

While some of the typos may not have a direct impact on functionality, I believe their correction will significantly improve both the overall readability of the source code, and the user experience.

I will address these minor issues by means of pull requests #6778, #6779, #6780, #6785 and #6786.
If you have any specific considerations or preferences regarding this matter, please let me know.

Best regards,

Francisco Milan.

**P.S. Below are the changes included in pull request #6778:**

1. Class: zcl_abapgit_transport_mass.
- Line 66. Fixing typo. Inconsistent capitalization.
The widely accepted and recognized convention for the application is to refer to it as "abapGit" with specific case sensitivity. Using "ABAPGit" (in different capitalization) is not consistent with the established naming convention and may lead to confusion within the community familiar with the application.
![image](https://github.com/abapGit/abapGit/assets/36721657/d314ea39-9ff7-4cff-aaeb-0270e05592db)

2. Class: zcl_abapgit_git_pack.
- Line: 231. Incorrect placement of the letter "i".
- Line 937. Incorrect placement of the letter "i".
The correct spelling of the word is "failed", not "falied". The typo in this case involves the incorrect placement of the letter "i".
![image](https://github.com/abapGit/abapGit/assets/36721657/5bf9477e-c0ce-49bd-9530-611e6c695bef)

3. Class: zcl_abapgit_http_client.
- Line: 155. Missing "r" in the word "occured".
The correct spelling of the word is "occurred", not "occured". The correct spelling contains an additional "r".
![image](https://github.com/abapGit/abapGit/assets/36721657/f21a7774-5291-4a89-afd4-940eabb5784b)

4. Class: zcl_abapgit_object_aifc.
Line: 210. Missing " " (space) and inconsistent capitalization.
Line: 397. Missing " " (space) and inconsistent capitalization.
The correct term is "Field Symbol".
![image](https://github.com/abapGit/abapGit/assets/36721657/8a059ecd-bbf0-4407-b307-7688e18753e6)

5. Class: zcl_abapgit_object_char.
- Line: 70. Missing "c" in the word "acquire".
The correct spelling of the word is "acquire", not "aquire". The correct spelling contains a letter "c".
![image](https://github.com/abapGit/abapGit/assets/36721657/811f1425-6c7e-4c6e-94bf-03346380be28)

6. Class: zcl_abapgit_object_ensc.
- Line: 58. Missing "r" in the word "occured".
- Line 127. Missing "r" in the word "occured".
- Line 245. Missing "r" in the word "occured".
The correct spelling of the word is "occured", not "occured"." The correct spelling contains an additional "r".
![image](https://github.com/abapGit/abapGit/assets/36721657/a3065cde-2b1f-478f-94fd-b18f43e9691f)

7. Class: zcl_abapgit_object_oa2p.
- Line: 72. Missing "t" in the word "getting".
- Line 268. Missing "t" in the word "getting".
The correct spelling of the word is "getting", not "geting". The correct spelling contains an additional "t".
![image](https://github.com/abapGit/abapGit/assets/36721657/678e001d-96cb-4710-945c-cf7b45b637c1)

8. Class: zcl_abapgit_object_otgr.
- Line: 69. Missing "c" in the word "acquire".
The correct spelling of the word is "acquire", not "aquire". The correct spelling contains a letter "c".
![image](https://github.com/abapGit/abapGit/assets/36721657/d7154489-a2c6-4dec-8703-96a27673dc83)

9. Class: zcl_abapgit_object_saxx_super.
- Line: 139. Missing "r" in the word "occured".
- Line: 212. Missing "r" in the word "occured".
- Line: 259. Missing "r" in the word "occured".
The correct spelling of the word is "occurred", not "occured". The correct spelling contains an additional "r".
![image](https://github.com/abapGit/abapGit/assets/36721657/374bb7d5-c019-498a-aa95-a898cc249b99)

10. Class: zcl_abapgit_object_ssfo.
- Line: 512. Missing "r" in the word "occured".
The correct spelling of the word is "occurred", not "occured". The correct spelling contains an additional "r".
![image](https://github.com/abapGit/abapGit/assets/36721657/8a9f7d8f-8ca7-43bc-afdd-6f5e46c21941)

11. Class: zcl_abapgit_objects
- Line: 460. Extra "s" in the word "decision".
The correct spelling of the word is "decision", not "descision". The typo involves an additional "s".
![image](https://github.com/abapGit/abapGit/assets/36721657/ec77f056-5ded-459f-8252-cc5eb46d23df)

12. Class: zcx_abapgit_exception.
- Line: 105. Missing "r" in the word "occured".
The correct spelling of the word is "occurred", not "occured". The correct spelling contains an additional "r".
![image](https://github.com/abapGit/abapGit/assets/36721657/6c86a044-d1cf-44a8-9cf1-8b82112061bf)

**Comment by larshp** [comment]
thanks 👍 just open a PR, or multiple. But try to gather it so we dont get 60 PRs 😄

**Comment by francisco-milan** [comment]
**Below are the changes included in pull request** #6779:

13. Ast generieren lassen (text in German, will be translated to English).
Class: zcl_abapgit_ecatt_script_downlLine: 354
- Line: 354. Translating text in German. 
"Ast generieren lassen" translates to "Generate branch" in English.
- Line: 370. Translating text in German. 
"Ast in Hauptbaum haengen" translates to "Hang a branch in the main tree" in English. 
![image](https://github.com/abapGit/abapGit/assets/36721657/e1fb063a-766b-4818-950d-f693f6fffd45)

**Comment by francisco-milan** [comment]
**Fixes for the typos in the words below are work in progress and will be addressed in a new PR**
13. Syncronize (the correct spelling is "Synchronize").
14. diplay (the correct spelling is "display").
15. Toogle (the correct spelling is "Toggle").
16. averwriting (the correct spelling is "overwriting").
17. refering (the correct spelling is "referring").
18. discarted (the correct spelling is "discarded").
19. highighter (the correct spelling is "highlighter").
20. struture (the correct spelling is "structure").
21. atribute (the correct spelling is "attribute").
22. contructor (the correct spelling is "constructor").
23. overwritting (the correct spelling is "overwriting").
24. resolveable (the correct spelling is "resolvable").
25. acknoledge (the correct spelling is "acknowledge").
26. woul (the correct spelling is "would").
27. Seriazation (the correct spelling is "Serialization").
28. Intialize (the correct spelling is "Initialize").
29. initilization (the correct spelling is "initialization").
30. maintein tabeles (the correct spelling is "maintain tables").
31. comapatible (the correct spelling is "compatible").
32. conent (the correct spelling is "content").
33. paramters (the correct spelling is "parameters").
34. serilization (the correct spelling is "serialization").
35. ourselve (the correct spelling is "ourselves").
36. rerorded (the correct spelling is "reordered").
37. inpredictable (the correct spelling is "unpredictable").
38. donwnpoort (the correct spelling is "downport").
39. activting (the correct spelling is "activating").
40. messsages (the correct spelling is "messages").
41. Otherweise (the correct spelling is "Otherwise").
42. unintialized (the correct spelling is "uninitialized").
43. deserialisation (the correct spelling is "deserialization").
44. enqueu (the correct spelling is "enqueue").
45. criterias (the correct spelling is "criteria").
46. handeled (the correct spelling is "handled").
47. Netweaver realeses (the correct spelling is "NetWeaver releases").
48. entrys (the correct spelling is "entries").

**Comment by francisco-milan** [comment]
**Fixes for the typos in the words below are work in progress and will be addressed in a new PR**
. Syncronize (the correct spelling is "Synchronize").
. diplay (the correct spelling is "display").
. Toogle (the correct spelling is "Toggle").
. averwriting (the correct spelling is "overwriting").
. refering (the correct spelling is "referring").
. discarted (the correct spelling is "discarded").
. highighter (the correct spelling is "highlighter").
. struture (the correct spelling is "structure").
. atribute (the correct spelling is "attribute").
. contructor (the correct spelling is "constructor").
. overwritting (the correct spelling is "overwriting").
. resolveable (the correct spelling is "resolvable").
. acknoledge (the correct spelling is "acknowledge").
. woul (the correct spelling is "would").
. Seriazation (the correct spelling is "Serialization").
. Intialize (the correct spelling is "Initialize").
. initilization (the correct spelling is "initialization").
. maintein tabeles (the correct spelling is "maintain tables").
. comapatible (the correct spelling is "compatible").
. conent (the correct spelling is "content").
. paramters (the correct spelling is "parameters").
. serilization (the correct spelling is "serialization").
. ourselve (the correct spelling is "ourselves").
. rerorded (the correct spelling is "reordered").
. inpredictable (the correct spelling is "unpredictable").
. donwnpoort (the correct spelling is "downport").
. activting (the correct spelling is "activating").
. messsages (the correct spelling is "messages").
. Otherweise (the correct spelling is "Otherwise").
. unintialized (the correct spelling is "uninitialized").
. deserialisation (the correct spelling is "deserialization").
. enqueu (the correct spelling is "enqueue").
. criterias (the correct spelling is "criteria").
. handeled (the correct spelling is "handled").
. Netweaver realeses (the correct spelling is "NetWeaver releases").
. entrys (the correct spelling is "entries").

**Comment by francisco-milan** [comment]
**Fixes for the typos in the words below are work in progress and will be addressed in a new PR.**
1. comapatible (the correct spelling is "compatible").
2. conent (the correct spelling is "content").
3. paramters (the correct spelling is "parameters").
4. serilization (the correct spelling is "serialization").
5. ourselve (the correct spelling is "ourselves").
6. rerorded (the correct spelling is "reordered").
7. inpredictable (the correct spelling is "unpredictable").
8. donwnpoort (the correct spelling is "downport").
9. activting (the correct spelling is "activating").
10. messsages (the correct spelling is "messages").
11. Otherweise (the correct spelling is "Otherwise").
12. unintialized (the correct spelling is "uninitialized").
13. deserialisation (the correct spelling is "deserialization").
14. enqueu (the correct spelling is "enqueue").
15. criterias (the correct spelling is "criteria").
16. handeled (the correct spelling is "handled").
17. Netweaver realeses (the correct spelling is "NetWeaver releases").
18. entrys (the correct spelling is "entries").

**Comment by francisco-milan** [comment]
Fixes for the typos in the words below are work in progress and will be addressed in a new PR.

.    enqueu (the correct spelling is "enqueue").
.    Netweaver realeses (the correct spelling is "NetWeaver releases").
.    conent (the correct spelling is "content").
.    havent (the correct spelling is "haven't")
.    doesnt (the correct spelling is "doesn't")
.    lcl_object_descision_list (the correct spelling is "lcl_object_decision_list").
.    testclass (the correct spelling is "test class").
.    Unformly (the correct spelling is "Uniformly").
.    agrueable (Should it be "arguable or agreeable?").
.    tage (the correct spelling is "tag").
.    even tho (the correct spelling is "even though").
.    and and (duplicate word "and").
.    all all (duplicate word "all")
.    english (the correct spelling is "English").
.   an toggle it via JS function (it should be "and", not "an").
.    german (the correct spelling is "German")

**Comment by larshp** [comment]
closing, https://github.com/abapGit/abapGit/pull/6786#issuecomment-1920494156
