### ISSUE TITLE
Bug in Status Bar Message When There's only 1 Thread.

### ISSUE THREAD

**Issue by francisco-milan** [abapGit/abapGit#6782]
Hi abapGit Team,

I wanted to bring to your attention a minor issue I've noticed in the abapGit application. The Status Bar consistently reports the number of threads in plural, even when there is only one thread. For instance, the message displayed is:
"Serialize <object_name>, 1 threads", (see the image below).

![image](https://github.com/abapGit/abapGit/assets/36721657/58e24a81-35dc-4237-89b1-b4fc93bbff44)

While this doesn't impact functionality, I believe it would improve the user experience if the Status Bar accurately reflects the singular or plural nature of the thread count.

To fix this issue I have submitted pull request #6783. Please let me know if this aligns with your expectations.

Thanks a lot for your time and consideration.

Best regards,

Francisco Milan.

**Comment by mbtools** [comment]
thanks Francisco. Are you on slack? https://communityinviter.com/apps/abapgit/abap

**Comment by francisco-milan** [comment]
> thanks Francisco. Are you on slack? https://communityinviter.com/apps/abapgit/abap

Thanks Marc, I just joined today. I'll see you there!
