### ISSUE TITLE
ZCL_ABAPGIT_REPO_REQUIREMENTS: Failing unit tests

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#6788]
I get these failing unit test on NW 752 SP04 dev edition
![grafik](https://github.com/abapGit/abapGit/assets/17437789/9773c062-587c-4e42-bae4-eafc38f69417)

#5223

**Comment by mbtools** [comment]
looks like there's some diff in the SAP data elements. can you post a screenshot of SE11 > CVERS?

**Comment by christianguenter2** [comment]
![grafik](https://github.com/abapGit/abapGit/assets/17437789/98b8aa26-caf2-4fd8-ba68-801da90dc9a3)
![grafik](https://github.com/abapGit/abapGit/assets/17437789/59b7d4bb-f56b-4e2a-824f-50ecd112beae)

**Comment by mbtools** [comment]
hmmm. that's the same. Last month I changed the tests to be independent of cvers selection:

https://github.com/abapGit/abapGit/pull/6739/files#diff-4b43d20b6ef49f3aec12d8d4753100ab5863d1aec89b105e859c6b80df9ea1d4

Do you have latest?

**Comment by christianguenter2** [comment]
754 is hard coded but CVERS is read from DB with 752?

**Comment by mbtools** [comment]
there's no more select from db.

**Comment by christianguenter2** [comment]
In production code?
https://github.com/abapGit/abapGit/blob/0514b2df6267716136066bb5f87f3d166cf7ac1f/src/repo/utils/zcl_abapgit_repo_requirements.clas.abap#L69-L72
![grafik](https://github.com/abapGit/abapGit/assets/17437789/e403e6e8-b3c2-4ccb-b4f0-0c616e8649c5)

![grafik](https://github.com/abapGit/abapGit/assets/17437789/f1f189a9-9c11-4ca7-9107-c8a1c8523839)

**Comment by mbtools** [comment]
ah, ok. i see = bug

**Comment by christianguenter2** [comment]
Some dependency injection and mocking needed I guess.
