### ISSUE TITLE
'Advanced > Open in main language': Wrong status message 

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#6789]
This status message appears after 'Advanced > Open in main language' (and most likely other actions) if the repo has a version constant.
Side effect from #6733
![grafik](https://github.com/abapGit/abapGit/assets/17437789/56cb4b7b-44e5-4b6f-89c7-16d6a3bd0bc5)
Instead of 'Repository opened in a new window' from here
https://github.com/abapGit/abapGit/blob/9a33f2180c603c5e17bdf3a86351fcd58aa14a80/src/objects/jump/zcl_abapgit_gui_jumper.clas.abap#L277

Message is issued here
![grafik](https://github.com/abapGit/abapGit/assets/17437789/8c265249-05ab-47e2-a4c6-b2226a8d46d7)

SEO_INTERFACE_CHECK_POOL / SEO_CLASS_CHECK_CLASSPOOL are both affected.

**Comment by mbtools** [comment]
"great" sap code 🦆
