### ISSUE TITLE
Code is cut from XSLT/ST objects when pulling

### ISSUE THREAD

**Issue by jonsnou** [abapGit/abapGit#6792]
- A handful of XSLT/ST objects are in my repo among others (also classes that use those objects, and more stuff)
- What I have recently been experiencing is pulling issues with (only) those XSLT/ST objects - in both on-premise and cloud. The pulling issue is like this: In all the XSLT/ST objects, the code is cut at precisely the 245th character (including spaces) in the files. 
- I tried many things, renamed the objects, created XSLT/ST objects again from scratch, tried to export and import again, and so on, same result with the code cutting.  When I manually add the "remaining" code that was cut to the imported objects and activate, the objects are fine, no errors shown, and the classes that use them work as expected.
- Consequently, due to the tags missing/code cut, the issue "Transformation XXXXX Line 2: XML parsing error (3007) in XXXXX, line 2, column 1: unexpected symbol; expected '<', '</', entity reference, character data, CDATA section, processing instruction or comment" is displayed.
- Any ideas on preventing this issue, or any ideas why this may happen with XSLT/ST objects? 

And btw: Kudos to the contributors to this awesome repo!!!

**Comment by mbtools** [comment]
Looks like an SAP bug to me. Can you create a small test case and push it to https://github.com/abapGit-tests/XSLT_wide, please?

**Comment by mbtools** [comment]
push the z-xslt to the repo I mentioned so we can reproduce it

**Comment by larshp** [comment]
@jonsnou any chance you are on a non-Unicode system? I didn't test this scenario, but wondering

**Comment by jonsnou** [comment]
@larshp: SCP_GET_CODEPAGE_KIND returns a value with U. 
@mbtools: I created a pull request.

**Comment by mbtools** [comment]
thanks for the PR. i was able to reproduce the issue. Your xslt source is using LF only but ABAP requires CRLF. This can happen if you edit it outside of SAP tools. 

I added a check in #6803 so that you get a proper error message in this case.

**Comment by jonsnou** [comment]
@mbtools: Thanks for the support. 
Before closing the issue, a question on "using LF only but ABAP requires CRLF": So the sample files include \n instead of \r\n which is required, right? How can I avoid this issue and continue to work with abapGit files locally in VS Code, for example? I only encountered this issue with XSLT objects, not with other objects. After some stack research, I assume it's a (Windows) setting that needs to be made and forces git pushes to use LF instead of CRLF, right? Any tips (although I assume that the solutions in stack do not mess anything up)?

**Comment by mbtools** [comment]
We know from experience that VS code can be used but that's limited to the common objects like CLAS, INTF, PROG, etc. Editing other types is unknown territory and requires feedback like yours 👏 

The best for external tools is to follow the rules setup in [`.editorconfig`](https://editorconfig.org/). VS Code is doing that... but the rule for XML files was "LF only" 😉 . I added a specific rule for XSLT source files in #6803 which should help avoid this issue going forward.

**Comment by mbtools** [comment]
VisualStudio respects editorconfig out-of-the-box. For VS Code you need https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
