### ISSUE TITLE
zabapgit_standalone: Window after choosing PULL missing buttons

### ISSUE THREAD

**Issue by jonsnou** [abapGit/abapGit#6797]
When running zabapgit_standalone, creating a new online repo, and choosing Pull, a window is displayed in which objects can be selected. What can be the reason for the following: Using the latest report, the Continue and Cancel buttons are not displayed. Any idea? Is there a way to proceed even without having the buttons?
![image](https://github.com/abapGit/abapGit/assets/47634819/5828712d-c1cf-4188-a658-818c99dff395)

**Comment by christianguenter2** [comment]
Can you check whether this gui status exists? It should be auto created upon startup.
![grafik](https://github.com/abapGit/abapGit/assets/17437789/9fbbe50d-daa9-40e6-b3b4-f36330ea642e)

**Comment by jonsnou** [comment]
I checked in my current version of the report (which uses the latest abapgit report). The said GUI status is in, still the buttons are not shown (only the sorting icons), cannot proceed. Removed the report, created one anew, pasted the (latest) code, ran it: no buttons shown, but I see that the GUI status is not created. However, I found another report in the system from Jan 2023. Using this one shows the buttons.

**Comment by mbtools** [comment]
The GUI status should be created in `zcl_abapgit_persist_migrate=>gui_create_status`. Put a break-point there in the standalone report and check why it's not working. 

https://github.com/abapGit/abapGit/blob/main/src/persist/zcl_abapgit_persist_migrate.clas.abap

**Comment by jonsnou** [comment]
@christianguenter2 , @mbtools : Any idea for a workaround here? No matter what, the buttons do not appear. As far as I can see, there's nothing fishy about the method mentioned. ls_new_cua and so on are all filled appropriately, the GUI status exists. Due to the missing buttons, the program cannot proceed. Even cancelling is not possible.

**Comment by christianguenter2** [comment]
> Hm, can you show us a screenshot from the active CUA status?

**Comment by christianguenter2** [comment]
Hm, can you show us a screenshot from the active CUA status?

What I don't get, on your first screenshot the buttons are there, why?

**Comment by mbtools** [comment]
From the Repo List, go to Utilities > Debug Info. Please, download the output and attach it here (as zip)

**Comment by lucasborin** [comment]
Same issue here.

@mbtools: `Try deleting GUI status in SE80. It should be recreated when you start the standalone program again` did not solve the issue.

@jonsnou: Are you from SAP too?

**Comment by christianguenter2** [comment]
@lucasborin how does the gui status look like? Was it created properly? Do you have any screenshots for us?

**Comment by lucasborin** [comment]
Right after click on "pull":
![image](https://github.com/abapGit/abapGit/assets/5233413/d67a0d09-b23a-4ab1-aaa9-dc3514af9175)

zabapgit_standalone three:
![image](https://github.com/abapGit/abapGit/assets/5233413/5b8fc3ef-c665-4d80-aee4-60bca095cfd8)

zabapgit three:
![image](https://github.com/abapGit/abapGit/assets/5233413/4248a95d-65ac-4b0b-98be-df33a09f0b3a)

I deleted the GUI STATUS and it did not create it again.

**Comment by christianguenter2** [comment]
Regarding `Try deleting GUI status in SE80. It should be recreated when you start the standalone program again`, can you check whether the GUI status appears under `inactive objects`? 
![grafik](https://github.com/abapGit/abapGit/assets/17437789/2507c2f6-459b-46b7-9799-0789e384a8a3)

Seems that one must activate the deletion somehow. At least that's the case for me. If not `RS_CUA_INTERNAL_FETCH` and `RS_CUA_STATUS_CHECK` still can read GUI status.

**Comment by lucasborin** [comment]
We detected the issue was internal, and the responsible team fixed it.
From my side, we can close this issue.
