### ISSUE TITLE
Pipeline failing

### ISSUE THREAD

**Issue by PabloMalerbaRedwood** [abapGit/abapGit#6802]
Hello! How are you? Hope you're doing great.

I need your help with an issue I'm having. I'm doing some ABAP changes and when I commit them, the resulting pipeline always returns errors. Thing is, these errors are not related to the object I've updated/changed/created, they are the same every time.

I'm sending the pipeline's log. The object I updated is/JCS/BC_RFC_READ_TABLE.

[Pipeline log.txt](https://github.com/abapGit/abapGit/files/14195435/Pipeline.log.txt)

Could you please give me a hand with this?

Also, let me know if you require more information from my side.

Thank you and have a great day! :)

Best regards

**Comment by mbtools** [comment]
@larshp can you transfer this to https://github.com/abaplint/abaplint, pls (I don't have permission)?

**Comment by larshp** [comment]
looks like its not possible to transfer across organizations 😒

**Comment by PabloMalerbaRedwood** [comment]
I was just about to ask how to do the transfer haha, maybe creating a new ticket? 😕
