### ISSUE TITLE
Form action "Submit Query" in Command Palette

### ISSUE THREAD

**Issue by francisco-milan** [abapGit/abapGit#6807]
Hi abapGit Team,

  Today I was checking the Command Palette on the "Repository List" page and I noticed something interesting. It seems like the "Submit Query" action doesn't quite fit in there since it's more of a form thing.

![image](https://github.com/abapGit/abapGit/assets/36721657/70f5fc72-2c4e-4242-9d7e-b3b343777dce)

I've got a simple fix in mind. We could just modify this line a little bit:

https://github.com/abapGit/abapGit/blob/ddd6bdb3326f0196193fb3d09d481369323d4267/src/ui/zabapgit_js_common.w3mi.data.js#L2376

**Proposed change:**
```
[].slice.call(document.querySelectorAll("input[type='submit'][value]:not([value='Submit Query'])"))
```

This would filter out the "Submit Query" action from the Command Palette, keeping things tidy and focused on what it's meant for.

![image](https://github.com/abapGit/abapGit/assets/36721657/05f396ae-440a-4841-bad4-f1082ce39887)

What do you think? If it sounds good, I can create a new PR to apply this change.

Best regards,

Francisco Milan.

**Comment by francisco-milan** [comment]
PR #6808

**Comment by francisco-milan** [comment]
Hi Marc,

After exploring your suggestion and further investigating the code, I found an alternative solution that I believe effectively addresses the problem.

Instead of directly setting the "title" attribute with a single expression like here: 

https://github.com/abapGit/abapGit/blob/fa66b626de7c578428bd07519be2d0d1bed356e3/src/ui/zabapgit_js_common.w3mi.data.js#L2386

we can implement a dynamic function to handle the title generation based on the value of the input. Here's the proposed code snippet:

```
title: function() {
  if (input.value === "Submit Query") {
    return "Filter";
  } else {
    return input.value + " " + input.title.replace(/\[.*\]/, "");
  }
}()
```

This approach dynamically determines the title based on the input value, displaying "Filter" if the value is "Submit Query" and using the original expression to get the title otherwise.

I would greatly appreciate your thoughts and feedback on this solution.

Best regards,

Francisco Milan.

**Comment by mbtools** [comment]
Let's not code UI elements ("Filter") in JS.

abap:

```abap
ri_html->add( |<input type="submit" class="hidden-submit" title="Filter">| ).
```

js:

```js
title: (input.value === "Submit Query" ? input.title : input.value + " " + input.title.replace(/\[.*\]/, ""))
```

**Comment by francisco-milan** [comment]
#6810
