### ISSUE TITLE
Purpose of sub package check

### ISSUE THREAD

**Issue by WegnerDan** [abapGit/abapGit#6809]
This is not a bug report, I just want to understand something.

I've used abapgit to export everything in a Z-Package that has many subpackages, some of which are associated with abapgit repos. 

When trying to do an export to a zip file, the following check (251 to 260) prohibits it:

https://github.com/abapGit/abapGit/blob/fa66b626de7c578428bd07519be2d0d1bed356e3/src/repo/zcl_abapgit_repo_srv.clas.abap#L251

I've commented these lines out, to continue and later put them back in.

I think it would make more sense to issue a warning or something, because if you just want to export stuff, subpackages which are associated with repos are not a problem. 

Is there something I'm missing here?

**Comment by mbtools** [comment]
You are right when it comes to "just exporting something" but a) the sub-package logic is used in other places, and b) abapGit matches exports to what's in a repo. 

Sounds like you're trying to backup a part of your system. That is not the purpose of abapGit. 

I suggest looking into the APIs and exporting the repos which you already have in the sub-packages automatically. The it becomes a repeatable process as well.

**Comment by larshp** [comment]
The "export to zip" was added after the "offline repository" feature, so I guess it uses some of the same code.

I'd see it as a bug, the "export to zip" should just export whatever asked for. While creating repositories keeps the check

**Comment by mbtools** [comment]
@danielwegner can you please test #6815?

**Comment by WegnerDan** [comment]
> @danielwegner can you please test #6815?

Well, it works, but it's not exactly what I wanted.
The "Package to zip" feature does exactly what I want and I wasn't aware of it. Thanks!

Sorry for taking so long to respond.
