### ISSUE TITLE
Question: Why does the checksum update after a commit need to serialize all objects

### ISSUE THREAD

**Issue by mkaesemann** [abapGit/abapGit#6823]
Hi,
as mentioned in the past we use abapGit for a huge repo, where performance is always an issue.
At the moment we use the "Stage By Transport" feature to optimize performance, because usually 90% or more of our objects are unchaged when a developer makes changes, but found that performance gain is much smaller than expected.
I looked into this a bit more and discovered that abapGit serializes the full scope quite often where it it completely unnecessary e.g. showing the diff of a single file/object or after a commit when updating the checksums of the changes objects.
Since this makes every single action take multiple minutes (even with parallel serialization in 40+ work processes), I was wondering what the reasoning behind this behavior is.
Why not limit the scope for diffs to just a single file (if it is requested for just that file) or update only the checksum of files that have actually changed?
Any information would be appreciated. Thanks.

**Comment by mbtools** [comment]
It's a known issue. See also https://github.com/abapGit/abapGit/issues/5137. 

The way things are, it's just easy to call "refresh" in the code when you want the most recent data. Feel free to suggest a PR to improve certain situations (or take on #5137) 😃

**Comment by mkaesemann** [comment]
Short follow-up questions, since I don't think I will be able to tackle #5137 at this time, but I have found three additional improvements that can be added short-term and seem to work in our scenarios at the moment.
1. Is it okay to create a PR as a basis for discussion or should I create an issue for discussion first? The contribution guidelines are not 100% clear to me in this regard.
2. Is there a reason why the filter used in the stage-by-transport action always adds all development packages (DEVC) in the repo independent of whether they are in the transport/task or not? I don't see a need for that and would like to skip the serialization of the 260+ packages that we have if they are not touched (not a huge gain, but every bit helps)

**Comment by mkaesemann** [comment]
Perfect. That answers my questions. 👍
