### ISSUE TITLE
Dump: cl_http_client=>create_by_url because of non-existent exceptions

### ISSUE THREAD

**Issue by mraht** [abapGit/abapGit#6825]
With commit 0d35e9377e044888bcbde78d2c435adcb3dea0e3 new exceptions are being handled which aren't existent in my systems version (7.52, SP4):
```
cl_http_client=>create_by_url(
[...]
pse_not_found      = 4
pse_not_distrib    = 5
pse_errors         = 6
[...]
```
[zcl_abapgit_http](https://github.com/abapGit/abapGit/commit/0d35e9377e044888bcbde78d2c435adcb3dea0e3#diff-3c913d9e6eeccf888d97fce6f21402b4d694980694170cfad162075b88defb7e)

This leads therefor to a dump of abapGit.

**Comment by larshp** [comment]
@mraht thanks, do you want to provide a PR?
