### ISSUE TITLE
Issue Browser

### ISSUE THREAD

**Issue by mraht** [abapGit/abapGit#6828]
I'd like to see a git issue browser in abapGit from which it would it be also  possible to jump to the related source code file directly via adt links.

Currently one has to open the issues webpage, copy the name of the source code object and open it manually in ADT.

To generate issues automatically on push to github I use https://github.com/alstr/todo-to-issue-action

**Comment by larshp** [comment]
issues is not a git feature as such, its a part of typical git hosts, which abapGit has code for in https://github.com/abapGit/abapGit/tree/main/src/git_platform

press "." to open the editor from the code, https://github.com/github/dev

**Comment by larshp** [comment]
taking https://github.com/mraht-ewm-standard/EXC_MGMT/issues/2 as an example, I'd recommend doing a Continuous Integration setup instead

**Comment by mraht** [comment]
> taking [mraht-ewm-standard/EXC_MGMT#2](https://github.com/mraht-ewm-standard/EXC_MGMT/issues/2) as an example, I'd recommend doing a Continuous Integration setup instead

By that you mean the automatic deletion of variable not used yet via CI workflow before the pushing of changes to git, right? Do you have links regarding the topic? I'm not very familiar with CI yet. Found this though on GitHub which has an autoformat option: https://github.com/andau/abapCI

**Comment by larshp** [comment]
like https://github.com/heliconialabs/abap-opentelemetry/pull/28, I added a unused variable using the web based editor, the PR cannot be merged because it has a unused variable

this will keep the main branch green, which means there are no outstanding issues in the codebase developers add their changes to(in feature branches)

**Comment by mraht** [comment]
Ok, thanks!
