### ISSUE TITLE
How to enable `*.properties` files

### ISSUE THREAD

**Issue by albertmink** [abapGit/abapGit#6834]
During the work on #6830 I tried to test the deserialization. In the system I can see that the DBs are correct. So I assume that the deserialization worked. However, I have issues in abapGit when working with `*.properties` files in general.

1. abapGit tells me after successfully deserialization, that there is a diff (probably AG does not serialize the DBs content, or skips *.properties files):
<img width="1310" alt="Screenshot 2024-03-06 at 14 23 52" src="https://github.com/abapGit/abapGit/assets/38354196/324d16b9-f9e2-4fe7-8e55-3bfe0492b2d4">
2. Trying to push translation changes to git repository leads to:
<img width="1298" alt="Screenshot 2024-03-06 at 14 22 18" src="https://github.com/abapGit/abapGit/assets/38354196/a0b41926-8acb-4339-910f-90f5a04c8c4d">

**Comment by albertmink** [comment]
Diff shows the remote content, all in green.

**Comment by mbtools** [comment]
Filenames in abapGit follow a specific pattern: see https://docs.abapgit.org/development-guide/serializers/file-formats.html#clas for example 

Object_name.object_type.extension
Or 
Object_name.object_type.extra.extension

There can't be more than four parts with the current logic. 

I'm not sure if the map methods in the serializer class could be used here. 

Need to think about this

**Comment by albertmink** [comment]
Well, maybe its alright with the file name and file type. As I just learned, the target language in the PR is never set, so serializing the object did not add any translation file.

However, setting a target language in the debugger rendered this one, which is exactly what I expected.

**Diff page**
<img width="1332" alt="Screenshot 2024-03-08 at 09 18 40" src="https://github.com/abapGit/abapGit/assets/38354196/445bffe3-6676-4284-b5ad-5ed161cc6300">

**Staging page**
<img width="1307" alt="Screenshot 2024-03-08 at 09 20 59" src="https://github.com/abapGit/abapGit/assets/38354196/75608750-0221-486b-957a-7c9fd3ed14d1">


Not sure whether this was exactly the issue. So I tend to let the issue open and work on the target language during serialization.

**Comment by albertmink** [comment]
closing this one.

Setting a target language solved the issue. Previously, the serialization just didn't knew about a target language at all. So nothing was serialized.
<img width="1329" alt="Screenshot 2024-03-11 at 09 03 35" src="https://github.com/abapGit/abapGit/assets/38354196/7045e731-8ebe-449c-824e-ba9c2c6a0a09">
