### ISSUE TITLE
ZCL_ABAPLINT_DEPS_SERIALIZER error The reference to a test class (identification with FOR TESTING) is onl y possible in test classes.

### ISSUE THREAD

**Issue by ed-holland** [abapGit/abapGit#6835]
After installing the change 15443a6aaaa89bff8234261c9b72cb10afb5925e (latest) when running zabaplint_dependencies
The following error is raised:
![image](https://github.com/abapGit/abapGit/assets/53995991/9635908b-21cf-4f87-a55d-8ac1d3a64bdf)

**Comment by ed-holland** [comment]
abapGit version: 1.127.0 
XML version:  v1.0.0 
GUI version:  8000.01.01 
APACK version:  1 
LCL_TIME:  1709742310 +0000 
SY time:  20240306 172510 3600 
SY release:  740 SP 0029

**Comment by mbtools** [comment]
This was fixed by https://github.com/abaplint/abaplint-sci-client/pull/292/files

**Comment by larshp** [comment]
the fix is in repository https://github.com/abaplint/abaplint-sci-client pull the latest

**Comment by ed-holland** [comment]
Thx Lars. Fix confirmed
