### ISSUE TITLE
zabaplint_dependencies: Function table parameter references are not selected for dependency repository

### ISSUE THREAD

**Issue by ed-holland** [abapGit/abapGit#6836]
Version: 
abapGit version: 1.127.0 
XML version:  v1.0.0 
GUI version:  8000.01.01 
APACK version:  1 
LCL_TIME:  1709742310 +0000 
SY time:  20240306 172510 3600 
SY release:  740 SP 0029 

The Tables used in function parameters are not added to the dependency list.
![image](https://github.com/abapGit/abapGit/assets/53995991/f9d45efa-9864-49c4-aa72-d7fecd823778)

This then causes Linter errors like this
`./src/ecc/#jcs#fi.fugr.#jcs#fi_ff67_preparation.abap[121, 3]                  - "t012" not found, Target (check_syntax) [E]`

**Comment by larshp** [comment]
Close and open in the abaplint sci repositoey? Not related to code in abapGit?

**Comment by ed-holland** [comment]
Done
https://github.com/abaplint/abaplint/issues/3261
