### ISSUE TITLE
APACK Method COPY_MANIFEST_DESCRIPTOR in class CL_ABAPGIT_APACK_READER does not handle namespaces

### ISSUE THREAD

**Issue by einareiriksson** [abapGit/abapGit#6837]
APACK Method COPY_MANIFEST_DESCRIPTOR in class CL_ABAPGIT_APACK_READER does not handle namespaces.

Suggestion is to extract the namespace from the class name of the instance io_manifest_provider that is provided as a parameter to the method and use that to build the correct representation of the descriptor.

**Comment by mbtools** [comment]
Closed by #6841
