### ISSUE TITLE
Grouping of page classes

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6838]
I'm planning to do some improvements to code inspector pages. For conveniense it would be nice to combine them in one subpackage:

```
UI_PAGES_CODI
  page_codi_base
  page_code_insp
  page_syntax (rename to code_syntax ??? or codi_syntax )
  page_runit (not based on codi_base but very relevant functionally)
```

Any concerns ? @larshp @mbtools 

Also probably makes sense to group db pages, settings, maybe add pages ?? The grouping of rest is less obvious - they'd stay in the root.

**Comment by mbtools** [comment]
Sounds good. Go for it

**Comment by larshp** [comment]
👍
