### ISSUE TITLE
change_transport_type in zcl_abapgit_cts_api not working as expected, gives an error that the task type can not be changed.

### ISSUE THREAD

**Issue by einareiriksson** [abapGit/abapGit#6843]
Method change_transport_type in class zcl_abapgit_cts_api is not working as expected.  First ls_request_header is used in function call to 'TRINT_READ_REQUEST_HEADER' without  have been given a value, should be assigned the transport request number from iv_transport_request.

Secondly I believe the 'TRINT_CHANGE_TRFUNCTION' works on the task so reading the transport request with task (using function TR_READ_REQUEST_WITH_TASKS) is probably needed and then all subtasks changed?

**Comment by mbtools** [comment]
I created a fix https://github.com/abapGit/abapGit/pull/6870. Please test again. Thanks!

PS: This fux also adds a new option: 

If you set the original system to "SID", then `tadir-srcsystem` in the target system will be forced to `sy-sysid`. 
When pulling projects with namespaces that include a repair license, abapGit usually sets `srcsystem` to "SAP" (i.e. a repair request). This prevents you from editing the objects. The "SID" setting would change the namespaced objects to local (i.e. development request), which is very handy for open-source projects.
