### ISSUE TITLE
abapGit on ABAP development Toolkit

### ISSUE THREAD

**Issue by MilanNTT** [abapGit/abapGit#6845]
Hi,

after the SSL certificate change I could not reach the GitHub Repositories due to this error:

HTTP error 421 occured: SSL handshake with github.com:443 failed: SSSLERR_PEER_CERT_UNTRUSTED (-102)
Peer's X.509 certificate (chain) validation failed (missing...

I have tryied to install the new certificates to my computer key stores, but the error is still there... Any clue how to fix it?
Again, I'm not using the abapGit on ABAP App Server, but from eclipse installed on my notebook...

BR,

Milan

**Comment by larshp** [comment]
GitHub changed the certificate last week, update it to

![image](https://github.com/abapGit/abapGit/assets/5888506/aabaec30-aff6-4f60-81b8-f2abb55a37ec)

**Comment by MilanNTT** [comment]
Hi Lars,

sorry for the stupid question, but this is most probably my issue: how should I update to it?
I just make sure I have installed these new certificates to my user and computer certificates, but still the issue...

BR,

Milan

**Comment by MilanNTT** [comment]
Hi Lars,

I might understand it now:
I'm working in a project for S/4Hana Cloud System, so this means I need to update this new certificate in the trust of this Cloud System... Have done that and it worked...
Appreciate your help.

BR,

Milan

**Comment by MilanNTT** [comment]
trying to close it, answer from Lars helped, just for S/4Hana Cloud system use Fiori App: Maintain Certificate Trust List where the certificate needs to be imported....

**Comment by larshp** [comment]
@MilanNTT yea, perhaps you can help adding the Fiori app reference in the document https://github.com/abapGit/docs.abapgit.org/edit/main/src/user-guide/setup/ssl-setup.md ?
