### ISSUE TITLE
UIPG, UIST: Support Launchpad Page and Space Templates

### ISSUE THREAD

**Issue by ViktoriaFreidel** [abapGit/abapGit#6850]
We implemented ADT support of Space/Page Templates. Object Types UIPG, UIST are added to https://github.com/SAP/abap-file-formats.
Now we want to enable object types with abapGit.

**Comment by larshp** [comment]
@ViktoriaFreidel thanks, is this something you would like to open a pull request for?

we cannot see the internal SAP jira

**Comment by albertmink** [comment]
AFAIK both are [AFF](https://github.com/SAP/abap-file-formats) types
So you can register new object type here https://github.com/abapGit/abapGit/blob/687c91bcf57761edbaf30c9bcd1118ea396bc3bb/src/objects/aff/zcl_abapgit_aff_registry.clas.abap#L49
and implement the object handler inheriting from [zcl_abapgit_object_common_aff](https://github.com/abapGit/abapGit/blob/687c91bcf57761edbaf30c9bcd1118ea396bc3bb/src/objects/aff/zcl_abapgit_object_common_aff.clas.abap#L15C7-L15C36)
