### ISSUE TITLE
TABL-DDL: case/when not working properly

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#6855]
Some of the constants have the same values. Therefore the case block doesn't work correctly:

https://github.com/abapGit/abapGit/blob/463f112c85001b964c8cb40162bd066f48affc16/src/objects/tabl/zcl_abapgit_object_tabl_ddl.clas.abap#L157-L164

@larshp

**Comment by larshp** [comment]
oh, yea, I was working on that too

the code is not active, so its not critical as such
