### ISSUE TITLE
Callbacks for installation / update / removal

### ISSUE THREAD

**Issue by flaiker** [abapGit/abapGit#686]
I think it would be a nice feature to have some hooks for abapGit "events" that can be subscribed to by a project.
For example a library that can be installed using abapGit contains customizing tables. Afaik you cannot check in table contents to abapGit (?) so for the default values you would probably write a report that inserts those values into the db table that has to be executed manually. If there was an installation event this could be triggered automatically after activation. Same for updating a repository (data migration) or removal (cleanup db / generated source code / file system / ...).

I was thinking of something like this (global interface might be a bit too tricky though):
```abap
INTERFACE zif_abapgit_repo_event_listener PUBLIC.
  METHODS:
    on_installation IMPORTING iv_package TYPE devclass,
    on_update IMPORTING iv_old_tag TYPE string OPTIONAL
                        iv_new_tag TYPE string OPTIONAL
                        iv_old_sha1 TYPE string
                        iv_new_sha1 TYPE string,
    on_removal.
ENDINTERFACE.
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
 <asx:values>
  <DATA>
   (...)
   <CALLBACK_CLASS>ZCL_MY_LISTENER</CALLBACK_CLASS>
  </DATA>
 </asx:values>
</asx:abap>
```

**Comment by larshp** [comment]
yeah

a global interface would be difficult, but a PERFORM IN PROGRAM would be easy

the callbacks could go into the .abapgit.xml file

**Comment by EduardoCopat** [comment]
abapGit is very easy to install because it is a very fat big Z program. However, this makes hard to call its APIs or even create these hooks you mentioned.

You can do stuff in `perform in program`, but, let's be honest, it's not the same thing as calling the classes as `lo_foo->bar( )`.

How can we expose abapGit APIs? Is it possible at all?

**Comment by jfilak** [comment]
How about to turn the abapGit program into an installer which creates an own package, tables, classes and so on?

**Comment by larshp** [comment]
abapGit APIs/Installer: from my point of view this is not related to the feature suggested by @flaiker, it is just calling a piece of code when eg. a repo is installed. We can move this new topic to a separate issue 😄

**Comment by flaiker** [comment]
For me the direction would be abapGit -> repo, so for that `PERFORM IN PROGRAM ... IF FOUND` or `(lv_callback_cls_name)=>(lv_callback_method)` would be enough. With the current (local) approach abapGit has I doubt it is feasible to define an interface in a static way.

If you don't mind I'll have a look if I can get something working.

The other way around is also an interesting topic and already somewhat needed for some of the feature issues (especially #636 in my opinion), but unrelated to this issue.

**Comment by flaiker** [comment]
Doing some work on this over here: https://github.com/flaiker/abapGit/tree/callbacks

**Comment by larshp** [comment]
I'm closing this, dont think this is possible to make this safe
