### ISSUE TITLE
Finding dependencies with abapGit

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6868]
Would be nice if AG could:

1) run `where used` over all objects in the repo and show references outside of the package. Why: deploying new versions of own products are sometimes tricky when the product code is used as a library in some other enhancements/forms/etc. And installing other tools is not always allowed. It would be great to have such a feature integrated into AG. It should be quite easy to implement

2) see cross dependencies among the current repo packages. Essentially to integrate https://github.com/sbcgua/crossdeps into AG. This is less critical as such a tool is mainly used in a development system where we have complete control and can install what we want. However, in terms of code quality this tool shows how coupled the code is, so might be a worthy part of abapGit as a toolkit.

**Comment by larshp** [comment]
Its partly a solution? Having discovered the references and looked through them there might be syntax errors if not looking carefully, I'd recommend shifting the discovery and syntax check to before attempting to install anything. But, yea, its not always possible to control the customer development process

**Comment by sbcgua** [comment]
prototype (for where used): https://github.com/sbcgua/crossdeps/tree/where-used

maybe will concentrate on this one. The second one is a bit further from AG ... it a good dev tool but interpretting the results is more ambiguous/

**Comment by mbtools** [comment]
Merged. Thanks, @sbcgua 👍
