### ISSUE TITLE
SUSP: Support for Authorization Profile Templates

### ISSUE THREAD

**Issue by norbert-cw** [abapGit/abapGit#6876]
![image](https://github.com/abapGit/abapGit/assets/120448275/1c689d38-810f-4e3c-a742-4cf3f76baec6)
Is it planned to add support for SUSP type? 
R3TR	SUSP	Templates for authorization profiles (Profile Generator)

**Comment by mbtools** [comment]
No (https://github.com/abapGit/abapGit/issues/5912), but we're always open for pull requests 😃

**Comment by mbtools** [comment]
Hi Norbert,

there are no plans to support this object type. I have added your request to #5912. 

Feel free to create a pull request or reopen this issue for further discussion.

You find the implementation details [here](https://docs.abapgit.org/development-guide/serializers/overview.html).

Best,
Marc
