### ISSUE TITLE
CDBO: Customer Data Browser Object

### ISSUE THREAD

**Issue by sivapriya-nagendran** [abapGit/abapGit#6879]
Support for object type CDBO

**Comment by mbtools** [comment]
Hi @sivapriya-nagendran 

there are no plans to support this object type. I have added your request to #5912. 

Feel free to create a pull request or reopen this issue for further discussion.

You find the implementation details [here](https://docs.abapgit.org/development-guide/serializers/overview.html).

Best,
Marc

**Comment by sivapriya-nagendran** [comment]
Hello Marc,
I am facing an issue committing the handler class ZCL_ABAPGIT_OBJECT_CDBO (AFF handler) into my forked repository https://github.com/sivapriya-nagendran/abapGit.git in branch CDBO using ZABAPGIT_STANDALONE report. Issue attached.
<img width="1164" alt="image" src="https://github.com/abapGit/abapGit/assets/122891311/d1ed105a-b958-43fa-9d5c-a031e9be3dfa">
