### ISSUE TITLE
Performance Issue REMOVE_VERTEX 

### ISSUE THREAD

**Issue by mabek** [abapGit/abapGit#6880]
Hi,

I am currently working with a very large repository of which I want to extract specific objects.
During Pulling the performance is too slow to handle the repository. 
One specific position is REMOVE_VERTEX. 
Please find trace attached. I think an improvement or parallelization might be possible and be very appreciated. 
Version I am running is the latest 1.127.
Thank you and Regards, Marius 
![abapgit](https://github.com/abapGit/abapGit/assets/7482652/1575440d-bbac-4ae3-bc09-d2b8e4ac4d24)

**Comment by larshp** [comment]
try adding a secondary key? https://github.com/abapGit/abapGit/blob/main/src/objects/core/zcl_abapgit_item_graph.clas.abap

**Comment by mabek** [comment]
Replacing`DELETE mt_edges WHERE
      from-obj_type = ls_vertex-obj_type AND
      from-obj_name = ls_vertex-obj_name.`

with this
`DELETE mt_edges USING KEY sec_key WHERE
      from-obj_type = ls_vertex-obj_type AND
      from-obj_name = ls_vertex-obj_name.`

brings around 30% performance improvement. Runtime is still not usable. mt_edges has around 500k entries in my case.

**Comment by larshp** [comment]
500k edges, how many object/items is there in the repository? 500k seems like a bug when building the data

**Comment by mabek** [comment]
> 500k edges, how many object/items is there in the repository? 500k seems like a bug when building the data

Yes that might be. the repository has around 36.000 objects

**Comment by larshp** [comment]
try setting a breakpoint at https://github.com/abapGit/abapGit/blob/9ad328b6819337d1f6db10eba63df769e0085541/src/objects/core/zcl_abapgit_file_deserialize.clas.abap#L251 to check when `lt_requires` has many rows

**Comment by mabek** [comment]
> try setting a breakpoint at
> 
> https://github.com/abapGit/abapGit/blob/9ad328b6819337d1f6db10eba63df769e0085541/src/objects/core/zcl_abapgit_file_deserialize.clas.abap#L251
> 
> to check when `lt_requires` has many rows

behaviour is as follows:
Every time a class is the current item lt requires are filtered by everythign but SPRX, INTF, XSLT
result is 1026 requires.
we have around 500 classes in the repository so 500 x 1026 = 500k entries.

**Comment by mabek** [comment]
> try adding a secondary key? https://github.com/abapGit/abapGit/blob/main/src/objects/core/zcl_abapgit_item_graph.clas.abap

somehow it works and performance improvement is x50 if its like this:
`   READ TABLE mt_edges WITH KEY sec_key COMPONENTS
        to-obj_type = ls_vertex-obj_type
        to-obj_name = ls_vertex-obj_name
         TRANSPORTING NO FIELDS.
   IF sy-subrc = 0.
      DELETE mt_edges USING KEY sec_key WHERE
              to-obj_type = ls_vertex-obj_type AND
              to-obj_name = ls_vertex-obj_name.
   ENDIF.`

**Comment by larshp** [comment]
@mabek can you help testing https://github.com/abapGit/abapGit/pull/6885 ?

**Comment by larshp** [comment]
note that your example code did not pass the unit tests

anyhow, suggest merging the PR, and after that, can you help opening a new PR with more changes?

**Comment by mbtools** [comment]
I guess you have about 1000 interfaces, @mabek, right? 

Do classes really require interfaces in AG, @larshp? 

https://github.com/abapGit/abapGit/blob/9ad328b6819337d1f6db10eba63df769e0085541/src/objects/core/zcl_abapgit_file_deserialize.clas.abap#L197

**Comment by larshp** [comment]
I guess so, its something I'd like not to mess with

**Comment by mbtools** [comment]
@mabek the change is merged. let us know if performance is now ok.
