### ISSUE TITLE
Question about import in 7.00

### ISSUE THREAD

**Issue by B0yEditi0n** [abapGit/abapGit#6881]
Hello, i have a question about AbapGit.
in my company we work with a multiple customers. We create products to implement in clients, some have older versions, there is abap git and your implementation is only sap basis 702, is there some way to implement **only the import module** from sap git in sap basis 700?

if not could you provide me with some documentation about import offline and class creation that might help.

**Comment by B0yEditi0n** [comment]
I know, I read this topic, but my question is only about import, if necessary I would try to make it into a system basis 700

**Comment by larshp** [comment]
the problem is symmetrical, for import splitting the class into the different parts, for export gathering the different parts into class source code. Exporting is probably easier, as it doesnt have to parse the source code, just do concatenation

**Comment by pokrakam** [comment]
You could try importing the standalone version and downporting it manually. I had a quick go at importing it into a 7.01 system and it loads.

There are a few tricks you can try to speed things up, e.g. some/most (?) string templates can be converted by search/replacing `|` with `'`, `{` with `' &&` and `}` with `&& '`. Delete all serialisation code and objects you don't need to reduce the effort. The pure syntax part is definitely doable, no idea how many API issues may crop up (e.g. calling SAP functions/methods that don't exist).

**Comment by mbtools** [comment]
Is there a bounty?

**Comment by B0yEditi0n** [comment]
@pokrakam, Thank you by your sugest, but the system basis 700 no suport concatenate using &&, i need create variables for each exporting class and concatenate inscructions, there are 130000 lines of source code, I'm not sure if work, but i try

**Comment by B0yEditi0n** [comment]
@mbtools in my company i try found a efficient form from tranport of products, sync source code with one base is helpfull

**Comment by pokrakam** [comment]
@B0yEditi0n it was an idea off the top of my head, but I guess 700 is older than I thought :-( 
So string templates would have to be done programmatically. It may be possible to convert them into CONCATENATE with Regex but I'm not expert enough. 

You could also try using an older version to reduce the amount of code, but then the standalone version is not available - @larshp? 

Another option is SAPlink, it was built on 6.4 if memory serves me correct, definitely compatible with 700.
Install via abapGit here:
https://github.com/pokrakam/SAPlink-Git
Or manual install for older versions from here:
https://github.com/sapmentors/SAPlink

**Comment by B0yEditi0n** [comment]
@pokrakam, it is exactly i want, thank you for your contribution, i will study your project

**Comment by pokrakam** [comment]
It's not my project, I just repackaged an abapGit-compatible version :)
But by all means install the abapGit version on a newer system first to get familiar with it, then do the manual install from the sapmentors repo on your 7.00 system. You may not need all the plugins if it's only for programs and classes which will make the install a bit easier.
