### ISSUE TITLE
Proposal: Implement Maximum Length for "Package" Field

### ISSUE THREAD

**Issue by francisco-milan** [abapGit/abapGit#6888]
Dear abapGit Team,

Currently, there is no limit to the number of characters allowed in the "Package" field within abapGit. As you can see in the image below, when users enter more than 30 characters, the text is truncated, resulting in potential confusion, especially when viewing the package name in both Online and Offline modes.

![image](https://github.com/abapGit/abapGit/assets/36721657/bc1abbd9-e17d-4bc0-9913-7fe323f497c1)

To address this issue proactively and improve user experience, I suggest implementing a maximum length of 30 characters for the "Package" field. By enforcing this limit, users will be unable to enter more than 30 characters in the field, thereby preventing unintended truncation of package names and ensuring consistency across both modes.

Thank you for considering this proposal. I look forward to hearing your thoughts on this matter.

Best regards,

Francisco Milan.

**Comment by larshp** [comment]
👍 go for it
