### ISSUE TITLE
Relation of `ZIF_ABAPGIT_REPO_ONLINE` to `ZIF_ABAPGIT_REPO`

### ISSUE THREAD

**Issue by ConjuringCoffee** [abapGit/abapGit#6893]
Hello community, is there a reason why `ZIF_ABAPGIT_REPO_ONLINE` does not implement `ZIF_ABAPGIT_REPO`? 

I noticed this while working on some abapGit integration stuff. I wanted to replace my use of `ZCL_ABAPGIT_REPO_ONLINE` with an interface, but the methods I need are contained in the two interfaces `ZIF_ABAPGIT_REPO_ONLINE` and `ZIF_ABAPGIT_REPO`.

**Comment by mbtools** [comment]
Maybe because we need someone to implement it this way? 😉

**Comment by ConjuringCoffee** [comment]
Great, if there's no architectural reason against it, then I'll submit a pull request. :)
