### ISSUE TITLE
Template page [#ag-dev-flow]

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6896]
What about adding a template page class? It would do nothing, but serve as a copy paste template. Could speed up [this](https://github.com/sbcgua/abapGit/commit/bb8e484910332249a5711a2eb904f36aa0aeab6b#diff-b9097d827966af7a5fb2cb3adb4bf7b8a2b064eead9c8c2b985900f80e6816fc). Until chat gpt knows abapgit well enough ...

Not critical, just an idea.

**Comment by larshp** [comment]
anywhere under `/test/`, then it will be syntax checked, but not installed in user systems
