### ISSUE TITLE
HTTP 426 error while connecting to git server

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#6900]
We get HTTP error code 426 - Upgrade Required - while connecting to our internal git server (gitlab).
![grafik](https://github.com/abapGit/abapGit/assets/17437789/4fe1dc99-d11b-40ea-b224-0d369058c56f)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426

SSL test program gives the same
![grafik](https://github.com/abapGit/abapGit/assets/17437789/9165c9d9-1a16-40c5-b8be-101ee84612db)

Whereas the same git server works from other SAP systems without problems.
![grafik](https://github.com/abapGit/abapGit/assets/17437789/b87b02d6-6458-4e93-94d1-05692cde652d)

Both systems running latest abapGit.

Any ideas what the root cause could be?

**Comment by pokrakam** [comment]
426 suggests that the server isn't happy with the request coming from SAP. See https://http.dev/426 
My first guess is something got upgraded on your Git server and that particular SAP system is using an older protocol. Have you had a look at SMICM trace? It might tell you a bit more.

**Comment by larshp** [comment]
check the `ssl/*` profile settings, https://docs.abapgit.org/user-guide/setup/ssl-setup.html#sap-system-profile

**Comment by mbtools** [comment]
Good news: 

The answer is in [SAP Note 51007](https://me.sap.com/notes/510007)

Bad news:

The note is about 12 A4 pages of small print

Better news:

Try [SAP Note 3112487](https://me.sap.com/notes/3112487)

**Comment by christianguenter2** [comment]
Thanks to all for your valuable inputs. Got it working with abapGit userexit `http_client`.
```abap
METHOD zif_abapgit_exit~http_client.

  IF iv_url CS 'https://xyz.com'.
    ii_client->request->set_version( if_http_request=>co_protocol_version_1_1 ).
  ENDIF.

ENDMETHOD.
```

Though SSL check still shows 426 because the mentioned exit isn't processed there. I think that's something we should consider.
- [ ] call `zif_abapgit_exit~http_client` in `zabapgit_test_ssl`
- [ ] update documentation  
- [ ] improve error handing, show additional information in case of 426 error

**Comment by mbtools** [comment]
You were quick...

These seem complicated. http 1.1 has been standard since [1997](https://en.wikipedia.org/w/index.php?title=HTTP&section=2#History). It's beyond me why the SAP http client still uses http1.0 as a default. 

We should set the version to 1.1 in AG. This will work in nearly all cases. 

There's only the rare exception that a server refuses 1.1 and insist on http2. However, it doesn't look like ABAP supports this cases for outbound connections. 

I against calling exits in the test program. That confuses. Make http version an input parameter.

**Comment by christianguenter2** [comment]
`It's beyond me why the SAP http client still uses http1.0 as a default.` 
Seems this has changed in recent releases.
`We should set the version to 1.1 in AG. This will work in nearly all cases.`
I didin't dare to do that :-) But let's try.
`I'm against calling exits in the test program. That confuses. Make http version an input parameter.`
Good point. I'll adjust.

**Comment by mbtools** [comment]
Feel the fear and do it anyway 😀

**Comment by mbtools** [comment]
All done 👍
