### ISSUE TITLE
Improve hotkeys architecture

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6907]
Idea: integrate toolbar component and hotkeys. See discussion [here](https://github.com/abapGit/abapGit/pull/6899#discussion_r1555892243)

The final result would look e.g. like this:

```abap
METHOD zif_abapgit_gui_hotkeys~get_hotkey_actions.
  ri_hotkeys = get_main_toolbar->hotkeys( ).
  ri_hotkeys->append( get_2nd_toolbar->hotkeys( ) ).
  ri_hotkeys->add( key = 'x' title = 'Stuff' cmd = 'do-smth' ).
```

So:

- add the possibility to define hotkeys in for toolbar commands
- and then "import" them into hotkeys with one line of code
- and merge with another toolbar keys and directly defined keys
- the `get_hotkey_actions` result should be an object then, not a structure
- ... with a potential extra check e.g. for duplication and maybe some other conveniences

**Comment by mbtools** [comment]
Too much OO  😉 

Why doesn't `toolbar->hotkeys( )` simply return `zif_abapgit_gui_hotkeys=>ty_hotkeys_with_descr`? 

```abap
METHOD zif_abapgit_gui_hotkeys~get_hotkey_actions.
  rt_hotkey_actions = zif_abapgit_gui_menu_provider~get_menu( )->hotkeys( ).
ENDMETHOD.
```

Adding entries remains the same:

https://github.com/abapGit/abapGit/blob/6459b0c067f86ee3633b0463f7f0c0992df9246b/src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap#L978-L982

An additional toolbar would be (I don't think AG has any):

```abap
  INSERT LINES OF 2nd_toolbar( )->hotkeys( ) INTO TABLE rt_hotkey_actions.
```

**Comment by mbtools** [comment]
Included in https://github.com/abapGit/abapGit/pull/6897 👍
