### ISSUE TITLE
ADT: abapGit is not supported in project xxx

### ISSUE THREAD

**Issue by Nuube** [abapGit/abapGit#6911]
I installed zabapgit_standalone programm (on premise S/4 HANA 2210) and used this successfully to pull the abapGit project from GitHub. I now can call ABAPGit with Gui using transaction ZABAPGIT.

I installed the ABAPGit Package in Eclipse as well. 

But when I try to open the ABAPGit Window in Eclipse/ADT I see the error Message  "abapGit is not supported in project xxx"

Any hints what can be done?

**Comment by mbtools** [comment]
The Eclipse plugin is not supported for on-premise systems. You have to use the standalone or dev version (ZABAPGIT).

See also https://github.com/abapGit/abapGit/issues/3141

**Comment by Nuube** [comment]
Thanks. I saw issue #3141 but it was 4 years old and I wondered if there was an update.

**Comment by mbtools** [comment]
Still the same 😃

**Comment by CiozZ** [comment]
Are there any plans to make the Eclipse plugin compatible with the on-prem systems?
I find it very sad to develop ABAP using Eclipse and for each commit to have to use the SAP GUI again..

I successfully used the abapGit Eclipse plugin until 2023 and worked like a charm.
Why is it all of a sudden unavailable for the on-prem systems?

All the best
Florin

**Comment by CiozZ** [comment]
thanks for your quick answer.
how can I support the project? If I knew exactly how I could help, I’d gladly give it a try.

**Comment by poonambk** [comment]
is there any update on eclipse support for abapgit for onpremise?

**Comment by mbtools** [comment]
@poonambk no. it's owned by SAP. we can't help.

https://help.sap.com/docs/btp/sap-business-technology-platform/working-with-abapgit
