### ISSUE TITLE
No option to set default git user details

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#6917]
There is a default Git user (name + email) available in `zcl_abapgit_persistence_user` and in the config XML. 
I'd expect to see it in the Personal Settings config page, but can't find any option anywhere to set this. Not high priority.

**Comment by mbtools** [comment]
AG stores the user/email of the last commit in these fields:

https://github.com/abapGit/abapGit/blob/a18b9c7f810a5ff3b904e2575583021ce851824b/src/ui/routing/zcl_abapgit_services_git.clas.abap#L61-L64

So it become the default for the *next* commit 😃

**Comment by mbtools** [comment]
Might be something for @francisco-milan ?

**Comment by francisco-milan** [comment]
Sure, you can assign this issue to me, I'll be glad to help.

**Comment by mbtools** [comment]
Closed by #6920 (changing authentication popup is seperate issue/pr)
