### ISSUE TITLE
Queries on ABAPGIT Features

### ISSUE THREAD

**Issue by Murthy-ASN** [abapGit/abapGit#6919]
Hi Team,
I am going through the ABAPGIT documentation and have following queries:
1) Can CTS and ABAPGIT be used in parallel ?
2) May I know If ABAPGit supports the OSS Notes implementation ?
3) Is there a location where I can find more information on the "data feature which can move table contents to and from git"

Thanks in advance.

Regards,
Murthy

**Comment by larshp** [comment]
1. yes, use abapGit for development, CTS for deployment. https://community.sap.com/t5/application-development-blog-posts/cts-is-beautiful/ba-p/13477778

2. it does not. Implement the notes in the central development system as normal. abapGit works with offline development, its not really possible to access them outside a real system. Also they dont belong to a custom package. And hopefully its not something that happens often. Plus they are often transported independently

3. https://github.com/abapGit/docs.abapgit.org/issues/220

**Comment by Murthy-ASN** [comment]
Thanks a lot Larshp for this information
