### ISSUE TITLE
Update for local Class not working

### ISSUE THREAD

**Issue by abapsheep** [abapGit/abapGit#6921]
Hi, 
I have noticed that local classes are not updated. 
I have an old version of a class on the system. This class has several local classes. If I now pull a new version from Git in which all local classes have been removed, they are not deleted.

**Comment by pokrakam** [comment]
@abapsheep can you reproduce this on GitHub? 
I tried this with a simple test and it works as expected: 
https://github.com/pokrakam/test6921
Branch `main` has a local class. Then I deleted and committed as `no_local`. You can switch between branches from abapGit and pull and it will create/delete the local class as expected. 
Just to cover all bases I also created branch `manual_delete` where I then went in and manually deleted the `.locals_imp.abap` file and it also behaves correctly.

**Comment by abapsheep** [comment]
Hi @pokrakam, I won't be able to test it until the beginning of next week...

I still had an old installation of https://github.com/abap2UI5/abap2UI5 on the system I assume it was version v.1.20.1. In this version, a class z2ui5_cl_http_handler contains local classes. When I pulled the current version these classes were still present. 
![image](https://github.com/abapGit/abapGit/assets/135960093/145cd30d-8fac-4f12-867d-660f8ec61f49)

**Comment by pokrakam** [comment]
I could reproduce by pulling 1.29.1 into an empty package and then pulling branch `main`. 

However there were many changes with stuff moving to different packages as well and the pull didn't end cleanly. I see this often when the complexity of the changes is just too much. You can see this by the fact that there are still changes visible after the pull. 
In this scenario, you will need to pull again, perhaps several times if it keeps changing, and it may resolve itself. In my tests this worked. 
If repeat pulls don't work, only select a few components to overwrite/recreate at each pull and it should eventually resolve. In some cases it's easier to just delete some of the problem objects and pull again.
