### ISSUE TITLE
ABAP Cloud and 3-tier-extensibility-model support in abapGit

### ISSUE THREAD

**Issue by fabianlupa** [abapGit/abapGit#6928]
Just wondering what the current state of support is. For example for the following use case:

- A software vendor provides a library as an abapGit repository to a customer
- The library has an API, objects are released via C1 release contracts and enabled for use in cloud development
- The customer consumes these APIs in tier 1 (language version = ABAP for Cloud Development)
- The customer is prohibited by the system to consume any unreleased objects (?)
  - Does this require installing the repo to a new custom software component if those unreleased objects are also in tier 1?
- Another library user is on a lower release or doesn't care or isn't able to use the tier model / ABAP Cloud. The user should still be able to consume the objects as normal.

I know the language version support is currently experimental. Are release contracts serialized? And the flags for use in key user apps / cloud development?

Business context: Some customers are investing quite heavily into the 3 tier model for their own developments and are asking external vendors to also support _clean core_ in their products in order for the customer to consume these partner APIs without having to create tier 2 wrappers and ATC exemptions. And also forcing the vendor to have stable APIs in the same turn ;)

**Comment by larshp** [comment]
APIS should work, https://github.com/abapGit-tests/APIS/blob/main/src/zreleasedc1test%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20dtel.apis.xml

**Comment by mbtools** [comment]
The ABAP language Version feature should support this case already (for the objects that have ALaV implemented). 

But I'm not sure about the release contracts. If they are part of the repo? How would they show up in lower releases?

It's probably best to setup a test scenario.

**Comment by larshp** [comment]
APIS are the release contracts AFAIK

**Comment by mbtools** [comment]
AG supports release contracts and ABAP language version (within the limitations of https://github.com/abapGit/abapGit/issues/6689). 

If something doesn't work, please create a new issue with a reproducible test case.
