### ISSUE TITLE
Proposal: Character Limit for "Table" Field in Data Config page

### ISSUE THREAD

**Issue by francisco-milan** [abapGit/abapGit#6933]
Hello abapGit Team,

I am writing to follow up on a proposal I made in issue #6914, which seems to have been overlooked. To recap, I suggested an enhancement for the "Data Config" page: enforcing a 16-character limit on the "Table" field. This change aims to improve user experience and prevent potential errors, as demonstrated in the screenshots included in the original issue.

Here is a brief summary of the proposal:

  -Current Situation: The "Table" field does not have a character limit.
  -Proposed Change: Implement a 16-character limit for the "Table" field.
  -Benefit: This would prevent issues or unexpected behaviour related to overly long table names.

Screenshots illustrating the issue and the proposed solution were included in the original issue #6914.

I would greatly appreciate your thoughts and feedback on this proposal.

Thank you for considering this enhancement. I look forward to your response.

Best regards,

Francisco Milan.

**Comment by larshp** [comment]
go for it
