### ISSUE TITLE
Proxy-authentication does not work in background mode

### ISSUE THREAD

**Issue by ThomasErgin** [abapGit/abapGit#6936]
I want to use the background mode to automatically download the latest version of the ABAPGIT into my system. Therefore I set up my repository as described in [](https://docs.abapgit.org/user-guide/repo-settings/background-mode.html).

When my job is executed, It will issue the message "_Proxy auth failed_" to the spool and stop. However, the simulation of the background mode from the repository settings screen works, since it uses the credentials I previously entered in the proxy authentication popup - and not those that I have configured in the repositories proxy settings.

What I tried so far:
I've added the following line right at the beginning of method ZCL_ABAPGIT_LOGIN_MANAGER->set( )
`    zcl_abapgit_default_auth_info=>set_auth_info( iv_user = iv_username iv_password = iv_password ).`
This should set the credentials according to the repository settings so they can later be accessed by the background mode. 
However, this is not enough: Now the job will issue the message "_Unauthorized access to resource (HTTP 401). Check your credentials_" to the spool. There seems to be another thing missing, that encodes the credentials in a way, that the repository accepts it.

**Comment by mbtools** [comment]
Looks like this is a missing feature. Proxy authentication is done in [`zcl_abapgit_proxy_auth`](https://github.com/abapGit/abapGit/blob/main/src/http/zcl_abapgit_proxy_auth.clas.abap). Doing a popup won't work in background. 

A solution could be to use an RFC connection + [exit](https://docs.abapgit.org/user-guide/reference/exits.html#create-http-client) where you maintain the proxy + proxy authentication.

PS: `zcl_abapgit_default_auth_info` is not part of abapGit so I don't know what that would do.

**Comment by pokrakam** [comment]
The exit as Marc suggested is potentially a better solution anyway as the password is stored securely. 
The only potential downside is that it applies to everyone using abapGit. Not a problem if it's your own developer system or using a company GitHub ID. Or you could use RFC just for the proxy and authenticate manually for any restricted repos.

**Comment by mbtools** [comment]
You could create user-specific RFC destinations like "GITHUB_BERNARD" and map them in the exit accordingly. Not better in terms of security or misuse but it does commit with the correct GH user this way.

**Comment by ThomasErgin** [comment]
Going to try this approach. Thank you for your feedback!
