### ISSUE TITLE
dump lo_hook_impl->get_include_bound where ls_original_object-org_obj_name is deleted

### ISSUE THREAD

**Issue by norman003** [abapGit/abapGit#6938]
![image](https://github.com/abapGit/abapGit/assets/33376952/622fb7fa-8982-43b5-967f-787c62bc2076)

**Comment by larshp** [comment]
hi, are you running the latest version?
should be fixed with https://github.com/abapGit/abapGit/pull/6935 and https://github.com/abapGit/abapGit/pull/6937
