### ISSUE TITLE
get_ui_theme can support lv_frontend_theme CS c_ui_theme-dark. rv_ui_theme = c_ui_theme-dark.

### ISSUE THREAD

**Issue by norman003** [abapGit/abapGit#6939]
dark theme

**Comment by mbtools** [comment]
Like this https://github.com/abapGit/abapGit/pull/6940?

**Comment by mbtools** [comment]
Feel free to create a pull request yourself, next time :-)

Otherwise, please add a longer description so we don't have to guess what you want.
