### ISSUE TITLE
BSP upload problems in public cloud environments

### ISSUE THREAD

**Issue by shinpyeongtaekpower** [abapGit/abapGit#6943]
Hello, I'm trying to upload BSP to Git through abapGit. I committed the development package to Git with abapGit in the Public Cloud environment, but the bsp app doesn't go up. Does anyone know how to upload the bsp app??
As far as I know, the bsp app goes up in WAPA format, but this also doesn't go up. Please help

**Comment by mbtools** [comment]
If it works, it look like [this](https://github.com/abapGit-tests/WAPA_Fiori). Test your system with this repo. Does it work?

**Comment by mbtools** [comment]
No progress. Closing
