### ISSUE TITLE
Push changes to different branch in using abapGit eclipse plugin

### ISSUE THREAD

**Issue by vishnucta** [abapGit/abapGit#6947]
I linked a git repo and have cloned it into the steampunk but i want to push that to a different branch.Already a new branch is created in Git repo and i woould like to switch it in eclipse.

**Comment by mbtools** [comment]
That's really a question for SAP who makes the [plugin](https://help.sap.com/docs/btp/sap-business-technology-platform/working-with-abapgit?locale=en-US)
