### ISSUE TITLE
DSFD: CDS Scalar Function Definition

### ISSUE THREAD

**Issue by fvalves** [abapGit/abapGit#6948]
I will implement the abapGit object handler for DSFD

**Comment by larshp** [comment]
https://github.com/abapGit-tests/DSFD created

**Comment by mbtools** [comment]
We should avoid implementing an abapGit version if an AFF is planned at SAP. I don't see these CDS objects in https://github.com/SAP/abap-file-formats at the moment but this should be coordinated with SAP 

@schneidermic0 Any AFF plans for "DSFD", "DSFI", "DRAS"?

**Comment by schneidermic0** [comment]
For DSFI, there is an ABAP file format defined:
https://github.com/SAP/abap-file-formats/tree/main/file-formats/dsfi

For the others, I need to check it with the colleagues and ask them to add it

**Comment by schneidermic0** [comment]
https://github.com/SAP/abap-file-formats/pull/623

Thanks, @fvalves 👍

**Comment by mbtools** [comment]
Closed by https://github.com/abapGit/abapGit/pull/6951
