### ISSUE TITLE
DSFI: CDS Scalar Function Implementation

### ISSUE THREAD

**Issue by fvalves** [abapGit/abapGit#6949]
I will implement the abapGit object handler for DSFI

**Comment by fvalves** [comment]
@larshp I want to add an elementary test case to https://github.com/abapGit-tests/DSFI but DSFIs can only be created with reference to an existing DSFD. Should add files for both a DSFD and a DSFI object to the src directory?

**Comment by mbtools** [comment]
The testcase is fine as is. Thx

Closed by #6952, #7013
