### ISSUE TITLE
Data Config: cx_sy_sql_error error "A compound error was discovered for token '#'"

### ISSUE THREAD

**Issue by thorsten-wolf-neptune** [abapGit/abapGit#6956]
Changing Data Config: Activating checkbox "Skip initial fields" adds a CarriageReturn sign in WHERE Config leading to a cx_sy_sql_error:
![image](https://github.com/abapGit/abapGit/assets/83953375/bdd19ade-362b-4803-9865-8c86e54bf4bc)
![image](https://github.com/abapGit/abapGit/assets/83953375/87eb930e-be06-4888-9325-11f4f8fd821c)

![image](https://github.com/abapGit/abapGit/assets/83953375/953b0b9a-f104-4a18-a6a0-de63eac68f21)
![image](https://github.com/abapGit/abapGit/assets/83953375/81ceb172-074b-4d65-bd2d-cb75d86c4740)
![image](https://github.com/abapGit/abapGit/assets/83953375/fd8d3fc4-0c96-4cd2-9683-6328173c766e)

I will do further analysis and update this issue once i found the reason for it

Running Developer Edition 1.127.0 and having Chromium as HTML Control

**Comment by larshp** [comment]
maybe a carriage return or newline that needs to be stripped when saving the data?

**Comment by thorsten-wolf-neptune** [comment]
i think i found it. Data is coming in from html control with CR_LF but we split only at \n 
![image](https://github.com/abapGit/abapGit/assets/83953375/78121954-02e6-4241-bf24-a62d99b2a824)
