### ISSUE TITLE
DB Table index include/exclude flag: clear if no DBs specified

### ISSUE THREAD

**Issue by sbcgua** [abapGit/abapGit#6959]
There is one typical diff I experience during deployments between different releases. `DD12V-DBINCLEXCL`. I have a suspicion that it is a bug in older abap releases. Although it does not cause direct issues but in AG it causes diffs. I'm not a big expert in how abap objects are stored so before fixing this would be great to collect some opinions for more experienced.

So the evidences are:

1) a table has in an index. Not limited to any DB

![image](https://github.com/abapGit/abapGit/assets/15635498/b4694b24-be24-4dce-be23-be6223f9611c)

2) Just in case, if I click "For selected" then, inside there is a radio button with "Exclude" option by default. **Yet, the activated setting is "Index on ALL"**

![image](https://github.com/abapGit/abapGit/assets/15635498/2da3d1b8-dc54-4acd-b0f0-e76e65f138e9)

3) And in DD12V the field DBINCLEXCL = 'E' (although it does not do anything). Problem is that in newer releases this field is force cleared on activation (which is more consistent)

![image](https://github.com/abapGit/abapGit/assets/15635498/30d414b7-2a6f-4f52-94f3-ed3f3a7821ba)

Solution idea: on serialization, if DBSTATE is empty, clear DBINCLEXCL 

![image](https://github.com/abapGit/abapGit/assets/15635498/3ec4d740-7279-42ab-8f8f-ecc094becddc)

**Comment by mbtools** [comment]
If DBSTATE is empty or 'O', clear DBINCLEXCL, DBSYSSEL1, DBSYSSEL2, DBSYSSEL3, and DBSYSSEL4.
