### ISSUE TITLE
Small Usability problem when creating new online repo

### ISSUE THREAD

**Issue by DerGuteWolf** [abapGit/abapGit#6968]
When I create a new online repo and I have a already stuff in the package, I arrive on the page with a list of the local objects but have no stage link/button there. I have to go back to the repo list and need to use the stage/button there for the initial stage/commit/push.

Current standalone version

**Comment by mbtools** [comment]
I'm unable to reproduce this with GitHub. "Stage" is available right away. 

What is the git host? What is the state of the repo in your case? Zero files? Some files like README but nothing related to ABAP?

**Comment by DerGuteWolf** [comment]
Git Host ist our company internal gitlab instance. Repo was created with only a README.md which I deleted beforehand, repo is thus empty, but with main branch . Package has content.
See here:
![image](https://github.com/abapGit/abapGit/assets/638512/c500068d-df2d-4778-9238-a9c8600bd436)

I created a short video:
https://github.com/abapGit/abapGit/assets/638512/d8e94421-8ebb-441e-b53d-639789592d1e

**Comment by mbtools** [comment]
See #6981

**Comment by DerGuteWolf** [comment]
Thanks!
