### ISSUE TITLE
Creating a repository with objects in a namespace containing the '/' character makes the links to the objects non-functional

### ISSUE THREAD

**Issue by BartekSAP** [abapGit/abapGit#6988]
While creating offline repo with objects in package which already exists on the system, it is not possible to enter any object in '/SGD/' or '/RTC/' namespace. 
We are preparing ABAPGIT to import some external solution to our system and are worried that it will not create objects on the system correctly if it cannot handle '/' character.
Did anyone encountered a similar issue and knows how to fix it? 
ABAPGIT standalone version: 1.129.0

Thank you in advance.

![Screenshot 2024-07-17 092526](https://github.com/user-attachments/assets/61109a70-1fea-4f94-a1e0-3fa648fad329)

**Comment by mbtools** [comment]
There are several projects using namespaces and it certainly works with AG. 

This looks like a bug in generating the link. I will check it later today.

**Comment by mbtools** [comment]
You can also test with https://github.com/abapGit-tests/NSPC. Check if this deserializes properly in your system and the links work.

**Comment by BartekSAP** [comment]
Hello,

Unfortunately, I am not authorized to create new namespaces in the system. However, as mentioned in the original post, we have many other namespaces with the '/' character, and ABAPGIT is also not working for them. On the other hand, it has no problem with the 'Z' namespace. It is clear that the '/' character is causing the issue here.

**Comment by mbtools** [comment]
I tested again and can't reproduce the issue (latest, 1.129.0). I was able to create an offline repo for package `/ASU/TOOLS`. All objects are listed properly and you can click to view them. Export to zip works. 

![saplogon_a1HTQX9Jxa](https://github.com/user-attachments/assets/4e1586af-7603-464b-a9da-087786a7d660)

[#ASU#TOOLS_20240720_211524.zip](https://github.com/user-attachments/files/16322742/ASU.TOOLS_20240720_211524.zip)

I also tested with the test repo mentioned above. Created a corresponding offline repo. Export to zip works. Deleted everything. Import and Pull as zip works as well (one minor warning).

![saplogon_aBPp3hWqTL](https://github.com/user-attachments/assets/82975d03-7c2d-4430-b01c-c32c4e43bd3c)

[#LIBDEMO#MAIN_20240720_204921.zip](https://github.com/user-attachments/files/16322812/LIBDEMO.MAIN_20240720_204921.zip)

We will need more details from you to figure out what's not working... i.e. a reproducible example/steps.

PS: Since `/asu/tools` is an SAP package, I set the [allow_sap_objects exit](https://docs.abapgit.org/user-guide/reference/exits.html#allow-sap-objects) to true.

**Comment by BartekSAP** [comment]
Could you please specify what kind of details do you need?

Regarding reproducing all the steps we're taking, we've created a new report ZABAPGIT_STANDALONE and pasted code from this location:
https://raw.githubusercontent.com/abapGit/build/main/zabapgit_standalone.prog.abap

After that, we triggered this report and pressed "New Offline" button:
![image](https://github.com/user-attachments/assets/74b2b305-cb25-4357-9ab7-d8d4b7e7faf9)

We've put a name of the repo, picked a package using search help and pressed "Create Offline Repo". 
![image](https://github.com/user-attachments/assets/545d53a6-2e79-4e52-a689-051c59da49b2)

Creation was successful:
![image](https://github.com/user-attachments/assets/a9b649d9-1565-451d-9ea7-88abadba8375)

But the link still does not work:
![image](https://github.com/user-attachments/assets/79747bfa-6df4-472b-80d6-0a91d1240d61)

Inside debugger I can see that OBJ_NAME is incorrectly created:
![image](https://github.com/user-attachments/assets/5807ea7f-6075-4b2c-9494-3978c6de5d04)

If I can provide any more details, please let me know

**Comment by mbtools** [comment]
I see you're using Edge browser control. Works for me with SAP GUI 8.0 patch 8. Which version of SAP GUI are you using?

![image](https://github.com/user-attachments/assets/9858f4d0-3043-4803-8266-18d0058ed43b)

![image](https://github.com/user-attachments/assets/6b5c0106-2482-43fe-a5f7-b2a5520ce9d3)

**Comment by BartekSAP** [comment]
![image](https://github.com/user-attachments/assets/e1f0bb58-48b7-411e-bff8-1f453f982da1)
Do you think logon version might be an issue here?

**Comment by mbtools** [comment]
1. Test if it works when switching to "Internet Explorer" as browser control
2. Upgrade SAPGUI to patch 3.1 or 4 or higher ([AG docs](https://docs.abapgit.org/user-guide/setup/sapgui.html#sap-gui-for-windows)) and test again with "Edge" browser control

**Comment by BartekSAP** [comment]
Sorry for the late response, but it took some time for my organization to upgrade SAP GUI to higher patch level. But I finally got it:
![image](https://github.com/user-attachments/assets/00697be2-90db-4580-abcd-0d1b1e7b5397)

Now it's much better. Many objects (like tables, domains, data types, transactions) I'm testing are now accessible, but some of them still don't. 
In example classes, programs or function groups. When I try to open them, at first I can see this pop-up:
![image](https://github.com/user-attachments/assets/5042490f-d45e-47b6-ae78-0944ffa03011)

And after clicking "Allow", I get something like this:
![image](https://github.com/user-attachments/assets/85f63079-d9c4-4826-85ac-a787291d975c)

Could you please help me with this last topic?

**Comment by BartekSAP** [comment]
Oh, now everything works as it should! Thank you for your assisstance, this topic may be closed.

**Comment by mbtools** [comment]
@christianguenter2 Can you add those ADT steps to the doc, please?
