### ISSUE TITLE
Unable to find Some function groups SAP in the local repository

### ISSUE THREAD

**Issue by gggdddrink** [abapGit/abapGit#6989]
The local repository I created for the package in the picture below：
![Snipaste_2024-07-19_16-45-41](https://github.com/user-attachments/assets/61e7a06d-6b2d-45cc-a549-1fa4dc1926ca)
This package has six function groups, I have annotated two function groups in the following image：
![Snipaste_2024-07-19_16-46-22](https://github.com/user-attachments/assets/56d2f2a9-1c3f-4c44-a80e-93a1193a3326)
Unable to find  the two function groups in the local repository
![Snipaste_2024-07-19_16-45-14](https://github.com/user-attachments/assets/ee24ca5d-0ad6-4e14-9eed-89afd81f4302)
May I ask how I can solve this problem？

**Comment by larshp** [comment]
Are these function groups generated for change documents? in that case they are filtered out,

![image](https://github.com/user-attachments/assets/8b30eb77-7192-40d3-bcd3-ba595090cea9)

**Comment by mbtools** [comment]
Based on the names of the function modules, these are indeed generated functions for change documents. They are not serialized and will be generated automatically when importing the repo somewhere else. Closing
