### ISSUE TITLE
AFF unit tests failing in dev edition 2022

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#6990]
looks like invalid constructor parameters,

https://github.com/abapGit/abapGit/pull/6986#issuecomment-2242515088

![image](https://github.com/user-attachments/assets/2310c20d-60ad-4729-a012-1dc3991ccc83)

![image](https://github.com/user-attachments/assets/abe68e24-52d3-4eb1-908f-78bf920b3a47)

**Comment by albertmink** [comment]
Initially, the AFF framework has been shipped without ABAP-Language-Version support. Nowadays there is one. That is the good news 😅

**Comment by larshp** [comment]
still a problem
