### ISSUE TITLE
Certain Objects not Fully Synchronized

### ISSUE THREAD

**Issue by cawoodmonads** [abapGit/abapGit#7001]
When pushing a package from one system to another we are noticing that changes are not fully synched. In fact we can just keep pulling and it constantly shows a list of 5 objects:
![image](https://github.com/user-attachments/assets/aa413d02-0605-496d-a735-b597ab97dc32)

When we look at the diff we see that it is the description of the class in english which is not being synchronized. This is the diff when we try to push back from the target system:
![image](https://github.com/user-attachments/assets/176a7701-6546-47a9-b7b6-1908b75464a2)
It shows, in effect, that the target system (on the left) does not have the following:

```xml
   <DESCRIPTIONS_CLASS>
    <SEOCLASSTX>
     <LANGU>E</LANGU>
     <DESCRIPT>Fehlerklasse</DESCRIPT>
    </SEOCLASSTX>
   </DESCRIPTIONS_CLASS>
```

No matter how many times we pull into the target system it always wants to pull the same objects as it notices they are different:

![image](https://github.com/user-attachments/assets/410287df-c79e-4514-b8c4-ef0e120e3158)

Function Group:
![image](https://github.com/user-attachments/assets/05d0459f-2f9a-4b2f-bf5c-c4431c7aedd2)

In the case of the TOBJ Object it seems like the description of a table is not being transferred:
![image](https://github.com/user-attachments/assets/9c77de82-0924-4e6a-a19f-61d8c1cd39b5)

One possible explanation is that we moved the table ZPMR_DATE from a package ZPMR_DATE_SRV which is in the Repo to a package ZPMR_DATE_SRV_DB which isn't. It seems SAP did not move the TOBJ correctly across:
![image](https://github.com/user-attachments/assets/1fe4de3b-34cc-4aef-85a9-762a701f6dc5)

**Comment by cawoodmonads** [comment]
I noticed that after and upgraded both ABAPGIT_STANDALONE reports. We are still seeing the endless pull cycle constantly showing diffs:

![image](https://github.com/user-attachments/assets/1034b31b-883e-492b-9dc9-a5b9fc72232c)

**Comment by larshp** [comment]
okay, try reproducing in a public repository, and open two separate issues one for DSYS and one for CLAS.

DSYS: it might have a bug, dont think theres many people using it

CLAS: can be a translation issue. Personally I recommend doing all development in English, and not translate technical descriptions (only translate stuff that affects possible business users)

**Comment by mbtools** [comment]
DSYS: abapGit keeps the version history of the object. If the object was changed in the target system (more times than in the source), then there will be diffs.

CLAS: I tested with https://github.com/abapGit-tests/CLAS branch "german" and there are not diffs. Please provide a reproducible example repo.
