### ISSUE TITLE
WebDynpro: Staged objects are not in line with SAP transport-locks

### ISSUE THREAD

**Issue by Chr1stoph-B** [abapGit/abapGit#7006]
Hey everyone,

I came across the following problem:
When making changes in two different WDY views within the same WDY component, I can lock those two objects on different transports. However, when staging these differences, it is not possible to differentiate between those changes, because I can only commit the whole component (one object), rather than view by view. The same behavior holds for the component controller etc.

This makes developing in bigger applications really difficult, since one is not able to work on two different tasks within the same component at the same time, while committing them at different points in time.

Is there a reason for this behavior and more important: may it be improved?

Thanks in advance &
all the best
Christoph

**Comment by larshp** [comment]
yea.. suggest

A: scope changes so there is only one ongoing change to an object, this applies for all object types
B: work on increasing the turnaround time for changes, so objects are "in progress" for shorter time
C: use the patch function to only commit the relevant changes

abapGit serializes objects on object level, there is the same problem for eg. classes. Keep the changes small, scope properly, increase turnaround then its not a problem IMHO, plus it will have a positive impact on delivering changes to business users

**Comment by mbtools** [comment]
It's a limitation of the current WebDynpro serializer which puts all of its parts into a single XML file. It's certainly possible to rewrite this to have separate files per view, for example (similar to files per function module in a function group). But who has time for this...?
