### ISSUE TITLE
SAP GUI for Java 8.10 beta: rendering weirdness

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abapGit/abapGit#7016]
As [documented](https://me.sap.com/notes/3485691), this new beta version incorporates the following changes to the HTML component:

- JxBrowser, the browser component used in the Html-Control, has been updated to 7.39.2.
- The html control has been modernised to use Chromium instead of WebKit as the browser engine

This leads to the following weird rendering of the repository view in aG:
![beta](https://github.com/user-attachments/assets/b17f42b9-29df-41b7-abed-b1b8ab81e3ff)

By comparison the previously release version 7.80 rev 6 behaves normally:
![stable](https://github.com/user-attachments/assets/2219de2b-eecc-4cae-abc7-9aadc362cc47)

In case anyone else is in the beta program and wishes to try it, please also be aware that the source code editor [must be manually patched](https://me.sap.com/notes/3450882).

Logging the issue mostly for documentation and for a heads up, not sure something is actually wrong in aG.

**Comment by mbtools** [comment]
Looks like injecting the CSS file isn't working. SAP will have to fix it.

**Comment by AndreaBorgia-Abo** [comment]
beta 2 still has this issue (again, purely for documentation)

**Comment by AndreaBorgia-Abo** [comment]
through the grapevine I heard that this issue has been recorded internally at SAP :)

**Comment by AndreaBorgia-Abo** [comment]
beta 3 still affected

**Comment by AndreaBorgia-Abo** [comment]
Good news, the rc2 version seems to be working fine, even commit works as expected :)
![image](https://github.com/user-attachments/assets/bb1acb6e-25d3-4388-924d-bdcb4ea257f3)
