### ISSUE TITLE
FORM with language not in system results in unhandled exception

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#7018]
The two character ISO code is used for the filename. If some of the less common languages are not installed, the code is not found and the filename is generated as `zformname.form.tdlines_.xml`. Multiple of these crash with an unhandled exception.

Add check: if language isn't found we should just ignore it as we can't be sure that we can handle it properly. PR in the works.

**Comment by pokrakam** [comment]
...and I found PR #7017 , pulled, tested, fixed :-)
Leaving this issue open until merged.

**Comment by mbtools** [comment]
should work now
