### ISSUE TITLE
Mismatched function group includes are not serialized

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#7021]
If a developer uses an include that doesn't follow the include naming convention, it is not serialized.
![image](https://github.com/user-attachments/assets/5f240982-aa32-4cca-a606-17d6f5f0921d)

abapGit serializes:
![image](https://github.com/user-attachments/assets/79a7bfa7-9f52-457b-825a-49701237344d)

In the real use case, the developer used Form includes from another FG. Not good, but not sure how else this should be handled other than serializing every include specified in the function group's main program as part of the Function Group.

PS. Eclipse manages this better by only asking for the suffix when naming the include...

**Comment by mbtools** [comment]
The include should not be serialized as part of the function group but it should be listed as a separate PROG object (if it's included in the repo package). Is it not?

**Comment by pokrakam** [comment]
Hmm, In the test I did, yes, but in the real-world case not. It's complicated: the developer included form routines from another FUGR which was subsequently deleted but the includes remained. 
ZFUGR1 -include-> ZFUGRF01
ZFUGR2 -include-> ZFUGRF01

Then ZFUGR1 was deleted but the include remained and is missing from abapGit. It is related to #7020 and most likely a related cause.

**Comment by mbtools** [comment]
It's certainly bad practice to use this kind of includes in multiple places. I guess that there was a warning when deleting ZFUGR1 saying that an include was used somewhere else. Since it was a FUGR include, it doesn't have the PROG tadir entry. That's not an AG problem. Edit the include and check "object entry". You should be able to create one from there (and it should ask for transport).

**Comment by pokrakam** [comment]
It's certainly bad practice. I am not in a position to edit this particular case, but since it now has been spotted in the wild we should cater for it in any case.

It's not an AG fault as such, but it does result in code missing from the repo without any warning or error of any sorts. 
It should be either as a standalone include or as part of the FUGR. I will investigate which is the most feasible, ideally within the FUGR.

**Comment by mbtools** [comment]
What happens if you try to transport this function group? If the include `zfoofgtest` is in the transport, AG should also serialize it. If it's not, then AG should raise a warning or error pointing to the fact that there's an include with a TADIR entry.

**Comment by pokrakam** [comment]
Unfortunately I have limited access so can't test this. I just noticed that the Git dump was missing a few files and abapGit is the only thing I'm allowed to work with. It's a little deprioritised at the moment but I'll get to it in due course, probably next week.

**Comment by pokrakam** [comment]
Finally managed to debug this on the system where I spotted it. It is in fact serialized but then incorrectly discarded, PR on way.
