### ISSUE TITLE
Move ZIF_APACK_MANIFEST out of abapGit

### ISSUE THREAD

**Issue by kjetil-kilhavn** [abapGit/abapGit#7023]
The user guide (https://docs.abapgit.org/user-guide/reference/apack.html#apack-in-namespaces) describes two ways of handling the syntax errors that arise as a result of importing open source projects which implement ZIF_APACK_MANIFEST. 

Would it not be easier for "everyone" if ZIF_APACK_MANIFEST is moved to a separate repository?
Then we can transport the interface without getting a warning from abapGit that the object exists in another package.

**Comment by sbcgua** [comment]
+1
It's super intransparent when the interface is created and then has to be manually added to transport after dumps in further systems. This process should be more accountable.

**Comment by mbtools** [comment]
I don't think anything stops you from creating a repo that contains just `ZIF_APACK_MANIFEST`. You can then import this repo before any other APACK solution. The only issues would be a change to the interface within AG but that's quite unlikely.

**Comment by kjetil-kilhavn** [comment]
I could do that @mbtools, but as I mention I will then get a warning from abapGit every time it is synced that the object exists in another package. Unless abapGit checks if the other package belongs to another abapGit project and then suppresses the message if the object is identical (no diff). I didn't even think of that possibility before, but is abapGit really that clever?

**Comment by mbtools** [comment]
There are different scenarios:

1. You create repos based on APACK and reference `zif_apack_manifest` in your code

You can rely on AG to generate `zif_apack_manifest` in all your systems (dev + any target). This means the interface is in `$tmp` everywhere. Or you move the interface in a transportable package and deploy it to target systems. This could be via transport or AG. The interface could be part of a "base repo" that you deploy everywhere before importing any other APACK-based repos.  

In all these cases, `zif_abapgit_apack` should be in at most one repo and you should not get any warnings.

2. You import an APACK repo containing `zif_apack_manifest`

Here you might get warnings. If the imported repo uses a namespace, encourage them to switch to a corresponding interface in the namespace. This will avoid the warning. If it has to stick with `zif_abapgit_apack`, encourage them to move the interface to a separate repo or remove it altogether.

3. Hack AG 

Sure we can adjust the AG code as you suggested. However, this would be in some way "hide the truth" which I'm not a big fan of. But feel free to submit a PR so we can have something concrete to test and discuss.

**Comment by mbtools** [comment]
If it's still an issue, feel free to re-open with more details.
