### ISSUE TITLE
VIEW: `tddat` entries not saved to transport

### ISSUE THREAD

**Issue by abap-weasel** [abapGit/abapGit#7033]
We updated abapgit to latest and noticed new DIFFS from #6918.
While content of TDDAT is properly serialized/deserialized/deleted etc it is not saved to transport request, therefore cannot be moved to QA/PROD.

**Comment by mbtools** [comment]
good point. `delete_extra` and `update_extra` need a call to `zcl_abapgit_factory=>get_cts_api( )->insert_transport_object`.

Would you like to give it a try with a PR?

**Comment by mbtools** [comment]
Please test with #7042
