### ISSUE TITLE
PROG: Pull fails with Splitter Control dynpros

### ISSUE THREAD

**Issue by zenrosadira** [abapGit/abapGit#7034]
Hello,
when I try to import a report that contains a dynpro of type “[Splitter Control](https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-US/abendynp_splitter_control_spcl.htm)” I get the following error during pull: 
![image](https://github.com/user-attachments/assets/b779efbe-2cd8-4e7c-876c-f75582daac68)

The report used in the test is a copy of the standard report "DEMO_DYNPRO_SPLITTER_CONTROL".

This is error message XI110 raised by function RPY_DYNPRO_INSERT called during the attempt to de-serialize the dynpro.

Can dynpro of this type be supported? 

Thank you

**Comment by larshp** [comment]
@zenrosadira thanks, can you help trying to make a public example so the issue can be reproduced?

**Comment by zenrosadira** [comment]
This is a minimal example: [https://github.com/zenrosadira/abapGit-test-splitter](https://github.com/zenrosadira/abapGit-test-splitter)

**Comment by christianguenter2** [comment]
Seems like a shortcoming of `RPY_DYNPRO_INSERT`
![image](https://github.com/user-attachments/assets/96856760-cdca-42d8-a07b-a996d8be4200)

**Comment by larshp** [comment]
is the TYPE missing missing? I guess this is just a normal custom container? What happens if creating a new screen with this stuff from scratch?

Sometimes old stuff, and the dynpro editor messes up stuff, I try to add extra consistency checks in https://rules.abaplint.org/dynpro_checks/

**Comment by fabianlupa** [comment]
> I guess this is just a normal custom container?
I think we are talking about the splitter control the "new debugger" for example uses to split subscreens next to each other. This is different from the splitter control available as a control in the control framework which can only split controls of the control framework itself but no subscreens. You can only create and edit dynpros with the classic splitter control using the old list-based screen paint, not the "new" screen painter.

**Comment by larshp** [comment]
> > I guess this is just a normal custom container?
> 
> I think we are talking about the splitter control the "new debugger" for example uses to split subscreens next to each other. This is different from the splitter control available as a control in the control framework which can only split controls of the control framework itself but no subscreens. You can only create and edit dynpros with the classic splitter control using the old list-based screen painter, not the "new" screen painter.

whuuut is this magic? 🤪

**Comment by mbtools** [comment]
Please test #7035. You need to serialize the original program again since the format changed for these dynpros.

**Comment by zenrosadira** [comment]
> Please test #7035. You need to serialize the original program again since the format changed for these dynpros.

Tests passed.
I tried with splitter control dynpros defined in an executable program, in a module pool, and in a function group: it worked in all cases. Thanks

**Comment by mbtools** [comment]
@zenrosadira the PR was also changing the XML for some dynpros that did not contain a splitter. 

Could you please test that it still works properly with https://github.com/abapGit/abapGit/pull/7038?

**Comment by mbtools** [comment]
Thank you!
