### ISSUE TITLE
SAP GTT implementation // package created for SAP GTT cannot be uninstalled

### ISSUE THREAD

**Issue by VitaliT78** [abapGit/abapGit#7044]
Hi everybody,

we downloaded SAP sample coding for SAP GTT and tried to install and fix the bugs. 
However, we need to uninstall it and get the issue with the AVAS objects.
You can reproduce this issue by doing following steps.
1. TC: SE38 -> ZABAPGIT_STANDALONE
2. Execute
3. Select and click on GTT_Code
4. Select "Advanced”.
5. Click on "Uninstall”.
6. Error message will be displayed
_"AVAS invalid data//Deletion of object .... failed"_
best regards
Vitali

**Comment by mbtools** [comment]
What's the url for the repo?

**Comment by VitaliT78** [comment]
Do you mean this one?
https://github.com/SAP-samples/logistics-business-network-gtt-standardapps-samples

**Comment by mbtools** [comment]
I can't test this since it requires full ERP or S4HANA which I don't have access to. 

AVAS install and uninstall in general works fine. Please test with https://github.com/abapGit-tests/AVAS. 

Try to reduce the issue to a minimal example repo (without ERP). Then I can help.

**Comment by crees01** [comment]
Hi mbtools,

I am also working with Vitali together on this problem. Could you explain me how I could reduce this example or what exactly I should do?

You could check the following PDF:

https://drive.google.com/file/d/1cEB3q7I1tI1en_8Q-6jJ6UATuqfanUvs/view?usp=sharing

After UNINSTALL there are 11 objects remaining. When I go to SE80 all packages are still there, but when I click to delete some object in the package the message is shown that it does not exist. Also I could not delete the package itself.

Is there a possibility to delete those 11 objects manually or in SE80 to delete the whole package?

**Comment by mbtools** [comment]
Packages:

Transportable packages can't be deleted in one step. First all objects have to be deleted and the  corresponding transport has to be released. Then you can delete the empty packages (in abapGit or SE80). 

AVAS:

This needs further investigation. Can you create a repo with just one of these tables and AVAS objects and try to reproduce the issue with this?

**Comment by mbtools** [comment]
Do you need more help?

**Comment by VitaliT78** [comment]
Hi,
thanks a lot for the valuable input. We solved that issue.
regards
Vitali
