### ISSUE TITLE
PROG: Pull fails with Splitter Control subscreen

### ISSUE THREAD

**Issue by zenrosadira** [abapGit/abapGit#7049]
Sorry, but I missed a case where issue [#7034](https://github.com/abapGit/abapGit/issues/7034) comes up again.

When a splitter control is defined *in a subscreen*, abapGit fails to serialize and deserialize it correctly: [here](https://github.com/zenrosadira/abapGit-test-splitter-sub) you can find a public repo having this issue.

The "normal" dynpro case was fixed by [#7035](https://github.com/abapGit/abapGit/pull/7035), where splitters are managed with a condition like `IF ls_dynpro-header-type = 'N'`, could it be sufficient to extend these conditions including `header-type = 'I'` for subscreens ?

Thank you

**Comment by mbtools** [comment]
Yes, you can add type=I. But check if fill=X is the same check for the splitter.

https://github.com/abapGit/abapGit/blob/b86a1d89244173c5b9a48416ea19d0f2d6fac4b7/src/objects/zcl_abapgit_objects_program.clas.abap#L856-L857

**Comment by mbtools** [comment]
The repo doesn't work since it's not serialized correctly. I have a hard time reproducing it with the old screen painter. Can you attach screenshots of SE51 and these subscreens? Or attach a transport with the program?

**Comment by zenrosadira** [comment]
You can upload each screen from this archive: [zdemo_splitter_subscreen.zip](https://github.com/user-attachments/files/17593931/zdemo_splitter_subscreen.zip)
The repo is just a copy of standard demo program "DEMO_DYNPRO_SPLITTER_CONTROL", where screen "100" (that one containing the splitter) is marked as "subscreen" instead of "normal" screen type, therefore I added a normal screen ("200") that includes screen 100 as subscreen.

**Comment by mbtools** [comment]
Thank you! That helped. I included the fix in #7066
