### ISSUE TITLE
Upgrading to the latest build

### ISSUE THREAD

**Issue by zayidu** [abapGit/abapGit#7054]
Hello,

Copied and Pasted the latest build from: https://[raw.githubusercontent.com/abapGit/build/main/zabapgit_standalone.prog.abap](https://raw.githubusercontent.com/abapGit/build/main/zabapgit_standalone.prog.abap) in the existing 'zabapgit_standalone' in SE38, unfortuantely having an error 'Implementation missing for method "ZIF_ABAPGIT_EXIT~CHANGE_MAX_PARALLEL_PROCESSES".' despite activating individually.

Motive: Trying to upgrade to the latest build to track CDS DDLS files saved under packages, exisitng build doesn't show the CDS files in a package.

Could you please help ?
![image](https://github.com/user-attachments/assets/4b6bf88b-9f3d-4c60-8d01-e9e04cc70a9a)

**Comment by larshp** [comment]
I see it in the report, check if you have a global or local exit class implemented, possibly include `zabapgit_user_exit`

![image](https://github.com/user-attachments/assets/1be3fac7-0689-497c-9bb3-5cc6c2b250bb)

**Comment by zayidu** [comment]
Thanks for your reply @larshp .
After adding the below lines of code in the ZABAPGIT_USER_EXIT implemementation part, it works fine. Thanks a lot.

`
CLASS zcl_abapgit_user_exit IMPLEMENTATION.
METHOD zif_abapgit_exit~change_proxy_authentication.

  ENDMETHOD.
  METHOD zif_abapgit_exit~VALIDATE_BEFORE_PUSH.

  ENDMETHOD.
  METHOD zif_abapgit_exit~ENHANCE_REPO_TOOLBAR.

  ENDMETHOD.

  METHOD zif_abapgit_exit~change_max_parallel_processes.

  ENDMETHOD.
  METHOD zif_abapgit_exit~CHANGE_SUPPORTED_DATA_OBJECTS.

  ENDMETHOD.
  METHOD zif_abapgit_exit~CHANGE_RFC_SERVER_GROUP.

  ENDMETHOD.
  METHOD zif_abapgit_exit~CHANGE_SUPPORTED_OBJECT_TYPES.

  ENDMETHOD.
  METHOD zif_abapgit_exit~DETERMINE_TRANSPORT_REQUEST.

  ENDMETHOD.`
