### ISSUE TITLE
Track cds files

### ISSUE THREAD

**Issue by zayidu** [abapGit/abapGit#7055]
Hello Experts,

Updated to the latest build, I am trying to track CDS changes done in eclipse.
I couldn't see any CDS objects which is saved under a package in staging when using ZABAPGIT, Could you please advise on tracking CDS ? or any other tools?

Thanks in advance.

**Comment by larshp** [comment]
CDS views? yea, they are supported

**Comment by larshp** [comment]
click refresh to see changes, and note that abapGit serializes the active version

**Comment by zayidu** [comment]
@larshp : yes, the cds views/Data definitions files those created in eclipse, I could see in SE80 under packages, all those files created under the sub-packages of the package called ZMM are there, but when ZBAPGIT is used and when I see the changes in ZMM packaage, there isn't any trace of CDS views that are there under sub packages of ZMM.

I could see files like CLAS, FUGR, ENHO, SSFO as mentioned in https://docs.abapgit.org/user-guide/reference/supported.html
but not DDLS files.

Is there any setting that I miss ?
Below is the repo settings:
![image](https://github.com/user-attachments/assets/1e9bb43d-89b0-4fe2-ad56-def27122e787)

**Comment by larshp** [comment]
well, usually its not a problem at all

but as discovered in https://github.com/abapGit/abapGit/issues/7054, first check your exits, perhaps disable them to test if they are interferring

**Comment by zayidu** [comment]
Perfecto. Added DDLS to the below method. WORKED. Thanks @larshp 

METHOD zif_abapgit_exit~change_tadir.
    DELETE ct_tadir WHERE object NOT IN VALUE isu_ranges_tab( sign = rs_c_range_sign-including option = rs_c_range_opt-equal :
   ( low = 'CLAS' )
    ( low = 'FUGR' )
    ( low = 'FUNC' )
    ( low = 'FUGS' )
    ( low = 'FUGX' )
    ( low = 'PROG' )
    ( low = 'DEVC' ) 
 **( low = 'DDLS' )**
).

**Comment by larshp** [comment]
you can choose to do the above in the exit, but please make sure to check it internally. The exits are powerful, and in your case it is implemented so the developer does not see the full picture of the package

**Comment by zayidu** [comment]
Thanks for the info.

**Comment by mbtools** [comment]
This exit implementation is very dangerous and could have unintended side effects. Instead of the exit, it's better to use the "ignore" setting in a repo to exclude files you don't want in the repository.

**Comment by zayidu** [comment]
@mbtools You mean to use .gitignore?

**Comment by mbtools** [comment]
abapGit does not use gitignore. But there's a setting in .abapGit.xml for the same:

https://docs.abapgit.org/user-guide/repo-settings/dot-abapgit.html#ignore-files

**Comment by zayidu** [comment]
Thanks @mbtools , will look into it. Good day!
