### ISSUE TITLE
ZIF_ABAPGIT_BACKGROUND  implementations are NOT called due to local/global class accessibility

### ISSUE THREAD

**Issue by gardian12** [abapGit/abapGit#7057]
Implementations of interface ZIF_ABAPGIT_BACKGROUND do NOT run properly, while using developer and standalone version of abapGit in parallel.

This forces an CX_SY_CREATE_OBJECT_ERROR exception.

![image](https://github.com/user-attachments/assets/0abf14d8-0e3d-4324-a7c7-6af4badb156d)
![image](https://github.com/user-attachments/assets/b2e53b9a-a471-4e65-9682-110991272546)

A pull request will follow soon, which fixes the problem and also enhances the auto determination capabilities of the interface implementation.

**Comment by mbtools** [comment]
An additional problem are passing the repo and log instances to a global class. That won't work either. 

Thanks for the PR. I will try it tomorrow.
