### ISSUE TITLE
src/objects/oo/zcl_abapgit_oo_class.clas.abap deserialize_source BUG?

### ISSUE THREAD

**Issue by niuniuch** [abapGit/abapGit#7061]
Hi,

I'm looking at the implementation of zif_abapgit_oo_object_fnc~deserialize_source and I can't help but notice, that parameter it_source passed to update_full_class_include at line 778 contains the source code of the last method, or the private section if no methods exist.

Not sure what impact this has, since appartenly everything works, but I can't see any scenarios where generating an include with a random piece of code makes any sense.

Or am I wrong?

kind regards,
Jacek

**Comment by niuniuch** [comment]
Sorry, I'm just dumb :D

**Comment by mbtools** [comment]
No worry. It happens to all of us when looking at code for too long. 😉
