### ISSUE TITLE
Indices transferred wrong from ERP to S4

### ISSUE THREAD

**Issue by mabek** [abapGit/abapGit#7098]
We are moving code from an ERP instance to an S4 instance using abapgit.
However we are running into problems moving indices like these:

![image](https://github.com/user-attachments/assets/b7726cf9-420b-4e8c-b5d4-6fc26df9936a)

When importing this table including the indices to S4 an error message appears like "Indices on buffers only for buffered tables" (paraphrased). Somehow during the transfer the checkmark "only for table buffer" is checked.

My workaround is currently in ZCL_ABAPGIT_OBJECT_TABL -> DESERIALIZE_INDEXES line 54. If the current system is HANA to skip the creation of the index.

**Comment by mabek** [comment]
Sure, its message DT309 sorry for the german " Index 300 definiert auf Tabellenpuffer aber Tabelle ist nicht gepuffert
Meldungsnr."  

Triggered in program RADIXCHK line 2994 include RADIXCHK form CHK_INDX_ON_TABL_BUFFER.

For all entries in DD12L Dbstate went from "D" to "O".
![Bildschirmfoto 2024-12-08 um 16 47 57](https://github.com/user-attachments/assets/64589455-dd8b-4fbb-a720-0979a19fe354)

**Comment by mbtools** [comment]
I had the feeling that it's not an AG problem... Please try this https://me.sap.com/notes/3485302

**Comment by mabek** [comment]
Thanks a lot for the hint!
Turns out the note is only for extension indices and my customer created all the indices not as extension indices, hence I still get the error message. 

I will have to keep my workaround even though it is not a fault of Abapgit :-)

**Comment by mbtools** [comment]
Or open a ticket with SAP to get it fixed for regular indexes
