### ISSUE TITLE
702: Activation error 

### ISSUE THREAD

**Issue by mbtools** [abapGit/abapGit#7103]
![image](https://github.com/user-attachments/assets/b56e057f-b247-4006-a033-21e5bb802e8e)

![image](https://github.com/user-attachments/assets/3acd711b-e624-4f83-bb59-6d0e90901970)

Some special char at the end of this mime.

**Comment by larshp** [comment]
hmm

**Comment by mbtools** [comment]
Guess I edited it with external tool in [https://github.com/abapGit/abapGit/pull/5980]. oh well
