### ISSUE TITLE
AOBJ	Archiving Object

### ISSUE THREAD

**Issue by larshp** [abapGit/abapGit#804]
Database table: ARCH_OBJ + other?

define via transaction AOBJ

function modules:
ARCHIVE_OBJECT_GET
ARCHIVE_OBJECT_CREATE
ARCHIVE_OBJECT_DELETE
ARCHIVE_OBJECT_STRUCTURE_SET
function group ARGN

**Comment by larshp** [comment]
if anyone wants to make a PR, this looks like a quite easy task

just add a comment here if somebody starts working on it

**Comment by bigld** [comment]
I'll do this at the weekend

**Comment by mbtools** [comment]
@bigld do you have a custom archive object that you could add to https://github.com/abapGit-tests/AOBJ.git for testing?

Thanks!

**Comment by xtough** [comment]
Hi @mbtools and @larshp ,
Sorry for throwing a spanner in the works. But SAP is currently also working on an AOBJ handler for abapGit, however with a JSON-based format based on AFF (see https://github.com/SAP/abap-file-formats ). We should avoid creating 2 incompatible formats that would need to be aligned afterwards. At least we should discuss the options. What do you think?
Thanks, Christoph

**Comment by mbtools** [comment]
@xtough I'm not clear about the release compatibility of AFF. Will the JSON version also work with all lower releases supported by abapGit? >=702

**Comment by xtough** [comment]
@mbtools I see your point. There is no easy answer to that. Please bear with me for a few more days until I had a chance to talk to some colleagues that are currently on vacation.

**Comment by xtough** [comment]
Hi @mbtools ,
sorry for the late response. The short answer is "yes", it is possible to use JSON based metadata also lower releases like 702, as shown recently with the experimental handler for INTF in #5658 . A handler just has to support the format as described in AFF, but does not necessarily have to depend on the AFF framework, which is obviously only available in newer releases. This even makes it possible to reuse the type interfaces like https://github.com/SAP/abap-file-formats/blob/main/file-formats/aobj/type/zif_aff_aobj_v1.intf.abap for AOBJ. Of course, the JSON-based format proposal for AOBJ currently focused on cloud features but missing older features can be added incrementally in a compatible way.
Cheers, Christoph

**Comment by mbtools** [comment]
To implement this object type, create a PR or reopen this issue for further discussion.
