### ISSUE TITLE
Namespace automated import of objects

### ISSUE THREAD

**Issue by geert-janklaps** [abapGit/abapGit#835]
When creating projects in namespaces it would be nice to be able to store the namespace (flat text) and the namespace repair license (encrypted) into the .abapgit.xml.

When importing the repository into a customer system abapGit should then be able to do following things automatically:
- Create / Update namespace (Table TRNSPACE)
- Decrypt repair license
- Insert the decrypted repair license
- Switch the namespace to modifiable
- Import the objects
- Switch the namespace to not modifiable
- Remove the repair license

This is a nice to have off course, but would really simplify the import of new versions at customer side. (Without intervention of the people/company who developed the solution and without leaving the repair license in the customer system)

**Comment by larshp** [comment]
yeah

what are your thoughts on encryption? I have implemented DES, see https://github.com/larshp/abapNTLM/blob/master/src/zcl_des.clas.abap which is symmetric. There is also https://github.com/Sumu-Ning/AES which is stronger but it will introduce a project dependency if using this feature.

**Comment by Gekke-Jakke** [comment]
I think DES should be enough, the main idea about the encryption is that the repair license is not readable for regular users. (Just to prevent that the license can be copy-pasted, so introducing a dependency would be overkill)

Three other things I would also include would be:
- In the producer system (TRNSPACE-ROLE = P) when commiting changes to the repository, automatically extract the namespace data and repair license
- Extract namespace(s) based on objects in the repository (It might be that multiple namespaces are used in one package. Chance of this happening would be really small I guess, but might be better to foresee this logic right away)
- Namespace(s) should only be changed if the system in which the data is imported is not a producer system for the namespace(s) imported

I would like to help introduce this new feature, but have still need to do a debugging session in the project to understand the main abapGit logic / structure. Any suggestions on a starting point? (e.g. some technical documentation available somewhere?)

**Comment by larshp** [comment]
technical doc: no. I would like to add more structure to the abapGit code, but it requires https://github.com/larshp/abapGit/issues/773

**Comment by larshp** [comment]
also hopefully https://github.com/Sirius-A/abap-doc-export can be used in the future to provide more technical documentation

**Comment by Gekke-Jakke** [comment]
Sounds great! I'll try to dive into the project and have a look at how we can fit in above features.

**Comment by larshp** [comment]
cool, suggest implementing this in small steps, dont worry about breaking stuff, we break and fix things fast
 😄

**Comment by Gekke-Jakke** [comment]
I definitely agree with implementing these requirements in small steps! Had a debugging session yesterday and think I have an idea on where we can export the namespaces to the XML file.

I'll have to move attached code block after the TADIR loop and add the namespaces before serializing the .abapgit.xml file.

![image](https://user-images.githubusercontent.com/2744548/28352526-3ce4e484-6c57-11e7-94af-c52c19a8f8d2.png)

First step I had in mind was to just export the namespace data to the XML file. (next step will be importing them)

**Comment by larshp** [comment]
The user has to manually create the package before being able to clone the repository.

Regarding encryption, at some point in time the real key would be registered in the system, so the encryption is just a false sense of security?

**Comment by larshp** [comment]
Repair license: is to avoid customers changing the code, however with git its quite easy to tell if the customer changed something.

**Comment by ypcyc** [comment]
I've never created custom namespaces so when I wanted to import objects with custom namespace I couldn't understand why I was getting error. If this feature is still on hold, can you make some check if custom namespace does exist in the system and then if not, inform user that objects can't be imported?

**Comment by mbtools** [comment]
3 part solution coming up:

- [ ] Warning, if namespace does not exist locally
- [ ] Object class for namespaces (will serialize and update namespaces, but does *not* create them)
- [ ] Automatic creation of namespaces, if they do not exist

Repair license will be unencrypted since it's a) required to create objects and b) visible in table `trnspace` during any process which would create/update objects. 

Auto-create based on the serialized namespace will take a bit longer since some refactoring of `zcl_abapgit_objects=>deserialize` will be required, first.

**Comment by mbtools** [comment]
Closing this. The only thing missing will be handled via #4505
