### ISSUE TITLE
Super package with subpackages that have there own development

### ISSUE THREAD

**Issue by vtebano13** [abapGit/abapGit#952]
I can't seem to find out how to do this or if it is even a possible option.  I have a super package that has objects on it.  The super also has sub packages under it.  I was trying to make a repo that has the super and its objects without the sub packages.  Then create the sub packages as there own repos from which I would include them into the super.  The reason for this is when a dev mods a sub package object I do not want the super to get a change against it.  It should be against the sub package.  It will also copy less objects back and forth when someone is working on a sub package.

So is this available? and if so how would you do it?

**Comment by larshp** [comment]
hi,
there is field `ignore_subpackages`, see https://github.com/larshp/abapGit/blob/e75fab654ddc2633af1fb61f3bd134b9e54f2a6f/src/zabapgit_persistence.prog.abap#L117 note that this is not part of the .abapgit.xml file, and so far the feature is not documented, and you have to use the database tool to enable it

**Comment by vtebano13** [comment]
Great!  Thanks.  Saw the abapGit at TechEd and it is awesome.  Great job.

**Comment by larshp** [comment]
so this is implemented, but a few things to be fixed:
* add this as part of the repo settings
* document the feature

**Comment by vtebano13** [comment]
I got the ignore_subpackages working.  I added the submodule and know when the I refresh the super package I get Error: Unknown chmod.  Looking into it to see where it is coming from.

**Comment by larshp** [comment]
will you be using git submodules? not sure it works with abapGit, never tried, see https://github.com/larshp/abapGit/issues/27

**Comment by vtebano13** [comment]
How else would you link a sub package in the super?

**Comment by larshp** [comment]
was thinking you would have separate repos installed, linked to the super via the package structure, and not linked in git.

it all depends on what requirements you have for the setup. But, as of now, submodules does not work inside abapGit, I have reopened #27

**Comment by flaiker** [comment]
There's also git subtree. Not sure if that helps.

**Comment by vtebano13** [comment]
I will check subtree out.  Thanks

**Comment by larshp** [comment]
I've never tried subtrees in git, and this is also not implemented in abapGit

**Comment by vtebano13** [comment]
lol,  I guess I will just separate out the packages.

**Comment by larshp** [comment]
yeah, hopefully we will get there someday 😄

**Comment by flaiker** [comment]
subtree _shouldn't need_ abapGit support if I remember correctly. Of course you would have to pull in changes of the subprojects using CLI outside of SAP and commit those pulls each time...
But I'd also recommend going for one repository per main package / project. Not sure I quite understand how your package hierarchy looks like.

**Comment by larshp** [comment]
(repeating issue status):

so this is implemented, but a few things to be fixed:

* add this as part of the repo settings
* document the feature

**Comment by mbtools** [comment]
Part of settings and documented for a while now:
https://docs.abapgit.org/ref-dot-abapgit.html#ignore-sub-packages
