### ISSUE TITLE
Proposals for release engineering

### ISSUE THREAD

**Issue by jfilak** [abapGit/abapGit#960]
Could you please tag the release commits? So, I will be able to check out the tag branches - that would help me to stick to a certain version.

Could you please release new versions adding support for new object types without adding that object types? For example, I cannot pull the latest master because DEVC is not yet supported.

**Comment by larshp** [comment]
tags: hmm, I'm very lazy, need to find some easy way to do it

DEVC: suggest installing the latest build via https://raw.githubusercontent.com/larshp/abapGit/build/zabapgit.abap it will be very difficult to introduce new features while maintaining compatibility with old versions

**Comment by flaiker** [comment]
Just adding the tags will not do it as you cannot check them out in abapGit yet (unless I missed tag support being implemented). Currently it would only work with branches, which seems weird having one for each release forever.
Regarding the DEVC pull: the solution would be an incremental update (pull support for devc and then abapGit's own DEVC objects in a later pull). Which I don't think is possible yet either.

As a workaround one could add a branch each time object support is added for an object type that is also later used by abapGit itself. Then you could manually switch to the "support" branch, pull the support that way and then checkout master again with the now supported objects.

**Comment by jfilak** [comment]
> Just adding the tags will not do it as you cannot check them out in abapGit yet ...

Correct. I didn't realize that before posting my proposal. So adding a support for tags would be great. If only I had more free time :)

> Just adding the tags will not do it as you cannot check them out in abapGit yet ...

Did so.

Commit https://github.com/larshp/abapGit/commit/f76050e71a675c532685401746db724e3674cc22#diff-0ec321afe5ecb8718d66390cab044b31 caused me some problems too.

@larshp  what do you mean by "test"? :)

**Comment by larshp** [comment]
sorry, bad commit description

what problems did it cause, any error messages?

**Comment by jfilak** [comment]
> what problems did it cause, any error messages?

The commit includes a file in a subpacakge that didn't exist yet. I created the subpackage manually to get rid of the issue. It was just an inconvenience while upgrading.

**Comment by larshp** [comment]
This issue is getting closer to reality now that @christianguenter2 implemented lightweight tags, will have to do some testing, and perhaps some supporting tools/scripts

**Comment by larshp** [comment]
Okay, let's open this discussion again 😄 

Some links:
https://nvie.com/posts/a-successful-git-branching-model/
https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/
https://trunkbaseddevelopment.com/

I like the story about the cactus model 🌵

**Comment by larshp** [comment]
**Suggestion: Master and release branch**

All features are merged(rebased/squashed) to the `master` branch.
The changes to `master` will regulary be synced to the `release` branch.

Assumptions:
ZIF_ABAPGIT_DEFINITIONS in `master` branch contains version = "latest"
ZIF_ABAPGIT_DEFINITIONS in `release` branch contains version = "v$OLD"

Release process:
1: Manual step to determine the new version number($NEW)
2: Manual update of the changelog(in `master` branch)
3: Merge/rebase all commits from `master` to `release` branch
4: Update ZIF_ABAPGIT_DEFINITIONS to "v$NEW" and push to `release` branch(perhaps move the version to a different file to avoid merge conflicts)
5: Create lightweight tag
6: The tag will trigger travis CI which will store the release somewhere(https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A)
Suggest automating step 3 + 4 + 5 with a ABAP program

Notes:
+ Default release schedule: every 2 weeks, and ad-hoc in case of hotfixes
+ Hotfixes can be made in the `release` branch
+ Possibility for user to select abapGit version when installing via the tutorial link, plus guide the user on how to upgrade
+ Make sure the news/changelog popup still works

**Comment by christianguenter2** [comment]
@larshp 
Where do you see the self containing abapGit report (latest build) in this picture? I guess it is build from the release branch? Or still from master?

**Comment by larshp** [comment]
latest build: both the master branch and release branch

Perhaps https://github.com/abapGit/releases storing the releases branch and https://github.com/abapGit/latest for the master branch, or mirror the branches in the builds repo

**Comment by christianguenter2** [comment]
What I don't understand yet, what are the benefits of a separat release branch? Especially compared to creating release tags on master?

**Comment by larshp** [comment]
* the version in ZIF_ABAPGIT_VERSION will be correct
* it will be easier to do hotfixes, if needed

**Comment by jfilak** [comment]
You don't need to crate a new brach - the branch can be created at any time when needed. `git checkout` works fine even with tags.

**Comment by larshp** [comment]
hmm, yeah

I would like to have abapGit show the right version number, eg. if "1.100.0" has been released, and a pull request is merged, currenlty abapGit will still show "1.100.0" even though it is not exactly that version, but I guess this can also be solved by some code in abapGit(for online repositories)

**Comment by larshp** [comment]
If there is a need to do a hotfix, then a branch is created from master? And tagged, this would mean that the branch would exist forever? And there will be a branch for each future hotfix? Or alternatively the git history has to be rewritten?

**Comment by jfilak** [comment]
Aha, when a tag exits, it is not possible to create a branch with the same name. I apologize for confusing you. There is no such a thing as 'tagged branch'.

I opened this ticket because deploy abapGit from an online repository. I ran into problems because use the version from master's HEAD. I thought it would be nice to be able to upgrade abapGit by switching to a tag. However, I have just learned that a tag has a bit different behavior than I though, so now I know I want to switch to a branch and not a tag.

The strategy of gtk - very long running project  - is to create tags with version "M.m.H" and branches "gtk-M.m".

**Comment by jfilak** [comment]
By the way, I work this way. I have a local for in out enterprise github. I clone the upstream abapgit, the I push the upstream abapgit int a corresponding branch in the local fork. When I log it to all the system with abapgit, I can easily switch between versions by changing branches.

However, I believe tags would work for me as well if we had a branch for someprefix-Major.minor and tags for frozen versions. In production systems, I would rather use tags because branches are still on the move :)

**Comment by jfilak** [comment]
Some progressive projects like Cockpit and Systemd do not use branches because they release often and they count on package maintainers.

Kubernetes uses a strategy similar to gtk.

Do you plan to offer a long term support for a certain version of abapGit (hell, yes, there should be a company that runs business on it)? Because right now, it looks more like you release early and often. And for such a strategy, branches are a bit overkill.

**Comment by larshp** [comment]
Thoughts:
* Release a new version at least every 2 weeks
* Hotfixes for only the latest version
* No long term support, but some versions might prove to be more stable than others. abapGit is a tool used in connection with development, so it is more important to provide features than stability.

**Comment by JohannesKonings** [comment]
Here is a example how Prometheus do releases: https://github.com/prometheus/prometheus/wiki/HOWTO-cut-a-new-release

**Comment by larshp** [comment]
we've not really done any hotfixes since abapGit was released, so perhaps just skip this part for now

so just something easy is needed, changelog can be updated manually, suggest writing a small script(command line or ABAP?) that does:
1: update the zif_abapgit_version
2: creates the tag
3: attaches the compiled/abapmerge'd file to the release(can probably be done automatially on travis)
4: adds the version in the changelog
5: opens a PR for the above, where possible

**Comment by sbcgua** [comment]
:+1: 
Just one question: how it will be triggered ? imho as an option, the travis script can check if the version changed in zif_abapgit_version (which is done manually) then do the rest from the list

**Comment by larshp** [comment]
closing, no progress
